Repository opf/openproject, pull requests merged in 2018-02, with the labels that each got.

#6167 [27088] Pagination is broken in some edge cases
  frontend/app/components/table-pagination/table-pagination.component.ts
Labels: bugfix

#6172 Refactor custom actions admin table to cell
  app/cells/custom_actions/row_cell.rb
  app/cells/custom_actions/table_cell.rb
  app/helpers/application_helper.rb
  app/views/custom_actions/index.html.erb
Labels: housekeeping

#6173 Extract upsale into a common template
  app/assets/stylesheets/content/_enterprise.sass
  app/controllers/custom_actions_controller.rb
  app/views/common/upsale.html.erb
  app/views/custom_actions/enterprise_token.html.erb
  config/locales/en.yml
  spec/controllers/custom_actions_controller_spec.rb
Labels: housekeeping

#6168 [26955] Improved distribution of available width for column width distribution
  frontend/app/components/wp-fast-table/builders/modes/hierarchy/single-hierarchy-row-builder.ts
Labels: bugfix, needs-review

#6176 version bump for RxJS and ReactiveStates
  frontend/app/components/states.service.ts
  frontend/app/components/wp-fast-table/state/wp-table-base.service.ts
  frontend/app/components/wp-table/wp-table.directive.ts
  frontend/npm-shrinkwrap.json
  frontend/package.json
Labels: housekeeping

#6181 [27097] Cannot navigate to project on mobile (Safari on iOS) (2)
  frontend/app/components/projects/project-menu-autocomplete/project-menu-autocomplete.component.ts
Labels: bugfix, needs-review

#6165 [27102] Main menu color not changed on activity page
  app/controllers/activities_controller.rb
Labels: bugfix, styling

#6183 user default time zone setting
  app/cells/settings/time_zone_setting_cell.rb
  app/cells/views/settings/time_zone_setting/show.erb
  app/models/user.rb
  app/models/user_preference.rb
  app/views/settings/_display.html.erb
  app/views/users/_preferences.html.erb
  config/locales/en.yml
  config/settings.yml
  spec/models/users/default_timezone_spec.rb
Labels: feature, needs-review

#6182 [27161] Custom actions: Dropdown arrow missing for "Please select" in MS Edge
  frontend/app/components/common/hide-section/add-section-dropdown/add-section-dropdown.component.html
Labels: bugfix, styling

#6190 [27231] Different font sizes in CF
  app/assets/stylesheets/content/work_packages/inplace_editing/_edit_fields.sass
Labels: bugfix, styling

#6191 [27230] Fix restricting the rev only to lowercase tags
  config/routes.rb
  spec/routing/repositories_routing_spec.rb
Labels: bugfix

#6188 [27158] No paragraphs in work package description
  app/assets/stylesheets/content/work_packages/inplace_editing/_edit_fields.sass
Labels: bugfix, styling

#6192 [27233] Edit mode of boolean CF is not cancelable
  frontend/app/components/wp-edit/field-types/wp-edit-boolean-field.directive.html
Labels: bugfix

#6189 [27090] Increase width of custom field "Text" attribute fields
  app/assets/stylesheets/content/work_packages/inplace_editing/_edit_fields.sass
  frontend/app/components/work-packages/wp-single-view/wp-single-view.html
Labels: styling

#6195 [24960] Fix routing to js file in repository results in JS format
  config/routes.rb
  spec/routing/repositories_routing_spec.rb
Labels: bugfix

#6193 Bump test-prof to re-use their let_it_be shared_let replacement
  Gemfile
  Gemfile.lock
  spec/requests/api/v3/work_packages/form/work_package_form_resource_spec.rb
  spec/support/shared_let.rb
Labels: housekeeping
