Repository opf/openproject, pull requests merged in 2018-04, with the labels that each got.

#6248 Update typescript to 2.8.
  frontend/app/components/table-pagination/pagination-service.ts
  frontend/app/components/wp-table/timeline/cells/timeline-cell-renderer.ts
  frontend/npm-shrinkwrap.json
  frontend/package.json
Labels: housekeeping

#6232 [27329] Layout: Remove footer and move menu toggle to right border
  app/assets/stylesheets/layout/_base.sass
  app/assets/stylesheets/layout/_base_mobile.sass
  app/assets/stylesheets/layout/_footer.sass
  app/assets/stylesheets/layout/_index.sass
  app/assets/stylesheets/layout/_main_menu.sass
  app/assets/stylesheets/layout/_main_menu_mobile.sass
  app/assets/stylesheets/layout/_top_menu.sass
  app/assets/stylesheets/layout/_top_menu_mobile.sass
  app/assets/stylesheets/layout/_work_package_mobile.sass
  app/assets/stylesheets/layout/_work_package_table.sass
  app/assets/stylesheets/openproject/_mixins.sass
  app/views/homescreen/blocks/_community.html.erb
  app/views/layouts/base.html.erb
  config/locales/en.yml
  lib/open_project/design.rb
  lib/open_project/static/links.rb
  lib/redmine/menu_manager/top_menu/help_menu.rb
Labels: needs-review

#6228 Move crowdin CSP into separate helper to override CSP at runtime
  app/helpers/crowdin_helper.rb
  app/views/layouts/base.html.erb
  config/initializers/secure_headers.rb
Labels: housekeeping

#6254 [27427] Breadcrumb missing in Admin/Custom Actions area
  app/controllers/custom_actions_controller.rb
Labels: bugfix, styling

#6256 [27430] Avoid hover effects on disabled buttons
  app/assets/stylesheets/layout/_drop_down.sass
Labels: bugfix, styling

#6253 [27425] Breadcrumb misplaced in FF
  app/assets/stylesheets/layout/_breadcrumb.sass
  app/helpers/breadcrumb_helper.rb
Labels: bugfix, styling

#6265 [27460] WP context menu misplaced when opened via keyboard
  frontend/app/components/op-context-menu/op-context-menu-handler.ts
Labels: accessibility, bugfix

#6262 Fix: project search
  frontend/app/components/common/autocomplete/lazyloaded/lazyloaded-autocompleter.ts
  frontend/app/components/projects/project-menu-autocomplete/project-menu-autocomplete.component.ts
  spec/features/projects/project_autocomplete_spec.rb
Labels: bugfix, needs-review

#6261 [27454] Bugs in WP table modal
  app/assets/stylesheets/content/_modal.sass
Labels: bugfix, styling

#6270 Misplaced WP breadcrumb (FF)
  app/assets/stylesheets/layout/_breadcrumb.sass
  frontend/app/components/work-packages/wp-breadcrumb/wp-breadcrumb.html
Labels: bugfix, styling

#6266 [27461] Disabled menu items are not disabled for screenreader
  config/locales/js-en.yml
  frontend/app/components/op-context-menu/op-context-menu.html
  frontend/app/components/wp-table/table-actions/actions/context-menu-table-action.ts
Labels: accessibility, bugfix

#6276 Bump ckeditor to stable v10.0.0
  .codeclimate.yml
  app/assets/javascripts/vendor/ckeditor/ckeditor.js
  app/assets/javascripts/vendor/ckeditor/ckeditor.js.map
  app/views/projects/form/_project_attributes.html.erb
  frontend/app/components/ckeditor/op-ckeditor-form.component.ts
  frontend/app/components/work-packages/wp-editor-field/wp-editor-field.component.ts
  frontend/app/components/wp-edit/field-types/wp-edit-wiki-textarea-field.module.ts
  frontend/ckeditor/ckeditor.ts
  frontend/ckeditor/plugins/op-image-upload/op-image-upload.ts
  frontend/ckeditor/plugins/op-image-upload/op-upload-adadpter.ts
  frontend/ckeditor/postcss.config.js
  frontend/ckeditor/tsconfig.json
  lib/open_project/text_formatting/formatters/markdown/helper.rb
Labels: bugfix, housekeeping

#6283 [27510] Make overlay a little darker to better focus on the introduction tour
  app/assets/stylesheets/content/_modal.sass
Labels: styling

#6281 [27580] Load query on AfterViewInit so that input has bound
  frontend/app/components/wp-table/embedded/wp-embedded-table.component.ts
  frontend/app/components/wp-table/embedded/wp-embedded-table.html
Labels: bugfix
