Repository opf/openproject, pull requests merged in 2018-11, with the labels that each got.

#6802 [28885] Improve html title consistency when navigating to queries
  frontend/src/app/components/routing/wp-list/wp-list.component.ts
  spec/features/work_packages/navigation_spec.rb
  spec/support/components/html_title.rb
Labels: bugfix, feature

#6799 [28765] Fix paragraphs in lists in CKEditor
  app/assets/javascripts/vendor/ckeditor/ckeditor.js
  app/assets/javascripts/vendor/ckeditor/ckeditor.js.map
  spec/features/wysiwyg/paragraphs_in_lists_spec.rb
Labels: bugfix, needs-review

#6803 [28670] Use WP update service for bulk updating
  app/controllers/work_packages/bulk_controller.rb
  spec/controllers/work_packages/bulk_controller_spec.rb
Labels: bugfix

#6800 [28754] Fix initial one-time rendering when element is not wide enough
  frontend/src/app/components/wp-table/timeline/container/wp-timeline-container.directive.ts
Labels: bugfix

#6805 Bump angular to 7.0.2, CLI to 7.0.4, TS to 3.1.6
  frontend/npm-shrinkwrap.json
  frontend/package.json
Labels: housekeeping

#6806 [28828] Implement regexp-based suffix lookup for mail addresses
  app/models/user.rb
  config/settings.yml
  docs/configuration/incoming-emails.md
  spec/models/user_spec.rb
  spec_legacy/functional/repositories_git_controller_spec.rb
  spec_legacy/functional/repositories_subversion_controller_spec.rb
Labels: feature

#6808 Add inline-buttons element styles
  app/assets/stylesheets/content/_forms.lsg
  app/assets/stylesheets/content/_forms.sass
Labels: styling

#6812 [28656] Open attachments in new tab
  frontend/src/app/components/attachments/attachment-list/attachment-list-item.html
Labels: feature

#6811 [28902] Don't fail hard on missing CF date
  app/models/custom_actions/actions/strategies/date.rb
Labels: bugfix

#6810 Fix untested regression not correctly setting assignee filter
  frontend/src/app/components/user/current-user.service.ts
  frontend/src/app/components/wp-edit-form/work-package-filter-values.ts
  frontend/src/app/components/wp-inline-create/wp-inline-create.component.ts
  frontend/src/app/components/wp-new/wp-create.controller.ts
  frontend/src/app/modules/hal/services/hal-resource.service.ts
  spec/features/attachments/attachments_spec.rb
  spec/features/work_packages/table/queries/me_filter_spec.rb
Labels: bugfix

#6813 Use flash info
  app/controllers/my_controller.rb
  spec/controllers/my_controller_spec.rb
Labels: bugfix

#6819 Improve layout for user notification functionality
  app/assets/javascripts/admin_users.js
  app/views/users/_form.html.erb
  app/views/users/_general.html.erb
Labels: styling

#6807 Allow to refresh a work package blocked by 409 conflict
  config/locales/js-en.yml
  frontend/src/app/components/work-packages/work-package-cache.service.ts
  frontend/src/app/components/wp-edit-form/work-package-changeset.ts
  frontend/src/app/components/wp-edit-form/work-package-edit-form.ts
  frontend/src/app/components/wp-edit/wp-edit-field/wp-edit-field.component.ts
  frontend/src/app/components/wp-edit/wp-notification.service.ts
  frontend/src/app/modules/fields/edit/edit-field.component.ts
Labels: feature

#6809 [27607] Implement parent selection in wp breadcrumb, drop subject
  app/assets/stylesheets/layout/_breadcrumb.sass
  config/locales/js-en.yml
  frontend/src/app/angular4-modules.ts
  frontend/src/app/components/work-packages/wp-breadcrumb/wp-breadcrumb-parent.component.ts
  frontend/src/app/components/work-packages/wp-breadcrumb/wp-breadcrumb-parent.html
  frontend/src/app/components/work-packages/wp-breadcrumb/wp-breadcrumb.component.ts
  frontend/src/app/components/work-packages/wp-breadcrumb/wp-breadcrumb.html
  frontend/src/app/components/work-packages/wp-breadcrumb/wp-breadcrumb.sass
  frontend/src/app/components/work-packages/wp-relations-count/wp-relations-count.component.ts
  frontend/src/app/components/wp-relations/wp-relation-add-child/wp-inline-add-existing-child.component.html
  frontend/src/app/components/wp-relations/wp-relations-create/wp-relations-autocomplete/wp-relations-autocomplete.upgraded.component.ts
  frontend/src/app/components/wp-relations/wp-relations-create/wp-relations-autocomplete/wp-relations-autocomplete.upgraded.html
  frontend/src/app/components/wp-relations/wp-relations-hierarchy/wp-relations-hierarchy.template.html
  frontend/src/app/components/wp-relations/wp-relations-parent/wp-relations-parent.component.ts
  frontend/src/app/components/wp-relations/wp-relations-parent/wp-relations-parent.html
  spec/features/work_packages/details/relations/hierarchy_spec.rb
  spec/support/components/work_packages/relations.rb
Labels: feature, needs-review

#6821 Adjust wiki headlines
  app/assets/stylesheets/content/_wiki.sass
Labels: styling

#6774 [28712] Application not responsive for a particular screen size
  app/assets/stylesheets/content/_calendar.sass
  app/assets/stylesheets/content/_custom_actions.sass
  app/assets/stylesheets/content/_editable_toolbar.sass
  app/assets/stylesheets/content/_forms.sass
  app/assets/stylesheets/content/_forms_mobile.sass
  app/assets/stylesheets/content/_modal.sass
  app/assets/stylesheets/content/_news.sass
  app/assets/stylesheets/content/_notifications.sass
  app/assets/stylesheets/content/_tables.sass
  app/assets/stylesheets/content/_tabs.sass
  app/assets/stylesheets/content/_types_form_configuration.sass
  app/assets/stylesheets/content/work_packages/_table_configuration_modal.sass
  app/assets/stylesheets/content/work_packages/fullscreen/_back_button.sass
  app/assets/stylesheets/content/work_packages/single_view/_single_view.sass
  app/assets/stylesheets/layout/_base.sass
  app/assets/stylesheets/layout/_base_mobile.sass
  app/assets/stylesheets/layout/_breadcrumb.sass
  app/assets/stylesheets/layout/_main_menu.sass
  app/assets/stylesheets/layout/_toolbar.sass
  app/assets/stylesheets/layout/_toolbar_mobile.sass
  app/assets/stylesheets/layout/_top_menu.sass
  app/assets/stylesheets/layout/work_packages/_full_view.sass
  app/assets/stylesheets/layout/work_packages/_mobile.sass
  app/assets/stylesheets/layout/work_packages/_query_menu.sass
  app/assets/stylesheets/layout/work_packages/_table.sass
  app/assets/stylesheets/openproject/_mixins.sass
  app/views/news/index.html.erb
  app/views/repositories/stats.html.erb
  app/views/settings/_repositories.html.erb
  config/locales/en.yml
Labels: feature, work in progress

#6829 [29019] Ensure query-props are correctly encoded
  frontend/src/app/components/routing/ui-router.config.ts
  frontend/src/app/components/wp-single-view-tabs/overview-tab/overview-tab.component.ts
  spec/features/work_packages/table/queries/subject_filter_spec.rb
Labels: bugfix

#6831 [29027] Remove absolute layout of work package page
  app/assets/stylesheets/content/_notifications.sass
  app/assets/stylesheets/content/_work_packages.sass
  app/assets/stylesheets/content/work_packages/details/_safari_flexbug_workaround.sass
  app/assets/stylesheets/content/work_packages/fullscreen/_back_button.sass
  app/assets/stylesheets/content/work_packages/inplace_editing/_textareas.sass
  app/assets/stylesheets/content/work_packages/new/_overridden_description_wiki.sass
  app/assets/stylesheets/content/work_packages/single_view/_single_view.sass
  app/assets/stylesheets/layout/_base.sass
  app/assets/stylesheets/layout/_base_mobile.sass
  app/assets/stylesheets/layout/_breadcrumb.sass
  app/assets/stylesheets/layout/_main_menu.sass
  app/assets/stylesheets/layout/_print.sass
  app/assets/stylesheets/layout/_toolbar_mobile.sass
  app/assets/stylesheets/layout/_top_menu.sass
  app/assets/stylesheets/layout/_top_menu_mobile.sass
  app/assets/stylesheets/layout/_zen_mode.sass
  app/assets/stylesheets/layout/work_packages/_full_view.sass
  app/assets/stylesheets/layout/work_packages/_mobile.sass
  app/assets/stylesheets/layout/work_packages/_print.sass
  app/assets/stylesheets/layout/work_packages/_table.sass
Labels: housekeeping, needs-review, styling

#6839 [29053] Fix copying wiki attachments
  app/models/project/copy.rb
  spec/features/projects/copy_spec.rb
Labels: bugfix

#6842 [29056] Fix drag&drop of folders on attachment component
  frontend/src/app/components/attachments/attachments-upload/attachments-upload.component.ts
  frontend/src/app/modules/common/openproject-common.module.ts
Labels: bugfix

#6845 [28960] Max width for main menu
  frontend/src/app/components/resizer/main-menu-toggle.service.ts
Labels: styling

#6844 [29054] Fix webhooks all_projects usage
  modules/webhooks/app/cells/webhooks/outgoing/webhooks/row_cell.rb
  modules/webhooks/app/models/webhooks/webhook.rb
  modules/webhooks/app/workers/work_package_webhook_job.rb
  modules/webhooks/lib/open_project/webhooks/event_resources/work_package.rb
  modules/webhooks/spec/models/webhook_spec.rb
  modules/webhooks/spec/workers/work_package_webhook_job.rb
Labels: bugfix

#6848 [29049] Fix missing start-of-week without user_specific_includes
  app/helpers/application_helper.rb
  app/views/layouts/base.html.erb
  frontend/src/app/init-globals.ts
  frontend/src/app/modules/common/i18n/i18n.service.ts
  frontend/src/test/i18n-shim.ts
Labels: bugfix

#6849 [28958] Saving cost reports not working on Laptop-sized screens
  modules/reporting/app/views/cost_reports/index.html.erb
  modules/reporting_engine/lib/assets/stylesheets/reporting_engine/reporting.css.erb
  modules/reporting_engine/lib/widget/settings.rb
Labels: bugfix, needs-review, styling

#6850 Bump factory-bot and fix static attributes deprecation
  Gemfile.lock
  modules/avatars/spec/factories/avatar_attachment_factory.rb
  modules/backlogs/spec/factories/impediment_factory.rb
  modules/backlogs/spec/factories/sprint_factory.rb
  modules/backlogs/spec/factories/story_factory.rb
  modules/backlogs/spec/factories/task_factory.rb
  modules/costs/spec/factories/cost_entry_factory.rb
  modules/costs/spec/factories/cost_object_factory.rb
  modules/costs/spec/factories/cost_rate_factory.rb
  modules/costs/spec/factories/cost_type_factory.rb
  modules/costs/spec/factories/default_hourly_rate_factory.rb
  modules/costs/spec/factories/hourly_rate_factory.rb
  modules/costs/spec/factories/labor_budget_item_factory.rb
  modules/costs/spec/factories/material_budget_item_factory.rb
  modules/costs/spec/factories/rate_factory.rb
  modules/costs/spec/factories/variable_cost_object_factory.rb
  modules/ldap_groups/spec/factories/synchronized_group_factory.rb
  modules/meeting/spec/factories/meeting_journal_factory.rb
  modules/pdf_export/spec/factories/export_card_configuration_factory.rb
  modules/reporting/spec/factories/cost_query_factory.rb
  modules/two_factor_authentication/spec/factories/two_factor_authentication_device_factory.rb
  modules/webhooks/spec/factories/webhook_factory.rb
  modules/webhooks/spec/factories/webhook_log_factory.rb
  spec/factories/announcement_factory.rb
  spec/factories/attachment_factory.rb
  spec/factories/attribute_help_text_factory.rb
  spec/factories/auth_source_factory.rb
  spec/factories/changeset_factory.rb
  spec/factories/color_factory.rb
  spec/factories/custom_field_factory.rb
  spec/factories/custom_value_factory.rb
  spec/factories/design_color_factory.rb
  spec/factories/enumerations_factory.rb
  spec/factories/file_factory.rb
  spec/factories/issue_priority_factory.rb
  spec/factories/journal/wiki_content_journal_factory.rb
  spec/factories/journal_factory.rb
  spec/factories/menu_item_factory.rb
  spec/factories/principal_factory.rb
  spec/factories/project_factory.rb
  spec/factories/query_factory.rb
  spec/factories/relation_factory.rb
  spec/factories/repository_factory.rb
  spec/factories/role_factory.rb
  spec/factories/status_factory.rb
  spec/factories/time_entry_factory.rb
  spec/factories/type_factory.rb
  spec/factories/user_factory.rb
  spec/factories/user_password_factory.rb
  spec/factories/user_preference_factory.rb
  spec/factories/version_factory.rb
  spec/factories/wiki_factory.rb
  spec/factories/wiki_redirect_factory.rb
  spec/factories/work_package_custom_field_factory.rb
  spec/factories/work_package_factory.rb
Labels: housekeeping

#6846 Re-add puma for single-process testing
  Gemfile
  Gemfile.lock
  modules/backlogs/spec/features/backlogs/create_story_spec.rb
  modules/backlogs/spec/views/rb_taskboards/show_spec.rb
  modules/meeting/spec/features/meetings_show_spec.rb
  spec/features/menu_items/wiki_menu_item_spec.rb
  spec/features/wiki/attachment_upload_spec.rb
  spec/features/work_packages/table/queries/me_filter_spec.rb
  spec/rails_helper.rb
  spec/support/browsers/chrome.rb
  spec/support/capybara.rb
  spec/support/components/work_packages/columns.rb
  spec/support/components/wysiwyg/wysiwyg_editor.rb
  spec/support/database_cleaner.rb
  spec/support/pages/work_packages_timeline.rb
  spec/support/system_test.rb
Labels: housekeeping

#6855 Evaluate link rendering on homescreen based on show_banners
  app/helpers/homescreen_helper.rb
  app/views/homescreen/index.html.erb
  config/initializers/homescreen.rb
Labels: housekeeping

#6856 [29055] Small responsiveness issues
  app/assets/stylesheets/content/_forms.sass
  app/assets/stylesheets/layout/work_packages/_full_view.sass
Labels: bugfix, needs-review, styling

#6853 [28959] On global pages sidebar expands automatically when resizing the window
  frontend/src/app/components/resizer/main-menu-toggle.service.ts
Labels: bugfix, needs-review, styling

#6858 [28880] Search with subproject as default
  app/controllers/search_controller.rb
  app/helpers/search_helper.rb
  spec/views/search/index.html.erb_spec.rb
  spec_legacy/functional/search_controller_spec.rb
Labels: feature, needs-review

#6860 [28871] Preselect of current project in project-dropdown-field
  app/assets/stylesheets/content/menus/_project_autocompletion.sass
  frontend/src/app/components/projects/project-menu-autocomplete/project-menu-autocomplete.component.ts
Labels: feature, needs-review

#6852 [29057] Mobile styling issues on MSEdge
  app/assets/stylesheets/content/work_packages/timelines/_timelines_header.sass
  app/assets/stylesheets/layout/_main_menu.sass
Labels: bugfix, needs-review, styling

#6864 [29079] Order of timeline buttons wrong
  app/assets/stylesheets/layout/_toolbar.sass
  frontend/src/app/components/wp-buttons/wp-timeline-toggle-button/wp-timeline-toggle-button.html
Labels: bugfix, styling

#6861 [Fix] Avoid unnecessary scrollbar of content
  app/assets/stylesheets/layout/_base.sass
  app/assets/stylesheets/layout/work_packages/_table.sass
  app/views/layouts/base.html.erb
Labels: bugfix, needs-review

#6857 [28869] Creating a new version is too complicated
  app/views/project_settings/_boards.html.erb
  app/views/project_settings/_categories.html.erb
  app/views/project_settings/_versions.html.erb
  app/views/versions/index.html.erb
  modules/backlogs/app/views/project_settings/_versions.html.erb
  modules/backlogs/app/views/rb_master_backlogs/index.html.erb
Labels: bugfix, needs-review

#6868 [29099] Fix version CFs running into errors when creating new project
  app/models/custom_field.rb
  spec/features/projects/projects_custom_fields_spec.rb
Labels: bugfix

#6870 [29101] Cannot deactivate gravatars
  app/assets/stylesheets/content/_tables.sass
  modules/avatars/app/views/settings/_openproject_avatars.html.erb
Labels: bugfix, needs-review

#6865 [29705] Logged unit cost and labor cost not shown on work package view
  modules/costs/frontend/module/wp-display/wp-display-currency-field.module.ts
Labels: bugfix, needs-review

#6871 [29102] Open the right-click context menu close to the mouse icon
  frontend/src/app/components/op-context-menu/op-context-menu-handler.ts
Labels: feature, needs-review

#6872 Clear query states correctly
  frontend/src/app/components/wp-list/wp-states-initialization.service.ts
  frontend/src/app/components/wp-query-select/wp-query-select-dropdown.component.ts
Labels: bugfix, needs-review
