Repository opf/openproject, pull requests merged in 2018-12, with the labels that each got.

#6869 [28879] Automatically create "related to" relation on copy
  frontend/src/app/components/wp-copy/wp-copy.controller.ts
  spec/features/work_packages/copy_spec.rb
Labels: feature, needs-review

#6876 [28956] Refactor filters to CSS grid and fix minor styling issues in forms
  app/assets/stylesheets/content/_advanced_filters.sass
  app/assets/stylesheets/content/_custom_actions.sass
  app/assets/stylesheets/content/_forms.sass
  app/assets/stylesheets/content/_forms_mobile.sass
  app/assets/stylesheets/content/_simple_filters.lsg
  app/assets/stylesheets/content/_simple_filters.sass
  app/cells/views/user_filter/show.erb
  modules/avatars/app/views/settings/_openproject_avatars.html.erb
  modules/backlogs/app/views/shared/_settings.html.erb
  modules/costs/app/views/settings/_openproject_costs.html.erb
  modules/global_roles/app/views/users/_available_global_role.html.erb
  modules/global_roles/app/views/users/_available_global_roles.html.erb
  modules/reporting_engine/lib/assets/javascripts/reporting_engine/reporting/filters.js
Labels: bugfix, needs-review, styling

#6875 [15909] Respect current_date as start_date setting
  app/services/work_packages/set_attributes_service.rb
  config/settings.yml
  spec/services/work_packages/set_attributes_service_spec.rb
  spec_legacy/unit/mail_handler_spec.rb
Labels: bugfix

#6874 Attempt to stabilise test
  app/assets/stylesheets/content/work_packages/_table_content.sass
Labels: bugfix

#6877 actually unsubscribe
  lib/open_project/notifications.rb
Labels: bugfix, needs-review

#6880 [Fix] Top menu elements are too big on hover
  app/assets/stylesheets/layout/_top_menu.sass
Labels: bugfix, styling

#6883 [29128] Correctly destroy autocompleter when outside element DOM
  frontend/src/app/components/wp-relations/wp-relations-create/wp-relations-autocomplete/wp-relations-autocomplete.upgraded.component.ts
Labels: bugfix

#6885 [29132] Wrong aligned elements in permissions
  modules/global_roles/app/views/roles/_form.html.erb
  modules/global_roles/app/views/roles/_member_attributes.html.erb
  modules/global_roles/app/views/roles/_member_form.html.erb
Labels: bugfix, styling

#6884 [29801] Fine tune split view (Part 1)
  app/assets/stylesheets/content/work_packages/single_view/_single_view.sass
  config/locales/js-en.yml
Labels: bugfix, styling

#6888 [29134] Alignment for repo settings off
  app/assets/stylesheets/content/_forms.sass
  app/views/settings/_repositories.html.erb
Labels: bugfix, styling

#6889 [29112] Ensure docker can write into /tmp/op_uploaded_files
  Dockerfile
Labels: bugfix

#6890 [29139] Use our own encoder/decoder for params to ensure correctness
  frontend/src/app/components/op-context-menu/handlers/op-columns-context-menu.directive.ts
  frontend/src/app/modules/router/openproject.routes.ts
  frontend/src/app/modules/work_packages/routing/work-packages-routes.ts
Labels: bugfix

#6891 [29125] Allow multiple sessions with remember tokens
  app/assets/stylesheets/content/_forms.sass
  app/models/token/expirable_token.rb
  modules/two_factor_authentication/app/controllers/two_factor_authentication/concerns/remember_token.rb
  modules/two_factor_authentication/app/controllers/two_factor_authentication/my/two_factor_devices_controller.rb
  modules/two_factor_authentication/app/models/two_factor_authentication/remembered_auth_token.rb
  modules/two_factor_authentication/app/views/two_factor_authentication/authentication/request_otp.html.erb
  modules/two_factor_authentication/app/views/two_factor_authentication/my/two_factor_devices/index.html.erb
  modules/two_factor_authentication/config/locales/en.yml
Labels: bugfix, needs-review

#6882 [29072] Bugfix: Remove texts of delete and edit icons in tables
  app/cells/custom_actions/row_cell.rb
  app/cells/enumerations/row_cell.rb
  app/cells/statuses/row_cell.rb
  app/views/attribute_help_texts/_tab.html.erb
  app/views/auth_sources/index.html.erb
  app/views/custom_fields/_custom_options.html.erb
  app/views/custom_fields/_tab.html.erb
  app/views/groups/_users_table.html.erb
  app/views/groups/index.html.erb
  app/views/my/blocks/_timelog.html.erb
  app/views/project_settings/_boards.html.erb
  app/views/project_settings/_categories.html.erb
  app/views/project_settings/_versions.html.erb
  app/views/roles/index.html.erb
  app/views/types/index.html.erb
  app/views/users/_memberships.html.erb
  modules/backlogs/app/views/project_settings/_versions.html.erb
  modules/backlogs/features/version_settings.feature
  modules/costs/app/views/cost_types/_list.html.erb
  modules/costs/app/views/cost_types/_rate.html.erb
  modules/costs/app/views/costlog/_list.html.erb
  modules/costs/app/views/hourly_rates/_rate.html.erb
  modules/costs/spec/features/users_hourly_rates_spec.rb
  modules/global_roles/app/views/principal_roles/_show_table_row.html.erb
  modules/global_roles/app/views/roles/index.html.erb
  modules/ldap_groups/app/cells/ldap_groups/synchronized_groups/row_cell.rb
  modules/my_project_page/app/views/my_projects_overviews/blocks/_spent_time.html.erb
  modules/pdf_export/app/views/export_card_configurations/index.html.erb
  modules/webhooks/app/assets/stylesheets/webhooks/webhooks.sass
  modules/webhooks/app/cells/webhooks/outgoing/webhooks/row_cell.rb
  modules/webhooks/spec/features/manage_webhooks_spec.rb
  spec/features/admin/attribute_help_texts_spec.rb
  spec/features/custom_fields/custom_fields_spec.rb
  spec/support/pages/admin/custom_actions/index.rb
  spec/support/pages/types/index.rb
Labels: bugfix, needs-review

#6892 [29147] Use onEnter, onExit to correctly apply body classes
  frontend/src/app/modules/router/openproject.routes.ts
  frontend/src/app/modules/work_packages/routing/work-packages-routes.ts
Labels: bugfix, needs-review

#6894 [29142][29143] Edge Bugs
  app/assets/stylesheets/content/_context_menu.sass
  frontend/src/app/modules/work_packages/routing/wp-list/wp-list.component.ts
Labels: bugfix

#6898 [29160] Date field in filters corrected
  frontend/src/app/components/filters/filter-date-times-value/filter-date-times-value.component.html
Labels: bugfix, needs-review, styling

#6896 [28745] Fix milestone inline create
  frontend/src/app/components/wp-relations/embedded/children/wp-children-inline-create.service.ts
  spec/features/work_packages/details/relations/hierarchy_milestone_spec.rb
Labels: bugfix

#6895 [29127] In FF scale missing in Roadmap (graph)
  app/assets/stylesheets/content/_index.sass
  app/assets/stylesheets/content/_version.sass
  app/views/versions/_overview.html.erb
  app/views/versions/show.html.erb
Labels: bugfix, styling

#6900 [29056] Add notification when trying to upload folders
  config/locales/js-en.yml
  frontend/src/app/components/wp-edit/wp-notification.service.ts
  frontend/src/app/modules/attachments/attachments-upload/attachments-upload.component.ts
Labels: bugfix

#6899 [29145] Alignment of icon not right in relation tab
  app/assets/stylesheets/content/work_packages/single_view/_single_view.sass
  app/assets/stylesheets/content/work_packages/tabs/_relations.sass
  frontend/src/app/components/wp-relations/wp-relations-group/wp-relations-group.template.html
Labels: bugfix, styling

#6901 Avoid running into nil error
  app/controllers/wiki_controller.rb
Labels: bugfix

#6908 [29155] Create wiki page from version if it does not exist
  app/controllers/wiki_controller.rb
Labels: bugfix

#6904 [29153] Accept that the WP state can be pristine temporarily
  frontend/src/app/components/wp-table/timeline/container/wp-timeline-container.directive.ts
  frontend/src/app/components/wp-table/timeline/wp-timeline.ts
Labels: bugfix

#6906 [29133] Workflow filters corrected
  app/assets/stylesheets/content/_simple_filters.sass
  app/views/workflows/edit.html.erb
Labels: bugfix, needs-review

#6910 Fix project scrolling running into null element
  frontend/src/app/components/projects/project-menu-autocomplete/project-menu-autocomplete.component.ts
Labels: bugfix

#6905 [29148] Icons on work package summary page overlap with lines
  app/assets/stylesheets/content/_forms.sass
  app/assets/stylesheets/content/work_packages/single_view/_single_view.sass
  app/views/work_packages/reports/_report_category.html.erb
  app/views/work_packages/reports/report_details.html.erb
  spec/features/work_packages/reports_spec.rb
Labels: bugfix, styling

#6914 [29134] Alignment for repo settings off
  app/views/settings/_repositories.html.erb
Labels: bugfix, styling

#6912 [Fix] User limit info cut off
  app/views/users/index.html.erb
Labels: bugfix, styling

#6915 [29180] In Edge magnifying glass in WP view search is above text
  app/assets/stylesheets/layout/work_packages/_query_menu.sass
Labels: bugfix, styling

#6911 [28958] Misplaced overlay for saving cost reports
  modules/reporting_engine/lib/assets/javascripts/reporting_engine/reporting/controls.js
Labels: bugfix, styling

#6916 [29179] Filters in "View all projects" list are shown by default and cannot be removed
  app/assets/stylesheets/content/_advanced_filters.sass
Labels: bugfix, styling

#6917 [29158] Revert lazy loaded calendar for now
  frontend/src/app/angular4-modules.ts
  frontend/src/app/modules/work_packages/openproject-work-packages.module.ts
  frontend/src/app/modules/work_packages/routing/work-packages-routes.ts
Labels: bugfix, housekeeping

#6918 Fix reloading wp-table on global query resource
  frontend/src/app/components/modals/save-modal/save-query.modal.ts
  frontend/src/app/components/modals/share-modal/query-sharing-form.component.ts
  frontend/src/app/components/modals/share-modal/query-sharing.modal.ts
  frontend/src/app/components/op-context-menu/handlers/op-settings-dropdown-menu.directive.ts
  frontend/src/app/components/states.service.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-columns.service.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-group-by.service.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-sort-by.service.ts
  frontend/src/app/components/wp-list/wp-list.service.ts
  frontend/src/app/components/wp-list/wp-states-initialization.service.ts
  frontend/src/app/components/wp-table/configuration-modal/tabs/highlighting-tab.component.ts
  frontend/src/app/components/wp-table/table-state/table-state.ts
  frontend/src/app/modules/calendar/wp-calendar/wp-calendar.component.ts
  frontend/src/app/modules/work_packages/routing/wp-set/wp-set.component.ts
Labels: bugfix

#6920 [29184] Validate with old parent templated value
  app/models/queries/filters/base.rb
  app/models/queries/work_packages/filter/filter_for_wp_mixin.rb
  spec/models/queries/work_packages/filter/parent_filter_spec.rb
Labels: bugfix

#6919 [27315] Ensure parent_id is read before it is destroyed
  app/models/concerns/virtual_attribute.rb
  app/services/work_packages/update_ancestors_service.rb
  spec/services/work_packages/destroy_service_integration_spec.rb
Labels: bugfix

#6922 [29199] Correctly pass permission to identify new WP button
  frontend/src/app/modules/work_packages/routing/wp-full-view/wp-full-view.html
  lib/api/v3/work_packages/work_package_representer.rb
  spec/features/work_packages/details/milestones_spec.rb
  spec/lib/api/v3/work_packages/work_package_representer_spec.rb
Labels: bugfix

#6913 [29178] Bump CKEditor5 to v11.2.0
  app/assets/javascripts/vendor/ckeditor/ckeditor.js
  app/assets/javascripts/vendor/ckeditor/ckeditor.js.map
Labels: feature, needs-review

#6924 [29202] Don't open editor unless readable on drop attachment
  frontend/src/app/components/wp-edit/wp-edit-field/wp-edit-field.component.ts
Labels: bugfix

#6925 [29192] Fix blank default time entry activity
  app/helpers/timelog_helper.rb
  app/views/timelog/edit.html.erb
Labels: bugfix

#6927 [29204] Cost reports: broken scrolling behaviour
  modules/reporting_engine/lib/assets/stylesheets/reporting_engine/reporting.css.erb
Labels: bugfix, styling

#6932 Avoid trying to access user if association does not exist
  app/controllers/account_controller.rb
Labels: bugfix

#6941 fixed version of typescript to avoid 3.2.2
  frontend/package.json
  frontend/src/app/components/modals/modal-wrapper/dynamic-content.modal.ts
  frontend/src/app/components/op-context-menu/handlers/op-columns-context-menu.directive.ts
  frontend/src/app/components/op-context-menu/handlers/op-context-menu-trigger.directive.ts
  frontend/src/app/components/op-context-menu/handlers/op-settings-dropdown-menu.directive.ts
  frontend/src/app/components/op-context-menu/handlers/op-types-context-menu.directive.ts
  frontend/src/app/components/op-context-menu/handlers/wp-create-settings-menu.directive.ts
  frontend/src/app/components/op-context-menu/handlers/wp-status-dropdown-menu.directive.ts
  frontend/src/app/components/op-context-menu/op-context-menu-handler.ts
  frontend/src/app/components/op-context-menu/op-context-menu.service.ts
  frontend/src/app/components/op-context-menu/wp-context-menu/wp-single-context-menu.ts
  frontend/src/app/components/op-modals/op-modal.component.ts
  frontend/src/app/components/op-modals/op-modal.service.ts
  frontend/src/app/components/projects/project-menu-autocomplete/project-menu-autocomplete.component.ts
  frontend/src/app/components/resizer/main-menu-toggle.service.ts
  frontend/src/app/components/wp-fast-table/handlers/click-or-enter-handler.ts
  frontend/src/app/components/wp-fast-table/handlers/context-menu/context-menu-handler.ts
  frontend/src/app/components/wp-inline-create/wp-inline-create.component.ts
  frontend/src/app/globals/global-listeners.ts
  frontend/src/app/globals/global-listeners/augmented-date-picker.ts
  frontend/src/app/globals/global-listeners/link-hijacking.ts
  frontend/src/app/modules/common/copy-to-clipboard/copy-to-clipboard.directive.ts
Labels: work in progress

#6938 Fix #new on internal api error
  lib/api/root.rb
Labels: bugfix

#6944 [29227] Enabled modules do not affect updated_on, thus add to cache_key
  app/controllers/projects_controller.rb
Labels: bugfix

#6947 [29228] Overlapping icon on welcome screen
  app/assets/stylesheets/content/_modal.sass
Labels: bugfix, styling

#6939 [29197] WP table and gantt row highlighting
  app/assets/stylesheets/content/work_packages/_table_content.sass
  app/assets/stylesheets/content/work_packages/timelines/_timelines.sass
  app/assets/stylesheets/content/work_packages/timelines/_timelines_header.sass
  app/assets/stylesheets/layout/work_packages/_table.sass
  lib/open_project/design.rb
Labels: bugfix, needs-review

#6946 [29238] Two column layout not applied on page reload
  app/assets/stylesheets/content/work_packages/single_view/_single_view.sass
  app/assets/stylesheets/layout/work_packages/_details_view.sass
  app/assets/stylesheets/openproject/_mixins.sass
  frontend/src/app/components/resizer/wp-resizer.component.ts
  frontend/src/app/components/wp-form-group/wp-attribute-group.template.html
Labels: bugfix, styling

#6928 Add postgres support in packager
  .buildpacks
  .pkgr.yml
  lib/tasks/packager.rake
  packaging/teardown
Labels: work in progress

#6951 [Fix] Remove welcome parameter after language selection
  app/controllers/onboarding_controller.rb
Labels: bugfix

#6952 Remove unused "styled checkboxes"
  app/assets/stylesheets/content/_forms.lsg
  app/assets/stylesheets/content/_forms.sass
Labels: housekeeping, styling

#6953 [29277] Fix wp empty row notification height
  app/assets/stylesheets/content/work_packages/_table_content.sass
Labels: bugfix, needs-review

#6950 [29242] MSEdge arrow alignment
  app/assets/stylesheets/content/work_packages/_table_hierarchy.sass
  frontend/src/app/components/resizer/wp-resizer.component.ts
Labels: bugfix, needs-review, styling

#6936 Make ProjectsController#destroy use background worker + service
  app/contracts/projects/base_contract.rb
  app/contracts/projects/delete_contract.rb
  app/controllers/projects_controller.rb
  app/mailers/base_mailer.rb
  app/mailers/project_mailer.rb
  app/mailers/user_mailer.rb
  app/services/projects/delete_project_service.rb
  app/views/project_mailer/copy_project_failed.html.erb
  app/views/project_mailer/copy_project_failed.text.erb
  app/views/project_mailer/copy_project_succeeded.html.erb
  app/views/project_mailer/copy_project_succeeded.text.erb
  app/views/project_mailer/delete_project_completed.html.erb
  app/views/project_mailer/delete_project_completed.text.erb
  app/views/project_mailer/delete_project_failed.html.erb
  app/views/project_mailer/delete_project_failed.text.erb
  app/workers/copy_project_job.rb
  app/workers/projects/delete_project_job.rb
  config/locales/en.yml
  spec/contracts/projects/delete_contract_spec.rb
  spec/controllers/copy_projects_controller_spec.rb
  spec/controllers/projects_controller_spec.rb
  spec/features/projects/destroy_spec.rb
  spec/models/copy_project_job_spec.rb
  spec/services/projects/delete_service_spec.rb
  spec_legacy/functional/projects_controller_spec.rb
Labels: feature, needs-review
