Repository opf/openproject, pull requests merged in 2018-05, with the labels that each got.

#6285 [27328] Fix invalid menu / form items shown when modifying queries
  frontend/app/components/modals/rename-query-modal/rename-query.modal.ts
  frontend/app/components/modals/share-modal/query-sharing-form.component.ts
  frontend/app/components/op-context-menu/handlers/op-settings-dropdown-menu.directive.ts
  frontend/app/components/wp-query-menu/wp-query-menu.service.ts
Labels: bugfix

#6287 Convert focus directive
  frontend/app/angular4-modules.ts
  frontend/app/components/angular/downgrade-attribute-directive.ts
  frontend/app/components/common/focus/focus-directive-upgraded.ts
  frontend/app/components/common/focus/focus-within.directive.ts
  frontend/app/components/common/focus/focus-within.upgraded.directive.ts
  frontend/app/components/common/focus/focus.directive.ts
  frontend/app/ui_components/index.js
Labels: housekeeping

#6286 Rework helper to auto-include wysiwig in tab builder when requested
  app/cells/views/settings/text_setting/show.erb
  app/controllers/wiki_controller.rb
  app/helpers/text_formatting_helper.rb
  app/views/projects/form/attributes/_description.html.erb
  app/views/settings/_general.html.erb
  lib/open_project/form_tag_helper.rb
  lib/open_project/text_formatting/formatters/markdown/helper.rb
  lib/open_project/text_formatting/formatters/plain/helper.rb
  lib/open_project/text_formatting/formatters/textile/helper.rb
  lib/tabular_form_builder.rb
  spec/lib/tabular_form_builder_spec.rb
Labels: bugfix, styling

#6289 Replace click-on-keypress directive
  frontend/app/angular4-modules.ts
  frontend/app/components/a11y/accessible-by-keyboard.component.ts
  frontend/app/components/a11y/accessible-by-keyboard.ng1.directive.ts
  frontend/app/components/a11y/accessible-click.directive.ng2.test.ts
  frontend/app/components/a11y/accessible-click.directive.ts
  frontend/app/components/a11y/accessible_by_keyboard.html
  frontend/app/components/op-context-menu/op-context-menu.html
  frontend/app/components/table-pagination/table-pagination.component.html
  frontend/app/components/wp-attachments/wp-attachments-upload/wp-attachments-upload.html
  frontend/app/components/wp-edit/wp-edit-field/wp-edit-field.html
  frontend/app/components/wp-inline-create/wp-inline-create.component.html
  frontend/app/ui_components/click-on-keypress-upgraded.component.ts
  frontend/app/ui_components/index.js
  frontend/tests/unit/tests/ui_components/click-on-keypress-directive-test.js
Labels: bugfix

#6292 [27604] Fix columns being parsed from columns[] in embedded queryprops
  app/services/api/v3/parse_query_params_service.rb
  spec/features/types/form_configuration_query_spec.rb
  spec/support/components/work_packages/columns.rb
Labels: bugfix

#6294 [27576] Conflict-check only main wiki items from same project
  app/controllers/wiki_controller.rb
Labels: bugfix

#6297 [27487] Don't check for current custom_field_ids when resetting to default
  app/models/type/attribute_groups.rb
  app/models/type/attributes.rb
  app/services/base_type_service.rb
  spec/factories/type_factory.rb
  spec/features/types/reset_form_configuration_spec.rb
  spec/models/type/attribute_groups_spec.rb
Labels: bugfix

#6299 [27462] Pass wiki title to new page if it does not exist
  app/controllers/wiki_controller.rb
  lib/open_project/text_formatting.rb
  spec/features/security/angular_xss_spec.rb
  spec/lib/open_project/text_formatting_spec.rb
  spec_legacy/functional/wiki_controller_spec.rb
  spec_legacy/unit/helpers/application_helper_spec.rb
Labels: bugfix

#6301 [27685] Allow to disable certain tabs of the embedded configuration modal
  app/assets/stylesheets/content/_tabs.sass
  app/services/base_type_service.rb
  config/locales/js-en.yml
  frontend/app/components/types/form-configuration/types-form-configuration.controller.ts
  frontend/app/components/wp-table/configuration-modal/tab-portal-outlet.ts
  frontend/app/components/wp-table/configuration-modal/wp-table-configuration.modal.html
  frontend/app/components/wp-table/configuration-modal/wp-table-configuration.service.ts
  frontend/app/components/wp-table/external-configuration/external-query-configuration.component.ts
  frontend/app/components/wp-table/external-configuration/external-query-configuration.service.ts
  frontend/app/components/wp-table/external-configuration/restricted-wp-table-configuration.service.ts
  lib/api/v3/queries/query_params_representer.rb
  spec/features/types/form_configuration_query_spec.rb
  spec/lib/api/v3/queries/query_representer_generation_spec.rb
  spec/services/api/v3/work_package_collection_from_query_service_spec.rb
  spec/support/components/work_packages/table_configuration_modal.rb
Labels: bugfix, feature

#6302 [27684] Embedded tables not aligned with group header
  app/assets/stylesheets/layout/_work_package_table_embedded.sass
Labels: bugfix, styling

#6303 Decrease font size of embedded table headers
  app/assets/stylesheets/layout/_work_package_table_embedded.sass
Labels: styling

#6307 Set query id on initialisation.
  frontend/app/components/wp-query-menu/wp-query-menu.ng2.test.ts
  frontend/app/components/wp-query-menu/wp-query-menu.service.ts
Labels: bugfix, needs-review

#6305 Replace cocaine/terrapin with Open3
  Gemfile
  Gemfile.lock
  lib/open_project/file_command_content_type_detector.rb
  spec/lib/open_project/content_type_detector_spec.rb
  spec/lib/open_project/file_command_content_type_detector_spec.rb
Labels: housekeeping

#6308 [27677] Better html titles
  app/helpers/application_helper.rb
  app/helpers/meta_tags_helper.rb
  app/views/layouts/base.html.erb
  app/views/layouts/help.html.erb
  app/views/timelog/index.html.erb
  config/locales/js-en.yml
  frontend/app/angular4-modules.ts
  frontend/app/components/html/op-title.service.ts
  frontend/app/components/routing/wp-view-base/wp-view-base.controller.ts
  frontend/app/components/wp-copy/wp-copy.controller.ts
  frontend/app/components/wp-new/wp-create.controller.ts
  frontend/app/components/wp-query-menu/wp-query-menu.ng2.test.ts
  frontend/app/components/wp-query-menu/wp-query-menu.service.ts
  frontend/app/components/wp-relations/wp-relations-parent/wp-relations-parent.html
  frontend/app/components/wp-relations/wp-single-relation.directive.ts
  frontend/app/modules/hal/resources/work-package-resource.ts
Labels: feature, needs-review

#6310 Convert wp-relations to angular
  frontend/app/angular4-modules.ts
  frontend/app/components/wp-edit/field-controls/wp-edit-field-controls-ng1-wrapper.ts
  frontend/app/components/wp-relations/ng1-wp-relations-wrapper.directive.ts
  frontend/app/components/wp-relations/wp-relation-row/wp-relation-row.component.ts
  frontend/app/components/wp-relations/wp-relation-row/wp-relation-row.template.html
  frontend/app/components/wp-relations/wp-relations-create/add-fixed-type.template.html
  frontend/app/components/wp-relations/wp-relations-create/dynamic-relation-types.template.html
  frontend/app/components/wp-relations/wp-relations-create/ng1-wp-relations-create.directive.ts
  frontend/app/components/wp-relations/wp-relations-create/wp-relation-create.template.html
  frontend/app/components/wp-relations/wp-relations-create/wp-relations-autocomplete/wp-relations-autocomplete.directive.ts
  frontend/app/components/wp-relations/wp-relations-create/wp-relations-autocomplete/wp-relations-autocomplete.template.html
  frontend/app/components/wp-relations/wp-relations-create/wp-relations-create.component.ts
  frontend/app/components/wp-relations/wp-relations-group/wp-relations-group.component.ts
  frontend/app/components/wp-relations/wp-relations-group/wp-relations-group.directive.ts
  frontend/app/components/wp-relations/wp-relations-group/wp-relations-group.template.html
  frontend/app/components/wp-relations/wp-relations-hierarchy-row/wp-relations-hierarchy-row.directive.ts
  frontend/app/components/wp-relations/wp-relations-hierarchy/wp-relations-hierarchy.directive.ts
  frontend/app/components/wp-relations/wp-relations.component.ts
  frontend/app/components/wp-relations/wp-relations.interfaces.ts
  frontend/app/components/wp-relations/wp-relations.service.ts
  frontend/app/components/wp-relations/wp-relations.template.html
  frontend/app/components/wp-single-view-tabs/relations-tab/relations-tab.html
  frontend/app/modules/hal/dm-services/relations-dm.service.ts
Labels: housekeeping

#6311 [27606] Allow inline-create in embedded children tables
  app/assets/stylesheets/layout/_work_package_table_embedded.sass
  app/policies/work_package_policy.rb
  frontend/app/components/routing/wp-view-base/wp-view-base.controller.ts
  frontend/app/components/wp-edit-form/work-package-filter-values.ts
  frontend/app/components/wp-inline-create/wp-inline-create.component.ts
  frontend/app/components/wp-relations/wp-relation-children/wp-children-query.html
  frontend/app/components/wp-relations/wp-relations-hierarchy/wp-relations-hierarchy.template.html
  frontend/app/components/wp-table/embedded/wp-embedded-table.component.ts
  frontend/app/components/wp-table/wp-table-configuration.ts
  spec/features/work_packages/details/relations/hierarchy_spec.rb
  spec/support/components/work_packages/relations.rb
  spec/support/pages/work_packages_table.rb
Labels: feature

#6312 [26874] Raise required FF version to 60 (latest ESR)
  browserslist
  docs/installation/system-requirements.md
  frontend/app/globals/unsupported-browsers.ts
Labels: housekeeping

#6313 [27260] Fix invitation token expiring
  app/models/token/invitation.rb
  app/views/account/_register.html.erb
  app/views/account/register.html.erb
  spec/features/users/invitation_spec.rb
Labels: bugfix

#6317 Avoid async ES5 generators all over the place
  frontend/app/components/angular/simple-template-renderer.ts
  frontend/app/components/api/api-work-packages/api-work-packages.service.ts
  frontend/app/components/common/config/configuration.service.ts
  frontend/app/components/common/help-texts/attribute-help-text.component.ts
  frontend/app/components/common/help-texts/attribute-help-text.service.ts
  frontend/app/components/modals/confirm-dialog/confirm-dialog.service.ts
  frontend/app/components/modals/save-modal/save-query.modal.ts
  frontend/app/components/projects/project-cache.service.ts
  frontend/app/components/routing/wp-list/wp-list.component.ts
  frontend/app/components/states/state-cache.service.ts
  frontend/app/components/table-pagination/pagination-service.ts
  frontend/app/components/user/user-cache.service.ts
  frontend/app/components/work-packages/work-package-cache.service.ts
  frontend/app/components/work-packages/work-package-comment/work-package-comment.directive.ts
  frontend/app/components/wp-activity/activity-service.ts
  frontend/app/components/wp-activity/user/user-activity-directive.ts
  frontend/app/components/wp-copy/wp-copy.controller.ts
  frontend/app/components/wp-edit-form/single-view-edit-context.ts
  frontend/app/components/wp-edit-form/table-row-edit-context.ts
  frontend/app/components/wp-edit-form/work-package-changeset.ts
  frontend/app/components/wp-edit-form/work-package-edit-field-handler.ts
  frontend/app/components/wp-edit-form/work-package-edit-form.ts
  frontend/app/components/wp-edit-form/work-package-editing-service.ts
  frontend/app/components/wp-edit-form/work-package-filter-values.ts
  frontend/app/components/wp-edit/wp-edit-field/wp-edit-field-group.directive.ts
  frontend/app/components/wp-edit/wp-edit-field/wp-edit-field.component.ts
  frontend/app/components/wp-fast-table/state/wp-table-additional-elements.service.ts
  frontend/app/components/wp-fast-table/state/wp-table-base.service.ts
  frontend/app/components/wp-fast-table/state/wp-table-filters.service.ts
  frontend/app/components/wp-list/wp-list.service.ts
  frontend/app/components/wp-new/wp-create.controller.ts
  frontend/app/components/wp-new/wp-create.service.ts
  frontend/app/components/wp-query-menu/wp-query-menu.ng2.test.ts
  frontend/app/components/wp-query-select/wp-query-select-dropdown.component.ts
  frontend/app/components/wp-relations/wp-relations-create/wp-relations-autocomplete/wp-relations-autocomplete.upgraded.component.ts
  frontend/app/components/wp-relations/wp-relations-create/wp-relations-create.component.ts
  frontend/app/components/wp-relations/wp-relations-hierarchy/wp-relations-hierarchy.service.ts
  frontend/app/components/wp-relations/wp-relations.service.ts
  frontend/app/components/wp-single-view-tabs/activity-panel/wp-activity.service.ts
  frontend/app/components/wp-single-view-tabs/watchers-tab/watchers-tab.component.ts
  frontend/app/components/wp-single-view-tabs/watchers-tab/wp-watchers.service.ts
  frontend/app/components/wp-single-view-tabs/wp-linked-resource-cache.service.ts
  frontend/app/components/wp-table/configuration-modal/wp-table-configuration.modal.ts
  frontend/app/components/wp-table/embedded/wp-embedded-table.component.ts
  frontend/app/components/wp-table/table-pagination/wp-table-pagination.component.ng2.test.ts
  frontend/app/components/wp-table/timeline/cells/wp-timeline-cell-mouse-handler.ts
  frontend/app/modules/hal/dm-services/configuration-dm.service.ts
  frontend/app/modules/hal/dm-services/help-text-dm.service.ts
  frontend/app/modules/hal/dm-services/project-dm.service.ts
  frontend/app/modules/hal/dm-services/query-dm.service.ts
  frontend/app/modules/hal/dm-services/query-form-dm.service.ts
  frontend/app/modules/hal/dm-services/relations-dm.service.ts
  frontend/app/modules/hal/dm-services/root-dm.service.ts
  frontend/app/modules/hal/dm-services/type-dm.service.ts
  frontend/app/modules/hal/dm-services/user-dm.service.ts
  frontend/app/modules/hal/hal-link/hal-link.ts
  frontend/app/modules/hal/resources/hal-resource.ts
  frontend/app/modules/hal/resources/relation-resource.ts
  frontend/app/modules/hal/resources/work-package-resource.ts
  frontend/tslint_typechecks.json
Labels: housekeeping

#6321 registration footer override
  app/helpers/accounts_helper.rb
  app/models/permitted_params.rb
  app/models/permitted_params/allowed_settings.rb
  app/views/settings/_authentication.html.erb
  lib/open_project/configuration.rb
  spec/models/permitted_params_spec.rb
  spec/views/account/register.html.erb_spec.rb
  spec/views/settings/_authentication.html.erb_spec.rb
Labels: feature, needs-review

#6324 [27769] Always use plain formatter for revision commits
  app/helpers/repositories_helper.rb
  app/views/repositories/_revisions.html.erb
  app/views/repositories/revision.html.erb
Labels: bugfix

#6323 [27746] When validating the contract, ignore the old parent
  app/contracts/work_packages/base_contract.rb
  spec/services/work_packages/update_service_integration_spec.rb
Labels: bugfix

#6330 [26189] Allow to always set parent page in new wiki page
  app/views/wiki/new.html.erb
Labels: bugfix

#6331 [27776] Fix double key-up trigger on newly focussed element
  frontend/app/components/a11y/accessible-click.directive.ng2.test.ts
  frontend/app/components/a11y/accessible-click.directive.ts
Labels: bugfix

#6328 [27493] Sort assignee filter by name
  frontend/app/components/filters/filter-toggled-multiselect-value/filter-toggled-multiselect-value.component.ng2.test.ts
  frontend/app/components/filters/filter-toggled-multiselect-value/filter-toggled-multiselect-value.component.ts
  frontend/app/components/wp-edit/field-types/wp-edit-select-field.module.ts
  frontend/app/modules/hal/openproject-hal.module.ts
  frontend/app/modules/hal/services/hal-resource-sorting.service.ts
Labels: bugfix

#6340 Fix: Re-add forms for uploading favicon and touch icon.
  app/views/custom_styles/show.html.erb
Labels: needs-review

#6342 [27794] Row is not highlighted when hovering above row in embedded tables
  app/assets/stylesheets/layout/_work_package_table_embedded.sass
Labels: bugfix, styling

#6333 [27780] Assign default status when type changes and old status does not exist
  app/models/status.rb
  app/models/type.rb
  app/services/work_packages/set_attributes_service.rb
  config/locales/en.yml
  spec/controllers/work_packages/moves_controller_spec.rb
  spec/models/status_spec.rb
  spec/models/type_spec.rb
  spec/services/work_packages/update_service_integration_spec.rb
  spec_legacy/unit/type_spec.rb
Labels: bugfix

#6327 Show parent's validation errors when saving child fails
  config/locales/en.yml
  frontend/app/components/wp-edit-form/work-package-changeset.ts
  lib/api/v3/work_packages/create_work_packages.rb
  lib/api/v3/work_packages/work_packages_api.rb
  lib/api/v3/work_packages/work_packages_shared_helpers.rb
  spec/requests/api/v3/work_packages/dependent_errors_spec.rb
Labels: bugfix, needs-review

#6338 AngularJS in 'mail-notifications.html.erb' replaced by Angular component
  app/controllers/my_controller.rb
  app/controllers/users_controller.rb
  app/views/users/_mail_notifications.html.erb
  frontend/app/angular4-modules.ts
  frontend/app/components/common/hide-section/show-section-dropdown.component.ts
  spec/views/users/edit.html.erb_spec.rb
Labels: housekeeping

#6348 [27833] Fix selecting multi CF value from filters
  frontend/app/components/wp-edit-form/work-package-changeset.ts
  spec/features/work_packages/new/attributes_from_filter_spec.rb
Labels: bugfix

#6345 [27823] Remove backface-visibility hidden in grid partials
  app/assets/stylesheets/content/_attributes_key_value.sass
  app/assets/stylesheets/content/_collapsible_section.sass
  app/assets/stylesheets/content/_forms.sass
  app/assets/stylesheets/content/_links.sass
  app/assets/stylesheets/content/_notifications.sass
  app/assets/stylesheets/content/_table.sass
  app/assets/stylesheets/content/_widget_box.sass
  app/assets/stylesheets/layout/_drop_down.sass
  app/assets/stylesheets/layout/_main_menu.sass
  app/assets/stylesheets/layout/_top_menu.sass
  app/assets/stylesheets/openproject/_scm.sass
  app/assets/stylesheets/vendor/_ng_dialog.sass
  app/assets/stylesheets/vendor/_select2.scss
  frontend/npm-shrinkwrap.json
  frontend/package.json
Labels: bugfix

#6352 Allow wysiwyg tables to exist with and without header
  app/assets/javascripts/vendor/ckeditor/ckeditor.js
  app/views/wiki/edit.html.erb
  app/views/wiki/new.html.erb
  lib/open_project/text_formatting/formatters/markdown/helper.rb
  spec/features/wysiwyg/tables_spec.rb
  spec/support/components/wysiwyg/wysiwyg_editor.rb
Labels: feature
