Repository opf/openproject, pull requests merged in 2018-10, with the labels that each got.

#6730 [28645] Toolbar container too high
  app/assets/stylesheets/layout/_toolbar.sass
  frontend/src/app/components/wp-query-select/wp-query-selectable-title.html
Labels: bugfix, styling

#6731 fail if asset precompile fails
  script/ci/cache_prepare.sh
  script/ci/setup.sh
Labels: work in progress

#6736 Change block order in version overview
  app/assets/stylesheets/content/_forms.sass
  app/assets/stylesheets/content/_widget_box.sass
  app/assets/stylesheets/openproject/_homescreen.sass
  app/views/homescreen/index.html.erb
  app/views/versions/_work_package_counts.html.erb
  app/views/versions/show.html.erb
Labels: styling

#6737 [28678] Top menu entries are misaligned in mobile views
  app/assets/stylesheets/layout/_drop_down_mobile.sass
Labels: bugfix, styling

#6738 [28253] Improve print layout of work package full screen
  app/assets/stylesheets/layout/work_packages/_print.sass
  frontend/src/app/components/wp-custom-actions/wp-custom-actions/wp-custom-action.component.html
Labels: bugfix, styling

#6740 [28410] WP resizer is wrongly positioned in Safari and Edge
  app/assets/stylesheets/layout/work_packages/_full_view.sass
  frontend/src/app/components/routing/wp-full-view/wp-full-view.html
Labels: bugfix, styling

#6742 [28663] Add link to privacy policy
  config/settings.yml
Labels: bugfix

#6744 [28632] Wider input field for news editor
  app/views/news/_form.html.erb
Labels: bugfix, needs-review

#6745 Fix #28639. Use api_v3_path helpers for linking work package's available relation candidates
  frontend/src/app/components/wp-relations/wp-relations-create/wp-relations-autocomplete/wp-relations-autocomplete.upgraded.component.ts
  lib/api/v3/utilities/path_helper.rb
  lib/api/v3/work_packages/work_package_representer.rb
Labels: bugfix

#6748 [28718] Bugfix: Sidebar hidden on mobile
  app/assets/stylesheets/layout/_base_mobile.sass
Labels: bugfix, needs-review, styling

#6746 [26126] Relations counter also includes parent and children
  app/assets/stylesheets/content/work_packages/single_view/_single_view.sass
  frontend/src/app/angular4-modules.ts
  frontend/src/app/components/routing/wp-full-view/wp-full-view.html
  frontend/src/app/components/routing/wp-split-view/wp-split-view.html
  frontend/src/app/components/work-packages/wp-relations-count/wp-relations-count.component.ts
  frontend/src/app/components/work-packages/wp-relations-count/wp-relations-count.html
  frontend/src/app/components/work-packages/wp-relations-count/wp-watchers-count.component.ts
  frontend/src/app/components/wp-edit-form/work-package-changeset.ts
  frontend/src/app/components/wp-relations/wp-relations-hierarchy/wp-relations-hierarchy.directive.ts
  frontend/src/app/components/wp-relations/wp-relations-hierarchy/wp-relations-hierarchy.service.ts
Labels: bugfix, needs-review

#6734 [28217] Move export options from footer to menu
  app/views/wiki/_wiki_export_modal.html.erb
  app/views/wiki/show.html.erb
Labels: feature, needs-review

#6753 make sure to delete tmp files
  app/workers/extract_fulltext_job.rb
Labels: bugfix, needs-review

#6757 [28740] Horizontal scrollbars due to links in work package activity
  app/assets/stylesheets/content/_wiki.sass
  app/assets/stylesheets/content/work_packages/tabs/_activities.sass
Labels: bugfix, styling

#6735 [28422] Fix/scroll behaviour
  app/assets/javascripts/specific/main_menu.js.erb
  app/assets/stylesheets/content/_wiki.sass
  app/assets/stylesheets/layout/_base.sass
  app/assets/stylesheets/layout/_main_menu.sass
  app/assets/stylesheets/layout/_main_menu_mobile.sass
  app/assets/stylesheets/layout/work_packages/_full_view.sass
  app/assets/stylesheets/layout/work_packages/_mobile.sass
  app/assets/stylesheets/layout/work_packages/_query_menu.sass
Labels: bugfix, on-hold, styling

#6754 [28719] Bugfix: Loading indicator not disappearing
  frontend/src/app/components/wp-query-select/wp-query-select-dropdown.component.ts
Labels: bugfix, needs-review

#6758 [28680] Optimize column-width
  app/assets/stylesheets/content/_table.sass
  frontend/src/app/components/wp-fast-table/builders/cell-builder.ts
Labels: styling

#6768 [28715] Ensure download disposition for non-image types
  app/uploaders/fog_file_uploader.rb
  spec/controllers/attachments_controller_spec.rb
Labels: bugfix, security

#6750 Add feature specs for relations count and watchers count
  spec/features/work_packages/details/relations/hierarchy_spec.rb
  spec/features/work_packages/details/relations/relations_spec.rb
  spec/features/work_packages/new/create_child_spec.rb
  spec/features/work_packages/tabs/watcher_tab_spec.rb
  spec/support/components/work_packages/relations.rb
  spec/support/components/work_packages/tabs_counter.rb
Labels: needs-review

#6763 [22399] Bugfix global menus hidden on mobile
  frontend/src/app/components/resizer/main-menu-resizer.component.ts
  frontend/src/app/components/resizer/main-menu-toggle.component.ts
  frontend/src/app/components/resizer/main-menu-toggle.service.ts
Labels: bugfix, needs-review

#6782 [28804] Adjust the Language selection screen
  app/assets/stylesheets/content/_modal.sass
  app/views/onboarding/_configuration_modal.html.erb
  config/locales/en.yml
Labels: bugfix, styling

#6784 [28812] Make links in seeder respect relative URL roots
  app/seeders/demo_data/custom_field_seeder.rb
  app/seeders/demo_data/project_seeder.rb
  app/seeders/demo_data/query_builder.rb
  app/seeders/demo_data/wiki_seeder.rb
  app/seeders/demo_data/work_package_seeder.rb
  app/seeders/seeder.rb
  config/locales/en.seeders.yml
Labels: bugfix

#6771 [28768] Long dropdowns scrollable
  app/assets/stylesheets/content/menus/_project_autocompletion.sass
  app/assets/stylesheets/layout/_top_menu.sass
Labels: bugfix, needs-review, styling

#6743 [27586] Guided tour for user onboarding
  app/assets/javascripts/application.js.erb
  app/assets/javascripts/onboarding/backlogs_tour.js
  app/assets/javascripts/onboarding/homescreen_tour.js
  app/assets/javascripts/onboarding/onboarding_tour.js
  app/assets/javascripts/onboarding/work_package_tour.js
  app/assets/javascripts/vendor/enjoyhint.js
  app/assets/stylesheets/content/work_packages/_table_content.sass
  app/assets/stylesheets/openproject/_generic.sass
  app/assets/stylesheets/vendor/_enjoyhint.sass
  app/assets/stylesheets/vendor/_index.sass
  app/controllers/projects_controller.rb
  app/seeders/demo_data/project_seeder.rb
  app/views/homescreen/index.html.erb
  app/views/layouts/base.html.erb
  config/initializers/assets.rb
  config/locales/js-en.yml
  config/settings.yml
  spec/features/auth/consent_auth_stage_spec.rb
  spec/features/onboarding/onboarding_tour_spec.rb
  spec/features/users/create_spec.rb
  spec/support/authentication_helpers.rb
Labels: feature, needs-review

#6785 Fix demo data
  app/seeders/demo_data/version_builder.rb
Labels: bugfix

#6787 [28469] Not possible to re-size Gantt chart on iPad/iPhone
  frontend/src/app/components/resizer/wp-resizer.component.ts
Labels: bugfix, styling

#6792 [28846] Fix upload permission check on drag&drop pane
  frontend/src/app/components/attachments/attachments-upload/attachments-upload.html
  frontend/src/app/components/work-packages/wp-single-view/wp-single-view.html
  frontend/src/app/modules/hal/resources/mixins/attachable-mixin.ts
Labels: bugfix

#6794 Address npm warnings after angular upgrade
  frontend/karma.conf.js
  frontend/npm-shrinkwrap.json
  frontend/package.json
Labels: housekeeping

#6796 Replace # on autocomplete for WPs
  frontend/src/app/components/wp-relations/wp-relations-create/wp-relations-autocomplete/wp-relations-autocomplete.upgraded.component.ts
Labels: feature
