Repository opf/openproject, pull requests merged in 2018-03, with the labels that each got.

#6203 [27262] Disable distinct on attributes only from leaves query for aggregated values
  app/services/work_packages/update_ancestors_service.rb
  spec/services/work_packages/update_ancestors_service_spec.rb
Labels: bugfix

#6210 [27284 ] Allow :none authentication as empty smtp_authentication setting
  app/assets/javascripts/settings.js.erb
  app/views/settings/_notifications.html.erb
  lib/open_project/configuration.rb
  spec/lib/open_project/configuration_spec.rb
Labels: bugfix

#6212 [26725] Filter "Assignee's group" contains confusing option <me>
  frontend/app/components/filters/filter-toggled-multiselect-value/filter-toggled-multiselect-value.directive.ts
Labels: bugfix, needs-review

#6218 Upgrade angular to 5.2
  frontend/npm-shrinkwrap.json
  frontend/package.json
Labels: housekeeping

#6194 [26737] Journal notification mail changed information not very prominent
  config/locales/en.yml
  lib/plugins/acts_as_journalized/lib/journal_formatter/base.rb
  spec/mailers/user_mailer_spec.rb
  spec_legacy/unit/repository_spec.rb
Labels: feature, needs-review, styling

#6209 [27215] PullPreview: Share "files" directory from "web" with "worker"
  Dockerfile
  Dockerfile.public
  docker-compose.pullpreview.yml
  docker/entrypoint-all-in-one.sh
  docker/entrypoint.sh
  docker/gosu
  docker/worker
Labels: work in progress

#6208 Avoid DatabaseCleaner truncation strategy with in-process puma server
  Gemfile
  Gemfile.lock
  spec/features/work_packages/details/custom_fields/custom_field_spec.rb
  spec/features/work_packages/table/edit_work_packages_spec.rb
  spec/features/work_packages/table/switch_types_spec.rb
  spec/rails_helper.rb
  spec/support/capybara.rb
  spec/support/database_cleaner.rb
  spec/support/pages/abstract_work_package.rb
  spec/support/pages/abstract_work_package_create.rb
  spec/support/pages/full_work_package.rb
  spec/support/pages/full_work_package_create.rb
  spec/support/pages/split_work_package.rb
  spec/support/pages/split_work_package_create.rb
  spec/support/system_test.rb
Labels: housekeeping

#6236 [27332] Labels not clickable in User section
  app/views/users/_memberships.html.erb
Labels: bugfix, styling

#6237 Fix color preview
  app/assets/javascripts/colors.js
  app/assets/stylesheets/content/_forms.sass
  app/helpers/colors_helper.rb
  app/views/custom_styles/show.html.erb
  app/views/planning_element_type_colors/_form.html.erb
  app/views/planning_element_type_colors/index.html.erb
Labels: bugfix

#6234 Ensure gon outputs the script tag with a nonce
  app/helpers/hide_sections_helper.rb
  app/views/layouts/angular.html.erb
  app/views/timelog/index.html.erb
Labels: bugfix

#6231 [27318] Display "Shared" / "Inherited" icon again in front of versions from other projects
  app/assets/stylesheets/content/_tables.sass
  app/views/project_settings/_versions.html.erb
Labels: bugfix, styling

#6233 Remove special sidebar page logic for wiki.
  app/models/wiki.rb
  app/views/wiki/_sidebar.html.erb
  app/views/wiki/date_index.html.erb
  app/views/wiki/index.html.erb
  app/views/wiki/show.html.erb
  spec_legacy/functional/wiki_controller_spec.rb
  spec_legacy/unit/wiki_spec.rb
Labels: housekeeping

#6238 Fix/cf spec
  Gemfile
  Gemfile.lock
  spec/features/work_packages/details/custom_fields/custom_field_spec.rb
Labels: bugfix

#6247 Bump ruby to 2.4.4
  .travis.yml
  Gemfile
  Gemfile.lock
Labels: housekeeping
