Repository opf/openproject, pull requests merged in 2018-06, with the labels that each got.

#6357 [27845] Use mixin for overflowing texts
  app/assets/stylesheets/content/_advanced_filters.sass
  app/assets/stylesheets/content/_attributes_key_value.sass
  app/assets/stylesheets/content/_attributes_table.sass
  app/assets/stylesheets/content/_forms.sass
  app/assets/stylesheets/content/_pagination.sass
  app/assets/stylesheets/content/_simple_filters.sass
  app/assets/stylesheets/content/_table.sass
  app/assets/stylesheets/content/_wiki.sass
  app/assets/stylesheets/content/menus/_project_autocompletion.sass
  app/assets/stylesheets/content/work_packages/tabs/_activities.sass
  app/assets/stylesheets/content/work_packages/tabs/_relations.sass
  app/assets/stylesheets/layout/_breadcrumb.sass
  app/assets/stylesheets/layout/_main_menu.sass
  app/assets/stylesheets/layout/_top_menu.sass
  app/assets/stylesheets/openproject/_legacy.sass
Labels: styling

#6360 Feature: user limits
  app/assets/javascripts/members_form.js
  app/assets/stylesheets/openproject/_generic.sass
  app/assets/stylesheets/openproject/_index.sass
  app/controllers/account_controller.rb
  app/controllers/concerns/user_limits.rb
  app/controllers/members_controller.rb
  app/controllers/users_controller.rb
  app/helpers/toolbar_helper.rb
  app/views/enterprises/_current.html.erb
  app/views/members/_member_form_non_impaired.html.erb
  app/views/users/index.html.erb
  config/locales/en.yml
  docs/configuration/configuration.md
  lib/open_project/enterprise.rb
  spec/controllers/account_controller_spec.rb
  spec/controllers/users_controller_spec.rb
  spec/lib/open_project/enterprise_spec.rb
  spec/views/users/index.html.erb_spec.rb
Labels: feature, needs-review

#6366 make /health_checks accessible via HTTP
  config/environments/production.rb
Labels: feature, needs-review

#6374 LDAP/OmniAuth on-the-fly registration user limits
  app/controllers/account_controller.rb
  app/controllers/concerns/omniauth_login.rb
  app/models/user.rb
  spec/controllers/account_controller_spec.rb
Labels: bugfix, needs-review

#6375 show instructions on how to upgrade
  app/controllers/enterprises_controller.rb
  config/locales/en.yml
Labels: feature, needs-review

#6379 [27915] Fix initial saving of query with is_public
  frontend/src/app/components/modals/save-modal/save-query.modal.html
  frontend/src/app/components/modals/share-modal/query-sharing-form.component.ts
  spec/features/work_packages/table/queries/query_menu_spec.rb
Labels: bugfix

#6373 notify admins if user could not activate due to the user limit
  app/controllers/account_controller.rb
  app/controllers/concerns/omniauth_login.rb
  app/controllers/concerns/user_limits.rb
  app/mailers/user_mailer.rb
  app/models/user.rb
  app/views/user_mailer/activation_limit_reached.html.erb
  app/views/user_mailer/activation_limit_reached.text.erb
  app/views/users/index.html.erb
  config/application.rb
  config/locales/en.yml
  lib/open_project/enterprise.rb
  lib/redmine/i18n.rb
  spec/controllers/account_controller_spec.rb
Labels: feature, needs-review

#6381 Disable unsafe-eval now that we're on AOT
  app/helpers/angular_helper.rb
  config/initializers/secure_headers.rb
  frontend/angular.json
  frontend/package.json
Labels: housekeeping

#6371 [22316] Feature: Adjustable width of tabs section in wp fullscreen view
  app/assets/stylesheets/layout/_work_package_mobile.sass
  app/assets/stylesheets/layout/_work_package_table_embedded.sass
  app/assets/stylesheets/layout/_work_packages_full_view.sass
  frontend/src/app/components/resizer/main-menu-resizer.component.ts
  frontend/src/app/components/resizer/main-menu-toggle.component.ts
  frontend/src/app/components/resizer/main-menu-toggle.service.ts
  frontend/src/app/components/resizer/wp-resizer.component.ts
  frontend/src/app/components/routing/wp-full-view/wp-full-view.html
  frontend/src/app/components/wp-form-group/wp-attribute-group.template.html
Labels: feature, needs-review

#6386 Fix My Page blocks
  app/assets/javascripts/my_page.js
  app/controllers/my_controller.rb
  app/views/my/_block.html.erb
  app/views/my/add_block.html.erb
  app/views/my/add_block.js.erb
  app/views/my/page.html.erb
  app/views/my/page_layout.html.erb
  app/views/my/remove_block.js.erb
  config/initializers/assets.rb
  config/locales/js-en.yml
  frontend/src/app/modules/common/notifications/notifications.service.ts
  spec/features/my/blocks_spec.rb
Labels: bugfix

#6387 Only request password confirmation when it has been activated
  app/helpers/password_helper.rb
  app/views/users/deletion_info.html.erb
Labels: bugfix

#6388 RxJS cleanup
  frontend/src/app/components/api/op-file-upload/op-file-upload.service.ts
  frontend/src/app/components/resizer/main-menu-resizer.component.ts
  frontend/src/app/components/resizer/main-menu-toggle.service.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-focus.service.ts
  frontend/src/app/components/wp-relations/wp-relations.component.ts
  frontend/src/app/modules/common/focus/focus-within.directive.ts
  frontend/src/app/modules/hal/services/hal-resource-sorting.service.ts
Labels: housekeeping

#6392 [Wiki UX] Remove usage of initial_page_content
  app/controllers/wiki_controller.rb
  app/helpers/text_formatting_helper.rb
  features/wiki/wiki_create_child.feature
  lib/open_project/text_formatting/formatters/markdown/helper.rb
  lib/open_project/text_formatting/formatters/plain/helper.rb
  lib/open_project/text_formatting/formatters/textile/helper.rb
Labels: work in progress

#6362 Fix wiki pages tree in main menu.
  app/assets/javascripts/application.js.erb
  app/assets/stylesheets/layout/_tree_menu.sass
  app/helpers/application_helper.rb
  frontend/src/app/globals/tree-menu.ts
  spec_legacy/unit/lib/redmine/wiki_formatting/macros_spec.rb
Labels: work in progress

#6395 [27940] Don't sort members of attribute groups
  app/models/type/attribute_group.rb
  spec/models/type/attribute_groups_spec.rb
Labels: bugfix

#6397 [27939] Re-add select2 for column selection
  app/assets/stylesheets/content/_modal.sass
  app/assets/stylesheets/vendor/_select2.scss
  config/locales/js-en.yml
  frontend/src/app/components/wp-fast-table/state/wp-table-columns.service.ts
  frontend/src/app/components/wp-table/configuration-modal/tabs/columns-tab.component.html
  frontend/src/app/components/wp-table/configuration-modal/tabs/columns-tab.component.ts
  frontend/src/typings/shims.d.ts
  frontend/vendor/select2/select2.css
  spec/features/work_packages/table/configuration_modal/column_spec.rb
  spec/features/work_packages/table_sorting_spec.rb
  spec/support/components/work_packages/columns.rb
Labels: feature

#6399 Fix breadcrumb alignment && add spaces in WP info row
  app/assets/stylesheets/layout/_breadcrumb.sass
  frontend/src/app/components/work-packages/wp-single-view/wp-single-view.html
  frontend/src/app/modules/common/date/op-date-time.component.ts
Labels: bugfix, styling
