Repository opf/openproject, pull requests merged in 2018-09, with the labels that each got.

#6631 [28431] Don't render attachment with downloadLocation
  docs/api/apiv3/endpoints/attachments.apib
  frontend/src/app/components/api/op-file-upload/op-file-upload.service.ts
  frontend/src/app/modules/hal/resources/mixins/attachable-mixin.ts
  lib/api/v3/attachments/attachment_representer.rb
  lib/api/v3/attachments/attachments_api.rb
  spec/lib/api/v3/attachments/attachment_representer_spec.rb
Labels: bugfix

#6632 [28434] Ensure strikethrough is double-tile everywhere
  app/assets/javascripts/vendor/ckeditor/ckeditor.js
  app/assets/javascripts/vendor/ckeditor/ckeditor.js.map
  docs/user/text-formatting/README.md
  lib/open_project/text_formatting/filters/markdown_filter.rb
Labels: bugfix

#6629 [28425] Accept that remote file can become nil
  app/uploaders/fog_file_uploader.rb
Labels: bugfix

#6634 [28426] Warn empty diffs in journals controller
  app/controllers/journals_controller.rb
  config/locales/en.yml
  spec/support/browsers/chrome.rb
Labels: bugfix

#6637 [28455] Ensure model contracts are initiaited immediately before saving
  app/contracts/custom_actions/cu_contract.rb
  app/contracts/model_contract.rb
  app/contracts/queries/base_contract.rb
  app/contracts/relations/base_contract.rb
  app/contracts/users/base_contract.rb
  app/contracts/work_packages/base_contract.rb
  app/contracts/work_packages/create_note_contract.rb
  app/models/concerns/virtual_attribute.rb
  app/models/mail_handler.rb
  app/models/project/copy.rb
  app/services/add_work_package_note_service.rb
  app/services/concerns/contracted.rb
  app/services/create_work_package_service.rb
  app/services/custom_actions/update_work_package_service.rb
  app/services/queries/create_query_service.rb
  app/services/queries/query_service.rb
  app/services/queries/update_query_service.rb
  app/services/relations/base_service.rb
  app/services/relations/create_service.rb
  app/services/relations/update_service.rb
  app/services/users/create_user_service.rb
  app/services/users/update_user_service.rb
  app/services/work_packages/copy_service.rb
  app/services/work_packages/create_service.rb
  app/services/work_packages/reschedule_service.rb
  app/services/work_packages/set_attributes_service.rb
  app/services/work_packages/update_service.rb
  lib/api/v3/work_packages/form_helper.rb
  spec/lib/api/contracts/model_contract_spec.rb
  spec/services/add_work_package_note_service_spec.rb
  spec/services/create_work_package_service_spec.rb
  spec/services/users/create_user_service_spec.rb
  spec/services/users/update_user_service_spec.rb
  spec/services/work_packages/set_attributes_service_spec.rb
Labels: bugfix

#6635 [28452] Avoid adding a CF multiple times to eager loaded WPs
  lib/api/v3/work_packages/eager_loading/custom_value.rb
  spec/lib/api/v3/work_packages/eager_loading/custom_value_integration_spec.rb
Labels: bugfix, needs-review

#6641 [28086] Add error when moving to milestone with children
  app/contracts/work_packages/update_contract.rb
  config/locales/en.yml
  spec/contracts/work_packages/update_contract_spec.rb
Labels: bugfix

#6642 [28004][28430] Custom Actions: Implement current user assignee and improve performance
  app/models/custom_actions/actions/assigned_to.rb
  config/locales/en.yml
  frontend/legacy/app/components/autocomplete-select-decoration/autocomplete-select-decoration.component.ts
  spec/models/custom_actions/actions/assigned_to_spec.rb
Labels: bugfix, feature

#6650 [28459] Fix initialization of updatedOn/createdOn filter
  frontend/src/app/components/filters/abstract-filter-date-time-value/abstract-filter-date-time-value.controller.ts
  frontend/src/app/components/filters/filter-date-time-value/filter-date-time-value.component.html
  frontend/src/app/components/filters/filter-date-time-value/filter-date-time-value.component.ts
  frontend/src/app/components/filters/filter-date-times-value/filter-date-times-value.component.ts
  spec/features/work_packages/table/queries/filter_spec.rb
Labels: bugfix

#6649 Set lang attribute on integer edit field
  frontend/src/app/modules/fields/edit/field-types/float-edit-field.ts
  frontend/src/app/modules/fields/edit/field-types/integer-edit-field.ts
Labels: bugfix

#6643 [28448] Avoid running into nil project on validation check
  app/models/queries/work_packages/filter/subproject_filter.rb
  spec/models/queries/work_packages/filter/subproject_filter_spec.rb
Labels: bugfix, needs-review

#6653 [28467] Use wiki page slug, not title for link generation
  app/mailers/user_mailer.rb
Labels: bugfix

#6655 [28446] Rename due date to finish date
  app/models/attribute_help_text/work_package.rb
  app/models/project.rb
  app/models/version.rb
  app/models/work_package.rb
  app/models/work_package/scheduling_rules.rb
  config/locales/crowdin/bg.yml
  config/locales/en.seeders.yml
  config/locales/en.yml
  config/locales/js-en.yml
  docs/api/apiv3/endpoints/queries.apib
  docs/api/apiv3/endpoints/work-packages.apib
  docs/configuration/incoming-emails.md
  frontend/src/app/components/wp-table/timeline/cells/timeline-cell-renderer.ts
  frontend/src/app/components/wp-table/timeline/cells/timeline-milestone-cell-renderer.ts
  frontend/src/app/components/wp-table/timeline/container/wp-timeline-container.directive.ts
  frontend/src/app/modules/fields/edit/field-types/date-edit-field.ts
  spec/contracts/work_packages/base_contract_spec.rb
  spec/features/work_packages/table/milestones_spec.rb
  spec/features/work_packages/table/queries/filter_spec.rb
  spec/features/work_packages/timeline/timeline_labels_spec.rb
  spec/lib/api/v3/work_packages/schema/specific_work_package_schema_spec.rb
  spec/lib/api/v3/work_packages/schema/typed_work_package_schema_spec.rb
  spec/lib/api/v3/work_packages/work_package_payload_representer_spec.rb
  spec/lib/api/v3/work_packages/work_package_representer_spec.rb
  spec/models/custom_actions/actions/date_spec.rb
  spec/models/version_spec.rb
  spec/models/work_package/work_package_reschedule_after_spec.rb
  spec/models/work_package/work_package_scheduling_spec.rb
  spec/models/work_package_spec.rb
  spec/requests/api/v3/work_package_resource_spec.rb
  spec/requests/api/v3/work_packages/form/work_package_form_resource_spec.rb
  spec/services/work_packages/update_service_integration_spec.rb
  spec_legacy/unit/project_spec.rb
Labels: feature

#6666 [28471] Don't escape truncate in output for title
  lib/open_project/text_formatting/matchers/link_handlers/work_packages.rb
  spec/lib/open_project/text_formatting/markdown/markdown_spec.rb
Labels: bugfix

#6668 Load styling CSS dynamically
  app/controllers/highlighting_controller.rb
  app/views/layouts/angular.html.erb
  frontend/src/app/components/work-packages/wp-single-view/wp-single-view.component.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-base.service.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-highlighting.service.ts
  frontend/src/app/modules/common/dynamic-css/dynamic-css.service.ts
  frontend/src/app/modules/common/openproject-common.module.ts
Labels: bugfix, feature, needs-review

#6670 [28492] Use manually rendered tag for preview
  app/views/custom_styles/show.html.erb
Labels: bugfix

#6663 [28474] Add border to selected/checked row
  app/assets/stylesheets/content/_tables.sass
  frontend/src/app/components/wp-table/configuration-modal/tabs/display-settings-tab.component.html
  frontend/src/app/components/wp-table/configuration-modal/tabs/highlighting-tab.component.html
  lib/open_project/design.rb
Labels: needs-review, styling

#6671 [28471] Fix encoding and splitting of repo paths
  app/helpers/repositories_helper.rb
  lib/open_project/scm/adapters/base.rb
Labels: bugfix

#6674 [28499] Don't render empty highlighting dots
  app/controllers/highlighting_controller.rb
  app/views/highlighting/styles.css.erb
Labels: bugfix, needs-review, styling

#6677 [28504] Set default fallback color for non-colored types
  app/assets/stylesheets/content/work_packages/timelines/elements/_bar.sass
  app/assets/stylesheets/content/work_packages/timelines/elements/_milestone.sass
Labels: bugfix

#6673 [28484] Add some polyfills to make older browsers function just enough
  app/assets/javascripts/specific/main_menu.js.erb
  frontend/angular.json
  frontend/src/polyfills.ts
  frontend/src/test.ts
Labels: bugfix

#6676 [28504] Avoid initially refresh timeline twice
  frontend/src/app/components/wp-table/timeline/container/wp-timeline-container.directive.ts
Labels: bugfix

#6675 [28490] Recursively clone query props
  frontend/src/app/components/wp-relations/wp-relation-children/wp-children-query.component.ts
  spec/features/types/form_configuration_query_spec.rb
Labels: bugfix

#6679 Consolidate timelineVisible and timelineAutoZoom states
  frontend/src/app/components/wp-fast-table/handlers/state/timeline-transformer.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-timeline.service.ts
  frontend/src/app/components/wp-fast-table/wp-table-timeline.ts
  frontend/src/app/components/wp-table/table-state/table-state.ts
  frontend/src/app/components/wp-table/timeline/container/wp-timeline-container.directive.ts
  frontend/src/app/components/wp-table/timeline/global-elements/wp-timeline-relations.directive.ts
  frontend/src/app/components/wp-table/timeline/wp-timeline.ts
Labels: housekeeping

#6682 [28501] Projects are not truncated correctly in project list
  app/assets/stylesheets/layout/_top_menu.sass
Labels: bugfix, styling

#6683 [28498] Too much padding on homescreen on mobile
  app/assets/stylesheets/openproject/_homescreen.sass
Labels: bugfix, styling

#6685 Add dark borders to highlighting dots with bright colors.
  app/assets/stylesheets/content/_index.sass
  app/assets/stylesheets/content/_tables.sass
  app/assets/stylesheets/layout/_colors.sass
  app/assets/stylesheets/layout/_drop_down.sass
  app/assets/stylesheets/layout/_index.sass
  app/views/highlighting/styles.css.erb
Labels: needs-review

#6684 [28392] Misaligned menu items and menu headlines
  app/assets/stylesheets/layout/_drop_down.sass
  app/assets/stylesheets/layout/_top_menu.sass
Labels: bugfix, styling

#6687 Fix positioning of avatars for watchers
  app/assets/stylesheets/content/_user.sass
Labels: needs-review

#6692 Add check for missing values in resources display field
  frontend/src/app/modules/fields/display/field-types/wp-display-resources-field.module.ts
Labels: bugfix

#6695 Use a gem to correctly parse semantic versions
  Gemfile
  Gemfile.lock
  lib/open_project/database.rb
  spec/lib/database_spec.rb
Labels: bugfix

#6694 [28488] Fix creation of tickets in my page with me filter
  frontend/src/app/components/user/current-user.service.ts
  frontend/src/app/components/wp-edit-form/work-package-filter-values.ts
  frontend/src/app/components/wp-inline-create/wp-inline-create.component.ts
  frontend/src/app/components/wp-new/wp-create.controller.ts
  frontend/src/app/modules/hal/resources/hal-resource.ts
  spec/features/my/assigned_to_me_embedded_table_spec.rb
  spec/support/pages/embedded_work_packages_table.rb
  spec/support/pages/work_packages_table.rb
Labels: bugfix

#6698 [28519] Fix hide-section in my page
  app/models/user.rb
  app/services/update_user_email_settings_service.rb
  app/views/custom_actions/_form.html.erb
  app/views/users/_mail_notifications.html.erb
  frontend/legacy/app/components/hide-section/hide-section.component.ts
  frontend/legacy/app/components/hide-section/show-section-dropdown.component.ts
  spec/features/my/my_notifications_spec.rb
Labels: bugfix

#6701 Refactor CKEditor into single component and allow markdown source
  app/assets/javascripts/forums.js
  app/assets/javascripts/vendor/ckeditor/ckeditor.js
  app/assets/javascripts/vendor/ckeditor/ckeditor.js.map
  app/assets/stylesheets/content/_wiki.sass
  app/cells/rails_cell.rb
  app/helpers/cells_helper.rb
  app/helpers/text_formatting_helper.rb
  app/views/settings/_authentication.html.erb
  app/views/settings/_notifications.html.erb
  app/views/settings/_users.html.erb
  app/views/wiki/_page_form.html.erb
  config/locales/js-en.yml
  frontend/src/app/angular4-modules.ts
  frontend/src/app/ckeditor/ckeditor-augmented-textarea.component.ts
  frontend/src/app/ckeditor/ckeditor-augmented-textarea.html
  frontend/src/app/components/modals/editor/macro-code-block-modal/code-block-macro.modal.ts
  frontend/src/app/modules/common/ckeditor/ckeditor-preview.service.ts
  frontend/src/app/modules/common/ckeditor/ckeditor-setup.service.ts
  frontend/src/app/modules/common/ckeditor/op-ckeditor.component.ts
  frontend/src/app/modules/common/ckeditor/op-ckeditor.html
  frontend/src/app/modules/common/ckeditor/op-ckeditor.sass
  frontend/src/app/modules/common/openproject-common.module.ts
  frontend/src/app/modules/fields/edit/edit-field.component.ts
  frontend/src/app/modules/fields/edit/field-types/formattable-edit-field.component.ts
  frontend/src/app/modules/fields/edit/field-types/formattable-edit-field.ts
  frontend/src/app/modules/plugins/plugin-context.ts
  lib/open_project/form_tag_helper.rb
  lib/open_project/text_formatting/formats/markdown/helper.rb
  lib/tabular_form_builder.rb
  spec/features/work_packages/attachments/attachment_upload_spec.rb
  spec/lib/tabular_form_builder_spec.rb
Labels: feature, housekeeping

#6702 [28524] Disable no_auto_create_user sql_mode
  config/database.yml.example
  config/initializers/check_mysql_flags.rb
  packaging/conf/database.yml
  script/templates/database.travis.mysql.yml
Labels: bugfix

#6703 [28541] Correctly check for upload permission
  app/assets/javascripts/vendor/ckeditor/ckeditor.js
  app/assets/javascripts/vendor/ckeditor/ckeditor.js.map
  spec/features/work_packages/attachments/attachment_upload_spec.rb
  spec/support/components/wysiwyg/wysiwyg_editor.rb
Labels: bugfix

#6706 [28564] Fix highlight in timeline
  frontend/src/app/components/wp-table/timeline/container/wp-timeline-container.directive.ts
Labels: bugfix

#6708 Fix: OP#28562 No automatic scrolling when comment editor opens and activity in reverse
  frontend/src/app/components/work-packages/work-package-comment/work-package-comment.component.ts
Labels: needs-review

#6709 [28556] Correctly check for the index during migrating
  db/migrate/20180510184732_rename_planning_elemnt_type_colors_to_colors.rb
Labels: bugfix

#6712 [28543] Validate Type#attribute_groups in contract
  app/contracts/types/base_contract.rb
  app/models/type/attribute_groups.rb
  app/services/base_type_service.rb
  app/services/create_type_service.rb
  app/services/update_type_service.rb
  spec/models/type/attribute_groups_spec.rb
  spec/services/create_type_service_spec.rb
  spec/services/shared_type_service.rb
  spec/services/update_type_service_spec.rb
Labels: bugfix

#6714 [28578] Fix work package parsing regression.
  lib/open_project/text_formatting/matchers/resource_links_matcher.rb
  spec/lib/open_project/text_formatting/markdown/markdown_spec.rb
Labels: bugfix

#6710 [28539] Fix incorrect handling of queries when quickly loading multiple queries
  frontend/src/app/components/routing/wp-list/wp-list.component.ts
  frontend/src/app/components/wp-list/wp-list.service.ts
  frontend/src/app/components/wp-query-select/wp-static-queries.service.ts
  frontend/src/app/modules/common/loading-indicator/loading-indicator.service.ts
  frontend/src/app/modules/hal/dm-services/query-dm.service.ts
Labels: bugfix, needs-review

#6680 Fix/optimize travis caching
  .travis.yml
  script/ci/cache_prepare.sh
  script/ci/runner.sh
  script/ci/setup.sh
Labels: work in progress

#6722 [28584] Fix query toggle hiding categories
  frontend/src/app/components/wp-query-select/wp-query-select-dropdown.component.ts
Labels: bugfix

#6721 [28609] Fix double newline when editing content with code block
  app/assets/javascripts/vendor/ckeditor/ckeditor.js
  app/assets/javascripts/vendor/ckeditor/ckeditor.js.map
  spec/features/wysiwyg/macros/code_block_macro_spec.rb
Labels: bugfix

#6724 [28580] Correctly replace the work package to avoid invalid update link
  frontend/src/app/components/wp-edit-form/work-package-changeset.ts
  spec/features/work_packages/new/new_work_package_spec.rb
  spec/support/work_packages/work_package_field.rb
Labels: bugfix

#6727 [28588] Fix toggling calendar filters
  app/views/queries/_filters.html.erb
Labels: bugfix

#6725 [28515] Make type highlightable field
  app/assets/stylesheets/layout/work_packages/_full_view.sass
  app/controllers/types_controller.rb
  app/models/query/highlighting.rb
  app/services/service_result.rb
  config/locales/js-en.yml
  frontend/src/app/components/op-context-menu/handlers/op-types-context-menu.directive.ts
  frontend/src/app/components/work-packages/wp-single-view/wp-single-view.component.ts
  frontend/src/app/components/work-packages/wp-type-status/wp-type-status.html
  frontend/src/app/components/wp-edit-form/display-field-renderer.ts
  frontend/src/app/components/wp-edit/wp-edit-field/wp-edit-field.component.ts
  frontend/src/app/components/wp-fast-table/builders/highlighting/highlighting-mode.const.ts
  frontend/src/app/components/wp-table/configuration-modal/tabs/highlighting-tab.component.html
  frontend/src/app/components/wp-table/configuration-modal/tabs/highlighting-tab.component.ts
  frontend/src/app/components/wp-table/wp-table-sums-row/wp-table-sums-row.directive.ts
  frontend/src/app/modules/fields/display/display-field.initializer.ts
  frontend/src/app/modules/fields/display/display-field.module.ts
  frontend/src/app/modules/fields/display/display-field.service.ts
  frontend/src/app/modules/fields/display/field-types/wp-display-highlightable-field.module.ts
  frontend/src/app/modules/fields/edit/edit-field.service.ts
  frontend/src/app/modules/fields/field.base.ts
  frontend/src/app/modules/fields/field.service.ts
Labels: feature, needs-review
