Repository opf/openproject, pull requests merged in 2018-07, with the labels that each got.

#6404 CKEditor: Add embedded table widget
  Gemfile
  Gemfile.lock
  app/assets/javascripts/vendor/ckeditor/ckeditor.js
  app/assets/javascripts/vendor/ckeditor/ckeditor.js.map
  config/locales/js-en.yml
  frontend/legacy/app/components/type-configuration/type-configuration.controller.ts
  frontend/src/app/angular4-modules.ts
  frontend/src/app/components/ckeditor/op-ckeditor-form.component.ts
  frontend/src/app/components/input/auto-complete-helper.service.ts
  frontend/src/app/components/wp-table/embedded/embedded-tables-macro.component.ts
  frontend/src/app/components/wp-table/external-configuration/external-query-configuration.component.ts
  frontend/src/app/components/wp-table/external-configuration/external-query-configuration.constants.ts
  frontend/src/app/components/wp-table/external-configuration/external-query-configuration.service.ts
  frontend/src/app/modules/common/notifications/notifications.service.ts
  lib/open_project/text_formatting/filters/markdown_filter.rb
  lib/open_project/text_formatting/filters/sanitization_filter.rb
  spec/features/wysiwyg/macros/embedded_tables_spec.rb
  spec/support/components/work_packages/table_configuration_modal.rb
Labels: feature

#6406 Allow Webpack to do tree-shaking by generating code with import/export.
  frontend/legacy/tsconfig.json
  frontend/legacy/webpack.config.js
  frontend/npm-shrinkwrap.json
  frontend/package.json
Labels: housekeeping

#6405 use application job to send delayed user mails
  app/workers/mail_user_job.rb
  lib/open_project/enterprise.rb
Labels: bugfix, needs-review

#6403 show imminent user limit warning
  app/controllers/concerns/user_limits.rb
  config/locales/en.yml
  lib/open_project/enterprise.rb
Labels: feature, needs-review

#6408 [27951][27952] Convert macro syntax and show warning for legacy macro
  app/assets/stylesheets/content/editor/_ckeditor.sass
  app/assets/stylesheets/content/editor/_macros.sass
  config/locales/en.yml
  lib/open_project/text_formatting/formatters/markdown/textile_converter.rb
Labels: feature

#6409 [27971] Close active edit fields and datepickers before refreshing
  frontend/src/app/components/wp-fast-table/builders/modes/hierarchy/single-hierarchy-row-builder.ts
  frontend/src/app/components/wp-fast-table/builders/primary-render-pass.ts
  frontend/src/app/components/wp-fast-table/builders/relations/relations-render-pass.ts
  frontend/src/app/components/wp-fast-table/builders/rows/single-row-builder.ts
  frontend/src/app/components/wp-fast-table/wp-fast-table.ts
  frontend/src/app/components/wp-inline-create/wp-inline-create.component.ts
  frontend/src/app/modules/common/op-date-picker/datepicker.ts
  frontend/src/app/modules/common/op-date-picker/op-date-picker.component.ts
Labels: bugfix

#6411 support plugins in the docker container
  docker/entrypoint
Labels: feature, needs-review

#6413 don't warn twice
  app/controllers/concerns/user_limits.rb
  app/controllers/users_controller.rb
Labels: bugfix, needs-review

#6416 [27808] Column hover effect on WP tables is broken
  frontend/src/app/modules/common/highlight-col/highlight-col.directive.ts
  frontend/src/app/modules/common/openproject-common.module.ts
Labels: bugfix, styling

#6415 Add inline code to ckeditor
  app/assets/javascripts/vendor/ckeditor/ckeditor.js
  app/assets/javascripts/vendor/ckeditor/ckeditor.js.map
Labels: feature

#6420 [27948] Workflow table layout broken
  app/assets/stylesheets/content/_headings.sass
  app/assets/stylesheets/content/_tables.sass
  app/assets/stylesheets/openproject/_generic.sass
  app/views/workflows/_form.html.erb
Labels: bugfix, styling

#6306 [27512] Add language selection as first step when entering a new trial installation
  app/assets/stylesheets/content/_modal.sass
  app/controllers/my_controller.rb
  app/controllers/onboarding_controller.rb
  app/services/users/update_service.rb
  app/views/layouts/base.html.erb
  app/views/onboarding/_configuration_modal.html.erb
  app/views/onboarding/_menu_item.html.erb
  app/views/onboarding/_onboarding_video_modal.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/my_controller_spec.rb
Labels: feature, needs-review

#6419 Timeline fixes/improvements
  frontend/npm-shrinkwrap.json
  frontend/src/app/components/wp-table/timeline/container/wp-timeline-container.directive.ts
  frontend/src/app/components/wp-table/timeline/header/wp-timeline-header.directive.ts
  frontend/src/app/components/wp-table/timeline/wp-timeline.ts
Labels: bugfix

#6414 [27975] Call update_ancestors in bulk controller
  app/controllers/work_packages/bulk_controller.rb
Labels: bugfix, needs-review

#6424 Add static CKEditor help link
  app/assets/javascripts/vendor/ckeditor/ckeditor.js
  app/assets/javascripts/vendor/ckeditor/ckeditor.js.map
  frontend/src/app/components/ckeditor/op-ckeditor-form.component.ts
  frontend/src/app/modules/common/path-helper/path-helper.service.ts
  frontend/src/app/modules/fields/edit/field-types/formattable-edit-field.ts
  lib/open_project/text_formatting/formatters/markdown/helper.rb
Labels: feature

#6426 [25135] Warn on leaving unsafed outside edit mode
  frontend/src/app/components/wp-edit-form/work-package-edit-form.ts
  frontend/src/app/components/wp-edit/wp-edit-field/wp-edit-field-group.directive.ts
  frontend/src/app/components/wp-form-group/wp-attribute-group.component.ts
  frontend/src/app/modules/common/edit-actions-bar/wp-edit-actions-bar.component.ts
  spec/features/work_packages/cancel_editing_spec.rb
Labels: bugfix

#6428 [27946] Bugs in mobile view
  app/assets/stylesheets/layout/_base_mobile.sass
  app/assets/stylesheets/layout/_toolbar.sass
  app/assets/stylesheets/openproject/_legacy.sass
Labels: bugfix, styling

#6430 [28017] Disable autocomplete for all datepicker fields
  app/helpers/application_helper.rb
  frontend/src/app/modules/common/op-date-picker/datepicker.ts
Labels: bugfix

#6431 Create and redirect to text formatting help, but allow override
  app/controllers/help_controller.rb
  config/routes.rb
  docs/user/text-formatting/README.md
  frontend/src/app/modules/common/path-helper/path-helper.service.ts
  lib/open_project/configuration.rb
  lib/open_project/static/links.rb
Labels: feature

#6435 Fix highlight class being used in rouge highlighting
  app/assets/stylesheets/content/_index.sass
  app/assets/stylesheets/content/_search.sass
  app/assets/stylesheets/openproject/_legacy.sass
  app/helpers/search_helper.rb
  spec/helpers/search_helper_spec.rb
Labels: styling

#6443 [27947] Filter by commit date for changeset activity provider
  app/models/activity/base_activity_provider.rb
  app/models/activity/changeset_activity_provider.rb
  lib/plugins/acts_as_activity_provider/lib/acts_as_activity_provider.rb
Labels: bugfix

#6444 [28030] Styling issues in embedded tables
  app/assets/stylesheets/content/_table.sass
  app/assets/stylesheets/layout/_work_package_table_embedded.sass
Labels: bugfix, styling

#6440 [27235] Clear tmp:cache through cronjob
  .pkgr.yml
  packaging/cron/openproject-clear-tmp-cache
Labels: housekeeping

#6447 [27934] Avoid bulk copying children more than once
  app/assets/stylesheets/content/_contextual.lsg
  app/assets/stylesheets/content/_contextual.sass
  app/assets/stylesheets/content/_index.sass
  app/controllers/work_packages/moves_controller.rb
  app/views/work_packages/moves/new.html.erb
  config/locales/en.yml
  spec/controllers/work_packages/moves_controller_spec.rb
Labels: bugfix

#6449 npm audit
  frontend/npm-shrinkwrap.json
  frontend/package.json
Labels: housekeeping

#6450 Allow bootstrapping in legacy context
  frontend/legacy/typings/open-project-legacy.typings.d.ts
  frontend/src/app/components/ckeditor/ckeditor-setup.service.ts
  frontend/src/app/components/ckeditor/op-ckeditor-form.component.ts
  frontend/src/app/modules/plugins/plugin-context.ts
  spec/support/components/wysiwyg/wysiwyg_editor.rb
Labels: bugfix

#6453 [28066] Fix duplicate label names in membership create/edit
  app/controllers/groups_controller.rb
  app/models/permitted_params.rb
  app/views/groups/_memberships.html.erb
  spec/support/pages/groups.rb
  spec_legacy/functional/groups_controller_spec.rb
Labels: bugfix

#6454 [28076] Fix registration modal on login
  app/views/account/_password_login_form.html.erb
  app/views/account/_register.html.erb
  frontend/src/app/components/projects/project-menu-autocomplete/project-menu-autocomplete.component.ts
  frontend/src/app/globals/augmenting/modal-wrapper.augment.service.ts
  spec/features/users/self_registration_spec.rb
Labels: bugfix

#6455 [28083] Correctly set active on wp-edit-field
  frontend/src/app/components/wp-edit-form/single-view-edit-context.ts
  frontend/src/app/components/wp-edit/wp-edit-field/wp-edit-field.html
Labels: bugfix

#6456 [28091] Fix project responsible and add spec
  app/assets/stylesheets/vendor/_select2.scss
  app/models/user.rb
  spec/features/projects/project_responsible_spec.rb
Labels: bugfix

#6457 [28090] Restore focus on subject fields in (inline) create
  frontend/src/app/components/wp-edit-form/work-package-edit-form.ts
  frontend/src/app/components/wp-edit/wp-edit-field/wp-edit-field-group.directive.ts
  frontend/src/app/components/wp-edit/wp-edit-field/wp-edit-field.component.ts
  frontend/src/app/modules/common/focus/focus-helper.ts
  frontend/src/app/modules/fields/edit/field-types/formattable-edit-field.ts
  frontend/src/app/modules/fields/edit/field-types/text-edit-field.ts
  spec/features/work_packages/new/new_work_package_spec.rb
  spec/features/work_packages/table/inline_create/create_work_packages_spec.rb
Labels: bugfix

#6460 [28099] Close active edited resource when changing type
  frontend/src/app/modules/fields/edit/edit-field.component.ts
  spec/features/work_packages/table/switch_types_spec.rb
Labels: bugfix

#6461 [27789] Don't prevent default on all accessible clicks
  frontend/src/app/components/op-context-menu/op-context-menu.html
  frontend/src/app/modules/a11y/accessible-click.directive.ts
Labels: bugfix

#6464 [28104] Fix opening help modal, instead open new window
  app/assets/javascripts/application.js.erb
  app/assets/javascripts/modal.js
  app/views/help/keyboard_shortcuts.erb
  frontend/src/app/modules/a11y/keyboard-shortcut-service.ts
Labels: bugfix

#6465 [28103] Fix reorder my page blocks
  app/assets/javascripts/my_page.js
  app/controllers/my_controller.rb
  app/views/my/page_layout.html.erb
Labels: bugfix

#6466 [28105] Fix click on button in formattable not going through
  frontend/src/app/components/wp-edit/wp-edit-field/wp-edit-field.component.ts
  frontend/src/app/components/wp-edit/wp-edit-field/wp-edit-field.html
Labels: bugfix

#6468 [28108] Fix user mentions when only project href exists
  app/assets/javascripts/vendor/ckeditor/ckeditor.js
  app/assets/javascripts/vendor/ckeditor/ckeditor.js.map
Labels: bugfix

#6467 [28088] Line shown next to embedded tables
  app/assets/stylesheets/content/_wiki.sass
  app/assets/stylesheets/layout/_work_package_table_embedded.sass
  app/assets/stylesheets/openproject/_legacy.sass
Labels: bugfix, styling

#6471 [27946] Bugs in mobile view (2)
  app/assets/stylesheets/layout/_toolbar_mobile.sass
  app/assets/stylesheets/openproject/_legacy.sass
  app/views/versions/_overview.html.erb
Labels: bugfix, styling

#6473 [28115] MultiCF controls cannot be clicked
  app/assets/stylesheets/content/work_packages/inplace_editing/_textareas.sass
Labels: bugfix, styling

#6469 [28110] Address issues on wp table configuration modal
  config/locales/js-en.yml
  frontend/src/app/components/op-context-menu/handlers/op-settings-dropdown-menu.directive.ts
  frontend/src/app/components/wp-table/configuration-modal/wp-table-configuration.service.ts
  spec/features/types/form_configuration_query_spec.rb
  spec/features/wysiwyg/macros/embedded_tables_spec.rb
  spec/support/components/work_packages/table_configuration/filters.rb
Labels: bugfix

#6472 [27090] Increase width of custom field "Text" attribute fields (2)
  frontend/src/app/components/wp-form-group/wp-attribute-group.template.html
Labels: bugfix, styling

#6475 [28112] Embedded timeline styling issues
  app/assets/stylesheets/content/_wiki.sass
  app/assets/stylesheets/content/work_packages/timelines/_timelines_header.sass
  app/assets/stylesheets/content/work_packages/timelines/elements/_labels.sass
  app/assets/stylesheets/layout/_work_package_table_embedded.sass
  frontend/src/app/components/wp-fast-table/state/wp-table-selection.service.ts
  frontend/src/app/components/wp-list/wp-states-initialization.service.ts
  frontend/src/app/components/wp-table/embedded/wp-embedded-table.component.ts
Labels: bugfix, styling

#6477 [28121] Focus not set to text box when quoting forum entry
  app/assets/javascripts/forums.js
  app/views/messages/_form.html.erb
Labels: bugfix

#6476 [28120] Set location.href when outside wp-base application
  frontend/src/app/components/routing/first-route-service.ts
  frontend/src/app/components/routing/main/work-packages-base.component.ts
  frontend/src/app/components/routing/ui-router.config.ts
  spec/features/wysiwyg/macros/embedded_tables_spec.rb
Labels: bugfix

#6479 [28117] Fall back to project if specific preview missing
  app/helpers/text_formatting_helper.rb
Labels: bugfix
