Repository opf/openproject, pull requests merged in 2018-08, with the labels that each got.

#6481 [28124] Avoid markdown table output
  app/assets/javascripts/vendor/ckeditor/ckeditor.js
  app/assets/javascripts/vendor/ckeditor/ckeditor.js.map
  app/assets/stylesheets/content/_wiki.sass
  app/assets/stylesheets/content/editor/_ckeditor.sass
  spec/features/wysiwyg/tables_spec.rb
  spec/support/components/wysiwyg/wysiwyg_editor.rb
Labels: bugfix

#6482 [27406] Rename responsible to accountable
  app/controllers/project_types_controller.rb
  app/controllers/projects_controller.rb
  app/helpers/projects_helper.rb
  app/models/permitted_params.rb
  app/models/project.rb
  app/models/project_type.rb
  app/models/type/attributes.rb
  app/models/user.rb
  app/seeders/basic_data/project_type_seeder.rb
  app/seeders/basic_data/workflow_seeder.rb
  app/seeders/basic_data_seeder.rb
  app/views/project_types/_form.html.erb
  app/views/project_types/confirm_destroy.html.erb
  app/views/project_types/edit.html.erb
  app/views/project_types/index.html.erb
  app/views/project_types/new.html.erb
  app/views/projects/form/_project_attributes.html.erb
  app/views/projects/form/attributes/_project_type_id.html.erb
  app/views/projects/form/attributes/_responsible_id.html.erb
  config/configuration.yml.example
  config/initializers/menus.rb
  config/locales/en.yml
  config/locales/js-en.yml
  config/routes.rb
  db/migrate/20180801072018_remove_responsible_and_type_from_project.rb
  features/step_definitions/project_steps.rb
  features/step_definitions/project_type_steps.rb
  lib/api/v3/projects/project_representer.rb
  spec/controllers/copy_projects_controller_spec.rb
  spec/controllers/project_types_controller_spec.rb
  spec/factories/project_type_factory.rb
  spec/features/project_types/project_type_administration_spec.rb
  spec/features/projects/project_responsible_spec.rb
  spec/features/types/form_configuration_spec.rb
  spec/lib/api/v3/projects/project_representer_spec.rb
  spec/lib/api/v3/work_packages/schema/work_package_schema_representer_spec.rb
  spec/models/permitted_params_spec.rb
  spec/models/project_type_spec.rb
  spec/models/user_deletion_spec.rb
  spec/requests/api/v3/work_package_resource_spec.rb
  spec/requests/api/v3/work_packages/form/work_package_form_resource_spec.rb
  spec_legacy/unit/project_spec.rb
Labels: feature

#6483 [28137] Fix click on image upload
  app/assets/stylesheets/content/editor/_ckeditor.sass
  frontend/package.json
  frontend/src/app/components/wp-fast-table/handlers/row/click-handler.ts
  frontend/src/app/globals/global-listeners.ts
  frontend/src/app/init-globals.ts
  frontend/src/app/modules/fields/edit/editing-portal/edit-form-portal.component.html
Labels: bugfix

#6487 Wiki page: Don't call to_i on parent_id
  app/controllers/wiki_controller.rb
Labels: bugfix

#6486 Wiki quick wins: Add editable toolbar and zen button
  app/assets/stylesheets/content/_editable_toolbar.lsg
  app/assets/stylesheets/content/_editable_toolbar.sass
  app/assets/stylesheets/content/_forms.sass
  app/assets/stylesheets/content/_index.sass
  app/assets/stylesheets/layout/_zen_mode.sass
  app/helpers/toolbar_helper.rb
  app/views/wiki/_page_form.html.erb
  app/views/wiki/edit.html.erb
  app/views/wiki/new.html.erb
  config/locales/en.yml
  frontend/src/app/angular4-modules.ts
  frontend/src/app/components/routing/wp-full-view/wp-full-view.html
  frontend/src/app/components/routing/wp-list/wp.list.component.html
  frontend/src/app/components/wp-buttons/wp-button.template.html
  frontend/src/app/components/wp-buttons/wp-buttons.module.ts
  frontend/src/app/components/wp-buttons/wp-details-view-button/wp-details-view-button.component.ts
  frontend/src/app/components/wp-buttons/wp-filter-button/wp-filter-button.component.ts
  frontend/src/app/components/wp-buttons/wp-filter-button/wp-filter-button.html
  frontend/src/app/components/wp-buttons/wp-timeline-toggle-button/wp-timeline-toggle-button.component.ts
  frontend/src/app/components/wp-buttons/zen-mode-toggle-button/zen-mode-toggle-button.component.ts
  frontend/src/app/components/wp-new/wp-new-full-view.html
  lib/tabular_form_builder.rb
  spec/views/wiki/new.html.erb_spec.rb
Labels: feature

#6489 Hide attachment list when attachments are empty
  frontend/src/app/components/attachments/attachments.component.ts
  frontend/src/app/components/attachments/attachments.html
  frontend/src/app/modules/hal/resources/mixins/attachable-mixin.ts
Labels: bugfix

#6490 [28141] drag-and-drop images and attachments into open and closed editors
  app/assets/stylesheets/content/work_packages/single_view/_attachments.sass
  config/locales/js-en.yml
  frontend/src/app/components/attachments/attachment-list/attachment-list-item.component.ts
  frontend/src/app/components/attachments/attachment-list/attachment-list-item.html
  frontend/src/app/components/work-packages/work-package-comment/work-package-comment.component.html
  frontend/src/app/components/work-packages/work-package-comment/work-package-comment.component.ts
  frontend/src/app/components/work-packages/wp-single-view/wp-single-view.html
  frontend/src/app/components/wp-edit/wp-edit-field/wp-edit-field-group.directive.ts
  frontend/src/app/components/wp-edit/wp-edit-field/wp-edit-field.component.ts
  frontend/src/app/components/wp-edit/wp-edit-field/wp-edit-field.html
  frontend/src/app/components/wp-form-group/wp-attribute-group.template.html
Labels: feature

#6488 [27873] Overlapping menus in mobile view
  app/assets/javascripts/top_menu.js
  app/assets/stylesheets/layout/_base_mobile.sass
  app/assets/stylesheets/layout/_main_menu_mobile.sass
  app/assets/stylesheets/layout/_toolbar.sass
  app/assets/stylesheets/layout/_toolbar_mobile.sass
  app/assets/stylesheets/layout/_top_menu_mobile.sass
  app/assets/stylesheets/layout/_work_package_mobile.sass
Labels: bugfix, styling

#6494 BUG #28153: Attachments are not reloaded on query results
  frontend/src/app/components/attachments/attachment-list/attachment-list.component.ts
Labels: bugfix

#6495 [28150] Cached avatar image
  frontend/src/app/components/wp-activity/user/user-activity.component.html
  lib/api/caching/cached_representer.rb
  lib/api/v3/users/user_representer.rb
  lib/api/v3/work_packages/work_package_representer.rb
  lib/open_project/cache/cache_key.rb
Labels: bugfix

#6496 [28163] Show an error when WP page can be accessed, but WP not loaded
  frontend/package.json
  frontend/src/app/components/work-packages/work-package-cache.service.ts
Labels: bugfix

#6497 [28155] Replace calendar_for with global augmented datepickers
  app/helpers/application_helper.rb
  app/helpers/custom_fields_helper.rb
  app/views/announcements/edit.html.erb
  app/views/custom_actions/_form.html.erb
  app/views/projects/filters/date/_between_dates.html.erb
  app/views/projects/filters/date/_on_date.html.erb
  app/views/timelog/_date_range.html.erb
  app/views/timelog/edit.html.erb
  app/views/versions/_form.html.erb
  app/views/work_packages/bulk/edit.html.erb
  app/views/work_packages/moves/new.html.erb
  frontend/src/app/globals/global-listeners.ts
  frontend/src/app/globals/global-listeners/augmented-date-picker.ts
  frontend/src/app/globals/global-listeners/link-hijacking.ts
  frontend/src/app/misc/datepicker-defaults.js
  lib/custom_field_form_builder.rb
  spec/lib/custom_field_form_builder_spec.rb
Labels: feature

#6499 [28148] Fix search shortcut
  app/assets/javascripts/application.js.erb
  frontend/src/app/components/expandable-search/expandable-search.component.html
  frontend/src/app/globals/global-listeners.ts
  frontend/src/app/globals/global-listeners/link-hijacking.ts
  frontend/src/app/init-vendors.js
  frontend/src/app/modules/a11y/keyboard-shortcut-service.ts
Labels: bugfix

#6500 Fix/modal cdref
  frontend/src/app/components/modals/confirm-dialog/confirm-dialog.modal.ts
  frontend/src/app/components/modals/editor/macro-child-pages-modal/child-pages-macro.modal.ts
  frontend/src/app/components/modals/editor/macro-code-block-modal/code-block-macro.modal.ts
  frontend/src/app/components/modals/editor/macro-wiki-include-page-modal/wiki-include-page-macro.modal.ts
  frontend/src/app/components/modals/editor/macro-wp-button-modal/wp-button-macro.modal.ts
  frontend/src/app/components/modals/export-modal/wp-table-export.modal.ts
  frontend/src/app/components/modals/modal-wrapper/dynamic-content.modal.ts
  frontend/src/app/components/modals/save-modal/save-query.modal.ts
  frontend/src/app/components/modals/share-modal/query-sharing.modal.ts
  frontend/src/app/components/modals/wp-destroy-modal/wp-destroy.modal.ts
  frontend/src/app/components/op-modals/op-modal.component.ts
  frontend/src/app/components/wp-table/configuration-modal/wp-table-configuration.modal.ts
  frontend/src/app/globals/global-listeners/link-hijacking.ts
  frontend/src/app/modules/common/help-texts/attribute-help-text.modal.ts
Labels: bugfix

#6493 [28147] Show results on focus in select decoration
  frontend/legacy/app/components/autocomplete-select-decoration/autocomplete-select-decoration.component.ts
  spec/features/work_packages/custom_actions_spec.rb
  spec/support/pages/abstract_work_package.rb
  spec/support/pages/admin/custom_actions/edit.rb
  spec/support/pages/admin/custom_actions/form.rb
  spec/support/pages/admin/custom_actions/index.rb
  spec/support/pages/admin/custom_actions/new.rb
  spec/support/pages/page.rb
Labels: bugfix

#6504 [28151] Get the three newest activities
  frontend/src/app/components/wp-single-view-tabs/activity-panel/activity-on-overview.component.ts
Labels: bugfix

#6498 use absolute URLs for user mentions so they work in emails too
  lib/open_project/object_linking.rb
  lib/open_project/text_formatting/matchers/link_handlers/colon_separator.rb
  lib/open_project/text_formatting/matchers/link_handlers/hash_separator.rb
  spec/lib/open_project/text_formatting/markdown/markdown_formatting_spec.rb
Labels: bugfix, needs-review

#6505 [28167][27973] Allow embedded table macros in WP description
  app/assets/javascripts/vendor/ckeditor/ckeditor.js
  app/assets/javascripts/vendor/ckeditor/ckeditor.js.map
  app/assets/stylesheets/content/work_packages/inplace_editing/_edit_fields.sass
  frontend/src/app/components/ckeditor/ckeditor-setup.service.ts
  frontend/src/app/components/work-packages/work-package-cache.service.ts
  frontend/src/app/components/wp-edit/wp-edit-field/wp-edit-field.component.ts
  frontend/src/app/modules/fields/display/field-types/wp-display-formattable-field.module.ts
  frontend/src/app/modules/fields/edit/field-types/formattable-edit-field.ts
  spec/features/wysiwyg/macros/embedded_tables_spec.rb
Labels: bugfix, feature

#6507 [28171] Output claimed attachments on wiki representer
  lib/api/v3/attachments/attachable_representer_mixin.rb
  spec/features/wiki/attachment_upload_spec.rb
Labels: bugfix

#6508 [28115] Don't show multi-CF controls in single select
  frontend/src/app/modules/fields/edit/field-types/multi-select-edit-field.component.html
Labels: bugfix

#6509 [28151] Fix activity numbers when taking newest elements
  frontend/src/app/components/wp-single-view-tabs/activity-panel/activity-on-overview.component.ts
Labels: bugfix

#6511 [28170] Remove Global selector affecting all timeline instances
  frontend/src/app/components/wp-fast-table/handlers/state/timeline-transformer.ts
  frontend/src/app/components/wp-table/embedded/wp-embedded-table-entry.component.ts
Labels: bugfix

#6510 ensure correct encoding on MySQL connections
  config/initializers/check_mysql_encoding.rb
  lib/open_project/database.rb
Labels: feature, needs-review

#6513 Update to Angular 6.1.2
  frontend/legacy/app/components/hide-section/add-section-dropdown/add-section-dropdown.component.ts
  frontend/npm-shrinkwrap.json
  frontend/package.json
Labels: housekeeping

#6515 [28187] Fix showing default query names
  frontend/src/app/components/angular/tracking-functions.ts
  frontend/src/app/components/filters/filter-container/filter-container.directive.ts
  frontend/src/app/components/filters/query-filter/query-filter.component.html
  frontend/src/app/components/filters/query-filter/query-filter.component.ts
  frontend/src/app/components/filters/query-filters/query-filters.component.html
  frontend/src/app/components/filters/query-filters/query-filters.component.ts
  frontend/src/app/components/routing/wp-list/wp-list.component.ts
  frontend/src/app/components/wp-fast-table/handlers/state/rows-transformer.ts
  frontend/src/app/components/wp-list/wp-list-checksum.service.ts
  frontend/src/app/components/wp-query-select/wp-query-select-dropdown.component.ts
  frontend/src/app/components/wp-table/wp-table.directive.ts
  frontend/src/app/helpers/debug_output.ts
Labels: bugfix

#6518 [28185] Fix wiki history and annotate
  app/models/journal/base_journal.rb
  app/models/wiki_page.rb
  app/views/wiki/history.html.erb
Labels: bugfix

#6519 [28194] Make TOC widget selectable
  app/assets/javascripts/vendor/ckeditor/ckeditor.js
  app/assets/javascripts/vendor/ckeditor/ckeditor.js.map
Labels: bugfix

#6521 [28189] Fix attachment uploading on wp-new
  frontend/src/app/modules/hal/resources/mixins/attachable-mixin.ts
  spec/features/work_packages/attachments/attachment_upload_spec.rb
Labels: bugfix

#6522 [28209] Better error handling on attachment upload
  frontend/src/app/components/modals/save-modal/save-query.modal.ts
  frontend/src/app/components/work-packages/work-package-cache.service.ts
  frontend/src/app/components/wp-activity/comment-service.ts
  frontend/src/app/components/wp-custom-actions/wp-custom-actions/wp-custom-action.component.ts
  frontend/src/app/components/wp-edit-form/work-package-changeset.ts
  frontend/src/app/components/wp-edit-form/work-package-edit-form.ts
  frontend/src/app/components/wp-edit/wp-notification.service.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-additional-elements.service.ts
  frontend/src/app/components/wp-new/wp-create.controller.ts
  frontend/src/app/components/wp-relations/wp-relation-add-child/wp-relation-add-child.ts
  frontend/src/app/components/wp-relations/wp-relation-row/wp-relation-row.component.ts
  frontend/src/app/components/wp-relations/wp-relations-create/wp-relations-create.component.ts
  frontend/src/app/components/wp-relations/wp-relations-hierarchy/wp-relations-hierarchy.service.ts
  frontend/src/app/components/wp-relations/wp-relations-parent/wp-relations-parent.component.ts
  frontend/src/app/components/wp-table/timeline/cells/wp-timeline-cell-mouse-handler.ts
  frontend/src/app/components/wp-table/timeline/container/wp-timeline-container.directive.ts
  frontend/src/app/modules/common/notifications/upload-progress.component.ts
  frontend/src/app/modules/hal/resources/mixins/attachable-mixin.ts
  frontend/src/app/modules/hal/resources/work-package-resource.spec.ts
Labels: bugfix

#6517 [28188] Make wiki content text not required
  app/controllers/wiki_controller.rb
  app/helpers/toolbar_helper.rb
  app/models/wiki_content.rb
  app/views/wiki/edit.html.erb
  spec/features/wiki/attachment_upload_spec.rb
Labels: feature

#6524 [28207] Disable wysiwyg macros in work packages
  app/assets/javascripts/vendor/ckeditor/ckeditor.js
  app/assets/javascripts/vendor/ckeditor/ckeditor.js.map
  frontend/src/app/components/ckeditor/ckeditor-setup.service.ts
  frontend/src/app/components/ckeditor/op-ckeditor-form.component.ts
  frontend/src/app/modules/fields/edit/field-types/formattable-edit-field.ts
  spec/features/wysiwyg/macros/embedded_tables_spec.rb
Labels: feature

#6523 [28186] Fix formatting journal details in no_html_mode
  app/models/work_package/pdf_export/work_package_to_pdf.rb
  config/locales/en.yml
  lib/plugins/acts_as_journalized/lib/journal_formatter/base.rb
  lib/plugins/acts_as_journalized/lib/journal_formatter/named_association.rb
  spec/lib/journal_formatter/custom_field_spec.rb
  spec/mailers/user_mailer_spec.rb
  spec_legacy/unit/repository_spec.rb
Labels: bugfix

#6526 [28205] Remove HTML export wiki and rename txt to markdown
  app/controllers/wiki_controller.rb
  app/views/wiki/export.html.erb
  app/views/wiki/show.html.erb
  config/routes.rb
  spec/routing/wiki_routing_spec.rb
Labels: feature

#6528 [28208] Re-add codeBlock, quote, image button to comments
  app/assets/javascripts/vendor/ckeditor/ckeditor.js
  app/assets/javascripts/vendor/ckeditor/ckeditor.js.map
  frontend/src/app/components/angular/tracking-functions.ts
  frontend/src/app/components/wp-activity/user/user-activity.component.ts
  frontend/src/app/components/wp-single-view-tabs/activity-panel/activity-entry-info.ts
  frontend/src/app/components/wp-single-view-tabs/activity-panel/activity-on-overview.component.ts
  frontend/src/app/components/wp-single-view-tabs/activity-panel/activity-on-overview.html
  frontend/src/app/components/wp-single-view-tabs/activity-panel/activity-tab.component.ts
  frontend/src/app/components/wp-single-view-tabs/activity-panel/activity-tab.html
Labels: feature

#6525 [28193] Make outer container of display field a div
  app/assets/stylesheets/content/work_packages/inplace_editing/_edit_fields.sass
  frontend/src/app/modules/fields/display/field-types/wp-display-formattable-field.module.ts
Labels: bugfix

#6529 [28206] Consolidate margins in toolbars
  app/assets/stylesheets/layout/_toolbar.sass
  app/assets/stylesheets/layout/work_packages/_table.sass
  frontend/src/app/components/wp-query-select/wp-query-selectable-title.html
  frontend/src/app/components/wp-query-select/wp-query-selectable-title.sass
Labels: feature

#6530 fixed autozoom
  frontend/src/app/components/wp-table/timeline/container/wp-timeline-container.directive.ts
  frontend/src/app/components/wp-table/timeline/wp-timeline.ts
Labels: bugfix

#6531 [28220] Fix links to community
  app/views/homescreen/blocks/_community.html.erb
  lib/open_project/static/links.rb
Labels: bugfix

#6533 [28226] Fix mail notification double escape
  app/controllers/admin_controller.rb
  spec/features/admin/test_mail_notification_spec.rb
Labels: bugfix

#6534 [28270][28236][28197][28200][28204] Query menu select mixed bag
  app/assets/stylesheets/layout/work_packages/_query_menu.sass
  frontend/src/app/components/wp-query-select/wp-query-select-dropdown.component.ts
  frontend/src/app/modules/common/path-helper/apiv3/apiv3-paths.ts
  frontend/src/app/modules/hal/dm-services/relations-dm.service.ts
Labels: bugfix

#6535 [28281] Remove filler ckeditor cells
  app/assets/javascripts/vendor/ckeditor/ckeditor.js
  app/assets/javascripts/vendor/ckeditor/ckeditor.js.map
Labels: bugfix

#6538 [28187] Fix all open static query name
  frontend/src/app/components/routing/wp-list/wp-list.component.ts
  frontend/src/app/components/wp-query-select/wp-static-queries.service.ts
  spec/features/work_packages/pagination_spec.rb
  spec/features/work_packages/table/queries/query_history_spec.rb
  spec/features/work_packages/work_package_index_spec.rb
Labels: bugfix

#6541 [28286] Wrong layout for attribute help texts
  frontend/src/app/modules/common/help-texts/attribute-help-text.modal.ts
  frontend/src/app/modules/common/help-texts/help-text.modal.html
Labels: bugfix

#6540 [28231] Wrong margins in work packages table (mobile)
  app/assets/stylesheets/layout/_toolbar_mobile.sass
  app/assets/stylesheets/layout/work_packages/_mobile.sass
Labels: bugfix, styling

#6542 [28304] Wrong distance between work package toolbar items
  app/assets/stylesheets/layout/_toolbar.sass
Labels: bugfix, styling

#6491 [27253] Custom actions: Design buttons in WP full and split view
  app/assets/stylesheets/content/_custom_actions.sass
  app/assets/stylesheets/content/work_packages/single_view/_single_view.sass
  frontend/src/app/components/resizer/wp-resizer.component.ts
Labels: needs-review, styling

#6545 [28230][28291] Minor styling issues
  app/assets/stylesheets/content/_forms.sass
  app/assets/stylesheets/layout/_main_menu.sass
Labels: bugfix, styling

#6547 [28294] Make news description actually optional
  app/models/news.rb
  app/views/news/_form.html.erb
Labels: bugfix

#6546 [28309] Avoid reloading table on removing columns
  frontend/src/app/components/wp-fast-table/state/wp-table-columns.service.ts
Labels: feature

#6549 [28318] Move query select no-results box into visible area
  frontend/src/app/components/wp-query-select/wp-query-select.template.html
Labels: bugfix

#6550 [28306] Avoid instantiating two resources that are not linked
  app/helpers/attachments_helper.rb
  app/views/messages/_form.html.erb
  app/views/wiki/_page_form.html.erb
  app/views/wiki/show.html.erb
  frontend/src/app/components/ckeditor/op-ckeditor-form.component.ts
  frontend/src/app/components/ckeditor/op-ckeditor-form.html
Labels: bugfix

#6552 Show error when getting data from CKEditor fails
  config/locales/js-en.yml
  frontend/npm-shrinkwrap.json
  frontend/src/app/components/ckeditor/op-ckeditor-form.component.ts
  frontend/src/polyfills.ts
  frontend/src/test.ts
  lib/open_project/page_hierarchy_helper.rb
Labels: bugfix

#6556 Avoid trying to show attachments when resource has no attachments
  frontend/src/app/components/attachments/attachments.html
  frontend/src/app/components/ckeditor/op-ckeditor-form.html
Labels: bugfix

#6558 [28314] Notify query changes only after query loaded
  frontend/src/app/components/wp-list/wp-list.service.ts
Labels: bugfix

#6557 [28339] Don't use inputstate for quote events
  frontend/src/app/components/work-packages/work-package-comment/work-package-comment.component.ts
  frontend/src/app/components/wp-activity/comment-service.ts
  frontend/src/app/components/wp-activity/user/user-activity.component.ts
Labels: bugfix

#6560 [28319] Actually observe upload events
  frontend/src/app/components/api/op-file-upload/op-file-upload.service.ts
Labels: bugfix

#6561 [28274] Use page slug to identify page on edit
  app/views/wiki/edit.html.erb
Labels: bugfix

#6492 [27992] Redesign OpenProject 8.0
  app/assets/images/favicon.ico
  app/assets/images/logo_openproject_white_big.png
  app/assets/stylesheets/content/_action_menu_main.sass
  app/assets/stylesheets/content/_autocomplete.sass
  app/assets/stylesheets/content/menus/_project_autocompletion.sass
  app/assets/stylesheets/fonts/_openproject_icon_font.sass
  app/assets/stylesheets/layout/_main_menu.sass
  app/assets/stylesheets/layout/_top_menu.sass
  app/assets/stylesheets/layout/_top_menu_mobile.sass
  app/assets/stylesheets/layout/work_packages/_query_menu.sass
  app/assets/stylesheets/layout/work_packages/_table.sass
  app/views/custom_styles/_inline_css.erb
  lib/open_project/design.rb
Labels: needs-review, styling

#6564 [28348] Coalesce values for contains filter
  app/models/queries/operators/contains.rb
  app/models/queries/operators/not_contains.rb
  spec/models/queries/work_packages/filter/custom_fields/contains_text_custom_field_filter_spec.rb
  spec/models/queries/work_packages/filter/custom_fields/custom_field_filter_spec.rb
  spec_legacy/unit/query_spec.rb
Labels: bugfix

#6567 [28303][28169] Fix configuration gantt chart and allow zoom level
  config/locales/js-en.yml
  frontend/src/app/components/wp-fast-table/state/wp-table-timeline.service.ts
  frontend/src/app/components/wp-query/url-params-helper.spec.ts
  frontend/src/app/components/wp-query/url-params-helper.ts
  frontend/src/app/components/wp-table/configuration-modal/tabs/timelines-tab.component.html
  frontend/src/app/components/wp-table/configuration-modal/tabs/timelines-tab.component.ts
  frontend/src/app/components/wp-table/embedded/wp-embedded-table.component.ts
  frontend/src/app/components/wp-table/embedded/wp-embedded-table.html
  frontend/src/app/components/wp-table/timeline/container/wp-timeline-container.directive.ts
Labels: bugfix

#6569 [28350] Fix bound element to pre block to avoid recursive insertion
  app/assets/javascripts/vendor/ckeditor/ckeditor.js
  app/assets/javascripts/vendor/ckeditor/ckeditor.js.map
  spec/features/wysiwyg/macros/code_block_macro_spec.rb
Labels: bugfix

#6570 [28307] Fix toolbar in wiki index/toc page
  app/views/wiki/index.html.erb
  features/wiki/wiki_index.feature
  spec/controllers/wiki_controller_spec.rb
  spec/features/wiki/wiki_index_spec.rb
Labels: bugfix

#6575 [28355] Always redraw on changed columns
  frontend/src/app/components/wp-fast-table/handlers/state/columns-transformer.ts
Labels: bugfix

#6581 [27992] Add hover effect for main menu toggler
  app/assets/stylesheets/layout/_top_menu.sass
Labels: bugfix, styling

#6582 [28279] Don't render remove child link without permission
  frontend/src/app/components/wp-relations/wp-relation-children/wp-children-query.component.ts
  frontend/src/app/components/wp-table/table-actions/actions/unlink-table-action.ts
  frontend/src/app/components/wp-table/table-actions/table-action.ts
  frontend/src/app/components/wp-table/table-actions/table-actions.service.ts
Labels: bugfix

#6585 [28271] Fix missing page message
  app/assets/javascripts/vendor/ckeditor/ckeditor.js
  app/assets/javascripts/vendor/ckeditor/ckeditor.js.map
Labels: bugfix

#6590 [27992] Redesign OpenProject 8.0 (2)
  app/assets/stylesheets/content/_forms.sass
  app/assets/stylesheets/layout/_main_menu.sass
  app/assets/stylesheets/layout/work_packages/_query_menu.sass
  app/assets/stylesheets/layout/work_packages/_table.sass
  app/views/layouts/base.html.erb
  lib/open_project/design.rb
Labels: styling

#6588 Styling of custom action buttons
  app/assets/stylesheets/content/_custom_actions.sass
  app/assets/stylesheets/content/work_packages/single_view/_single_view.sass
  frontend/src/app/components/resizer/wp-resizer.component.ts
  frontend/src/app/components/wp-custom-actions/wp-custom-actions/wp-custom-action.component.html
Labels: bugfix, styling

#6594 Create linked image tag in Markdown from textile syntax
  lib/open_project/text_formatting/formats/markdown/textile_converter.rb
Labels: bugfix, needs-review

#6586 [28177] Fix &nbsp; breaking markdown formatting in turndown
  app/assets/javascripts/vendor/ckeditor/ckeditor.js
  app/assets/javascripts/vendor/ckeditor/ckeditor.js.map
  spec/features/wysiwyg/non_breaking_spaces_spec.rb
Labels: bugfix, needs-review

#6595 [28352][28353] Inline create / No results changes
  frontend/src/app/components/wp-inline-create/wp-inline-create.component.html
  frontend/src/app/components/wp-inline-create/wp-inline-create.component.ts
  frontend/src/app/components/wp-table/wp-table.directive.html
  frontend/src/app/components/wp-table/wp-table.directive.ts
  spec/features/work_packages/table/inline_create/create_work_packages_spec.rb
  spec/features/work_packages/table/inline_create/parallel_creation_spec.rb
Labels: feature

#6598 [28381] Fix attachment lookup by customizing src attribute downcast
  app/assets/javascripts/vendor/ckeditor/ckeditor.js
  app/assets/javascripts/vendor/ckeditor/ckeditor.js.map
  frontend/src/app/modules/hal/resources/mixins/attachable-mixin.ts
  spec/features/wiki/attachment_upload_spec.rb
Labels: bugfix

#6603 [28401] Avoid treating empty query group as attribute group
  app/services/base_type_service.rb
  spec/features/types/form_configuration_query_spec.rb
Labels: bugfix

#6602 [28382] Remove last week from recent filters
  frontend/src/app/components/wp-query-select/wp-static-queries.service.ts
Labels: feature, needs-review

#6601 [28400] Avoid resetting attribute groups on name change
  app/services/base_type_service.rb
  spec/services/shared_type_service.rb
Labels: bugfix

#6611 Replace newlines with hard breaks within textile tables
  lib/open_project/text_formatting/formats/markdown/textile_converter.rb
Labels: bugfix

#6618 [28389] Remove WP resizer workaround
  app/assets/stylesheets/layout/work_packages/_full_view.sass
Labels: bugfix, styling

#6617 [26466] Don't set timelog timeframe condition to today if none exist
  app/controllers/timelog_controller.rb
  app/helpers/timelog_helper.rb
  spec_legacy/functional/timelog_controller_spec.rb
Labels: bugfix

#6621 [23877] Increase padding above view sections in work packages sidebar
  app/assets/stylesheets/layout/work_packages/_query_menu.sass
Labels: bugfix, styling

#6620 [28378][28379] Misplaced "Buy Now" Teaser (Core)
  app/assets/stylesheets/layout/_main_menu.sass
Labels: bugfix

#6622 [28371] Work package activity entries on 2nd indentation level on overview tab
  app/assets/stylesheets/content/work_packages/tabs/_activities.lsg
  frontend/src/app/components/wp-single-view-tabs/activity-panel/activity-on-overview.html
Labels: bugfix, styling

#6623 [28419] Allow to hide percentage sign in progress bar
  app/assets/javascripts/versions.js
  app/helpers/application_helper.rb
  app/views/versions/_work_package_counts.html.erb
Labels: bugfix

#6626 Buy now Teaser and scrolling in the Main menu
  app/assets/stylesheets/layout/_main_menu.sass
  app/assets/stylesheets/layout/work_packages/_query_menu.sass
  app/assets/stylesheets/openproject/_mixins.sass
Labels: bugfix, styling
