Repository opf/openproject, pull requests merged in 2019-04, with the labels that each got.

#7163 [Boards] Correct kanban board seed data
  app/seeders/demo_data/work_package_board_seeder.rb
  config/locales/en.seeders.standard.yml
Labels: bugfix

#7167 [28904] Gantt zoom level not saved with work packages custom view
  frontend/src/app/components/wp-buttons/wp-timeline-toggle-button/wp-timeline-toggle-button.component.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-timeline.service.ts
  frontend/src/app/components/wp-fast-table/wp-table-timeline.ts
  frontend/src/app/components/wp-table/timeline/container/wp-timeline-container.directive.ts
  spec/features/work_packages/timeline/timeline_navigation_spec.rb
Labels: bugfix, needs-review

#7176 [29839][Boards] Error shown when deleting last character in "add"-autocompleter
  frontend/src/app/modules/boards/board/inline-add/board-inline-add-autocompleter.component.ts
Labels: bugfix

#7174 [29845] Pagination in embedded tables not working
  frontend/src/app/components/wp-table/embedded/wp-embedded-table.component.ts
  frontend/src/app/modules/work_packages/routing/wp-view-base/work-packages-view.base.ts
  modules/grids/spec/features/my/my_page_assigned_to_me_spec.rb
Labels: bugfix

#7177 [29872][Boards] Filter cannot be removed
  frontend/src/app/modules/boards/board/board-filter/board-filter.component.ts
Labels: bugfix, needs-review

#7178 [29879][Boards] Improve lists title selection and focussing
  frontend/src/app/modules/boards/board/board-list/board-list.component.html
  frontend/src/app/modules/boards/board/board-list/board-list.component.ts
  frontend/src/app/modules/boards/board/board-list/board-lists.service.ts
  frontend/src/app/modules/boards/board/board.component.ts
  frontend/src/app/modules/common/editable-toolbar-title/editable-toolbar-title.component.ts
  frontend/src/app/modules/common/editable-toolbar-title/editable-toolbar-title.html
Labels: bugfix, needs-review

#7181 [29752] Missing warning when leaving with unsafed content in meetings
  modules/meeting/app/assets/javascripts/meeting/meeting.js
Labels: bugfix

#7180 [29884][Boards] Filters are taken over between single boards
  frontend/src/app/modules/boards/boards-sidebar/boards-menu.component.html
Labels: bugfix

#7184 [29880][Boards] After creating or deleting a new list in the board view the entire view is loaded again
  frontend/src/app/modules/boards/board/board-list/board-list.component.ts
Labels: bugfix, needs-review

#7187 [29189] [Boards] Active input field after clicking "New list" in Boards module
  frontend/src/app/modules/boards/board/board-list/board-list.component.ts
  frontend/src/app/modules/boards/board/board.component.ts
  frontend/src/app/modules/common/editable-toolbar-title/editable-toolbar-title.component.ts
  frontend/src/app/modules/common/editable-toolbar-title/editable-toolbar-title.html
Labels: bugfix, needs-review

#7189 [29457] Fix escaping of manual table rules
  app/assets/javascripts/vendor/ckeditor/ckeditor.js
  app/assets/javascripts/vendor/ckeditor/ckeditor.js.map
  spec/features/wysiwyg/tables_spec.rb
Labels: bugfix

#7191 [29905] Do not save board filters unless explicitly saved
  frontend/src/app/modules/boards/board/board-filter/board-filter.component.ts
  frontend/src/app/modules/boards/board/board.component.html
  frontend/src/app/modules/boards/board/board.component.ts
Labels: bugfix

#7194 [29752] Cross-browser conformant beforeunload in meeting
  modules/meeting/app/assets/javascripts/meeting/meeting.js
Labels: bugfix

#7195 [29913] Perform board saving in switchmap
  frontend/src/app/components/wp-card-view/wp-card-view.component.ts
  frontend/src/app/components/wp-edit/wp-notification.service.ts
  frontend/src/app/helpers/rxjs/request-switchmap.ts
  frontend/src/app/modules/boards/board/board-list/board-list.component.html
  frontend/src/app/modules/boards/board/board-list/board-list.component.sass
  frontend/src/app/modules/boards/board/board-list/board-list.component.ts
  frontend/src/app/modules/boards/board/board.component.ts
  frontend/src/app/modules/boards/openproject-boards.module.ts
  modules/boards/config/locales/js-en.yml
Labels: bugfix, needs-review

#7196 [29832] Split whitespace in like query
  app/models/queries/operators/contains.rb
  spec/models/queries/work_packages/filter/search_filter_spec.rb
Labels: feature, needs-review

#7182 [29898] Gantt auto zoom button does not work
  app/models/query/timelines.rb
  db/migrate/20190411122815_set_timeline_auto_zoom.rb
  frontend/src/app/components/wp-buttons/wp-timeline-toggle-button/wp-timeline-toggle-button.component.ts
  frontend/src/app/components/wp-buttons/wp-timeline-toggle-button/wp-timeline-toggle-button.html
  frontend/src/app/components/wp-fast-table/state/wp-table-timeline.service.ts
  frontend/src/app/components/wp-fast-table/wp-table-timeline.ts
  frontend/src/app/components/wp-table/configuration-modal/tabs/timelines-tab.component.ts
  frontend/src/app/components/wp-table/timeline/container/wp-timeline-container.directive.ts
  frontend/src/app/components/wp-table/timeline/header/wp-timeline-header.directive.ts
  frontend/src/app/components/wp-table/timeline/wp-timeline.ts
  frontend/src/app/modules/hal/resources/query-resource.ts
  spec/features/work_packages/timeline/timeline_navigation_spec.rb
  spec/support/pages/work_packages/work_packages_timeline.rb
Labels: bugfix

#7200 Medley of board fixes
  frontend/src/app/modules/boards/board/board-filter/board-filter.component.ts
  frontend/src/app/modules/boards/board/board.component.ts
  frontend/src/app/modules/boards/board/board.service.ts
  frontend/src/app/modules/boards/boards-sidebar/boards-menu.component.html
  modules/boards/spec/features/board_management_spec.rb
  modules/boards/spec/features/support/board_page.rb
Labels: bugfix

#7201 [29966] Fix card referencing with filters
  frontend/src/app/modules/boards/board/inline-add/board-inline-add-autocompleter.component.ts
  frontend/src/app/modules/boards/board/inline-add/board-inline-add-autocompleter.html
  modules/boards/spec/features/board_reference_work_package_spec.rb
Labels: bugfix

#7203 Update the documentation related to pkgr CLI
  docs/installation/packaged/2-configuration.md
Labels: documentation

#7197 [29829][Boards] Enable scrolling while dragging a WP or a list
  frontend/npm-shrinkwrap.json
  frontend/package.json
  frontend/src/app/components/wp-card-view/wp-card-view.component.ts
  frontend/src/app/components/wp-fast-table/handlers/state/drag-and-drop-transformer.ts
  frontend/src/app/modules/boards/board/board.component.html
  frontend/src/app/modules/boards/board/board.component.sass
  frontend/src/app/modules/boards/board/board.component.ts
  frontend/src/app/modules/boards/drag-and-drop/drag-and-drop.service.ts
  frontend/src/app/modules/boards/openproject-boards.module.ts
  frontend/src/app/modules/common/drag-and-drop/dom-autoscroll.service.ts
  frontend/src/typings.d.ts
Labels: feature, needs-review

#7204 [29883] Notify when loading submenu of boards and work packages
  app/assets/javascripts/application.js.erb
  app/assets/javascripts/onboarding/boards_tour.js
  app/assets/javascripts/specific/main_menu.js.erb
  frontend/src/app/angular4-modules.ts
  frontend/src/app/components/main-menu/main-menu-navigation.service.ts
  frontend/src/app/components/main-menu/main-menu-toggle.component.ts
  frontend/src/app/components/main-menu/main-menu-toggle.service.ts
  frontend/src/app/components/resizer/main-menu-resizer.component.ts
  frontend/src/app/components/resizer/wp-resizer.component.ts
  frontend/src/app/components/wp-query-select/wp-query-select-dropdown.component.ts
  frontend/src/app/modules/boards/board/board.component.ts
  frontend/src/app/modules/boards/boards-sidebar/boards-menu.component.html
  frontend/src/app/modules/boards/boards-sidebar/boards-menu.component.ts
  lib/redmine/menu_manager/menu_helper.rb
Labels: feature, needs-review

#7206 [29873] Fix parsing of form query params in project context
  frontend/src/app/modules/hal/dm-services/query-form-dm.service.ts
  lib/api/v3/queries/create_form_api.rb
  lib/api/v3/queries/filters/query_filter_instance_representer.rb
  lib/api/v3/queries/query_helper.rb
  spec/requests/api/v3/queries/create_form_api_spec.rb
Labels: bugfix

#7209 [29888] Avoid reload flag to not reload query
  frontend/src/app/components/wp-list/wp-list.service.ts
Labels: feature

#7210 Remember collapsed state
  frontend/src/app/components/wp-fast-table/handlers/state/hierarchy-transformer.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-hierarchy.service.ts
Labels: bugfix

#7212 [29589] Fix version graph showing and add regression test
  frontend/src/app/components/wp-by-version-graph/wp-by-version-graph.component.ts
  frontend/src/app/components/wp-table/embedded/wp-embedded-graph.component.ts
  spec/features/versions/graph_spec.rb
Labels: bugfix

#7211 [29914][Boards] Back button overlaps toolbar (mobile)
  frontend/src/app/modules/boards/board/board.component.html
  modules/boards/app/assets/stylesheets/boards/board_header_mobile.sass
  modules/boards/app/views/boards/boards/index.html.erb
  modules/boards/lib/open_project/boards/engine.rb
Labels: bugfix, styling

#7214 [30000] Content is not scrollable with long embedded tables
  frontend/src/app/components/wp-table/wp-table-scroll-sync.ts
Labels: bugfix, needs-review

#7217 [29910] Make Edge respond to hierarchy click handler
  app/assets/stylesheets/content/work_packages/_table_hierarchy.sass
  frontend/src/app/components/wp-fast-table/handlers/row/hierarchy-click-handler.ts
Labels: bugfix

#7219 [30044] Implement double-tap behaivor using hammer.js
  frontend/npm-shrinkwrap.json
  frontend/package.json
  frontend/src/app/components/wp-card-view/wp-card-view.component.html
  frontend/src/app/init-globals.ts
  frontend/src/app/modules/a11y/double-click-or-tap.directive.ts
  frontend/src/app/modules/a11y/openproject-a11y.module.ts
Labels: bugfix

#7220 [30031] Don't inherit isNew flag in boards
  frontend/src/app/modules/boards/openproject-boards.module.ts
Labels: bugfix

#7218 [30039] Implement toggled-multiselect with ng-select
  app/assets/stylesheets/content/_autocomplete.sass
  app/assets/stylesheets/content/_forms.sass
  app/assets/stylesheets/content/_modal.sass
  frontend/npm-shrinkwrap.json
  frontend/src/app/components/filters/filter-toggled-multiselect-value/filter-toggled-multiselect-value.component.html
  frontend/src/app/components/filters/filter-toggled-multiselect-value/filter-toggled-multiselect-value.component.spec.ts
  frontend/src/app/components/filters/filter-toggled-multiselect-value/filter-toggled-multiselect-value.component.ts
  frontend/src/app/modules/common/openproject-common.module.ts
  frontend/src/app/modules/fields/edit/field-types/multi-select-edit-field.component.html
  spec/features/support/components/ng_select_autocomplete.rb
  spec/features/work_packages/export_spec.rb
  spec/features/work_packages/table/inline_create/create_work_packages_spec.rb
  spec/features/work_packages/table/invalid_query_spec.rb
  spec/features/work_packages/table/queries/query_history_spec.rb
  spec/support/components/ng_select_autocomplete_helpers.rb
  spec/support/components/work_packages/filters.rb
  spec/support/pages/work_packages/work_packages_table.rb
Labels: feature, needs-review

#7221 [30037] Correctly focus on new list
  frontend/src/app/modules/boards/board/board-list/board-list.component.html
  frontend/src/app/modules/boards/board/board-list/board-list.component.ts
  frontend/src/app/modules/boards/board/board-list/board-lists.service.ts
  frontend/src/app/modules/boards/board/board.component.ts
  frontend/src/app/modules/boards/board/board.ts
Labels: bugfix

#7222 [30053] Fix writable scope check
  modules/boards/lib/open_project/boards/grid_registration.rb
  modules/grids/lib/grids/configuration.rb
  modules/grids/lib/grids/configuration/registration.rb
Labels: bugfix

#7224 [29898] Use computed zoom level in case of zooming with auto zoom
  frontend/src/app/components/wp-fast-table/state/wp-table-timeline.service.ts
  frontend/src/app/components/wp-table/timeline/container/wp-timeline-container.directive.ts
Labels: bugfix

#7226 [30061] Reposition ng-select on updates
  frontend/src/app/components/filters/filter-toggled-multiselect-value/filter-toggled-multiselect-value.component.html
  frontend/src/app/components/filters/filter-toggled-multiselect-value/filter-toggled-multiselect-value.component.ts
Labels: bugfix

#7216 [30021][Boards] Apply new boards styling
  app/assets/stylesheets/content/work_packages/single_view/_single_view.sass
  config/locales/js-en.yml
  frontend/src/app/components/wp-buttons/wp-status-button/wp-status-button.component.sass
  frontend/src/app/components/wp-buttons/wp-status-button/wp-status-button.component.ts
  frontend/src/app/components/wp-buttons/wp-status-button/wp-status-button.html
  frontend/src/app/components/wp-card-view/wp-card-view.component.html
  frontend/src/app/components/wp-card-view/wp-card-view.component.sass
  frontend/src/app/components/wp-card-view/wp-card-view.component.ts
  frontend/src/app/components/wp-edit-form/work-package-changeset.ts
  frontend/src/app/components/wp-fast-table/builders/highlighting/highlighting-mode.const.ts
  frontend/src/app/modules/boards/board/board-list/board-list-dropdown.directive.ts
  frontend/src/app/modules/boards/board/board-list/board-list.component.html
  frontend/src/app/modules/boards/board/board-list/board-list.component.sass
  frontend/src/app/modules/boards/board/board-list/board-list.component.ts
  frontend/src/app/modules/boards/board/board.component.sass
  frontend/src/app/modules/boards/board/configuration-modal/tabs/highlighting-tab.component.html
  frontend/src/app/modules/boards/board/configuration-modal/tabs/highlighting-tab.component.ts
  frontend/src/app/modules/boards/drag-and-drop/drag-and-drop.service.ts
  frontend/src/app/modules/boards/openproject-boards.module.ts
  lib/open_project/design.rb
  modules/boards/spec/features/board_highlighting_spec.rb
  modules/boards/spec/features/board_navigation_spec.rb
  modules/boards/spec/features/status_board_spec.rb
  modules/boards/spec/features/support/board_page.rb
Labels: feature, styling

#7225 [30027] Fix onEnter bodyClasses to be used instead of controller classes
  app/assets/stylesheets/content/work_packages/single_view/_single_view.sass
  app/assets/stylesheets/layout/work_packages/_details_view.sass
  app/assets/stylesheets/layout/work_packages/_mobile.sass
  app/assets/stylesheets/layout/work_packages/_print.sass
  app/assets/stylesheets/layout/work_packages/_table.sass
  frontend/src/app/modules/calendar/openproject-calendar.module.ts
  frontend/src/app/modules/calendar/wp-calendar/wp-calendar.component.ts
  frontend/src/app/modules/router/openproject.routes.ts
  frontend/src/app/modules/work_packages/routing/work-packages-routes.ts
Labels: bugfix, needs-review

#7232 [30001] Ensure embedded table/timeline split evenly
  app/assets/stylesheets/layout/work_packages/_table_embedded.sass
Labels: bugfix, needs-review

#7227 [30043] Disable events on touchend similar to mouseup
  frontend/src/app/components/filters/filter-container/filter-container.directive.html
  frontend/src/app/components/filters/filter-container/filter-container.directive.ts
  frontend/src/app/components/filters/query-filters/query-filters.component.ts
  frontend/src/app/modules/common/drag-and-drop/dom-autoscroll.service.ts
  spec/features/accessibility/work_packages/work_package_query_spec.rb
  spec/features/menu_items/query_menu_item_spec.rb
  spec/features/work_packages/export_spec.rb
  spec/features/work_packages/select_query_spec.rb
  spec/features/work_packages/shared_contexts.rb
  spec/features/work_packages/work_packages_page.rb
Labels: bugfix

#7233 [30082] Ensure global work package query menu is activated
  frontend/src/app/components/main-menu/main-menu-navigation.service.ts
  frontend/src/app/components/wp-query-select/wp-query-select-dropdown.component.ts
  spec/features/work_packages/table/queries/query_menu_spec.rb
Labels: bugfix

#7234 [30075] Destroy drake on ngOnDestroy
  frontend/src/app/modules/boards/drag-and-drop/drag-and-drop.service.ts
Labels: bugfix, needs-review

#7237 [30076] WP back button does not work when coming from the MyPage
  frontend/src/app/modules/grids/openproject-grids.module.ts
  frontend/src/app/modules/work_packages/routing/work-packages-routes.ts
Labels: bugfix, needs-review

#7235 [29253] Render error message in production on pending migrations
  app/assets/stylesheets/content/_notifications.sass
  app/assets/stylesheets/layout/_index.sass
  app/assets/stylesheets/layout/_top_shelf.sass
  app/assets/stylesheets/layout/_warning_bar.sass
  app/controllers/application_controller.rb
  app/helpers/error_message_helper.rb
  app/helpers/errors_helper.rb
  app/helpers/migrations_helper.rb
  app/views/common/_error_base.html.erb
  app/views/common/_validation_error.html.erb
  app/views/common/error.html.erb
  app/views/layouts/base.html.erb
  app/views/projects/_form.html.erb
  app/views/warning_bar/_pending_migrations.html.erb
  app/views/warning_bar/_unsupported_browser.html.erb
  app/views/warning_bar/_warning_bar.html.erb
  config/locales/en.yml
  lib/open_project/configuration.rb
  lib/open_project/database.rb
  lib/open_project/logging/log_delegator.rb
  lib/open_project/static/links.rb
  modules/avatars/spec/features/my_avatar_spec.rb
  modules/avatars/spec/features/user_avatar_spec.rb
  modules/ldap_groups/app/controllers/ldap_groups/synchronized_groups_controller.rb
  modules/my_project_page/spec/features/block_editing_spec.rb
  modules/reporting/spec/features/permissions_spec.rb
  modules/webhooks/spec/features/manage_webhooks_spec.rb
  spec/controllers/news_controller_spec.rb
  spec/features/admin/oauth/oauth_applications_management_spec.rb
  spec/features/users/password_change_spec.rb
Labels: feature

#7242 [30091][Boards] Missing space between boards table and screen
  frontend/src/app/modules/boards/board/board.component.sass
  frontend/src/app/modules/boards/openproject-boards.module.ts
Labels: bugfix, styling

#7240 [29683] Fix order statements of CF list
  app/models/custom_field/order_statements.rb
  app/models/queries/work_packages/columns/custom_field_column.rb
  spec/features/custom_fields/multi_value_custom_field_spec.rb
  spec/features/work_packages/table/hierarchy/hierarchy_parent_below_spec.rb
  spec/features/work_packages/table/hierarchy/hierarchy_spec.rb
  spec/support/components/work_packages/sort_by.rb
  spec/support/pages/work_packages/work_packages_table.rb
Labels: bugfix

#7236 [30070] Change the representation of the WP type
  app/assets/stylesheets/content/_tables.sass
  app/assets/stylesheets/layout/_colors.sass
  app/assets/stylesheets/layout/work_packages/_full_view.sass
  app/helpers/colors_helper.rb
  frontend/src/app/components/op-context-menu/handlers/op-types-context-menu.directive.ts
  frontend/src/app/components/op-context-menu/handlers/wp-status-dropdown-menu.directive.ts
  frontend/src/app/components/wp-buttons/wp-status-button/wp-status-button.component.ts
  frontend/src/app/components/wp-card-view/wp-card-view.component.ts
  frontend/src/app/components/wp-fast-table/builders/highlighting/highlighting.functions.ts
  frontend/src/app/components/wp-fast-table/builders/highlighting/row-highlight-render-pass.ts
  frontend/src/app/components/wp-table/timeline/cells/timeline-cell-renderer.ts
  frontend/src/app/components/wp-table/wp-table.styles.sass
  frontend/src/app/modules/boards/board/board-list/board-list.component.ts
  frontend/src/app/modules/calendar/wp-calendar/wp-calendar.component.ts
  frontend/src/app/modules/fields/display/field-types/wp-display-highlighted-resource-field.module.ts
  frontend/src/app/modules/global_search/global-search-input.component.html
  frontend/src/app/modules/global_search/global-search-input.component.ts
  modules/bcf/app/views/bcf/issues/index.html.erb
  modules/boards/spec/features/board_highlighting_spec.rb
  modules/costs/spec/features/costs_edit_fields_spec.rb
  spec/features/work_package_show_spec.rb
  spec/features/work_packages/custom_actions_spec.rb
  spec/features/work_packages/details/milestones_spec.rb
  spec/features/work_packages/edit_work_package_spec.rb
  spec/features/work_packages/highlighting_spec.rb
  spec/features/work_packages/new/attributes_from_filter_spec.rb
  spec/features/work_packages/new/new_work_package_spec.rb
  spec/features/work_packages/table/inline_create/parallel_creation_spec.rb
  spec/features/work_packages/table/switch_types_spec.rb
  spec/features/work_packages/timeline/timeline_labels_spec.rb
  spec/support/pages/work_packages/abstract_work_package.rb
  spec/support/pages/work_packages/work_packages_table.rb
Labels: feature, needs-review, styling

#7245 [29663] Handle multi select fields with no value set
  frontend/src/app/modules/fields/edit/field-types/multi-select-edit-field.component.ts
Labels: bugfix, needs-review

#7241 [29876][Boards] Add board seed data and tour for scrum project
  app/assets/javascripts/onboarding/boards_tour.js
  app/assets/javascripts/onboarding/onboarding_tour.js
  app/seeders/demo_data/work_package_board_seeder.rb
  config/locales/en.seeders.standard.yml
  modules/boards/spec/features/onboarding/boards_onboarding_tour_spec.rb
  modules/boards/spec/features/support/onboarding_steps.rb
  spec/seeders/demo_data_seeder_spec.rb
Labels: needs-review

#7252 [29941] Disable two column layout for MS Edge
  frontend/src/app/components/resizer/wp-resizer.component.ts
  frontend/src/app/components/work-packages/wp-single-view/wp-single-view.component.ts
  frontend/src/app/components/work-packages/wp-single-view/wp-single-view.html
  frontend/src/app/modules/common/browser/browser-detector.service.ts
Labels: bugfix, needs-review

#7254 [24378] Clear apache PID file
  docker/entrypoint.sh
Labels: bugfix

#7249 Fix/user invitations blocked by self registration setting
  app/controllers/concerns/omniauth_login.rb
  spec/controllers/concerns/omniauth_login_spec.rb
  spec/features/users/brute_force_spec.rb
  spec/helpers/security_badge_helper_spec.rb
  spec/models/setting_spec.rb
  spec/support/shared/with_settings.rb
  spec_legacy/functional/user_mailer_spec.rb
Labels: bugfix, needs-review

#7253 [29898] Fix zoom level after autozoom
  frontend/src/app/components/wp-buttons/wp-timeline-toggle-button/wp-timeline-toggle-button.component.ts
  frontend/src/app/components/wp-buttons/wp-timeline-toggle-button/wp-timeline-toggle-button.html
  frontend/src/app/components/wp-fast-table/state/wp-table-timeline.service.ts
  frontend/src/app/components/wp-table/timeline/container/wp-timeline-container.directive.ts
  spec/features/work_packages/timeline/timeline_navigation_spec.rb
  spec/support/pages/work_packages/work_packages_timeline.rb
Labels: bugfix

#7257 [30097] Only add default status to status board
  frontend/src/app/modules/boards/board/board-actions/status-action.service.ts
  modules/boards/spec/features/status_board_spec.rb
Labels: feature

#7247 [29834] Add warning bar when MySQL database is used
  app/assets/stylesheets/layout/_warning_bar.sass
  app/helpers/application_helper.rb
  app/helpers/warning_bar_helper.rb
  app/views/warning_bar/_mysql_database.html.erb
  app/views/warning_bar/_pending_migrations.html.erb
  app/views/warning_bar/_unsupported_browser.html.erb
  app/views/warning_bar/_warning_bar.html.erb
  config/locales/en.yml
  docs/operations/migrating/packaged/postgresql-migration.md
  lib/open_project/configuration.rb
  lib/open_project/configuration/helpers.rb
  lib/open_project/static/links.rb
  lib/redmine/mime_type.rb
  modules/avatars/app/controllers/avatars/avatar_controller.rb
  spec/features/mysql/deprecation_spec.rb
  spec/rails_helper.rb
Labels: feature

#7258 [30104] Fix empty titled being used in new wiki page
  app/controllers/wiki_controller.rb
  lib/redmine/menu_manager/top_menu/help_menu.rb
Labels: bugfix

#7259 [30108] Remove grid for readonly board lists
  frontend/src/app/modules/boards/board/board-list/board-list.component.html
  frontend/src/app/modules/boards/board/board-list/board-list.component.sass
Labels: bugfix

#7261 [30092] Fix duplicated join alias name in attachment filters
  app/models/queries/work_packages/filter/attachment_base_filter.rb
  lib/api/root.rb
  lib/api/utilities/grape_helper.rb
  lib/open_project/logging/log_delegator.rb
Labels: bugfix

#7264 [30109] Increase min-width of split view to 500
  app/assets/stylesheets/layout/work_packages/_details_view.sass
  app/assets/stylesheets/layout/work_packages/_full_view.sass
  frontend/src/app/components/resizer/wp-resizer.component.ts
Labels: bugfix

#7265 Use ng-select for add_filter_select
  frontend/src/app/components/filters/query-filters/query-filters.component.html
  frontend/src/app/components/filters/query-filters/query-filters.component.ts
  spec/features/work_packages/table/queries/filter_spec.rb
  spec/support/components/ng_select_autocomplete_helpers.rb
  spec/support/components/work_packages/filters.rb
Labels: feature, needs-review

#7268 [30136] Typo in onboarding tour ("Scrum")
  config/locales/js-en.yml
  modules/boards/spec/features/support/onboarding_steps.rb
Labels: bugfix

#7256 [30096] Bright colours for WP Types cannot be seen
  app/helpers/colors_helper.rb
  app/models/color.rb
  app/views/colors/_color_autocomplete_field.html.erb
  app/views/enumerations/_form.html.erb
  app/views/highlighting/styles.css.erb
  app/views/statuses/_form.html.erb
  app/views/types/form/_settings.html.erb
  config/locales/en.yml
  config/locales/js-en.yml
  frontend/src/app/components/wp-fast-table/builders/highlighting/highlighting.functions.ts
  frontend/src/app/modules/common/colors/colors-autocompleter.component.ts
Labels: bugfix, needs-review

#7255 [30110] Avoid type bg classes applied to timeline bar
  app/assets/stylesheets/content/work_packages/timelines/elements/_bar.sass
  app/assets/stylesheets/content/work_packages/timelines/elements/_labels.sass
  frontend/src/app/components/wp-table/timeline/cells/timeline-cell-renderer.ts
  frontend/src/app/components/wp-table/timeline/cells/timeline-milestone-cell-renderer.ts
  frontend/src/app/components/wp-table/timeline/wp-timeline.ts
Labels: bugfix, needs-review
