Repository opf/openproject, pull requests merged in 2019-03, with the labels that each got.

#7104 Add custom getter for Setting.installation_uuid
  app/models/setting.rb
  config/initializers/security_badge.rb
  spec/models/setting_spec.rb
Labels: bugfix, needs-review

#7093 don't show versions which are configured not to be shown by default
  modules/backlogs/app/models/sprint.rb
  modules/backlogs/spec/models/sprint_spec.rb
Labels: bugfix, needs-review

#7103 [29122] Enable hierarchies and sort-by at the same time
  app/models/queries/work_packages/columns/property_column.rb
  app/models/query.rb
  app/models/relation/hierarchy_paths.rb
  config/initializers/typed_dag.rb
  db/migrate/20180116065518_add_hierarchy_paths.rb
  db/migrate/20190301122554_remove_hierarchy_paths.rb
  docs/api/apiv3/endpoints/queries.apib
  docs/api/apiv3/endpoints/work-packages.apib
  frontend/src/app/components/wp-fast-table/state/wp-table-hierarchy.service.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-sort-by.service.ts
  frontend/src/app/components/wp-query-select/wp-static-queries.service.ts
  spec/features/work_packages/table/hierarchy/hierarchy_sorting_spec.rb
  spec/features/work_packages/table_sorting_spec.rb
  spec/models/query/results_spec.rb
  spec/models/query_spec.rb
  spec/models/relation/hierarchy_paths_spec.rb
  spec/support/pages/work_packages_table.rb
Labels: feature, needs-review

#7106 [29652] Avoid duplicated deferred parent insertion
  frontend/src/app/components/wp-fast-table/builders/modes/hierarchy/hierarchy-render-pass.ts
  spec/features/work_packages/table/hierarchy/hierarchy_parent_below_spec.rb
Labels: bugfix

#7105 [29639] Selected entry in auto-completion not removed from list of options
  frontend/src/app/modules/common/autocomplete/user-autocompleter.component.ts
  frontend/src/app/modules/fields/edit/field-types/multi-select-edit-field.component.html
  frontend/src/app/modules/fields/edit/field-types/multi-select-edit-field.component.ts
  frontend/src/app/modules/fields/edit/field-types/select-edit-field.component.ts
  spec/support/work_packages/work_package_field.rb
Labels: bugfix

#7110 [29664] Fix calendar history navigation
  frontend/src/app/modules/calendar/wp-calendar/wp-calendar.component.ts
  spec/features/calendars/calendars_spec.rb
Labels: bugfix

#7109 [29654] Save perPage in localstorage again
  frontend/src/app/components/table-pagination/table-pagination.component.ts
  frontend/src/app/components/wp-relations/embedded/inline/add-existing/wp-relation-inline-add-existing.component.html
  frontend/src/app/components/wp-table/table-pagination/wp-table-pagination.component.ts
  spec/features/work_packages/details/query_groups/relation_query_group_spec.rb
Labels: bugfix

#7111 Use latest buildpack with bundler2 support
  .buildpacks
  .pkgr.yml
Labels: packager

#7113 [29673] Avoid stale? with CSP nonces on activities controller
  app/controllers/activities_controller.rb
Labels: bugfix, needs-review

#7116 [29569] [Boards] Save list name when clicking outside
  frontend/src/app/modules/common/editable-toolbar-title/editable-toolbar-title.component.ts
  frontend/src/app/modules/common/editable-toolbar-title/editable-toolbar-title.html
Labels: feature, needs-review

#7112 [29672] [Boards] Show work package in full view when double-clicking on a card
  app/assets/javascripts/onboarding/work_package_tour.js
  app/assets/stylesheets/layout/_base.sass
  config/locales/js-en.yml
  frontend/src/app/components/wp-card-view/wp-card-view.component.html
  frontend/src/app/components/wp-card-view/wp-card-view.component.ts
  frontend/src/app/components/wp-single-view-tabs/keep-tab/keep-tab.service.ts
  frontend/src/app/modules/boards/openproject-boards.module.ts
  frontend/src/app/modules/calendar/openproject-calendar.module.ts
  frontend/src/app/modules/common/back-routing/back-routing.service.ts
  frontend/src/app/modules/common/openproject-common.module.ts
  frontend/src/app/modules/router/openproject.routes.ts
  frontend/src/app/modules/work_packages/routing/work-packages-routes.ts
  frontend/src/app/modules/work_packages/routing/wp-full-view/wp-full-view.component.ts
  frontend/src/app/modules/work_packages/routing/wp-full-view/wp-full-view.html
  modules/boards/spec/features/board_navigation_spec.rb
  modules/boards/spec/features/support/board_index_page.rb
  spec/features/calendars/calendars_spec.rb
  spec/features/work_packages/navigation_spec.rb
  spec/features/work_packages/zen_mode_spec.rb
  spec/support/pages/work_packages/abstract_work_package.rb
  spec/support/pages/work_packages/split_work_package.rb
Labels: feature, needs-review

#7122 [29697] Add link to impressum on homescreen and help dropdown
  app/views/homescreen/index.html.erb
  config/initializers/homescreen.rb
  config/locales/en.yml
  docs/configuration/configuration.md
  lib/open_project/configuration.rb
  lib/open_project/static/links.rb
  lib/redmine/menu_manager/top_menu/help_menu.rb
Labels: feature

#7121 [29529] [Boards] Handle non-default types
  app/assets/stylesheets/layout/_colors.sass
  app/assets/stylesheets/layout/work_packages/_full_view.sass
  config/locales/js-en.yml
  frontend/src/app/components/wp-card-view/wp-card-view.component.html
  frontend/src/app/components/wp-card-view/wp-card-view.component.sass
  frontend/src/app/components/wp-card-view/wp-card-view.component.ts
Labels: feature, needs-review

#7125 [Boards] Remove inline editing in cards
  frontend/src/app/components/wp-card-view/wp-card-view.component.html
  frontend/src/app/components/wp-card-view/wp-card-view.component.sass
  frontend/src/app/components/wp-card-view/wp-card-view.component.ts
Labels: needs-review

#7129 [29722] Fix removed attachments on wp reply
  app/models/mail_handler.rb
  spec/models/mail_handler_spec.rb
Labels: bugfix

#7130 Silently remove parent sort_by
  app/models/query.rb
  spec/models/query_spec.rb
Labels: bugfix

#7135 Bump rails to 5.2.2.1
  Gemfile
  Gemfile.lock
Labels: bugfix

#7065 Set the public-host to ng serve to avoid 307 redirects on websocket
  config/routes.rb
  frontend/package.json
Labels: housekeeping, needs-review

#7124 Replace display-mode tab with highlighting tab
  config/locales/js-en.yml
  frontend/src/app/components/wp-card-view/wp-card-view.component.html
  frontend/src/app/components/wp-card-view/wp-card-view.component.ts
  frontend/src/app/components/wp-fast-table/builders/highlighting/highlighting-mode.const.ts
  frontend/src/app/modules/boards/board/board-list/board-list.component.html
  frontend/src/app/modules/boards/board/board.ts
  frontend/src/app/modules/boards/board/configuration-modal/board-configuration.service.ts
  frontend/src/app/modules/boards/board/configuration-modal/tabs/display-settings-tab.component.html
  frontend/src/app/modules/boards/board/configuration-modal/tabs/display-settings-tab.component.ts
  frontend/src/app/modules/boards/board/configuration-modal/tabs/highlighting-tab.component.html
  frontend/src/app/modules/boards/board/configuration-modal/tabs/highlighting-tab.component.ts
  frontend/src/app/modules/boards/openproject-boards.module.ts
  modules/boards/spec/features/board_highlighting_spec.rb
  modules/boards/spec/features/support/board_page.rb
Labels: feature, needs-review

#7134 [29724] Removable cards in free boards
  app/assets/stylesheets/content/_buttons.sass
  config/locales/js-en.yml
  frontend/src/app/components/op-context-menu/op-context-menu.html
  frontend/src/app/components/wp-card-view/wp-card-view.component.html
  frontend/src/app/components/wp-card-view/wp-card-view.component.sass
  frontend/src/app/components/wp-card-view/wp-card-view.component.ts
  frontend/src/app/components/wp-table/embedded/wp-embedded-table.component.ts
  frontend/src/app/modules/boards/board/add-card-dropdown/add-card-dropdown-menu.directive.ts
  frontend/src/app/modules/boards/board/board-list/board-inline-create.service.ts
  frontend/src/app/modules/boards/board/board-list/board-list.component.html
  frontend/src/app/modules/boards/board/board-list/board-list.component.sass
  frontend/src/app/modules/boards/board/board-list/board-list.component.ts
  frontend/src/app/modules/boards/board/board.component.sass
  frontend/src/app/modules/boards/board/inline-add/board-inline-add-autocompleter.component.ts
  frontend/src/app/modules/boards/board/inline-add/board-inline-add-autocompleter.html
  frontend/src/app/modules/boards/openproject-boards.module.ts
  frontend/src/app/modules/common/model-auth/model-auth.service.ts
  modules/boards/app/controllers/boards/boards_controller.rb
  modules/boards/config/locales/js-en.yml
  modules/boards/spec/features/board_management_spec.rb
  modules/boards/spec/features/status_board_spec.rb
  modules/boards/spec/features/support/board_page.rb
Labels: feature, needs-review

#7138 [Boards] Beautify board highlighting
  frontend/src/app/components/wp-card-view/wp-card-view.component.html
  frontend/src/app/components/wp-card-view/wp-card-view.component.sass
  frontend/src/app/components/wp-card-view/wp-card-view.component.ts
  modules/boards/spec/features/board_navigation_spec.rb
  modules/boards/spec/features/support/board_page.rb
Labels: housekeeping, styling

#7140 [29727] Removing a work package in full view does not use BackRouteService
  frontend/src/app/components/modals/wp-destroy-modal/wp-destroy.modal.ts
  frontend/src/app/modules/common/back-routing/back-routing.service.ts
Labels: bugfix, needs-review

#7141 [29721] Switch timeline buttons
  frontend/src/app/components/wp-buttons/wp-timeline-toggle-button/wp-timeline-toggle-button.html
Labels: bugfix

#7142 [29718] Fix costlog link
  modules/costs/app/controllers/costlog_controller.rb
  modules/costs/app/views/cost_objects/_show_variable_cost_object.html.erb
  modules/costs/lib/open_project/costs/hooks/work_packages_show_attributes.rb
Labels: bugfix

#7143 [29699][Boards] Make board view Enterprise Edition feature
  app/services/authorization/enterprise_service.rb
  config/locales/js-en.yml
  frontend/src/app/components/enterprise-banner/enterprise-banner.component.sass
  frontend/src/app/components/enterprise-banner/enterprise-banner.component.ts
  frontend/src/app/components/filters/query-filters/query-filters.component.html
  frontend/src/app/components/wp-table/configuration-modal/tabs/columns-tab.component.html
  frontend/src/app/components/wp-table/configuration-modal/tabs/highlighting-tab.component.html
  frontend/src/app/components/wp-table/configuration-modal/tabs/highlighting-tab.component.ts
  frontend/src/app/globals/constants.const.ts
  frontend/src/app/modules/boards/board/board.component.html
  frontend/src/app/modules/boards/board/board.component.ts
  frontend/src/app/modules/boards/index-page/boards-index-page.component.html
  frontend/src/app/modules/boards/index-page/boards-index-page.component.ts
  frontend/src/app/modules/common/openproject-common.module.ts
  modules/boards/lib/open_project/boards/engine.rb
  modules/boards/lib/open_project/boards/patches/setting_seeder_patch.rb
  modules/boards/spec/features/board_highlighting_spec.rb
  modules/boards/spec/features/board_management_spec.rb
  modules/boards/spec/features/board_navigation_spec.rb
  modules/boards/spec/features/status_board_spec.rb
  spec/support/enterprise_token_helper.rb
Labels: feature, needs-review

#7150 [29702] Don't skip changed status or type
  frontend/src/app/components/wp-edit-form/work-package-changeset.ts
  frontend/src/app/components/wp-edit-form/work-package-edit-form.ts
  frontend/src/app/components/wp-edit/wp-edit-field/wp-edit-field-group.directive.ts
Labels: bugfix

#7147 Add board seeder
  app/seeders/basic_data/role_seeder.rb
  app/seeders/demo_data/project_seeder.rb
  app/seeders/demo_data/work_package_board_seeder.rb
  config/locales/en.seeders.yml
  spec/seeders/demo_data_seeder_spec.rb
Labels: feature

#7151 [29689] Allow setting the sort dir for group_by column
  app/models/query/group_by.rb
  app/models/query/results.rb
  app/models/query/sums.rb
  frontend/src/app/components/wp-fast-table/state/wp-table-sort-by.service.ts
  spec/models/query/results_spec.rb
Labels: bugfix

#7148 [29522][Boards] Update Onboarding Tour for Boards
  app/assets/javascripts/onboarding/backlogs_tour.js
  app/assets/javascripts/onboarding/boards_tour.js
  app/assets/javascripts/onboarding/menu_tour.js
  app/assets/javascripts/onboarding/onboarding_tour.js
  app/assets/javascripts/onboarding/work_package_tour.js
  app/seeders/demo_data/work_package_board_seeder.rb
  app/views/layouts/base.html.erb
  config/locales/js-en.yml
  config/settings.yml
  frontend/src/app/components/filters/query-filter/query-filter.component.ts
  frontend/src/app/components/filters/query-filters/query-filters.component.ts
  frontend/src/app/components/wp-table/configuration-modal/tabs/columns-tab.component.ts
  frontend/src/app/components/wp-table/configuration-modal/tabs/filters-tab.component.ts
  modules/backlogs/spec/features/onboarding/backlogs_onboarding_tour_spec.rb
  modules/boards/spec/features/onboarding/boards_onboarding_tour_spec.rb
  spec/features/onboarding/onboarding_tour_spec.rb
  spec/support/onboarding_helper.rb
Labels: feature, needs-review

#7152 [29519] Implement board-wide filters
  frontend/src/app/components/api/api-v3/query-filter-builder.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-filters.service.ts
  frontend/src/app/components/wp-query/url-params-helper.ts
  frontend/src/app/modules/boards/board/board-actions/status-action.service.ts
  frontend/src/app/modules/boards/board/board-filter/board-filter.component.html
  frontend/src/app/modules/boards/board/board-filter/board-filter.component.ts
  frontend/src/app/modules/boards/board/board-list/board-list.component.ts
  frontend/src/app/modules/boards/board/board-list/board-lists.service.ts
  frontend/src/app/modules/boards/board/board.component.html
  frontend/src/app/modules/boards/board/board.component.sass
  frontend/src/app/modules/boards/board/board.component.ts
  frontend/src/app/modules/boards/board/board.ts
  frontend/src/app/modules/boards/index-page/boards-index-page.component.html
  frontend/src/app/modules/boards/index-page/boards-index-page.component.sass
  frontend/src/app/modules/boards/index-page/boards-index-page.component.ts
  frontend/src/app/modules/boards/new-board-modal/new-board-modal.component.ts
  frontend/src/app/modules/boards/new-board-modal/new-board-modal.html
  frontend/src/app/modules/boards/openproject-boards.module.ts
  frontend/src/app/modules/hal/dm-services/query-form-dm.service.ts
  frontend/src/app/modules/hal/resources/query-filter-instance-resource.ts
  modules/boards/spec/features/board_management_spec.rb
  modules/boards/spec/features/status_board_spec.rb
  modules/boards/spec/features/support/board_page.rb
  spec/support/components/work_packages/filters.rb
Labels: feature

#7156 Avoid search filter being applied multiple times
  frontend/src/app/components/filters/quick-filter-by-text-input/quick-filter-by-text-input.component.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-filters.service.ts
Labels: bugfix

#7157 [29758][Boards] Show remove icon only with correct permissions
  frontend/src/app/modules/boards/board/board-list/board-list.component.html
  frontend/src/app/modules/boards/board/board-list/board-list.component.ts
Labels: bugfix

#7155 [29605][Boards] Improve styling of cards in board view
  app/assets/stylesheets/content/_editable_toolbar.sass
  frontend/src/app/components/wp-card-view/wp-card-view.component.sass
  frontend/src/app/modules/boards/board/board-list/board-list.component.html
  frontend/src/app/modules/boards/board/board-list/board-list.component.sass
  frontend/src/app/modules/boards/board/board.component.html
  frontend/src/app/modules/boards/board/board.component.sass
Labels: styling

#7159 [29754] Don't match substates in the /boards state definition
  frontend/src/app/modules/boards/board/board-list/board-list.component.ts
  frontend/src/app/modules/boards/openproject-boards.module.ts
Labels: bugfix, needs-review

#7160 Allow down migration of tsv to happen
  db/migrate/20180122135443_add_tsv_columns_to_attachments.rb
Labels: bugfix

#7162 [29752] Missing warning when switching from meetings (agenda / minutes) to other page
  modules/meeting/app/assets/javascripts/meeting/meeting.js
  modules/meeting/app/views/meeting_contents/_form.html.erb
Labels: bugfix

#7168 Correct hover effect of main menus with togglers
  app/assets/stylesheets/layout/_main_menu.sass
  lib/open_project/design.rb
Labels: bugfix, styling

#7171 [29820] [Forum] Trying to start editing a forum board returns an exception
  app/controllers/forums_controller.rb
Labels: bugfix, needs-review

#7170 [29819][Boards] Activate input field after clicking "New list"
  frontend/src/app/modules/boards/board/board-list/board-list.component.html
  frontend/src/app/modules/boards/board/board-list/board-list.component.ts
  frontend/src/app/modules/boards/board/board.component.ts
Labels: bugfix

#7169 [29812] Double click needed to edit the list name
  frontend/src/app/modules/common/editable-toolbar-title/editable-toolbar-title.component.ts
  frontend/src/app/modules/common/editable-toolbar-title/editable-toolbar-title.html
Labels: bugfix

#7173 [29824][Boards] Space below the horizontal scroll in boards view
  frontend/src/app/modules/boards/board/board-list/board-list.component.sass
  frontend/src/app/modules/boards/board/board.component.sass
  frontend/src/app/modules/boards/board/board.component.ts
Labels: bugfix, styling
