Repository opf/openproject, pull requests merged in 2019-12, with the labels that each got.

#7911 [31731] Lists are out of place in rtl-CF
  app/assets/stylesheets/content/editor/_ckeditor.sass
  app/assets/stylesheets/openproject/_generic.sass
Labels: bugfix, needs review, styling

#7909 [31698] Check if querySpace is initialized already to avoid reloading
  frontend/src/app/components/states/state-cache.service.ts
  frontend/src/app/components/wp-fast-table/wp-fast-table.ts
  frontend/src/app/modules/work_packages/routing/wp-list/wp-list.component.ts
Labels: bugfix

#7916 [31765] Selected long cf values are reduced to ... in ng-select
  app/assets/stylesheets/content/_autocomplete.sass
  app/assets/stylesheets/content/work_packages/inplace_editing/_display_fields.sass
Labels: bugfix, styling

#7917 [31683] Update the links to new documentation
  README.md
  config/locales/en.seeders.standard.yml
  docs/README.md
  docs/installation/packaged/2-configuration.md
  docs/operations/upgrading/manual/upgrading.md
  docs/user/textile-to-markdown-migration/README.md
  help/installation-and-operations/manual/upgrading.md
  help/user-guide/enterprise-features/agile-boards.md
  lib/open_project/static/links.rb
  modules/overviews/config/locales/en.seeders.bim.yml
  modules/overviews/config/locales/en.seeders.standard.yml
Labels: housekeeping

#7898 [31699] Feature: Scroll mobile header with content
  app/assets/stylesheets/layout/_base.sass
  app/assets/stylesheets/layout/_base_mobile.sass
  app/assets/stylesheets/layout/_top_menu_mobile.sass
  frontend/src/app/globals/global-listeners.ts
  frontend/src/app/globals/global-listeners/top-menu-scroll.ts
  frontend/src/app/modules/work_packages/routing/wp-list/wp-list.component.ts
Labels: feature

#7932 [31721] Remove FocusOut event which breaks iOS Safari menu
  frontend/src/app/components/main-menu/main-menu-toggle.service.ts
Labels: bugfix

#7934 [31723] Bottom bar overlaps content on mobile
  app/assets/stylesheets/layout/_base_mobile.sass
  app/assets/stylesheets/layout/_top_menu_mobile.sass
  frontend/src/app/globals/global-listeners.ts
  frontend/src/app/globals/global-listeners/top-menu-scroll.ts
  frontend/src/app/modules/router/openproject.routes.ts
  frontend/src/app/modules/work_packages/routing/wp-list/wp-list.component.ts
Labels: bugfix, needs review, styling

#7942 [31891] On mobile side menu is cut off when opening side menu
  app/assets/stylesheets/layout/_base_mobile.sass
Labels: bugfix, needs review

#7948 [31905] Remove tab "Forum" from project settings
  app/controllers/forums_controller.rb
  app/helpers/projects_helper.rb
  app/views/forums/edit.html.erb
  app/views/forums/index.html.erb
  app/views/project_settings/_forums.html.erb
  config/initializers/menus.rb
  spec/controllers/forums_controller_spec.rb
  spec/features/forums/attachment_upload_spec.rb
  spec/features/forums/message_spec.rb
  spec/features/forums/sticky_spec.rb
Labels: feature, housekeeping, needs review
