Repository opf/openproject, pull requests merged in 2019-11, with the labels that each got.

#7843 [31583] avoid parsing strings to yaml
  lib/open_project/configuration.rb
  spec/lib/open_project/configuration_spec.rb
Labels: bugfix

#7850 [31596] Use pristine, not projected resource for delta building
  frontend/src/app/components/wp-table/timeline/cells/timeline-milestone-cell-renderer.ts
Labels: bugfix

#7854 [31609] Make system user active
  app/contracts/members/create_contract.rb
  app/helpers/users_helper.rb
  app/models/principal.rb
  app/models/system_user.rb
  app/models/user.rb
  db/migrate/20191106132533_make_system_user_active.rb
  frontend/src/app/modules/common/path-helper/apiv3/apiv3-paths.ts
  frontend/src/app/modules/common/path-helper/path-helper.service.spec.ts
  lib/api/v3/memberships/schemas/membership_schema_representer.rb
  lib/api/v3/queries/schemas/all_principals_filter_dependency_representer.rb
  lib/api/v3/queries/schemas/user_filter_dependency_representer.rb
  lib/api/v3/utilities/custom_field_injector.rb
  lib/open_project/authentication/strategies/warden/global_basic_auth.rb
  spec/factories/user_factory.rb
  spec/lib/api/v3/memberships/schemas/membership_schema_representer_spec.rb
  spec/lib/api/v3/queries/schemas/all_principals_filter_dependency_representer_spec.rb
  spec/lib/api/v3/queries/schemas/user_filter_dependency_representer_spec.rb
  spec/lib/api/v3/utilities/custom_field_injector_spec.rb
  spec/models/system_user_spec.rb
  spec/services/users/delete_service_spec.rb
  spec_legacy/fixtures/users.yml
Labels: bugfix

#7858 Use sourcemaps for production angular builds for sentry
  frontend/package.json
Labels: housekeeping

#7857 Fix resetting the session for non-html requests
  app/controllers/application_controller.rb
Labels: bugfix, needs review

#7862 [31643] Don't try to render attachments on meeting content journal
  modules/meeting/app/controllers/meeting_contents_controller.rb
  modules/meeting/app/views/meeting_contents/_show.html.erb
  modules/meeting/app/views/meeting_contents/show.html.erb
Labels: bugfix

#7867 [31650] Avoid builtin in user limit
  app/controllers/account_controller.rb
  app/models/principal.rb
  app/models/setting/self_registration.rb
  app/models/user.rb
  app/models/user/status_options.rb
  app/views/authentication/authentication_settings.html.erb
  db/migrate/20191112111040_fix_system_user_status.rb
  lib/open_project/enterprise.rb
  modules/meeting/features/meetings_activity.feature
  modules/meeting/spec/features/meetings_activity_spec.rb
  spec/features/auth/omniauth_spec.rb
  spec/lib/open_project/enterprise_spec.rb
  spec/support/shared/acts_as_watchable.rb
Labels: bugfix, needs review

#7871 Fix for downloading attachments that are JSON files.
  lib/api/helpers/attachment_renderer.rb
  spec/requests/api/v3/attachments/attachment_resource_shared_examples.rb
Labels: needs review

#7879 [31667] Fix ambiguous reference to project_id when group/sort
  app/models/queries/work_packages/columns/property_column.rb
  spec/models/query/results_spec.rb
Labels: bugfix, needs review

#7881 [31566] Missing spaces before URLs in checklists
  app/assets/stylesheets/content/editor/_markdown.sass
Labels: bugfix, needs review

#7884 [31656] Right-to-left support for work package long text custom fields
  app/assets/javascripts/custom-fields.js
  app/assets/stylesheets/openproject/_generic.sass
  app/models/permitted_params.rb
  app/views/custom_fields/_form.html.erb
  db/migrate/20191115141154_add_content_orientation_to_custom_fields.rb
  frontend/src/app/components/wp-edit-form/display-field-renderer.ts
  frontend/src/app/modules/common/ckeditor/ckeditor-setup.service.ts
  frontend/src/app/modules/fields/display/display-field.module.ts
  frontend/src/app/modules/fields/display/field-types/formattable-display-field.module.ts
  frontend/src/app/modules/fields/edit/field-types/formattable-edit-field.component.ts
  frontend/src/app/modules/fields/edit/field-types/multi-select-edit-field.component.ts
  frontend/src/app/modules/fields/edit/field-types/select-edit-field.component.ts
  frontend/src/app/modules/fields/field.base.ts
  lib/api/decorators/property_schema_representer.rb
  lib/api/decorators/schema_representer.rb
  lib/api/v3/utilities/custom_field_injector.rb
  spec/lib/api/v3/work_packages/schema/work_package_sums_schema_representer_spec.rb
  spec/requests/api/v3/work_packages/work_packages_schemas_resource_spec.rb
Labels: feature, needs review

#7891 [31656] Remove schema property "visibility"
  lib/api/decorators/allowed_values_by_collection_representer.rb
  lib/api/decorators/property_schema_representer.rb
  lib/api/decorators/schema_representer.rb
  lib/api/v3/memberships/schemas/membership_schema_representer.rb
  lib/api/v3/projects/schemas/project_schema_representer.rb
  lib/api/v3/queries/schemas/custom_option_filter_dependency_representer.rb
  lib/api/v3/queries/schemas/filter_dependency_representer.rb
  lib/api/v3/queries/schemas/query_filter_instance_schema_representer.rb
  lib/api/v3/queries/schemas/query_schema_representer.rb
  lib/api/v3/versions/schemas/version_schema_representer.rb
  modules/backlogs/lib/api/v3/queries/schemas/backlogs_type_dependency_representer.rb
  modules/grids/app/representers/api/v3/grids/schemas/grid_schema_representer.rb
  modules/grids/spec/lib/api/v3/grids/schemas/grid_schema_representer_spec.rb
  spec/lib/api/v3/memberships/schemas/membership_schema_representer_spec.rb
  spec/lib/api/v3/projects/schemas/project_schema_representer_spec.rb
  spec/lib/api/v3/queries/schemas/query_filter_instance_schema_representer_spec.rb
  spec/lib/api/v3/queries/schemas/query_schema_representer_spec.rb
  spec/lib/api/v3/support/api_v3_filter_dependency.rb
  spec/lib/api/v3/support/schema_examples.rb
  spec/lib/api/v3/versions/schemas/version_schema_representer_spec.rb
  spec/lib/api/v3/work_packages/schema/work_package_sums_schema_representer_spec.rb
  spec/requests/api/v3/work_packages/work_packages_schemas_resource_spec.rb
Labels: housekeeping, needs review

#7882 [31631] Feature: Wp cards on mobile
  frontend/src/app/components/wp-card-view/event-handler/click-handler.ts
  frontend/src/app/components/wp-card-view/wp-card-view.component.ts
  frontend/src/app/components/wp-card-view/wp-single-card/wp-single-card.component.html
  frontend/src/app/components/wp-card-view/wp-single-card/wp-single-card.component.sass
  frontend/src/app/modules/work_packages/routing/wp-list/wp-list.component.ts
  frontend/src/app/modules/work_packages/routing/wp-view-base/work-packages-view.base.ts
  spec/features/work_packages/display_representations/switch_display_representations_spec.rb
  spec/support/pages/work_packages/work_package_cards.rb
Labels: feature, work in progress

#7892 [31214] Outline of display-field extends table cell width
  app/assets/stylesheets/content/work_packages/_table_content.sass
  frontend/src/app/components/wp-fast-table/builders/modes/hierarchy/single-hierarchy-row-builder.ts
Labels: bugfix, needs review, styling

#7897 Attempt to stabilise attachments_upload_spec
  spec/features/work_packages/attachments/attachment_upload_spec.rb
Labels: housekeeping

#7899 [31701] Feature: Mobile sidebar width not fullscreen
  app/assets/stylesheets/layout/_base.sass
  app/assets/stylesheets/layout/_main_menu_mobile.sass
  app/views/layouts/base.html.erb
Labels: feature, needs review

#7900 [31720] "group by"-header line to short
  frontend/src/app/components/wp-fast-table/builders/modes/grouped/grouped-rows-builder.ts
Labels: bugfix, styling

#7890 Add viewpoint GET and xml->json mapper
  .codeclimate.yml
  Gemfile
  Gemfile.lock
  lib/api/errors/bad_request.rb
  lib/api/errors/conflict.rb
  lib/api/errors/internal_error.rb
  lib/api/errors/invalid_query.rb
  lib/api/errors/invalid_render_context.rb
  lib/api/errors/invalid_request_body.rb
  lib/api/errors/invalid_resource_link.rb
  lib/api/errors/invalid_user_status_transition.rb
  lib/api/errors/multiple_errors.rb
  lib/api/errors/not_found.rb
  lib/api/errors/not_implemented.rb
  lib/api/errors/property_format_error.rb
  lib/api/errors/unauthenticated.rb
  lib/api/errors/unauthorized.rb
  lib/api/errors/unsupported_media_type.rb
  lib/api/errors/unwritable_property.rb
  lib/api/errors/validation.rb
  lib/api/root_api.rb
  lib/api/v3/errors/error_representer.rb
  modules/bcf/app/controllers/bcf/api/v2_1/topics_api.rb
  modules/bcf/app/controllers/bcf/api/v2_1/viewpoints/api.rb
  modules/bcf/app/models/bcf/issue.rb
  modules/bcf/app/models/bcf/viewpoint.rb
  modules/bcf/app/representers/bcf/api/v2_1/viewpoints/base_representer.rb
  modules/bcf/app/representers/bcf/api/v2_1/viewpoints/coloring_representer.rb
  modules/bcf/app/representers/bcf/api/v2_1/viewpoints/full_representer.rb
  modules/bcf/app/representers/bcf/api/v2_1/viewpoints/selection_representer.rb
  modules/bcf/app/representers/bcf/api/v2_1/viewpoints/visibility_representer.rb
  modules/bcf/app/views/bcf/issues/_render_issues.html.erb
  modules/bcf/db/migrate/20191121140202_migrate_xml_viewpoint_to_json.rb
  modules/bcf/lib/open_project/bcf/bcf_json/viewpoint_reader.rb
  modules/bcf/lib/open_project/bcf/bcf_xml/base_writer.rb
  modules/bcf/lib/open_project/bcf/bcf_xml/exporter.rb
  modules/bcf/lib/open_project/bcf/bcf_xml/issue_reader.rb
  modules/bcf/lib/open_project/bcf/bcf_xml/issue_writer.rb
  modules/bcf/lib/open_project/bcf/bcf_xml/viewpoint_writer.rb
  modules/bcf/spec/factories/bcf_issue_factory.rb
  modules/bcf/spec/factories/bcf_viewpoint_factory.rb
  modules/bcf/spec/factories/xml_viewpoint_factory.rb
  modules/bcf/spec/fixtures/viewpoints/full_viewpoint.bcfv.json
  modules/bcf/spec/fixtures/viewpoints/full_viewpoint.bcfv.xml
  modules/bcf/spec/fixtures/viewpoints/minimal.bcfv.json
  modules/bcf/spec/fixtures/viewpoints/minimal.bcfv.xml
  modules/bcf/spec/fixtures/viewpoints/neubau_sc_1.bcfv.json
  modules/bcf/spec/fixtures/viewpoints/neubau_sc_1.bcfv.xml
  modules/bcf/spec/fixtures/viewpoints/neubau_sc_1_fixed.bcfv.xml
  modules/bcf/spec/lib/open_project/bcf/bcf_json/viewpoint_reader_shared_examples.rb
  modules/bcf/spec/lib/open_project/bcf/bcf_json/viewpoint_reader_spec.rb
  modules/bcf/spec/lib/open_project/bcf/bcf_xml/viewpoint_writer_spec.rb
  modules/bcf/spec/requests/api/bcf/v2_1/shared_responses.rb
  modules/bcf/spec/requests/api/bcf/v2_1/viewpoints_api_spec.rb
  modules/bim_seeder/lib/open_project/bim_seeder/patches/work_package_seeder_patch.rb
  spec/models/queries/work_packages/manual_sorting_spec.rb
  spec/support/matchers/be_boolean.rb
Labels: feature, needs review

#7901 [31721] Second level menu of boards is not reachable on first click
  frontend/src/app/components/main-menu/main-menu-toggle.service.ts
  frontend/src/app/modules/boards/boards-sidebar/boards-menu.component.ts
Labels: bugfix, needs review

#7903 [31730] Main menu width is lost after closing it
  frontend/src/app/components/main-menu/main-menu-toggle.service.ts
Labels: bugfix, needs review

#7905 [31739] Use withCredentials: true in budget forms
  frontend/src/app/modules/common/remote-field-updater/remote-field-updater.component.ts
  modules/costs/frontend/module/augment/cost-budget-subform.augment.service.ts
  modules/costs/spec/features/budgets/add_budget_spec.rb
Labels: bugfix, needs review

#7904 [31732] Dropdown for table highlighting configuration is off place
  frontend/src/app/components/wp-table/configuration-modal/tabs/highlighting-tab.component.html
Labels: bugfix, needs review, styling

#7906 [31737] Double click on WP row not working
  frontend/src/app/components/wp-fast-table/handlers/row/click-handler.ts
  frontend/src/app/components/wp-fast-table/handlers/row/double-click-handler.ts
Labels: bugfix, needs review

#7907 [31702] Remove borders of card view on mobile work package page
  app/assets/stylesheets/layout/_toolbar_mobile.sass
  app/assets/stylesheets/layout/work_packages/_mobile.sass
  frontend/src/app/components/wp-card-view/styles/wp-card-view-horizontal.sass
  frontend/src/app/components/wp-card-view/wp-card-view.component.html
  frontend/src/app/components/wp-card-view/wp-card-view.component.ts
  frontend/src/app/components/wp-card-view/wp-single-card/wp-single-card.component.sass
  frontend/src/app/components/wp-card-view/wp-single-card/wp-single-card.component.ts
  frontend/src/app/components/wp-grid/wp-grid.component.ts
  frontend/src/app/modules/work_packages/routing/wp-list/wp-list.component.sass
Labels: feature, needs review, styling
