Repository opf/openproject, pull requests merged in 2019-07, with the labels that each got.

#7435 [30453] Replace last occurrence of toggled multi-select with ng-select
  app/assets/stylesheets/content/work_packages/_table_configuration_modal.sass
  frontend/src/app/components/wp-table/configuration-modal/tabs/highlighting-tab.component.html
  frontend/src/app/components/wp-table/configuration-modal/tabs/highlighting-tab.component.ts
  frontend/src/app/modules/common/multi-toggled-select/multi-toggled-select.component.html
  frontend/src/app/modules/common/multi-toggled-select/multi-toggled-select.component.ts
  frontend/src/app/modules/common/openproject-common.module.ts
  spec/support/components/work_packages/table_configuration/highlighting.rb
Labels: housekeeping

#7440 Remove pointer events hack in WP table
  app/assets/stylesheets/content/work_packages/_table_content.sass
  frontend/src/app/components/wp-edit-form/table-row-edit-context.ts
  frontend/src/app/components/wp-fast-table/handlers/row/double-click-handler.ts
  frontend/src/app/components/wp-fast-table/handlers/table-handler-registry.ts
  frontend/src/app/modules/fields/edit/edit-field.component.ts
Labels: housekeeping, needs-review

#7426 Update ng-select
  frontend/npm-shrinkwrap.json
  frontend/package.json
  frontend/src/app/components/filters/filter-toggled-multiselect-value/filter-toggled-multiselect-value.component.ts
  frontend/src/app/modules/boards/board/inline-add/board-inline-add-autocompleter.component.ts
  frontend/src/app/modules/common/autocomplete/create-autocompleter.component.ts
  frontend/src/app/modules/common/autocomplete/user-autocompleter.component.ts
  frontend/src/app/modules/fields/edit/field-types/multi-select-edit-field.component.html
  frontend/src/app/modules/fields/edit/field-types/multi-select-edit-field.component.ts
  frontend/src/styles.css
  frontend/tsconfig.json
Labels: housekeeping, needs-review

#7442 [30457] Search work package hints are not links
  app/assets/stylesheets/layout/_top_menu.sass
  frontend/src/app/modules/common/link-handling/link-handling.ts
  frontend/src/app/modules/global_search/global-search-input.component.html
  frontend/src/app/modules/global_search/global-search-input.component.ts
  spec/features/search_spec.rb
Labels: bugfix, needs-review

#7439 Lookup visible children in table beforehand
  frontend/src/app/components/projects/project-menu-autocomplete/project-menu-autocomplete.component.ts
  frontend/src/app/components/wp-edit-form/display-field-renderer.ts
  frontend/src/app/components/wp-fast-table/builders/cell-builder.ts
  frontend/src/app/components/wp-fast-table/builders/drag-and-drop/drag-drop-handle-render-pass.ts
  frontend/src/app/components/wp-fast-table/builders/modes/hierarchy/hierarchy-render-pass.ts
  frontend/src/app/components/wp-fast-table/builders/modes/hierarchy/single-hierarchy-row-builder.ts
  frontend/src/app/components/wp-fast-table/builders/primary-render-pass.ts
  frontend/src/app/components/wp-fast-table/builders/rows/single-row-builder.ts
  frontend/src/app/components/wp-fast-table/handlers/state/highlighting-transformer.ts
  frontend/src/app/components/wp-fast-table/handlers/state/rows-transformer.ts
  frontend/src/app/components/wp-fast-table/helpers/wp-table-hierarchy-helpers.ts
  frontend/src/app/components/wp-fast-table/wp-fast-table.ts
  frontend/src/app/components/wp-inline-create/wp-inline-create.component.ts
  frontend/src/app/components/wp-query-select/wp-query-select-dropdown.component.ts
  frontend/src/app/components/wp-table/timeline/cells/timeline-cell-renderer.ts
  frontend/src/app/modules/fields/display/display-field.module.ts
  frontend/src/app/modules/fields/display/display-field.service.ts
  modules/costs/frontend/module/wp-display/wp-display-costs-by-type-field.module.ts
Labels: housekeeping, performance

#7448 Reinstate contain: strict for performance wins in the table
  app/assets/stylesheets/layout/work_packages/_table.sass
Labels: performance

#7445 [30441] Maintain the order of work packages in a separate table service
  config/locales/js-en.yml
  frontend/src/app/components/wp-fast-table/handlers/state/drag-and-drop-transformer.ts
  frontend/src/app/components/wp-fast-table/handlers/state/rows-transformer.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-order.service.ts
  frontend/src/app/components/wp-list/wp-states-initialization.service.ts
  frontend/src/app/modules/boards/board/inline-add/board-inline-add-autocompleter.component.ts
  frontend/src/app/modules/common/editable-toolbar-title/editable-toolbar-title.component.ts
  frontend/src/app/modules/work_packages/query-space/isolated-query-space.ts
  frontend/src/app/modules/work_packages/query-space/wp-isolated-query-space.directive.ts
  frontend/src/app/modules/work_packages/routing/wp-list/wp-list.component.ts
  frontend/src/app/modules/work_packages/routing/wp-list/wp.list.component.html
  frontend/src/app/modules/work_packages/routing/wp-view-base/work-packages-view.base.ts
  lib/open_project/logging/log_delegator.rb
  spec/features/work_packages/sorting/manual_sorting_spec.rb
  spec/features/work_packages/table/queries/query_history_spec.rb
  spec/features/work_packages/work_package_index_spec.rb
Labels: feature, needs-review

#7453 [30490] Table is not scrollable with enabled Gantt chart
  frontend/src/app/components/wp-table/wp-table.directive.ts
Labels: bugfix

#7455 Fix: cached highlighting styles
  config/application.rb
  lib/open_project/configuration.rb
  lib/open_project/configuration/asset_host.rb
  spec/views/layouts/base.html.erb_spec.rb
Labels: bugfix, needs-review

#7443 Restyle edit fields
  app/assets/stylesheets/content/_attributes_key_value.sass
  app/assets/stylesheets/content/_work_packages.sass
  app/assets/stylesheets/content/work_packages/_table_hierarchy.sass
  app/assets/stylesheets/content/work_packages/inplace_editing/_edit_fields.sass
  app/assets/stylesheets/content/work_packages/inplace_editing/_legacy_inplace_styles.sass
  frontend/src/app/components/work-packages/work-package-comment/work-package-comment-field-handler.ts
  frontend/src/app/components/wp-edit-form/table-row-edit-context.ts
  frontend/src/app/components/wp-edit-form/work-package-edit-field-handler.ts
  frontend/src/app/modules/fields/edit/edit-field.component.ts
  frontend/src/app/modules/fields/edit/editing-portal/edit-field-handler.ts
  frontend/src/app/modules/fields/edit/field-types/float-edit-field.component.ts
  frontend/src/app/modules/fields/edit/field-types/integer-edit-field.component.ts
  frontend/src/app/modules/fields/edit/field-types/text-edit-field.component.ts
  spec/features/work_packages/cancel_editing_spec.rb
  spec/features/work_packages/edit_work_package_spec.rb
  spec/support/work_packages/work_package_field.rb
Labels: styling

#7457 Feature: puma (multithreading support)
  Gemfile
  Gemfile.lock
  Procfile
  app/middleware/reset_current_user.rb
  app/models/user.rb
  app/workers/application_job.rb
  config/application.rb
  config/environments/production.rb
  config/puma.rb
  docker/web
  lib/open_project/configuration.rb
  packaging/scripts/web
  spec/features/api/authentication_spec.rb
  spec/lib/redmine/i18n_spec.rb
  spec/requests/api/v3/authentication_spec.rb
  spec/requests/current_user_spec.rb
  spec/workers/application_job_spec.rb
Labels: feature

#7456 Attachments content disposition in APIv3
  app/models/attachment.rb
  app/uploaders/file_uploader.rb
  app/uploaders/fog_file_uploader.rb
  lib/api/helpers/attachment_renderer.rb
  spec/fixtures/files/textfile.txt.gz
  spec/models/attachment_spec.rb
  spec/requests/api/v3/attachments/attachment_resource_shared_examples.rb
Labels: bugfix, feature, needs-review

#7454 [30501] Render text field links in the backend independently of the user
  app/assets/stylesheets/openproject/_generic.sass
  app/helpers/work_packages_helper.rb
  frontend/src/app/angular4-modules.ts
  frontend/src/app/components/modals/preview-modal/wp-preview-modal/wp-preview.modal.html
  frontend/src/app/components/modals/preview-modal/wp-preview-modal/wp-preview.modal.sass
  frontend/src/app/components/modals/preview-modal/wp-preview-modal/wp-preview.modal.ts
  frontend/src/app/globals/global-listeners/preview-trigger.service.ts
  lib/open_project/text_formatting/matchers/link_handlers/colon_separator.rb
  lib/open_project/text_formatting/matchers/link_handlers/hash_separator.rb
  lib/open_project/text_formatting/matchers/link_handlers/revisions.rb
  lib/open_project/text_formatting/matchers/link_handlers/work_packages.rb
  spec/lib/api/v3/repositories/revision_representer_spec.rb
  spec/lib/open_project/text_formatting/markdown/markdown_spec.rb
  spec/requests/api/v3/render_resource_spec.rb
Labels: needs-review

#7449 Allow at max 250 elements to be rendered with manual sorting
  Dockerfile
  app/assets/stylesheets/content/work_packages/_table_content.sass
  app/models/query/manual_sorting.rb
  app/services/api/v3/work_package_collection_from_query_service.rb
  config/locales/js-en.yml
  config/settings.yml
  frontend/src/app/components/main-menu/main-menu-toggle.component.ts
  frontend/src/app/components/routing/my-page/my-page.component.html
  frontend/src/app/components/routing/my-page/my-page.component.ts
  frontend/src/app/components/wp-list/wp-states-initialization.service.ts
  frontend/src/app/components/wp-query-select/wp-query-select-dropdown.component.ts
  frontend/src/app/components/wp-table/embedded/wp-embedded-base.component.ts
  frontend/src/app/components/wp-table/wp-table.directive.html
  frontend/src/app/components/wp-table/wp-table.directive.ts
  frontend/src/app/modules/boards/board/board-list/board-lists.service.ts
  frontend/src/app/modules/common/notifications/notification.component.ts
  frontend/src/app/modules/common/notifications/notifications-container.component.ts
  frontend/src/app/modules/work_packages/routing/wp-list/wp-list.component.ts
  frontend/src/app/modules/work_packages/routing/wp-list/wp.list.component.html
Labels: feature, needs-review

#7131 Let Global search also search within custom fields
  app/models/queries/work_packages/filter/search_filter.rb
  spec/features/search_spec.rb
Labels: needs-review

#7464 [30518] Fix writing HalResource arrays into $source when copying
  frontend/src/app/modules/hal/helpers/hal-resource-builder.ts
  frontend/src/app/modules/hal/resources/work-package-resource.ts
  spec/features/work_packages/copy_spec.rb
Labels: bugfix

#7470 Fix missing eager loading paths in production
  app/models/journal.rb
  app/models/legacy_journal.rb
  config/application.rb
  config/initializers/00-core_plugins.rb
  lib/generators/open_project/plugin/plugin_generator.rb
  lib/open_project/hooks/activity_index_head_hook.rb
  lib/open_project/hooks/view_projects_form_hook.rb
  lib/open_project/plugins/acts_as_op_engine.rb
  lib/plugins/acts_as_journalized/init.rb
  lib/plugins/acts_as_journalized/lib/acts_as_journalized.rb
  lib/plugins/acts_as_journalized/lib/journal_formatter.rb
  lib/plugins/acts_as_journalized/lib/journal_formatter/attribute.rb
  lib/plugins/acts_as_journalized/lib/journal_formatter/base.rb
  lib/plugins/acts_as_journalized/lib/journal_formatter/datetime.rb
  lib/plugins/acts_as_journalized/lib/journal_formatter/decimal.rb
  lib/plugins/acts_as_journalized/lib/journal_formatter/fraction.rb
  lib/plugins/acts_as_journalized/lib/journal_formatter/id.rb
  lib/plugins/acts_as_journalized/lib/journal_formatter/named_association.rb
  lib/plugins/acts_as_journalized/lib/journal_formatter/plaintext.rb
  lib/plugins/acts_as_journalized/lib/journal_formatter/proc.rb
  lib/plugins/acts_as_journalized/test/changes_test.rb
  lib/plugins/acts_as_journalized/test/conditions_test.rb
  lib/plugins/acts_as_journalized/test/configuration_test.rb
  lib/plugins/acts_as_journalized/test/control_test.rb
  lib/plugins/acts_as_journalized/test/creation_test.rb
  lib/plugins/acts_as_journalized/test/options_test.rb
  lib/plugins/acts_as_journalized/test/reload_test.rb
  lib/plugins/acts_as_journalized/test/reset_test.rb
  lib/plugins/acts_as_journalized/test/reversion_test.rb
  lib/plugins/acts_as_journalized/test/schema.rb
  lib/plugins/acts_as_journalized/test/tagging_test.rb
  lib/plugins/acts_as_journalized/test/test_helper.rb
  lib/plugins/acts_as_journalized/test/users_test.rb
  lib/plugins/acts_as_journalized/test/version_test.rb
  lib/plugins/acts_as_journalized/test/versioned_test.rb
  lib/plugins/acts_as_journalized/test/versions_test.rb
  lib/plugins/verification/test/test_helper.rb
  lib/plugins/verification/test/verification_test.rb
  lib/redmine/plugin.rb
  lib/redmine_plugin_locator.rb
  modules/github_integration/lib/open_project/github_integration/engine.rb
  modules/reporting_engine/lib/reporting_engine/engine.rb
  modules/reporting_engine/lib/widget/filters/multi_choice.rb
  modules/webhooks/lib/open_project/webhooks.rb
  modules/webhooks/lib/open_project/webhooks/event_resources.rb
  modules/xls_export/lib/open_project/xls_export/disabled/hooks/cost_report_hook.rb
  modules/xls_export/lib/open_project/xls_export/disabled/patches/cost_reports_controller_patch.rb
  modules/xls_export/lib/open_project/xls_export/disabled/xls_views.rb
  modules/xls_export/lib/open_project/xls_export/disabled/xls_views/cost_entry_table.xls.rb
  modules/xls_export/lib/open_project/xls_export/disabled/xls_views/cost_report_table.xls.rb
  modules/xls_export/lib/open_project/xls_export/disabled/xls_views/simple_cost_report_table.xls.rb
Labels: needs-review

#7477 Enable debian 10
  .pkgr.yml
Labels: packager, work in progress

#7475 [30532] Don't submit notification mails for parent changes
  app/services/work_packages/update_ancestors_service.rb
  spec/models/work_package/work_package_notifications_spec.rb
  spec/services/work_packages/update_service_spec.rb
Labels: feature, needs-review

#7472 Fix: estimated hours sum
  app/models/queries/work_packages/columns/work_package_column.rb
  app/models/work_package/parent.rb
  config/application.rb
  config/environments/development.rb
  lib/core_extensions.rb
  lib/core_extensions/string.rb
  spec/models/queries/work_packages/columns/work_package_column_spec.rb
  spec/support/work_packages.rb
Labels: bugfix, needs-review

#7484 [30590] Fix switching into closed status with closed version assigned
  app/contracts/work_packages/base_contract.rb
  config/locales/js-en.yml
  frontend/src/app/components/op-context-menu/handlers/wp-status-dropdown-menu.directive.ts
  frontend/src/app/components/wp-buttons/wp-status-button/wp-status-button.component.ts
  frontend/src/app/components/wp-buttons/wp-status-button/wp-status-button.html
  spec/contracts/work_packages/base_contract_spec.rb
  spec/features/work_packages/details/closed_status_and_version_spec.rb
Labels: bugfix

#7486 [30595] Fix board links when router not initialized
  frontend/src/app/modules/boards/boards-sidebar/boards-menu.component.html
  frontend/src/app/modules/boards/boards-sidebar/boards-menu.component.ts
  frontend/src/app/modules/router/openproject.routes.ts
  modules/boards/spec/features/board_navigation_spec.rb
Labels: bugfix

#7488 [30591] Use username for login form
  config/locales/en.yml
  modules/reporting/spec/features/permissions_spec.rb
  spec/controllers/concerns/auth_source_sso_spec.rb
  spec/features/auth/login_spec.rb
  spec/features/auth/logout_spec.rb
  spec/features/users/brute_force_spec.rb
  spec/features/users/self_registration_spec.rb
  spec/models/mail_handler_spec.rb
  spec/support/pages/new_user.rb
  spec/views/layouts/base.html.erb_spec.rb
Labels: bugfix

#7489 [30589] Allow inline-create only with edit_work_packages permission
  frontend/src/app/components/wp-inline-create/wp-inline-create.service.ts
  frontend/src/app/modules/boards/board/board-list/board-inline-create.service.ts
  modules/my_page/spec/features/my/assigned_to_me_spec.rb
  spec/features/work_packages/details/query_groups/relation_query_group_spec.rb
  spec/features/work_packages/table/inline_create/create_work_packages_spec.rb
  spec/features/work_packages/table/inline_create/parallel_creation_spec.rb
Labels: bugfix

#7490 [30574] Correct float formatting in reporting and budgets
  lib/redmine/i18n.rb
  modules/costs/app/views/cost_objects/_show_variable_cost_object.html.erb
  modules/costs/spec/features/time_entries_spec.rb
  modules/reporting/spec/features/custom_fields_spec.rb
  modules/reporting/spec/features/me_value_spec.rb
  modules/reporting/spec/features/permissions_spec.rb
  spec/features/time_entry/time_entry_report_spec.rb
Labels: bugfix

#7494 [30600] Create grid layout icon
  app/assets/fonts/openproject_icon/openproject-icon-font.svg
  app/assets/fonts/openproject_icon/openproject-icon-font.ttf
  app/assets/fonts/openproject_icon/openproject-icon-font.woff
  app/assets/fonts/openproject_icon/openproject-icon-font.woff2
  app/assets/fonts/openproject_icon/src/view-card.svg
  app/assets/stylesheets/fonts/_openproject_icon_definitions.scss
  app/assets/stylesheets/fonts/_openproject_icon_font.lsg
  frontend/src/app/components/wp-buttons/wp-view-toggle-button/work-package-view-toggle-button.component.ts
Labels: feature

#7493 [30572] References in seeded Scrum project point to Demo project
  app/seeders/demo_data/work_package_seeder.rb
Labels: bugfix, needs-review
