Repository opf/openproject, pull requests merged in 2019-02, with the labels that each got.

#7024 [29423] Replace class '-hidden-content' in generic tables
  app/assets/stylesheets/content/_table.sass
  app/views/repositories/_revisions.html.erb
  app/views/wiki/history.html.erb
Labels: housekeeping, styling

#7021 [29468] Deactivate option "Use current date as start date for new work packages" by default
  config/settings.yml
Labels: feature, needs-review

#7020 Attempt to stabilise tests
  spec/features/work_packages/details/relations/hierarchy_spec.rb
  spec/models/journal/aggregated_journal_spec.rb
  spec/support/components/work_packages/relations.rb
Labels: housekeeping

#7029 [28484] Remove frontend browser detector with rails based view
  Gemfile
  Gemfile.lock
  app/assets/javascripts/onboarding/onboarding_tour.js
  app/assets/stylesheets/layout/_top_shelf.sass
  app/helpers/application_helper.rb
  app/helpers/browser_helper.rb
  app/views/browser/_unsupported_browser.html.erb
  app/views/layouts/base.html.erb
  config/locales/en.yml
  config/locales/js-en.yml
  frontend/npm-shrinkwrap.json
  frontend/package.json
  frontend/src/app/components/op-context-menu/handlers/op-types-context-menu.directive.ts
  frontend/src/app/globals/browser-specific-flags.ts
  frontend/src/app/globals/top-shelf.ts
  frontend/src/app/globals/unsupported-browsers.ts
  frontend/src/app/init-globals.ts
  frontend/src/app/modules/common/browser/browser-detector.service.ts
  frontend/src/app/modules/common/openproject-common.module.ts
Labels: bugfix, needs-review

#7030 Display a security badge with the installation status
  Dockerfile.public
  app/helpers/security_badge_helper.rb
  app/views/admin/info.html.erb
  app/views/homescreen/blocks/_administration.html.erb
  app/views/settings/_general.html.erb
  config/initializers/secure_headers.rb
  config/initializers/security_badge.rb
  config/locales/en.yml
  config/settings.yml
  lib/open_project/configuration.rb
  spec/helpers/security_badge_helper_spec.rb
Labels: feature

#7026 [29462] Avatars/Names not loading when not logged in
  lib/api/v3/users/users_api.rb
  spec/requests/api/v3/user/user_resource_spec.rb
Labels: bugfix

#7032 Add default avatars
  app/assets/stylesheets/content/_autocomplete.sass
  app/assets/stylesheets/content/_user.lsg
  app/assets/stylesheets/content/_user.sass
  app/assets/stylesheets/layout/_top_menu.sass
  frontend/src/app/components/user/user-avatar/user-avatar.component.html
  frontend/src/app/components/user/user-avatar/user-avatar.component.ts
  frontend/src/app/components/wp-activity/revision/revision-activity.component.html
  frontend/src/app/components/wp-activity/revision/revision-activity.component.ts
  frontend/src/app/components/wp-activity/user/user-activity.component.html
  frontend/src/app/components/wp-activity/user/user-activity.component.ts
  frontend/src/app/components/wp-single-view-tabs/watchers-tab/watchers-tab.component.ts
  frontend/src/app/components/wp-single-view-tabs/watchers-tab/watchers-tab.html
  frontend/src/app/components/wp-single-view-tabs/watchers-tab/wp-watcher-entry.html
  frontend/src/app/modules/common/autocomplete/user-autocompleter.component.ts
  frontend/src/app/modules/common/openproject-common.module.ts
  lib/open_project/design.rb
  lib/redmine/menu_manager/top_menu_helper.rb
  modules/avatars/app/views/settings/_openproject_avatars.html.erb
  modules/avatars/frontend/module/globals/global-avatar-fallback.ts
  modules/avatars/frontend/module/main.ts
  modules/avatars/lib/open_project/avatars/avatar_manager.rb
  modules/avatars/lib/open_project/avatars/patches/avatar_helper_patch.rb
  modules/avatars/spec/helpers/avatar_helper_spec.rb
  modules/meeting/app/views/meetings/show.html.erb
  spec/features/support/components/ngselect_autocompleter.rb
  spec/features/work_packages/tabs/watcher_tab_spec.rb
Labels: feature

#7036 [29482] Editor dropdown is cut off when opened to top
  app/assets/stylesheets/content/_forms.sass
  app/views/wiki/_page_form.html.erb
  modules/my_project_page/app/views/my_projects_overviews/_block_textilizable.html.erb
Labels: bugfix, styling

#7016 Replace jQuery autocompleter by ng-select
  app/assets/stylesheets/layout/_top_menu.sass
  config/locales/js-en.yml
  frontend/src/app/modules/global_search/global-search-input.component.html
  frontend/src/app/modules/global_search/global-search-input.component.ts
  frontend/src/app/modules/global_search/global-search-work-packages.component.ts
  modules/meeting/spec/features/meetings_search_spec.rb
  spec/features/search_spec.rb
  spec/features/support/components/ng_select_autocomplete.rb
  spec/features/work_packages/tabs/watcher_tab_spec.rb
Labels: needs-review

#7038 [29492][29531] Styling issues with the WP field autocompleter
  app/assets/stylesheets/content/_autocomplete.sass
Labels: bugfix, styling

#7039 Fix LDAP synchronized group plugin loading and deletion
  Gemfile.lock
  Gemfile.modules
  modules/ldap_groups/app/cells/ldap_groups/synchronized_groups/row_cell.rb
Labels: bugfix

#7044 Reduce number of API calls for user avatars
  frontend/src/app/components/wp-activity/revision/revision-activity.component.html
  frontend/src/app/components/wp-activity/revision/revision-activity.component.ts
  frontend/src/app/components/wp-activity/user/user-activity.component.html
  frontend/src/app/components/wp-activity/user/user-activity.component.ts
  frontend/src/app/components/wp-single-view-tabs/watchers-tab/wp-watcher-entry.html
  frontend/src/app/modules/common/autocomplete/user-autocompleter.component.ts
Labels: housekeeping, work in progress

#7031 Global search for mobile devices
  app/assets/stylesheets/layout/_top_menu.sass
  app/assets/stylesheets/layout/_top_menu_mobile.sass
  app/views/search/_mini_form.html.erb
  config/locales/js-en.yml
  frontend/src/app/angular4-modules.ts
  frontend/src/app/components/resizer/main-menu-toggle.component.ts
  frontend/src/app/components/resizer/main-menu-toggle.service.ts
  frontend/src/app/modules/common/browser/device.service.ts
  frontend/src/app/modules/global_search/global-search-input.component.html
  frontend/src/app/modules/global_search/global-search-input.component.ts
  lib/redmine/menu_manager/top_menu_helper.rb
Labels: needs-review

#7046 [29468] Custom fields for groups throw error message when set
  app/models/permitted_params.rb
  app/views/customizable/_form.html.erb
Labels: bugfix, needs-review

#7048 User avatars not loaded correctly on the WP activity
  app/assets/stylesheets/content/_user.sass
  frontend/src/app/components/user/user-avatar/user-avatar.component.ts
  frontend/src/app/components/wp-activity/revision/revision-activity.component.html
  frontend/src/app/components/wp-activity/revision/revision-activity.component.ts
  frontend/src/app/components/wp-activity/user/user-activity.component.html
  spec/features/work_packages/tabs/activity_revisions_spec.rb
Labels: bugfix

#7049 [29561 ] Better errors when bulk editing
  app/controllers/work_packages/bulk_controller.rb
  app/services/service_result.rb
  app/services/work_packages/bulk/update_service.rb
  app/views/work_packages/bulk/edit.html.erb
  config/locales/en.yml
  spec/controllers/work_packages/bulk_controller_spec.rb
  spec/features/work_packages/bulk/update_work_package_spec.rb
Labels: feature, needs-review

#7050 [29497] Gantt chart not properly aligned when using groups
  app/assets/stylesheets/content/work_packages/_table_content.sass
Labels: bugfix, needs-review

#7054 [29467] Automatic calculation of work packages per pagination based on widget height
  frontend/src/app/components/table-pagination/table-pagination.component.html
  frontend/src/app/components/table-pagination/table-pagination.component.ts
  frontend/src/app/components/wp-table/embedded/wp-embedded-table.component.ts
  frontend/src/app/components/wp-table/embedded/wp-embedded-table.html
  frontend/src/app/components/wp-table/wp-table-configuration.ts
  frontend/src/app/modules/grids/grid/grid.component.html
  frontend/src/app/modules/grids/widgets/wp-accountable/wp-accountable.component.ts
  frontend/src/app/modules/grids/widgets/wp-assigned/wp-assigned.component.ts
  frontend/src/app/modules/grids/widgets/wp-created/wp-created.component.ts
  frontend/src/app/modules/grids/widgets/wp-watched/wp-watched.component.ts
  frontend/src/app/modules/grids/widgets/wp-widget/wp-widget.component.ts
Labels: feature, needs-review

#7059 [29461] Better error handling for attachment upload size limits
  config/locales/js-en.yml
  frontend/src/app/components/wp-edit/wp-notification.service.ts
  frontend/src/app/modules/common/notifications/upload-progress.component.ts
  frontend/src/app/modules/hal/resources/mixins/attachable-mixin.ts
Labels: bugfix

#7058 Fix renaming of board through dropdown
  frontend/src/app/modules/boards/board/toolbar-menu/boards-toolbar-menu.directive.ts
  modules/boards/spec/features/board_management_spec.rb
  modules/boards/spec/features/support/board_page.rb
Labels: bugfix

#7060 [29581] Fix redrawing table and loosen contain
  app/assets/stylesheets/layout/work_packages/_table.sass
  frontend/src/app/modules/calendar/wp-calendar/wp-calendar.component.ts
Labels: bugfix

#7056 [29357] Migrate my page to Grid based layout
  db/migrate/20190220080647_migrate_my_page_layout.rb
  frontend/src/app/modules/grids/widgets/news/news.component.html
  frontend/src/app/modules/grids/widgets/news/news.component.ts
  frontend/src/app/modules/grids/widgets/time-entries-current-user/time-entries-current-user.component.ts
  modules/grids/app/models/grids/grid.rb
Labels: feature

#7061 [29588] Don't replace filters service during search filter change
  frontend/src/app/components/filters/quick-filter-by-text-input/quick-filter-by-text-input.component.ts
  frontend/src/app/components/wp-table/configuration-modal/tabs/filters-tab.component.html
Labels: bugfix

#7063 [29582] Hide query groups in new wp screens
  frontend/src/app/components/work-packages/wp-single-view/wp-single-view.component.ts
  spec/features/types/form_configuration_query_spec.rb
Labels: bugfix

#7062 [29100] Ensure mails are handled in the update service
  app/models/mail_handler.rb
  app/views/settings/_mail_handler.html.erb
  config/locales/en.yml
  config/settings.yml
  spec/fixtures/mail_handler/update_ticket_with_attachment_and_sig.eml
  spec/models/mail_handler_spec.rb
  spec_legacy/fixtures/mail_handler/ticket_reply_with_status.eml
Labels: bugfix

#7057 [29460] Fix redundant wp type in relations tab
  app/assets/stylesheets/content/work_packages/_table_relations.sass
  frontend/src/app/components/wp-relations/wp-relation-row/wp-relation-row.template.html
  frontend/src/app/modules/hal/resources/work-package-resource.ts
  spec/support/components/work_packages/relations.rb
Labels: work in progress

#7064 Extend onboarding tour library to accept timeout functions
  app/assets/javascripts/onboarding/work_package_tour.js
  app/assets/javascripts/vendor/enjoyhint.js
Labels: bugfix, needs-review

#7067 Disable hierarchy toggle in embedded widgets for 8.3
  frontend/src/app/modules/grids/widgets/wp-widget/wp-widget.component.ts
Labels: bugfix

#7068 [29595] Remove cost_entries page when cost reporting is disabled
  app/controllers/application_controller.rb
  modules/costs/app/controllers/costlog_controller.rb
  modules/costs/app/helpers/costlog_helper.rb
  modules/costs/app/views/costlog/_date_range.html.erb
  modules/costs/app/views/costlog/_list.html.erb
  modules/costs/app/views/costlog/index.html.erb
  modules/costs/config/routes.rb
  modules/costs/frontend/module/wp-display/wp-display-costs-by-type-field.module.ts
  modules/costs/lib/open_project/costs/engine.rb
  modules/costs/lib/open_project/costs/patches/project_patch.rb
  modules/costs/lib/open_project/costs/patches/work_package_patch.rb
  modules/costs/spec/controllers/costlog_controller_spec.rb
  modules/costs/spec/routing/costlog_routing_spec.rb
  modules/reporting/app/controllers/work_package_costlog_controller.rb
  modules/reporting/config/routes.rb
  modules/reporting/lib/open_project/reporting/engine.rb
  modules/reporting/lib/open_project/reporting/patches/costlog_controller_patch.rb
  modules/reporting/spec/features/work_package_costlog_spec.rb
  modules/reporting/spec/routing/costlog_routing_spec.rb
Labels: bugfix

#7069 [29598] Fix SQL joins from filter when grouping
  app/models/query/results.rb
  spec/models/query/results_spec.rb
Labels: bugfix

#7070 [29604] Fix project autocompleter loading text
  app/assets/stylesheets/layout/_top_menu.sass
Labels: bugfix, needs-review, styling

#7074 Fix global search input hover color
  app/assets/stylesheets/layout/_top_menu.sass
Labels: bugfix, needs-review, styling

#7073 [29596] Closing icon in wp column configuration modal aligned correctly
  app/assets/stylesheets/content/_modal.sass
  app/assets/stylesheets/vendor/_select2.scss
Labels: bugfix, needs-review, styling

#7072 [29609] Incompatibility warning in IE / old versions of FF messes up layout
  app/assets/stylesheets/layout/_top_shelf.sass
Labels: bugfix, styling

#7076 [29614] Main menu toggler hover color corrected
  app/assets/stylesheets/layout/_top_menu.sass
Labels: bugfix, needs-review, styling

#7079 [29578] Refactor wp-set in common work-packges-view-base
  frontend/src/app/components/wp-table/embedded/wp-embedded-base.component.ts
  frontend/src/app/components/wp-table/embedded/wp-embedded-table.component.ts
  frontend/src/app/modules/calendar/wp-calendar-entry/wp-calendar-entry.component.html
  frontend/src/app/modules/calendar/wp-calendar-entry/wp-calendar-entry.component.ts
  frontend/src/app/modules/grids/widgets/wp-widget/wp-widget.component.ts
  frontend/src/app/modules/work_packages/routing/wp-full-view/wp-full-view.component.ts
  frontend/src/app/modules/work_packages/routing/wp-list/wp-list.component.ts
  frontend/src/app/modules/work_packages/routing/wp-split-view/wp-split-view.component.ts
  frontend/src/app/modules/work_packages/routing/wp-view-base/work-package-single-view.base.ts
  frontend/src/app/modules/work_packages/routing/wp-view-base/work-packages-view.base.ts
  modules/grids/spec/features/my/my_page_assigned_to_me_spec.rb
  spec/support/components/work_packages/hierarchies.rb
Labels: bugfix

#7071 [26758] Show unit on group by headers
  frontend/src/app/components/wp-fast-table/builders/modes/grouped/grouped-render-pass.ts
  lib/api/decorators/aggregation_group.rb
  spec/features/work_packages/table/group_by/group_by_progress_spec.rb
Labels: feature, needs-review

#7081 [29617] Type field too small (cut off unnecessarily)
  app/assets/stylesheets/content/work_packages/_table_content.sass
  frontend/src/app/components/wp-edit-form/table-row-edit-context.ts
Labels: bugfix, needs-review, styling

#7077 [29610] Translations missing on MyPage
  config/locales/en.yml
  config/locales/js-en.yml
  modules/grids/config/locales/en.yml
  modules/grids/config/locales/js-en.yml
Labels: bugfix, needs-review

#7083 Fix: Submit global search on enter before results are loaded
  frontend/src/app/modules/global_search/global-search-input.component.html
  frontend/src/app/modules/global_search/global-search-input.component.ts
  spec/features/search_spec.rb
Labels: bugfix, needs-review

#7084 [29619] Follows-precedes relationship arrow in Gantt chart not correctly connected
  frontend/src/app/components/wp-table/timeline/global-elements/wp-timeline-relations.directive.ts
Labels: bugfix, needs-review, styling

#7086 Global search advanced filters styling adapted
  app/assets/stylesheets/content/_advanced_filters.sass
  frontend/src/app/components/filters/filter-container/filter-container.directive.html
Labels: needs-review, styling

#7078 [29476] Forum layout adapted to news layout
  app/assets/stylesheets/content/_comments.sass
  app/assets/stylesheets/content/_index.sass
  app/assets/stylesheets/content/_news.lsg
  app/assets/stylesheets/content/_news.sass
  app/views/messages/show.html.erb
  app/views/news/_news.html.erb
  app/views/news/index.html.erb
  app/views/news/show.html.erb
  spec/support/pages/messages/show.rb
Labels: bugfix, needs-review, styling

#7085 Global search polishing
  app/assets/stylesheets/content/_tabs.sass
  frontend/src/app/components/wp-fast-table/builders/rows/single-row-builder.ts
  frontend/src/app/components/wp-table/wp-table.directive.html
  frontend/src/app/modules/a11y/keyboard-shortcut-service.ts
  frontend/src/app/modules/global_search/global-search-input.component.html
  frontend/src/app/modules/global_search/global-search-input.component.ts
Labels: needs-review

#7082 Replace non-copyable table state classes with objects
  frontend/src/app/ckeditor/ckeditor-augmented-textarea.component.ts
  frontend/src/app/components/filters/filter-container/filter-container.directive.ts
  frontend/src/app/components/filters/query-filters/query-filters.component.html
  frontend/src/app/components/filters/query-filters/query-filters.component.ts
  frontend/src/app/components/filters/quick-filter-by-text-input/quick-filter-by-text-input.component.ts
  frontend/src/app/components/states.service.ts
  frontend/src/app/components/wp-buttons/wp-filter-button/wp-filter-button.component.ts
  frontend/src/app/components/wp-fast-table/handlers/cell/relations-cell-handler.ts
  frontend/src/app/components/wp-fast-table/handlers/state/hierarchy-transformer.ts
  frontend/src/app/components/wp-fast-table/handlers/state/timeline-transformer.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-base.service.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-columns.service.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-filters.service.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-group-by.service.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-hierarchy.service.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-highlighting.service.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-relation-columns.service.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-sort-by.service.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-sum.service.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-timeline.service.ts
  frontend/src/app/components/wp-fast-table/wp-fast-table.ts
  frontend/src/app/components/wp-fast-table/wp-table-base.ts
  frontend/src/app/components/wp-fast-table/wp-table-filters.ts
  frontend/src/app/components/wp-fast-table/wp-table-group-by.ts
  frontend/src/app/components/wp-fast-table/wp-table-hierarchies.ts
  frontend/src/app/components/wp-fast-table/wp-table-highlight.ts
  frontend/src/app/components/wp-fast-table/wp-table-pagination.ts
  frontend/src/app/components/wp-fast-table/wp-table-relation-columns.ts
  frontend/src/app/components/wp-fast-table/wp-table-sort-by.ts
  frontend/src/app/components/wp-fast-table/wp-table-sum.ts
  frontend/src/app/components/wp-fast-table/wp-table-timeline.ts
  frontend/src/app/components/wp-fast-table/wp-table.interfaces.ts
  frontend/src/app/components/wp-list/wp-states-initialization.service.ts
  frontend/src/app/components/wp-table/configuration-modal/tabs/display-settings-tab.component.ts
  frontend/src/app/components/wp-table/configuration-modal/tabs/filters-tab.component.ts
  frontend/src/app/components/wp-table/configuration-modal/tabs/highlighting-tab.component.ts
  frontend/src/app/components/wp-table/configuration-modal/tabs/sort-by-tab.component.ts
  frontend/src/app/components/wp-table/configuration-modal/wp-table-configuration-relation-selector.ts
  frontend/src/app/components/wp-table/embedded/wp-embedded-table.component.ts
  frontend/src/app/components/wp-table/sort-header/sort-header.directive.ts
  frontend/src/app/components/wp-table/timeline/container/wp-timeline-container.directive.ts
  frontend/src/app/components/wp-table/timeline/global-elements/wp-timeline-relations.directive.ts
  frontend/src/app/components/wp-table/wp-table-sums-row/wp-table-sums-row.directive.ts
  frontend/src/app/components/wp-table/wp-table.directive.html
  frontend/src/app/components/wp-table/wp-table.directive.ts
  frontend/src/app/modules/attachments/attachment-list/attachment-list-item.component.ts
  frontend/src/app/modules/attachments/attachments.component.ts
  frontend/src/app/modules/calendar/wp-calendar/wp-calendar.component.ts
  frontend/src/app/modules/global_search/global-search-work-packages.component.ts
  frontend/src/app/modules/work_packages/query-space/isolated-query-space.ts
  frontend/src/app/modules/work_packages/routing/wp-view-base/work-packages-view.base.ts
Labels: bugfix, housekeeping

#7087 [29616] No 'Cancel' Button for news or forum comments
  app/views/boards/edit.html.erb
  app/views/boards/new.html.erb
  app/views/messages/edit.html.erb
  app/views/messages/new.html.erb
  app/views/messages/show.html.erb
  app/views/news/edit.html.erb
  app/views/news/new.html.erb
  app/views/news/show.html.erb
Labels: bugfix

#7095 [29611] Remove members group sort by
  app/cells/members/table_cell.rb
  app/cells/table_cell.rb
  app/cells/views/table/show.erb
  app/views/members/index.html.erb
  spec/features/members/membership_spec.rb
  spec/support/pages/members.rb
Labels: bugfix

#7097 [29622] Implement start_tls for ldap_auth_source
  app/models/ldap_auth_source.rb
  app/models/permitted_params.rb
  app/views/ldap_auth_sources/_form.html.erb
  config/locales/en.yml
  db/migrate/20190227163226_add_tls_mode_to_auth_sources.rb
  lib/open_project/static/links.rb
  lib/tasks/ldap.rake
Labels: feature

#7094 [29625] Forum page shows boards submenu
  app/controllers/boards_controller.rb
  modules/boards/app/controllers/boards/boards_controller.rb
Labels: bugfix, styling

#7098 [25471] Draw empty due date until today in timeline
  frontend/src/app/components/wp-table/timeline/cells/timeline-cell-renderer.ts
Labels: feature

#7100 [29635] Add missing parameters for incoming-mails IMAP
  docker/cron
Labels: bugfix

#7101 Fix client credentials user
  app/views/oauth/applications/_form.html.erb
  frontend/src/app/modules/common/autocomplete/user-autocompleter.component.ts
Labels: bugfix

#7096 [28891] Required fields implementation adapted to LSG
  app/assets/stylesheets/content/_forms.lsg
  app/assets/stylesheets/content/_forms.sass
  app/views/account/_password_login_form.html.erb
  app/views/account/_register.html.erb
  app/views/account/_user_consent_check.html.erb
  app/views/boards/_form.html.erb
  app/views/colors/_form.html.erb
  app/views/custom_actions/_form.html.erb
  app/views/enumerations/_form.html.erb
  app/views/groups/_form.html.erb
  app/views/ldap_auth_sources/_form.html.erb
  app/views/messages/_form.html.erb
  app/views/my/_password_form_fields.html.erb
  app/views/my/account.html.erb
  app/views/news/_form.html.erb
  app/views/oauth/applications/_form.html.erb
  app/views/roles/_form.html.erb
  app/views/statuses/_form.html.erb
  app/views/types/form/_settings.html.erb
  app/views/users/_form.html.erb
  app/views/users/_simple_form.html.erb
  app/views/versions/_form.html.erb
  app/views/workflows/copy.html.erb
  lib/custom_field_form_builder.rb
  lib/tabular_form_builder.rb
  modules/backlogs/app/views/versions/_form.html.erb
  modules/costs/app/views/cost_objects/_form.html.erb
  modules/costs/app/views/cost_types/edit.html.erb
  modules/costs/app/views/costlog/edit.html.erb
  modules/documents/app/views/documents/_form.html.erb
  modules/global_roles/app/views/roles/_form.html.erb
  modules/global_roles/app/views/roles/_member_form.html.erb
  modules/ldap_groups/app/views/ldap_groups/synchronized_groups/index.html.erb
  modules/ldap_groups/app/views/ldap_groups/synchronized_groups/new.html.erb
  modules/meeting/app/views/meetings/_form.html.erb
  modules/pdf_export/app/views/export_card_configurations/_form.html.erb
  modules/pdf_export/app/views/export_card_configurations/_rows_format_help.html.erb
  modules/reporting_engine/lib/widget/controls/save_as.rb
  modules/two_factor_authentication/app/views/two_factor_authentication/authentication/enter_backup_code.html.erb
  modules/two_factor_authentication/app/views/two_factor_authentication/two_factor_devices/confirm.html.erb
  modules/two_factor_authentication/app/views/two_factor_authentication/two_factor_devices/sms/_form.html.erb
  modules/two_factor_authentication/app/views/two_factor_authentication/two_factor_devices/totp/_form.html.erb
  modules/webhooks/app/views/webhooks/outgoing/admin/_form.html.erb
  spec/features/auth/login_spec.rb
  spec/features/users/brute_force_spec.rb
  spec/lib/tabular_form_builder_spec.rb
  spec/support/authentication_helpers.rb
Labels: housekeeping, styling
