Repository opf/openproject, pull requests merged in 2019-06, with the labels that each got.

#7345 [29487] Apply filter criteria to embedded table inline reference
  frontend/src/app/components/wp-query/url-params-helper.ts
  frontend/src/app/components/wp-relations/embedded/inline/add-existing/wp-relation-inline-add-existing.component.html
  frontend/src/app/components/wp-relations/embedded/inline/add-existing/wp-relation-inline-add-existing.component.ts
  frontend/src/app/components/wp-relations/wp-relations-create/wp-relations-autocomplete/wp-relations-autocomplete.component.ts
  lib/api/v3/work_packages/available_relation_candidates_api.rb
  lib/api/v3/work_packages/available_relation_candidates_helper.rb
  spec/features/types/form_configuration_query_spec.rb
  spec/support/components/work_packages/relations.rb
  spec/support/pages/work_packages/embedded_work_packages_table.rb
Labels: feature, needs-review

#7330 [29509] Hide query groups when project filter is reduced to zero
  app/services/api/v3/update_query_from_v3_params_service.rb
  app/services/api/v3/work_package_collection_from_query_service.rb
  app/services/update_query_from_params_service.rb
  frontend/src/app/components/work-packages/wp-single-view/wp-single-view.component.ts
  frontend/src/app/components/work-packages/wp-single-view/wp-single-view.html
  frontend/src/app/components/wp-query/url-params-helper.ts
  frontend/src/app/components/wp-relations/embedded/children/wp-children-query.component.ts
  frontend/src/app/components/wp-relations/embedded/relations/wp-relation-query.component.ts
  frontend/src/app/components/wp-relations/embedded/wp-relation-query.base.ts
  frontend/src/app/components/wp-relations/embedded/wp-relation-query.html
  frontend/src/app/components/wp-table/embedded/wp-embedded-table.component.ts
  lib/api/v3/queries/helpers/query_representer_response.rb
  lib/api/v3/queries/queries_api.rb
  spec/features/work_packages/details/query_groups/relation_query_group_spec.rb
  spec/services/api/v3/update_query_from_v3_params_service_spec.rb
  spec/services/api/v3/work_package_collection_from_query_service_spec.rb
Labels: feature, needs-review

#7347 [Boards ] Fine tuning of version board header
  frontend/src/app/components/wp-card-view/wp-card-view.component.sass
  frontend/src/app/modules/boards/board/board-actions/board-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/status/status-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/version/version-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/version/version-board-header.html
  frontend/src/app/modules/boards/board/board-actions/version/version-board-header.sass
  frontend/src/app/modules/boards/board/board-list/board-list.component.html
  frontend/src/app/modules/boards/board/board-list/board-list.component.sass
  frontend/src/app/modules/boards/board/board-list/board-list.component.ts
  frontend/src/app/modules/common/path-helper/path-helper.service.ts
  modules/boards/config/locales/js-en.yml
Labels: needs-review, styling

#7354 [30284] Reload table after removing filter
  frontend/src/app/components/filters/query-filters/query-filters.component.ts
Labels: bugfix

#7349 [30278] Enable automatic scrolling in lists again
  app/assets/stylesheets/openproject/_mixins.sass
  frontend/src/app/components/wp-card-view/wp-card-view.component.sass
  frontend/src/app/modules/boards/board/board-list/board-list.component.sass
Labels: bugfix

#7353 [30279] No error when version cannot be inline-created
  frontend/src/app/modules/common/autocomplete/create-autocompleter.component.ts
  frontend/src/app/modules/common/autocomplete/version-autocompleter.component.ts
Labels: bugfix

#7351 Create option of version autocompleter is not readable in WP table
  app/assets/stylesheets/content/work_packages/_table_content.sass
  config/locales/js-en.yml
  frontend/src/app/components/wp-edit-form/table-row-edit-context.ts
  frontend/src/app/modules/common/autocomplete/create-autocompleter.component.ts
  modules/boards/spec/features/support/board_page.rb
  spec/features/work_packages/details/inplace_editor/version_editor_spec.rb
  spec/support/work_packages/work_package_field.rb
Labels: bugfix, styling

#7352 [30281] Put the focus on newly added filters
  frontend/src/app/components/filters/filter-boolean-value/filter-boolean-value.component.html
  frontend/src/app/components/filters/filter-boolean-value/filter-boolean-value.component.ts
  frontend/src/app/components/filters/filter-date-time-value/filter-date-time-value.component.html
  frontend/src/app/components/filters/filter-date-time-value/filter-date-time-value.component.ts
  frontend/src/app/components/filters/filter-date-times-value/filter-date-times-value.component.html
  frontend/src/app/components/filters/filter-date-times-value/filter-date-times-value.component.ts
  frontend/src/app/components/filters/filter-date-value/filter-date-value.component.html
  frontend/src/app/components/filters/filter-date-value/filter-date-value.component.ts
  frontend/src/app/components/filters/filter-dates-value/filter-dates-value.component.html
  frontend/src/app/components/filters/filter-dates-value/filter-dates-value.component.ts
  frontend/src/app/components/filters/filter-integer-value/filter-integer-value.component.html
  frontend/src/app/components/filters/filter-integer-value/filter-integer-value.component.ts
  frontend/src/app/components/filters/filter-string-value/filter-string-value.component.html
  frontend/src/app/components/filters/filter-string-value/filter-string-value.component.ts
  frontend/src/app/components/filters/filter-toggled-multiselect-value/filter-toggled-multiselect-value.component.ts
  frontend/src/app/components/filters/query-filter/query-filter.component.html
  frontend/src/app/components/filters/query-filter/query-filter.component.ts
  frontend/src/app/components/filters/query-filters/query-filters.component.html
Labels: feature

#7356 handle missing agenda
  modules/meeting/app/models/meeting.rb
Labels: bugfix

#7357 Styled scrollbars for Gantt and embedded tables
  app/assets/stylesheets/content/_modal.sass
  app/assets/stylesheets/content/menus/_project_autocompletion.sass
  app/assets/stylesheets/layout/_main_menu.sass
  app/assets/stylesheets/layout/_top_menu.sass
  app/assets/stylesheets/layout/work_packages/_query_menu.sass
  app/assets/stylesheets/layout/work_packages/_table.sass
  app/assets/stylesheets/layout/work_packages/_table_embedded.sass
  app/assets/stylesheets/openproject/_mixins.sass
  frontend/src/app/components/wp-card-view/wp-card-view.component.sass
Labels: styling

#7361 [30293] User avatar is cut off in WP table (MS Edge)
  app/assets/stylesheets/content/work_packages/_table_content.sass
  app/assets/stylesheets/content/work_packages/_table_hierarchy.sass
Labels: bugfix, needs-review, styling

#7360 [30288] Styling and wording issues in autocompleter below embedded tables
  app/assets/stylesheets/content/work_packages/tabs/_relations.sass
  config/locales/js-en.yml
  frontend/src/app/components/wp-relations/embedded/inline/add-existing/wp-relation-inline-add-existing.component.html
  frontend/src/app/components/wp-relations/wp-relations-create/wp-relations-autocomplete/wp-relations-autocomplete.component.ts
  spec/features/work_packages/new/work_package_default_description_spec.rb
  spec/support/components/work_packages/relations.rb
Labels: bugfix

#7364 [30296] Fix invalid reference to ViewChild
  frontend/src/app/components/wp-relations/embedded/children/wp-children-query.component.ts
Labels: bugfix

#7365 Fix broken npm test
  frontend/src/app/components/api/op-file-upload/op-file-upload.service.spec.ts
Labels: bugfix, needs-review

#7366 [30005] Use schema and create form to check version writability
  frontend/src/app/angular4-modules.ts
  frontend/src/app/components/forms/forms-cache.service.ts
  frontend/src/app/components/wp-card-view/wp-card-view.component.html
  frontend/src/app/components/wp-card-view/wp-card-view.component.ts
  frontend/src/app/components/wp-edit-form/work-package-changeset.ts
  frontend/src/app/modules/boards/board/board-actions/board-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/status/status-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/version/version-action.service.ts
  frontend/src/app/modules/boards/board/board-list/board-list.component.html
  frontend/src/app/modules/boards/board/board-list/board-list.component.ts
  modules/boards/config/locales/js-en.yml
  modules/boards/spec/features/action_boards/version_board_spec.rb
  modules/boards/spec/features/support/board_page.rb
Labels: bugfix, needs-review

#7362 Feature/csv export on time entry index only
  Gemfile
  Gemfile.lock
  app/controllers/projects_controller.rb
  app/controllers/timelog_controller.rb
  app/helpers/projects_helper.rb
  app/views/projects/level_list.api.rabl
  app/views/timelog/_list.html.erb
  app/views/timelog/index.html.erb
  app/views/timelog/index.rabl
  app/views/timelog/show.rabl
  app/views/users/show.rabl
  config/initializers/rabl_hack.rb
  config/initializers/rabl_init.rb
  config/initializers/respond_to_api.rb
  config/locales/en.yml
  config/routes.rb
  spec/features/time_entry/root_time_entries_spec.rb
  spec/features/time_entry/time_entry_report_spec.rb
  spec/helpers/projects_helper_spec.rb
  spec/views/projects/level_list_api_json_spec.rb
  spec_legacy/functional/timelog_controller_spec.rb
Labels: housekeeping

#7368 [30298] Remove type row highlighting
  frontend/src/app/components/wp-table/configuration-modal/tabs/highlighting-tab.component.html
Labels: bugfix

#7369 Apply styled scrollbars for the WP views
  app/assets/stylesheets/layout/work_packages/_details_view.sass
  app/assets/stylesheets/layout/work_packages/_full_view.sass
Labels: styling

#7371 [30309] Fix saving duplicate enabled modules and rendering wrong errors
  app/models/project/copy.rb
  app/views/project_mailer/copy_project_succeeded.html.erb
  app/views/project_mailer/copy_project_succeeded.text.erb
  app/workers/copy_project_job.rb
  config/locales/en.yml
  spec/models/copy_project_job_spec.rb
Labels: bugfix

#7372 [30343] Handle missing menu item on my page
  frontend/src/app/modules/router/openproject.routes.ts
  spec/features/work_packages/navigation_spec.rb
Labels: bugfix

#7375 [30291] Doubled files section in meeting agenda
  modules/meeting/app/assets/javascripts/meeting/meeting.js
Labels: bugfix

#7373 [30305] Improve print view of cost report via CSS
  modules/reporting/app/assets/stylesheets/reporting/_reporting.sass
  modules/reporting/app/assets/stylesheets/reporting/_reporting_group_by.sass
  modules/reporting/app/assets/stylesheets/reporting/_reporting_table.sass
  modules/reporting/app/assets/stylesheets/reporting/_reporting_table_print.sass
  modules/reporting/app/assets/stylesheets/reporting/reporting.sass
  modules/reporting/app/assets/stylesheets/reporting/reporting_styles.sass
  modules/reporting/app/views/cost_reports/_reporting_header.html.erb
  modules/reporting/lib/open_project/reporting/engine.rb
  modules/reporting_engine/lib/assets/stylesheets/reporting_engine/reporting.css.erb
  modules/reporting_engine/lib/assets/stylesheets/reporting_engine/reporting_engine.css
  modules/reporting_engine/lib/reporting_engine/engine.rb
  modules/reporting_engine/lib/widget/filters.rb
  modules/reporting_engine/lib/widget/settings.rb
Labels: needs-review, styling

#7344 Bump angular to 8.0.0
  docs/development/development-environment-osx.md
  docs/development/development-environment-ubuntu.md
  frontend/npm-shrinkwrap.json
  frontend/package.json
  frontend/src/app/ckeditor/ckeditor-augmented-textarea.component.ts
  frontend/src/app/components/filters/filter-toggled-multiselect-value/filter-toggled-multiselect-value.component.ts
  frontend/src/app/components/filters/query-filters/query-filters.component.ts
  frontend/src/app/components/modals/editor/macro-child-pages-modal/child-pages-macro.modal.ts
  frontend/src/app/components/modals/editor/macro-code-block-modal/code-block-macro.modal.ts
  frontend/src/app/components/modals/editor/macro-wiki-include-page-modal/wiki-include-page-macro.modal.ts
  frontend/src/app/components/modals/editor/macro-wp-button-modal/wp-button-macro.modal.ts
  frontend/src/app/components/modals/request-for-confirmation/password-confirmation.modal.ts
  frontend/src/app/components/modals/save-modal/save-query.modal.ts
  frontend/src/app/components/user/user-link/user-link.component.spec.ts
  frontend/src/app/components/work-packages/work-package-comment/work-package-comment.component.ts
  frontend/src/app/components/wp-by-version-graph/wp-by-version-graph.component.ts
  frontend/src/app/components/wp-card-view/wp-card-view.component.ts
  frontend/src/app/components/wp-edit/wp-edit-field/wp-edit-field.component.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-filters.service.ts
  frontend/src/app/components/wp-query-select/wp-query-select-dropdown.component.ts
  frontend/src/app/components/wp-relations/embedded/children/wp-children-query.component.ts
  frontend/src/app/components/wp-relations/embedded/wp-relation-query.base.ts
  frontend/src/app/components/wp-relations/wp-relation-row/wp-relation-row.component.ts
  frontend/src/app/components/wp-relations/wp-relations-create/wp-relations-autocomplete/wp-relations-autocomplete.component.ts
  frontend/src/app/components/wp-relations/wp-relations-create/wp-relations-create.component.ts
  frontend/src/app/components/wp-relations/wp-relations-group/wp-relations-group.component.ts
  frontend/src/app/components/wp-table/configuration-modal/tabs/columns-tab.component.ts
  frontend/src/app/components/wp-table/configuration-modal/wp-table-configuration.modal.ts
  frontend/src/app/components/wp-table/external-configuration/external-query-configuration.component.ts
  frontend/src/app/helpers/selection-helpers.ts
  frontend/src/app/modules/a11y/accessible-by-keyboard.component.spec.ts
  frontend/src/app/modules/a11y/accessible-click.directive.spec.ts
  frontend/src/app/modules/a11y/double-click-or-tap.directive.ts
  frontend/src/app/modules/attachments/attachments-upload/attachments-upload.component.ts
  frontend/src/app/modules/boards/board/board-list/board-list.component.ts
  frontend/src/app/modules/boards/board/board.component.ts
  frontend/src/app/modules/boards/board/configuration-modal/board-configuration.modal.ts
  frontend/src/app/modules/boards/board/inline-add/board-inline-add-autocompleter.component.ts
  frontend/src/app/modules/boards/new-board-modal/new-board-modal.component.ts
  frontend/src/app/modules/calendar/wp-calendar-entry/wp-calendar-entry.component.ts
  frontend/src/app/modules/calendar/wp-calendar/wp-calendar.component.ts
  frontend/src/app/modules/common/autocomplete/create-autocompleter.component.ts
  frontend/src/app/modules/common/autocomplete/user-autocompleter.component.ts
  frontend/src/app/modules/common/autocomplete/version-autocompleter.component.ts
  frontend/src/app/modules/common/ckeditor/op-ckeditor.component.ts
  frontend/src/app/modules/common/collapsible-section/collapsible-section.component.ts
  frontend/src/app/modules/common/editable-toolbar-title/editable-toolbar-title.component.ts
  frontend/src/app/modules/common/icon/op-icon.spec.ts
  frontend/src/app/modules/common/notifications/upload-progress.component.ts
  frontend/src/app/modules/common/tabs/scrollable-tabs.component.ts
  frontend/src/app/modules/fields/edit/field-types/formattable-edit-field.component.ts
  frontend/src/app/modules/fields/edit/field-types/multi-select-edit-field.component.ts
  frontend/src/app/modules/global_search/global-search-input.component.ts
  frontend/src/app/modules/grids/widgets/wp-table/wp-table.component.ts
  frontend/src/polyfills.ts
  frontend/src/tsconfig.app.json
  frontend/src/tsconfig.spec.json
  frontend/tsconfig.json
  modules/avatars/frontend/module/avatar-upload-form/avatar-upload-form.component.ts
  package.json
Labels: housekeeping

#7387 [30348] Switching between manual and forced sorting in the sort by tab
  app/assets/stylesheets/content/_table.sass
  config/locales/js-en.yml
  frontend/src/app/components/wp-table/configuration-modal/tabs/sort-by-tab.component.html
  frontend/src/app/components/wp-table/configuration-modal/tabs/sort-by-tab.component.ts
  frontend/src/app/components/wp-table/wp-table.directive.html
  frontend/src/app/components/wp-table/wp-table.directive.ts
Labels: feature, work in progress

#7391 [30372] Vendor foundation to ensure angular assets must not be present
  .travis.yml
  app/assets/stylesheets/vendor/foundation-apps/LICENSE
  app/assets/stylesheets/vendor/foundation-apps/scss/_global.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/_settings.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/components/_accordion.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/components/_action-sheet.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/components/_block-list.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/components/_button-group.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/components/_button.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/components/_card.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/components/_extras.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/components/_forms.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/components/_grid.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/components/_label.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/components/_list.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/components/_menu-bar.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/components/_modal.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/components/_motion.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/components/_notification.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/components/_off-canvas.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/components/_panel.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/components/_popup.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/components/_switch.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/components/_tabs.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/components/_title-bar.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/components/_typography.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/components/_utilities.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/foundation.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/helpers/_breakpoints.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/helpers/_functions.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/helpers/_images.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/helpers/_mixins.scss
  app/assets/stylesheets/vendor/foundation-apps/scss/vendor/_normalize.scss
  config/initializers/sass.rb
  frontend/npm-shrinkwrap.json
  frontend/package.json
Labels: bugfix

#7392 [30370] Fix not allowed scope for relative URL root
  lib/open_project/static_routing.rb
  modules/boards/lib/open_project/boards/grid_registration.rb
  modules/boards/spec/lib/open_project/boards/grid_registration_spec.rb
  spec/lib/open_project/static_routing_spec.rb
Labels: bugfix

#7395 [DnD] Redraw the gantt chart after manual sort
  frontend/src/app/components/wp-fast-table/handlers/state/drag-and-drop-transformer.ts
  spec/features/work_packages/sorting/manual_sorting_spec.rb
  spec/support/pages/work_packages/work_packages_timeline.rb
Labels: needs-review

#7396 Create table drag action service for hierarchies, grouping
  frontend/src/app/components/filters/query-filters/query-filters.component.ts
  frontend/src/app/components/wp-card-view/wp-card-view.component.ts
  frontend/src/app/components/wp-fast-table/builders/drag-and-drop/drag-drop-handle-builder.ts
  frontend/src/app/components/wp-fast-table/builders/modes/hierarchy/hierarchy-render-pass.ts
  frontend/src/app/components/wp-fast-table/builders/modes/hierarchy/single-hierarchy-row-builder.ts
  frontend/src/app/components/wp-fast-table/builders/rows/single-row-builder.ts
  frontend/src/app/components/wp-fast-table/handlers/state/drag-and-drop-transformer.ts
  frontend/src/app/components/wp-fast-table/helpers/wp-table-row-helpers.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-sort-by.service.ts
  frontend/src/app/components/wp-list/wp-list.service.ts
  frontend/src/app/components/wp-table/drag-and-drop/actions/group-by-drag-action.service.ts
  frontend/src/app/components/wp-table/drag-and-drop/actions/hierarchy-drag-action.service.ts
  frontend/src/app/components/wp-table/drag-and-drop/actions/table-drag-action.service.ts
  frontend/src/app/components/wp-table/drag-and-drop/actions/table-drag-actions-registry.service.ts
  frontend/src/app/components/wp-table/embedded/wp-embedded-base.component.ts
  frontend/src/app/components/wp-table/embedded/wp-embedded-table.component.ts
  frontend/src/app/modules/boards/board/board.component.ts
  frontend/src/app/modules/common/drag-and-drop/drag-and-drop.helpers.ts
  frontend/src/app/modules/common/drag-and-drop/drag-and-drop.service.ts
  frontend/src/app/modules/common/drag-and-drop/reorder-query.service.ts
  frontend/src/app/modules/grids/widgets/wp-table/wp-table.component.html
  frontend/src/app/modules/grids/widgets/wp-table/wp-table.component.ts
  frontend/src/app/modules/hal/dm-services/query-dm.service.ts
  frontend/src/app/modules/hal/resources/work-package-resource.ts
  frontend/src/app/modules/work_packages/query-space/wp-isolated-query-space.directive.ts
  frontend/src/app/modules/work_packages/routing/wp-list/wp-list.component.ts
  modules/backlogs/features/step_definitions/_then_steps.rb
  spec/features/work_packages/sorting/manual_sorting_spec.rb
  spec/support/pages/work_packages/abstract_work_package.rb
Labels: feature

#7400 [30395] Sorting mode is not correctly displayed in the modal
  frontend/src/app/components/op-context-menu/handlers/op-columns-context-menu.directive.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-sort-by.service.ts
Labels: bugfix, needs-review

#7409 [30373] Work package description not updated after initial edit
  modules/costs/frontend/module/wp-display/wp-display-costs-by-type-field.module.ts
Labels: bugfix, needs-review

#7415 [30415] Fix missing project reference in journal
  app/models/journal/aggregated_journal.rb
  lib/open_project/text_formatting/matchers/link_handlers/revisions.rb
  spec/features/work_packages/tabs/activity_revisions_spec.rb
  spec/models/journal/aggregated_journal_spec.rb
Labels: bugfix

#7417 [30432] <p> tag shown on My page for time tracking comments
  frontend/src/app/modules/grids/widgets/time-entries-current-user/time-entries-current-user.component.ts
Labels: bugfix

#7418 [30426] User with :manage_boards but without :manage_public_queries can create faulty board columns
  frontend/src/app/modules/boards/board/board-list/board-lists.service.ts
  frontend/src/app/modules/boards/board/board.ts
  modules/boards/config/locales/js-en.yml
Labels: bugfix, needs-review

#7416 [30421] Disable drag and drop for relational sub rows
  frontend/src/app/components/wp-fast-table/builders/drag-and-drop/drag-drop-handle-builder.ts
  frontend/src/app/components/wp-fast-table/builders/drag-and-drop/drag-drop-handle-render-pass.ts
  frontend/src/app/components/wp-fast-table/builders/primary-render-pass.ts
  frontend/src/app/components/wp-fast-table/builders/rows/single-row-builder.ts
Labels: needs-review

#7420 Cleanup structure of global search module
  app/assets/stylesheets/content/_search.sass
  app/assets/stylesheets/content/work_packages/_table_hierarchy.sass
  app/assets/stylesheets/content/work_packages/_table_relations.sass
  app/assets/stylesheets/content/work_packages/single_view/_single_view.sass
  app/assets/stylesheets/layout/_top_menu.sass
  app/assets/stylesheets/layout/_top_menu_mobile.sass
  frontend/src/app/modules/global_search/global-search-work-packages.component.ts
  frontend/src/app/modules/global_search/input/global-search-input-mobile.component.sass
  frontend/src/app/modules/global_search/input/global-search-input.component.html
  frontend/src/app/modules/global_search/input/global-search-input.component.sass
  frontend/src/app/modules/global_search/input/global-search-input.component.ts
  frontend/src/app/modules/global_search/openproject-global-search.module.ts
  frontend/src/app/modules/global_search/services/global-search.service.spec.ts
  frontend/src/app/modules/global_search/services/global-search.service.ts
  frontend/src/app/modules/global_search/tabs/global-search-tabs.component.ts
  frontend/src/app/modules/global_search/title/global-search-title.component.html
  frontend/src/app/modules/global_search/title/global-search-title.component.ts
Labels: housekeeping

#7419 [30436] OmniAuth login link in top menu not styled properly
  app/assets/stylesheets/layout/_top_menu.sass
  lib/redmine/menu_manager/top_menu_helper.rb
Labels: bugfix, styling

#7431 [30411] Check spelling of "email"
  config/locales/en.yml
  docs/api/apiv3/endpoints/users.apib
  modules/bcf/app/views/bcf/issues/configure_invalid_people.html.erb
  modules/bcf/app/views/bcf/issues/configure_unknown_mails.html.erb
  modules/bcf/app/views/bcf/issues/diff_on_work_packages.html.erb
  modules/bcf/lib/open_project/bcf/bcf_xml/importer.rb
Labels: bugfix

#7428 Add version tag to highlighting css
  app/controllers/highlighting_controller.rb
  app/helpers/highlighting_helper.rb
  app/models/application_record.rb
  app/views/layouts/base.html.erb
  config/brakeman.ignore
  config/routes.rb
  frontend/src/app/components/work-packages/wp-single-view/wp-single-view.component.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-highlighting.service.ts
  frontend/src/app/components/wp-table/timeline/container/wp-timeline-container.directive.ts
  frontend/src/app/modules/boards/board/board.component.ts
  frontend/src/app/modules/common/colors/colors-autocompleter.component.ts
  frontend/src/app/modules/common/dynamic-css/dynamic-css.service.ts
  frontend/src/app/modules/common/openproject-common.module.ts
  frontend/src/app/modules/global_search/input/global-search-input.component.ts
  spec/models/application_record_spec.rb
Labels: performance

#7433 [30444] Board list not sorted alphabetically
  frontend/src/app/modules/boards/boards-sidebar/boards-menu.component.ts
Labels: bugfix, needs-review
