Repository opf/openproject, pull requests merged in 2019-01, with the labels that each got.

#6966 [29328] Text content overlaps table header in FF
  app/assets/stylesheets/content/_table.sass
Labels: bugfix, styling

#6965 [29292] Few errors in German onboading tour
  app/assets/javascripts/onboarding/backlogs_tour.js
  app/assets/javascripts/onboarding/homescreen_tour.js
  app/assets/javascripts/onboarding/work_package_tour.js
  config/locales/js-en.yml
Labels: bugfix

#6967 [28839] Long heading in forum overlaps buttons
  app/assets/stylesheets/content/_legacy_actions.sass
  app/views/messages/show.html.erb
Labels: bugfix, styling

#6968 [29335] Remove legacy action menus
  app/assets/javascripts/action_menu.js
  app/assets/stylesheets/content/_forum.sass
  app/assets/stylesheets/content/_index.sass
  app/views/layouts/_action_menu.html.erb
  app/views/layouts/_action_menu_base.html.erb
  app/views/layouts/_action_menu_specific.html.erb
  app/views/layouts/base.html.erb
  app/views/project_settings/_action_menu.html.erb
  app/views/roles/index.html.erb
  app/views/wiki/date_index.html.erb
  app/views/workflows/_toolbar.html.erb
  app/views/workflows/copy.html.erb
  app/views/workflows/edit.html.erb
  app/views/workflows/index.html.erb
Labels: housekeeping, needs-review

#6955 [29191] Fix wp attributes truncation
  app/assets/stylesheets/content/_attributes_key_value.sass
  frontend/src/app/components/work-packages/wp-single-view/wp-single-view.html
  frontend/src/app/components/wp-form-group/wp-attribute-group.template.html
Labels: bugfix, styling, work in progress

#6970 [29347] Styling bugs in pop-up modals
  app/assets/stylesheets/content/_modal.sass
  app/assets/stylesheets/openproject/_onboarding.sass
  app/views/onboarding/_onboarding_video_modal.html.erb
Labels: bugfix, styling

#6960 Quickly filter by text within normal filters section without showing any operator
  app/assets/stylesheets/content/_advanced_filters.sass
  config/locales/js-en.yml
  frontend/src/app/components/filters/query-filters/query-filters.component.html
  frontend/src/app/components/filters/query-filters/query-filters.component.ts
  frontend/src/app/components/filters/quick-filter-by-text-input/quick-filter-by-text-input.component.ts
  frontend/src/app/components/filters/quick-filter-by-text-input/quick-filter-by-text-input.html
  frontend/src/app/components/wp-buttons/wp-filter-button/wp-filter-button.component.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-filters.service.ts
  frontend/src/app/components/wp-fast-table/wp-table-filters.ts
  frontend/src/app/modules/hal/resources/query-filter-instance-resource.ts
  frontend/src/app/modules/work_packages/openproject-work-packages.module.ts
  modules/my_project_page/spec/features/block_editing_spec.rb
  spec/features/types/form_configuration_query_spec.rb
  spec/features/work_packages/table/configuration_modal/filter_spec.rb
  spec/features/wysiwyg/macros/embedded_tables_spec.rb
Labels: needs-review

#6975 [29171] Fix position of mobile notifications
  app/assets/stylesheets/content/_notifications_mobile.sass
Labels: bugfix, needs-review, styling

#6983 Redirect to correct controller
  app/controllers/application_controller.rb
Labels: bugfix

#6972 [29353] Unescape DATABASE_URL password before backup
  packaging/scripts/backup
Labels: bugfix

#6954 [29239] Wp table header sticky for all browsers
  app/assets/stylesheets/content/_table.sass
  app/assets/stylesheets/content/work_packages/timelines/_timelines_header.sass
  frontend/src/app/globals/browser-specific-flags.ts
Labels: bugfix, needs-review, styling

#6996 Add dependencies required by the plaintext gem
  .pkgr.yml
Labels: packager

#7000 [29409] Bugfix disarranged time sheet filters
  app/assets/stylesheets/content/_advanced_filters.sass
  app/assets/stylesheets/content/_simple_filters.sass
  app/views/timelog/_date_range.html.erb
Labels: bugfix, styling, work in progress

#6988 [29257] Auto completion for work package attributes
  app/assets/stylesheets/content/_attributes_group.sass
  app/assets/stylesheets/content/_attributes_key_value.sass
  app/assets/stylesheets/content/_autocomplete.sass
  app/assets/stylesheets/content/work_packages/inplace_editing/_display_fields.sass
  app/assets/stylesheets/content/work_packages/inplace_editing/_textareas.sass
  app/assets/stylesheets/content/work_packages/new/_type_status_row.sass
  app/assets/stylesheets/content/work_packages/single_view/_single_view.sass
  app/assets/stylesheets/layout/work_packages/_details_view.sass
  app/assets/stylesheets/layout/work_packages/_full_view.sass
  app/assets/stylesheets/openproject/_mixins.sass
  app/views/layouts/base.html.erb
  config/locales/js-en.yml
  frontend/npm-shrinkwrap.json
  frontend/package.json
  frontend/src/app/components/work-packages/wp-single-view/wp-single-view.component.ts
  frontend/src/app/components/work-packages/wp-single-view/wp-single-view.html
  frontend/src/app/components/work-packages/wp-subject/wp-subject.component.ts
  frontend/src/app/components/work-packages/wp-subject/wp-subject.html
  frontend/src/app/components/wp-edit-form/work-package-edit-field-handler.ts
  frontend/src/app/components/wp-edit/wp-edit-field/wp-edit-field.component.ts
  frontend/src/app/components/wp-fast-table/handlers/cell/edit-cell-handler.ts
  frontend/src/app/components/wp-table/wp-table.directive.html
  frontend/src/app/components/wp-table/wp-table.directive.ts
  frontend/src/app/helpers/random-string.ts
  frontend/src/app/modules/common/openproject-common.module.ts
  frontend/src/app/modules/fields/edit/edit-field.component.ts
  frontend/src/app/modules/fields/edit/editing-portal/edit-field-handler.ts
  frontend/src/app/modules/fields/edit/editing-portal/wp-editing-portal-service.ts
  frontend/src/app/modules/fields/edit/field-types/multi-select-edit-field.component.html
  frontend/src/app/modules/fields/edit/field-types/multi-select-edit-field.component.ts
  frontend/src/app/modules/fields/edit/field-types/select-edit-field.component.html
  frontend/src/app/modules/fields/edit/field-types/select-edit-field.component.ts
  frontend/src/styles.css
  frontend/tsconfig.json
  modules/costs/spec/features/costs_edit_fields_spec.rb
  spec/features/custom_fields/multi_user_custom_field_spec.rb
  spec/features/custom_fields/multi_value_custom_field_spec.rb
  spec/features/my/assigned_to_me_embedded_table_spec.rb
  spec/features/work_packages/details/custom_fields/custom_field_spec.rb
  spec/features/work_packages/details/inplace_editor/version_editor_spec.rb
  spec/features/work_packages/new/attributes_from_filter_spec.rb
  spec/features/work_packages/new/new_work_package_spec.rb
  spec/features/work_packages/table/edit_work_packages_spec.rb
  spec/features/work_packages/table/inline_create/create_work_packages_spec.rb
  spec/features/work_packages/table/switch_types_spec.rb
  spec/support/work_packages/work_package_field.rb
  spec/support/work_packages/work_package_multi_select_field.rb
Labels: feature, needs-review

#7002 Improve error logging with lograge and log delegators
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/helpers/open_project_error_helper.rb
  config/initializers/lograge.rb
  lib/open_project.rb
  lib/open_project/logging/log_delegator.rb
Labels: feature, housekeeping

#7005 [29417] Missing translation in work package context menu
  frontend/src/app/components/op-context-menu/wp-context-menu/wp-single-context-menu.ts
Labels: bugfix

#7007 [29325] Remove accessibility mode
  app/assets/stylesheets/content/_notifications.sass
  app/assets/stylesheets/layout/_breadcrumb.sass
  app/assets/stylesheets/openproject/_accessibility.sass
  app/controllers/account_controller.rb
  app/helpers/application_helper.rb
  app/models/permitted_params.rb
  app/models/user.rb
  app/models/user_preference.rb
  app/views/account/consent.html.erb
  app/views/account/exit.html.erb
  app/views/account/login.html.erb
  app/views/account/lost_password.html.erb
  app/views/account/password_recovery.html.erb
  app/views/members/_member_form.html.erb
  app/views/members/_member_form_impaired.html.erb
  app/views/members/_member_form_non_impaired.html.erb
  app/views/repositories/show.html.erb
  app/views/settings/_display.html.erb
  app/views/settings/_users.html.erb
  app/views/users/_form.html.erb
  app/views/users/_impaired_settings.html.erb
  app/views/users/_preferences.html.erb
  config/initializers/assets.rb
  db/migrate/20190124081710_remove_accessibility_mode.rb
  docs/development/accessibility-checklist.md
  features/step_definitions/general_steps.rb
  features/step_definitions/project_member_steps.rb
  frontend/src/app/components/wp-activity/user/user-activity.component.ts
  frontend/src/app/components/wp-new/wp-new-split-view.html
  frontend/src/app/components/wp-table/configuration-modal/tabs/columns-tab.component.html
  frontend/src/app/components/wp-table/configuration-modal/tabs/columns-tab.component.ts
  frontend/src/app/components/wp-table/configuration-modal/wp-table-configuration-relation-selector.ts
  frontend/src/app/components/wp-table/configuration-modal/wp-table-configuration.modal.ts
  frontend/src/app/modules/common/config/configuration.service.ts
  frontend/src/app/modules/common/copy-to-clipboard/copy-to-clipboard.directive.ts
  frontend/src/app/modules/common/op-date-picker/op-date-picker.component.ts
  lib/api/v3/user_preferences/user_preferences_representer.rb
  lib/redmine/menu_manager/top_menu/projects_menu.rb
  modules/backlogs/lib/open_project/backlogs/engine.rb
  modules/reporting_engine/lib/assets/stylesheets/reporting_engine/reporting.css.erb
  modules/two_factor_authentication/app/views/two_factor_authentication/authentication/enter_backup_code.html.erb
  modules/two_factor_authentication/app/views/two_factor_authentication/authentication/request_otp.html.erb
  spec/features/members/error_messages_spec.rb
  spec/features/members/membership_spec.rb
  spec/features/work_packages/table/configuration_modal/column_spec.rb
  spec/lib/api/v3/user_preferences/user_preferences_representer_spec.rb
  spec/models/permitted_params_spec.rb
  spec/models/user_preference_spec.rb
  spec/models/user_spec.rb
  spec/support/components/work_packages/columns.rb
  spec/support/pages/members.rb
Labels: accessibility, housekeeping, needs-review

#7006 Style expandable search bar
  app/assets/stylesheets/layout/_top_menu.sass
  app/views/custom_styles/_inline_css.erb
  frontend/src/app/components/global-search/global-search-input.component.html
  frontend/src/app/components/global-search/global-search-input.component.ts
Labels: styling

#7003 Global search title component
  app/assets/stylesheets/layout/_top_menu.sass
  app/views/search/index.html.erb
  config/locales/js-en.yml
  frontend/src/app/angular4-modules.ts
  frontend/src/app/components/global-search/global-search-input.component.ts
  frontend/src/app/components/global-search/global-search-title.component.html
  frontend/src/app/components/global-search/global-search-title.component.ts
Labels: work in progress

#7009 Bump angular/core and angular/cli
  frontend/e2e/app.e2e-spec.ts
  frontend/e2e/app.po.ts
  frontend/e2e/tsconfig.e2e.json
  frontend/npm-shrinkwrap.json
  frontend/package.json
  frontend/src/app/components/wp-query-select/wp-query-select-dropdown.component.ts
Labels: housekeeping

#6984 [29275] LSG cleanup and update
  app/assets/stylesheets/content/_action_menu_main.lsg
  app/assets/stylesheets/content/_action_menu_main.sass
  app/assets/stylesheets/content/_attributes_group.lsg
  app/assets/stylesheets/content/_attributes_key_value.lsg
  app/assets/stylesheets/content/_attributes_table.lsg
  app/assets/stylesheets/content/_attributes_table.sass
  app/assets/stylesheets/content/_boxes.lsg
  app/assets/stylesheets/content/_boxes.sass
  app/assets/stylesheets/content/_choice.lsg
  app/assets/stylesheets/content/_choice.sass
  app/assets/stylesheets/content/_context_menu.lsg
  app/assets/stylesheets/content/_context_menu.sass
  app/assets/stylesheets/content/_contextual.sass
  app/assets/stylesheets/content/_control_colors.lsg
  app/assets/stylesheets/content/_control_colors.sass
  app/assets/stylesheets/content/_editable_toolbar.lsg
  app/assets/stylesheets/content/_expandable_group_content.lsg
  app/assets/stylesheets/content/_expandable_group_content.sass
  app/assets/stylesheets/content/_forms.lsg
  app/assets/stylesheets/content/_forms_mobile.sass
  app/assets/stylesheets/content/_grid_table.lsg
  app/assets/stylesheets/content/_grid_table.sass
  app/assets/stylesheets/content/_in_place_editing.lsg
  app/assets/stylesheets/content/_index.sass
  app/assets/stylesheets/content/_modal.lsg
  app/assets/stylesheets/content/_my_page.lsg
  app/assets/stylesheets/content/_news.lsg
  app/assets/stylesheets/content/_news.sass
  app/assets/stylesheets/content/_notifications.lsg
  app/assets/stylesheets/content/_simple_filters.lsg
  app/assets/stylesheets/content/_table.lsg
  app/assets/stylesheets/content/_user.lsg
  app/assets/stylesheets/content/_user.sass
  app/assets/stylesheets/content/_widget_box.lsg
  app/assets/stylesheets/content/work_packages/_table_content.lsg
  app/assets/stylesheets/content/work_packages/tabs/_activities.lsg
  app/assets/stylesheets/content/work_packages/tabs/_relations.lsg
  app/assets/stylesheets/content/work_packages/tabs/_relations.sass
  app/assets/stylesheets/layout/_drop_down.sass
  app/assets/stylesheets/openproject/_mixins.sass
  app/assets/stylesheets/styleguide.html.lsg
  lib/open_project/design.rb
Labels: housekeeping, needs-review

#7019 [29464] Apply correct structure for news section
  app/assets/stylesheets/content/_news.lsg
  app/assets/stylesheets/content/_news.sass
  app/views/news/index.html.erb
  app/views/news/show.html.erb
Labels: bugfix, styling

#7018 [29448] WP content does not close right side gap
  app/assets/stylesheets/layout/work_packages/_full_view.sass
  app/assets/stylesheets/layout/work_packages/_mobile.sass
  app/assets/stylesheets/layout/work_packages/_table.sass
Labels: bugfix, styling

#7022 Remove accessibility setting
  config/settings.yml
Labels: housekeeping
