Repository opf/openproject, pull requests merged in 2019-05, with the labels that each got.

#7267 [30135] Add work package id link to add modifiable clicks
  frontend/src/app/components/wp-card-view/wp-card-view.component.html
  frontend/src/app/components/wp-card-view/wp-card-view.component.sass
Labels: feature

#7273 [30150] Use inline highlighting mode for boards as default
  frontend/src/app/modules/boards/board/board.ts
Labels: bugfix

#7274 [30146] Remember relation columns expand state
  frontend/src/app/components/wp-fast-table/state/wp-table-relation-columns.service.ts
Labels: bugfix

#7272 [30147] Use file, not filename column for attachments order
  app/models/work_package.rb
Labels: bugfix

#7275 [30142][30058] Change wording of onboarding tour
  config/locales/js-en.yml
  modules/boards/spec/features/support/onboarding_steps.rb
  spec/features/onboarding/onboarding_tour_spec.rb
Labels: bugfix

#7276 [Boards] Avoid type select field to overlap closing icon of cards
  frontend/src/app/components/wp-card-view/wp-card-view.component.html
  frontend/src/app/components/wp-card-view/wp-card-view.component.sass
Labels: bugfix, styling

#7277 [30151] Perform attribute group validations when changed
  app/contracts/types/base_contract.rb
  app/models/type/attribute_groups.rb
  config/locales/en.yml
Labels: bugfix

#7281 [30175] Style scrollbars consistently where supported
  app/assets/stylesheets/openproject/_mixins.sass
  frontend/src/app/modules/boards/board/board-list/board-list.component.sass
Labels: styling

#7282 [Boards] Increase highlighted drop zone
  app/assets/stylesheets/openproject/_generic.sass
  frontend/src/app/components/wp-card-view/wp-card-view.component.sass
  frontend/src/app/modules/boards/board/board-list/board-list.component.html
  frontend/src/app/modules/boards/board/board-list/board-list.component.sass
  frontend/src/app/modules/boards/board/board.component.sass
  frontend/src/app/modules/boards/drag-and-drop/drag-and-drop.service.ts
Labels: bugfix, needs-review, styling

#7289 [30143] Respect fullcalendar exclusive end date
  frontend/src/app/modules/calendar/wp-calendar/wp-calendar.component.ts
Labels: bugfix

#7285 Use our packaged pgloader-ccl, as well as the migration script
  docs/operations/migrating/packaged/postgresql-migration.md
Labels: documentation, needs-review, packager

#7296 [30172] Label "New" for boards module
  app/assets/stylesheets/layout/_main_menu.sass
  frontend/src/app/components/main-menu/main-menu-navigation.service.ts
  lib/redmine/menu_manager/menu_helper.rb
  modules/boards/config/locales/en.yml
  modules/boards/lib/open_project/boards/engine.rb
Labels: feature, styling

#7298 [30211] Missing status indicator on card in version board
  frontend/src/app/modules/boards/board/board-list/board-list.component.html
  frontend/src/app/modules/boards/board/board-list/board-list.component.ts
  frontend/src/app/modules/boards/board/board.ts
Labels: bugfix

#7301 [Boards] Seeded board queries are not public
  app/seeders/demo_data/work_package_board_seeder.rb
Labels: bugfix

#7300 [30218] Restrict inline editing for basic boards
  frontend/src/app/modules/boards/board/board-list/board-list.component.ts
  frontend/src/app/modules/boards/board/board.component.sass
  frontend/src/app/modules/common/editable-toolbar-title/editable-toolbar-title.sass
  modules/boards/spec/features/board_highlighting_spec.rb
  modules/boards/spec/features/support/board_page.rb
Labels: feature

#7302 [30217] WP table highlighting not kept after reloading
  frontend/src/app/components/wp-fast-table/state/wp-table-highlighting.service.ts
  spec/features/work_packages/highlighting_spec.rb
Labels: bugfix, styling

#7305 Add icon for openID module
  app/assets/fonts/openproject_icon/openproject-icon-font.svg
  app/assets/fonts/openproject_icon/openproject-icon-font.ttf
  app/assets/fonts/openproject_icon/openproject-icon-font.woff
  app/assets/fonts/openproject_icon/openproject-icon-font.woff2
  app/assets/fonts/openproject_icon/src/openid.svg
  app/assets/stylesheets/fonts/_openproject_icon_definitions.scss
  app/assets/stylesheets/fonts/_openproject_icon_font.lsg
  modules/openid_connect/lib/open_project/openid_connect/engine.rb
Labels: styling

#7304 [30202] Visualise that empty filter values are not allowed for multiSelect Fields
  app/assets/stylesheets/content/_context_menu.sass
  app/assets/stylesheets/content/_loading_indicator.sass
  app/assets/stylesheets/openproject/_generic.sass
  app/assets/stylesheets/openproject/_mixins.sass
  frontend/src/app/components/filters/filter-container/filter-container.directive.ts
  frontend/src/app/components/filters/filter-toggled-multiselect-value/filter-toggled-multiselect-value.component.html
  frontend/src/app/components/filters/filter-toggled-multiselect-value/filter-toggled-multiselect-value.component.ts
  frontend/src/app/components/wp-fast-table/state/wp-table-filters.service.ts
  frontend/src/app/modules/work_packages/routing/wp-list/wp-list.component.sass
  frontend/src/app/modules/work_packages/routing/wp-list/wp-list.component.ts
  frontend/src/app/modules/work_packages/routing/wp-list/wp.list.component.html
Labels: bugfix, needs-review, styling

#7287 Type description
  app/contracts/types/base_contract.rb
  app/models/permitted_params.rb
  app/services/work_packages/set_attributes_service.rb
  app/views/types/form/_settings.html.erb
  config/locales/en.yml
  db/migrate/20190509071101_add_default_description_to_types.rb
  frontend/src/app/components/work-packages/wp-single-view/wp-single-view.html
  frontend/src/app/components/wp-edit-form/work-package-changeset.ts
  frontend/src/app/modules/fields/edit/edit-field.component.ts
  frontend/src/app/modules/fields/edit/field-types/formattable-edit-field.component.ts
  lib/api/v3/work_packages/work_package_payload_representer.rb
  spec/factories/type_factory.rb
  spec/features/work_packages/new/work_package_default_description_spec.rb
Labels: feature

#7307 [29994] First click on view in left menu often lost
  frontend/src/app/components/wp-query-select/wp-query-select-dropdown.component.ts
  frontend/src/app/modules/router/openproject.routes.ts
  spec/features/work_packages/navigation_spec.rb
Labels: bugfix

#7312 [30231] Correctly reset form when cancelling editing
  frontend/src/app/components/wp-edit/wp-edit-field/wp-edit-field-group.directive.ts
  frontend/src/app/components/wp-new/wp-create.service.ts
  spec/features/work_packages/new/new_work_package_spec.rb
Labels: bugfix

#7313 [30230] Don't pass injector in isolated query
  frontend/src/app/components/work-packages/wp-single-view/wp-single-view.component.ts
  frontend/src/app/components/work-packages/wp-single-view/wp-single-view.html
Labels: bugfix

#7297 [30212] Add link to edit version in list options in boards view
  config/locales/js-en.yml
  frontend/src/app/modules/boards/board/board-actions/board-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/status-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/version-action.service.ts
  frontend/src/app/modules/boards/board/board-list/board-list-dropdown.directive.ts
  frontend/src/app/modules/boards/board/board-list/board-list.component.ts
  frontend/src/app/modules/boards/board/board-list/board-list.service.ts
  frontend/src/app/modules/boards/openproject-boards.module.ts
  frontend/src/app/modules/common/path-helper/path-helper.service.ts
Labels: feature, needs-review

#7309 [30224] Allow referrer back url to be used for back_url
  app/helpers/application_helper.rb
Labels: bugfix, needs-review

#7310 [30168][Boards] Create new versions in the board view
  config/locales/js-en.yml
  frontend/src/app/modules/boards/board/add-list-modal/add-list-modal.component.ts
  frontend/src/app/modules/boards/board/add-list-modal/add-list-modal.html
  frontend/src/app/modules/boards/board/board-actions/board-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/status-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/version-action.service.ts
  frontend/src/app/modules/common/path-helper/apiv3/versions/apiv3-version-paths.ts
  frontend/src/app/modules/hal/dm-services/version-dm.service.ts
  modules/boards/config/locales/js-en.yml
  modules/boards/spec/features/action_boards/version_board_spec.rb
  modules/boards/spec/features/support/board_page.rb
Labels: feature, needs-review

#7314 [28036] Give admin all roles in a project
  app/cells/members/row_cell.rb
  app/models/user.rb
  config/locales/en.yml
  spec/features/work_packages/edit_work_package_spec.rb
  spec_legacy/unit/user_spec.rb
Labels: feature

#7288 [30173] Allow altering order of permission and modules
  app/controllers/roles_controller.rb
  app/views/roles/_form.html.erb
  config/initializers/permissions.rb
  lib/redmine/access_control.rb
  lib/redmine/plugin.rb
  modules/boards/lib/open_project/boards/engine.rb
  modules/costs/lib/open_project/costs/engine.rb
  modules/documents/lib/open_project/documents/engine.rb
  modules/global_roles/app/views/roles/_form.html.erb
  modules/global_roles/app/views/roles/_member_form.html.erb
  modules/global_roles/app/views/roles/_permissions.html.erb
  modules/global_roles/app/views/roles/edit.html.erb
  modules/global_roles/app/views/roles/new.html.erb
  modules/global_roles/features/global_create_project.feature
  modules/global_roles/features/global_role_assignment.feature
  modules/global_roles/features/global_role_crud.feature
  modules/global_roles/features/member_roles.feature
  modules/global_roles/features/no_module.feature
  modules/global_roles/features/step_definitions/global_role_steps.rb
  modules/global_roles/lib/open_project/global_roles/patches/roles_controller_patch.rb
  modules/global_roles/spec/controllers/roles_controller_spec.rb
  modules/global_roles/spec/features/global_create_project_spec.rb
  modules/global_roles/spec/features/global_role_assignment_spec.rb
  modules/global_roles/spec/features/global_role_crud_spec.rb
  modules/global_roles/spec/features/member_roles_spec.rb
  modules/global_roles/spec/features/no_module_spec.rb
  modules/global_roles/spec/plugin_spec_helper.rb
  modules/meeting/lib/open_project/meeting/engine.rb
  modules/my_project_page/config/locales/en.yml
  spec/support/pages/members.rb
Labels: feature, needs-review

#7316 [Boards] Focus the autocompleter of the add-list-modal
  app/assets/stylesheets/content/_modal.sass
  frontend/src/app/modules/boards/board/add-list-modal/add-list-modal.component.ts
  frontend/src/app/modules/boards/board/add-list-modal/add-list-modal.html
  modules/boards/spec/features/support/board_page.rb
Labels: bugfix, styling

#7306 Documentation for OpenID Azure
  docs/configuration/openid.md
  docs/images/openid/01-menu.png
  docs/images/openid/02-admin-dashboard.png
  docs/images/openid/03-app-registrations.png
  docs/images/openid/04-register-app.png
  docs/images/openid/05-register-overview.png
  docs/images/openid/06-certificates.png
  docs/images/openid/07-client-secret.png
  docs/images/openid/08-add-secret.png
Labels: documentation

#7318 [30197] Use separate ENV to trigger frontend angular recompilation
  lib/tasks/assets.rake
  lib/tasks/packager.rake
Labels: packager

#7324 Use shallow copy in changeset
  frontend/src/app/components/wp-edit-form/work-package-changeset.ts
Labels: performance

#7325 Increase avatars in WP table
  app/assets/stylesheets/content/_user.lsg
  app/assets/stylesheets/content/_user.sass
  frontend/src/app/modules/fields/display/display-portal/display-user-field-portal/user-field-portal.component.html
  lib/open_project/design.rb
Labels: styling

#7323 [30249] Change default order of wp table
  config/settings.yml
  modules/xls_export/spec/lib/work_package_xls_export_spec.rb
  spec/features/accessibility/work_packages/work_package_query_spec.rb
Labels: on-hold

#7317 [30237] Create versions from within select box in WP views
  config/locales/js-en.yml
  frontend/src/app/modules/boards/board/add-list-modal/add-list-modal.component.ts
  frontend/src/app/modules/boards/board/add-list-modal/add-list-modal.html
  frontend/src/app/modules/boards/board/board-actions/board-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/status-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/version-action.service.ts
  frontend/src/app/modules/common/autocomplete/create-autocompleter.component.ts
  frontend/src/app/modules/common/autocomplete/version-autocompleter.component.ts
  frontend/src/app/modules/common/openproject-common.module.ts
  frontend/src/app/modules/fields/edit/edit-field.initializer.ts
  frontend/src/app/modules/fields/edit/field-types/select-autocompleter-register.service.ts
  frontend/src/app/modules/fields/edit/field-types/select-edit-field.component.html
  frontend/src/app/modules/fields/edit/field-types/select-edit-field.component.ts
  frontend/src/app/modules/fields/openproject-fields.module.ts
  frontend/src/app/modules/work_packages/openproject-work-packages.module.ts
  lib/api/v3/versions/create_form_api.rb
  modules/boards/spec/features/support/board_page.rb
  spec/features/custom_fields/multi_user_custom_field_spec.rb
  spec/features/custom_fields/multi_value_custom_field_spec.rb
  spec/features/work_packages/details/custom_fields/custom_field_spec.rb
  spec/features/work_packages/details/inplace_editor/version_editor_spec.rb
  spec/features/work_packages/new/new_work_package_spec.rb
  spec/features/work_packages/table/edit_work_packages_spec.rb
  spec/features/work_packages/table/switch_types_spec.rb
  spec/support/pages/work_packages/abstract_work_package.rb
  spec/support/work_packages/work_package_field.rb
  spec/support/work_packages/work_package_multi_select_field.rb
Labels: feature, needs-review

#7321 Feature: meeting content attachments
  app/models/attachment.rb
  frontend/src/app/modules/hal/resources/meeting-content-resource.ts
  frontend/src/app/modules/hal/services/hal-resource.config.ts
  modules/meeting/app/controllers/meeting_contents_controller.rb
  modules/meeting/app/models/meeting.rb
  modules/meeting/app/models/meeting_content.rb
  modules/meeting/app/views/meeting_contents/_form.html.erb
  modules/meeting/app/views/meeting_contents/_show.html.erb
  modules/meeting/lib/api/v3/attachments/attachments_by_meeting_content_api.rb
  modules/meeting/lib/api/v3/meeting_agendas/meeting_agenda_representer.rb
  modules/meeting/lib/api/v3/meeting_contents/meeting_content_representer.rb
  modules/meeting/lib/api/v3/meeting_minutes/meeting_minutes_representer.rb
  modules/meeting/lib/api/v3/meetings/meeting_contents_api.rb
  modules/meeting/lib/open_project/meeting/engine.rb
  modules/meeting/spec/features/meetings_attachments_spec.rb
  modules/meeting/spec/requests/api/v3/attachments/meeting_agenda_spec.rb
  modules/meeting/spec/requests/api/v3/attachments/meeting_minutes_spec.rb
  spec/requests/api/v3/attachments/attachment_resource_shared_examples.rb
  spec/requests/api/v3/attachments/attachments_by_post_resource_spec.rb
  spec/requests/api/v3/attachments/attachments_by_wiki_page_resource_spec.rb
  spec/requests/api/v3/attachments/attachments_by_work_package_resource_spec.rb
  spec/requests/api/v3/attachments/forum_message_spec.rb
  spec/requests/api/v3/attachments/wiki_page_spec.rb
  spec/requests/api/v3/attachments/work_package_spec.rb
Labels: needs-review

#7322 [30247] Fix regresion from double click work package search
  frontend/src/app/modules/router/openproject.routes.ts
  spec/features/work_packages/navigation_spec.rb
Labels: bugfix

#7326 [30246] Defer loading form for work package fields
  frontend/src/app/components/work-packages/work-package-comment/work-package-comment-field-handler.ts
  frontend/src/app/components/wp-edit-form/work-package-edit-form.ts
  frontend/src/app/modules/common/autocomplete/create-autocompleter.component.ts
  frontend/src/app/modules/common/set-click-position/set-click-position.ts
  frontend/src/app/modules/fields/edit/edit-field.component.ts
  frontend/src/app/modules/fields/edit/field-types/formattable-edit-field.component.ts
  frontend/src/app/modules/fields/edit/field-types/multi-select-edit-field.component.ts
  frontend/src/app/modules/fields/edit/field-types/select-edit-field.component.ts
  spec/features/work_packages/attachments/attachment_upload_spec.rb
  spec/features/work_packages/details/custom_fields/custom_field_spec.rb
  spec/features/work_packages/details/inplace_editor/version_editor_spec.rb
  spec/features/work_packages/tabs/activity_tab_spec.rb
Labels: needs-review, performance

#7337 [30257] Redirect after deleting WPs from WP table leads to boards
  frontend/src/app/components/modals/wp-destroy-modal/wp-destroy.modal.ts
Labels: bugfix

#7340 [30243] Update highlighted menu node when switching between angular states
  app/assets/javascripts/onboarding/boards_tour.js
  app/assets/javascripts/onboarding/onboarding_tour.js
  config/locales/en.yml
  config/locales/js-en.yml
  frontend/src/app/modules/boards/openproject-boards.module.ts
  frontend/src/app/modules/calendar/openproject-calendar.module.ts
  frontend/src/app/modules/router/openproject.routes.ts
  frontend/src/app/modules/work_packages/routing/work-packages-routes.ts
  lib/redmine/menu_manager/menu_helper.rb
Labels: bugfix, needs-review

#7341 [30269] Creating a new version from within the WP create form does nothing
  frontend/src/app/modules/common/autocomplete/create-autocompleter.component.ts
  frontend/src/app/modules/fields/edit/field-types/select-edit-field.component.ts
Labels: bugfix

#7334 [30255] Add new teaser element for Boards on Application landing page
  app/assets/images/boards_video_teaser.png
  app/assets/stylesheets/content/_widget_box.sass
  app/views/homescreen/blocks/_new_features.html.erb
  app/views/homescreen/blocks/_news.html.erb
  config/initializers/homescreen.rb
  config/locales/en.yml
  config/locales/js-en.yml
  frontend/src/app/components/homescreen/blocks/new-features.component.sass
  frontend/src/app/components/homescreen/blocks/new-features.component.ts
  frontend/src/app/modules/boards/board-constants.const.ts
  frontend/src/app/modules/boards/board/board-video-teaser-modal/board-video-teaser-modal.component.ts
  frontend/src/app/modules/common/openproject-common.module.ts
  lib/open_project/design.rb
Labels: feature, needs-review
