Repository opf/openproject, pull requests merged in 2020-07, with the labels that each got.

#8478 [33680]Add "projects" to the global Modules menu
  config/initializers/menus.rb
  config/locales/en.yml
  spec/features/menu_items/top_menu_item_spec.rb
Labels: feature

#8486 [33715] Align checkboxes in tables correctly
  frontend/src/global_styles/content/_wiki.sass
  frontend/src/global_styles/content/editor/_markdown.sass
  frontend/src/global_styles/vendor/foundation-apps/scss/components/_typography.scss
Labels: bugfix, needs review, styling

#8487 [33749] Add padding to "Log time" widget and unify modal paddings
  frontend/src/app/components/enterprise/enterprise-modal/enterprise-trial.modal.sass
  frontend/src/app/modules/time_entries/shared/modal/base.modal.sass
  frontend/src/global_styles/content/_modal.sass
  frontend/src/global_styles/content/work_packages/_table_configuration_modal.sass
  frontend/src/global_styles/openproject/_onboarding.sass
Labels: bugfix, needs review, styling

#8489 Allow jobs to define a title for the job status modal
  app/workers/copy_project_job.rb
  app/workers/work_packages/exports/export_job.rb
  config/locales/en.yml
  frontend/src/app/modules/job-status/job-status-modal/job-status.modal.html
  frontend/src/app/modules/job-status/job-status-modal/job-status.modal.ts
  frontend/src/app/modules/job-status/job-status.interface.ts
  modules/job_status/app/workers/job_status/application_job_with_status.rb
  spec/features/work_packages/export_spec.rb
  spec/workers/copy_project_job_spec.rb
Labels: feature

#8490 Push images to official docker repository
  .github/workflows/docker.yml
Labels: needs review

#8485 [33650]ATOM feed link for all activities is not created as intended
  app/views/activities/index.html.erb
Labels: bugfix

#8497 [33736] Adapt LSG styling
  app/views/layouts/styleguide/styleguide.layout.html.erb
Labels: housekeeping, needs review

#8488 [33747]Back button does not work when coming from Boards
  frontend/src/app/components/wp-single-view-tabs/keep-tab/keep-tab.service.spec.ts
  frontend/src/app/components/wp-single-view-tabs/keep-tab/keep-tab.service.ts
  frontend/src/app/modules/common/back-routing/back-routing.service.ts
  frontend/src/app/modules/work_packages/openproject-work-packages.module.ts
  modules/bim/spec/features/bim_navigation_spec.rb
  modules/boards/spec/features/board_navigation_spec.rb
Labels: bugfix

#8499 [33690] wiki after navigate on item in sidebar, the sidebar reset to top and lose the view of focus item
  frontend/src/app/globals/tree-menu.ts
Labels: bugfix

#8502 [33302] Redirect user to TOC if new wiki page is not editable
  app/controllers/wiki_controller.rb
  config/locales/en.yml
  spec/controllers/wiki_controller_spec.rb
Labels: bugfix

#8503 [33678] Priority needs to be a require field
  app/models/type/attributes.rb
  lib/api/v3/work_packages/schema/work_package_schema_representer.rb
  spec/lib/api/v3/work_packages/schema/work_package_schema_representer_spec.rb
Labels: bugfix

#8505 [33868] Refactor table events as output of the table component
  frontend/src/app/components/wp-card-view/event-handler/click-handler.ts
  frontend/src/app/components/wp-card-view/event-handler/double-click-handler.ts
  frontend/src/app/components/wp-card-view/wp-card-view.component.ts
  frontend/src/app/components/wp-fast-table/builders/ui-state-link-builder.ts
  frontend/src/app/components/wp-fast-table/handlers/cell/edit-cell-handler.ts
  frontend/src/app/components/wp-fast-table/handlers/cell/relations-cell-handler.ts
  frontend/src/app/components/wp-fast-table/handlers/click-or-enter-handler.ts
  frontend/src/app/components/wp-fast-table/handlers/context-menu/context-menu-click-handler.ts
  frontend/src/app/components/wp-fast-table/handlers/context-menu/context-menu-handler.ts
  frontend/src/app/components/wp-fast-table/handlers/context-menu/context-menu-keyboard-handler.ts
  frontend/src/app/components/wp-fast-table/handlers/context-menu/context-menu-rightclick-handler.ts
  frontend/src/app/components/wp-fast-table/handlers/row/click-handler.ts
  frontend/src/app/components/wp-fast-table/handlers/row/double-click-handler.ts
  frontend/src/app/components/wp-fast-table/handlers/row/group-row-handler.ts
  frontend/src/app/components/wp-fast-table/handlers/row/hierarchy-click-handler.ts
  frontend/src/app/components/wp-fast-table/handlers/row/wp-state-links-handler.ts
  frontend/src/app/components/wp-fast-table/handlers/table-handler-registry.ts
  frontend/src/app/components/wp-grid/wp-grid.component.ts
  frontend/src/app/components/wp-table/embedded/wp-embedded-table.component.ts
  frontend/src/app/components/wp-table/embedded/wp-embedded-table.html
  frontend/src/app/components/wp-table/timeline/container/wp-timeline-container.directive.ts
  frontend/src/app/components/wp-table/wp-table.component.ts
  frontend/src/app/modules/bim/ifc_models/bcf/list-container/bcf-list-container.component.ts
  frontend/src/app/modules/bim/ifc_models/ifc-base-view/event-handler/bcf-card-view-handler-registry.ts
  frontend/src/app/modules/bim/ifc_models/ifc-base-view/event-handler/bcf-click-handler.ts
  frontend/src/app/modules/bim/ifc_models/ifc-base-view/event-handler/bcf-double-click-handler.ts
  frontend/src/app/modules/boards/board/board-list/board-list.component.html
  frontend/src/app/modules/boards/board/board-list/board-list.component.ts
  frontend/src/app/modules/work_packages/openproject-work-packages.module.ts
  frontend/src/app/modules/work_packages/routing/wp-list-view/wp-list-view.component.html
  frontend/src/app/modules/work_packages/routing/wp-list-view/wp-list-view.component.ts
  frontend/src/app/modules/work_packages/routing/wp-view-base/event-handling/event-handler-registry.ts
Labels: housekeeping

#8500 [33753] "New Board" modal is missing a header text
  frontend/src/app/modules/boards/new-board-modal/new-board-modal.component.ts
  frontend/src/app/modules/boards/new-board-modal/new-board-modal.html
  modules/boards/config/locales/js-en.yml
Labels: bugfix

#8507 [33756] WP still shown after deleting it
  frontend/src/app/modules/common/back-routing/back-routing.service.ts
  modules/boards/spec/features/board_navigation_spec.rb
  modules/boards/spec/features/support/board_page.rb
Labels: bugfix

#8506 Accept the fact that timings cause a rows' group to be null
  frontend/src/app/components/wp-fast-table/builders/modes/grouped/grouped-render-pass.ts
  spec/support/components/work_packages/tabs_counter.rb
Labels: bugfix

#8508 [33592] Allow type configuration to be empty
  frontend/src/app/modules/admin/types/type-form-configuration.component.ts
  spec/features/types/form_configuration_spec.rb
  spec/support/components/admin/type_configuration_form.rb
Labels: bugfix

#8511 [33654] Make the project member invitation more appealing
  app/mailers/user_mailer.rb
  app/views/layouts/user_mailer.html.erb
  app/views/user_mailer/user_signed_up.html.erb
  app/views/user_mailer/user_signed_up.text.erb
  config/locales/en.yml
  lib/open_project/static/links.rb
Labels: feature

#8510 Use distinct(*) on aggregated journal to avoid duplicate raw journals
  app/models/journal/aggregated_journal.rb
  app/models/journal/scopes/aggregated_journal.rb
  spec/features/work_packages/details/markdown/activity_comments_spec.rb
Labels: bugfix

#8496 Bim/fix/33758 keep scroll position when back to list from detail
  frontend/src/app/modules/bim/ifc_models/bcf/list-container/bcf-list-container.component.ts
  frontend/src/app/modules/work_packages/routing/wp-list-view/wp-list-view.component.ts
Labels: needs review, pullpreview

#8523 [33930] Fix broken documents layout
  frontend/src/global_styles/content/modules/_index.sass
  frontend/src/global_styles/openproject/_variables.scss
Labels: bugfix, needs review

#8517 [33901] Disable the button and disallow editing for scheduled parents
  frontend/src/app/components/datepicker/datepicker.modal.html
  frontend/src/app/components/datepicker/datepicker.modal.sass
  frontend/src/app/components/datepicker/datepicker.modal.ts
  spec/features/work_packages/table/scheduling/manual_scheduling_spec.rb
Labels: bugfix
