Repository opf/openproject, pull requests merged in 2020-01, with the labels that each got.

#7939 [31744] Fix: mobile grid
  app/assets/stylesheets/content/_grid_mobile.sass
  app/assets/stylesheets/content/_index.sass
  app/assets/stylesheets/content/menus/_menu_blocks.sass
  app/assets/stylesheets/layout/_base.sass
  frontend/src/app/modules/grids/grid/grid.component.html
  frontend/src/app/modules/grids/grid/page/grid-page.component.sass
Labels: bugfix, needs review

#7962 [31896] Text in custom field not correctly displayed
  app/assets/stylesheets/content/_autocomplete.sass
  app/assets/stylesheets/content/work_packages/_table_content.sass
  app/assets/stylesheets/content/work_packages/inplace_editing/_display_fields.sass
  frontend/src/app/modules/grids/widgets/custom-text/custom-text.component.ts
Labels: bugfix, needs review, styling

#7967 [31907] New Wiki page are not showed
  app/helpers/wiki_helper.rb
  app/views/wiki/index.html.erb
  db/migrate/20200115090742_fix_parent_id_for_wiki_pages.rb
Labels: bugfix, needs review

#7970 [31962] Selection tiles or multiple tiles is not working
  frontend/src/app/components/wp-card-view/wp-card-view.component.ts
  frontend/src/app/components/wp-card-view/wp-single-card/wp-single-card.component.html
  frontend/src/app/components/wp-card-view/wp-single-card/wp-single-card.component.ts
  spec/features/work_packages/select/select_card_view.spec.rb
  spec/support/pages/work_packages/work_package_cards.rb
Labels: bugfix, needs review

#7966 [31974] Simplify instance color theme changes
  app/assets/stylesheets/content/_forms.sass
  app/assets/stylesheets/layout/_colors.sass
  app/assets/stylesheets/openproject/_variables.scss.erb
  app/controllers/custom_styles_controller.rb
  app/views/custom_styles/show.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20200114091135_add_theme_name_to_custom_styles.rb
  lib/open_project.rb
  lib/open_project/custom_styles/color_themes.rb
  lib/open_project/custom_styles/design.rb
  modules/bim_seeder/lib/open_project/bim_seeder/patches/design_patch.rb
  spec/views/custom_styles/show.html.erb_spec.rb
Labels: feature, needs review, styling

#7980 Bump xeokit viewer and sdk
  frontend/npm-shrinkwrap.json
  frontend/package.json
Labels: housekeeping, needs review

#7981 Remove unnecessary file upload
  modules/ifc_models/spec/factories/ifc_model_factory.rb
Labels: housekeeping

#7951 [31871] Fix: Keyboard opens unnecessarily on Safari mobile
  frontend/src/app/components/main-menu/main-menu-toggle.service.ts
Labels: bugfix, needs review

#7985 Add "manage models" button on show page
  modules/ifc_models/app/views/ifc_models/ifc_models/show.html.erb
  modules/ifc_models/app/views/ifc_models/ifc_models/show_defaults.html.erb
Labels: bugfix, housekeeping, needs review

#7986 Bump Xeokit-Viewer to 1.4.2 and xeokit-sdk to 0.7.0
  frontend/npm-shrinkwrap.json
  frontend/package.json
  frontend/src/app/modules/ifc_models/ifc-viewer.component.ts
  frontend/src/app/modules/ifc_models/xeokit.d.ts
Labels: housekeeping

#7990 [31922] Child WP version cannot be edited although parent is no backlogs type
  modules/backlogs/lib/open_project/backlogs/patches/specific_work_package_schema_patch.rb
  modules/backlogs/spec/api/work_packages/schema/specific_work_package_schema_spec.rb
Labels: bugfix, needs review
