Repository opf/openproject, pull requests merged in 2020-02, with the labels that each got.

#7956 fixed the pop3 command (typo - error)
  docs/configuration/incoming-emails.md
Labels: needs review

#7993 [32114] Parent changes by drag and drop are not saved correctly
  frontend/src/app/components/wp-fast-table/helpers/wp-table-row-helpers.ts
  frontend/src/app/components/wp-table/drag-and-drop/actions/hierarchy-drag-action.service.ts
  spec/features/work_packages/sorting/manual_sorting_spec.rb
  spec/support/pages/work_packages/work_packages_table.rb
Labels: bugfix, needs review

#8009 [32118] Correctly pass highlighted attributes to query backend
  frontend/src/app/components/wp-query/url-params-helper.spec.ts
  frontend/src/app/components/wp-query/url-params-helper.ts
  spec/features/work_packages/highlighting_spec.rb
Labels: bugfix, needs review

#7992 [31744] Fix: Disable dragging on mobile devices
  frontend/src/app/modules/grids/grid/grid.component.html
  frontend/src/app/modules/grids/grid/grid.component.ts
Labels: bugfix, needs review

#8010 [32039] Wrong breadcrumbs in Administration
  app/controllers/application_controller.rb
  app/controllers/settings_controller.rb
  app/views/attribute_help_texts/edit.html.erb
  app/views/attribute_help_texts/new.html.erb
  app/views/layouts/admin.html.erb
  app/views/oauth/applications/edit.html.erb
  app/views/oauth/applications/new.html.erb
  app/views/oauth/applications/show.html.erb
  lib/redmine/menu_manager/menu_controller.rb
  modules/avatars/app/views/settings/_openproject_avatars.html.erb
  modules/backlogs/app/views/shared/_settings.html.erb
  modules/costs/app/views/settings/_openproject_costs.html.erb
  modules/ldap_groups/app/controllers/ldap_groups/synchronized_groups_controller.rb
  modules/ldap_groups/app/views/ldap_groups/synchronized_groups/new.html.erb
  modules/openid_connect/app/controllers/openid_connect/providers_controller.rb
  modules/openid_connect/app/views/openid_connect/providers/edit.html.erb
  modules/openid_connect/app/views/openid_connect/providers/new.html.erb
  modules/recaptcha/app/controllers/recaptcha/admin_controller.rb
  modules/two_factor_authentication/app/controllers/two_factor_authentication/two_factor_settings_controller.rb
  spec/views/layouts/admin.html.erb_spec.rb
Labels: bugfix, needs review

#8004 [32177] Disable recaptcha for admins
  modules/recaptcha/app/controllers/recaptcha/request_controller.rb
  modules/recaptcha/spec/controllers/request_controller_spec.rb
Labels: bugfix, needs review

#8005 [32178] Don't use flash in rendering change password form
  app/controllers/account_controller.rb
  app/controllers/concerns/user_password_change.rb
  app/views/my/password.html.erb
  spec/controllers/account_controller_spec.rb
Labels: bugfix, needs review

#8012 Show protocol mismatch warning when request is https
  app/helpers/warning_bar_helper.rb
  app/views/warning_bar/_host_and_protocol_mismatch.html.erb
  app/views/warning_bar/_warning_bar.html.erb
  config/locales/en.yml
  frontend/src/app/globals/global-listeners.ts
  lib/open_project/configuration.rb
Labels: housekeeping

#8019 [32141] OpenProject logo in light theme is hard to see
  app/controllers/custom_styles_controller.rb
  app/views/custom_styles/_inline_css.erb
  db/migrate/20200206101135_add_theme_logo_to_custom_style.rb
  lib/open_project/custom_styles/color_themes.rb
Labels: bugfix, needs review

#8020 [32056] Rename backlogs menu entry and move categories to the bottom
  app/helpers/project_settings_helper.rb
  config/initializers/menus.rb
  modules/backlogs/lib/open_project/backlogs/patches/project_settings_helper_patch.rb
Labels: bugfix

#8021 [32179] Reload list when deleting work package
  frontend/src/app/components/modals/wp-destroy-modal/wp-destroy.modal.ts
  frontend/src/app/modules/common/back-routing/back-routing.service.ts
Labels: bugfix

#8023 [32190] Switch filter requires/required for queries
  app/models/queries/work_packages/filter/required_filter.rb
  app/models/queries/work_packages/filter/requires_filter.rb
  frontend/src/app/components/wp-relations/wp-relations.service.ts
  spec/models/queries/work_packages/filter/required_filter_spec.rb
  spec/models/queries/work_packages/filter/requires_filter_spec.rb
Labels: bugfix

#8025 [32202] Update links on application start page and in help menu
  lib/open_project/static/links.rb
Labels: housekeeping

#8022 [32180] Fix invalid version diff number
  app/mailers/user_mailer.rb
  spec/mailers/user_mailer_spec.rb
Labels: bugfix

#8024 [32134] Blank Gantt chart when zooming out
  frontend/src/app/components/wp-table/timeline/container/wp-timeline-container.directive.ts
  frontend/src/app/components/wp-table/timeline/header/wp-timeline-header.directive.ts
Labels: bugfix, needs review

#7946 Improve Dockerfile and update docker-compose.yml
  .dockerignore
  Dockerfile
  docker-compose.yml
  docker/entrypoint.sh
  docker/mysql-to-postgres/bin/build
  docker/precompile-assets.sh
  docker/proxy.conf.erb
  docker/seeder
  docker/supervisord
  docker/worker
  docs/installation-and-operations/configuration/database/README.md
  docs/installation-and-operations/configuration/server/README.md
  docs/installation-and-operations/installation/docker/README.md
  docs/installation-and-operations/operation/backing-up/README.md
  docs/installation-and-operations/operation/restoring/README.md
Labels: needs review

#8027 [32204] Missing indication if field is mandatory for time tracking
  app/assets/stylesheets/content/_attributes_key_value.sass
  frontend/src/app/modules/time_entries/form/form.component.html
Labels: needs review, styling

#8032 [32218] Unnecessary dots displayed in subject column
  app/assets/stylesheets/content/work_packages/_table_hierarchy.sass
Labels: bugfix, styling

#8034 Add firefox headless to test the broken chrome float input
  spec/features/work_packages/details/custom_fields/custom_field_spec.rb
  spec/support/browsers/firefox.rb
Labels: housekeeping

#8033 [32216] Wrong query displayed after going to full screen view
  frontend/src/app/components/wp-query-select/wp-query-select-dropdown.component.ts
Labels: bugfix, needs review

#8035 [32168] Reload query in all cases
  frontend/src/app/components/modals/wp-destroy-modal/wp-destroy.modal.ts
  frontend/src/app/modules/common/back-routing/back-routing.service.ts
  frontend/src/app/modules/work_packages/routing/wp-list/wp-list.component.ts
  spec/features/work_packages/navigation_spec.rb
Labels: bugfix

#8039 make new feature teaser edition dependent
  app/assets/images/new_feature_teaser.jpg
  app/assets/images/new_feature_teaser.png
  app/assets/stylesheets/content/_widget_box.sass
  app/views/layouts/base.html.erb
  config/locales/js-en.yml
  frontend/src/app/components/homescreen/blocks/new-features.component.spec.ts
  frontend/src/app/components/homescreen/blocks/new-features.component.ts
  frontend/src/app/globals/openproject.ts
  frontend/src/app/modules/dashboards/dashboard-constants.const.ts
  lib/open_project/custom_styles/design.rb
  modules/bim_seeder/app/assets/images/bim_seeder/new_feature_teaser.jpg
  modules/bim_seeder/lib/open_project/bim_seeder/patches/design_patch.rb
Labels: feature, needs review

#8041 [32133] Show loading indicator until timeline refreshed if it is open
  frontend/src/app/components/wp-card-view/services/wp-card-view.service.ts
  frontend/src/app/components/wp-fast-table/builders/modes/grouped/grouped-rows-builder.ts
  frontend/src/app/components/wp-fast-table/handlers/state/hierarchy-transformer.ts
  frontend/src/app/components/wp-fast-table/handlers/state/rows-transformer.ts
  frontend/src/app/components/wp-fast-table/handlers/state/selection-transformer.ts
  frontend/src/app/components/wp-fast-table/wp-fast-table.ts
  frontend/src/app/components/wp-list/wp-states-initialization.service.ts
  frontend/src/app/components/wp-table/timeline/cells/wp-timeline-cell-mouse-handler.ts
  frontend/src/app/components/wp-table/timeline/container/wp-timeline-container.directive.ts
  frontend/src/app/modules/work_packages/query-space/isolated-query-space.ts
  frontend/src/app/modules/work_packages/routing/wp-list/wp-list.component.ts
  frontend/src/app/modules/work_packages/routing/wp-view-base/view-services/wp-view-hierarchy-indentation.service.spec.ts
Labels: bugfix, needs review

#8042 [32227] Header menu item vanishes when moving the mouse a bit to the left
  app/assets/javascripts/top_menu.js
  app/assets/stylesheets/layout/_top_menu_mobile.sass
Labels: bugfix, needs review, styling

#8048 [32267] Allow setting version on bulk copy
  app/controllers/work_packages/moves_controller.rb
  app/views/work_packages/moves/new.html.erb
  spec/controllers/work_packages/moves_controller_spec.rb
  spec/features/work_packages/bulk/copy_work_package_spec.rb
Labels: feature

#8047 [32268] Missing warning message when deleting time entry (on My page)
  frontend/src/app/modules/time_entries/edit/edit.modal.ts
  frontend/src/app/modules/time_entries/shared/modal/base.modal.ts
  modules/my_page/spec/features/my/time_entries_current_user_spec.rb
Labels: bugfix

#8049 [32274] Show the original roles for admins
  app/cells/members/row_cell.rb
Labels: bugfix

#8037 Change wording of relation queries
  app/assets/stylesheets/content/_tabs.sass
  config/locales/js-en.yml
  frontend/src/app/components/wp-table/configuration-modal/wp-table-configuration-relation-selector.html
  frontend/src/app/components/wp-table/configuration-modal/wp-table-configuration-relation-selector.ts
  frontend/src/app/components/wp-table/configuration-modal/wp-table-configuration.modal.html
  frontend/src/app/modules/admin/types/group-edit-in-place.component.ts
  frontend/src/app/modules/admin/types/group-edit-in-place.html
  frontend/src/app/modules/admin/types/type-form-configuration.component.ts
  lib/open_project/custom_styles/design.rb
  spec/features/types/form_configuration_query_spec.rb
  spec/support/browsers/chrome.rb
  spec/support/components/admin/type_configuration_form.rb
  spec/support/components/work_packages/table_configuration_modal.rb
  spec/support/local_storage_cleanup.rb
Labels: work in progress

#8055 [32205] Work package Save button should be blue as all other save buttons in the application
  frontend/src/app/modules/common/edit-actions-bar/wp-edit-actions-bar.html
Labels: bugfix, styling

#8054 [31859] Save date with confirm button when empty
  frontend/src/app/modules/common/op-date-picker/datepicker.ts
  frontend/src/app/modules/fields/edit/field-types/date-edit-field.component.ts
  spec/features/work_packages/details/date_editor_spec.rb
  spec/features/work_packages/details/inplace_editor/shared_examples.rb
  spec/features/work_packages/table/milestones_spec.rb
  spec/features/wysiwyg/user_autocomplete_spec.rb
  spec/support/edit_fields/edit_field.rb
  spec/support/edit_fields/text_editor_field.rb
Labels: bugfix

#8053 [32235] Fix missing news timestamp updated_at
  app/controllers/news_controller.rb
  app/models/news.rb
  app/models/queries/news/orders/default_order.rb
  app/views/homescreen/blocks/_news.html.erb
  app/views/news/_news.html.erb
  app/views/news/index.html.erb
  app/views/news/show.html.erb
  config/initializers/activity.rb
  db/migrate/20200217061622_add_timestamp_to_news.rb
  frontend/src/app/modules/grids/widgets/news/news.component.ts
  lib/api/v3/news/news_representer.rb
  modules/dashboards/spec/features/news_spec.rb
  modules/my_page/spec/features/my/news_spec.rb
  spec/controllers/homescreen_controller_spec.rb
  spec/controllers/news_controller_spec.rb
  spec/features/projects/projects_index_spec.rb
  spec/lib/api/v3/news/news_representer_rendering_spec.rb
  spec/models/project/activity_spec.rb
  spec_legacy/fixtures/news.yml
Labels: bugfix

#8060 [32194] New feature image for IFC integration
  modules/bim_seeder/app/assets/images/bim_seeder/new_feature_teaser.jpg
Labels: feature, styling

#8057 [31524] Overlapping menus on WP page
  app/assets/javascripts/top_menu.js
  frontend/src/app/components/op-context-menu/op-context-menu.service.ts
Labels: bugfix

#8061 [32255] Remove hover effect of action column in children table
  frontend/src/app/components/wp-table/wp-table.directive.html
Labels: bugfix, styling

#7969 [32000] Show WP list next to the ifc viewer
  app/assets/stylesheets/layout/work_packages/_table_embedded.sass
  frontend/src/app/components/wp-grid/wp-grid.component.ts
  frontend/src/app/components/wp-table/embedded/wp-embedded-table.html
  frontend/src/app/modules/ifc_models/ifc-base-view/ifc-base-view.component.html
  frontend/src/app/modules/ifc_models/ifc-base-view/ifc-base-view.component.sass
  frontend/src/app/modules/ifc_models/ifc-base-view/ifc-base-view.component.ts
  frontend/src/app/modules/ifc_models/ifc-viewer/ifc-viewer.component.ts
  frontend/src/app/modules/ifc_models/openproject-ifc-models.module.ts
  frontend/src/app/modules/ifc_models/xeokit/xeokit-server.d.ts
  frontend/src/app/modules/ifc_models/xeokit/xeokit-server.js
  frontend/src/app/modules/ifc_models/xeokit/xeokit.d.ts
  frontend/src/app/modules/work_packages/routing/wp-list/wp.list.component.html
  modules/ifc_models/app/assets/stylesheets/ifc_viewer/generic.sass
  modules/ifc_models/app/views/ifc_models/ifc_models/show.html.erb
  modules/ifc_models/app/views/ifc_models/ifc_models/show_defaults.html.erb
  modules/ifc_models/spec/features/model_viewer_spec.rb
  spec/support/pages/work_packages/work_package_cards.rb
Labels: feature, needs review

#8040 Bump xeokit viewer to 1.5.7
  frontend/npm-shrinkwrap.json
  frontend/package.json
  frontend/src/app/modules/ifc_models/ifc-viewer.component.ts
  frontend/src/app/modules/ifc_models/xeokit-server.js
  modules/ifc_models/app/assets/stylesheets/ifc_viewer/context_menu.sass
  modules/ifc_models/app/assets/stylesheets/ifc_viewer/tabs.sass
  modules/ifc_models/app/helpers/ifc_models_helper.rb
Labels: housekeeping

#8064 [32296] Also ensure versions are sorted by name
  app/models/queries/work_packages/columns/property_column.rb
  app/models/version.rb
  spec/models/query/sort_criteria_spec.rb
Labels: bugfix, needs review

#8066 Create CustomStyle if it does not exist yet
  app/controllers/custom_styles_controller.rb
  spec/controllers/custom_styles_controller_spec.rb
Labels: bugfix, needs review

#8065 IFC models: Add routes for split and viewer
  frontend/src/app/components/wp-table/embedded/wp-embedded-base.component.ts
  frontend/src/app/modules/calendar/wp-calendar-entry/wp-calendar-entry.component.ts
  frontend/src/app/modules/grids/grid/grid.component.ts
  frontend/src/app/modules/ifc_models/bcf/container/bcf-container.component.html
  frontend/src/app/modules/ifc_models/bcf/container/bcf-container.component.ts
  frontend/src/app/modules/ifc_models/empty/empty-component.ts
  frontend/src/app/modules/ifc_models/ifc-viewer/ifc-viewer.component.ts
  frontend/src/app/modules/ifc_models/openproject-ifc-models.module.ts
  frontend/src/app/modules/ifc_models/openproject-ifc-models.routes.ts
  frontend/src/app/modules/ifc_models/pages/index/ifc-index-page.component.sass
  frontend/src/app/modules/ifc_models/pages/viewer/ifc-viewer-page.component.html
  frontend/src/app/modules/ifc_models/pages/viewer/ifc-viewer-page.component.sass
  frontend/src/app/modules/ifc_models/pages/viewer/ifc-viewer-page.component.ts
  frontend/src/app/modules/work_packages/routing/wp-list/wp-list.component.ts
  frontend/src/app/modules/work_packages/routing/wp-view-base/work-packages-view.base.ts
  modules/bim/config/routes.rb
  modules/bim/spec/support/pages/ifc_models/index.rb
Labels: feature

#8070 Readd view toggle component
  frontend/src/app/modules/ifc_models/ifc-viewer/ifc-viewer.component.ts
  frontend/src/app/modules/ifc_models/openproject-ifc-models.module.ts
  frontend/src/app/modules/ifc_models/openproject-ifc-models.routes.ts
  frontend/src/app/modules/ifc_models/pages/viewer/ifc-viewer-page.component.html
  frontend/src/app/modules/ifc_models/view-toggle/bim-view-toggle-dropdown.directive.ts
  frontend/src/app/modules/ifc_models/view-toggle/bim-view-toggle.component.ts
  frontend/src/app/modules/ifc_models/view-toggle/bim-view.service.ts
  modules/bim/spec/features/bim_navigation_spec.rb
  modules/bim/spec/support/pages/ifc_models/show_default.rb
Labels: feature

#8078 Fix the design patch to respond to bim config
  lib/open_project/custom_styles/design.rb
  modules/bim/lib/open_project/bim/engine.rb
  modules/bim/lib/open_project/bim/patches/design_patch.rb
Labels: bugfix

#8073 [31979] Allow filtering WPs within IFC Models module
  frontend/src/app/components/wp-query/query-param-listener.service.ts
  frontend/src/app/modules/ifc_models/bcf/container/bcf-container.component.ts
  frontend/src/app/modules/ifc_models/openproject-ifc-models.routes.ts
  frontend/src/app/modules/ifc_models/pages/viewer/ifc-viewer-page.component.html
  frontend/src/app/modules/ifc_models/pages/viewer/ifc-viewer-page.component.sass
  frontend/src/app/modules/ifc_models/pages/viewer/ifc-viewer-page.component.ts
  frontend/src/app/modules/ifc_models/view-toggle/bim-view-toggle-dropdown.directive.ts
  frontend/src/app/modules/ifc_models/view-toggle/bim-view-toggle.component.ts
  frontend/src/app/modules/ifc_models/view-toggle/bim-view.service.ts
  frontend/src/app/modules/work_packages/routing/wp-list/wp-list.component.ts
  modules/bim/spec/features/bim_filter_spec.rb
  modules/bim/spec/support/pages/ifc_models/show_default.rb
Labels: feature, needs review

#8081 [32356] Custom Design gone after change color schema
  app/views/custom_styles/show.html.erb
  config/locales/en.yml
Labels: bugfix, needs review, styling

#8080 [32354] Correctly escape filters in frontend to avoid unescape
  app/services/api/v3/parse_query_params_service.rb
  frontend/src/app/components/api/api-v3/api-v3-filter-builder.ts
  frontend/src/app/modules/common/path-helper/apiv3/apiv3-paths.ts
  frontend/src/app/modules/common/path-helper/path-helper.service.spec.ts
  frontend/src/app/modules/global_search/input/global-search-input.component.ts
  spec/features/search_spec.rb
  spec/features/work_packages/table/queries/filter_spec.rb
  spec/services/api/v3/parse_query_params_service_spec.rb
Labels: bugfix, needs review

#8088 [31902] Ensure we pass the query_id in case of manual queries
  app/services/api/v3/work_package_collection_from_query_service.rb
  spec/features/work_packages/export_spec.rb
Labels: bugfix
