Repository opf/openproject, pull requests merged in 2020-09, with the labels that each got.

#8616 [34063] Prevent child to be moved into its own column
  frontend/src/app/modules/boards/board/board-actions/board-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/subtasks/board-subtasks-action.service.ts
  frontend/src/app/modules/fields/changeset/resource-changeset.ts
  frontend/src/app/modules/hal/services/hal-resource-notification.service.ts
  modules/boards/config/locales/js-en.yml
  modules/boards/spec/features/action_boards/subtasks_board_spec.rb
Labels: bugfix

#8562 Open wp form in full width on BCF section on Revit
  frontend/src/app/modules/bim/ifc_models/openproject-ifc-models.routes.ts
  frontend/src/app/modules/bim/ifc_models/pages/viewer/ifc-viewer-page.component.ts
  modules/bim/spec/features/bim_revit_add_in_navigation_spec.rb
Labels: needs review

#8612 Fix/33578 Image in comments removes the original on description
  frontend/src/app/components/work-packages/work-package-comment/work-package-comment.component.ts
Labels: needs review

#8626 [33869] Use `auth_source` link for parsing
  lib/api/v3/users/user_representer.rb
  spec/requests/api/v3/user/create_user_resource_spec.rb
Labels: bugfix

#8628 Remove patches for document links generation and re-add meetings
  docs/user-guide/wysiwyg/README.md
  lib/open_project/text_formatting/matchers/link_handlers/colon_separator.rb
  lib/open_project/text_formatting/matchers/link_handlers/hash_separator.rb
  modules/documents/lib/open_project/documents/engine.rb
  modules/documents/lib/open_project/documents/patches/colon_separator_patch.rb
  modules/documents/lib/open_project/documents/patches/hash_separator_patch.rb
  modules/documents/spec/lib/open_project/markdown_formatting_spec.rb
  modules/meeting/spec/lib/open_project/markdown_formatting_spec.rb
Labels: feature, housekeeping

#8629 [34190] Add missing wiki classes on project list
  app/cells/projects/row_cell.rb
  app/cells/views/projects/row/show.erb
Labels: styling

#8624 [34167] Add new project custom fields to enabled columns
  app/contracts/concerns/requires_admin_guard.rb
  app/contracts/custom_fields/base_contract.rb
  app/contracts/custom_fields/create_contract.rb
  app/contracts/custom_fields/update_contract.rb
  app/controllers/custom_fields_controller.rb
  app/services/custom_fields/create_service.rb
  app/services/custom_fields/set_attributes_service.rb
  app/services/custom_fields/update_service.rb
  db/migrate/20200903064009_enable_current_project_custom_fields_columns.rb
  spec/contracts/custom_fields/create_contract_spec.rb
  spec/contracts/custom_fields/update_contract_spec.rb
  spec/controllers/custom_fields_controller_spec.rb
  spec/services/custom_fields/create_service_spec.rb
  spec/services/custom_fields/set_attributes_service_spec.rb
  spec/services/custom_fields/update_service_spec.rb
Labels: feature, needs review

#8630 [33405] Track activity on overview by href + version
  frontend/src/app/components/wp-single-view-tabs/activity-panel/activity-entry-info.ts
  frontend/src/app/components/wp-single-view-tabs/activity-panel/activity-on-overview.component.ts
Labels: bugfix

#8631 [33766] Show errors when CF is invalid in project form
  app/controllers/projects_controller.rb
  app/views/projects/form/attributes/_identifier.html.erb
  frontend/src/app/modules/augmenting/dynamic-scripts/project_form_listener.js
  spec/features/projects/projects_spec.rb
Labels: bugfix

#8633 [33750] Ensure default statuses can not be set read only
  app/models/status.rb
  config/locales/en.yml
  spec/models/status_spec.rb
Labels: bugfix

#8634 [33912] Correct change detection on custom actions
  frontend/src/app/components/wp-custom-actions/wp-custom-actions.component.ts
Labels: bugfix

#8632 [32131] Only show active projects in custom action condition
  app/models/custom_actions/conditions/project.rb
  spec/models/custom_actions/conditions/project_spec.rb
Labels: bugfix

#8636 [33383] Treat number fields as text fields to allow localized input
  modules/budgets/app/controllers/budgets_controller.rb
  modules/budgets/app/models/budget.rb
  modules/budgets/app/views/budgets/items/_labor_budget_item.html.erb
  modules/budgets/app/views/budgets/items/_material_budget_item.html.erb
  modules/budgets/config/locales/en.yml
  modules/budgets/spec/features/budgets/add_budget_spec.rb
  modules/budgets/spec/support/pages/budget_form.rb
  modules/costs/app/views/cost_types/_list.html.erb
  modules/costs/app/views/cost_types/_rate.html.erb
  modules/costs/spec/features/cost_types/create_cost_type_spec.rb
Labels: bugfix

#8623 Fix/34126 Gantt chart styles conflict between last active work package and hovered work package
  frontend/src/app/components/wp-card-view/wp-single-card/wp-single-card.component.sass
  frontend/src/global_styles/content/_tables.sass
  frontend/src/global_styles/content/_work_packages.sass
  frontend/src/global_styles/content/work_packages/_cards.sass
Labels: needs review

#8637 Cancel changes and refresh timeline on backend error
  frontend/src/app/components/wp-table/timeline/cells/wp-timeline-cell-mouse-handler.ts
Labels: needs review

#8643 Use slide toggle on the project boolean filter
  app/views/projects/filters/_boolean.html.erb
  app/views/projects/filters/_form.html.erb
  frontend/src/app/components/filters/filter-boolean-value/filter-boolean-value.component.html
  frontend/src/app/global-dynamic-components.const.ts
  frontend/src/app/globals/global-listeners/top-menu.ts
  frontend/src/app/modules/augmenting/dynamic-scripts/project.js
  frontend/src/app/modules/common/slide-toggle/slide-toggle.component.html
  frontend/src/app/modules/common/slide-toggle/slide-toggle.component.sass
  frontend/src/app/modules/common/slide-toggle/slide-toggle.component.spec.ts
  frontend/src/app/modules/common/slide-toggle/slide-toggle.component.ts
  frontend/src/global_styles/content/_slide_toggle.lsg
  frontend/src/main.ts
  spec/features/projects/projects_index_spec.rb
  spec/support/pages/projects/index.rb
Labels: housekeeping, styling

#8644 [33983] Don't grant budget permissions on costs permissions
  modules/costs/lib/costs/engine.rb
Labels: bugfix

#8645 [34289] Avoid duplicate output of error messages in flash
  app/controllers/custom_fields_controller.rb
Labels: bugfix

#8640 Pin postgresql to 9.6 for the all-in-one docker image
  Dockerfile
  docker/setup/postinstall.sh
  docker/setup/preinstall-on-prem.sh
  docker/setup/preinstall.sh
  docker/supervisord
  docker/supervisord.conf
Labels: docker

#8642 Fixed: added margin bottom to the Gantt chart
  frontend/src/global_styles/layout/work_packages/_table.sass
Labels: needs review

#8621 Fix: Table: Dropping after last child of a group includes element in the group
  frontend/src/app/components/wp-fast-table/handlers/state/drag-and-drop-transformer.ts
  frontend/src/app/components/wp-fast-table/helpers/wp-table-hierarchy-helpers.ts
  frontend/src/app/components/wp-fast-table/helpers/wp-table-row-helpers.ts
  frontend/src/app/components/wp-table/drag-and-drop/actions/hierarchy-drag-action.service.ts
Labels: needs review

#8656 [34257] Allow localized input of overridden costs
  frontend/src/app/modules/common/remote-field-updater/remote-field-updater.component.ts
  modules/budgets/app/controllers/budgets_controller.rb
  modules/budgets/app/views/budgets/items/_labor_budget_item.html.erb
  modules/budgets/app/views/budgets/items/_material_budget_item.html.erb
  modules/budgets/frontend/module/augment/planned-costs-form.ts
  modules/costs/app/controllers/costlog_controller.rb
  modules/costs/app/views/costlog/edit.html.erb
  modules/costs/frontend/module/augment/cost-budget-subform.augment.service.ts
  modules/costs/frontend/module/augment/cost-subform.augment.service.ts
  modules/costs/frontend/module/augment/planned-costs-form.ts
  modules/costs/spec/features/add_cost_entry_spec.rb
Labels: bugfix

#8641 Update pullpreview workflow
  .github/workflows/pullpreview.yml
Labels: pullpreview

#8658 [34312] Update and use default settings for gantt query
  app/services/projects/gantt_query_generator_service.rb
  app/views/settings/_projects.html.erb
Labels: bugfix

#8659 [33696] Retain autologin cookied request in session
  app/controllers/account_controller.rb
  app/controllers/concerns/accounts/authentication_stages.rb
  spec/features/auth/consent_auth_stage_spec.rb
Labels: bugfix

#8639 [34070] Improve board creation modal
  frontend/src/app/helpers/images/path-helper.ts
  frontend/src/app/modules/boards/board/board-actions/assignee/assignee-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/board-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/board-actions-registry.service.ts
  frontend/src/app/modules/boards/board/board-actions/status/status-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/subproject/subproject-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/subtasks/board-subtasks-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/version/version-action.service.ts
  frontend/src/app/modules/boards/new-board-modal/new-board-modal.component.ts
  frontend/src/app/modules/boards/tile-view/tile-view.component.html
  frontend/src/app/modules/boards/tile-view/tile-view.component.sass
  frontend/src/app/modules/boards/tile-view/tile-view.component.spec.ts
  frontend/src/app/modules/boards/tile-view/tile-view.component.ts
  frontend/src/assets/images/board_creation_modal/assignees.svg
  frontend/src/assets/images/board_creation_modal/lists.svg
  frontend/src/assets/images/board_creation_modal/parent-child.svg
  frontend/src/assets/images/board_creation_modal/status.svg
  frontend/src/assets/images/board_creation_modal/subproject.svg
  frontend/src/assets/images/board_creation_modal/version.svg
  modules/boards/config/locales/js-en.yml
  modules/boards/spec/features/action_boards/subtasks_board_spec.rb
  modules/boards/spec/features/support/board_index_page.rb
Labels: feature, pullpreview

#8654 Fix: Time entry modal allows duplicated entries
  frontend/src/app/modules/fields/edit/edit-form/edit-form.ts
  frontend/src/app/modules/time_entries/shared/modal/base.modal.html
  frontend/src/app/modules/time_entries/shared/modal/base.modal.ts
Labels: needs review, pullpreview

#8669 [34427] Do not output empty success flash in omniauth flow
  app/controllers/concerns/accounts/omniauth_login.rb
Labels: bugfix

#8670 [34253] Fix positioning of datepicker
  frontend/src/global_styles/content/_datepicker.sass
Labels: bugfix, styling

#8635 Fix/34239 quick filters lost on projects system settings
  frontend/src/app/components/wp-table/configuration-modal/tabs/filters-tab.component.ts
Labels: needs review

#8671 [34291] Use placeholder for new resource dates
  frontend/src/app/components/wp-custom-actions/wp-custom-actions.component.ts
  frontend/src/app/modules/fields/edit/field-types/combined-date-edit-field.component.ts
  spec/features/work_packages/new/new_work_package_spec.rb
Labels: bugfix

#8673 [34446] Fix direct upload with backend-generated resources
  frontend/src/app/modules/hal/resources/hal-resource.ts
  frontend/src/app/modules/hal/resources/mixins/attachable-mixin.ts
  lib/api/v3/attachments/attachable_representer_mixin.rb
  modules/documents/spec/features/attachment_upload_spec.rb
  spec/features/admin/attribute_help_texts_spec.rb
  spec/support/shared/with_direct_uploads.rb
Labels: bugfix, pullpreview

#8650 Restore dropped element's original styles when back-end error
  frontend/src/app/components/wp-fast-table/handlers/state/drag-and-drop-transformer.ts
  frontend/src/app/modules/common/drag-and-drop/drag-and-drop.helpers.ts
Labels: needs review

#8648 Removed CSS that limit -checked styles to splitted views
  frontend/src/app/components/wp-card-view/wp-single-card/wp-single-card.component.sass
  frontend/src/global_styles/content/_tables.sass
  frontend/src/global_styles/content/_work_packages.sass
  frontend/src/global_styles/content/work_packages/_cards.sass
Labels: needs review

#8683 extend session TTL for logged-in users when using cache store for sessions
  config/initializers/session_store.rb
Labels: bugfix, needs review

#8674 Fix: Remove default values for BCF timestamps.
  db/migrate/20200914092212_set_current_timestamp_defaults_for_bcf_viewpoints_and_issues.rb
Labels: needs review

#8684 [33571] Update release teaser block
  config/locales/js-en.yml
  frontend/src/app/components/homescreen/blocks/new-features.component.ts
  frontend/src/assets/images/new_features.png
Labels: feature

#8688 [34290] Fix autoscroller on type groups
  frontend/src/app/modules/admin/types/type-form-configuration.component.ts
  frontend/src/app/modules/common/drag-and-drop/dom-autoscroll.service.ts
Labels: bugfix

#8668 Scrolling into view the activity component
  frontend/src/app/components/wp-activity/user/user-activity.component.ts
Labels: needs review

#8690 [34432] Save the tablesorter sort options in session
  frontend/src/app/modules/reporting/reporting-page/functionality/tablesorter.ts
Labels: bugfix

#8696 [34292]Typo and strange wording on board creation screen
  modules/boards/config/locales/js-en.yml
  modules/boards/spec/features/action_boards/subtasks_board_spec.rb
  modules/boards/spec/features/support/board_index_page.rb
Labels: bugfix

#8692 [33674]Make tables scrollable with sticky header
  app/cells/views/projects/table/show.erb
  frontend/src/global_styles/content/_pagination.sass
  frontend/src/global_styles/content/_table.sass
Labels: feature

#8649 Fix tooltips for Xeokit IFC viewer toolbar buttons.
  frontend/src/app/modules/bim/ifc_models/pages/viewer/styles/tooltips.sass
  frontend/src/global_styles/content/_tooltips.lsg
  frontend/src/global_styles/content/_tooltips.sass
Labels: needs review, pullpreview

#8695 [34358] Unclear warning message displayed when filtered value for assignee board does not match any member
  frontend/src/app/modules/boards/board/add-list-modal/add-list-modal.component.ts
  frontend/src/app/modules/boards/board/board-actions/assignee/assignee-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/board-action.service.ts
  modules/boards/config/locales/js-en.yml
Labels: bugfix

#8703 [34514] What's new teaser OpenProject BIM 11.0
  config/locales/js-en.yml
Labels: feature

#8709 [33690] wiki after navigate on item in sidebar, the sidebar reset to top and lose the view of focus item
  app/views/layouts/base.html.erb
  frontend/src/global_styles/layout/_main_menu.sass
Labels: bugfix

#8716 [34544] Ensure search results can be clicked with modifier
  frontend/src/app/modules/global_search/input/global-search-input.component.html
  frontend/src/app/modules/global_search/input/global-search-input.component.sass
  frontend/src/app/modules/global_search/input/global-search-input.component.ts
Labels: bugfix

#8719 [31614] Fix wp attribute columns
  frontend/src/app/components/wp-form-group/wp-attribute-group.component.ts
Labels: bugfix, needs review

#8720 [34132] Extend search autocompleter with useful information
  frontend/src/app/modules/global_search/input/global-search-input.component.sass
Labels: pullpreview

#8722 Fix/34538 default gantt chart query wrong name
  frontend/src/app/components/wp-query-select/wp-static-queries.service.ts
Labels: needs review

#8713 [34535] Override project limiting filter if subproject filter present
  app/models/query.rb
  app/models/query/results.rb
  spec/models/query/results_subproject_filter_integration_spec.rb
  spec/models/query_spec.rb
Labels: bugfix, needs review

#8723 [34490] Don't try to redirect angular route on first load
  frontend/src/app/modules/router/openproject.routes.ts
Labels: bugfix

#8727 Fix: Api vs API (API settings not found on saas)
  app/controllers/settings/api_controller.rb
  config/initializers/zeitwerk.rb
Labels: bugfix, needs review

#8725 [34550] Output board widget errors even if successful copy
  app/services/copy/dependency.rb
  app/services/grids/copy/widgets_dependent_service.rb
  app/services/projects/copy/boards_dependent_service.rb
  app/services/projects/copy/overview_dependent_service.rb
  app/services/service_result.rb
  modules/boards/spec/services/copy_service_integration_spec.rb
  modules/grids/app/models/grids/grid.rb
  modules/grids/config/locales/en.yml
Labels: bugfix

#8715 [34070] Improve board creation modal
  frontend/src/app/modules/boards/board/board-actions/assignee/assignee-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/status/status-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/subproject/subproject-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/subtasks/board-subtasks-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/version/version-action.service.ts
  frontend/src/app/modules/boards/new-board-modal/new-board-modal.component.ts
  frontend/src/app/modules/boards/tile-view/tile-view.component.html
  frontend/src/app/modules/boards/tile-view/tile-view.component.sass
  modules/boards/config/locales/js-en.yml
  modules/boards/spec/features/action_boards/subtasks_board_spec.rb
Labels: feature, pullpreview

#8737 Fix/34511 wrong default settings for gantt chart query
  frontend/src/app/components/wp-query-select/wp-static-queries.service.ts
Labels: needs review

#8744 port documentation added to dev over to release branch
  docs/getting-started/projects/README.md
  docs/user-guide/gantt-chart/README.md
  docs/user-guide/integrations/README.md
  docs/user-guide/projects/README.md
  docs/user-guide/projects/image-20200921153208651.png
  docs/user-guide/projects/project-settings/project-information/README.md
Labels: documentation

#8729 Bim/fix/34493 revit responsive design failing on wp form
  frontend/src/app/modules/work_packages/routing/partitioned-query-space-page/partitioned-query-space-page.component.sass
Labels: needs review

#8739 add generated release notes for 11.0.0
  docs/release-notes/11-0-0/README.md
  docs/release-notes/11-0-0/Top-down-scheduling.gif
  docs/release-notes/11-0-0/boards-creation-modal.png
  docs/release-notes/11-0-0/boards-split-screen.png
  docs/release-notes/11-0-0/openproject-11-0-release-blog.jpg
  docs/release-notes/11-0-0/project-help-texts.png
  docs/release-notes/11-0-0/project-portfolio-management.png
  docs/release-notes/11-0-0/project-templates-creation.png
  docs/release-notes/11-0-0/resize-imagesshort.gif
  docs/release-notes/11-0-0/subproject-boards.png
  docs/release-notes/11-0-0/time-and-costs-module.png
  docs/release-notes/11-0-0/top-down-scheduling.png
  docs/release-notes/11-0-0/wbs-boards.png
  docs/release-notes/README.md
  docs/user-guide/agile-boards/README.md
Labels: documentation, needs review
