Repository opf/openproject, pull requests merged in 2020-08, with the labels that each got.

#8533 [33382] Let mail notifications respect OS dark mode
  app/views/layouts/project_mailer.html.erb
  app/views/layouts/user_mailer.html.erb
Labels: bugfix, needs review

#8527 [33931] Increase modal width
  frontend/src/app/modules/job-status/job-status-modal/job-status.modal.sass
Labels: needs review, styling

#8532 Scrolling previous row working
  frontend/src/app/modules/work_packages/routing/wp-list-view/wp-list-view.component.ts
Labels: needs review

#8525 Bim/feature/33952 show viewpoint when card row clicked
  frontend/src/app/modules/bim/ifc_models/bcf/list-container/bcf-list-container.component.ts
Labels: needs review

#8537 [32817] Disable advanced settings in project template
  app/views/projects/_form.html.erb
  app/views/projects/form/_select_template.html.erb
  frontend/src/app/modules/augmenting/dynamic-scripts/project_form_listener.js
  spec/features/projects/template_spec.rb
Labels: bugfix

#8530 Bim/feature/33941 show wp detail in full view
  frontend/src/app/modules/bim/ifc_models/bcf/list-container/bcf-list-container.component.ts
  frontend/src/app/modules/bim/ifc_models/openproject-ifc-models.routes.ts
  frontend/src/app/modules/bim/ifc_models/pages/viewer/bim-view.service.ts
  frontend/src/app/modules/bim/ifc_models/toolbar/view-toggle/bim-view-toggle-dropdown.directive.ts
  frontend/src/app/modules/work_packages/routing/split-view-routes.template.ts
Labels: needs review

#8529 Bump Angular to 10.0
  frontend/angular.json
  frontend/npm-shrinkwrap.json
  frontend/package.json
  frontend/protractor.conf.js
  frontend/src/app/components/filters/abstract-filter-date-time-value/abstract-filter-date-time-value.controller.ts
  frontend/src/app/components/op-modals/op-modal.component.ts
  frontend/src/app/components/work-packages/work-package-comment/work-package-comment-field-handler.ts
  frontend/src/app/components/wp-buttons/zen-mode-toggle-button/zen-mode-toggle-button.component.ts
  frontend/src/app/helpers/angular/until-destroyed.mixin.ts
  frontend/src/app/init-globals.ts
  frontend/src/app/init-vendors.ts
  frontend/src/app/modules/bim/bcf/api/bcf-api-request.service.ts
  frontend/src/app/modules/bim/bcf/openproject-bcf.module.ts
  frontend/src/app/modules/bim/ifc_models/pages/viewer/styles/tooltips.sass
  frontend/src/app/modules/boards/board/board-filter/board-filter.component.ts
  frontend/src/app/modules/boards/board/board-filter/board-filters.service.ts
  frontend/src/app/modules/boards/board/board-list/board-list-cross-selection.service.ts
  frontend/src/app/modules/calendar/te-calendar/te-calendar.component.sass
  frontend/src/app/modules/calendar/te-calendar/te-calendar.component.ts
  frontend/src/app/modules/calendar/te-calendar/te-calendar.template.html
  frontend/src/app/modules/calendar/wp-calendar/wp-calendar.component.ts
  frontend/src/app/modules/calendar/wp-calendar/wp-calendar.template.html
  frontend/src/app/modules/global_search/input/global-search-input.component.ts
  frontend/src/app/modules/grids/widgets/time-entries/list/time-entries-list.component.ts
  frontend/src/app/modules/hal/helpers/hal-resource-builder.ts
  frontend/src/app/modules/hal/services/hal-resource.service.ts
  frontend/src/app/modules/work_packages/openproject-work-packages.module.ts
  frontend/src/app/modules/work_packages/routing/wp-view-base/view-services/wp-view-hierarchy.service.ts
  frontend/src/global_styles/content/_calendars.sass
  frontend/src/global_styles/content/_forms.sass
  frontend/src/global_styles/content/_forms_mobile.sass
  frontend/src/global_styles/content/_user.sass
  frontend/src/global_styles/content/work_packages/_table_relations.sass
  frontend/src/global_styles/content/work_packages/single_view/_inplace_esque_fields.sass
  frontend/src/main.ts
  frontend/src/tsconfig.app.json
  frontend/src/tsconfig.spec.json
  frontend/src/typings/observable-array.d.ts
  frontend/src/typings/shims.d.ts
  frontend/tsconfig.base.json
  frontend/tsconfig.json
  frontend/tsconfig.test.json
  modules/dashboards/spec/features/work_package_calendar_spec.rb
  modules/my_page/spec/features/my/time_entries_current_user_spec.rb
  package.json
  spec/features/calendars/calendars_spec.rb
Labels: housekeeping

#8504 [33864] Add subproject boards and extract common board action class
  app/models/queries/work_packages.rb
  app/models/queries/work_packages/filter/only_subproject_filter.rb
  app/models/queries/work_packages/filter/subproject_filter.rb
  config/locales/en.yml
  config/locales/js-en.yml
  frontend/src/app/components/wp-edit-form/work-package-filter-values.ts
  frontend/src/app/modules/boards/board/add-list-modal/add-list-modal.component.ts
  frontend/src/app/modules/boards/board/board-actions/assignee/assignee-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/board-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/status/status-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/subproject/subproject-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/subproject/subproject-board-header.component.ts
  frontend/src/app/modules/boards/board/board-actions/subproject/subproject-board-header.html
  frontend/src/app/modules/boards/board/board-actions/subproject/subproject-board-header.sass
  frontend/src/app/modules/boards/board/board-actions/version/version-action.service.ts
  frontend/src/app/modules/boards/board/board-list/board-list.component.ts
  frontend/src/app/modules/boards/board/board-partitioned-page/board-list-container.component.ts
  frontend/src/app/modules/boards/board/board.service.ts
  frontend/src/app/modules/boards/board/query-updated/query-updated.service.ts
  frontend/src/app/modules/boards/board/toolbar-menu/boards-toolbar-menu.directive.ts
  frontend/src/app/modules/boards/boards-root/boards-root.component.ts
  frontend/src/app/modules/boards/openproject-boards.module.ts
  lib/api/v3/queries/schemas/only_subproject_filter_dependency_representer.rb
  modules/boards/config/locales/js-en.yml
  modules/boards/spec/features/action_boards/subproject_board_spec.rb
  modules/boards/spec/features/support/board_page.rb
Labels: feature, needs review

#8542 Fix filtered() on work-packages paths to resolve to correct type
  frontend/src/app/modules/apiv3/endpoints/work_packages/api-v3-work-package-cached-subresource.ts
  frontend/src/app/modules/apiv3/endpoints/work_packages/api-v3-work-packages-paths.ts
Labels: housekeeping

#8544 Emitting stateLinkClicked events from cards
  frontend/src/app/components/modals/preview-modal/wp-preview-modal/wp-preview.modal.html
  frontend/src/app/components/modals/preview-modal/wp-preview-modal/wp-preview.modal.ts
  frontend/src/app/components/wp-card-view/wp-card-view.component.html
  frontend/src/app/components/wp-card-view/wp-single-card/wp-single-card.component.html
  frontend/src/app/components/wp-card-view/wp-single-card/wp-single-card.component.ts
  frontend/src/app/modules/bim/ifc_models/bcf/list-container/bcf-list-container.component.ts
  frontend/src/app/modules/boards/board/board-list/board-list.component.html
  frontend/src/app/modules/boards/board/board-list/board-list.component.ts
Labels: needs review

#8535 [32111]Work package no longer included in filter "Estimated time: none" when removing value for Estimated time
  app/models/queries/work_packages/filter/estimated_hours_filter.rb
  spec/models/queries/work_packages/filter/estimated_hours_filter_spec.rb
Labels: bugfix

#8539 [24343] Allow PDFs to be served inline
  app/models/attachment.rb
Labels: feature

#8551 set correct host name in pull preview instances
  docker-compose.pullpreview.yml
Labels: pullpreview

#8524 Change the new board modal to be selected in tile mode in collaboration with task number [33864]
  frontend/src/app/modules/boards/board/board-actions/assignee/assignee-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/board-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/board-actions-registry.service.ts
  frontend/src/app/modules/boards/board/board-actions/status/status-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/subproject/subproject-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/version/version-action.service.ts
  frontend/src/app/modules/boards/new-board-modal/new-board-modal.component.ts
  frontend/src/app/modules/boards/new-board-modal/new-board-modal.html
  frontend/src/app/modules/boards/openproject-boards.module.ts
  frontend/src/app/modules/boards/tile-view/tile-view.component.html
  frontend/src/app/modules/boards/tile-view/tile-view.component.sass
  frontend/src/app/modules/boards/tile-view/tile-view.component.spec.ts
  frontend/src/app/modules/boards/tile-view/tile-view.component.ts
  modules/boards/config/locales/js-en.yml
  modules/boards/spec/features/action_boards/subproject_board_spec.rb
  modules/boards/spec/features/support/board_index_page.rb
Labels: feature, pullpreview, work in progress

#8528 [33910] Move reporting styles to 'global_styles' folder
  modules/reporting/app/controllers/cost_reports_controller.rb
Labels: bugfix, needs review

#8552 [33443 Integrate plugin specs / features into common group
  .travis.yml
  lib/tasks/parallel_testing.rake
Labels: housekeeping

#8558 Show server error message when uploaded file is too big
  frontend/src/app/components/api/op-file-upload/op-direct-file-upload.service.ts
Labels: needs review

#8546 [33865] Subtasks board
  config/locales/js-en.yml
  frontend/src/app/components/api/api-v3/api-v3-filter-builder.ts
  frontend/src/app/helpers/rxjs/debounced-input-switchmap.ts
  frontend/src/app/modules/boards/board/add-list-modal/add-list-modal.component.ts
  frontend/src/app/modules/boards/board/add-list-modal/add-list-modal.html
  frontend/src/app/modules/boards/board/board-actions/assignee/assignee-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/board-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/cached-board-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/status/status-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/subproject/subproject-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/subtasks/board-subtasks-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/subtasks/subtasks-board-header.component.ts
  frontend/src/app/modules/boards/board/board-actions/subtasks/subtasks-board-header.html
  frontend/src/app/modules/boards/board/board-actions/subtasks/subtasks-board-header.sass
  frontend/src/app/modules/boards/board/board-actions/version/version-action.service.ts
  frontend/src/app/modules/boards/board/board-list/board-list.component.ts
  frontend/src/app/modules/boards/board/board-partitioned-page/board-list-container.component.ts
  frontend/src/app/modules/boards/boards-root/boards-root.component.ts
  frontend/src/app/modules/boards/openproject-boards.module.ts
  frontend/src/app/modules/common/autocomplete/create-autocompleter.component.html
  modules/boards/config/locales/js-en.yml
  modules/boards/spec/features/action_boards/subproject_board_spec.rb
  modules/boards/spec/features/action_boards/subtasks_board_spec.rb
  modules/boards/spec/features/support/board_index_page.rb
Labels: feature, needs review, pullpreview

#8565 [33911] Fix unnecessary scrollbars of wp graph widgets
  frontend/src/app/modules/grids/widgets/wp-graph/wp-graph.component.html
  frontend/src/app/modules/grids/widgets/wp-overview/wp-overview.component.html
Labels: bugfix, needs review, styling

#8564 [33936] Problem with watchers
  lib/api/v3/work_packages/watchers_api.rb
  spec/requests/api/v3/watcher_resource_spec.rb
Labels: bugfix

#8549 Resizer hidden on full width
  frontend/src/app/modules/work_packages/routing/partitioned-query-space-page/partitioned-query-space-page.component.sass
Labels: needs review

#8563 cache types in postgres adapter
  config/initializers/postgres_type_cache.rb
Labels: feature, needs review, performance

#8522 [31614] Prevent wp attribute fields from repositioning
  frontend/src/app/components/wp-form-group/wp-attribute-group.component.ts
  frontend/src/global_styles/content/_attributes_key_value.sass
  frontend/src/global_styles/openproject/_mixins.sass
Labels: bugfix, needs review

#8534 Hiding 'Manage models' button on plugins (Revit)
  frontend/src/app/modules/bim/ifc_models/pages/viewer/ifc-viewer-page.component.ts
  modules/bim/spec/features/bim_revit_add_in_navigation_spec.rb
  modules/bim/spec/support/pages/ifc_models/show_default.rb
Labels: needs review

#8575 [34048] Can not delete work package attribute delete by inline editing in work package table
  frontend/src/app/modules/fields/edit/field-types/duration-edit-field.component.ts
Labels: bugfix

#8567 [33982] Fix broken checklists in ckeditor tables
  frontend/src/global_styles/content/editor/_markdown.sass
Labels: bugfix, needs review, styling

#8553 Unified docker image for BIM edition. Add hooks for Cloud platform
  .dockerignore
  .github/workflows/docker.yml
  Dockerfile
  docker/entrypoint.sh
  docker/precompile-assets.sh
  docker/setup/postinstall.sh
  docker/setup/preinstall-on-prem.sh
  docker/setup/preinstall.sh
  docker/supervisord
Labels: pullpreview, work in progress

#8572 [33074] Add unassigned value for the assignee action board
  frontend/src/app/components/wp-edit-form/work-package-filter-values.ts
  frontend/src/app/modules/boards/board/board-actions/assignee/assignee-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/assignee/assignee-board-header.html
  frontend/src/app/modules/boards/board/board-actions/board-action.service.ts
  frontend/src/app/modules/boards/board/board-partitioned-page/board-list-container.component.ts
  modules/boards/spec/features/action_boards/assignee_board_spec.rb
Labels: feature, needs review

#8577 allow omni-auth user to switch to password on reinvitation
  app/controllers/concerns/user_invitation.rb
Labels: bugfix, needs review

#8583 [34001] Ensure filters always receive the query context
  app/models/query.rb
  app/services/queries/copy_service.rb
  app/workers/work_packages/exports/export_job.rb
  lib/api/v3/work_packages/schema/form_configurations/query_representer.rb
Labels: bugfix

#8578 [33648] Add value macros for referencing label and values of project and work packages
  config/locales/js-en.yml
  docs/user-guide/wysiwyg/README.md
  frontend/src/app/components/wp-fast-table/builders/cell-builder.ts
  frontend/src/app/components/wp-fast-table/builders/modes/grouped/grouped-render-pass.ts
  frontend/src/app/components/wp-fast-table/handlers/cell/edit-cell-handler.ts
  frontend/src/app/components/wp-fast-table/handlers/row/click-handler.ts
  frontend/src/app/components/wp-fast-table/handlers/row/double-click-handler.ts
  frontend/src/app/components/wp-table/timeline/cells/timeline-cell-renderer.ts
  frontend/src/app/global-dynamic-components.const.ts
  frontend/src/app/helpers/string-helpers.ts
  frontend/src/app/modules/apiv3/cache/cachable-apiv3-resource.ts
  frontend/src/app/modules/apiv3/endpoints/work_packages/api-v3-work-package-cached-subresource.ts
  frontend/src/app/modules/apiv3/endpoints/work_packages/api-v3-work-packages-paths.ts
  frontend/src/app/modules/common/openproject-common.module.ts
  frontend/src/app/modules/fields/display/display-field-renderer.ts
  frontend/src/app/modules/fields/display/display-field.component.ts
  frontend/src/app/modules/fields/display/display-field.service.ts
  frontend/src/app/modules/fields/display/field-types/combined-date-display.field.ts
  frontend/src/app/modules/fields/display/field-types/project-status-display-field.module.ts
  frontend/src/app/modules/fields/display/field-types/wp-spent-time-display-field.module.ts
  frontend/src/app/modules/fields/edit/field/editable-attribute-field.component.ts
  frontend/src/app/modules/fields/field.base.ts
  frontend/src/app/modules/fields/help-texts/attribute-help-text.component.html
  frontend/src/app/modules/fields/help-texts/attribute-help-text.component.ts
  frontend/src/app/modules/fields/help-texts/attribute-help-text.modal.ts
  frontend/src/app/modules/fields/help-texts/attribute-help-text.service.ts
  frontend/src/app/modules/fields/help-texts/help-text.modal.html
  frontend/src/app/modules/fields/macros/attribute-label-macro.component.ts
  frontend/src/app/modules/fields/macros/attribute-label-macro.html
  frontend/src/app/modules/fields/macros/attribute-macro.sass
  frontend/src/app/modules/fields/macros/attribute-model-loader.service.ts
  frontend/src/app/modules/fields/macros/attribute-value-macro.component.ts
  frontend/src/app/modules/fields/macros/attribute-value-macro.html
  frontend/src/app/modules/fields/macros/work-package-quickinfo-macro.component.ts
  frontend/src/app/modules/fields/macros/work-package-quickinfo-macro.html
  frontend/src/app/modules/fields/macros/work-package-quickinfo-macro.sass
  frontend/src/app/modules/fields/openproject-fields.module.ts
  frontend/src/app/modules/grids/widgets/custom-text/custom-text.component.ts
  frontend/src/app/modules/hal/resources/schema-resource.ts
  frontend/src/app/modules/plugins/plugin-context.ts
  frontend/src/app/modules/work_packages/openproject-work-packages.module.ts
  frontend/src/global_styles/openproject/_mixins.sass
  lib/open_project/text_formatting/filters/pattern_matcher_filter.rb
  lib/open_project/text_formatting/matchers/attribute_macros.rb
  lib/open_project/text_formatting/matchers/link_handlers/work_packages.rb
  spec/features/wysiwyg/macros/attribute_macros_spec.rb
  spec/features/wysiwyg/macros/quicklink_macros_spec.rb
  spec/lib/open_project/text_formatting/markdown/attribute_macros_spec.rb
  spec/lib/open_project/text_formatting/markdown/markdown_spec.rb
  spec/requests/api/v3/work_package_resource_spec.rb
Labels: feature, needs review

#8560 Translucent rows on table/gantt charts
  frontend/src/global_styles/layout/work_packages/_table.sass
Labels: needs review

#8554 [30242] Extend work package autocompleter with more useful information
  frontend/src/app/modules/global_search/input/global-search-input.component.html
  frontend/src/app/modules/global_search/input/global-search-input.component.sass
  frontend/src/app/modules/global_search/input/global-search-input.component.ts
  spec/features/search_spec.rb
  spec/support/components/global_search.rb
Labels: feature, pullpreview

#8590 Don't try to load invited mail avatars
  frontend/src/app/modules/common/autocomplete/user-autocompleter.component.html
  frontend/src/app/modules/members/members-autocompleter.component.ts
Labels: housekeeping

#8593 [34071] Improve the labels in the board add-list modal
  frontend/src/app/modules/boards/board/add-list-modal/add-list-modal.html
  frontend/src/app/modules/boards/board/board-actions/assignee/assignee-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/board-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/status/status-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/subproject/subproject-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/subtasks/board-subtasks-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/version/version-action.service.ts
  modules/boards/config/locales/js-en.yml
Labels: feature

#8602 Avoid disabled hidden inputs that generates the not focusable error
  modules/costs/app/views/cost_types/_rate.html.erb
Labels: needs review

#8569 Show children duration clamp on gantt charts
  config/locales/js-en.yml
  frontend/src/app/components/wp-fast-table/builders/modes/hierarchy/hierarchy-render-pass.ts
  frontend/src/app/components/wp-fast-table/handlers/state/hierarchy-transformer.ts
  frontend/src/app/components/wp-table/timeline/cells/timeline-cell-renderer.ts
  frontend/src/app/components/wp-table/wp-table-hover-sync.ts
  frontend/src/global_styles/content/work_packages/timelines/_timelines.sass
  frontend/src/global_styles/content/work_packages/timelines/elements/_bar.sass
  frontend/src/global_styles/layout/work_packages/_table.sass
  frontend/src/global_styles/openproject/_variables.scss
Labels: needs review, pullpreview

#8604 Refactor project list into cell
  app/cells/projects/row_cell.rb
  app/cells/projects/table_cell.rb
  app/cells/rails_cell.rb
  app/cells/row_cell.rb
  app/cells/table_cell.rb
  app/cells/views/projects/row/show.erb
  app/cells/views/projects/table/show.erb
  app/controllers/projects_controller.rb
  app/helpers/projects_helper.rb
  app/views/projects/_hierarchy_header.html.erb
  app/views/projects/index.html.erb
  app/views/settings/_projects.html.erb
  config/locales/en.yml
Labels: housekeeping

#8579 [33882] Fine tuning of datepicker
  frontend/src/app/components/datepicker/datepicker.modal.html
  frontend/src/app/components/datepicker/datepicker.modal.sass
  frontend/src/global_styles/content/_datepicker.sass
Labels: feature, needs review, pullpreview, styling

#8586 [34002] Show errors in the job modal instead of automatically redirecting
  app/services/base_services/copy.rb
  app/services/copy/dependency.rb
  app/services/projects/copy/boards_dependent_service.rb
  app/services/projects/copy/categories_dependent_service.rb
  app/services/projects/copy/forums_dependent_service.rb
  app/services/projects/copy/members_dependent_service.rb
  app/services/projects/copy/queries_dependent_service.rb
  app/services/projects/copy/versions_dependent_service.rb
  app/services/projects/copy/wiki_dependent_service.rb
  app/services/projects/copy/work_packages_dependent_service.rb
  app/services/service_result.rb
  app/workers/copy_project_job.rb
  config/locales/en.yml
  frontend/src/app/modules/job-status/job-status-modal/job-status.modal.html
  frontend/src/app/modules/job-status/job-status-modal/job-status.modal.sass
  frontend/src/app/modules/job-status/job-status-modal/job-status.modal.ts
  modules/job_status/config/locales/js-en.yml
  modules/job_status/spec/factories/delayed_job_status_factory.rb
  modules/job_status/spec/features/job_status_spec.rb
Labels: bugfix, feature, needs review

#8600 Allow template to set the default advanced settings once selected
  app/controllers/projects_controller.rb
  app/services/projects/copy_service.rb
  app/views/projects/form/_select_template.html.erb
  config/locales/js-en.yml
  frontend/src/app/globals/global-listeners/toggable-fieldset.ts
  frontend/src/app/modules/augmenting/dynamic-scripts/project_form_listener.js
  spec/features/projects/template_spec.rb
Labels: feature, needs review

#8599 Show only manual scheduling icon and only on the start date
  frontend/src/app/modules/fields/display/field-types/date-display-field.module.ts
  frontend/src/global_styles/content/_table.sass
  frontend/src/global_styles/content/work_packages/inplace_editing/_display_fields.sass
Labels: needs review, pullpreview
