Repository opf/openproject, pull requests merged in 2020-10, with the labels that each got.

#8748 Sums and group rows color swap, but not in table footer
  frontend/src/global_styles/content/work_packages/_table_content.sass
Labels: work in progress

#8747 Fix/34710 allow schedule manual parent wp on gantt chart
  frontend/src/app/components/wp-table/timeline/cells/wp-timeline-cell-mouse-handler.ts
Labels: needs review

#8714 New demo seed data featuring scheduling mode
  app/seeders/demo_data/attribute_help_text_seeder.rb
  app/seeders/demo_data/custom_field_seeder.rb
  app/seeders/demo_data/global_query_seeder.rb
  app/seeders/demo_data/group_seeder.rb
  app/seeders/demo_data/wiki_seeder.rb
  app/seeders/demo_data/work_package_board_seeder.rb
  app/seeders/demo_data/work_package_seeder.rb
  app/seeders/development_data/custom_fields_seeder.rb
  app/seeders/random_data/forum_seeder.rb
  app/seeders/random_data/news_seeder.rb
  app/seeders/random_data/wiki_seeder.rb
  app/seeders/random_data/work_package_seeder.rb
  app/seeders/seeder.rb
  app/seeders/standard_seeder/basic_data/type_seeder.rb
  config/locales/en.seeders.standard.yml
  config/locales/js-en.yml
  config/settings.yml
  modules/bim/app/seeders/bim/demo_data/bcf_xml_seeder.rb
  modules/bim/app/seeders/bim/demo_data/ifc_model_seeder.rb
  modules/bim/lib/open_project/bim/patches/work_package_board_seeder_patch.rb
  modules/overviews/config/locales/en.seeders.standard.yml
  spec/seeders/demo_data_seeder_spec.rb
Labels: pullpreview

#8738 Correct width calculation on cells with user picture
  frontend/src/global_styles/content/modules/_avatars.sass
Labels: needs review

#8743 [34712] Menu too small/completely hidden on Roadmap
  app/views/layouts/base.html.erb
  frontend/src/global_styles/layout/_main_menu.sass
Labels: bugfix, pullpreview

#8746 Correct arrow back selected + styles improvements
  frontend/src/app/globals/onboarding/tours/boards_tour.ts
  frontend/src/app/globals/onboarding/tours/work_package_tour.ts
Labels: needs review

#8755 [34590] Year almost hidden in date picker for version
  frontend/src/global_styles/content/_datepicker.sass
Labels: bugfix

#8766 Fix/25683 warning when data will be discarded rebased
  frontend/src/app/globals/global-listeners.ts
  frontend/src/app/globals/openproject.ts
  frontend/src/app/modules/fields/edit/edit-form/edit-form.component.ts
  frontend/src/app/modules/fields/edit/services/global-edit-form-changes-tracker/global-edit-form-changes-tracker.service.spec.ts
  frontend/src/app/modules/fields/edit/services/global-edit-form-changes-tracker/global-edit-form-changes-tracker.service.ts
Labels: needs review

#8741 [34355] EE: Trial creation modal changes size when error is shown
  frontend/src/app/components/enterprise/enterprise-modal/enterprise-trial-form/ee-trial-form.component.html
  frontend/src/app/components/enterprise/enterprise-modal/enterprise-trial-form/ee-trial-form.component.sass
  frontend/src/app/components/enterprise/enterprise-modal/enterprise-trial-form/ee-trial-form.component.ts
Labels: bugfix

#8742 [34584] Deleted work packages don't disappear in boards view
  frontend/src/app/modules/common/back-routing/back-routing.service.ts
Labels: bugfix

#8736 Fix/34126 gantt chart row styles conflict between active and hovered
  frontend/src/app/modules/global_search/input/global-search-input.component.html
  frontend/src/global_styles/layout/work_packages/_table.sass
Labels: needs review, pullpreview

#8762 Updated local development docker setup
  .gitignore
  bin/compose
  docker/dev/Dockerfile.dev
  docker/dev/backend/Dockerfile
  docker/dev/backend/scripts/run-app
  docker/dev/backend/scripts/setup
  docker/dev/compose.yml
  docker/dev/frontend/Dockerfile
  docker/dev/scripts/backend
  docker/dev/scripts/frontend
  docker/dev/scripts/seeder
  docs/development/development-environment-docker/README.md
  frontend/package.json
  frontend/scripts/link_plugin_placeholder.js
Labels: docker

#8787 [34842] Error message when copying boards not scrollable
  frontend/src/app/modules/job-status/job-status-modal/job-status.modal.html
  frontend/src/app/modules/job-status/job-status-modal/job-status.modal.sass
Labels: bugfix

#8531 Add support for BIM edition selection in packages
  .pkgr.yml
  docs/installation-and-operations/installation/packaged/README.md
  docs/installation-and-operations/installation/packaged/select-edition.png
Labels: packager

#8802 re-run postgres index fix migration if necessary during budgets migration
  modules/budgets/db/migrate/20200810152654_rename_cost_object_to_budget.rb
Labels: needs review

#8771 Firefox fix for aligning table and Gantt chart rows
  frontend/src/global_styles/content/work_packages/timelines/_timelines.sass
  frontend/src/global_styles/layout/work_packages/_table.sass
Labels: needs review

#8782 FlatPickr Firefox quirks fixed
  frontend/src/app/modules/common/op-date-picker/datepicker.ts
Labels: needs review
