Repository opf/openproject, pull requests merged in 2020-04, with the labels that each got.

#8239 [32853] Disable drag'n'drop of cards in BCF module
  frontend/src/app/modules/bim/ifc_models/bcf/list-container/bcf-list-container.component.ts
Labels: bugfix, needs review

#8241 [32848] Add BCF features to "Getting started" block in seed data
  modules/overviews/config/locales/en.seeders.bim.yml
Labels: feature

#8240 Remove access keys in application
  app/controllers/help_controller.rb
  app/views/help/_keyboard_shortcut_table.erb
  app/views/help/keyboard_shortcuts.erb
  app/views/layouts/help.html.erb
  config/locales/en.yml
  frontend/src/app/modules/a11y/keyboard-shortcut-service.ts
  lib/redmine/menu_manager/top_menu/help_menu.rb
  spec/features/accessibility/work_packages/work_package_query_spec.rb
Labels: housekeeping

#8235 [32822] Fix parsing budget with non-english locale
  Gemfile
  Gemfile.lock
  modules/costs/app/helpers/costs/number_helper.rb
  modules/costs/app/views/cost_objects/items/_labor_budget_item.html.erb
  modules/costs/app/views/cost_objects/items/_material_budget_item.html.erb
  modules/costs/frontend/module/augment/planned-costs-form.ts
  modules/costs/spec/features/budgets/update_budget_spec.rb
  modules/costs/spec/support/pages/budget_form.rb
Labels: bugfix, needs review

#8242 [32852] Use the baseRoute in redirecting back from destroy modal
  frontend/src/app/components/modals/wp-destroy-modal/wp-destroy.modal.ts
Labels: bugfix

#8225 [26684] Redirect to WP from search only with #ID match on enter
  app/controllers/search_controller.rb
  frontend/src/app/modules/global_search/input/global-search-input.component.html
  frontend/src/app/modules/global_search/input/global-search-input.component.sass
  frontend/src/app/modules/global_search/input/global-search-input.component.ts
  spec/controllers/search_controller_spec.rb
  spec/features/search_spec.rb
  spec/support/components/global_search.rb
Labels: bugfix, needs review

#8246 [32782] Update the project description onboarding texts and activate the project description in the demo projects
  config/locales/en.seeders.standard.yml
  modules/bim/config/locales/en.seeders.bim.yml
  modules/overviews/config/locales/en.seeders.bim.yml
  modules/overviews/config/locales/en.seeders.standard.yml
Labels: needs review

#8244 [32870] Don't set cache headers for own avatar
  modules/avatars/lib/api/v3/users/user_avatar_api.rb
Labels: bugfix

#8248 [31298] Missing warning message when reopening agenda
  modules/meeting/app/helpers/meeting_contents_helper.rb
  modules/meeting/config/locales/en.yml
  modules/meeting/spec/features/meetings_close_spec.rb
Labels: bugfix, needs review

#8257 Fix bcf viewpoint create spec
  modules/bim/spec/features/bcf/create_spec.rb
  modules/bim/spec/support/pages/bcf/create_split.rb
Labels: housekeeping, needs review

#8255 Ensure we reload values in select field when changeset updates
  frontend/src/app/components/wp-edit/work-package-changeset.ts
  frontend/src/app/modules/fields/edit/field-types/select-edit-field.component.ts
  frontend/src/app/modules/fields/edit/services/hal-resource-editing.service.ts
  spec/features/work_packages/new/new_work_package_spec.rb
Labels: bugfix, needs review

#8264 [32983] Ensure wp-embedded-table-entry does not get bootstrapped twice
  frontend/src/app/components/wp-table/embedded/embedded-tables-macro.component.ts
  frontend/src/app/components/wp-table/embedded/wp-embedded-base.component.ts
  frontend/src/app/components/wp-table/embedded/wp-embedded-table.html
  frontend/src/app/global-dynamic-components.const.ts
  spec/features/wysiwyg/macros/embedded_tables_spec.rb
Labels: bugfix

#8268 [32825] Cache external URLs for at max 604799 seconds …
  lib/api/v3/attachments/attachments_api.rb
  spec/requests/api/v3/attachments/attachment_resource_shared_examples.rb
Labels: bugfix

#8269 [32908] Styling changes to the confirm-dialog modal
  frontend/src/app/components/modals/confirm-dialog/confirm-dialog.modal.html
  frontend/src/app/components/modals/confirm-dialog/confirm-dialog.modal.sass
  frontend/src/app/components/modals/confirm-dialog/confirm-dialog.modal.ts
Labels: bugfix, styling

#8270 [30157] Add action assignee board
  frontend/src/app/modules/boards/board/board-actions/assignee/assignee-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/assignee/assignee-board-header.component.ts
  frontend/src/app/modules/boards/board/board-actions/assignee/assignee-board-header.html
  frontend/src/app/modules/boards/board/board-actions/assignee/assignee-board-header.sass
  frontend/src/app/modules/boards/boards-root/boards-root.component.ts
  frontend/src/app/modules/boards/openproject-boards.module.ts
  modules/boards/spec/features/action_boards/assignee_board_spec.rb
  modules/boards/spec/features/support/board_index_page.rb
Labels: feature

#8267 [32911] EE Trial: Use previously entered form data
  frontend/src/app/components/enterprise/enterprise-active-trial/ee-active-trial.component.html
  frontend/src/app/components/enterprise/enterprise-active-trial/ee-active-trial.component.ts
  frontend/src/app/components/enterprise/enterprise-modal/enterprise-trial-form/ee-trial-form.component.ts
  frontend/src/app/components/enterprise/enterprise-trial.service.ts
Labels: feature

#8256 Fix xeokit keyboard inputs and show icon when viewer has focus
  app/assets/fonts/openproject_icon/openproject-icon-font.svg
  app/assets/fonts/openproject_icon/openproject-icon-font.ttf
  app/assets/fonts/openproject_icon/openproject-icon-font.woff
  app/assets/fonts/openproject_icon/openproject-icon-font.woff2
  app/assets/stylesheets/fonts/_openproject_icon_definitions.scss
  app/assets/stylesheets/fonts/_openproject_icon_font.lsg
  frontend/npm-shrinkwrap.json
  frontend/src/app/modules/bim/ifc_models/ifc-viewer/ifc-viewer.component.html
  frontend/src/app/modules/bim/ifc_models/ifc-viewer/ifc-viewer.component.sass
  frontend/src/app/modules/bim/ifc_models/ifc-viewer/ifc-viewer.component.ts
  frontend/src/app/modules/bim/ifc_models/ifc-viewer/ifc-viewer.service.ts
  modules/bim/app/assets/stylesheets/bim/ifc_viewer/generic.sass
  modules/bim/config/locales/js-en.yml
  vendor/openproject-icon-font/src/input-disabled.svg
Labels: feature

#8278 Correctly load groups trough hrefs
  frontend/src/app/modules/boards/board/board-actions/assignee/assignee-action.service.ts
  frontend/src/app/modules/hal/resources/group-resource.ts
  frontend/src/app/modules/hal/services/hal-resource.config.ts
  modules/boards/spec/features/action_boards/assignee_board_spec.rb
  modules/boards/spec/features/support/board_index_page.rb
Labels: bugfix, needs review

#8279 Update LSG to widget header classes
  app/assets/stylesheets/content/_widget_box.lsg
  modules/documents/app/views/my/blocks/_documents.html.erb
  modules/documents/app/views/my_projects_overviews/blocks/_documents.html.erb
Labels: housekeeping, styling

#8283 [33087] Wait until the token was saved to the backend before reloading
  frontend/src/app/components/enterprise/enterprise-trial.service.ts
Labels: bugfix, needs review

#8282 [33083] Fix localized links
  frontend/src/app/components/enterprise/enterprise-modal/enterprise-trial-form/ee-trial-form.component.ts
  frontend/src/app/helpers/i18n/localized-link.ts
Labels: bugfix

#8290 Highlight correct error field in EE trial form
  config/locales/js-en.yml
  frontend/src/app/components/enterprise/enterprise-modal/enterprise-trial-form/ee-trial-form.component.html
  frontend/src/app/components/enterprise/enterprise-modal/enterprise-trial-form/ee-trial-form.component.ts
  frontend/src/app/components/enterprise/enterprise-modal/enterprise-trial.modal.ts
  frontend/src/app/components/enterprise/enterprise-trial.service.ts
  spec/features/admin/enterprise/enterprise_trial_spec.rb
Labels: bugfix

#8294 What's new teaser for release 10.5
  app/assets/images/new_feature_teaser.jpg
  config/locales/js-en.yml
  frontend/src/app/components/homescreen/blocks/new-features.component.ts
  frontend/src/app/modules/bim/bcf/bcf-constants.const.ts
  modules/bim/app/assets/images/bim/new_feature_teaser.jpg
Labels: needs review

#8296 [33111] Always assign query_props to change persisted queries
  app/models/work_package/pdf_export/common.rb
  app/services/work_packages/exports/schedule_service.rb
  app/workers/work_packages/exports/export_job.rb
  modules/bim/spec/workers/work_packages/exports/export_job_spec.rb
  spec/workers/work_packages/exports/export_job_spec.rb
Labels: bugfix, needs review

#8291 Improve design of EE page
  app/assets/stylesheets/content/_enterprise.sass
  app/views/enterprises/_info.html.erb
  app/views/homescreen/blocks/_upsale.html.erb
  frontend/src/app/components/enterprise/enterprise-base.component.html
  frontend/src/app/components/enterprise/enterprise-base.component.ts
Labels: styling

#8298 [33115] Escape uriComponent in members autocompleter
  frontend/src/app/modules/members/members-autocompleter.component.ts
Labels: bugfix, needs review

#8292 Test new pullpreview action
  .github/workflows/pullpreview.yml
  docker-compose.pullpreview.yml
Labels: pullpreview

#8304 [33127] Work package template text form is too small
  app/assets/stylesheets/content/editor/_ckeditor.sass
  app/views/types/form/_settings.html.erb
Labels: bugfix, styling

#8305 Test conditional boot under BIM edition
  .github/workflows/pullpreview.yml
Labels: pullpreview

#8318 Change position of create button for Attribute Help Text page
  app/views/attribute_help_texts/index.html.erb
Labels: housekeeping, styling

#8306 [32129] Add icon "Log time" close to spent time attribute in work packages details view
  config/locales/js-en.yml
  frontend/src/app/modules/fields/display/field-types/wp-spent-time-display-field.module.ts
  frontend/src/app/modules/time_entries/create/create.service.ts
  frontend/src/app/modules/time_entries/form/form.component.html
  frontend/src/app/modules/time_entries/form/form.component.ts
  frontend/src/app/modules/time_entries/shared/modal/base.modal.html
  frontend/src/app/modules/time_entries/shared/modal/base.modal.ts
  frontend/src/app/modules/work_packages/query-space/wp-isolated-query-space.directive.ts
  modules/my_page/spec/features/my/time_entries_current_user_spec.rb
  spec/features/support/components/time_logging_modal.rb
  spec/features/work_packages/spent_time_display_spec.rb
  spec/support/edit_fields/spent_time_edit_field.rb
Labels: feature, needs review, pullpreview

#8320 Show modal when logging time via the context menu of a WP view
  frontend/src/app/components/op-context-menu/wp-context-menu/wp-single-context-menu.ts
  frontend/src/app/components/op-context-menu/wp-context-menu/wp-view-context-menu.directive.ts
  spec/features/work_packages/spent_time_display_spec.rb
  spec/features/work_packages/table/context_menu_spec.rb
Labels: housekeeping

#8321 Bump ngSelect to version 4.0.0
  frontend/npm-shrinkwrap.json
  frontend/package.json
Labels: housekeeping

#8322 [33193] Missing translation for default assignee board name
  frontend/src/app/modules/boards/board/board.service.ts
  frontend/src/app/modules/boards/index-page/boards-index-page.component.ts
  modules/boards/config/locales/js-en.yml
Labels: bugfix, needs review

#8331 [33144] Wiki CKEditor5 toolbar no longer sticky
  app/assets/stylesheets/content/_wiki.sass
Labels: bugfix, styling
