Repository opf/openproject, pull requests merged in 2020-05, with the labels that each got.

#8325 [33073] Add notification message to board when there are no options to add
  frontend/src/app/modules/boards/board/add-list-modal/add-list-modal.component.ts
  frontend/src/app/modules/boards/board/add-list-modal/add-list-modal.html
  frontend/src/app/modules/boards/board/board-actions/assignee/assignee-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/board-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/status/status-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/version/version-action.service.ts
  modules/boards/config/locales/js-en.yml
  modules/boards/spec/features/action_boards/assignee_board_spec.rb
  modules/boards/spec/features/support/board_page.rb
Labels: feature, needs review

#8335 [33185] Number vanishes in time logging widget
  frontend/src/app/modules/fields/edit/field-types/duration-edit-field.component.ts
Labels: bugfix, needs review

#8344 [32126] Use time logging widget on project overview page
  frontend/src/app/modules/common/path-helper/path-helper.service.ts
  frontend/src/app/modules/grids/openproject-grids.module.ts
  frontend/src/app/modules/grids/widgets/time-entries/list/time-entries-list.component.html
  frontend/src/app/modules/grids/widgets/time-entries/list/time-entries-list.component.ts
  frontend/src/app/modules/grids/widgets/time-entries/project/time-entries-project.component.ts
  frontend/src/app/modules/time_entries/openproject-time-entries.module.ts
Labels: feature, needs review

#8334 [32926]Improve styling for the news widget
  app/assets/stylesheets/content/_news.sass
  app/assets/stylesheets/content/_widget_box.sass
  app/assets/stylesheets/content/work_packages/tabs/_activities.sass
  app/helpers/application_helper.rb
  app/views/homescreen/blocks/_news.html.erb
  config/locales/js-en.yml
  frontend/src/app/modules/grids/widgets/news/news.component.html
  frontend/src/app/modules/grids/widgets/news/news.component.ts
Labels: feature, styling

#8351 Avoid requesting the form more than once per changeset instance
  frontend/src/app/components/time-entries/time-entry-changeset.ts
  frontend/src/app/components/wp-edit/work-package-changeset.ts
  frontend/src/app/modules/fields/changeset/resource-changeset.ts
  frontend/src/app/modules/fields/edit/edit-form/edit-form.ts
  frontend/src/app/modules/fields/edit/services/hal-resource-editing.service.ts
  frontend/src/app/modules/work_packages/routing/wp-full-view/wp-full-view.component.ts
  spec/features/work_packages/details/custom_fields/custom_field_spec.rb
  spec/features/work_packages/table/edit_work_packages_spec.rb
Labels: bugfix, needs review

#8338 [31556]Show Project name in Card View
  frontend/src/app/components/wp-card-view/wp-single-card/wp-single-card.component.html
  frontend/src/app/components/wp-card-view/wp-single-card/wp-single-card.component.sass
  frontend/src/app/components/wp-card-view/wp-single-card/wp-single-card.component.ts
Labels: feature

#8355 [33124]Missing space below user rate history
  app/assets/stylesheets/content/_user.sass
  modules/costs/app/views/hourly_rates/_list_default.html.erb
  modules/costs/app/views/hourly_rates/_list_project.html.erb
Labels: bugfix

#8356 [33119]The onboarding tour does not start when closing the language modal via Escape
  app/assets/javascripts/onboarding/onboarding_tour.js
Labels: bugfix

#8340 [33123] Fix: Unnecessary resizer and scrollbar shown on BIM page
  frontend/src/app/modules/bim/ifc_models/bcf/list-container/bcf-list-container.component.ts
  frontend/src/app/modules/bim/ifc_models/ifc-viewer/ifc-viewer.component.sass
  frontend/src/app/modules/work_packages/routing/wp-list-view/wp-list-view.component.ts
Labels: bugfix, needs review

#8362 Avoid creating many changesets by checking for resource equality
  frontend/src/app/components/wp-new/wp-create.component.ts
  frontend/src/app/modules/fields/edit/services/hal-resource-editing.service.ts
Labels: bugfix

#8357 Allow an optional auth_source_sso flag
  app/controllers/account_controller.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/accounts/current_user.rb
  app/controllers/concerns/auth_source_sso.rb
  app/services/users/login_service.rb
  app/services/users/logout_service.rb
  docs/installation-and-operations/configuration/README.md
  docs/system-admin-guide/authentication/kerberos/README.md
  spec/controllers/concerns/auth_source_slo_spec.rb
  spec/controllers/concerns/auth_source_sso_spec.rb
Labels: feature, needs review

#8363 [33307] Move "log time" icon outside of the hover highlighting
  app/assets/stylesheets/content/work_packages/inplace_editing/_display_fields.sass
  frontend/src/app/modules/fields/display/field-types/wp-spent-time-display-field.module.ts
Labels: needs review, styling

#8345 [32126] Use time logging widget on cost reports page
  frontend/src/app/global-dynamic-components.const.ts
  frontend/src/app/modules/grids/widgets/time-entries/list/time-entries-list.component.ts
  frontend/src/app/modules/hal/dm-services/time-entry-dm.service.ts
  frontend/src/app/modules/time_entries/edit/edit.service.ts
  frontend/src/app/modules/time_entries/edit/trigger-actions-entry.component.ts
  frontend/src/app/modules/time_entries/openproject-time-entries.module.ts
  modules/reporting/app/helpers/reporting_helper.rb
  modules/reporting/lib/widget/table/entry_table.rb
  modules/reporting/spec/features/support/components/cost_reports_base_table.rb
  modules/reporting/spec/features/support/pages/cost_report_page.rb
  modules/reporting/spec/features/update_entries_spec.rb
  modules/reporting_engine/lib/assets/javascripts/reporting_engine/reporting/controls.js
Labels: feature, needs review

#8361 [33249] Bim error on console when creating a global Work Package
  frontend/src/app/modules/bim/bcf/bcf-wp-attribute-group/bcf-new-wp-attribute-group.component.ts
Labels: bugfix, needs review

#8342 Feature #32877: WP scheduling mode
  app/contracts/work_packages/base_contract.rb
  app/models/work_package/scheduling_rules.rb
  config/locales/en.yml
  db/migrate/20200504085933_add_schedule_manually_to_work_packages.rb
  docs/api/apiv3/endpoints/work-packages.apib
  lib/api/v3/work_packages/schema/specific_work_package_schema.rb
  lib/api/v3/work_packages/schema/work_package_schema_representer.rb
  lib/api/v3/work_packages/work_package_representer.rb
  spec/lib/api/v3/work_packages/schema/work_package_schema_representer_spec.rb
  spec/lib/api/v3/work_packages/work_package_payload_representer_spec.rb
  spec/lib/api/v3/work_packages/work_package_representer_spec.rb
  spec/requests/api/v3/work_package_resource_spec.rb
Labels: feature, needs review

#8367 [33329] Set parent in changeset to ensure it gets saved
  frontend/src/app/components/wp-new/wp-create.component.ts
  spec/features/work_packages/table/context_menu_spec.rb
Labels: bugfix

#8365 [32457]Wrong display of work package widgets on project overview
  frontend/npm-shrinkwrap.json
  frontend/package.json
  frontend/src/app/modules/work-package-graphs/embedded/wp-embedded-graph.component.ts
Labels: bugfix

#8369 [33345] Allow to override path to the CA used by LDAP connections
  app/models/ldap_auth_source.rb
  config/configuration.yml.example
  docs/system-admin-guide/authentication/ldap-authentication/README.md
  docs/system-admin-guide/authentication/ldap-authentication/Screenshot-from-2018-11-01-13-47-42.png
  docs/system-admin-guide/authentication/ldap-authentication/ldap-attribute-mapping.png
  docs/system-admin-guide/authentication/ldap-authentication/ldap-details.png
  docs/system-admin-guide/authentication/ldap-authentication/ldap-host-and-security.png
  docs/system-admin-guide/authentication/ldap-authentication/ldap-index-page.png
  docs/system-admin-guide/authentication/ldap-authentication/ldap-settings.png
  docs/system-admin-guide/authentication/ldap-authentication/ldap-system-user.png
  lib/open_project/configuration.rb
  lib/open_project/configuration/helpers.rb
  spec/models/ldap_auth_source_spec.rb
Labels: feature

#8368 [33233] Display errors in the heading of project widgets with missing edit rights
  frontend/src/app/modules/common/editable-toolbar-title/editable-toolbar-title.html
Labels: bugfix

#8370 [33143] (Work packages) Custom fields for long text
  app/assets/stylesheets/content/work_packages/single_view/_single_view.sass
  app/assets/stylesheets/openproject/_mixins.sass
Labels: bugfix

#8373 [31728] Rename the module Cost reports to Time and costs
  modules/auth_plugins/lib/open_project/auth_plugins/engine.rb
  modules/backlogs/lib/open_project/backlogs/engine.rb
  modules/bim/lib/open_project/bim/engine.rb
  modules/costs/lib/open_project/costs/engine.rb
  modules/global_roles/lib/open_project/global_roles/engine.rb
  modules/meeting/lib/open_project/meeting/engine.rb
  modules/openid_connect/lib/open_project/openid_connect/engine.rb
  modules/pdf_export/lib/open_project/pdf_export/engine.rb
  modules/recaptcha/lib/open_project/recaptcha/engine.rb
  modules/reporting/app/controllers/cost_reports_controller.rb
  modules/reporting/config/locales/en.yml
  modules/reporting/lib/open_project/reporting/engine.rb
  modules/reporting/spec/features/menu_spec.rb
  modules/reporting/spec/features/subproject_spec.rb
  modules/two_factor_authentication/lib/open_project/two_factor_authentication/engine.rb
  modules/xls_export/lib/open_project/xls_export/engine.rb
  modules/xls_export/lib/open_project/xls_export/xls_views.rb
Labels: feature, needs review

#8374 [23129] Time is logged on wrong WP when triggering the modal from within the table.
  frontend/src/app/modules/fields/display/field-types/wp-spent-time-display-field.module.ts
  spec/features/work_packages/spent_time_display_spec.rb
Labels: bugfix, needs review

#8371 Fix/set csp form action for oauth
  app/controllers/oauth/auth_base_controller.rb
  config/initializers/secure_headers.rb
  docs/system-admin-guide/authentication/oauth-applications/README.md
  docs/system-admin-guide/authentication/oauth-applications/Sys-admin-authentication-oauth-postman.png
  spec/features/oauth/authorization_code_flow_spec.rb
Labels: work in progress

#8375 [30918] Boards: Cards do not update on change in split screen
  frontend/src/app/components/wp-card-view/wp-card-view.component.ts
  modules/boards/spec/features/board_update_spec.rb
Labels: bugfix, needs review

#8376 Feature/saml config from settings
  modules/auth_plugins/lib/open_project/plugins/auth_plugin.rb
  modules/auth_saml/lib/open_project/auth_saml/engine.rb
  modules/auth_saml/spec/lib/open_project/auth_saml_spec.rb
  modules/auth_saml/spec/spec_helper.rb
Labels: feature, needs review

#8386 [33152]Button to log time is shown even if I do not have the permissions
  frontend/src/app/modules/calendar/te-calendar/te-calendar.component.ts
  frontend/src/app/modules/calendar/te-calendar/te-calendar.template.html
Labels: bugfix

#8389 Render avatars manually not in angular portal
  frontend/src/app/components/user/user-avatar/user-avatar-renderer.service.ts
  frontend/src/app/components/user/user-avatar/user-avatar.component.html
  frontend/src/app/components/user/user-avatar/user-avatar.component.spec.ts
  frontend/src/app/components/user/user-avatar/user-avatar.component.ts
  frontend/src/app/components/work-packages/wp-single-view/wp-single-view.component.ts
  frontend/src/app/components/wp-fast-table/wp-fast-table.ts
  frontend/src/app/modules/fields/display/display-portal/display-user-field-portal/user-field-portal-service.ts
  frontend/src/app/modules/fields/display/display-portal/display-user-field-portal/user-field-portal.component.html
  frontend/src/app/modules/fields/display/display-portal/display-user-field-portal/user-field-portal.component.sass
  frontend/src/app/modules/fields/display/display-portal/display-user-field-portal/user-field-portal.component.ts
  frontend/src/app/modules/fields/display/display-portal/display-user-field-portal/user-field-portal.injector.ts
  frontend/src/app/modules/fields/display/display-portal/portal-cleanup.service.ts
  frontend/src/app/modules/fields/display/field-types/multiple-lines-user-display-field.module.ts
  frontend/src/app/modules/fields/display/field-types/multiple-user-display-field.module.ts
  frontend/src/app/modules/fields/display/field-types/user-display-field.module.ts
  frontend/src/app/modules/fields/openproject-fields.module.ts
  frontend/src/app/modules/grids/widgets/project-status/project-status.component.ts
  frontend/src/app/modules/work_packages/query-space/wp-isolated-graph-query-space.directive.ts
  frontend/src/app/modules/work_packages/query-space/wp-isolated-query-space.directive.ts
  modules/avatars/app/assets/stylesheets/avatars/_openproject_avatars.sass
Labels: performance

#8330 Build docker image using Github Action
  .github/workflows/docker.yml
Labels: needs review

#8360 [docker] Depend on seeder process
  docker-compose.yml
Labels: needs review

#8394 [31993] Arrangement legend dashboard
  frontend/src/app/modules/work-package-graphs/embedded/wp-embedded-graph.component.ts
Labels: bugfix

#8398 Bug #33437: Non members shall see IFC models and boards of public projects
  app/seeders/basic_data/role_seeder.rb
  modules/bim/app/seeders/bim/basic_data/role_seeder.rb
Labels: bugfix, needs review

#8396 Introduce separate permission for deleting BCF issues
  modules/bim/app/contracts/bim/bcf/issues/delete_contract.rb
  modules/bim/config/locales/en.yml
  modules/bim/lib/open_project/bim/engine.rb
  modules/bim/spec/requests/api/bcf/v2_1/topics_api_spec.rb
Labels: bugfix, needs review

#8393 Prevent double 409 conflict form errors after saving the work package
  frontend/src/app/components/work-packages/wp-single-view/wp-single-view.component.ts
  frontend/src/app/components/wp-buttons/wp-status-button/wp-status-button.component.ts
  frontend/src/app/components/wp-buttons/wp-status-button/wp-status-button.html
  frontend/src/app/components/wp-edit-form/table-edit-form.ts
  frontend/src/app/components/wp-new/wp-create.component.ts
  frontend/src/app/modules/common/edit-actions-bar/wp-edit-actions-bar.component.ts
  frontend/src/app/modules/fields/changeset/resource-changeset.ts
  frontend/src/app/modules/fields/edit/edit-form/edit-form.component.ts
  frontend/src/app/modules/fields/edit/edit-form/edit-form.ts
  frontend/src/app/modules/fields/edit/field-types/formattable-edit-field.component.ts
  frontend/src/app/modules/fields/edit/services/hal-resource-editing.service.ts
  frontend/src/app/modules/hal/resources/hal-resource.ts
  frontend/src/app/modules/hal/resources/work-package-resource.ts
  frontend/src/app/modules/time_entries/form/form.component.ts
  spec/features/work_packages/table/switch_types_spec.rb
Labels: bugfix

#8402 [33413] Use around hook to reload config in jobs
  app/workers/application_job.rb
  spec/workers/application_job_spec.rb
Labels: bugfix

#8404 [33451] Use baseRoute to navigate to split view
  frontend/src/app/components/op-context-menu/wp-context-menu/wp-view-context-menu.directive.ts
  frontend/src/app/components/wp-card-view/wp-single-card/wp-single-card.component.ts
  frontend/src/app/components/wp-new/wp-create.component.ts
  frontend/src/app/modules/work_packages/routing/split-view-routes.helper.ts
  spec/features/work_packages/navigation_spec.rb
  spec/support/pages/work_packages/work_package_cards.rb
Labels: bugfix

#8405 [33445] Ensure user is activated if invited and accessing auth source
  app/controllers/concerns/auth_source_sso.rb
  spec/controllers/concerns/auth_source_sso_spec.rb
Labels: bugfix

#8392 [33200] Work Package - Comment can only be edited once per description call
  frontend/src/app/components/wp-activity/user/user-activity.component.ts
Labels: bugfix

#8378 [33136] Filter attributes change order
  app/models/queries/work_packages/filter/category_filter.rb
  app/models/queries/work_packages/filter/group_filter.rb
  app/models/queries/work_packages/filter/priority_filter.rb
  app/models/queries/work_packages/filter/project_filter.rb
  app/models/queries/work_packages/filter/role_filter.rb
  app/models/queries/work_packages/filter/status_filter.rb
  app/models/queries/work_packages/filter/subproject_filter.rb
  app/models/queries/work_packages/filter/type_filter.rb
  app/models/queries/work_packages/filter/version_filter.rb
  modules/backlogs/lib/open_project/backlogs/work_package_filter.rb
  modules/costs/lib/open_project/costs/work_package_filter.rb
  spec/features/work_packages/table/queries/filter_spec.rb
  spec/support/components/work_packages/filters.rb
Labels: bugfix, needs review

#8411 [33470] New Features teaser for 10.6
  app/assets/images/new_feature_teaser.jpg
  app/assets/stylesheets/content/_widget_box.sass
  config/locales/js-en.yml
  frontend/src/app/components/homescreen/blocks/new-features.component.ts
Labels: needs review

#8406 Refactoring viewpoint management in the Frontend
  frontend/src/app/modules/bim/bcf/api/viewpoints/bcf-viewpoint-item.interface.ts
  frontend/src/app/modules/bim/bcf/api/viewpoints/bcf-viewpoint.interface.ts
  frontend/src/app/modules/bim/bcf/bcf-viewer-bridge/revit-bridge.service.ts
  frontend/src/app/modules/bim/bcf/bcf-viewer-bridge/viewer-bridge.service.ts
  frontend/src/app/modules/bim/bcf/bcf-wp-attribute-group/bcf-new-wp-attribute-group.component.ts
  frontend/src/app/modules/bim/bcf/bcf-wp-attribute-group/bcf-wp-attribute-group.component.html
  frontend/src/app/modules/bim/bcf/bcf-wp-attribute-group/bcf-wp-attribute-group.component.ts
  frontend/src/app/modules/bim/bcf/helper/viewpoints.service.ts
  frontend/src/app/modules/bim/bcf/openproject-bcf.module.ts
  frontend/src/app/modules/bim/ifc_models/ifc-base-view/event-handler/bcf-click-handler.ts
  frontend/src/app/modules/bim/ifc_models/ifc-viewer/ifc-viewer.service.ts
Labels: needs review

#8407 [33324] Form misplaced after error
  app/assets/stylesheets/content/_form_error_messages.sass
  app/helpers/custom_fields_helper.rb
Labels: bugfix

#8414 [33449] Usability bug: layout bug when setting new parent
  frontend/src/app/components/work-packages/wp-breadcrumb/wp-breadcrumb.component.ts
  frontend/src/app/components/work-packages/wp-breadcrumb/wp-breadcrumb.html
  frontend/src/app/components/work-packages/wp-breadcrumb/wp-breadcrumb.sass
Labels: bugfix, needs review

#8415 Add Enterprise trial infos and fix issues
  app/controllers/enterprises_controller.rb
  config/locales/js-en.yml
  config/routes.rb
  frontend/src/app/components/enterprise/enterprise-modal/enterprise-trial-form/ee-trial-form.component.html
  frontend/src/app/components/enterprise/enterprise-trial-waiting/ee-trial-waiting.component.html
  frontend/src/app/components/enterprise/enterprise-trial-waiting/ee-trial-waiting.component.ts
  frontend/src/app/components/enterprise/enterprise-trial.service.ts
  spec/features/admin/enterprise/enterprise_trial_spec.rb
Labels: needs review
