Repository opf/openproject, pull requests merged in 2020-06, with the labels that each got.

#8419 Use the visible parent if the actual parent is not visible
  frontend/src/app/components/wp-fast-table/builders/modes/hierarchy/hierarchy-render-pass.ts
  frontend/src/app/components/wp-relations/wp-relations-hierarchy/wp-relations-hierarchy.directive.ts
  frontend/src/app/components/wp-relations/wp-relations-hierarchy/wp-relations-hierarchy.service.ts
  frontend/src/app/components/wp-table/drag-and-drop/actions/hierarchy-drag-action.service.ts
  frontend/src/app/modules/hal/resources/work-package-resource.ts
Labels: bugfix

#8418 Restrict table width by break-all words
  app/assets/stylesheets/content/editor/_ckeditor.sass
  app/assets/stylesheets/content/editor/_markdown.sass
  spec/features/wysiwyg/tables_spec.rb
Labels: feature, styling

#8420 [33447] Inconsistent confirmation modal for deleting a time entry
  app/assets/stylesheets/content/_forms.sass
  app/assets/stylesheets/content/_modal.lsg
  app/assets/stylesheets/content/_modal.sass
  config/locales/js-en.yml
  frontend/src/app/components/modals/confirm-dialog/confirm-dialog.modal.html
  frontend/src/app/components/modals/confirm-dialog/confirm-dialog.modal.sass
  frontend/src/app/components/modals/confirm-dialog/confirm-dialog.modal.ts
  frontend/src/app/components/modals/wp-destroy-modal/wp-destroy.modal.html
  frontend/src/app/modules/grids/widgets/time-entries/list/time-entries-list.component.ts
Labels: bugfix

#8430 [33520]Rename work package permission "Manage subtasks" to "Manage work package hierarchies"
  config/locales/en.yml
Labels: bugfix

#8429 [33346] Derive available values for Board AddListModal from widget options
  frontend/src/app/modules/boards/board/add-list-modal/add-list-modal.component.ts
  frontend/src/app/modules/boards/board/board-actions/assignee/assignee-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/board-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/status/status-action.service.ts
  frontend/src/app/modules/boards/board/board-actions/version/version-action.service.ts
  frontend/src/app/modules/boards/board/board-partitioned-page/board-list-container.component.ts
  frontend/src/app/modules/boards/board/board.ts
Labels: bugfix, needs review

#8440 Dont call #delete on status params
  app/services/projects/set_attributes_service.rb
  spec/features/projects/template_spec.rb
Labels: bugfix

#8432 [33478] Users without editing permission can move widgets on overview page (frontend only)
  frontend/src/app/modules/grids/grid/grid.component.html
Labels: bugfix

#8441 [33514] Selected board in the left sidebar loses color highlighting
  frontend/src/app/modules/boards/board/board-partitioned-page/board-list-container.component.ts
  frontend/src/app/modules/boards/board/board.service.ts
  frontend/src/app/modules/boards/boards-sidebar/boards-menu.component.html
  frontend/src/app/modules/boards/boards-sidebar/boards-menu.component.ts
Labels: bugfix, needs review

#8449 Add support for Ubuntu 20.04 on packager.io
  .pkgr.yml
Labels: packager

#8450 Bim: Fixing several issues with the BCF XML import
  modules/bim/app/controllers/bim/bcf/issues_controller.rb
  modules/bim/app/models/bim/bcf/issue.rb
  modules/bim/app/views/bim/bcf/issues/configure_invalid_people.html.erb
  modules/bim/app/views/bim/bcf/issues/configure_non_members.html.erb
  modules/bim/app/views/bim/bcf/issues/configure_unknown_mails.html.erb
  modules/bim/app/views/bim/bcf/issues/configure_unknown_priorities.html.erb
  modules/bim/app/views/bim/bcf/issues/configure_unknown_statuses.html.erb
  modules/bim/app/views/bim/bcf/issues/configure_unknown_types.html.erb
  modules/bim/config/locales/en.yml
  modules/bim/config/routes.rb
  modules/bim/db/migrate/20200610083854_add_uniqueness_contrain_to_bcf_topic_on_uuid.rb
  modules/bim/lib/open_project/bim/bcf_xml/issue_reader.rb
  modules/bim/lib/open_project/bim/engine.rb
  modules/bim/spec/controllers/issues_controller_spec.rb
Labels: needs review

#8448 [33617] Allow SSO providers to define logout flows
  app/controllers/account_controller.rb
  app/controllers/concerns/accounts/current_user.rb
  app/controllers/concerns/auth_source_sso.rb
  app/services/users/login_service.rb
  modules/auth_plugins/lib/open_project/plugins/auth_plugin.rb
  modules/auth_saml/lib/open_project/auth_saml/engine.rb
  spec/controllers/account_controller_spec.rb
  spec/services/users/login_service_spec.rb
Labels: bugfix

#8454 [33460] Standalone icon for spentTimeDisplayField
  frontend/src/app/modules/fields/display/field-types/wp-spent-time-display-field.module.ts
Labels: bugfix, styling

#8455 [33311] Remove wrong usage of "box" class from HTML and CSS
  app/assets/stylesheets/content/_boxes.sass
  app/assets/stylesheets/content/_forms.sass
  app/views/categories/destroy.html.erb
  app/views/wiki/_page_form.html.erb
  app/views/wiki/destroy.html.erb
  app/views/wiki/edit_parent_page.html.erb
  app/views/wiki/rename.html.erb
  modules/costs/app/views/costlog/edit.html.erb
Labels: housekeeping, styling

#8456 [33446] Closing icon overlaps modal header when the content is small
  app/assets/stylesheets/content/_modal.lsg
  app/assets/stylesheets/content/_modal.sass
  app/views/wiki/_wiki_export_modal.html.erb
  frontend/src/app/components/modals/export-modal/wp-table-export.modal.html
  frontend/src/app/components/modals/save-modal/save-query.modal.html
  frontend/src/app/components/modals/share-modal/query-sharing.modal.html
  frontend/src/app/components/wp-table/configuration-modal/wp-table-configuration.modal.html
  frontend/src/app/modules/boards/board/board-video-teaser-modal/board-video-teaser-modal.component.ts
  frontend/src/app/modules/boards/board/configuration-modal/board-configuration.modal.html
  frontend/src/app/modules/common/help-texts/help-text.modal.html
Labels: bugfix, housekeeping, needs review, styling

#8446 [33457] Date fields of closed work packages are highlighted red
  frontend/src/app/modules/fields/display/field-types/date-display-field.module.ts
  frontend/src/app/modules/work_packages/routing/wp-view-base/view-services/wp-view-highlighting.service.ts
  spec/features/work_packages/display_fields/date_field_display_spec.rb
  spec/features/work_packages/display_fields/estimated_hours_display_spec.rb
  spec/features/work_packages/display_fields/spent_time_display_spec.rb
Labels: bugfix, needs review

#8451 [33317] Deleted issue still in split view after deleting it in WP-Fullscreen mode
  frontend/src/app/components/wp-single-view-tabs/keep-tab/keep-tab.service.ts
  frontend/src/app/modules/bim/ifc_models/openproject-ifc-models.routes.ts
  frontend/src/app/modules/common/back-routing/back-routing.service.ts
  frontend/src/app/modules/work_packages/routing/split-view-routes.template.ts
  modules/bim/spec/features/bim_navigation_spec.rb
Labels: bugfix, needs review

#8445 [32766] Align checkboxes correctly
  app/assets/stylesheets/content/editor/_ckeditor.sass
  app/assets/stylesheets/content/editor/_markdown.sass
  app/assets/stylesheets/content/work_packages/tabs/_activities.sass
Labels: needs review

#8422 Only Cards mode for the Revit Plugin
  frontend/angular.json
  frontend/src/app/components/op-context-menu/op-context-menu.component.ts
  frontend/src/app/components/op-context-menu/op-context-menu.html
  frontend/src/app/modules/bim/bcf/bcf-viewer-bridge/revit-bridge.service.ts
  frontend/src/app/modules/bim/bcf/bcf-viewer-bridge/viewer-bridge.service.ts
  frontend/src/app/modules/bim/ifc_models/ifc-viewer/ifc-viewer.service.ts
  frontend/src/app/modules/bim/ifc_models/openproject-ifc-models.routes.ts
  frontend/src/app/modules/bim/ifc_models/toolbar/view-toggle/bim-view-toggle-dropdown.directive.ts
  modules/bim/spec/features/bim_navigation_spec.rb
  modules/bim/spec/features/bim_revit_addin_navigation_spec.rb
  modules/bim/spec/support/pages/ifc_models/show_default.rb
  spec/support/browsers/chrome.rb
Labels: needs review

#8467 Add install instructions for Ubuntu 20.04
  .pkgr.yml
  docs/installation-and-operations/installation/packaged/README.md
  docs/installation-and-operations/system-requirements/README.md
Labels: documentation

#8458 [33344] Multiple spaces in project name causes problems
  app/models/project.rb
  spec/models/project_spec.rb
Labels: bugfix

#8466 [33685]Number of watchers not shown when opening work package in full screen (through double-click)
  frontend/src/app/components/work-packages/wp-relations-count/wp-watchers-count.component.ts
  spec/features/work_packages/tabs/watcher_tab_spec.rb
Labels: bugfix

#8473 [33659] Fix inserting on group MEMBER id not MEMBER ROLE id
  app/services/groups/add_users_service.rb
  db/migrate/20200625133727_fix_inherited_group_member_roles.rb
  spec/features/groups/group_memberships_spec.rb
Labels: bugfix, needs review

#8468 [33683, 33684] Extend Date picker to show two months next to each other and a "Today" link
  app/assets/stylesheets/content/_forms_mobile.sass
  config/locales/js-en.yml
  frontend/src/app/components/datepicker/datepicker.helper.ts
  frontend/src/app/components/datepicker/datepicker.modal.helper.ts
  frontend/src/app/components/datepicker/datepicker.modal.html
  frontend/src/app/components/datepicker/datepicker.modal.sass
  frontend/src/app/components/datepicker/datepicker.modal.ts
  frontend/src/app/components/datepicker/datepicker_mobile.modal.sass
  frontend/src/app/modules/common/op-date-picker/datepicker.ts
  spec/features/work_packages/details/date_editor_spec.rb
  spec/support/components/datepicker/datepicker.rb
  spec/support/edit_fields/date_edit_field.rb
Labels: feature, needs review

#8465 [33247] Cannot drag & drop work package outside of currently displayed browser window
  frontend/src/app/modules/common/drag-and-drop/dom-autoscroll.service.ts
  frontend/src/app/modules/common/drag-and-drop/drag-and-drop.service.ts
Labels: bugfix, needs review

#8472 [33109]Arrow next to parent task still shown after removing subtask
  frontend/src/app/components/wp-relations/wp-relations-hierarchy/wp-relations-hierarchy.service.ts
  spec/features/work_packages/table/hierarchy/hierarchy_parent_below_spec.rb
Labels: bugfix

#8471 BIM Fix: BCF-XML writer should not set FieldOfView but ViewToWorldScale instead.
  modules/bim/app/controllers/bim/bcf/issues_controller.rb
  modules/bim/lib/open_project/bim/bcf_xml/viewpoint_writer.rb
  modules/bim/spec/fixtures/viewpoints/minimal.bcfv.json
  modules/bim/spec/fixtures/viewpoints/minimal.bcfv.xml
  modules/bim/spec/lib/open_project/bcf/bcf_json/viewpoint_reader_shared_examples.rb
Labels: needs review

#8476 Allow logging slow SQL queries to sentry/local logger
  config/initializers/log_slow_sql_queries.rb
  lib/open_project/configuration.rb
Labels: housekeeping

#8479 [33707] Provide active window service and poll only when active
  frontend/src/app/modules/boards/board/query-updated/query-updated.service.ts
  frontend/src/app/modules/common/active-window/active-window.service.ts
Labels: feature
