Repository opf/openproject, pull requests merged in 2020-12, with the labels that each got.

#8835 Feature/35115 wyswyg documentation
  docs/development/concepts/wysiwyg-editor/README.md
  docs/development/concepts/wysiwyg-editor/ckeditor-diagram.png
  docs/development/concepts/wysiwyg-editor/ckeditor-inspector.png
Labels: needs review

#8852 [34840] Unclear error message when subproject column for action board cannot be displayed due to missing permissions (handling this bug in another way)
  frontend/src/app/modules/boards/board/board-partitioned-page/board-list-container.component.ts
  modules/boards/spec/features/action_boards/subproject_board_spec.rb
Labels: bugfix

#8884 Fix/wysiwyg changes
  docker-compose.yml
  frontend/src/global_styles/content/user-content/_figure.sass
  frontend/src/global_styles/content/user-content/_image.sass
  frontend/src/global_styles/content/user-content/_table.sass
  frontend/src/global_styles/content/user-content/_typography.sass
  spec/features/work_packages/new/new_work_package_spec.rb
Labels: pullpreview

#8889 Video embedding
  docs/cloud-edition-guide/sign-in/README.md
  docs/getting-started/README.md
  docs/getting-started/boards-introduction/README.md
  docs/getting-started/gantt-chart-introduction/README.md
  docs/getting-started/invite-members/README.md
  docs/getting-started/projects/README.md
  docs/getting-started/sign-in-registration/README.md
  docs/getting-started/work-packages-introduction/README.md
  docs/installation-and-operations/installation/packaged/README.md
  docs/system-admin-guide/custom-fields/README.md
  docs/system-admin-guide/manage-work-packages/work-package-types/README.md
  docs/user-guide/agile-boards/README.md
  docs/user-guide/backlogs-scrum/README.md
  docs/user-guide/gantt-chart/README.md
  docs/user-guide/gantt-chart/scheduling/README.md
  docs/user-guide/integrations/Excel Synchronization/README.md
  docs/user-guide/members/README.md
  docs/user-guide/projects/README.md
  docs/user-guide/time-and-costs/README.md
  docs/user-guide/work-packages/README.md
Labels: documentation
