Repository opf/openproject, pull requests merged in 2021-01, with the labels that each got.

#8903 fix bug 35735 height 80px to min-height 84px
  frontend/src/app/modules/backlogs/backlogs-page/styles/taskboard.sass
Labels: needs review

#8910 Fix: pgloader-ccl binaries
  docker/prod/Dockerfile
Labels: pullpreview

#8911 Only require newrelic if license key present
  Gemfile
Labels: docker, packager

#8627 [32928] Move cost reports to a submenu
  frontend/src/app/components/main-menu/main-menu-toggle.service.ts
  frontend/src/app/components/wp-query-select/wp-query-select-dropdown.component.ts
  frontend/src/app/components/wp-query-select/wp-query-select.template.html
  frontend/src/app/globals/tree-menu.ts
  frontend/src/global_styles/layout/_collapsible_menu.sass
  frontend/src/global_styles/layout/_index.sass
  frontend/src/global_styles/layout/_main_menu.sass
  frontend/src/global_styles/layout/_tree_menu.sass
  frontend/src/global_styles/layout/work_packages/_index.sass
  modules/reporting/app/controllers/cost_reports_controller.rb
  modules/reporting/app/models/cost_query.rb
  modules/reporting/app/views/cost_reports/_report_category.html.erb
  modules/reporting/app/views/cost_reports/_report_list.html.erb
  modules/reporting/app/views/cost_reports/_report_menu.html.erb
  modules/reporting/app/views/cost_reports/index.html.erb
  modules/reporting/config/locales/en.yml
  modules/reporting/lib/open_project/reporting/engine.rb
  modules/reporting/spec/features/saving_spec.rb
  spec/features/menu_items/query_menu_item_spec.rb
  spec/features/work_packages/navigation_spec.rb
  spec/features/work_packages/select/select_query_spec.rb
  spec/features/work_packages/table/queries/hidden_query_spec.rb
  spec/features/work_packages/table/queries/query_menu_refresh_spec.rb
  spec/features/work_packages/table/queries/query_menu_spec.rb
  spec/support/components/work_packages/query_menu.rb
Labels: feature, needs review, pullpreview

#8902 Added link to permissions
  docs/development/concepts/queries/README.md
Labels: needs review

#8909 Removed meanless? .textarea-wrapper class
  frontend/src/app/modules/fields/edit/field-types/multi-select-edit-field.component.html
Labels: needs review

#8920 Fix removed LdapError error class
  app/models/ldap_auth_source.rb
  spec_legacy/unit/user_spec.rb
Labels: bugfix

#8915 Fix/35144 milestones due dates not highlighted
  frontend/src/app/components/wp-table/configuration-modal/tabs/highlighting-tab.component.ts
  frontend/src/app/modules/fields/display/field-types/highlightable-display-field.module.ts
Labels: needs review

#8826 [33163] Add work package filter for child work packages(implementing the component in another way)
  frontend/src/app/components/filters/filter-searchable-multiselect-value/filter-searchable-multiselect-value.component.html
  frontend/src/app/components/filters/filter-searchable-multiselect-value/filter-searchable-multiselect-value.component.ts
  frontend/src/app/components/filters/query-filter/query-filter.component.html
  frontend/src/app/components/filters/query-filter/query-filter.component.ts
  frontend/src/app/components/filters/query-filters/query-filters.component.html
  frontend/src/app/components/filters/query-filters/query-filters.component.ts
  frontend/src/app/modules/hal/resources/query-filter-instance-resource.ts
  frontend/src/app/modules/work_packages/openproject-work-packages.module.ts
  frontend/src/app/modules/work_packages/routing/wp-view-base/view-services/wp-view-filters.service.ts
  spec/features/work_packages/table/queries/filter_spec.rb
Labels: feature

#8932 Inputs' blue border removed
  frontend/src/global_styles/content/work_packages/inplace_editing/_edit_fields.sass
Labels: needs review

#8938 set content type of attachments in S3
  app/uploaders/direct_fog_uploader.rb
  app/uploaders/fog_file_uploader.rb
  modules/costs/spec/requests/api/attachments/attachments_by_budget_resource_spec.rb
  modules/documents/spec/requests/api/v3/attachments/attachments_by_documents_resource_spec.rb
  spec/requests/api/v3/attachments/attachment_resource_shared_examples.rb
  spec/requests/api/v3/attachments_spec.rb
Labels: bugfix, needs review

#8941 make download URL expiry configurable, use safer default
  app/uploaders/fog_file_uploader.rb
  docs/installation-and-operations/configuration/README.md
  lib/open_project/configuration.rb
  spec/models/attachment_spec.rb
Labels: bugfix, needs review

#8951 Maintenance: ruby patch level update to 2.7.2
  .github/workflows/docker.yml
  .ruby-version
  .travis.yml
  Gemfile
  Gemfile.lock
  app/models/work_package/exporter/csv.rb
  docker/dev/backend/Dockerfile
  docker/prod/Dockerfile
  docs/development/development-environment-osx/README.md
  docs/development/development-environment-ubuntu/README.md
  docs/installation-and-operations/installation/manual/README.md
Labels: housekeeping, pullpreview, security
