Repository opf/openproject, pull requests merged in 2021-12, with the labels that each got.

#9935 Use PartitionedQuerySpace as basis for team planner
  frontend/src/app/features/team-planner/team-planner/page/team-planner-page.component.ts
Labels: pullpreview

#9872 [40016] Wiki Link List in content formatting issue
  frontend/src/global_styles/layout/_tree_menu.sass
Labels: bugfix

#9934 [40200] Style FullCalendar for team planner module
  app/helpers/colors_helper.rb
  frontend/src/global_styles/content/_avatar.sass
  frontend/src/global_styles/vendor/_full_calendar.sass
  frontend/src/global_styles/vendor/_index.sass
Labels: styling, needs review

#9951 [40142] Textausrichtung von Langtextfeldern in Projektübersicht
  frontend/src/global_styles/content/_table.sass
  frontend/src/global_styles/content/work_packages/_table_content.sass
Labels: bugfix, styling, needs review

#9955 [40154] Dropdown menu empty when adding new element to parent child board
  frontend/src/app/features/boards/board/add-list-modal/add-list-modal.component.ts
  frontend/src/app/features/boards/board/add-list-modal/add-list-modal.html
  frontend/src/app/features/boards/board/board-actions/assignee/assignee-action.service.ts
  frontend/src/app/features/boards/board/board-actions/board-action.service.ts
  frontend/src/app/features/boards/board/board-actions/status/status-action.service.ts
  frontend/src/app/features/boards/board/board-actions/subproject/subproject-action.service.ts
  frontend/src/app/features/boards/board/board-actions/subtasks/board-subtasks-action.service.ts
  frontend/src/app/features/boards/board/board-actions/version/version-action.service.ts
  modules/boards/spec/features/action_boards/subtasks_board_spec.rb
  modules/boards/spec/features/support/board_page.rb
Labels: bugfix, needs review

#9971 [40281] User Avatar misaligned in top menu
  frontend/src/global_styles/common/header/app-menu.sass
  frontend/src/global_styles/content/_avatar.sass
  frontend/src/global_styles/content/_principal.sass
Labels: bugfix, styling, needs review

#9967 [39492] Create work packages in team planner split view with defaults
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.ts
  frontend/src/app/features/work-packages/components/wp-new/wp-create.component.ts
  frontend/src/app/features/work-packages/routing/split-view-routes.helper.ts
  frontend/src/app/features/work-packages/routing/split-view-routes.template.ts
  frontend/src/app/features/work-packages/routing/work-packages-routes.ts
  modules/team_planner/spec/features/shared_context.rb
  modules/team_planner/spec/features/team_planner_create_spec.rb
  modules/team_planner/spec/features/team_planner_spec.rb
  modules/team_planner/spec/support/pages/team_planner.rb
Labels: pullpreview

#9994 Fix: attachments cache cleanup
  app/models/attachment.rb
  app/workers/backup_job.rb
  lib/tasks/attachments.rake
Labels: bugfix, needs review

#9980 Prevent dates from being persisted in team planner query
  frontend/src/app/core/apiv3/endpoints/queries/apiv3-queries-paths.ts
  frontend/src/app/core/apiv3/endpoints/queries/apiv3-query-form.ts
  frontend/src/app/features/team-planner/team-planner/page/team-planner-page.component.ts
  frontend/src/app/features/team-planner/team-planner/team-planner.routes.ts
  frontend/src/app/features/work-packages/components/wp-list/wp-list-checksum.service.ts
  frontend/src/app/features/work-packages/components/wp-list/wp-list.service.ts
  frontend/src/app/features/work-packages/components/wp-query/url-params-helper.spec.ts
  frontend/src/app/features/work-packages/components/wp-query/url-params-helper.ts
  frontend/src/app/shared/components/calendar/op-calendar.service.ts
  frontend/src/app/shared/components/op-view-select/op-view-select.component.ts
  frontend/src/app/shared/components/sidemenu/sidemenu.component.html
  frontend/src/app/shared/components/sidemenu/sidemenu.component.ts
Labels: pullpreview

#9991 [40294] User name not shown in news block
  app/views/homescreen/blocks/_news.html.erb
  frontend/src/app/shared/components/grids/widgets/news/news.component.html
  frontend/src/global_styles/content/_news.sass
Labels: bugfix
