Repository opf/openproject, pull requests merged in 2021-09, with the labels that each got.

#9623 [38665] Fix application job mail config reload
  app/models/setting.rb
  app/workers/application_job.rb
  docker/ci/Dockerfile
  spec/workers/application_job_spec.rb
Labels: bugfix

#9633 Add missing libapache2-reload-perl to addon-repositories
  packaging/addons/repositories/bin/preinstall
Labels: packager

#9640 Deprecation warning for < postgres13 in admin/info
  app/views/admin/info.html.erb
  lib/open_project/database.rb
  lib/open_project/static/links.rb
  lib/tasks/database.rake
Labels: backport

#9639 [38805] Fix notification loading as anonymous user
  frontend/src/app/features/work-packages/routing/wp-view-base/state/wp-single-view.service.ts
  spec/features/work_packages/tabs/activity_notifications_spec.rb
Labels: bugfix, needs review

#9615 [34322] Row break in status selector on cards after spaces
  frontend/src/app/features/work-packages/components/wp-buttons/wp-status-button/wp-status-button.component.sass
  frontend/src/app/features/work-packages/components/wp-card-view/wp-single-card/wp-single-card.component.sass
Labels: bugfix

#9642 [38713] Highlighting of ng-select breaks when matching multiple words
  frontend/src/app/shared/components/autocompleter/op-autocompleter/op-autocompleter.component.html
Labels: bugfix, styling

#9643 [38793] Watchers dropdown is cut off
  frontend/src/global_styles/layout/work_packages/_details_view.sass
Labels: bugfix, styling

#9613 [38690] Email design - Daily Reminders
  app/assets/images/logo_openproject_narrow.svg
  app/helpers/mail_digest_helper.rb
  app/helpers/mail_notification_helper.rb
  app/mailers/digest_mailer.rb
  app/views/digest_mailer/work_packages.html.erb
  app/views/digest_mailer/work_packages.text.erb
  app/views/layouts/mailer.html.erb
  app/views/mailer/_notification_mailer_header.html.erb
  app/views/mailer/_notification_row.html.erb
  app/views/mailer/_notification_settings_button.html.erb
  config/locales/en.yml
  spec/features/notifications/digest_mail_spec.rb
  spec/mailers/digest_mailer_spec.rb
Labels: feature, styling, needs review

#9650 [38650] Adjustments on the styling of notification rows
  config/locales/js-en.yml
  frontend/src/app/features/in-app-notifications/entry/in-app-notification-entry.component.html
  frontend/src/app/features/in-app-notifications/entry/in-app-notification-entry.component.sass
  frontend/src/app/features/in-app-notifications/entry/in-app-notification-entry.component.ts
  frontend/src/app/features/in-app-notifications/entry/status/in-app-notification-status.component.sass
Labels: styling, needs review

#9655 [38878] Fix condition in scrolling to wiki element nav
  frontend/src/app/globals/tree-menu.ts
Labels: bugfix, needs review

#9645 [38813] Ensure embedded tables load their own columns
  frontend/src/app/components/states.service.ts
  frontend/src/app/components/wp-list/wp-states-initialization.service.ts
  frontend/src/app/components/wp-table/embedded/wp-embedded-table.component.ts
  frontend/src/app/modules/work_packages/query-space/isolated-query-space.ts
  frontend/src/app/modules/work_packages/routing/wp-view-base/view-services/wp-view-columns.service.ts
  frontend/src/app/modules/work_packages/routing/wp-view-base/view-services/wp-view-filters.service.ts
  frontend/src/app/modules/work_packages/routing/wp-view-base/view-services/wp-view-group-by.service.ts
  frontend/src/app/modules/work_packages/routing/wp-view-base/view-services/wp-view-sort-by.service.ts
  spec/features/work_packages/details/relations/hierarchy_spec.rb
Labels: bugfix, needs review

#9621 [38693] Scroll to oldest unread activity in the activity tab
  frontend/src/app/features/work-packages/components/wp-activity/revision/revision-activity.component.html
  frontend/src/app/features/work-packages/components/wp-activity/user/user-activity.component.html
  frontend/src/app/features/work-packages/components/wp-single-view-tabs/activity-panel/activity-base.controller.ts
  frontend/src/app/features/work-packages/components/wp-tabs/components/wp-tabs/wp-tabs.component.sass
  frontend/src/app/features/work-packages/components/wp-tabs/components/wp-tabs/wp-tabs.component.ts
  frontend/src/app/features/work-packages/routing/wp-full-view/wp-full-view.html
  frontend/src/app/features/work-packages/routing/wp-split-view/wp-split-view.html
  frontend/src/global_styles/layout/work_packages/_full_view.sass
Labels: feature

#9662 [38795] Easier testing of safari in browser stack
  bin/safari_browser_stack
  bin/setup_dev
  config/environments/development.rb
Labels: documentation, maintenance, needs review

#9669 Wrong font color for quick add menu
  frontend/src/global_styles/common/header/quick-add-menu.sass
Labels: bugfix, styling, needs review

#9661 [38797] Custom Field - Button to create custom field is placed at the bottom of page
  app/helpers/tabs_helper.rb
  app/views/attribute_help_texts/_tab.html.erb
  app/views/attribute_help_texts/index.html.erb
  app/views/custom_fields/_tab.html.erb
  app/views/custom_fields/index.html.erb
Labels: bugfix, needs review

#9625 [38648] Loading indicator when loading "all" notifications (content loader component)
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/features/in-app-notifications/center/in-app-notification-center.component.html
  frontend/src/app/features/in-app-notifications/center/in-app-notification-center.component.sass
  frontend/src/app/features/in-app-notifications/center/in-app-notification-center.component.ts
  frontend/src/app/features/in-app-notifications/center/state/ian-center.service.ts
  frontend/src/app/features/in-app-notifications/entry/in-app-notification-entry.component.html
  frontend/src/app/features/in-app-notifications/entry/in-app-notification-entry.component.sass
  frontend/src/app/features/in-app-notifications/entry/in-app-notification-entry.component.ts
  frontend/src/app/features/in-app-notifications/in-app-notifications.module.ts
  frontend/src/app/shared/components/op-content-loader/op-content-loader.component.html
  frontend/src/app/shared/components/op-content-loader/op-content-loader.component.ts
  frontend/src/app/shared/components/op-content-loader/openproject-content-loader.module.ts
  frontend/src/app/shared/shared.module.ts
Labels: feature

#9674 [38794] Highlight selected notification in the center
  frontend/src/app/features/in-app-notifications/center/in-app-notification-center.component.html
  frontend/src/app/features/in-app-notifications/center/in-app-notification-center.component.sass
  frontend/src/app/features/in-app-notifications/center/in-app-notification-center.component.ts
  frontend/src/app/features/in-app-notifications/entry/in-app-notification-entry.component.html
  frontend/src/app/features/in-app-notifications/entry/in-app-notification-entry.component.sass
  frontend/src/app/features/in-app-notifications/entry/in-app-notification-entry.component.ts
  frontend/src/global_styles/openproject/_mixins.sass
Labels: feature, needs review

#9677 handle null body in issue and pull_request events correctly
  modules/github_integration/lib/open_project/github_integration/notification_handler/helper.rb
  modules/github_integration/spec/lib/open_project/github_integration/notification_handler/helper_spec.rb
Labels: bugfix, needs review

#9681 [38927] Color contrast on status button is too low
  app/models/color.rb
Labels: bugfix, styling, needs review

#9689 ee token reprieve support
  Gemfile
  Gemfile.lock
  app/models/enterprise_token.rb
  app/views/enterprises/_current.html.erb
  config/locales/js-en.yml
  frontend/src/app/components/enterprise/enterprise-active-trial/ee-active-saved-trial.component.ts
  frontend/src/app/components/enterprise/enterprise-active-trial/ee-active-trial.base.ts
  frontend/src/app/components/enterprise/enterprise-active-trial/ee-active-trial.component.html
  frontend/src/app/components/enterprise/enterprise-active-trial/ee-active-trial.component.sass
  spec/fixtures/ee_tokens/v1_expired_with_7_days_reprieve_at_2021_09_01.token
  spec/fixtures/ee_tokens/v1_expired_without_reprieve_at_2021_09_01.token
  spec/views/admin/enterprises/_current.html.erb_spec.rb
Labels: bugfix, needs review

#9675 [38690] Improve email design for various clients
  app/helpers/mail_notification_helper.rb
  app/views/digest_mailer/work_packages.html.erb
  app/views/digest_mailer/work_packages.text.erb
  app/views/layouts/mailer.html.erb
  app/views/mailer/_notification_mailer_header.html.erb
  app/views/mailer/_notification_row.html.erb
  config/locales/en.yml
Labels: styling

#9697 [#38960] Viewpoint files must end with .bcfv
  modules/bim/lib/open_project/bim/bcf_xml/exporter.rb
  modules/bim/lib/open_project/bim/bcf_xml/issue_writer.rb
  modules/bim/spec/bcf/bcf_xml/issue_writer_spec.rb
Labels: bugfix

#9705 disable direct uploads for custom fog hosts
  lib/open_project/configuration/helpers.rb
Labels: bugfix, needs review

#9712 [#38981] Integrate latest Xeokit version v2.3.6
  frontend/npm-shrinkwrap.json
  frontend/package.json
  frontend/src/app/modules/bim/ifc_models/ifc-viewer/ifc-viewer.component.html
  frontend/src/app/modules/bim/ifc_models/ifc-viewer/ifc-viewer.component.sass
  frontend/src/app/modules/bim/ifc_models/ifc-viewer/ifc-viewer.component.ts
  frontend/src/app/modules/bim/ifc_models/ifc-viewer/ifc-viewer.service.ts
  frontend/src/app/modules/bim/ifc_models/pages/viewer/styles/generic.sass
  frontend/src/app/modules/bim/ifc_models/pages/viewer/styles/tabs.sass
  frontend/src/app/modules/bim/ifc_models/pages/viewer/styles/toolbar.sass
  frontend/src/app/modules/bim/ifc_models/xeokit/xeokit-server.ts
  frontend/src/app/modules/bim/ifc_models/xeokit/xeokit.d.ts
  modules/bim/app/views/bim/ifc_models/ifc_models/_panels.html.erb
  modules/bim/spec/support/pages/ifc_models/index.rb
  modules/bim/spec/support/pages/ifc_models/show_default.rb
Labels: feature, maintenance
