Repository opf/openproject, pull requests merged in 2022-12, with the labels that each got.

#11738 Remove createdAt, add start/due date for datepicker banner columns
  frontend/src/app/shared/components/datepicker/banner/datepicker-banner.component.ts
Labels: bugfix

#11729 Corrections to Notifications page
  docs/user-guide/notifications/NotificationCenter-12.4-inbox.png
  docs/user-guide/notifications/NotificationCenter-12.4-splitScreenView-structure.png
  docs/user-guide/notifications/NotificationCenter-12.4-splitScreenView.png
  docs/user-guide/notifications/README.md
Labels: documentation

#11743 [45167] Update Enterprise add-on illustration in the core app
  app/assets/images/enterprise-add-on.svg
  app/assets/images/premium_features.svg
  app/views/common/upsale.html.erb
  app/views/enterprises/_info.html.erb
  app/views/homescreen/blocks/_upsale.html.erb
  frontend/src/app/shared/components/enterprise-banner/enterprise-banner.component.ts
  frontend/src/app/shared/components/enterprise-page/enterprise-page.component.ts
  frontend/src/assets/images/enterprise-add-on.svg
  frontend/src/assets/images/enterprise_edition.png
Labels: pullpreview

#10822 Bump angular to v14
  app/controllers/enterprises_controller.rb
  frontend/.gitignore
  frontend/angular.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/core/augmenting/dynamic-scripts/backlogs/model.js
  frontend/src/app/core/augmenting/dynamic-scripts/members_form.js
  frontend/src/app/core/augmenting/dynamic-scripts/project.js
  frontend/src/app/core/augmenting/dynamic-scripts/two_factor_authentication.ts
  frontend/src/app/core/forms/forms.service.spec.ts
  frontend/src/app/core/forms/forms.service.ts
  frontend/src/app/core/setup/globals/components/admin/backup.component.html
  frontend/src/app/core/setup/globals/components/admin/backup.component.ts
  frontend/src/app/core/setup/globals/global-listeners/danger-zone-validation.ts
  frontend/src/app/core/setup/globals/onboarding/helpers.ts
  frontend/src/app/core/setup/globals/onboarding/tours/boards_tour.ts
  frontend/src/app/core/setup/globals/onboarding/tours/team_planners_tour.ts
  frontend/src/app/features/enterprise/enterprise-modal/enterprise-trial-form/ee-trial-form.component.ts
  frontend/src/app/features/enterprise/enterprise-modal/enterprise-trial.modal.ts
  frontend/src/app/features/enterprise/enterprise-trial.service.ts
  frontend/src/app/features/invite-user-modal/principal/principal-search.component.ts
  frontend/src/app/features/invite-user-modal/principal/principal.component.ts
  frontend/src/app/features/invite-user-modal/project-selection/project-selection.component.ts
  frontend/src/app/features/invite-user-modal/role/role-search.component.ts
  frontend/src/app/features/overview/openproject-overview.module.ts
  frontend/src/app/features/projects/components/new-project/new-project.component.ts
  frontend/src/app/features/reporting/reporting-page/functionality/reporting_engine/controls.js
  frontend/src/app/features/reporting/reporting-page/functionality/reporting_engine/filters.js
  frontend/src/app/features/user-preferences/notifications-settings/inline-create/notification-setting-inline-create.component.ts
  frontend/src/app/features/user-preferences/notifications-settings/page/notifications-settings-page.component.ts
  frontend/src/app/features/user-preferences/notifications-settings/table/notification-settings-table.component.ts
  frontend/src/app/features/user-preferences/reminder-settings/email-alerts/email-alerts-settings.component.ts
  frontend/src/app/features/user-preferences/reminder-settings/immediate-reminders/immediate-reminder-settings.component.ts
  frontend/src/app/features/user-preferences/reminder-settings/page/reminder-settings-page.component.ts
  frontend/src/app/features/user-preferences/reminder-settings/pause-reminders/pause-reminders.component.ts
  frontend/src/app/features/user-preferences/reminder-settings/reminder-time/reminder-settings-daily-time.component.ts
  frontend/src/app/features/user-preferences/reminder-settings/workdays/workdays-settings.component.ts
  frontend/src/app/features/work-packages/components/wp-table/timeline/container/wp-timeline-container.directive.ts
  frontend/src/app/features/work-packages/routing/wp-view-base/view-services/wp-view-selection.service.ts
  frontend/src/app/shared/components/dynamic-forms/components/dynamic-form/dynamic-form.component.spec.ts
  frontend/src/app/shared/components/dynamic-forms/components/dynamic-form/dynamic-form.component.ts
  frontend/src/app/shared/components/dynamic-forms/services/dynamic-form/dynamic-form.service.spec.ts
  frontend/src/app/shared/components/dynamic-forms/services/dynamic-form/dynamic-form.service.ts
  frontend/src/app/shared/components/dynamic-forms/spec/helpers.ts
  frontend/src/app/shared/components/fields/changeset/resource-changeset.ts
  frontend/src/app/shared/components/op-context-menu/handlers/op-context-menu-trigger.directive.ts
  frontend/src/app/shared/components/op-context-menu/op-context-menu.service.ts
  frontend/src/app/shared/directives/a11y/keyboard-shortcut.service.ts
  frontend/src/app/shared/helpers/set-click-position/set-click-position.ts
  frontend/src/app/spot/components/form-field/form-binding.directive.ts
  frontend/src/app/spot/components/form-field/stories/FormFieldErrorSlot.example.ts
  frontend/src/polyfills.ts
  frontend/src/test.ts
  frontend/src/vendor/enjoyhint.js
  frontend/src/vendor/qrcode-min.js
  modules/backlogs/spec/features/stories_in_backlog_spec.rb
  modules/boards/spec/features/boards_sorting_spec.rb
  modules/reporting/spec/features/update_cost_report_spec.rb
  spec/support/browsers/chrome.rb
Labels: maintenance

#11781 fix(docs): remove invalid empty headline [skip ci]
  docs/user-guide/notifications/README.md
Labels: documentation

#11786 [#45345] Add FAQ for changing the email/account in cloud for instance…
  docs/enterprise-guide/enterprise-cloud-guide/enterprise-cloud-faq/README.md
Labels: documentation, needs review

#11754 [#45213] Cross Link Authentication and Custom OpenID Connect Providers
  docs/installation-and-operations/misc/custom-openid-connect-providers/README.md
  docs/system-admin-guide/authentication/openid-providers/README.md
Labels: documentation, needs review

#11797 Don't pluralize, but localize day count
  lib_static/plugins/acts_as_journalized/lib/journal_formatter/day_count.rb
Labels: bugfix

#11764 Fix multiple day filter bug, by explicitly applying the from clause
  app/models/queries/days/day_query.rb
  spec/models/queries/days/day_query_spec.rb
Labels: needs review

#11802 Keep comment draft when switching between work package tabs
  frontend/src/app/app.module.ts
  frontend/src/app/features/work-packages/components/work-package-comment/work-package-comment.component.ts
  frontend/src/app/features/work-packages/components/wp-activity/comment-service.ts
  frontend/src/app/features/work-packages/components/wp-activity/user/user-activity.component.ts
  frontend/src/app/features/work-packages/routing/wp-full-view/wp-full-view.component.ts
  frontend/src/app/features/work-packages/routing/wp-split-view/wp-split-view.component.ts
  frontend/src/app/shared/components/fields/edit/field-types/formattable-edit-field/formattable-edit-field.component.html
  frontend/src/app/shared/components/fields/edit/field-types/formattable-edit-field/formattable-edit-field.component.ts
  spec/features/work_packages/details/markdown/activity_comments_spec.rb
Labels: feature

#11817 Fix cancelling modal on submit due to first button being called
  frontend/src/app/shared/components/modals/request-for-confirmation/password-confirmation.modal.html
  spec/features/users/delete_spec.rb
  spec/support/components/password_confirmation_dialog.rb
Labels: bugfix

#11827 Correcting a typo in documentation
  docs/development/contribution-documentation/documentation-process/Create-draft-pull-request.png
  docs/development/contribution-documentation/documentation-process/README.md
  docs/development/contribution-documentation/documentation-process/Ready-for-review.png
  docs/getting-started/my-account/README.md
Labels: documentation

#11834 Minor updates/bugfixes to user and admin guides
  docs/release-notes/12-0-0/README.md
  docs/system-admin-guide/system-settings/display-settings/README.md
  docs/user-guide/team-planner/README.md
Labels: documentation

#11843 [#45334] Edit "Working with Backlogs" section https://community.open… OP#45334
  docs/user-guide/backlogs-scrum/manage-sprints/README.md
  docs/user-guide/backlogs-scrum/work-with-backlogs/README.md
Labels: documentation, needs review

#11844 [#43904] User guide: Add a Link for ressource management in Time and …
  docs/user-guide/time-and-costs/README.md
Labels: documentation, needs review

#11845 [#44513] Installation guide: Update https://www.openproject.org/docs/…
  docs/installation-and-operations/README.md
Labels: documentation, needs review

#11847 [#45528] Add log time by left click on work package to user guide (ti…
  docs/user-guide/time-and-costs/time-tracking/README.md
Labels: documentation, needs review

#11815 Design fixes
  frontend/src/app/features/user-preferences/notifications-settings/page/notifications-settings-page.component.sass
  frontend/src/app/features/user-preferences/notifications-settings/table/notification-settings-table.component.sass
  frontend/src/global_styles/content/work_packages/single_view/_single_view.sass
Labels: pullpreview
