Repository opf/openproject, pull requests merged in 2022-05, with the labels that each got.

#10607 Account for padding in scroll height
  frontend/src/app/shared/components/autocompleter/lazyloaded/lazyloaded-autocompleter.ts
Labels: bugfix

#10610 fix(docs12.1): update relative doc link
  docs/release-notes/12-1-0/README.md
Labels: documentation

#10609 Don't look for english team planner string in tour
  frontend/src/app/core/setup/globals/onboarding/tours/team_planners_tour.ts
Labels: bugfix, needs review

#10601 [#42173] Add endpoint (API spec) to update cache with live data
  docs/api/apiv3/components/schemas/user_collection_model.yml
  docs/api/apiv3/components/schemas/user_create_model.yml
  docs/api/apiv3/components/schemas/user_model.yml
  docs/api/apiv3/components/schemas/users_model.yml
  docs/api/apiv3/openapi-spec.yml
  docs/api/apiv3/paths/user.yml
  docs/api/apiv3/paths/user_lock.yml
  docs/api/apiv3/paths/users.yml
  docs/api/apiv3/paths/work_package_update_file_links.yml
Labels: documentation

#10613 Docs/12.1 rebased
  docs/user-guide/calendar/README.md
  docs/user-guide/calendar/filter-calendar.png
  docs/user-guide/calendar/image-20220502123901594.png
  docs/user-guide/calendar/select-projects.png
  docs/user-guide/calendar/zen-calendar.png
  docs/user-guide/team-planner/README.md
  docs/user-guide/team-planner/add-new-work-package.png
  docs/user-guide/team-planner/new-work-package-details.png
  docs/user-guide/work-packages/work-package-table-configuration/README.md
  docs/user-guide/work-packages/work-package-table-configuration/assignee-or-assignee-group-filter.png
  docs/user-guide/work-packages/work-package-table-configuration/configure-work-package-table.png
  docs/user-guide/work-packages/work-package-table-configuration/filter-for-parent-work-package.png
  docs/user-guide/work-packages/work-package-table-configuration/filter-text.png
  docs/user-guide/work-packages/work-package-table-configuration/filter-work-packages.png
  docs/user-guide/work-packages/work-package-table-configuration/filtering-by-work-package-id.png
  docs/user-guide/work-packages/work-package-table-configuration/work_package_filter.png
Labels: documentation

#10618 Documentation/41316 changes to role administration
  docs/system-admin-guide/users-permissions/roles-permissions/README.md
  docs/system-admin-guide/users-permissions/roles-permissions/Sys-admin-create-new-role.png
  docs/system-admin-guide/users-permissions/roles-permissions/create-new-role-with-role-template.png
  docs/system-admin-guide/users-permissions/roles-permissions/work-package-tracking-for-role-8145761.png
Labels: documentation

#10619 Task/41010 add configure work packages forms (headlines) (premium feature) 2
  docs/development/concepts/application-architecture/README.md
  docs/development/concepts/inline-editing/README.md
  docs/development/concepts/resource-schemas/README.md
  docs/system-admin-guide/custom-fields/README.md
  docs/system-admin-guide/manage-work-packages/work-package-types/README.md
  docs/user-guide/projects/project-settings/custom-fields/README.md
  docs/user-guide/time-and-costs/time-and-costs-faq/README.md
Labels: documentation

#10620 [chore] bump ruby version to 3.1.2
  .github/workflows/test-core.yml
  .ruby-version
  Gemfile
  Gemfile.lock
  docker/ci/Dockerfile
  docker/dev/backend/Dockerfile
  docker/prod/Dockerfile
  docs/development/development-environment-docker/README.md
  docs/development/development-environment-osx/README.md
  docs/development/development-environment-ubuntu/README.md
  docs/installation-and-operations/installation/manual/README.md
Labels: maintenance

#10623 Fix installation doc config typo
  docs/installation-and-operations/configuration/README.md
Labels: documentation, needs review

#10628 [42217] Layout of spent time widget is broken
  frontend/src/app/features/calendar/te-calendar/te-calendar.component.sass
Labels: bugfix, styling, needs review

#10627 Fix user decimals for comma decimal separators
  modules/costs/app/views/hourly_rates/_rate.html.erb
  modules/costs/spec/features/users_hourly_rates_spec.rb
Labels: bugfix, needs review

#10629 [42237] Add project settings looks broken in notification settings
  frontend/src/app/features/user-preferences/notifications-settings/inline-create/notification-setting-inline-create.component.html
Labels: bugfix, styling, needs review

#10631 Fix/42229/autocompleter typeahead
  frontend/src/app/shared/components/autocompleter/op-autocompleter/op-autocompleter.component.html
  frontend/src/app/shared/components/autocompleter/op-autocompleter/op-autocompleter.component.ts
  modules/my_page/spec/features/my/time_entries_current_user_spec.rb
  spec/support/edit_fields/edit_field.rb
Labels: bugfix, needs review

#10642 feat(docs): update links to changed feature pages, add spec download …
  docs/api/README.md
  docs/system-admin-guide/manage-work-packages/work-package-types/README.md
  docs/user-guide/backlogs-scrum/README.md
Labels: documentation

#10638 [42224] Wrong row break in Include Project modal for German
  frontend/src/app/spot/styles/sass/components/action-bar.sass
Labels: bugfix, styling, needs review

#10641 [42250] Search field does not open on mobile
  frontend/src/app/core/global_search/input/global-search-input.component.ts
Labels: bugfix, needs review

#10640 [42252] Export modal opens when clicking on "introduction video"
  app/views/onboarding/_menu_item.html.erb
Labels: bugfix, needs review

#10633 Remove budget when copying work package
  app/services/projects/copy/work_packages_dependent_service.rb
  spec/services/projects/copy_service_integration_spec.rb
Labels: bugfix, needs review

#10571 [#42161] api add open file in location links implementation
  modules/storages/lib/api/v3/file_links/file_link_representer.rb
  modules/storages/lib/api/v3/file_links/file_links_open_api.rb
  modules/storages/lib/api/v3/file_links/storage_url_helper.rb
  modules/storages/lib/open_project/storages/engine.rb
  modules/storages/spec/lib/api/v3/file_links/file_link_representer_rendering_spec.rb
  modules/storages/spec/requests/api/v3/file_links/file_links_spec.rb
Labels: feature

#10659 Rewrite oauth application owner to deleted user
  app/services/principals/replace_references_service.rb
  spec/services/principals/replace_references_service_call_integration_spec.rb
Labels: bugfix, needs review

#10665 Update capitalization in BIM guide
  docs/bim-guide/README.md
  docs/bim-guide/bim-issue-management/README.md
  docs/bim-guide/ifc-viewer/README.md
  docs/bim-guide/revit-add-in/README.md
Labels: documentation

#10660 Add missing include_subprojects property to schema
  lib/api/v3/queries/schemas/query_schema_representer.rb
Labels: bugfix

#10651 Fix: smtp settings in packager
  app/models/setting.rb
  lib/tasks/setting.rake
  packaging/conf/configuration.yml
  packaging/scripts/postinstall
Labels: bugfix, needs review

#10668 Update custom actions
  docs/system-admin-guide/manage-work-packages/custom-actions/README.md
Labels: documentation, needs review

#10678 Fix service call for user sync service
  app/services/ldap/base_service.rb
  app/services/ldap/synchronize_users_service.rb
  app/workers/ldap/synchronization_job.rb
  spec/workers/ldap/synchronization_job_spec.rb
Labels: bugfix, needs review

#10676 [#42362] API: Add storages links to project resource
  docs/api/apiv3/components/schemas/project_model.yml
  docs/api/apiv3/components/schemas/work_packages_model.yml
  docs/api/apiv3/paths/work_packages.yml
  lib/api/v3/projects/project_representer.rb
  spec/lib/api/v3/projects/project_representer_rendering_spec.rb
Labels: feature

#10669 Update flatpickr and remove most of the custom overwrites for the dat…
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/shared/components/datepicker/datepicker.modal.helper.ts
  frontend/src/app/shared/components/datepicker/datepicker.modal.html
  frontend/src/app/shared/components/datepicker/datepicker.modal.ts
  spec/features/work_packages/details/date_editor_spec.rb
  spec/support/edit_fields/date_edit_field.rb
Labels: feature, needs review

#10687 Fix mailer interceptors rejecting empty to addresses
  app/mailers/application_mailer.rb
  app/mailers/interceptors/default_headers.rb
  app/mailers/interceptors/do_not_send_mails_without_recipient.rb
  config/initializers/register_mail_interceptors.rb
  spec/mailers/user_mailer_spec.rb
Labels: bugfix, needs review

#10688 Allow setting new setting from env
  lib/tasks/setting.rake
Labels: bugfix, needs review

#10690 Correctly skip user admin mapping when syncing users
  app/models/ldap_auth_source.rb
  spec/models/ldap_auth_source_spec.rb
  spec/services/ldap/synchronize_users_service_integration_spec.rb
Labels: bugfix, needs review

#10624 Add dotenv-rails to Gemfile
  Gemfile
  Gemfile.lock
  docs/development/development-environment-osx/README.md
  docs/development/development-environment-ubuntu/README.md
  docs/installation-and-operations/installation/manual/README.md
Labels: needs review

#10693 [42397] Project filter is not applied in embedded table
  frontend/src/app/features/work-packages/components/wp-edit-form/work-package-filter-values.ts
  frontend/src/app/features/work-packages/components/wp-new/wp-create.service.ts
  spec/features/work_packages/details/query_groups/relation_query_group_spec.rb
Labels: bugfix, needs review

#10694 [42398] Form configuration is accessible without EE token
  frontend/src/app/features/admin/types/group-edit-in-place.component.ts
  frontend/src/app/features/admin/types/query-group.component.ts
  frontend/src/app/features/admin/types/type-form-configuration.component.ts
  frontend/src/app/features/admin/types/type-form-configuration.html
Labels: bugfix, needs review

#10700 Avoid "undefined" as value for text fields
  frontend/src/app/spot/components/text-field/text-field.component.ts
Labels: bugfix, needs review

#10701 Provide a way to disable user status syncing in LDAP user sync
  app/services/ldap/base_service.rb
  config/constants/settings/definitions.rb
  docs/installation-and-operations/configuration/environment/README.md
  docs/system-admin-guide/authentication/ldap-authentication/README.md
  spec/services/ldap/synchronize_users_service_integration_spec.rb
Labels: bugfix, needs review

#10705 Actually load all pages in the relations view
  frontend/src/app/core/apiv3/endpoints/relations/apiv3-relations-paths.ts
  frontend/src/app/core/apiv3/paths/apiv3-resource.ts
Labels: bugfix, needs review

#10710 Fix reloading avatars by removing the patching
  app/helpers/avatar_helper.rb
  app/models/user.rb
  modules/avatars/app/helpers/avatar_helper.rb
  modules/avatars/app/models/users/avatars.rb
  modules/avatars/lib/open_project/avatars/engine.rb
  modules/avatars/lib/open_project/avatars/patches/avatar_helper_patch.rb
  modules/avatars/lib/open_project/avatars/patches/user_patch.rb
Labels: maintenance, needs review

#10720 [#42628] Enable feature flag for storages module on pull preview
  .github/workflows/pullpreview.yml
Labels: pullpreview

#10697 [41814] Apply style changes to new date picker
  frontend/src/app/shared/components/datepicker/datepicker.modal.html
  frontend/src/app/shared/components/datepicker/datepicker.modal.sass
  frontend/src/app/shared/components/datepicker/datepicker.modal.ts
  frontend/src/app/shared/components/datepicker/datepicker_mobile.modal.sass
  frontend/src/app/shared/components/modal/modal.sass
  frontend/src/global_styles/content/_datepicker.sass
  spec/features/work_packages/scheduling/scheduling_mode_spec.rb
  spec/support/edit_fields/date_edit_field.rb
Labels: feature, styling

#10724 Bug/42194 special characters in comments not translated in activity view
  app/helpers/application_helper.rb
  app/helpers/search_helper.rb
  app/helpers/text_formatting_helper.rb
  app/views/activities/index.html.erb
  app/views/users/show.html.erb
  lib/open_project/text_formatting/truncation.rb
  modules/documents/app/views/documents/_document.html.erb
  modules/documents/spec/controllers/documents_controller_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/helpers/search_helper_spec.rb
  spec/helpers/text_formatting_helper_spec.rb
Labels: needs review

#10732 Fix spacing of "Log time" button in the my spent time widget
  frontend/src/app/features/calendar/te-calendar/te-calendar.component.sass
Labels: pullpreview

#10718 Prevent toasts on loading errors from notifications
  frontend/src/app/core/state/in-app-notifications/in-app-notifications.service.ts
  frontend/src/app/features/in-app-notifications/bell/in-app-notification-bell.component.html
  frontend/src/app/features/in-app-notifications/bell/in-app-notification-bell.component.ts
  frontend/src/app/features/in-app-notifications/bell/state/ian-bell.service.ts
Labels: bugfix, needs review

#10730 [42479] "Project" is not translated in invite user modal
  frontend/src/app/features/invite-user-modal/project-selection/project-selection.component.html
  frontend/src/app/features/invite-user-modal/project-selection/project-selection.component.ts
Labels: bugfix, pullpreview, needs review
