Repository opf/openproject, pull requests merged in 2022-07, with the labels that each got.

#10890 Don't add flatpickr-disabled when work package is manually scheduled
  frontend/src/app/shared/components/datepicker/datepicker.modal.ts
Labels: bugfix, needs review

#10743 [40774] Unify Enterprise Edition pages
  app/assets/images/enterprise/ldap-groups.jpg
  app/assets/images/enterprise/open-id-providers.jpg
  app/assets/images/enterprise/two-factor-authentication.jpg
  app/assets/videos/enterprise/custom-actions.mp4
  app/assets/videos/enterprise/custom-design.mp4
  app/assets/videos/enterprise/placeholder_users.mp4
  app/controllers/custom_actions_controller.rb
  app/views/common/upsale.html.erb
  app/views/custom_styles/upsale.html.erb
  app/views/homescreen/blocks/_upsale.html.erb
  app/views/placeholder_users/index.html.erb
  app/views/types/form/_form_configuration.html.erb
  config/locales/en.yml
  config/locales/js-en.yml
  frontend/src/app/core/setup/global-dynamic-components.const.ts
  frontend/src/app/features/boards/board/board-partitioned-page/board-list-container.component.html
  frontend/src/app/features/boards/new-board-modal/new-board-modal.component.ts
  frontend/src/app/features/boards/new-board-modal/new-board-modal.html
  frontend/src/app/features/enterprise/free-trial-button/free-trial-button.component.html
  frontend/src/app/features/in-app-notifications/center/in-app-notification-center.component.html
  frontend/src/app/features/work-packages/components/filters/filter-container/filter-container.directive.html
  frontend/src/app/features/work-packages/components/filters/query-filters/query-filters.component.html
  frontend/src/app/features/work-packages/components/filters/query-filters/query-filters.component.ts
  frontend/src/app/features/work-packages/components/wp-card-view/wp-card-view.component.html
  frontend/src/app/features/work-packages/components/wp-table/configuration-modal/tabs/columns-tab.component.html
  frontend/src/app/features/work-packages/components/wp-table/configuration-modal/tabs/columns-tab.component.ts
  frontend/src/app/features/work-packages/components/wp-table/configuration-modal/tabs/filters-tab.component.html
  frontend/src/app/features/work-packages/components/wp-table/configuration-modal/tabs/highlighting-tab.component.html
  frontend/src/app/features/work-packages/components/wp-table/configuration-modal/tabs/highlighting-tab.component.ts
  frontend/src/app/features/work-packages/components/wp-table/configuration-modal/wp-table-configuration.modal.html
  frontend/src/app/shared/components/enterprise-banner/enterprise-banner-bootstrap.component.ts
  frontend/src/app/shared/components/enterprise-banner/enterprise-banner.component.html
  frontend/src/app/shared/components/enterprise-banner/enterprise-banner.component.sass
  frontend/src/app/shared/components/enterprise-banner/enterprise-banner.component.ts
  frontend/src/app/shared/components/grids/widgets/add/add.modal.html
  frontend/src/app/shared/components/grids/widgets/add/add.modal.ts
  frontend/src/app/shared/components/grids/widgets/documents/documents.component.html
  frontend/src/app/shared/components/grids/widgets/members/members.component.html
  frontend/src/app/shared/components/grids/widgets/news/news.component.html
  frontend/src/app/shared/components/grids/widgets/subprojects/subprojects.component.html
  frontend/src/app/shared/components/grids/widgets/time-entries/list/time-entries-list.component.html
  frontend/src/app/shared/components/no-results/no-results.component.ts
  frontend/src/app/shared/components/work-package-graphs/configuration-modal/tabs/filters-tab-inner.component.html
  frontend/src/app/shared/components/work-package-graphs/embedded/wp-embedded-graph.html
  frontend/src/assets/images/enterprise_edition.png
  frontend/src/global_styles/content/_enterprise.sass
  frontend/src/global_styles/content/_toast.sass
  frontend/src/global_styles/fonts/_openproject_icon_definitions.sass
  frontend/src/global_styles/openproject/_homescreen.sass
  modules/boards/config/locales/js-en.yml
  modules/ldap_groups/app/views/ldap_groups/synchronized_groups/upsale.html.erb
  modules/ldap_groups/config/locales/en.yml
  modules/my_page/spec/features/my/work_package_table_spec.rb
  modules/openid_connect/app/views/openid_connect/providers/upsale.html.erb
  modules/openid_connect/config/locales/de.yml
  modules/team_planner/app/views/team_planner/team_planner/upsale.html.erb
  modules/team_planner/config/locales/en.yml
  modules/two_factor_authentication/app/views/two_factor_authentication/upsale.html.erb
  modules/two_factor_authentication/config/locales/en.yml
  spec/support/components/work_packages/table_configuration_modal.rb
Labels: feature, pullpreview

#10778 [#42856] Edit workpackage relation in the user guide (Screenshots and… OP#42856
  docs/user-guide/work-packages/work-package-relations-hierarchies/README.md
  docs/user-guide/work-packages/work-package-relations-hierarchies/User-guide-edit-remove-parent.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/change-parent-work-package-6597345.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/change-parent.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/image-20200129145338301.png
Labels: documentation

#10846 Documentation/improve docker compose installation docs
  docs/installation-and-operations/installation/docker/README.md
Labels: documentation, needs review

#10905 fix(docs): adjust links to refactored frontend source [skip ci]
  docs/development/code-review-guidelines/README.md
  docs/development/concepts/application-architecture/README.md
  docs/development/concepts/dynamic-forms/README.md
  docs/development/concepts/hal-resources/README.md
  docs/development/concepts/inline-editing/README.md
  docs/development/concepts/permissions/README.md
  docs/development/concepts/queries/README.md
  docs/development/concepts/resource-schemas/README.md
  docs/development/concepts/state-management/README.md
  docs/development/concepts/translations/README.md
  docs/getting-started/invite-members/invite-new-member-via-email.png
  docs/release-notes/3-0-8/README.md
  docs/release-notes/4-0-0/README.md
  docs/release-notes/5-0-16/README.md
Labels: documentation

#10904 Avoid trying to load relations for new work packages
  frontend/src/app/shared/components/datepicker/datepicker.modal.service.ts
  spec/features/work_packages/new/new_work_package_datepicker_spec.rb
  spec/support/edit_fields/date_edit_field.rb
Labels: bugfix, needs review

#10903 [42047] Improve disabled state of datepicker
  frontend/src/app/shared/components/datepicker/datepicker.modal.html
  frontend/src/app/shared/components/datepicker/datepicker.modal.ts
  frontend/src/app/spot/components/text-field/text-field.component.html
  frontend/src/app/spot/components/text-field/text-field.component.ts
  frontend/src/app/spot/styles/sass/components/text-field.sass
  frontend/src/global_styles/content/_datepicker.sass
Labels: bugfix, needs review

#10854 Implementation 42924 Display duration in the work package activity
  app/models/work_package/journalized.rb
  lib_static/plugins/acts_as_journalized/lib/journal_changes.rb
  lib_static/plugins/acts_as_journalized/lib/journal_formatter.rb
  lib_static/plugins/acts_as_journalized/lib/journal_formatter/day_count.rb
  spec/lib/journal_formatter/day_count_spec.rb
  spec/models/mail_handler_spec.rb
  spec/models/work_package/work_package_acts_as_journalized_spec.rb
Labels: needs review

#10884 [41948] Global project select optimisations
  frontend/src/app/core/setup/globals/global-listeners/top-menu.ts
  frontend/src/app/shared/components/autocompleter/project-menu-autocomplete/project-menu-autocomplete.template.html
  frontend/src/app/shared/components/project-include/project-include.component.html
  frontend/src/app/shared/components/project-list/project-list.component.html
  frontend/src/app/shared/components/project-list/project-list.component.sass
  frontend/src/app/shared/helpers/focus-helpers.ts
  frontend/src/app/spot/components/drop-modal/drop-modal.component.ts
  frontend/src/app/spot/styles/sass/components/action-bar.sass
  frontend/src/app/spot/styles/sass/components/drop-modal.sass
  frontend/src/global_styles/content/_forms_mobile.sass
Labels: bugfix, pullpreview, needs review

#10910 [41830] In team planner and calendar, the sidebar should not use the word "views"
  config/locales/js-en.yml
  frontend/src/app/shared/components/editable-toolbar-title/editable-toolbar-title.component.ts
  frontend/src/app/shared/components/op-view-select/op-view-select.component.ts
Labels: bugfix, needs review

#10911 Add dark border not only to white, but all super bright colors
  app/helpers/colors_helper.rb
Labels: bugfix, needs review

#10913 Fix parent link not being reachable due to missing tabIdentifier
  frontend/src/app/features/work-packages/components/wp-breadcrumb/wp-breadcrumb-parent.html
  frontend/src/app/features/work-packages/routing/work-packages-routes.ts
  spec/features/notifications/navigation_spec.rb
Labels: bugfix, needs review

#10901 LDAP groups: Rollback transaction on service call failure
  modules/ldap_groups/app/models/ldap_groups/synchronized_group.rb
  modules/ldap_groups/spec/models/synchronized_group_spec.rb
Labels: bugfix, needs review

#10921 [#43115] Remove second redirect button in StorageInformationBox
  frontend/src/app/shared/components/file-links/file-link-list/file-link-list.component.ts
Labels: bugfix, needs review

#10753 [40148] Make the empty notification inbox nicer
  config/locales/js-en.yml
  frontend/src/app/features/in-app-notifications/center/in-app-notification-center.component.html
  frontend/src/app/features/in-app-notifications/center/in-app-notification-center.component.sass
  frontend/src/app/features/in-app-notifications/center/in-app-notification-center.component.ts
  frontend/src/app/features/in-app-notifications/in-app-notifications.routes.ts
  spec/features/notifications/navigation_spec.rb
  spec/features/notifications/notification_center/notification_center_sidemenu_spec.rb
  spec/features/notifications/notification_center/split_screen_spec.rb
  spec/support/components/common/sidemenu.rb
  spec/support/pages/notifications/split_screen.rb
Labels: feature

#10934 [43125] Action bar is missing in global project select
  frontend/src/app/shared/components/autocompleter/project-menu-autocomplete/project-menu-autocomplete.template.html
  frontend/src/app/shared/components/project-include/project-include.component.sass
  frontend/src/app/shared/components/project-list/project-list.component.sass
  frontend/src/app/shared/components/project-list/project-list.component.ts
Labels: bugfix, needs review

#10935 [#43133] Edit Project status FAQ https://community.openproject.org/w…
  docs/user-guide/projects/project-status/README.md
Labels: documentation

#10940 [#43151] fixed plural menu entry
  app/views/my/access_token.html.erb
  config/initializers/menus.rb
  config/locales/en.yml
Labels: bugfix

#10938 [41667] Cannot inline-create a work package on views that filter by WP ID
  frontend/src/app/features/work-packages/components/filters/filter-searchable-multiselect-value/filter-searchable-multiselect-value.component.ts
  frontend/src/app/features/work-packages/components/wp-edit-form/work-package-filter-values.ts
  spec/features/work_packages/table/queries/id_filter_spec.rb
Labels: bugfix, needs review

#10945 [43086] Dots of Ü are missing in notification list
  frontend/src/app/features/in-app-notifications/entry/in-app-notification-entry.component.sass
Labels: bugfix, needs review

#10937 [#43111] Fix design and layout for storage creation workflow
  config/locales/en.yml
  modules/storages/app/services/storages/storages/set_attributes_service.rb
  modules/storages/app/views/storages/admin/storages/_form.html.erb
  modules/storages/app/views/storages/admin/storages/edit.html.erb
  modules/storages/app/views/storages/admin/storages/new.html.erb
  modules/storages/app/views/storages/admin/storages/new_oauth_client.html.erb
  modules/storages/app/views/storages/admin/storages/show.html.erb
  modules/storages/app/views/storages/admin/storages/show_oauth_application.html.erb
  modules/storages/config/locales/en.yml
  modules/storages/spec/features/admin_storages_spec.rb
  modules/storages/spec/services/storages/oauth_applications/create_service_spec.rb
  modules/storages/spec/services/storages/storages/set_attributes_service_spec.rb
Labels: feature, needs review

#10952 [43143] Attachment list and project select harmonisation (wrong styling)
  frontend/src/app/features/work-packages/components/wp-single-view-tabs/files-tab/op-files-tab.html
  frontend/src/app/shared/components/attachments/attachment-list/attachment-list-item.html
  frontend/src/app/shared/components/file-links/file-link-list-item/file-link-list-item.html
  frontend/src/app/spot/styles/sass/components/list.sass
  frontend/src/global_styles/content/work_packages/tabs/_files.sass
Labels: bugfix, styling, needs review

#10925 [41845] Distances in work package details tabs inconsistent
  frontend/src/app/features/work-packages/components/work-package-comment/work-package-comment.component.html
  frontend/src/app/features/work-packages/components/wp-buttons/wp-mark-notification-button/work-package-mark-notification-button.component.html
  frontend/src/app/features/work-packages/components/wp-buttons/wp-mark-notification-button/work-package-mark-notification-button.component.ts
  frontend/src/app/features/work-packages/components/wp-details/wp-details-toolbar.component.ts
  frontend/src/app/features/work-packages/components/wp-details/wp-details-toolbar.html
  frontend/src/app/features/work-packages/components/wp-relations/wp-relations.template.html
  frontend/src/app/features/work-packages/routing/wp-full-view/wp-full-view.html
  frontend/src/app/features/work-packages/routing/wp-split-view/wp-split-view.html
  frontend/src/app/shared/components/attachments/attachment-list/attachment-list.html
  frontend/src/global_styles/content/_scrollable_tabs.sass
  frontend/src/global_styles/content/work_packages/tabs/_activities.sass
  frontend/src/global_styles/content/work_packages/tabs/_files.sass
  frontend/src/global_styles/layout/work_packages/_details_view.sass
  frontend/src/global_styles/layout/work_packages/_full_view.sass
  frontend/src/global_styles/layout/work_packages/_table.sass
  modules/github_integration/frontend/module/tab-header/styles/tab-header.sass
Labels: bugfix

#10944 [#43094] Add scripts to public docs repository
  docs/enterprise-guide/enterprise-cloud-guide/backups/README.md
  docs/enterprise-guide/enterprise-cloud-guide/backups/script/backup-via-apiv3.sh
  docs/enterprise-guide/enterprise-on-premises-guide/support/installation-support/README.md
  docs/enterprise-guide/enterprise-on-premises-guide/support/installation-support/script/op-support-data.sh
Labels: documentation, needs review

#10959 Fixes for datepicker banner relations link
  frontend/src/app/shared/components/datepicker/banner/datepicker-banner.component.ts
  spec/features/work_packages/details/date_editor_spec.rb
Labels: feature, needs review

#10951 [#43153] Fix storage admin breadcrumbs
  config/locales/en.yml
  modules/storages/app/controllers/storages/admin/oauth_clients_controller.rb
  modules/storages/app/controllers/storages/admin/storages_controller.rb
  modules/storages/app/services/storages/oauth_applications/create_service.rb
  modules/storages/app/views/storages/admin/storages/new_oauth_client.html.erb
  modules/storages/app/views/storages/admin/storages/show.html.erb
  modules/storages/app/views/storages/admin/storages/show_oauth_application.html.erb
  modules/storages/config/locales/en.yml
Labels: bugfix, needs review

#10963 [#43181] new open storage link
  docs/api/apiv3/components/schemas/storage_model.yml
  frontend/src/app/core/state/storages/storage.model.ts
  frontend/src/app/shared/components/file-links/file-link-list/file-link-list.component.ts
  modules/storages/lib/api/v3/file_links/file_link_representer.rb
  modules/storages/lib/api/v3/file_links/file_links_open_api.rb
  modules/storages/lib/api/v3/file_links/storage_url_helper.rb
  modules/storages/lib/api/v3/storages/storage_representer.rb
Labels: bugfix

#10965 Update of installation support
  docs/enterprise-guide/enterprise-on-premises-guide/support/installation-support/README.md
Labels: documentation

#10961 Add duration display field
  config/locales/js-en.yml
  frontend/.eslintrc.js
  frontend/src/app/core/datetime/timezone.service.ts
  frontend/src/app/shared/components/fields/display/display-field.initializer.ts
  frontend/src/app/shared/components/fields/display/field-types/duration-display-field.module.ts
  frontend/src/app/shared/components/fields/display/field-types/estimated-time-display-field.module.ts
  frontend/src/app/shared/components/fields/display/field-types/wp-spent-time-display-field.module.ts
  frontend/src/app/shared/components/fields/edit/edit-field.initializer.ts
  frontend/src/app/shared/components/fields/edit/field-types/hours-duration-edit-field.component.ts
  frontend/src/app/shared/components/fields/openproject-fields.module.ts
  spec/features/work_packages/table/duration_field_spec.rb
Labels: feature, needs review

#10971 [43207] Mobile: The right margin for the files list is not correct
  frontend/src/global_styles/content/work_packages/tabs/_tab_content.sass
  frontend/src/global_styles/layout/work_packages/_details_view.sass
  frontend/src/global_styles/layout/work_packages/_full_view.sass
Labels: bugfix, styling, needs review

#10973 [43240] Work packages in Gantt chart in light grey hard to say
  frontend/src/global_styles/content/work_packages/timelines/elements/_bar.sass
Labels: bugfix, styling, needs review

#10975 [43247] Work package types with colour white are not visible in emails
  app/helpers/mail_notification_helper.rb
Labels: bugfix, styling, needs review

#10953 [#43182] Migrate permissions of existing admins and users to handle Nextcloud operations
  modules/storages/db/migrate/20220712165928_add_storages_permissions_to_roles.rb
Labels: needs review

#10980 [43252] Unnecessary scrollbar when adding a comment
  frontend/src/global_styles/layout/work_packages/_full_view.sass
Labels: bugfix, styling, needs review

#10991 fix(markdown): add mandatory table header row [skip ci]
  docs/installation-and-operations/configuration/README.md
  docs/installation-and-operations/installation/README.md
Labels: documentation

#10967 [43118] Fixes for arrow navigation in project lists
  frontend/src/app/shared/components/autocompleter/project-menu-autocomplete/project-menu-autocomplete.template.html
  frontend/src/app/shared/components/project-include/project-include.component.html
  frontend/src/app/shared/components/project-list/project-list.component.html
  frontend/src/app/shared/components/searchable-project-list/searchable-project-list.service.ts
  frontend/src/app/spot/components/drop-modal/drop-modal.component.ts
Labels: bugfix, needs review

#10992 [43296] Can not access the main actions on work package on mobile from the details view
  frontend/src/app/features/work-packages/components/back-routing/back-button.component.sass
  frontend/src/app/features/work-packages/routing/partitioned-query-space-page/partitioned-query-space-page.component.html
  frontend/src/app/features/work-packages/routing/wp-full-view/wp-full-view.html
Labels: bugfix, styling, needs review

#11000 [40858] Default status is shown multiple times in new board
  frontend/src/app/features/boards/board/board-actions/cached-board-action.service.ts
  frontend/src/app/features/boards/boards-sidebar/boards-menu.component.html
  modules/boards/spec/features/action_boards/status_board_spec.rb
  modules/boards/spec/features/support/board_index_page.rb
Labels: bugfix, needs review

#11001 [43222] Double click to open work packages in the Team Planner
  frontend/src/app/features/calendar/op-work-packages-calendar.service.ts
  frontend/src/app/features/team-planner/team-planner/add-work-packages/add-existing-pane.component.html
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.html
  frontend/src/app/features/work-packages/components/wp-card-view/wp-single-card/wp-single-card.component.html
  frontend/src/app/features/work-packages/components/wp-card-view/wp-single-card/wp-single-card.component.ts
Labels: bugfix, needs review

#10968 [#43231] Migration::MigrationUtils::PermissionAdder.add not idempotent
  db/migrate/migration_utils/permission_adder.rb
Labels: needs review

#10983 [#43260] removed hover effect on disabled file links
  frontend/src/app/shared/components/file-links/file-link-list-item/file-link-list-item.component.ts
  frontend/src/app/shared/components/file-links/file-link-list-item/file-link-list-item.html
  frontend/src/app/shared/components/file-links/storage-information/storage-information.html
  frontend/src/global_styles/content/work_packages/tabs/_files.sass
  modules/storages/app/views/storages/admin/storages/_form.html.erb
  modules/storages/config/locales/en.yml
  modules/storages/config/locales/js-en.yml
Labels: bugfix

#11004 [#43263] The space between the form and the buttons on the 2nd and 3r…
  modules/storages/app/views/storages/admin/storages/_form.html.erb
  modules/storages/app/views/storages/admin/storages/edit.html.erb
  modules/storages/app/views/storages/admin/storages/new_oauth_client.html.erb
  modules/storages/app/views/storages/admin/storages/show_oauth_application.html.erb
Labels: bugfix, needs review

#11011 Fix backup mailer
  app/mailers/user_mailer.rb
  spec/mailers/user_mailer_spec.rb
Labels: needs review

#11002 Restore 12.1 style of form configuration info toast
  app/views/types/form/_form_configuration.html.erb
Labels: bugfix, needs review

#11009 [#43185] Show alert when storage is not added to any project
  modules/storages/app/views/storages/admin/storages/show.html.erb
Labels: bugfix, feature, needs review

#11008 [#43193] Remove OAuth cookie after successful authorization against N…
  app/controllers/oauth_clients_controller.rb
Labels: bugfix, needs review

#11005 [#43226] add additional spacing
  frontend/src/app/features/work-packages/components/wp-single-view-tabs/files-tab/op-files-tab.component.ts
  frontend/src/app/features/work-packages/components/wp-single-view-tabs/files-tab/op-files-tab.html
  frontend/src/app/shared/components/attachments/attachment-list/attachment-list.html
  frontend/src/app/shared/components/attachments/attachments-upload/attachments-upload.html
  frontend/src/app/spot/styles/sass/components/list.sass
  frontend/src/global_styles/content/work_packages/tabs/_files.sass
  frontend/src/global_styles/content/work_packages/tabs/_tab_content.sass
Labels: bugfix

#11012 Prevent stripping of permissions before disabled modules registered
  config/initializers/module_handler.rb
  lib/open_project/plugins/module_handler.rb
  spec/lib/open_project/plugins/module_handler_spec.rb
Labels: bugfix, needs review

#11029 task(docs): fix links to for restructured release notes folders
  docs/installation-and-operations/operation/upgrading/README.md
  docs/release-notes/10/10-0-0/README.md
  docs/release-notes/10/10-3-0/README.md
  docs/release-notes/10/10-4-0/README.md
  docs/release-notes/10/10-4-1/README.md
  docs/release-notes/11/11-0-0/README.md
  docs/release-notes/11/11-1-0/README.md
  docs/release-notes/11/11-2-0/README.md
  docs/release-notes/11/11-3-0/README.md
  docs/release-notes/3/3-0-0/README.md
  docs/release-notes/4/4-2-0/README.md
  docs/release-notes/5/5-0-0/README.md
  docs/release-notes/6/6-0-1/README.md
  docs/release-notes/6/6-0-2/README.md
  docs/release-notes/6/6-0-3/README.md
  docs/release-notes/6/6-0-4/README.md
  docs/release-notes/6/6-0-5/README.md
  docs/release-notes/6/6-1-0/README.md
  docs/release-notes/6/6-1-1/README.md
  docs/release-notes/7/7-4-0/README.md
  docs/release-notes/7/7-4-5/README.md
  docs/release-notes/7/7-4-6/README.md
  docs/release-notes/8/8-0-0/README.md
  docs/release-notes/8/8-2-1/README.md
  docs/release-notes/8/8-3-2/README.md
  docs/release-notes/9/9-0-0/README.md
  docs/user-guide/gantt-chart/scheduling/README.md
Labels: documentation

#11026 [#43209] Unlink action sometimes missing on hover
  frontend/src/app/shared/components/file-links/file-link-list/file-link-list.component.ts
  frontend/src/app/shared/components/file-links/file-link-list/file-link-list.html
Labels: bugfix

#10997 Bug/43120 internal server error when navigating to work package page
  lib/api/v3/work_packages/work_package_eager_loading_wrapper.rb
Labels: bugfix, needs review

#11027 added -p to mkdir command
  docs/installation-and-operations/operation/restoring/README.md
Labels: documentation, needs review

#11037 [#43183] added sync for modifier
  frontend/src/app/shared/components/file-links/file-link-list/file-link-list.component.ts
  modules/storages/app/services/storages/file_link_sync_service.rb
Labels: bugfix

#11044 Cherry pick from dev
  docs/system-admin-guide/authentication/two-factor-authentication/README.md
  docs/user-guide/notifications/README.md
  docs/user-guide/notifications/notification-center-16366289566021.png
  docs/user-guide/notifications/notifications-activity-tab.png
  docs/user-guide/notifications/notifications-bottom-bar.png
  docs/user-guide/notifications/notifications-full-screen.png
Labels: documentation

#10712 Task/42619 revise in project faqs how can i get an overview over multiple projects at the same time OP#42619
  docs/user-guide/projects/projects-faq/README.md
Labels: documentation, needs review

#10727 [#42640] Edit FAQ regarding custom domain https://community.openproj… OP#42640
  docs/enterprise-guide/enterprise-cloud-guide/enterprise-cloud-faq/README.md
Labels: documentation

#11045 [#43304] removed unwanted padding from activity container
  frontend/src/global_styles/content/work_packages/tabs/_activities.sass
Labels: bugfix

#10765 [#42809] Export work packages: Customization of the data to be export… OP#42809
  docs/user-guide/work-packages/exporting/README.md
Labels: documentation

#11048 Task/42848 edit relations in work package list
  docs/user-guide/work-packages/work-package-relations-hierarchies/Add-relation-column.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/README.md
  docs/user-guide/work-packages/work-package-relations-hierarchies/change-parent-work-package.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/change-parent.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/select-parent-as-column.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/work-package-add-relation-as-column.png
Labels: documentation

#11050 Task/42740 copy, change project or delete a work package revise text and screenshot
  docs/user-guide/work-packages/copy-move-delete/README.md
  docs/user-guide/work-packages/copy-move-delete/User-guide-copy-change-project-delete-4071022.png
  docs/user-guide/work-packages/copy-move-delete/User-guide-copy-change-project-delete.png
  docs/user-guide/work-packages/copy-move-delete/change-copy-delete-work-package.png
  docs/user-guide/work-packages/copy-move-delete/change-project-of-work-package.png
  docs/user-guide/work-packages/copy-move-delete/image-20200129143632697.png
  docs/user-guide/work-packages/copy-move-delete/image-20210426163336211.png
Labels: documentation

#11043 [#40680] Documentation on how to use git inside of OP concerning the docs
  docs/development/contribution-documentation/documentation-process/README.md
  docs/development/contribution-documentation/documentation-process/fetch-upstream-changes.png
  docs/development/contribution-documentation/documentation-process/pull-upstream-changes.png
Labels: documentation, needs review

#11023 [chore] hide floating actions on mobile resolutions
  frontend/src/app/shared/components/attachments/attachment-list/attachment-list-item.html
  frontend/src/app/shared/components/file-links/file-link-list-item/file-link-list-item.html
Labels: pullpreview

#11051 Task/42684 project settings change screenshot and customize text
  docs/user-guide/projects/1566214944644.png
  docs/user-guide/projects/1566293251039.png
  docs/user-guide/projects/README.md
  docs/user-guide/projects/configure-project-list.png
  docs/user-guide/projects/copy-project-advanced-settings-3914305.png
  docs/user-guide/projects/delete-a-project.png
  docs/user-guide/projects/display-all-workpackages.png
  docs/user-guide/projects/export-project-list-formats.png
  docs/user-guide/projects/export-projects.png
  docs/user-guide/projects/image-20201007161248903.png
  docs/user-guide/projects/image-20201007172029375.png
  docs/user-guide/projects/image-20201007172208540.png
  docs/user-guide/projects/image-20210204165705788.png
  docs/user-guide/projects/image-20210204170357754.png
  docs/user-guide/projects/image-20210204170603014.png
  docs/user-guide/projects/image-20210204170859459.png
  docs/user-guide/projects/image-20210204171059565.png
  docs/user-guide/projects/image-20210204171251754.png
  docs/user-guide/projects/image-20210204171422693.png
  docs/user-guide/projects/image-20210204171811255.png
  docs/user-guide/projects/image-20210204172213314.png
  docs/user-guide/projects/navigation-bar-modules-3923134.png
  docs/user-guide/projects/new-subproject-project-list.png
  docs/user-guide/projects/overall-activity-button-3922893.png
  docs/user-guide/projects/overall-activity-meeting-filter.png
  docs/user-guide/projects/overarching-modules.png
  docs/user-guide/projects/project-hierarchy-select-project.png
  docs/user-guide/projects/project-information-copy-project.png
  docs/user-guide/projects/project-information-description-status.png
  docs/user-guide/projects/project-list-filter.png
  docs/user-guide/projects/project-settings-archive-project.png
  docs/user-guide/projects/project-settings-information-change-hierarchy-3912542.png
  docs/user-guide/projects/project-settings-information-copy-project-copy-options.png
  docs/user-guide/projects/project-settings-subproject.png
  docs/user-guide/projects/select-a-project-view-all-projects.png
Labels: documentation

#11052 Task/cherry pick docs from release 12 1
  docs/enterprise-guide/enterprise-cloud-guide/enterprise-cloud-faq/README.md
  docs/user-guide/projects/1566214944644.png
  docs/user-guide/projects/1566293251039.png
  docs/user-guide/projects/README.md
  docs/user-guide/projects/configure-project-list.png
  docs/user-guide/projects/copy-project-advanced-settings-3914305.png
  docs/user-guide/projects/delete-a-project.png
  docs/user-guide/projects/display-all-workpackages.png
  docs/user-guide/projects/export-project-list-formats.png
  docs/user-guide/projects/export-projects.png
  docs/user-guide/projects/image-20201007161248903.png
  docs/user-guide/projects/image-20201007172029375.png
  docs/user-guide/projects/image-20201007172208540.png
  docs/user-guide/projects/image-20210204165705788.png
  docs/user-guide/projects/image-20210204170357754.png
  docs/user-guide/projects/image-20210204170603014.png
  docs/user-guide/projects/image-20210204170859459.png
  docs/user-guide/projects/image-20210204171059565.png
  docs/user-guide/projects/image-20210204171251754.png
  docs/user-guide/projects/image-20210204171422693.png
  docs/user-guide/projects/image-20210204171811255.png
  docs/user-guide/projects/image-20210204172213314.png
  docs/user-guide/projects/navigation-bar-modules-3923134.png
  docs/user-guide/projects/new-subproject-project-list.png
  docs/user-guide/projects/overall-activity-button-3922893.png
  docs/user-guide/projects/overall-activity-meeting-filter.png
  docs/user-guide/projects/overarching-modules.png
  docs/user-guide/projects/project-hierarchy-select-project.png
  docs/user-guide/projects/project-information-copy-project.png
  docs/user-guide/projects/project-information-description-status.png
  docs/user-guide/projects/project-list-filter.png
  docs/user-guide/projects/project-settings-archive-project.png
  docs/user-guide/projects/project-settings-information-change-hierarchy-3912542.png
  docs/user-guide/projects/project-settings-information-copy-project-copy-options.png
  docs/user-guide/projects/project-settings-subproject.png
  docs/user-guide/projects/projects-faq/README.md
  docs/user-guide/projects/select-a-project-view-all-projects.png
Labels: documentation

#10907 task/43095-edit-progress-tracking OP#43095
  docs/user-guide/time-and-costs/progress-tracking/README.md
Labels: documentation, needs review

#11054 [#40680] [waiting for merge] Documentation on how to use git inside o…
  docs/development/contribution-documentation/documentation-process/README.md
  docs/development/contribution-documentation/documentation-process/pull-upstream-changes.png
  docs/development/contribution-documentation/documentation-process/sync-fork-update-branch.png
Labels: documentation, needs review

#11053 [39166] Invite users via a UserCF on the project settings page
  config/locales/js-en.yml
  frontend/src/app/shared/components/dynamic-forms/components/dynamic-form/dynamic-form.component.ts
  frontend/src/app/shared/components/dynamic-forms/components/dynamic-inputs/project-input/project-input.component.ts
  frontend/src/app/shared/components/dynamic-forms/components/dynamic-inputs/select-input/select-input.component.html
  frontend/src/app/shared/components/dynamic-forms/components/dynamic-inputs/select-input/select-input.component.ts
  frontend/src/app/shared/components/dynamic-forms/components/dynamic-inputs/user-input/user-input.component.html
  frontend/src/app/shared/components/dynamic-forms/components/dynamic-inputs/user-input/user-input.component.ts
  frontend/src/app/shared/components/dynamic-forms/dynamic-forms.module.ts
  frontend/src/app/shared/components/dynamic-forms/services/dynamic-fields/dynamic-fields.service.ts
  frontend/src/app/shared/components/dynamic-forms/typings.d.ts
  frontend/src/app/shared/components/forms/form-field/form-field.component.html
  frontend/src/app/shared/components/forms/form-field/form-field.component.ts
  spec/features/projects/projects_custom_fields_spec.rb
  spec/support/form_fields/select_form_field.rb
Labels: bugfix, needs review

#11055 [40148] Fine tuning of empty state in the notification center
  frontend/src/app/features/in-app-notifications/center/in-app-notification-center.component.sass
Labels: bugfix, styling, needs review

#11056 [21754] Move buttons in log time modal to correct side
  frontend/src/app/shared/components/time_entries/shared/modal/base.modal.html
Labels: bugfix, styling, needs review

#11014 [#43329] Fix Pressing Enter has no effect when being in the global project select
  frontend/src/app/shared/components/autocompleter/project-menu-autocomplete/project-menu-autocomplete.component.ts
  frontend/src/app/shared/components/autocompleter/project-menu-autocomplete/project-menu-autocomplete.template.html
  frontend/src/app/shared/components/searchable-project-list/searchable-project-list.service.ts
  spec/features/projects/project_autocomplete_spec.rb
Labels: bugfix, pullpreview, needs review

#11017 [#43123] Remove files storages feature flag
  config/configuration.yml.example
  config/constants/settings/definitions.rb
  lib/open_project/feature_decisions.rb
  modules/storages/app/controllers/storages/admin/oauth_clients_controller.rb
  modules/storages/app/controllers/storages/admin/projects_storages_controller.rb
  modules/storages/app/controllers/storages/admin/storages_controller.rb
  modules/storages/app/models/queries/storages/work_packages/filter/concerns/validate_storages_module_available.rb
  modules/storages/app/models/queries/storages/work_packages/filter/file_link_origin_id_filter.rb
  modules/storages/app/models/queries/storages/work_packages/filter/linkable_to_storage_id_filter.rb
  modules/storages/app/models/queries/storages/work_packages/filter/linkable_to_storage_url_filter.rb
  modules/storages/app/models/queries/storages/work_packages/filter/storage_id_filter.rb
  modules/storages/app/models/queries/storages/work_packages/filter/storage_url_filter.rb
  modules/storages/lib/api/v3/file_links/file_links_api.rb
  modules/storages/lib/api/v3/file_links/work_packages_file_links_api.rb
  modules/storages/lib/api/v3/storages/storages_api.rb
  modules/storages/lib/api/v3/utilities/storages_helpers.rb
  modules/storages/lib/open_project/storages/engine.rb
  modules/storages/spec/contracts/storages/file_links/create_contract_spec.rb
  modules/storages/spec/contracts/storages/file_links/delete_contract_spec.rb
  modules/storages/spec/contracts/storages/project_storages/create_contract_spec.rb
  modules/storages/spec/contracts/storages/project_storages/delete_contract_spec.rb
  modules/storages/spec/contracts/storages/storages/base_contract_spec.rb
  modules/storages/spec/contracts/storages/storages/create_contract_spec.rb
  modules/storages/spec/contracts/storages/storages/delete_contract_spec.rb
  modules/storages/spec/contracts/storages/storages/update_contract_spec.rb
  modules/storages/spec/controller/storages_controller_spec.rb
  modules/storages/spec/features/admin_storages_spec.rb
  modules/storages/spec/features/create_and_delete_project_storage_spec.rb
  modules/storages/spec/features/delete_project_storage_and_file_links_spec.rb
  modules/storages/spec/features/show_file_links_spec.rb
  modules/storages/spec/features/storages_module_disabled_spec.rb
  modules/storages/spec/features/storages_module_spec.rb
  modules/storages/spec/permissions/manage_storage_in_project_spec.rb
  modules/storages/spec/requests/api/v3/file_links/file_links_spec.rb
  modules/storages/spec/requests/api/v3/file_links/mixed_case_file_links_integration_spec.rb
  modules/storages/spec/requests/api/v3/storages/storages_spec.rb
  modules/storages/spec/requests/api/v3/work_packages/shared_filter_examples.rb
  modules/storages/spec/requests/api/v3/work_packages/work_packages_linkable_filter_spec.rb
  modules/storages/spec/requests/api/v3/work_packages/work_packages_linked_filter_spec.rb
  modules/storages/spec/services/storages/project_storages/delete_service_spec.rb
  spec/features/menu_items/admin_menu_item_spec.rb
  spec/requests/oauth_clients/callback_flow_spec.rb
  spec/support/shared/with_settings.rb
Labels: maintenance, needs review

#11058 [43479] There is no empty status in the Project Select when search criteria is not met
  config/locales/js-en.yml
  frontend/src/app/shared/components/autocompleter/project-menu-autocomplete/project-menu-autocomplete.component.ts
  frontend/src/app/shared/components/autocompleter/project-menu-autocomplete/project-menu-autocomplete.template.html
  frontend/src/app/shared/components/project-include/project-include.component.html
  frontend/src/app/shared/components/project-include/project-include.component.ts
  frontend/src/global_styles/content/_project_list_modal.sass
Labels: bugfix, needs review

#11034 [42185] Issues when manually changing dates in datepicker
  frontend/src/app/shared/components/datepicker/datepicker.modal.html
  frontend/src/app/shared/components/datepicker/datepicker.modal.service.ts
  frontend/src/app/shared/components/datepicker/datepicker.modal.ts
  spec/features/work_packages/details/date_editor_spec.rb
  spec/features/work_packages/scheduling/scheduling_mode_spec.rb
  spec/features/work_packages/table/scheduling/manual_scheduling_spec.rb
  spec/support/components/datepicker/datepicker.rb
  spec/support/edit_fields/date_edit_field.rb
Labels: bugfix, pullpreview, needs review

#10955 [40774] Unify Enterprise Edition pages- fix test fails
  app/assets/images/enterprise/attribute-help-texts.png
  app/views/admin/settings/projects_settings/show.html.erb
  app/views/admin/settings/work_packages_settings/_enterprise_feature_hint.html.erb
  app/views/custom_fields/_form.html.erb
  app/views/custom_fields/_tab.html.erb
  app/views/enterprise/_locked_note.html.erb
  app/views/projects/filters/_form.html.erb
  app/views/statuses/_form.html.erb
  app/views/types/form/_form_configuration.html.erb
  config/locales/en.yml
  config/locales/js-en.yml
  frontend/src/app/core/setup/global-dynamic-components.const.ts
  frontend/src/app/core/setup/globals/constants.const.ts
  frontend/src/app/features/boards/board/board-partitioned-page/board-list-container.component.html
  frontend/src/app/features/boards/board/board-partitioned-page/board-list-container.component.ts
  frontend/src/app/features/boards/new-board-modal/new-board-modal.component.ts
  frontend/src/app/features/boards/new-board-modal/new-board-modal.html
  frontend/src/app/features/boards/tile-view/tile-view.component.sass
  frontend/src/app/features/work-packages/components/filters/query-filters/query-filters.component.html
  frontend/src/app/features/work-packages/components/filters/query-filters/query-filters.component.ts
  frontend/src/app/features/work-packages/components/wp-table/configuration-modal/tabs/columns-tab.component.html
  frontend/src/app/features/work-packages/components/wp-table/configuration-modal/tabs/columns-tab.component.ts
  frontend/src/app/features/work-packages/components/wp-table/configuration-modal/tabs/highlighting-tab.component.html
  frontend/src/app/features/work-packages/components/wp-table/configuration-modal/tabs/highlighting-tab.component.ts
  frontend/src/app/shared/components/enterprise-banner/enterprise-banner-bootstrap.component.ts
  frontend/src/app/shared/components/enterprise-banner/enterprise-banner.component.html
  frontend/src/app/shared/components/enterprise-banner/enterprise-banner.component.sass
  frontend/src/app/shared/components/enterprise-banner/enterprise-banner.component.ts
  frontend/src/app/shared/components/grids/widgets/add/add.modal.html
  frontend/src/app/shared/components/grids/widgets/add/add.modal.ts
  frontend/src/app/shared/shared.module.ts
  frontend/src/global_styles/content/_advanced_filters.sass
  frontend/src/global_styles/content/_forms.sass
  frontend/src/global_styles/content/_toast.sass
  frontend/src/global_styles/openproject/_homescreen.sass
  lib/open_project/static/links.rb
  modules/boards/config/locales/js-en.yml
  modules/grids/config/locales/js-en.yml
Labels: bugfix, needs review
