Repository opf/openproject, pull requests merged in 2022-01, with the labels that each got.

#9985 [#40267] Opening viewpoints on mobile
  frontend/src/app/features/bim/ifc_models/bcf/list/bcf-list.component.html
  frontend/src/app/features/bim/ifc_models/bcf/list/bcf-list.component.ts
  frontend/src/app/features/bim/ifc_models/openproject-ifc-models.routes.ts
  frontend/src/app/features/bim/ifc_models/pages/viewer/ifc-viewer-page.component.ts
  frontend/src/app/features/work-packages/components/wp-card-view/wp-single-card/wp-single-card.component.ts
  frontend/src/app/features/work-packages/routing/split-view-routes.template.ts
  frontend/src/app/features/work-packages/routing/wp-list-view/wp-list-view.component.ts
  frontend/src/global_styles/content/modules/_bim.sass
  modules/bim/spec/features/bim_navigation_spec.rb
  modules/bim/spec/features/viewer/show_viewpoint_spec.rb
  spec/support/pages/work_packages/work_package_cards.rb
Labels: bugfix

#9995 [#40282] wrong position of xeokit context menu
  frontend/src/app/features/bim/ifc_models/pages/viewer/styles/context_menu.sass
Labels: bugfix

#10012 [40296] Incorrect label causes screenreader problems
  frontend/src/app/shared/components/fields/edit/editing-portal/edit-form-portal.component.html
Labels: bugfix

#9992 Docs/development environment
  docs/development/development-environment-ubuntu/README.md
Labels: documentation

#10036 [40191] Git "View Differences" results in 500 error in Repository module
  app/views/repositories/diff.html.erb
Labels: bugfix, needs review

#10017 [40396] no "Example" for Host name in "Administration->General"
  app/controllers/admin/settings/general_settings_controller.rb
Labels: bugfix

#10007 [40363] Avatars misplaces in team planner dropdown
  frontend/src/app/shared/components/autocompleter/op-autocompleter/op-autocompleter.component.html
  frontend/src/app/shared/components/autocompleter/op-autocompleter/op-autocompleter.component.sass
Labels: bugfix

#10043 [40533] Add cview to team planner
  frontend/src/app/features/calendar/op-calendar.service.ts
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.ts
  frontend/src/app/features/team-planner/team-planner/team-planner.routes.ts
  modules/team_planner/config/locales/js-en.yml
  modules/team_planner/spec/features/team_planner_view_modes_spec.rb
  modules/team_planner/spec/support/pages/team_planner.rb
Labels: pullpreview

#10044 Add tests for team planner drag and drop behavior
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.ts
  modules/backlogs/spec/features/stories_in_backlog_spec.rb
  modules/backlogs/spec/support/pages/backlogs.rb
  modules/backlogs/spec/support/pages/taskboard.rb
  modules/boards/spec/features/support/board_page.rb
  modules/team_planner/spec/features/team_planner_error_handling_spec.rb
  modules/team_planner/spec/features/team_planner_user_interaction_spec.rb
  modules/team_planner/spec/support/pages/team_planner.rb
  spec/features/admin/custom_fields/multi_value_custom_fields_spec.rb
  spec/support/shared/drag_and_drop_helper_spec.rb
Labels: needs review

#10056 [40532] Assignees column in team planner takes too wide
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.ts
Labels: needs review

#10057 [40531] Team planner not correctly redrawn after closing a split view (empty areas)
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.ts
Labels: bugfix, needs review

#10032 use fully assembled spec, return correct exit code
  script/api/validate_spec
Labels: bugfix, needs review

#10071 added no anonymous in cloud
  docs/installation-and-operations/configuration/incoming-emails/README.md
Labels: documentation, needs review

#10080 [40319] Show all statuses by default in team planner
  frontend/src/app/features/calendar/op-calendar.service.ts
  modules/team_planner/spec/features/team_planner_spec.rb
Labels: feature, needs review

#10068 [40747] Set default scope for notifications to visible
  app/models/queries/notifications/notification_query.rb
  spec/models/queries/notifications/notification_query_spec.rb
  spec/requests/api/v3/notifications/bulk_read_ian_resource_spec.rb
  spec/requests/api/v3/notifications/bulk_unread_ian_resource_spec.rb
Labels: bugfix, needs review

#10067 Render the costs subform in rails
  frontend/src/global_styles/content/_table.sass
  modules/budgets/app/controllers/budgets_controller.rb
  modules/budgets/app/views/budgets/items/_budget_override_cost_form.html.erb
  modules/budgets/app/views/budgets/items/_labor_budget_item.html.erb
  modules/budgets/app/views/budgets/items/_material_budget_item.html.erb
  modules/budgets/frontend/module/augment/cost-budget-subform.augment.service.ts
  modules/budgets/frontend/module/augment/planned-costs-form.ts
  modules/budgets/spec/features/budgets/update_budget_spec.rb
  modules/budgets/spec/support/pages/budget_form.rb
  modules/costs/app/views/costlog/edit.html.erb
  modules/costs/spec/features/cost_entries/add_cost_entry_spec.rb
Labels: bugfix, needs review

#10059 [40031] Left-side search pane to add existing work packages to team planner
  frontend/src/app/features/calendar/op-calendar.service.ts
  frontend/src/app/features/team-planner/team-planner/add-work-packages/add-existing-pane.component.html
  frontend/src/app/features/team-planner/team-planner/add-work-packages/add-existing-pane.component.sass
  frontend/src/app/features/team-planner/team-planner/add-work-packages/add-existing-pane.component.ts
  frontend/src/app/features/team-planner/team-planner/assignee/add-assignee.component.html
  frontend/src/app/features/team-planner/team-planner/assignee/add-assignee.component.ts
  frontend/src/app/features/team-planner/team-planner/assignee/tp-assignee.sass
  frontend/src/app/features/team-planner/team-planner/calendar-drag-drop.service.ts
  frontend/src/app/features/team-planner/team-planner/page/team-planner-page.component.ts
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.html
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.sass
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.ts
  frontend/src/app/features/team-planner/team-planner/team-planner.module.ts
  frontend/src/app/features/work-packages/components/wp-buttons/wp-status-button/wp-status-button.component.sass
  frontend/src/app/features/work-packages/components/wp-buttons/wp-status-button/wp-status-button.component.ts
  frontend/src/app/features/work-packages/components/wp-buttons/wp-status-button/wp-status-button.html
  frontend/src/app/features/work-packages/components/wp-card-view/wp-single-card/wp-single-card.component.html
  frontend/src/app/features/work-packages/components/wp-card-view/wp-single-card/wp-single-card.component.sass
  frontend/src/app/features/work-packages/components/wp-card-view/wp-single-card/wp-single-card.component.ts
  frontend/src/assets/images/team-planner/add-existing-pane--empty-state.svg
  frontend/src/global_styles/content/_calendars.sass
  frontend/src/global_styles/content/modules/_team_planner.sass
  frontend/src/global_styles/vendor/_full_calendar.sass
  modules/boards/spec/features/support/board_page.rb
  modules/team_planner/config/locales/js-en.yml
  modules/team_planner/spec/features/team_planner_add_existing_work_packages_spec.rb
  modules/team_planner/spec/support/components/add_existing_pane.rb
  modules/team_planner/spec/support/pages/team_planner.rb
Labels: feature, pullpreview

#10045 [40033] Tab info does not update when closing the split screen
  frontend/src/app/core/html/op-title.service.ts
  frontend/src/app/features/boards/board/board-partitioned-page/board-partitioned-page.component.ts
  frontend/src/app/features/in-app-notifications/center/in-app-notification-center-page.component.ts
  frontend/src/app/features/work-packages/routing/partitioned-query-space-page/partitioned-query-space-page.component.ts
  spec/features/notifications/notification_center/split_screen_spec.rb
Labels: bugfix, needs review

#10021 [40038] Make team planner only accessible with EE token
  app/assets/images/enterprise/team-planner.png
  app/controllers/custom_actions_controller.rb
  app/services/authorization/enterprise_service.rb
  app/views/common/upsale.html.erb
  app/views/placeholder_users/index.html.erb
  config/locales/en.yml
  frontend/src/assets/fonts/openproject_icon/openproject-icon-font.svg
  frontend/src/assets/fonts/openproject_icon/openproject-icon-font.ttf
  frontend/src/assets/fonts/openproject_icon/openproject-icon-font.woff
  frontend/src/assets/fonts/openproject_icon/openproject-icon-font.woff2
  frontend/src/global_styles/content/_enterprise.sass
  frontend/src/global_styles/fonts/_openproject_icon_definitions.scss
  frontend/src/global_styles/fonts/_openproject_icon_font.lsg
  modules/team_planner/app/controllers/team_planner/team_planner_controller.rb
  modules/team_planner/app/views/team_planner/team_planner/upsale.html.erb
  modules/team_planner/config/locales/en.yml
  modules/team_planner/config/routes.rb
  modules/team_planner/lib/open_project/team_planner/engine.rb
  modules/team_planner/spec/features/query_handling_spec.rb
  modules/team_planner/spec/features/team_planner_add_existing_work_packages_spec.rb
  modules/team_planner/spec/features/team_planner_create_spec.rb
  modules/team_planner/spec/features/team_planner_error_handling_spec.rb
  modules/team_planner/spec/features/team_planner_spec.rb
  modules/team_planner/spec/features/team_planner_user_interaction_spec.rb
  modules/team_planner/spec/features/team_planner_view_modes_spec.rb
  modules/two_factor_authentication/app/views/two_factor_authentication/upsale.html.erb
  modules/two_factor_authentication/config/locales/en.yml
  spec/features/placeholder_users/index_spec.rb
  vendor/openproject-icon-font/src/medal.svg
Labels: feature

#10111 [40744] Date picker for the wp split view in the calendar module misaligned
  frontend/src/app/shared/components/modal/modal-overlay.sass
Labels: bugfix
