Repository opf/openproject, pull requests merged in 2022-11, with the labels that each got.

#11503 [44481]Expandable Enterprise Edition banners
  app/views/admin/settings/projects_settings/show.html.erb
  app/views/admin/settings/work_packages_settings/_enterprise_feature_hint.html.erb
  app/views/custom_fields/_form.html.erb
  app/views/custom_fields/_tab.html.erb
  app/views/projects/filters/_form.html.erb
  app/views/statuses/_form.html.erb
  app/views/types/form/_form_configuration.html.erb
  frontend/src/app/shared/components/enterprise-banner/enterprise-banner.component.html
  frontend/src/app/shared/components/enterprise-banner/enterprise-banner.component.sass
  frontend/src/app/shared/components/enterprise-banner/enterprise-banner.component.ts
Labels: feature

#11498 Bug/43553 move workpackage in other project error
  app/controllers/work_packages/moves_controller.rb
  app/models/custom_field.rb
  app/models/permitted_params.rb
  app/views/work_packages/moves/new.html.erb
  spec/features/work_packages/bulk/move_work_package_spec.rb
Labels: needs review

#11488 documentation/support-1453-correcting-paths-in-docker
  docs/installation-and-operations/operation/restoring/README.md
Labels: documentation, needs review

#11545 Documentation/44766 user guide work package table configuration edit section about flat list OP#44766
  docs/user-guide/work-packages/work-package-table-configuration/README.md
Labels: documentation, needs review

#11484 [#43696] Add modal navigation on chevrons
  docs/api/apiv3/openapi-spec.yml
  frontend/src/app/core/state/file-links/file-links.service.ts
  frontend/src/app/shared/components/file-links/file-picker-modal/file-picker-modal.component.ts
  frontend/src/app/shared/components/file-links/file-picker-modal/file-picker-modal.html
  frontend/src/app/shared/components/file-links/storage-file-list-item/storage-file-list-item.component.ts
  frontend/src/app/shared/components/file-links/storage-file-list-item/storage-file-list-item.html
  frontend/src/app/shared/components/file-links/storage-file-list-item/storage-file-list-item.ts
  modules/storages/app/common/storages/peripherals/storage_interaction/nextcloud_storage_query.rb
  modules/storages/config/locales/js-en.yml
  modules/storages/lib/api/v3/storage_files/storage_files_api.rb
  modules/storages/spec/common/peripherals/storage_requests_spec.rb
  modules/storages/spec/requests/api/v3/storages/storages_spec.rb
  spec/features/notifications/notification_center/notification_center_spec.rb
Labels: feature, pullpreview, needs review

#11546 [#44758] Permissions for viewing file links are not correct
  frontend/src/app/shared/components/file-links/file-link-list/file-link-list.html
Labels: bugfix, needs review

#11529 Fix font loading in storybook
  frontend/.storybook/SpotTheme.js
  frontend/.storybook/main.js
Labels: pullpreview

#11548 Extract rendering of search form into helper
  app/views/layouts/base.html.erb
  lib/redmine/menu_manager/top_menu_helper.rb
Labels: maintenance, needs review

#11551 Documentation/44771 user guide wysiwyg editor in openproject links (typo fix) OP#44771
  docs/user-guide/work-packages/work-package-table-configuration/README.md
  docs/user-guide/wysiwyg/README.md
Labels: documentation, needs review

#11539 [#43698] Add select all
  frontend/src/app/core/state/storage-files/storage-files.service.ts
  frontend/src/app/shared/components/file-links/file-picker-modal/file-picker-modal.component.ts
  frontend/src/app/shared/components/file-links/file-picker-modal/file-picker-modal.html
  frontend/src/app/spot/icon-font/src/activity-history.svg
  frontend/src/app/spot/icon-font/src/add-attachment.svg
  frontend/src/app/spot/icon-font/src/cancel-circle.svg
  frontend/src/app/spot/icon-font/src/checkmark-circle.svg
  frontend/src/app/spot/icon-font/src/date-alerts.svg
  frontend/src/app/spot/icon-font/src/dropdown-open.svg
  frontend/src/app/spot/icon-font/src/dropdown.svg
  frontend/src/app/spot/icon-font/src/enterprise-badge.svg
  frontend/src/app/spot/icon-font/src/select-all.svg
  frontend/src/app/spot/styles/sass/common/icon.sass
  frontend/src/assets/fonts/openproject_icon/openproject-icon-font.svg
  frontend/src/assets/fonts/openproject_icon/openproject-icon-font.ttf
  frontend/src/assets/fonts/openproject_icon/openproject-icon-font.woff
  frontend/src/assets/fonts/openproject_icon/openproject-icon-font.woff2
  frontend/src/global_styles/fonts/_openproject_icon_definitions.sass
  frontend/src/global_styles/fonts/_openproject_icon_font.lsg
  frontend/src/stories/ActionBarMoreButtons.example.html
  modules/storages/config/locales/js-en.yml
Labels: feature

#11589 [#44767] Anonymouse User has Nextcloud access token
  frontend/src/app/features/work-packages/components/wp-single-view-tabs/files-tab/op-files-tab.component.ts
  frontend/src/app/shared/components/file-links/file-link-list/file-link-list.component.ts
Labels: bugfix, needs review

#11581 [#44842] User guide: Give hint for the commands in the text editor h… OP#44842
  docs/user-guide/wysiwyg/README.md
Labels: documentation, needs review

#11597 Keep duration when setting dates from soonest start date
  app/services/work_packages/schedule_dependency/dependency.rb
  app/services/work_packages/set_schedule_service.rb
  spec/models/projects/exporter/exportable_project_context.rb
  spec/services/work_packages/set_schedule_service_working_days_spec.rb
Labels: needs review

#11580 Add date alerts to reasons
  config/locales/js-en.yml
  frontend/.eslintrc.js
  frontend/src/app/core/state/in-app-notifications/in-app-notification.model.ts
  frontend/src/app/features/in-app-notifications/center/state/ian-center.service.ts
  frontend/src/app/features/in-app-notifications/entry/actors-line/in-app-notification-actors-line.component.html
  frontend/src/app/features/in-app-notifications/entry/actors-line/in-app-notification-actors-line.component.sass
  frontend/src/app/features/in-app-notifications/entry/actors-line/in-app-notification-actors-line.component.ts
  frontend/src/app/features/in-app-notifications/entry/date-alert/in-app-notification-date-alert.component.html
  frontend/src/app/features/in-app-notifications/entry/date-alert/in-app-notification-date-alert.component.sass
  frontend/src/app/features/in-app-notifications/entry/date-alert/in-app-notification-date-alert.component.ts
  frontend/src/app/features/in-app-notifications/entry/in-app-notification-entry.component.html
  frontend/src/app/features/in-app-notifications/entry/in-app-notification-entry.component.sass
  frontend/src/app/features/in-app-notifications/entry/in-app-notification-entry.component.ts
  frontend/src/app/features/in-app-notifications/in-app-notifications.module.ts
  lib/api/v3/notifications/notifications_api.rb
  spec/features/notifications/notification_center/notification_center_date_alerts_spec.rb
  spec/support/pages/notifications/center.rb
  spec/workers/notifications/create_date_alerts_notifications_job_spec.rb
Labels: feature, needs review

#11600 Add the Enterprise Edition guard on date alerts creation
  app/services/authorization/enterprise_service.rb
  app/workers/notifications/create_date_alerts_notifications_job.rb
  spec/support/shared/with_ee.rb
  spec/workers/notifications/create_date_alerts_notifications_job_spec.rb
Labels: needs review

#11578 Add native / custom schemes to form-action CSP
  app/controllers/oauth/auth_base_controller.rb
  spec/requests/auth/oauth_login_csp_spec.rb
Labels: bugfix, needs review

#11579 [#44825] Add .env to Environment Configuration Docs
  docs/installation-and-operations/configuration/README.md
  docs/installation-and-operations/configuration/database/README.md
  docs/installation-and-operations/configuration/environment/README.md
  docs/installation-and-operations/configuration/plugins/README.md
  docs/installation-and-operations/configuration/repositories/README.md
  docs/installation-and-operations/configuration/server/README.md
  docs/installation-and-operations/configuration/ssl/README.md
  docs/installation-and-operations/installation/docker/README.md
  docs/installation-and-operations/installation/packaged/README.md
Labels: documentation, needs review

#11601 Feature/44702 team planner add work week option to visible time scale
  frontend/src/app/core/days/weekday.service.ts
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.html
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.sass
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.ts
  frontend/src/app/features/team-planner/team-planner/team-planner.module.ts
  frontend/src/app/features/team-planner/team-planner/view-select/view-select-menu.directive.ts
  frontend/src/global_styles/content/modules/_team_planner.sass
  modules/team_planner/config/locales/js-en.yml
  modules/team_planner/spec/features/team_planner_dates_spec.rb
  modules/team_planner/spec/features/team_planner_spec.rb
  modules/team_planner/spec/features/team_planner_view_modes_spec.rb
  modules/team_planner/spec/support/pages/team_planner.rb
Labels: pullpreview

#11607 Revert timezone setting back to string, validate using canonical
  app/models/setting.rb
  config/constants/settings/definition.rb
  config/constants/settings/definitions.rb
  lib/core_extensions.rb
  lib/core_extensions/time_zone.rb
  spec/constants/settings/definition_spec.rb
  spec/features/users/my_spec.rb
Labels: bugfix, needs review

#11612 Allow choosing "Based on user's language" for first_day_of_week and start_of_week
  app/models/setting.rb
  spec/models/setting_spec.rb
Labels: bugfix, needs review

#11570 [#44763] Add information about Attachments to Enterprise Cloud Backup
  docs/enterprise-guide/enterprise-cloud-guide/backups/README.md
  docs/enterprise-guide/enterprise-cloud-guide/backups/backup-enterprise-cloud.png
Labels: documentation, needs review

#11611 Fix history icon for wiki and meeting (#44745)
  app/views/wiki/show.html.erb
  modules/meeting/app/helpers/meeting_contents_helper.rb
Labels: bugfix, needs review

#11620 Set overdue default value to "No notification"
  frontend/src/app/features/user-preferences/notifications-settings/table/notification-settings-table.component.ts
Labels: bugfix, needs review

#11622 Include Capybara::RSpecMatchers to speed up Capybara negative assertion matchers
  modules/bim/spec/support/components/xeokit_model_tree.rb
  modules/reporting/spec/features/support/components/cost_reports_base_table.rb
  modules/storages/spec/support/components/file_picker_dialog.rb
  modules/team_planner/spec/support/components/add_existing_pane.rb
  spec/features/categories/categories_page.rb
  spec/features/custom_fields/custom_fields_page.rb
  spec/features/repositories/repository_settings_page.rb
  spec/features/support/components/attribute_help_text_modal.rb
  spec/features/support/components/danger_zone.rb
  spec/features/support/components/time_logging_modal.rb
  spec/features/work_packages/work_packages_page.rb
  spec/support/components/admin/type_configuration_form.rb
  spec/support/components/attachments/attachments.rb
  spec/support/components/common/modal.rb
  spec/support/components/common/sidemenu.rb
  spec/support/components/confirmation_dialog.rb
  spec/support/components/datepicker/datepicker.rb
  spec/support/components/global_search.rb
  spec/support/components/grids/grid_area.rb
  spec/support/components/html_title.rb
  spec/support/components/menu/dropdown.rb
  spec/support/components/password_confirmation_dialog.rb
  spec/support/components/project_include_component.rb
  spec/support/components/projects/top_menu.rb
  spec/support/components/table_pagination.rb
  spec/support/components/timelines/configuration_modal.rb
  spec/support/components/timelines/timeline_row.rb
  spec/support/components/work_packages/activities.rb
  spec/support/components/work_packages/columns.rb
  spec/support/components/work_packages/context_menu.rb
  spec/support/components/work_packages/destroy_modal.rb
  spec/support/components/work_packages/display_representation.rb
  spec/support/components/work_packages/filters.rb
  spec/support/components/work_packages/group_by.rb
  spec/support/components/work_packages/hierarchies.rb
  spec/support/components/work_packages/query_menu.rb
  spec/support/components/work_packages/query_title.rb
  spec/support/components/work_packages/relations.rb
  spec/support/components/work_packages/settings_menu.rb
  spec/support/components/work_packages/sort_by.rb
  spec/support/components/work_packages/table_configuration/graph_general.rb
  spec/support/components/work_packages/table_configuration/highlighting.rb
  spec/support/components/work_packages/table_configuration_modal.rb
  spec/support/components/work_packages/tabs_counter.rb
  spec/support/components/wysiwyg/wysiwyg_editor.rb
  spec/support/edit_fields/edit_field.rb
  spec/support/form_fields/form_field.rb
  spec/support/pages/work_packages/work_package_cards.rb
  spec/views/layouts/base.html.erb_spec.rb
Labels: needs review

#11632 Bug/44926 error in source string for team planner (2) OP#44926
  docs/user-guide/team-planner/README.md
Labels: documentation, needs review

#11629 [43305] Mobile: The mark as read icon in the notification centre is not visible
  frontend/src/app/features/in-app-notifications/entry/in-app-notification-entry.component.sass
Labels: bugfix

#11634 [44903] Initial focus not within work package export modal
  frontend/src/app/shared/components/modals/export-modal/wp-table-export.modal.html
Labels: bugfix

#11636 Fix 'Watcher' row appearing twice in project notification settings
  frontend/src/app/features/user-preferences/notifications-settings/table/notification-settings-table.component.html
Labels: bugfix, needs review

#11640 [#44916] File picker does not load directory listing when OAuth token is expired
  app/services/oauth_clients/connection_manager.rb
  modules/storages/app/common/storages/peripherals/storage_interaction/nextcloud_storage_query.rb
  modules/storages/app/common/storages/peripherals/storage_interaction/storage_queries.rb
  modules/storages/app/services/storages/file_link_sync_service.rb
  modules/storages/spec/common/peripherals/storage_requests_spec.rb
  modules/storages/spec/features/create_file_links_spec.rb
Labels: bugfix, needs review

#11533 Refactor top-menu into global service with rxjs observable
  app/views/layouts/base.html.erb
  frontend/src/app/app.module.ts
  frontend/src/app/core/main-menu/main-menu-toggle.component.html
  frontend/src/app/core/main-menu/main-menu-toggle.component.ts
  frontend/src/app/core/main-menu/main-menu-toggle.service.ts
  frontend/src/app/core/setup/globals/global-listeners.ts
  frontend/src/app/core/setup/globals/global-listeners/action-menu.ts
  frontend/src/app/core/setup/globals/global-listeners/top-menu.ts
  frontend/src/app/core/top-menu/top-menu.service.ts
Labels: maintenance, needs review

#11657 Fix viewpoint seeding in multitenancy
  modules/bim/lib/open_project/bim/bcf_xml/issue_reader.rb
Labels: bugfix

#11563 Allow set_default to set setting only if empty and writable
  app/seeders/demo_data/project_seeder.rb
Labels: bugfix, needs review

#11661 Filter dateAlerts from activity tab badge counter
  frontend/src/app/features/work-packages/components/wp-tabs/services/wp-tabs/wp-notifications-count.function.ts
  frontend/src/app/features/work-packages/routing/wp-view-base/state/wp-single-view.service.ts
  spec/features/notifications/notification_center/notification_center_date_alerts_spec.rb
  spec/support/components/work_packages/activities.rb
Labels: bugfix, needs review

#11643 Allow LDAP auth sources to set verify_mode and expected TLS certificate
  app/controllers/auth_sources_controller.rb
  app/models/ldap_auth_source.rb
  app/models/permitted_params.rb
  app/views/ldap_auth_sources/_form.html.erb
  config/locales/en.yml
  db/migrate/20221115082403_add_ldap_tls_options.rb
  spec/factories/auth_source_factory.rb
  spec/fixtures/ldap/snakeoil.pem
  spec/models/ldap_auth_source_spec.rb
Labels: bugfix, feature

#11675 FAQ docs update
  docs/faq/README.md
Labels: documentation

#11673 [#40162] Update installation script to ensure successful installation…
  docs/enterprise-guide/enterprise-on-premises-guide/support/installation-support/script/op-support-data.sh
Labels: documentation

#11649 Handle unavailable attachments in backup job
  app/workers/backup_job.rb
Labels: bugfix

#11662 Provide same post-logout flow for OIDC as with SAML
  modules/openid_connect/lib/open_project/openid_connect/engine.rb
Labels: bugfix

#11644 [43298] Copy button is misplaced in Github tab
  frontend/src/app/spot/styles/sass/components/form-field.sass
  modules/github_integration/frontend/module/git-actions-menu/styles/git-actions-menu.sass
Labels: bugfix

#11670 Fix alignment of admin sidemenu enterprise badge
  frontend/src/app/shared/components/sidemenu/sidemenu.component.sass
  frontend/src/global_styles/layout/_main_menu.sass
  lib/redmine/menu_manager/menu_helper.rb
Labels: pullpreview

#11677 [#44876] Implement API endpoint for creating upload link
  modules/storages/app/common/storages/peripherals/storage_requests.rb
  modules/storages/lib/api/v3/storage_files/storage_files_api.rb
  modules/storages/lib/api/v3/storage_files/storage_upload_link_representer.rb
  modules/storages/lib/open_project/storages/engine.rb
  modules/storages/spec/lib/api/v3/storage_files/storage_upload_link_representer_spec.rb
  modules/storages/spec/requests/api/v3/storages/storages_spec.rb
Labels: feature

#11689 Update spot shadows
  frontend/src/app/spot/styles/tokens/dist/tokens.json
  frontend/src/app/spot/styles/tokens/dist/tokens.sass
  frontend/src/app/spot/styles/tokens/shadows.yml
Labels: pullpreview

#11616 Docs update for 12.4
  docs/getting-started/my-account/README.md
  docs/installation-and-operations/configuration/README.md
  docs/installation-and-operations/installation/docker/README.md
  docs/release-notes/12-2-0/README.md
  docs/release-notes/12-2-1/README.md
  docs/system-admin-guide/authentication/two-factor-authentication/README.md
  docs/system-admin-guide/integrations/nextcloud/NC_admin-defaults-user-options.png
  docs/system-admin-guide/integrations/nextcloud/README.md
  docs/system-admin-guide/users-permissions/users/README.md
  docs/user-guide/README.md
  docs/user-guide/notifications/NotificationCenter-12.4-badge.png
  docs/user-guide/notifications/NotificationCenter-12.4-inbox.png
  docs/user-guide/notifications/NotificationCenter-12.4-splitScreenView.png
  docs/user-guide/notifications/README.md
  docs/user-guide/notifications/notification-settings/Notification-settings-12.4-Participating.png
  docs/user-guide/notifications/notification-settings/Notification-settings-12.4-dateAlerts.png
  docs/user-guide/notifications/notification-settings/Notification-settings-12.4-fromNotificationCenter.png
  docs/user-guide/notifications/notification-settings/Notification-settings-12.4-nonPartipating.png
  docs/user-guide/notifications/notification-settings/Notification-settings-12.4-overall.png
  docs/user-guide/notifications/notification-settings/Notification-settings-12.4-projectSpecific.png
  docs/user-guide/notifications/notification-settings/README.md
  docs/user-guide/notifications/notification-settings/notification-settings.png
  docs/user-guide/team-planner/README.md
  docs/user-guide/team-planner/TeamPlanner-12.4-addAssignee.png
  docs/user-guide/team-planner/TeamPlanner-12.4-addExisting.png
  docs/user-guide/team-planner/TeamPlanner-12.4-emptyNew.png
  docs/user-guide/team-planner/TeamPlanner-12.4-hoverWorkPackageCard-dragHandles.png
  docs/user-guide/team-planner/TeamPlanner-12.4-hoverWorkPackageCard.png
  docs/user-guide/team-planner/TeamPlanner-12.4-listAllAvailable.png
  docs/user-guide/team-planner/TeamPlanner-12.4-newTask-drag.png
  docs/user-guide/team-planner/TeamPlanner-12.4-newTask-splitScreen.png
  docs/user-guide/team-planner/TeamPlanner-12.4-oneWeek.png
  docs/user-guide/team-planner/TeamPlanner-12.4-removeAssigneeDates.png
  docs/user-guide/team-planner/TeamPlanner-12.4-splitScreen.png
  docs/user-guide/team-planner/TeamPlanner-12.4-twoWeeks.png
Labels: documentation

#11712 fix(markdown): adjust invalid/broken format [skip ci]
  docs/system-admin-guide/authentication/saml/README.md
Labels: documentation

#11686 [43253] Wrong right margin in the side menu new team planner button
  frontend/src/global_styles/content/_sidebar.sass
Labels: pullpreview

#11577 Adding docs for more components and patterns on Storybook
  .gitignore
  frontend/src/app/spot/components/text-field/stories/TextField.stories.mdx
  frontend/src/app/spot/components/tooltip/stories/Tooltip.stories.mdx
  frontend/src/stories/DropdownButton.stories.mdx
  frontend/src/stories/DropdownMenu.stories.mdx
  frontend/src/stories/SectionHeaders.stories.mdx
  frontend/src/stories/Toast.stories.mdx
Labels: pullpreview

#11723 [44962] Re-think and harmonize the icon used for premium/enterprise features
  app/views/common/upsale.html.erb
  app/views/homescreen/blocks/_upsale.html.erb
  config/initializers/menus.rb
  config/locales/en.yml
  config/locales/js-en.yml
  frontend/src/app/shared/components/enterprise-banner/enterprise-banner.component.html
  frontend/src/app/shared/components/enterprise-page/enterprise-page.component.html
  frontend/src/app/shared/components/sidemenu/sidemenu.component.html
  frontend/src/app/spot/icon-font/src/dropdown.svg
  frontend/src/app/spot/icon-font/src/enterprise-addons.svg
  frontend/src/app/spot/styles/sass/common/icon.sass
  frontend/src/assets/fonts/openproject_icon/openproject-icon-font.svg
  frontend/src/assets/fonts/openproject_icon/openproject-icon-font.ttf
  frontend/src/assets/fonts/openproject_icon/openproject-icon-font.woff
  frontend/src/assets/fonts/openproject_icon/openproject-icon-font.woff2
  frontend/src/global_styles/common/menu/menu.sass
  frontend/src/global_styles/content/_enterprise.sass
  frontend/src/global_styles/fonts/_openproject_icon_definitions.sass
  frontend/src/global_styles/fonts/_openproject_icon_font.lsg
  frontend/src/global_styles/layout/_main_menu.sass
  lib/redmine/menu_manager/menu_helper.rb
  modules/boards/lib/open_project/boards/engine.rb
  modules/two_factor_authentication/lib/open_project/two_factor_authentication/engine.rb
Labels: pullpreview

#11730 Submit date fields when tabbing outside or clicking enter
  frontend/src/app/shared/components/fields/edit/field-types/date-edit-field/date-edit-field.component.ts
  frontend/src/app/shared/components/op-date-picker/date-picker.directive.ts
  frontend/src/app/shared/components/op-date-picker/op-single-date-picker/op-single-date-picker.component.html
  frontend/src/app/shared/components/op-date-picker/op-single-date-picker/op-single-date-picker.component.ts
  spec/features/work_packages/details/custom_fields/custom_field_spec.rb
Labels: bugfix
