Repository opf/openproject, pull requests merged in 2022-03, with the labels that each got.

#10229 [41080] Pass selection of cards from add existing to calendar service
  frontend/src/app/features/calendar/op-calendar.service.ts
  frontend/src/app/features/calendar/wp-calendar/wp-calendar.component.ts
  frontend/src/app/features/team-planner/team-planner/add-work-packages/add-existing-pane.component.html
  frontend/src/app/features/team-planner/team-planner/add-work-packages/add-existing-pane.component.ts
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.html
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.ts
  frontend/src/app/features/work-packages/components/wp-card-view/wp-single-card/wp-single-card.component.html
  frontend/src/app/features/work-packages/components/wp-card-view/wp-single-card/wp-single-card.component.ts
  modules/team_planner/spec/features/team_planner_add_existing_work_packages_spec.rb
  modules/team_planner/spec/support/components/add_existing_pane.rb
Labels: feature, needs review

#10233 [41073] Add empty state image and button to team planner
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.html
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.sass
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.ts
  frontend/src/assets/images/team-planner/empty-state.svg
Labels: feature, needs review

#10237 [41310] Avoid outputting internal statement errors
  lib/api/errors/internal_error.rb
Labels: bugfix, needs review

#10246 fix/doc-urls
  docs/release-notes/10-3-0/README.md
  docs/release-notes/11-3-0/README.md
  docs/user-guide/notifications/4.PNG
  docs/user-guide/notifications/IaN-2.PNG
  docs/user-guide/notifications/IaN-3.PNG
  docs/user-guide/notifications/IaN4.PNG
  docs/user-guide/notifications/In-app Notifications 4-16363871439641-16363916505421.png
  docs/user-guide/notifications/In-app Notifications 4-16363871439641.PNG
  docs/user-guide/notifications/In-app Notifications 4-16363899013582.PNG
  docs/user-guide/notifications/In-app Notifications 4-16363918684191.PNG
  docs/user-guide/notifications/In-app Notifications 4.PNG
  docs/user-guide/notifications/In-app Notifications 5.PNG
  docs/user-guide/notifications/In-app Notifications 6.PNG
  docs/user-guide/notifications/image-20211108104621920.png
  docs/user-guide/notifications/image-20211111120316753.png
Labels: documentation

#10202 [#40228] amended apispec for changes to file links
  .redocly.lint-ignore.yaml
  docs/api/apiv3/components/schemas/file_link_model.yml
  docs/api/apiv3/components/schemas/file_links_model.yml
  docs/api/apiv3/components/schemas/project_model.yml
  docs/api/apiv3/components/schemas/work_package_create_form.yml
  docs/api/apiv3/components/schemas/work_package_create_form_for_project.yml
  docs/api/apiv3/components/schemas/work_package_edit_form.yml
  docs/api/apiv3/components/schemas/work_package_model.yml
  docs/api/apiv3/components/schemas/work_package_schema.yml
  docs/api/apiv3/components/schemas/work_packages_model.yml
  docs/api/apiv3/openapi-spec.yml
  docs/api/apiv3/paths/file_link.yml
  docs/api/apiv3/paths/file_link_open.yml
  docs/api/apiv3/paths/work_package_file_link_download.yml
  docs/api/apiv3/paths/work_package_file_links.yml
  docs/api/apiv3/paths/work_packages.yml
Labels: feature, documentation

#10240 [chore] excluded filters section
  lib/api/v3/queries/schemas/filter_dependency_representer_factory.rb
  lib/api/v3/queries/schemas/query_filter_instance_schema_representer.rb
  lib/api/v3/queries/schemas/query_schema_representer.rb
Labels: maintenance

#10219 [41213]Include projects - Loading skeleton view
  frontend/src/app/shared/components/project-include/project-include.component.html
  frontend/src/app/shared/components/project-include/project-include.component.sass
  frontend/src/app/shared/components/project-include/project-include.component.ts
  frontend/src/app/shared/shared.module.ts
  spec/support/components/project_include_component.rb
Labels: feature

#10252 [40856]Team planner animation
  app/assets/images/enterprise/team-planner.png
  app/assets/videos/enterprise/team-planner-animation.mp4
  app/controllers/custom_actions_controller.rb
  app/views/common/upsale.html.erb
  app/views/placeholder_users/index.html.erb
  frontend/src/global_styles/content/_enterprise.sass
  modules/team_planner/app/views/team_planner/team_planner/upsale.html.erb
  modules/two_factor_authentication/app/views/two_factor_authentication/upsale.html.erb
Labels: feature, pullpreview

#10264 [41134] Wrong name in mail for "wiki page has been updated by"
  app/services/wiki_pages/update_service.rb
Labels: bugfix, needs review

#10256 [chore] fix excluded filters
  app/models/queries/register.rb
  app/models/queries/work_packages.rb
  lib/api/v3/queries/schemas/filter_dependency_representer_factory.rb
  lib/api/v3/queries/schemas/query_filter_instance_schema_collection_representer.rb
Labels: bugfix

#10242 [40958] Updated placement and design of the create button in the sidebar
  app/views/work_packages/_menu_query_select.html.erb
  config/locales/js-en.yml
  frontend/src/app/core/setup/global-dynamic-components.const.ts
  frontend/src/app/core/setup/globals/onboarding/tours/boards_tour.ts
  frontend/src/app/features/bim/ifc_models/pages/viewer/styles/generic.sass
  frontend/src/app/features/boards/boards-sidebar/boards-menu.component.html
  frontend/src/app/features/boards/boards-sidebar/boards-menu.component.ts
  frontend/src/app/features/calendar/openproject-calendar.module.ts
  frontend/src/app/features/calendar/sidemenu/calendar-sidemenu.component.html
  frontend/src/app/features/calendar/sidemenu/calendar-sidemenu.component.ts
  frontend/src/app/features/team-planner/team-planner/sidemenu/team-planner-sidemenu.component.html
  frontend/src/app/features/team-planner/team-planner/sidemenu/team-planner-sidemenu.component.ts
  frontend/src/app/features/team-planner/team-planner/team-planner.module.ts
  frontend/src/app/shared/components/op-view-select/op-static-queries.service.ts
  frontend/src/app/shared/components/op-view-select/op-view-select.component.ts
  frontend/src/app/shared/shared.module.ts
  frontend/src/global_styles/content/_index.sass
  frontend/src/global_styles/content/_sidebar.sass
  frontend/src/global_styles/layout/_main_menu.sass
  modules/bim/app/views/bim/ifc_models/ifc_models/_panels.html.erb
  modules/boards/config/locales/js-en.yml
  modules/boards/lib/open_project/boards/engine.rb
  modules/boards/spec/features/board_navigation_spec.rb
  modules/boards/spec/features/boards_sorting_spec.rb
  modules/calendar/app/views/calendar/calendars/_menu.html.erb
  modules/calendar/config/locales/js-en.yml
  modules/team_planner/app/views/team_planner/team_planner/_menu.html.erb
  modules/team_planner/config/locales/js-en.yml
  modules/team_planner/spec/features/query_handling_spec.rb
  modules/team_planner/spec/features/team_planner_index_spec.rb
  modules/team_planner/spec/features/team_planner_menu_spec.rb
  modules/team_planner/spec/features/team_planner_upsale_spec.rb
Labels: feature, needs review

#10262 [40981] Change scrolling behavior of team planner
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.html
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.sass
Labels: feature, needs review

#10263 [41103] Configure boards modal has empty tab header
  frontend/src/app/features/boards/board/configuration-modal/board-configuration.modal.html
Labels: bugfix, needs review

#10250 Better template ID tracking for team planner
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.ts
Labels: maintenance, needs review

#10284 [40856] Team planner animation - fix test failed issues
  app/views/common/upsale.html.erb
  app/views/types/form/_form_configuration.html.erb
  frontend/src/global_styles/content/_enterprise.sass
  modules/ldap_groups/app/views/ldap_groups/synchronized_groups/upsale.html.erb
  modules/openid_connect/app/views/openid_connect/providers/upsale.html.erb
Labels: feature

#10269 Add open_?project to sentry app patterns
  config/initializers/sentry.rb
Labels: maintenance

#10300 [#41322] Decision about Cloud status landing page [skip ci]
  docs/enterprise-guide/enterprise-cloud-guide/openproject-cloud-status/README.md
Labels: documentation

#10301 [41416] Fix API docs naming custom_objects -> custom_options
  docs/api/apiv3/components/schemas/custom_option_model.yml
  docs/api/apiv3/openapi-spec.yml
  docs/api/apiv3/paths/custom_option.yml
  docs/api/apiv3/tags/custom_options.yml
Labels: documentation, needs review

#10265 [40859] Today column is not highlighted in FF
  frontend/src/global_styles/vendor/_full_calendar.sass
Labels: bugfix, styling, needs review

#10310 feat(docs): cherry-pick some dev only changes
  docs/development/concepts/queries/README.md
  docs/development/security/README.md
  docs/development/translate-openproject/CrowdIn1.png
  docs/development/translate-openproject/CrowdIn2.png
  docs/development/translate-openproject/CrowdIn3.png
  docs/development/translate-openproject/README.md
  docs/development/translate-openproject/crowdin-editor.png
  docs/development/translate-openproject/crowdin-language-overview.png
  docs/development/translate-openproject/crowdin-multi-translation.png
  docs/development/translate-openproject/crowdin-overview.png
  docs/installation-and-operations/configuration/README.md
  docs/installation-and-operations/misc/custom-openid-connect-providers/README.md
  docs/release-notes/10-5-0/README.md
  docs/system-admin-guide/system-settings/attachments/README.md
  docs/system-admin-guide/users-permissions/roles-permissions/README.md
  docs/user-guide/wiki/wiki-faq/README.md
  docs/user-guide/work-packages/edit-work-package/README.md
Labels: documentation

#10312 feat(docs): bim images & link fixes
  docs/bim-guide/README.md
  docs/bim-guide/bim-issue-management/README.md
  docs/bim-guide/revit-add-in/README.md
  docs/bim-guide/revit-add-in/installation-step-01.png
  docs/bim-guide/revit-add-in/installation-step-02.png
  docs/bim-guide/revit-add-in/installation-step-03.png
  docs/bim-guide/revit-add-in/installer-smart-screen-01.png
  docs/bim-guide/revit-add-in/installer-smart-screen-02.png
Labels: documentation

#10321 fix(docs): adjust 404 links & anchors
  docs/faq/README.md
  docs/getting-started/my-account/README.md
  docs/system-admin-guide/users-permissions/roles-permissions/README.md
  docs/user-guide/repository/README.md
Labels: documentation

#10305 Fix team planner crash when adding a wp from the add existing pane
  frontend/src/app/shared/components/principal/principal.component.ts
Labels: pullpreview

#10272 [41235] Add loading indicator toast for team planner
  config/locales/js-en.yml
  frontend/src/app/features/team-planner/team-planner/page/team-planner-page.component.ts
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.actions.ts
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.ts
  frontend/src/app/shared/components/toaster/toast.component.html
  frontend/src/app/shared/components/toaster/toast.component.ts
  frontend/src/app/shared/components/toaster/toast.service.ts
  frontend/src/global_styles/content/_loading_indicator.sass
  frontend/src/global_styles/content/_toast.sass
Labels: feature, needs review

#10333 fix(docs): lowercase folder name
  docs/development/security/README.md
  docs/enterprise-guide/README.md
  docs/enterprise-guide/enterprise-cloud-guide/README.md
  docs/enterprise-guide/enterprise-cloud-guide/gdpr-compliance/DPA.png
  docs/enterprise-guide/enterprise-cloud-guide/gdpr-compliance/README.md
Labels: documentation

#10319 Remove webfonts generator due to outdated dependencies
  frontend/package-lock.json
  frontend/package.json
Labels: maintenance, needs review

#10336 [#40436] Update LDAP documentation
  docs/system-admin-guide/authentication/ldap-authentication/ldap-group-synchronization/README.md
Labels: documentation, needs review

#10348 [41483] Milestones show dashes without dates
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.ts
Labels: bugfix, needs review

#10347 [40863] Hide 1-week and 2-week buttons when split screen is opened
  frontend/src/global_styles/content/modules/_team_planner.sass
Labels: bugfix, styling, needs review

#10309 [40755] Add context menu to team planner / calendar
  frontend/src/app/core/routing/openproject.routes.ts
  frontend/src/app/features/calendar/op-calendar.service.ts
  frontend/src/app/features/calendar/wp-calendar/wp-calendar.component.ts
  frontend/src/app/features/calendar/wp-calendar/wp-calendar.template.html
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.html
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.ts
  frontend/src/app/features/work-packages/components/wp-card-view/wp-single-card/wp-single-card.component.html
  frontend/src/app/features/work-packages/components/wp-card-view/wp-single-card/wp-single-card.component.ts
  frontend/src/app/shared/components/op-context-menu/op-context-menu-handler.ts
  frontend/src/app/shared/components/op-context-menu/op-context-menu.service.ts
  modules/team_planner/spec/features/shared_context.rb
  modules/team_planner/spec/features/team_planner_context_menu_spec.rb
  spec/features/work_packages/table/context_menu/context_menu_shared_examples.rb
  spec/features/work_packages/table/context_menu/context_menu_spec.rb
  spec/features/work_packages/table/context_menu_spec.rb
  spec/support/components/work_packages/context_menu.rb
Labels: feature, pullpreview, needs review

#10352 fix(docs): adjust anchors
  docs/faq/README.md
  docs/installation-and-operations/README.md
Labels: documentation

#10343 [41810] Disabled tooltips overlap the left side of the team planner
  frontend/src/app/features/team-planner/team-planner/add-work-packages/add-existing-pane.component.ts
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.ts
  frontend/src/app/features/work-packages/components/wp-card-view/wp-single-card/wp-single-card.component.html
  frontend/src/app/features/work-packages/components/wp-card-view/wp-single-card/wp-single-card.component.sass
  frontend/src/app/features/work-packages/components/wp-card-view/wp-single-card/wp-single-card.component.ts
Labels: bugfix, styling, needs review

#10346 [40958] Fine tuning for sidebar create button
  frontend/src/app/features/boards/boards-sidebar/boards-menu.component.html
  frontend/src/app/features/calendar/sidemenu/calendar-sidemenu.component.html
  frontend/src/app/spot/styles/sass/components/button.sass
  frontend/src/global_styles/content/_sidebar.sass
Labels: bugfix, needs review

#10358 Add paginated request helper
  frontend/src/app/core/apiv3/endpoints/work_packages/api-v3-work-packages-paths.ts
  frontend/src/app/core/apiv3/helpers/get-paginated-results.ts
  frontend/src/app/core/apiv3/paths/apiv3-list-resource.interface.ts
  frontend/src/app/core/current-user/current-user.service.ts
  frontend/src/app/features/hal/services/hal-resource.service.ts
  frontend/src/app/shared/components/project-include/project-include.component.ts
Labels: feature, needs review

#10360 [40323] Empty state is visible during team planner query reload
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.html
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.ts
Labels: bugfix, needs review

#10362 [41453] Use valid_values! to get assignee count
  modules/team_planner/app/cells/team_planner/row_cell.rb
Labels: bugfix

#10350 Remove "oneOf" in case of a single referenced schema.
  docs/api/apiv3/components/schemas/file_link_model.yml
Labels: documentation

#10363 Bug/40989 wrong screenshot for log unit costs release
  docs/user-guide/time-and-costs/cost-tracking/README.md
Labels: documentation

#10278 Fix error when changing parent of sub-sub-work_package
  app/services/work_packages/update_ancestors_service.rb
  spec/services/work_packages/update_ancestors_service_spec.rb
Labels: bugfix, contribution

#10364 [41511] Make basic boards a CE feature
  frontend/src/app/features/boards/board/board-actions/board-actions-registry.service.ts
  frontend/src/app/features/boards/board/board-partitioned-page/board-list-container.component.html
  frontend/src/app/features/boards/board/board-partitioned-page/board-list-container.component.ts
  frontend/src/app/features/boards/boards-sidebar/boards-menu.component.ts
  frontend/src/app/features/boards/index-page/boards-index-page.component.html
  frontend/src/app/features/boards/index-page/boards-index-page.component.ts
  frontend/src/app/features/boards/new-board-modal/new-board-modal.component.ts
  frontend/src/app/features/boards/new-board-modal/new-board-modal.html
  frontend/src/app/features/boards/tile-view/tile-view.component.html
  frontend/src/app/features/boards/tile-view/tile-view.component.sass
  frontend/src/app/features/boards/tile-view/tile-view.component.spec.ts
  frontend/src/app/features/boards/tile-view/tile-view.component.ts
  frontend/src/app/shared/components/enterprise-banner/enterprise-banner.component.ts
  modules/boards/config/locales/js-en.yml
  modules/boards/spec/features/board_enterprise_spec.rb
  modules/boards/spec/features/support/board_index_page.rb
Labels: feature, needs review

#10367 [41405] Add Basic Board to onboarding tour for Community edition
  config/locales/js-en.yml
  frontend/src/app/core/setup/globals/onboarding/helpers.ts
  frontend/src/app/core/setup/globals/onboarding/onboarding_tour.ts
  frontend/src/app/core/setup/globals/onboarding/onboarding_tour_trigger.ts
  frontend/src/app/core/setup/globals/onboarding/tours/boards_tour.ts
  modules/boards/spec/features/onboarding/boards_onboarding_tour_spec.rb
  modules/boards/spec/features/support/onboarding_steps.rb
Labels: feature

#10372 [41515] Cannot change date of milestone in team planner
  frontend/src/app/features/calendar/op-calendar.service.ts
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.html
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.ts
Labels: bugfix, needs review

#10179 Improve `watchers_model.yml` and `work_packages_model.yml`
  docs/api/apiv3/components/schemas/watchers_model.yml
  docs/api/apiv3/components/schemas/work_packages_by_project_model.yml
  docs/api/apiv3/openapi-spec.yml
  docs/api/apiv3/paths/project_work_packages.yml
Labels: documentation

#10369 Replace type with enum in onboarding tour
  frontend/src/app/core/setup/globals/onboarding/helpers.ts
  frontend/src/app/core/setup/globals/onboarding/onboarding_tour.ts
  frontend/src/app/core/setup/globals/onboarding/onboarding_tour_trigger.ts
  frontend/src/app/core/setup/globals/onboarding/tours/boards_tour.ts
Labels: maintenance

#10374 fix(doc-links): use https, harmonize url formats, linkify text-only urls, codify example urls
  docs/development/README.md
  docs/development/code-review-guidelines/README.md
  docs/development/concepts/hal-resources/README.md
  docs/development/concepts/inline-editing/README.md
  docs/development/concepts/queries/README.md
  docs/development/concepts/resource-schemas/README.md
  docs/development/concepts/translations/README.md
  docs/development/contribution-documentation/contribution-support/README.md
  docs/development/contribution-documentation/documentation-process/README.md
  docs/development/contribution-documentation/documentation-style-guide/README.md
  docs/development/create-openproject-plugin/README.md
  docs/development/development-environment-docker/README.md
  docs/development/development-environment-osx/README.md
  docs/development/development-environment-ubuntu/README.md
  docs/development/git-workflow/README.md
  docs/development/running-tests/README.md
  docs/development/security/README.md
  docs/enterprise-guide/enterprise-cloud-guide/enterprise-cloud-faq/README.md
  docs/enterprise-guide/enterprise-cloud-guide/gdpr-compliance/README.md
  docs/enterprise-guide/enterprise-cloud-guide/openproject-cloud-status/README.md
  docs/enterprise-guide/enterprise-on-premises-guide/enterprise-on-premises-faq/README.md
  docs/faq/README.md
  docs/installation-and-operations/configuration/README.md
  docs/installation-and-operations/configuration/repositories/README.md
  docs/installation-and-operations/installation-faq/README.md
  docs/installation-and-operations/installation/docker/README.md
  docs/installation-and-operations/installation/manual/README.md
  docs/installation-and-operations/installation/packaged/README.md
  docs/installation-and-operations/installation/univention/README.md
  docs/installation-and-operations/misc/docker-postgresql-migration/README.md
  docs/installation-and-operations/misc/migration-to-postgresql13/README.md
  docs/installation-and-operations/misc/migration/README.md
  docs/installation-and-operations/misc/packaged-postgresql-migration/README.md
  docs/release-notes/12-0-4/README.md
  docs/release-notes/4-1-0/README.md
  docs/system-admin-guide/authentication/kerberos/README.md
  docs/system-admin-guide/authentication/ldap-authentication/README.md
  docs/system-admin-guide/authentication/openid-providers/README.md
  docs/system-admin-guide/authentication/recaptcha/README.md
  docs/system-admin-guide/system-settings/display-settings/README.md
  docs/user-guide/gantt-chart/README.md
  docs/user-guide/time-and-costs/time-tracking/toggl-integration/README.md
  docs/user-guide/wiki/wiki-faq/README.md
Labels: documentation

#10357 Add arm64 support for docker "prod" build
  docker/prod/setup/preinstall-common.sh
Labels: docker, contribution

#10371 [41516] Hide lists of advanced boards outside EE
  frontend/src/app/features/boards/board/board-partitioned-page/board-list-container.component.html
  frontend/src/app/features/boards/board/board-partitioned-page/board-list-container.component.ts
  frontend/src/app/shared/components/enterprise-banner/enterprise-banner.component.html
  frontend/src/app/shared/components/enterprise-banner/enterprise-banner.component.ts
  modules/boards/spec/factories/board_factory.rb
  modules/boards/spec/features/board_enterprise_spec.rb
Labels: feature, needs review

#10338 [41199] Display a loading skeleton before actual content is fully loaded (using event sources of full calendar)
  frontend/src/app/features/team-planner/team-planner/planner/loading-skeleton-data.ts
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.html
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.ts
  frontend/src/app/features/work-packages/components/wp-card-view/wp-single-card/wp-single-card.component.sass
  frontend/src/app/shared/components/op-content-loader/op-principal-loading-skeleton/op-principal-loading-skeleton.component.html
  frontend/src/app/shared/components/op-content-loader/op-principal-loading-skeleton/op-principal-loading-skeleton.component.sass
  frontend/src/app/shared/components/op-content-loader/op-principal-loading-skeleton/op-principal-loading-skeleton.component.ts
  frontend/src/app/shared/components/op-content-loader/op-wp-loading-skeleton/op-wp-loading-skeleton.component.html
  frontend/src/app/shared/components/op-content-loader/op-wp-loading-skeleton/op-wp-loading-skeleton.component.sass
  frontend/src/app/shared/components/op-content-loader/op-wp-loading-skeleton/op-wp-loading-skeleton.component.ts
  frontend/src/app/shared/components/op-content-loader/openproject-content-loader.module.ts
  frontend/src/global_styles/content/modules/_team_planner.sass
Labels: feature

#10383 [41217] Use typeahead filter for "Add existing" on team planner
  frontend/src/app/features/team-planner/team-planner/add-work-packages/add-existing-pane.component.ts
Labels: maintenance

#10384 fix(doc): adjust broken list formatting
  docs/system-admin-guide/authentication/ldap-authentication/ldap-group-synchronization/README.md
Labels: documentation

#10175 Some API fixes discovered while experimenting with OpenAPI Generator generated client library
  docs/api/apiv3/components/schemas/activity_model.yml
  docs/api/apiv3/components/schemas/link.yml
  docs/api/apiv3/components/schemas/work_package_model.yml
  docs/api/apiv3/paths/work_package.yml
  docs/api/apiv3/paths/work_packages.yml
Labels: documentation

#10270 [chore] split read and write models
  docs/api/apiv3/components/schemas/file_link_collection_read_model.yml
  docs/api/apiv3/components/schemas/file_link_collection_write_model.yml
  docs/api/apiv3/components/schemas/file_link_origin_data_model.yml
  docs/api/apiv3/components/schemas/file_link_read_model.yml
  docs/api/apiv3/components/schemas/file_link_write_model.yml
  docs/api/apiv3/openapi-spec.yml
  docs/api/apiv3/paths/file_link.yml
  docs/api/apiv3/paths/work_package_file_links.yml
Labels: documentation, maintenance

#10356 [41492] Clicking in "include projects" breaks the page
  frontend/src/app/spot/styles/sass/components/checkbox.sass
Labels: bugfix, styling, needs review

#10396 [bugfix] Added additional visibility check for file links
  modules/storages/app/models/queries/storages/work_packages/filter/file_link_origin_id_filter.rb
  modules/storages/app/models/queries/storages/work_packages/filter/storage_id_filter.rb
  modules/storages/app/models/queries/storages/work_packages/filter/storage_url_filter.rb
  modules/storages/app/models/queries/storages/work_packages/filter/storages_filter_mixin.rb
  modules/storages/app/models/storages/file_link.rb
  modules/storages/spec/requests/api/v3/file_links/file_links_spec.rb
  modules/storages/spec/requests/api/v3/work_packages/work_packages_linkable_filter_spec.rb
  modules/storages/spec/requests/api/v3/work_packages/work_packages_linked_filter_spec.rb
  spec/factories/project_factory.rb
Labels: bugfix

#10403 [#40435] Update SAML documentation
  docs/system-admin-guide/authentication/saml/README.md
Labels: documentation, needs review

#10409 Add LDAP user synchronization job
  app/models/auth_source.rb
  app/models/ldap_auth_source.rb
  app/services/ldap/base_service.rb
  app/services/ldap/import_users_from_filter_service.rb
  app/services/ldap/import_users_from_list_service.rb
  app/services/ldap/synchronize_users_service.rb
  app/workers/ldap/synchronization_job.rb
  config/initializers/cronjobs.rb
  lib/open_project/mutex.rb
  lib/tasks/ldap.rake
  modules/ldap_groups/spec/services/synchronization_spec.rb
  spec/services/ldap/import_user_list_service_integration_spec.rb
  spec/services/ldap/import_users_from_filter_service_integration_spec.rb
  spec/services/ldap/synchronize_users_service_integration_spec.rb
  spec/support/shared/with_test_ldap.rb
Labels: feature, needs review

#10411 Chore/add file tab migration section
  .editorconfig
  config/locales/js-en.yml
  frontend/src/app/features/work-packages/components/wp-single-view/wp-single-view.component.ts
  frontend/src/app/features/work-packages/components/wp-single-view/wp-single-view.html
  frontend/src/app/features/work-packages/routing/wp-full-view/wp-full-view.component.ts
  frontend/src/app/features/work-packages/routing/wp-full-view/wp-full-view.html
  frontend/src/app/features/work-packages/routing/wp-split-view/wp-split-view.html
  frontend/src/global_styles/content/_attributes_group.sass
  spec/features/types/form_configuration_spec.rb
  spec/features/work_packages/tabs/activity_tab_spec.rb
  spec/features/work_packages/tabs/files_tab_spec.rb
Labels: maintenance, javascript
