Repository opf/openproject, pull requests merged in 2023-03, with the labels that each got.

#12091 Fixes to datepicker styles
  frontend/src/app/shared/components/datepicker/multi-date-picker/multi-date-picker.component.html
  frontend/src/app/shared/components/datepicker/single-date-picker/single-date-picker.component.html
  frontend/src/app/shared/components/datepicker/styles/datepicker.modal.sass
  frontend/src/app/shared/components/datepicker/wp-multi-date-form/wp-multi-date-form.component.html
  frontend/src/app/shared/components/datepicker/wp-single-date-form/wp-single-date-form.component.html
  frontend/src/app/shared/components/datepicker/wp-single-date-form/wp-single-date-form.component.sass
  frontend/src/app/shared/components/datepicker/wp-single-date-form/wp-single-date-form.component.ts
  frontend/src/app/shared/components/modal/modal-banner/modal-banner.component.sass
  frontend/src/app/spot/styles/sass/components/drop-modal.sass
  frontend/src/app/spot/styles/sass/components/modal.sass
  frontend/src/app/spot/styles/sass/components/selector-field.sass
Labels: pullpreview

#12183 Allow bulk move/copy actions to happen in the background
  app/controllers/work_packages/bulk_controller.rb
  app/controllers/work_packages/bulk_error_message.rb
  app/controllers/work_packages/moves_controller.rb
  app/workers/work_packages/bulk_copy_job.rb
  app/workers/work_packages/bulk_job.rb
  app/workers/work_packages/bulk_move_job.rb
  config/constants/settings/definition.rb
  config/locales/en.yml
  frontend/src/app/features/job-status/job-status-modal/job-status.modal.html
  frontend/src/app/features/job-status/job-status-modal/job-status.modal.ts
  frontend/src/app/features/job-status/job-status.interface.ts
  spec/controllers/work_packages/moves_controller_spec.rb
  spec/features/work_packages/bulk/copy_work_package_spec.rb
  spec/features/work_packages/bulk/move_work_package_spec.rb
  spec/support/pages/page.rb
Labels: bugfix

#12182 [46237] Datepicker: Update colours of mini calendar so non-working days are visible in all modes
  frontend/src/app/shared/components/datepicker/basic-range-date-picker/basic-range-date-picker.component.ts
  frontend/src/app/shared/components/datepicker/basic-single-date-picker/basic-single-date-picker.component.ts
  frontend/src/app/shared/components/datepicker/modal-single-date-picker/modal-single-date-picker.component.ts
  frontend/src/app/shared/components/datepicker/multi-date-picker/multi-date-picker.component.ts
  frontend/src/app/shared/components/datepicker/single-date-picker/single-date-picker.component.ts
  frontend/src/app/shared/components/datepicker/styles/datepicker.modal.sass
  frontend/src/app/shared/components/datepicker/styles/datepicker_mobile.modal.sass
  frontend/src/app/shared/components/datepicker/wp-multi-date-form/wp-multi-date-form.component.ts
  frontend/src/app/shared/components/datepicker/wp-single-date-form/wp-single-date-form.component.ts
  frontend/src/global_styles/content/_datepicker.sass
  frontend/src/global_styles/vendor/_flatpickr-overrides.sass
  frontend/src/global_styles/vendor/_index.sass
  spec/features/projects/edit_settings_spec.rb
Labels: pullpreview

#12215 [45566] Work package view layout breaks with long 'text' custom field values
  frontend/src/global_styles/content/work_packages/inplace_editing/_display_fields.sass
Labels: bugfix

#12221 [46649] Work package single date picker (eg. Milestone) should show short banners
  frontend/src/app/shared/components/datepicker/wp-single-date-form/wp-single-date-form.component.sass
Labels: bugfix

#12222 [42358] Standardise date pickers outside of the main work package date field
  app/helpers/custom_fields_helper.rb
  frontend/src/app/core/setup/global-dynamic-components.const.ts
  frontend/src/app/features/work-packages/components/wp-custom-actions/date-action/custom-date-action-admin.html
  frontend/src/app/shared/components/datepicker/single-date-picker/single-date-picker.component.html
  frontend/src/app/shared/components/datepicker/single-date-picker/single-date-picker.component.ts
  frontend/src/app/shared/components/op-non-working-days-list/op-non-working-days-list.component.html
  frontend/src/app/shared/shared.module.ts
  modules/costs/app/views/cost_types/index.html.erb
  spec/features/work_packages/custom_actions/custom_actions_spec.rb
Labels: pullpreview

#12209 [#46325] Header cut off in Filepicker on mobile iOS 15.3 Safari
  frontend/src/app/shared/components/modal/modal.component.ts
  frontend/src/app/spot/styles/sass/components/modal-overrides.sass
  frontend/src/app/spot/styles/sass/components/modal.sass
  frontend/src/global_styles/content/work_packages/shared/_file_picker.sass
  frontend/src/global_styles/vendor/foundation-apps/scss/components/_modal.scss
Labels: bugfix

#12275 [46813] page freezes if we clear selection in project filter
  frontend/src/app/features/work-packages/components/filters/filter-project/filter-project.component.ts
  frontend/src/app/shared/directives/search-highlight.directive.ts
Labels: bugfix

#11981 Documentation for 12.5 features
  docs/system-admin-guide/attribute-help-texts/README.md
  docs/system-admin-guide/integrations/README.md
  docs/system-admin-guide/working-days/README.md
  docs/system-admin-guide/working-days/add-non-working-day-link.png
  docs/system-admin-guide/working-days/add-working-day-modal.png
  docs/system-admin-guide/working-days/admin-working-days.png
  docs/system-admin-guide/working-days/apply-changes-button.png
  docs/user-guide/activity/README.md
  docs/user-guide/activity/enable-activity-module.png
  docs/user-guide/activity/project-activity-filter-list.png
  docs/user-guide/activity/project-activity-overview.png
  docs/user-guide/activity/project-activity-project-attributes.png
  docs/user-guide/activity/project-activity-workpackge-attributes.png
  docs/user-guide/agile-boards/README.md
  docs/user-guide/agile-boards/close-split-screen.png
  docs/user-guide/nextcloud-integration/NC_12.5-clickonAFileorFolderToSelectIt.png
  docs/user-guide/nextcloud-integration/NC_12.5-fileIsNowLinked.png
  docs/user-guide/nextcloud-integration/NC_12.5-linkExistingFilesLink.png
  docs/user-guide/nextcloud-integration/NC_12.5-linkNFilesButton.png
  docs/user-guide/nextcloud-integration/NC_12.5-secondFileAlsoLinked.png
  docs/user-guide/nextcloud-integration/NC_12.5-selctFileToUpload.png
  docs/user-guide/nextcloud-integration/NC_12.5-selectLocationToUploadTo.png
  docs/user-guide/nextcloud-integration/NC_12.5-uploadFilesLink.png
  docs/user-guide/nextcloud-integration/NC_removeFileLinkButton.png
  docs/user-guide/nextcloud-integration/README.md
  docs/user-guide/projects/README.md
  docs/user-guide/search/README.md
  docs/user-guide/work-packages/edit-work-package/README.md
  docs/user-guide/work-packages/set-change-dates/README.md
  docs/user-guide/work-packages/work-package-table-configuration/README.md
  docs/user-guide/work-packages/work-package-table-configuration/work-package-filter-include-projects.png
  docs/user-guide/work-packages/work-package-views/README.md
  docs/user-guide/work-packages/work-package-views/work-package-views-default.png
Labels: documentation

#12286 [46812] Delete button for filters disappears in case selected item is long
  frontend/src/app/shared/components/autocompleter/project-autocompleter/project-autocompleter.component.sass
Labels: bugfix

#12271 add release notes draft for 12.5.0
  docs/release-notes/12-5-0/Non-working-days-holidays.png
  docs/release-notes/12-5-0/README.md
  docs/release-notes/12-5-0/openproject-nextcloud-files-link.png
  docs/release-notes/12-5-0/openproject-nextcloud-files-picker.png
  docs/release-notes/12-5-0/openproject-nextcloud-upload-files-empty-status.png
  docs/release-notes/12-5-0/openproject-nextcloud-upload.gif
  docs/release-notes/12-5-0/openproject-print-wiki.png
  docs/release-notes/12-5-0/openproject-search-work-package-attachments.png
  docs/release-notes/12-5-0/project-activity-tracking.png
  docs/release-notes/12-5-0/project-list-activity.png
  docs/release-notes/12-5-0/work-package-filter-overdue.png
  docs/release-notes/README.md
Labels: documentation

#12297 [#46345] fix notification actors misalignment
  frontend/src/app/features/in-app-notifications/entry/actors-line/in-app-notification-actors-line.component.sass
Labels: bugfix, pullpreview

#12299 Revert between datepickers to use two basic fields again
  frontend/src/app/features/work-packages/components/filters/abstract-filter-date-time-value/abstract-filter-date-time-value.controller.ts
  frontend/src/app/features/work-packages/components/filters/filter-date-times-value/filter-date-times-value.component.html
  frontend/src/app/features/work-packages/components/filters/filter-date-times-value/filter-date-times-value.component.ts
  frontend/src/app/features/work-packages/components/filters/filter-dates-value/filter-dates-value.component.ts
  frontend/src/app/shared/components/datepicker/basic-single-date-picker/basic-single-date-picker.component.ts
  spec/features/work_packages/table/queries/filter_spec.rb
  spec/support/components/work_packages/filters.rb
  spec/support/shared/selenium_workarounds.rb
Labels: pullpreview

#12303 Documentation/fix docs
  docs/api/apiv3/paths/work_package.yml
  docs/api/apiv3/paths/work_packages.yml
  docs/release-notes/12-5-0/README.md
  docs/system-admin-guide/working-days/README.md
Labels: documentation

#12308 Review, changes to release notes for 12.5
  docs/release-notes/12-5-0/README.md
Labels: documentation

#12342 [#47157] Swagger UI is not rendering for API docs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/features/api-docs/swagger-ui/swagger-ui.component.ts
Labels: bugfix
