Repository opf/openproject, pull requests merged in 2023-04, with the labels that each got.

#12360 allow direct uploads outside of Amazon S3
  config/constants/settings/definition.rb
  docs/installation-and-operations/configuration/README.md
  lib_static/open_project/configuration/helpers.rb
Labels: bugfix, needs review

#12398 [#46843] Include helm charts documentation directly in the main docum…
  docs/installation-and-operations/installation/helm-chart/README.md
  docs/installation-and-operations/installation/kubernetes/README.md
Labels: documentation

#12409 fix(markdown): remove headline marker from image
  docs/user-guide/nextcloud-integration/README.md
Labels: documentation

#12411 Revert storybook-angular to v6
  frontend/package-lock.json
  frontend/package.json
Labels: pullpreview

#12397 [47057] Non-working Days/Holidays selection with 12.5 update
  frontend/src/app/features/calendar/op-calendar.service.ts
  frontend/src/app/shared/components/datepicker/modal-single-date-picker/modal-single-date-picker.component.ts
  spec/features/admin/working_days_spec.rb
Labels: bugfix

#12400 add reverse proxy examples for nginx
  docs/installation-and-operations/installation/docker/README.md
Labels: documentation, needs review

#12429 docker dev setup bin compose fixes
  bin/compose
  docker-compose.yml
Labels: bugfix, docker, needs review

#12427 Patch mail gem to handle TLS settings properly
  Gemfile
  Gemfile.lock
  config/initializers/mail_starttls_patch.rb
Labels: bugfix, contribution

#12417 Update hover styling for flatpickr days
  frontend/src/global_styles/content/_datepicker.sass
Labels: pullpreview

#12461 Keep active date field when clearing it
  frontend/src/app/shared/components/datepicker/wp-multi-date-form/wp-multi-date-form.component.ts
Labels: bugfix, needs review

#12401 [#44828] add overrides for grid layout for relations on mobile
  frontend/src/app/features/work-packages/components/wp-relations/wp-relation-row/wp-relation-row.template.html
  frontend/src/app/features/work-packages/components/wp-relations/wp-relations-group/wp-relations-group.template.html
  frontend/src/global_styles/content/work_packages/tabs/_relations.sass
  spec/features/work_packages/copy_spec.rb
  spec/features/work_packages/details/relations/hierarchy_spec.rb
  spec/features/work_packages/details/relations/relations_spec.rb
  spec/support/components/work_packages/relations.rb
Labels: bugfix, pullpreview

#12376 Add stories and argstable for basic datepickers
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/core/apiv3/endpoints/time-entries/apiv3-time-entries-paths.ts
  frontend/src/app/shared/components/datepicker/basic-datepicker.module.ts
  frontend/src/app/shared/components/datepicker/datepicker.module.ts
  frontend/src/app/shared/shared.module.ts
  frontend/src/stories/DatePickerBasic.example.html
  frontend/src/stories/DatePickerBasic.example.ts
  frontend/src/stories/DatePickerBasicPrefilled.example.html
  frontend/src/stories/DatePickerBasicPrefilled.example.ts
  frontend/src/stories/DatePickerRangePrefilled.example.html
  frontend/src/stories/DatePickerRangePrefilled.example.ts
  frontend/src/stories/Datepicker-Basic.stories.mdx
  frontend/src/stories/Datepicker-Common.stories.mdx
  frontend/src/stories/Datepicker-Modal.stories.mdx
  frontend/src/stories/Datepicker-WorkPackage.stories.mdx
  frontend/src/stories/day.service.stub.ts
  frontend/src/stories/i18n.service.stub.ts
  frontend/src/stories/weekday.service.stub.ts
Labels: pullpreview

#12474 [#47002] Release Multi-Select `CustomField`s from Enterprise to Community
  app/controllers/custom_fields_controller.rb
  app/services/authorization/enterprise_service.rb
  app/views/custom_fields/_form.html.erb
  app/views/custom_fields/_tab.html.erb
  config/locales/en.yml
  spec/features/custom_fields/custom_fields_spec.rb
  spec/services/authorization/enterprise_service_spec.rb
Labels: needs review

#12489 Remove truncation of work package subject in title
  frontend/src/app/features/work-packages/routing/wp-view-base/work-package-single-view.base.ts
Labels: on-hold

#12475 [46885] Non-working day settings: Move the arrows closer to the year
  frontend/src/app/shared/components/op-non-working-days-list/op-non-working-days-list.component.sass
Labels: pullpreview

#12499 do no allow taking over builtin users via omniauth
  app/services/authentication/omniauth_service.rb
  spec/services/authentication/omniauth_service_spec.rb
Labels: bugfix

#12494 Timestamps service and column rendering
  app/models/query/timestamps.rb
  config/locales/js-en.yml
  frontend/src/app/features/hal/resources/query-resource.ts
  frontend/src/app/features/hal/resources/work-package-resource.ts
  frontend/src/app/features/hal/schemas/schema-proxy.ts
  frontend/src/app/features/work-packages/components/wp-baseline/baseline-loading/baseline-loading.component.html
  frontend/src/app/features/work-packages/components/wp-baseline/baseline-loading/baseline-loading.component.ts
  frontend/src/app/features/work-packages/components/wp-baseline/baseline-modal/baseline-modal.component.html
  frontend/src/app/features/work-packages/components/wp-baseline/baseline-modal/baseline-modal.component.sass
  frontend/src/app/features/work-packages/components/wp-baseline/baseline-modal/baseline-modal.component.ts
  frontend/src/app/features/work-packages/components/wp-baseline/baseline/baseline.component.html
  frontend/src/app/features/work-packages/components/wp-baseline/baseline/baseline.component.sass
  frontend/src/app/features/work-packages/components/wp-baseline/baseline/baseline.component.ts
  frontend/src/app/features/work-packages/components/wp-fast-table/builders/baseline/baseline-column-builder.ts
  frontend/src/app/features/work-packages/components/wp-fast-table/builders/internal-sort-columns.ts
  frontend/src/app/features/work-packages/components/wp-fast-table/builders/rows/single-row-builder.ts
  frontend/src/app/features/work-packages/components/wp-list/wp-states-initialization.service.ts
  frontend/src/app/features/work-packages/components/wp-query/url-params-helper.spec.ts
  frontend/src/app/features/work-packages/components/wp-query/url-params-helper.ts
  frontend/src/app/features/work-packages/components/wp-table/external-configuration/external-query-configuration.component.ts
  frontend/src/app/features/work-packages/components/wp-table/wp-table.component.ts
  frontend/src/app/features/work-packages/components/wp-table/wp-table.directive.html
  frontend/src/app/features/work-packages/directives/query-space/wp-isolated-query-space.directive.ts
  frontend/src/app/features/work-packages/openproject-work-packages.module.ts
  frontend/src/app/features/work-packages/routing/wp-view-base/view-services/wp-view-baseline.service.ts
  frontend/src/app/features/work-packages/routing/wp-view-base/work-packages-view.base.ts
  frontend/src/app/features/work-packages/routing/wp-view-page/wp-view-page.component.ts
  frontend/src/app/shared/shared.module.ts
  frontend/src/app/spot/icon-font/src/baseline.svg
  frontend/src/app/spot/styles/sass/common/icon.sass
  frontend/src/assets/fonts/openproject_icon/openproject-icon-font.svg
  frontend/src/assets/fonts/openproject_icon/openproject-icon-font.ttf
  frontend/src/assets/fonts/openproject_icon/openproject-icon-font.woff
  frontend/src/assets/fonts/openproject_icon/openproject-icon-font.woff2
  frontend/src/global_styles/fonts/_openproject_icon_definitions.sass
  frontend/src/global_styles/fonts/_openproject_icon_font.lsg
  frontend/src/global_styles/layout/work_packages/_index.sass
  frontend/src/global_styles/layout/work_packages/_table_baseline.sass
  spec/features/work_packages/table/baseline/baseline_query_spec.rb
  spec/features/work_packages/table/baseline/baseline_rendering_spec.rb
  spec/lib/api/v3/work_packages/work_package_collection_representer_spec.rb
  spec/lib/api/v3/work_packages/work_package_representer_spec.rb
  spec/models/journable/with_historic_attributes_spec.rb
  spec/models/query/results_filter_on_historic_data_spec.rb
  spec/models/query/timestamps_spec.rb
  spec/requests/api/v3/queries/create_form_api_spec.rb
  spec/requests/api/v3/queries/create_query_spec.rb
  spec/requests/api/v3/queries/query_resource_spec.rb
  spec/requests/api/v3/queries/update_form_api_spec.rb
  spec/requests/api/v3/queries/update_query_spec.rb
  spec/requests/api/v3/work_packages/index_resource_spec.rb
  spec/services/api/v3/work_package_collection_from_query_service_spec.rb
  spec/services/update_query_from_params_service_spec.rb
  spec/support/components/work_packages/baseline.rb
  spec/support/components/work_packages/baseline_modal.rb
  spec/support/queries/shared_get_individual_query_examples.rb
Labels: pullpreview

#12509 Fix/invalidate recovery tokens after password change
  app/services/users/change_password_service.rb
  spec/services/users/change_password_service_spec.rb
Labels: bugfix
