Repository opf/openproject, pull requests merged in 2023-06, with the labels that each got.

#12718 [#48243] Convert `project.js` to Stimulus
  app/components/projects/row_component.html.erb
  app/views/messages/show.html.erb
  app/views/projects/filters/_boolean.html.erb
  app/views/projects/filters/_form.html.erb
  app/views/projects/filters/_text.html.erb
  app/views/projects/filters/date/_days.html.erb
  app/views/projects/filters/date/_input_options.html.erb
  app/views/projects/filters/list/_input_options.html.erb
  app/views/projects/filters/list/_select.html.erb
  app/views/projects/index.html.erb
  frontend/src/app/core/augmenting/dynamic-scripts/project.js
  frontend/src/app/core/augmenting/openproject-augmenting.module.ts
  frontend/src/app/core/augmenting/services/path-script.augment.service.ts
  frontend/src/app/shared/components/datepicker/basic-single-date-picker/basic-single-date-picker.component.html
  frontend/src/stimulus/controllers/dynamic/project.controller.ts
  frontend/src/tsconfig.app.json
  modules/storages/app/views/storages/admin/storages/edit.html.erb
Labels: needs review

#12735 [chore] refactored storage information box
  frontend/src/app/shared/components/storages/openproject-storages.module.ts
  frontend/src/app/shared/components/storages/storage-information/storage-information-box.ts
  frontend/src/app/shared/components/storages/storage-information/storage-information.html
  frontend/src/app/shared/components/storages/storage-information/storage-information.service.ts
  frontend/src/app/shared/components/storages/storage-login-button/storage-login-button.component.html
  frontend/src/app/shared/components/storages/storage-login-button/storage-login-button.component.ts
  frontend/src/app/shared/components/storages/storage-login-button/storage-login-input.ts
Labels: maintenance

#12673 Change icons to spot-icon part 2
  frontend/src/app/features/admin/types/attribute-group.component.html
  frontend/src/app/features/admin/types/group-edit-in-place.html
  frontend/src/app/features/admin/types/query-group.component.html
  frontend/src/app/features/admin/types/type-form-configuration.html
  frontend/src/app/features/invite-user-modal/button/invite-user-button.component.html
  frontend/src/app/features/invite-user-modal/principal/principal-search.component.html
  frontend/src/app/features/invite-user-modal/principal/principal.component.html
  frontend/src/app/features/invite-user-modal/summary/summary.component.html
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.html
  frontend/src/app/features/work-packages/components/work-package-comment/work-package-comment.component.html
  frontend/src/app/features/work-packages/components/wp-buttons/wp-button.template.html
  frontend/src/app/features/work-packages/components/wp-buttons/wp-create-button/wp-create-button.html
  frontend/src/app/features/work-packages/components/wp-buttons/wp-details-view-button/wp-details-view-button.component.ts
  frontend/src/app/features/work-packages/components/wp-buttons/wp-mark-notification-button/work-package-mark-notification-button.component.html
  frontend/src/app/features/work-packages/components/wp-buttons/zen-mode-toggle-button/zen-mode-toggle-button.component.ts
  frontend/src/app/features/work-packages/components/wp-details/wp-details-toolbar.html
  frontend/src/app/features/work-packages/components/wp-new/wp-new-full-view.html
  frontend/src/app/features/work-packages/components/wp-watcher-button/wp-watcher-button.component.ts
  frontend/src/app/features/work-packages/components/wp-watcher-button/wp-watcher-button.html
  frontend/src/app/features/work-packages/routing/wp-full-view/wp-full-view.html
  frontend/src/app/shared/components/dynamic-forms/components/dynamic-form/dynamic-form.component.html
  frontend/src/app/shared/components/dynamic-forms/components/dynamic-form/dynamic-form.component.sass
  frontend/src/app/shared/components/dynamic-forms/components/dynamic-form/dynamic-form.component.scss
  frontend/src/app/shared/components/dynamic-forms/components/dynamic-form/dynamic-form.component.ts
  frontend/src/app/shared/components/enterprise-banner/enterprise-banner.component.html
  frontend/src/app/shared/components/enterprise-banner/enterprise-banner.component.sass
  frontend/src/global_styles/content/_buttons.sass
  frontend/src/global_styles/content/_types_form_configuration.sass
  spec/features/types/form_configuration_spec.rb
  spec/features/work_packages/tabs/watcher_tab_spec.rb
Labels: pullpreview

#12681 Change icons to spot-icon part 3
  app/helpers/breadcrumb_helper.rb
  app/views/layouts/base.html.erb
  frontend/src/app/features/work-packages/components/back-routing/back-button.component.html
  frontend/src/app/features/work-packages/components/edit-actions-bar/wp-edit-actions-bar.html
  frontend/src/app/features/work-packages/components/filters/query-filter/query-filter.component.html
  frontend/src/app/features/work-packages/components/filters/query-filters/query-filters.component.html
  frontend/src/app/features/work-packages/components/wp-breadcrumb/wp-breadcrumb-parent.html
  frontend/src/app/features/work-packages/components/wp-breadcrumb/wp-breadcrumb.component.ts
  frontend/src/app/features/work-packages/components/wp-breadcrumb/wp-breadcrumb.html
  frontend/src/app/features/work-packages/components/wp-breadcrumb/wp-breadcrumb.sass
  frontend/src/app/features/work-packages/components/wp-buttons/wp-filter-button/wp-filter-button.component.ts
  frontend/src/app/features/work-packages/components/wp-buttons/wp-filter-button/wp-filter-button.html
  frontend/src/app/features/work-packages/components/wp-buttons/wp-fold-toggle-button/wp-fold-toggle-button.component.ts
  frontend/src/app/features/work-packages/components/wp-buttons/wp-settings-button/wp-settings-button.component.html
  frontend/src/app/features/work-packages/components/wp-buttons/wp-status-button/wp-status-button.component.sass
  frontend/src/app/features/work-packages/components/wp-buttons/wp-status-button/wp-status-button.html
  frontend/src/app/features/work-packages/components/wp-buttons/wp-timeline-toggle-button/wp-timeline-toggle-button.html
  frontend/src/app/features/work-packages/components/wp-buttons/wp-view-toggle-button/work-package-view-toggle-button.component.ts
  frontend/src/app/features/work-packages/components/wp-card-view/wp-single-card/wp-single-card.component.html
  frontend/src/app/features/work-packages/components/wp-fast-table/builders/baseline/baseline-column-builder.ts
  frontend/src/app/features/work-packages/components/wp-fast-table/builders/drag-and-drop/drag-drop-handle-builder.ts
  frontend/src/app/features/work-packages/components/wp-fast-table/builders/modes/hierarchy/single-hierarchy-row-builder.ts
  frontend/src/app/features/work-packages/components/wp-table/config-menu/config-menu.template.html
  frontend/src/app/features/work-packages/components/wp-table/configuration-modal/tabs/display-settings-tab.component.html
  frontend/src/app/features/work-packages/components/wp-table/sort-header/sort-header.directive.html
  frontend/src/app/features/work-packages/components/wp-table/sort-header/sort-header.directive.ts
  frontend/src/app/features/work-packages/components/wp-table/table-actions/actions/context-menu-table-action.ts
  frontend/src/app/features/work-packages/components/wp-table/table-actions/actions/details-table-action.ts
  frontend/src/app/features/work-packages/components/wp-table/table-actions/actions/unlink-table-action.ts
  frontend/src/app/features/work-packages/components/wp-table/wp-table.component.html
  frontend/src/app/features/work-packages/components/wp-table/wp-table.component.sass
  frontend/src/app/shared/components/editable-toolbar-title/editable-toolbar-title.html
  frontend/src/app/shared/components/editable-toolbar-title/editable-toolbar-title.sass
  frontend/src/app/shared/components/op-non-working-days-list/op-non-working-days-list.component.ts
  frontend/src/app/shared/helpers/op-icon-builder.ts
  frontend/src/app/shared/helpers/spot-icon-builder.ts
  frontend/src/global_styles/content/_advanced_filters.sass
  frontend/src/global_styles/content/_buttons.sass
  frontend/src/global_styles/content/_table.sass
  frontend/src/global_styles/content/work_packages/_table_drag_and_drop.sass
  frontend/src/global_styles/content/work_packages/_table_hierarchy.sass
  frontend/src/global_styles/layout/_breadcrumb.sass
  frontend/src/global_styles/openproject.sass
  frontend/src/global_styles/openproject/_mixins.sass
  modules/storages/spec/features/admin_storages_spec.rb
  spec/features/admin/working_days_spec.rb
  spec/features/work_packages/details/details_refreshing_spec.rb
  spec/features/work_packages/table/hierarchy/hierarchy_parent_below_spec.rb
  spec/support/components/work_packages/hierarchies.rb
Labels: pullpreview

#12588 WP Fields [4]: Two columns with label-on-top on mobile only for long text fields
  frontend/src/app/features/work-packages/components/wp-form-group/wp-attribute-group.component.sass
  frontend/src/global_styles/content/_attributes_key_value.sass
  frontend/src/global_styles/content/_forms_mobile.sass
  frontend/src/global_styles/content/work_packages/single_view/_single_view.sass
  frontend/src/global_styles/layout/work_packages/_mobile.sass
Labels: pullpreview

#12819 [#44340] Make "switch to context" blue box easier to understand
  config/locales/js-en.yml
  frontend/src/app/features/work-packages/components/wp-single-view/wp-single-view.component.html
  frontend/src/app/features/work-packages/components/wp-single-view/wp-single-view.component.ts
  frontend/src/global_styles/content/work_packages/single_view/_single_view.sass
  spec/features/work_packages/custom_actions/custom_actions_spec.rb
  spec/features/work_packages/switching_to_project_from_work_package_spec.rb
Labels: pullpreview, needs review

#12841 Reduce flakiness on `mobile_date_filter_spec`
  spec/features/work_packages/table/queries/mobile_date_filter_spec.rb
  spec/support/pages/work_packages/work_package_cards.rb
Labels: needs review

#12810 install correct gosu for each architecture
  docker/prod/Dockerfile
  docker/prod/entrypoint.sh
  docker/prod/gosu
Labels: docker, needs review

#12791 Fix buggy issues in baseline
  frontend/src/app/features/work-packages/components/wp-baseline/baseline/baseline.component.html
  frontend/src/app/features/work-packages/components/wp-baseline/baseline/baseline.component.sass
Labels: pullpreview

#12843 [#48506] Add `parent` as a supported link property under `attributesByTimestamp`
  lib/api/v3/work_packages/work_package_at_timestamp_representer.rb
  spec/lib/api/v3/work_packages/work_package_at_timestamp_representer_rendering_spec.rb
  spec/lib/api/v3/work_packages/work_package_representer_spec.rb
Labels: needs review

#12867 [#48428] Add Icons to global page menu
  config/initializers/menus.rb
  modules/boards/lib/open_project/boards/engine.rb
  modules/calendar/lib/open_project/calendar/engine.rb
  modules/meeting/lib/open_project/meeting/engine.rb
  modules/reporting/lib/open_project/reporting/engine.rb
  modules/team_planner/lib/open_project/team_planner/engine.rb
Labels: needs review

#12851 [#48504] The subject in the index of the PDF export is not a link
  app/models/work_package/pdf_export/table_of_contents.rb
Labels: pullpreview, needs review

#12875 Backport: Allow internal login in case omniauth direct provider is set
  app/controllers/account_controller.rb
  config/routes.rb
  docs/installation-and-operations/configuration/README.md
  spec/controllers/account_controller_spec.rb
Labels: backport

#12880 Use correctly prefixed warnings
  frontend/src/app/features/work-packages/components/wp-baseline/baseline/baseline.component.sass
  frontend/src/app/shared/components/enterprise-banner/enterprise-banner.component.sass
  frontend/src/app/spot/styles/sass/components/modal-overlay.sass
  frontend/src/global_styles/content/_enterprise.sass
  frontend/src/global_styles/content/work_packages/tabs/_files_tab.sass
  frontend/src/global_styles/content/work_packages/tabs/_relations.sass
  frontend/src/global_styles/layout/_print.sass
Labels: needs review

#12904 Force application/json in redirect to job status
  lib/api/v3/utilities/endpoints/delayed_modify.rb
Labels: bugfix, needs review

#12906 Add API link to the copied project on success
  app/workers/copy_project_job.rb
  spec/workers/copy_project_job_spec.rb
Labels: bugfix, needs review

#12922 Small fixes based on rbs research
  app/models/work_package_custom_field.rb
  lib/tasks/attachment_migrations.rake
Labels: needs review

#12942 Fix "implicit String conversion" Deprecation Warning
  app/helpers/application_helper.rb
Labels: needs review

#12950 fix(glossary): adjust menu position and markdown
  docs/glossary/README.md
Labels: documentation

#12954 Fix deprecated use of implicit block syntax as expectation subject
  spec/lib/open_project/authentication/strategies/warden/global_basic_auth_spec.rb
Labels: needs review

#12874 Open external links with window.open using link hook
  frontend/src/app/core/setup/globals/global-listeners.ts
  frontend/src/app/core/setup/globals/global-listeners/link-hijacking.ts
  spec/features/wiki/wiki_page_external_link_spec.rb
Labels: feature, needs review

#12908 Show recently viewed work packages when clicking on search bar
  app/services/api/v3/work_package_collection_from_query_params_service.rb
  config/locales/js-en.yml
  frontend/src/app/core/apiv3/cache/state-cache.service.ts
  frontend/src/app/core/apiv3/endpoints/work_packages/api-v3-work-packages-paths.ts
  frontend/src/app/core/global_search/input/global-search-input.component.html
  frontend/src/app/core/global_search/input/global-search-input.component.sass
  frontend/src/app/core/global_search/input/global-search-input.component.ts
  frontend/src/app/core/global_search/openproject-global-search.module.ts
  frontend/src/app/core/recent-items.service.ts
  frontend/src/app/features/hal/services/hal-resource.service.ts
  frontend/src/app/features/work-packages/openproject-work-packages.module.ts
  frontend/src/app/features/work-packages/routing/wp-full-view/wp-full-view.component.ts
  frontend/src/app/features/work-packages/routing/wp-split-view/wp-split-view.component.ts
  frontend/src/app/shared/components/autocompleter/op-autocompleter/op-autocompleter.component.ts
  spec/features/search/recently_viewed_work_packages_spec.rb
  spec/features/search/search_spec.rb
  spec/services/api/v3/work_package_collection_from_query_params_service_spec.rb
  spec/support/components/global_search.rb
  spec/support/pages/work_packages/full_work_package.rb
Labels: pullpreview

#12962 Update on Glossary
  docs/glossary/README.md
  docs/glossary/glossary-openproject-custom-field.png
  docs/glossary/glossary-openproject-gantt-chart.png
  docs/glossary/glossary-openproject-wiki.png
  docs/glossary/glossary-openproject-work-package.png
Labels: documentation

#12965 Changes to documentation
  docs/getting-started/my-account/README.md
  docs/user-guide/README.md
  docs/user-guide/calendar/calendar-faq/README.md
  docs/user-guide/repository/README.md
  docs/user-guide/time-and-costs/reporting/README.md
  docs/user-guide/time-and-costs/time-and-costs-faq/README.md
  docs/user-guide/time-and-costs/time-tracking/README.md
  docs/user-guide/time-and-costs/time-tracking/time-tracker-integration/README.md
  docs/user-guide/time-and-costs/time-tracking/toggl-integration/README.md
  docs/user-guide/wiki/create-edit-wiki/README.md
  docs/user-guide/wiki/wiki-menu/README.md
  docs/user-guide/work-packages/set-change-dates/README.md
  docs/user-guide/work-packages/work-packages-faq/README.md
Labels: documentation

#12984 Glossary: added image of workpackage table
  docs/glossary/README.md
  docs/glossary/glossary-openproject-header.png
  docs/glossary/glossary-openproject-work-package-table.png
Labels: documentation

#12995 Glossary hyperlinks + deleted empty letters
  docs/glossary/README.md
Labels: documentation
