Repository opf/openproject, pull requests merged in 2023-12, with the labels that each got.

#14196 [50489] Page cannot be scrolled after Meeting details are edited
  app/controllers/concerns/op_turbo/component_stream.rb
  frontend/src/turbo/setup.ts
  modules/meeting/app/controllers/concerns/meetings/agenda_component_streams.rb
  modules/meeting/app/controllers/concerns/meetings/work_package_meetings_tab_component_streams.rb
Labels: bugfix

#14213 [OP#50985] use primer flash (banner) for file storage administration settings
  app/helpers/application_helper.rb
  app/helpers/flash_messages_helper.rb
  app/views/layouts/base.html.erb
  modules/meeting/app/components/banner_message_component.html.erb
  modules/meeting/app/components/banner_message_component.rb
  modules/storages/app/controllers/storages/admin/automatically_managed_project_folders_controller.rb
  modules/storages/app/controllers/storages/admin/oauth_clients_controller.rb
  modules/storages/app/controllers/storages/admin/storages_controller.rb
  modules/storages/spec/features/admin_storages_spec.rb
Labels: feature

#14298 chore[Op#50985]: Remove unused flash for automatic management update
  modules/storages/app/controllers/storages/admin/automatically_managed_project_folders_controller.rb
Labels: maintenance

#14302 [#51174] Update the button labels for the automatically managed form to change based on checkbox active
  frontend/src/stimulus/controllers/dynamic/storages/automatically-managed-project-folders-form.controller.ts
  modules/storages/app/components/storages/admin/forms/automatically_managed_project_folders_form_component.html.erb
  modules/storages/app/components/storages/admin/forms/automatically_managed_project_folders_form_component.rb
  modules/storages/config/locales/en.yml
Labels: styling

#14303 [#51270] Update OneDrive/SharePoint oauth client form design labels
  modules/storages/app/components/storages/admin/forms/oauth_client_form_component.html.erb
  modules/storages/app/forms/storages/admin/oauth_client_form.rb
  modules/storages/config/locales/en.yml
Labels: styling, needs review

#14306 Bump `rspec-rails` to 6.1.0
  Gemfile
  Gemfile.lock
Labels: dependencies, ruby, needs review

#14301 [50233] Changed project deletion danger zone
  app/controllers/projects_controller.rb
  app/views/projects/destroy_info.html.erb
  config/locales/en.yml
Labels: feature

#14312 [51375] Fix spacing in relations dropdown
  frontend/src/app/features/work-packages/components/wp-relations/wp-relations-create/wp-relations-autocomplete/wp-relations-autocomplete.component.ts
Labels: needs review

#14305 Bump `test-prof` to 1.3.0
  Gemfile
  Gemfile.lock
Labels: dependencies, ruby, needs review

#14319 [#51396] Update invalid provider flash error to primer
  modules/storages/app/controllers/storages/admin/storages_controller.rb
Labels: tinyfix

#14326 docs(links): adjust anchors and to moved pages
  docs/installation-and-operations/configuration/README.md
  docs/system-admin-guide/backup/README.md
  docs/system-admin-guide/users-permissions/users-permissions-faq/README.md
  docs/user-guide/calendar/calendar-faq/README.md
  docs/user-guide/meetings/classic-meetings/README.md
  docs/user-guide/meetings/dynamic-meetings/README.md
Labels: documentation

#14327 [Op#51415] Toggle Automatic management password input on initial view render
  frontend/src/stimulus/controllers/dynamic/storages/automatically-managed-project-folders-form.controller.ts
  modules/storages/app/components/storages/admin/forms/automatically_managed_project_folders_form_component.html.erb
  modules/storages/app/components/storages/admin/forms/automatically_managed_project_folders_form_component.rb
Labels: bugfix

#14324 Show meeting add button when user has permission in any project
  modules/meeting/app/components/work_package_meetings_tab/heading_component.rb
  modules/meeting/spec/features/structured_meetings/work_package_meetings_tab_spec.rb
Labels: bugfix, needs review

#14328 include the roles on work package members in workflow calculation
  app/contracts/work_packages/base_contract.rb
  app/models/users/permission_checks.rb
  spec/contracts/work_packages/base_contract_spec.rb
  spec/models/user_spec.rb
Labels: pullpreview

#14336 Bump gosu to 1.17
  docker/prod/Dockerfile
Labels: operations, docker

#14183 FAQ Inboud Mails Cloud
  docs/enterprise-guide/enterprise-cloud-guide/enterprise-cloud-faq/README.md
Labels: documentation

#14325 [#50931] Ensure the Share Modal's header section is always present
  app/components/work_packages/share/modal_body_component.html.erb
  app/components/work_packages/share/modal_body_component.rb
  config/locales/en.yml
  frontend/src/stimulus/controllers/dynamic/work-packages/share/bulk-selection.controller.ts
  spec/features/work_packages/share/filter_spec.rb
  spec/support/components/work_packages/share_modal.rb
Labels: bugfix, needs review

#14338 Use `allowed_based_on_permission_context` for menu items
  lib/redmine/menu_manager/menu_helper.rb
  spec/lib/redmine/menu_manager/menu_helper_spec.rb
Labels: needs review

#14339 Fix flaky query spec in bcf_view_management_spec.rb
  spec/support/components/work_packages/filters.rb
Labels: flaky-spec

#14343 [#51392] Fix incorrect translation keys used in sharing text-part email
  app/views/sharing_mailer/shared_work_package.text.erb
Labels: bugfix, needs review

#14344 Initialize paginationOptions after configuration loaded
  frontend/src/app/app.module.ts
  frontend/src/app/core/global_search/openproject-global-search.module.ts
  frontend/src/app/features/work-packages/openproject-work-packages.module.ts
  frontend/src/app/shared/components/autocompleter/openproject-autocompleter.module.ts
  frontend/src/app/shared/components/datepicker/basic-datepicker.module.ts
  frontend/src/app/shared/components/editor/openproject-editor.module.ts
  frontend/src/app/shared/components/fields/openproject-fields.module.ts
  frontend/src/app/shared/components/principal/principal-rendering.module.ts
Labels: bugfix

#14352 docs(links): adjust anchors & links
  docs/getting-started/my-account/README.md
  docs/installation-and-operations/installation/docker/README.md
  docs/system-admin-guide/emails-and-notifications/README.md
  docs/user-guide/time-and-costs/reporting/README.md
  docs/user-guide/work-packages/add-work-packages-to-meetings/README.md
  docs/user-guide/work-packages/set-change-dates/README.md
Labels: documentation

#14346 [#51186] Render the "Share" button based on the user's viewing capability
  config/initializers/permissions.rb
  frontend/src/app/features/work-packages/routing/wp-full-view/wp-full-view.component.ts
  frontend/src/app/features/work-packages/routing/wp-full-view/wp-full-view.html
  spec/features/work_packages/share/bulk_sharing_spec.rb
  spec/features/work_packages/share/enterprise_restriction_spec.rb
  spec/features/work_packages/share/filter_spec.rb
  spec/features/work_packages/share/multi_invite_spec.rb
  spec/features/work_packages/share_spec.rb
  spec/support/pages/work_packages/full_work_package.rb
Labels: bugfix, needs review

#14262 [51244] Create separate project module "Gantt"
  Gemfile.lock
  Gemfile.modules
  app/controllers/work_packages_controller.rb
  app/helpers/work_packages_controller_helper.rb
  app/views/roles/_permissions.html.erb
  config/initializers/menus.rb
  config/locales/en.yml
  frontend/src/app/features/work-packages/components/wp-list/wp-query-view.service.ts
  frontend/src/app/features/work-packages/openproject-work-package-routes.module.ts
  frontend/src/app/features/work-packages/routing/work-packages-gantt-routes.ts
  frontend/src/app/shared/components/op-view-select/op-static-queries.service.ts
  frontend/src/app/shared/components/op-view-select/op-view-select.component.ts
  modules/gantt/app/contracts/gantt/views/contract_strategy.rb
  modules/gantt/app/controllers/gantt/base_controller.rb
  modules/gantt/app/controllers/gantt/gantt_controller.rb
  modules/gantt/app/views/gantt/gantt/_menu.html.erb
  modules/gantt/app/views/gantt/gantt/index.html.erb
  modules/gantt/config/locales/en.yml
  modules/gantt/config/routes.rb
  modules/gantt/lib/open_project/gantt.rb
  modules/gantt/lib/open_project/gantt/engine.rb
  modules/gantt/lib/openproject-gantt.rb
  modules/gantt/openproject-gantt.gemspec
  modules/gantt/spec/routing/gantt_routing_spec.rb
  spec/lib/redmine/menu_manager_spec.rb
Labels: feature, pullpreview, needs review

#14360 Hide public permissions in assignment and report
  app/contracts/roles/base_contract.rb
  spec/contracts/roles/shared_contract_examples.rb
  spec/seeders/basic_data/project_role_seeder_spec.rb
Labels: needs review

#14300 [51245] Move all existing views with Gantt enabled to new Gantt module
  db/migrate/20231201085450_change_view_of_queries_with_timeline_to_gantt.rb
  modules/gantt/spec/migrations/change_view_of_queries_with_timeline_to_gantt_spec.rb
  spec/factories/query_factory.rb
  spec/factories/view_factory.rb
Labels: feature, needs review

#14367 chore[Op#50748] Cleanup unused views
  modules/storages/app/views/storages/admin/storages/nextcloud/_edit.html.erb
  modules/storages/app/views/storages/admin/storages/nextcloud/_oauth_client.html.erb
  modules/storages/app/views/storages/admin/storages/nextcloud/_oauth_client_section.html.erb
  modules/storages/app/views/storages/admin/storages/one_drive/_edit.html.erb
  modules/storages/app/views/storages/admin/storages/one_drive/_oauth_client.html.erb
  modules/storages/app/views/storages/admin/storages/one_drive/_oauth_client_section.html.erb
  modules/storages/app/views/storages/admin/storages/one_drive/edit.html.erb
Labels: maintenance, needs review

#14351 Fix time logging issue
  app/policies/work_package_policy.rb
  lib/api/caching/cached_representer.rb
  lib/api/v3/work_packages/schema/work_package_schema_representer.rb
  lib/api/v3/work_packages/work_package_representer.rb
  modules/costs/app/models/cost_scopes.rb
  modules/costs/app/models/time_entries/scopes/visible.rb
  modules/costs/app/models/time_entries/time_entry_scopes.rb
  modules/costs/app/models/time_entry.rb
  modules/costs/spec/features/view_own_rates_spec.rb
  modules/costs/spec/models/time_entries/scopes/visible_spec.rb
  spec/factories/principal_factory.rb
Labels: needs review

#14356 Fix activation of invited users during sharing
  app/controllers/account_controller.rb
  app/controllers/concerns/accounts/omniauth_login.rb
  app/controllers/concerns/accounts/redirect_after_login.rb
  app/helpers/application_helper.rb
  app/helpers/mail_notification_helper.rb
  app/mailers/sharing_mailer.rb
  app/models/token/invitation.rb
  app/models/user.rb
  app/views/account/_register.html.erb
  app/views/mailer/_notification_row.html.erb
  app/views/sharing_mailer/shared_work_package.html.erb
  app/views/sharing_mailer/shared_work_package.text.erb
  config/locales/en.yml
  spec/features/auth/omniauth_spec.rb
  spec/features/users/invitation_spec.rb
  spec/features/work_packages/share/share_account_activation_spec.rb
Labels: bugfix

#14366 chore[Op51372]: Remove unused redirect URI builder JS
  frontend/src/stimulus/controllers/dynamic/storages/oauth-client-form.controller.ts
  modules/storages/app/components/storages/admin/forms/oauth_client_form_component.html.erb
  modules/storages/app/components/storages/admin/forms/redirect_uri_form_component.html.erb
Labels: maintenance, needs review

#14380 [51225] i18n translation missing for rescheduled email header
  modules/meeting/app/mailers/meeting_mailer.rb
  modules/meeting/config/locales/en.yml
Labels: bugfix, needs review

#14361 update seeded permissions
  app/seeders/common.yml
  modules/costs/app/seeders/common.yml
  modules/github_integration/app/seeders/common.yml
  modules/meeting/app/seeders/common.yml
  modules/reporting/app/seeders/common.yml
  modules/storages/app/seeders/common.yml
  spec/seeders/root_seeder_standard_edition_spec.rb
Labels: pullpreview, needs review

#14385 Update lookbook patch Gem version
  lib/open_project/patches/lookbook_tree_node_inflector.rb
Labels: maintenance, needs review

#14371 [51259] Create new global module "Gantt"
  modules/gantt/lib/open_project/gantt/engine.rb
  spec/lib/redmine/menu_manager_spec.rb
Labels: feature

#14391 [51412] Lines not aligned with text on the login screen
  frontend/src/global_styles/content/_accounts.sass
Labels: bugfix, needs review

#14392 WP Descendant query also allows single WP access
  app/models/work_packages/scopes/left_join_self_and_descendants.rb
Labels: needs review

#14395 documentation link-fixes
  docs/api/bcf/bcf-rest-api.md
  docs/development/code-review-guidelines/README.md
  docs/development/contribution-documentation/documentation-process-internal-contributor/README.md
  docs/development/product-development-handbook/README.md
  docs/development/running-tests/README.md
  docs/installation-and-operations/misc/custom-openid-connect-providers/README.md
  docs/release-notes/12/12-0-4/README.md
  docs/release-notes/12/12-0-7/README.md
  docs/release-notes/12/12-1-3/README.md
  docs/release-notes/12/12-2-2/README.md
  docs/release-notes/12/12-5-4/README.md
  docs/release-notes/13-1-0/README.md
  docs/release-notes/8/8-3-2/README.md
  docs/security-and-privacy/statement-on-security/README.md
  docs/system-admin-guide/authentication/openid-providers/README.md
  docs/system-admin-guide/authentication/two-factor-authentication/README.md
  docs/system-admin-guide/system-settings/general-settings/README.md
  docs/user-guide/work-packages/share-work-packages/README.md
  docs/user-guide/work-packages/work-package-views/README.md
Labels: documentation

#14399 [51482] "New meeting" buttons in Meetings module have different translation strings
  modules/meeting/app/views/meetings/_menu_query_select.html.erb
Labels: bugfix, needs review

#14394 [#51531] Incomplete Automatically managed form does not toggle the submit button label
  modules/storages/app/components/storages/admin/forms/automatically_managed_project_folders_form_component.rb
Labels: bugfix, needs review

#14383 Fix flaky modules/costs/spec/features/timer_spec
  modules/costs/spec/features/timer_spec.rb
  spec/features/work_packages/table/queries/filter_spec.rb
  spec/support/pages/admin/custom_actions/form.rb
Labels: flaky-spec

#14401 [51402] Date field on work package too narrow
  frontend/src/app/spot/styles/sass/components/drop-modal.sass
Labels: bugfix, needs review

#14400 Set is_filter to true by default and add descriptions
  app/views/custom_fields/_form.html.erb
  config/locales/en.yml
  db/migrate/20231212131603_set_custom_fields_filter_default_true.rb
Labels: bugfix, needs review

#14398 [51386] Sharing with a locked user causes the modal to go fullscreen
  app/components/work_packages/share/invite_user_form_component.html.erb
  app/components/work_packages/share/invite_user_form_component.rb
  app/components/work_packages/share/invite_user_form_component.sass
  app/components/work_packages/share/modal_body_component.html.erb
  app/components/work_packages/share/modal_body_component.rb
  app/controllers/work_packages/shares_controller.rb
  app/forms/work_packages/share/invitee.rb
  config/locales/en.yml
  spec/features/work_packages/share_spec.rb
  spec/support/components/work_packages/share_modal.rb
Labels: bugfix, needs review

#14407 Speed up a spec by using shared_let.
  modules/storages/spec/requests/api/v3/project_storages/project_storages_spec.rb
Labels: needs review

#14417 Fix tests that rely on notifications being pulled all 10 seconds
  modules/boards/spec/features/onboarding/boards_onboarding_tour_spec.rb
  modules/storages/spec/features/manage_project_storage_spec.rb
  modules/team_planner/spec/features/onboarding/team_planner_onboarding_tour_spec.rb
  spec/features/notifications/notification_center/notification_center_spec.rb
Labels: needs review

#14412 [51480] Inconsistent hrefs in WP shared mail
  app/views/sharing_mailer/shared_work_package.html.erb
Labels: bugfix, needs review

#14411 Minor translation changes
  config/locales/en.yml
  modules/meeting/config/locales/en.yml
Labels: bugfix

#14387 Guard access behavior for shared work packages with a feature spec
  spec/factories/work_package_role_factory.rb
  spec/features/work_packages/share/access_spec.rb
  spec/support/components/projects/top_menu.rb
  spec/support/components/work_packages/share_modal.rb
  spec/support/pages/projects/index.rb
  spec/support/pages/projects/show.rb
  spec/support/pages/work_packages/abstract_work_package.rb
  spec/support/pages/work_packages/work_packages_table.rb
Labels: ruby, needs review

#14415 [51370] In mobile view, the primer banner does not take the full width
  frontend/src/app/features/work-packages/components/back-routing/back-button.component.sass
  frontend/src/app/features/work-packages/components/wp-breadcrumb/wp-breadcrumb.sass
  frontend/src/app/features/work-packages/routing/wp-full-view/wp-full-view.html
  frontend/src/global_styles/content/work_packages/single_view/_single_view.sass
  frontend/src/global_styles/layout/_base.sass
  frontend/src/global_styles/layout/_base_mobile.sass
  frontend/src/global_styles/layout/_toolbar.sass
  frontend/src/global_styles/layout/_toolbar_mobile.sass
  frontend/src/global_styles/layout/work_packages/_full_view.sass
  frontend/src/global_styles/layout/work_packages/_mobile.sass
  frontend/src/global_styles/layout/work_packages/_print.sass
Labels: bugfix, styling, needs review

#14424 fix slow project visible scope for admins
  app/models/project.rb
  app/models/projects/scopes/visible.rb
  lib_static/plugins/acts_as_searchable/lib/acts_as_searchable.rb
  spec/models/projects/scopes/visible_spec.rb
Labels: needs review

#14416 Bump ruby to 3.2.2 & bundler to 2.4.22
  .ruby-version
  Gemfile
  Gemfile.lock
  docker/ci/Dockerfile
  docker/ci/entrypoint.sh
  docker/dev/backend/Dockerfile
  docker/prod/Dockerfile
  docs/development/development-environment-docker/README.md
  docs/development/development-environment-osx/README.md
  docs/development/development-environment-ubuntu/README.md
  docs/installation-and-operations/installation/manual/README.md
  script/github_pr_errors
Labels: needs review

#14436 [51374] Notes on Add work package to meeting modal are overflowing
  modules/meeting/app/components/meetings/sidebar/participants_form_component.html.erb
  modules/meeting/app/components/op_turbo/op_primer/async_dialog_component.html.erb
  modules/meeting/app/components/work_package_meetings_tab/add_work_package_to_meeting_form_component.html.erb
Labels: bugfix

#14433 [51652] Share modal has two close options
  frontend/src/app/features/work-packages/components/wp-share-modal/wp-share.modal.html
  spec/support/components/work_packages/share_modal.rb
Labels: bugfix

#14421 Silence multiple database warning
  config/environments/production.rb
Labels: bugfix

#14428 [#50945] Ensure filters are re-applied on CRUD share actions
  app/components/work_packages/share/permission_button_component.html.erb
  app/components/work_packages/share/permission_button_component.rb
  app/controllers/work_packages/shares_controller.rb
  spec/features/work_packages/share/filter_spec.rb
Labels: bugfix, needs review

#14313 Add mod_rewrite to nextcloud troubleshooting
  docs/system-admin-guide/integrations/nextcloud/README.md
  docs/system-admin-guide/integrations/nextcloud/nextcloud_not_fully_set_up.png
Labels: documentation

#14435 update glossary after release of 13.1
  docs/glossary/README.md
Labels: documentation

#14354 [#51033] Enable OAuth Client Form submit button and show validation errors in case of invalid submission
  app/contracts/oauth_clients/create_contract.rb
  app/services/oauth_clients/create_service.rb
  config/locales/en.yml
  frontend/src/stimulus/controllers/dynamic/storages/oauth-client-form.controller.ts
  modules/storages/app/components/storages/admin/forms/oauth_client_form_component.html.erb
  modules/storages/app/components/storages/admin/forms/oauth_client_form_component.rb
  modules/storages/app/components/storages/admin/forms/redirect_uri_form_component.html.erb
  modules/storages/app/components/storages/admin/oauth_application_info_copy_component.rb
  modules/storages/app/components/storages/admin/oauth_client_info_component.rb
  modules/storages/app/components/storages/admin/storage_view_component.html.erb
  modules/storages/app/controllers/storages/admin/oauth_clients_controller.rb
  modules/storages/app/controllers/storages/admin/storages_controller.rb
  modules/storages/app/views/storages/admin/oauth_clients/new.turbo_stream.erb
  modules/storages/app/views/storages/admin/storages/create.turbo_stream.erb
  modules/storages/app/views/storages/admin/storages/replace_oauth_application.turbo_stream.erb
  modules/storages/app/views/storages/admin/storages/show_oauth_application.turbo_stream.erb
  modules/storages/spec/components/storages/admin/oauth_client_info_component_spec.rb
  modules/storages/spec/features/admin_storages_spec.rb
  modules/storages/spec/requests/api/v3/storages/storages_api_spec.rb
  spec/contracts/oauth_clients/create_contract_spec.rb
Labels: maintenance, needs review

#14445 [#51716] Toggle Automatically managed label on initial view render
  modules/storages/app/components/storages/admin/forms/automatically_managed_project_folders_form_component.rb
Labels: needs review, tinyfix

#14446 Don't resubmit an empty string on opening
  frontend/src/app/shared/components/autocompleter/op-autocompleter/op-autocompleter.component.ts
Labels: bugfix, needs review

#14422 Remove form loading in embedded table
  frontend/src/app/features/work-packages/components/filters/filter-container/filter-container.directive.ts
  frontend/src/app/features/work-packages/components/wp-edit-form/table-edit-form.ts
  frontend/src/app/features/work-packages/components/wp-list/wp-list.service.ts
  frontend/src/app/features/work-packages/components/wp-table/embedded/wp-embedded-table.component.ts
Labels: bugfix, needs review

#14438 Use auto size for the button group in mobile meeting agenda form
  frontend/package.json
  modules/meeting/app/components/meeting_agenda_items/form_component.sass
Labels: bugfix, styling, needs review

#14448 Speed up specs by using shared_let.
  modules/storages/spec/requests/api/v3/file_links/file_links_api_spec.rb
  modules/storages/spec/requests/api/v3/storages/storages_api_spec.rb
  modules/storages/spec/support/user_permissions_helper.rb
Labels: needs review

#14419 Code maintenance/50748 remove obsolete file storages translations - Automation via `i18n-tasks` gem
  Gemfile
  Gemfile.lock
  config/i18n-tasks.yml
  modules/backlogs/app/controllers/rb_tasks_controller.rb
  modules/storages/app/views/storages/admin/storages/upsale.html.erb
  modules/storages/config/locales/en.yml
  spec/i18n_spec.rb
Labels: maintenance, needs review

#14452 Include ongoing meetings in meeting tab
  modules/meeting/app/forms/meeting_agenda_item/meeting_form.rb
  modules/meeting/config/locales/en.yml
  modules/meeting/spec/features/structured_meetings/work_package_meetings_tab_spec.rb
Labels: bugfix, needs review

#14453 [51680] white space at the end of page when scrolling a wiki page
  frontend/src/global_styles/content/editor/_ckeditor.sass
Labels: needs review

#14450 [45469] Unnecessary bullet displayed for TODO checkboxes in wp comments
  frontend/src/global_styles/content/work_packages/tabs/_activities.sass
Labels: needs review

#14449 chore[Op#51033]: Remove unnecessary conditional
  app/services/oauth_clients/create_service.rb
Labels: maintenance, needs review

#14460 [#50622] Alias `Storages::NextcloudStorage#automatically_managed?` as `Storages::NextcloudStorage#automatic_management_enabled?` for clarity
  modules/storages/app/components/storages/admin/forms/automatically_managed_project_folders_form_component.html.erb
  modules/storages/app/components/storages/admin/forms/automatically_managed_project_folders_form_component.rb
  modules/storages/app/components/storages/admin/storage_view_information.rb
  modules/storages/app/contracts/storages/storages/nextcloud_contract.rb
  modules/storages/app/controllers/storages/admin/automatically_managed_project_folders_controller.rb
  modules/storages/app/forms/storages/admin/managed_project_folders/automatic_management_checkbox.rb
  modules/storages/app/models/storages/nextcloud_storage.rb
  modules/storages/app/models/storages/project_storage.rb
  modules/storages/app/services/storages/project_storages/set_attributes_service.rb
  modules/storages/app/services/storages/storages/set_attributes_service.rb
  modules/storages/app/services/storages/storages/set_nextcloud_provider_fields_attributes_service.rb
  modules/storages/app/views/storages/admin/storages/edit.html.erb
  modules/storages/app/workers/storages/manage_nextcloud_integration_job_mixin.rb
  modules/storages/lib/api/v3/storages/storage_representer.rb
  modules/storages/spec/contracts/storages/project_storages/base_contract_spec.rb
  modules/storages/spec/contracts/storages/storages/shared_contract_examples.rb
  modules/storages/spec/features/admin_storages_spec.rb
  modules/storages/spec/models/storages/nextcloud_storage_spec.rb
Labels: maintenance

#14463 Evaluate changes on journal creation only for supported associations
  app/services/journals/create_service.rb
Labels: needs review
