Repository opf/openproject, pull requests merged in 2023-09, with the labels that each got.

#13608 [#47871] [AppSignal] Performance MessagesController#show
  app/controllers/messages_controller.rb
  app/views/messages/show.html.erb
Labels: bugfix, needs review

#13612 [#49836] Activate users upon successful password reset
  app/services/users/change_password_service.rb
  spec/controllers/account_controller_spec.rb
  spec/services/users/change_password_service_spec.rb
Labels: bugfix

#13621 [#49494] Create `add_work_package_members` permission
  config/initializers/permissions.rb
Labels: needs review

#13631 Add subversion to all-in-one docker image
  docker/prod/setup/preinstall-common.sh
Labels: docker

#13626 Follow up for Share Work Package permission
  config/initializers/permissions.rb
  config/locales/en.yml
  db/migrate/20230905090205_add_share_workpackages_permission.rb
Labels: needs review

#13634 Add in all currently-missing translations
  app/helpers/no_results_helper.rb
  app/views/oauth/applications/_form.html.erb
  app/views/user_mailer/wiki_page_added.html.erb
  app/views/user_mailer/wiki_page_updated.html.erb
  config/environments/test.rb
  config/locales/en.yml
  modules/storages/app/views/storages/project_settings/project_storage_members/index.html.erb
  modules/storages/config/locales/en.yml
  modules/two_factor_authentication/app/views/two_factor_authentication/two_factor_devices/confirm.html.erb
  spec/features/global_roles/global_role_assignment_spec.rb
  spec/features/global_roles/global_role_crud_spec.rb
  spec/features/global_roles/mock_global_permissions.rb
  spec/features/global_roles/no_module_spec.rb
Labels: bugfix, maintenance, needs review

#13643 Add missing translations for public permissions
  config/locales/en.yml
Labels: needs review

#13641 Remove debug statement in the middle of the case statement of RDM Mailhandler
  extra/mail_handler/rdm-mailhandler.rb
Labels: needs review

#13619 [chore] removed configuration check concern
  modules/storages/app/controllers/storages/admin/project_storages_controller.rb
  modules/storages/app/models/storages/nextcloud_storage.rb
  modules/storages/app/models/storages/one_drive_storage.rb
  modules/storages/app/models/storages/storage.rb
  modules/storages/spec/components/admin/configuration_checks_component_spec.rb
  modules/storages/spec/contracts/storages/file_links/shared_contract_examples.rb
  modules/storages/spec/contracts/storages/project_storages/shared_contract_examples.rb
  modules/storages/spec/factories/project_storage_factory.rb
  modules/storages/spec/factories/storage_factory.rb
  modules/storages/spec/features/admin_storages_spec.rb
  modules/storages/spec/features/manage_project_storage_spec.rb
  modules/storages/spec/features/show_file_links_spec.rb
  modules/storages/spec/features/storages_menu_links_spec.rb
  modules/storages/spec/features/storages_module_spec.rb
  modules/storages/spec/lib/api/v3/file_links/file_link_representer_parsing_spec.rb
  modules/storages/spec/lib/api/v3/file_links/file_link_representer_rendering_spec.rb
  modules/storages/spec/lib/api/v3/storage_files/storage_file_representer_spec.rb
  modules/storages/spec/lib/api/v3/storage_files/storage_files_representer_spec.rb
  modules/storages/spec/lib/append_storages_hosts_to_csp_hook_spec.rb
  modules/storages/spec/models/common/configuration_checks_spec.rb
  modules/storages/spec/models/file_link_spec.rb
  modules/storages/spec/models/nextcloud_storage_spec.rb
  modules/storages/spec/models/one_drive_storage_spec.rb
  modules/storages/spec/models/project_storage_spec.rb
  modules/storages/spec/models/shared_base_storage_spec.rb
  modules/storages/spec/requests/api/v3/file_links/file_links_api_spec.rb
  modules/storages/spec/requests/api/v3/file_links/mixed_case_file_links_integration_spec.rb
  modules/storages/spec/requests/api/v3/project_storages/project_storages_spec.rb
  modules/storages/spec/requests/api/v3/storages/storage_files_api_spec.rb
  modules/storages/spec/requests/api/v3/work_packages/work_packages_linkable_filter_spec.rb
  modules/storages/spec/requests/api/v3/work_packages/work_packages_linked_filter_spec.rb
  modules/storages/spec/requests/append_content_security_policy_spec.rb
  modules/storages/spec/services/principals/replace_references_service_call_integration_spec.rb
  modules/storages/spec/services/storages/file_links/file_link_sync_service_spec.rb
  modules/storages/spec/services/storages/oauth_applications/create_service_spec.rb
  modules/storages/spec/services/storages/project_storages/delete_service_spec.rb
  modules/storages/spec/services/storages/storages/set_attributes_service_spec.rb
  modules/storages/spec/services/storages/storages/update_service_spec.rb
  spec/contracts/oauth_clients/create_contract_spec.rb
  spec/factories/oauth_client_factory.rb
  spec/features/projects/copy_spec.rb
  spec/lib/api/v3/projects/project_representer_rendering_spec.rb
  spec/lib/api/v3/work_packages/work_package_representer_spec.rb
  spec/lib/journal_formatter/file_link_spec.rb
  spec/models/query/results_filter_on_historic_data_spec.rb
  spec/requests/api/v3/work_packages/create_resource_spec.rb
  spec/services/oauth_clients/connection_manager_spec.rb
  spec/services/oauth_clients/create_service_spec.rb
Labels: maintenance, needs review

#13623 Apply skip metadata to `svnadmin`-dependent specs
  spec/services/scm/create_managed_repository_service_spec.rb
  spec/services/scm/delete_managed_repository_service_spec.rb
Labels: maintenance, needs review

#13622 Remove unused `system_test.rb` configuration file
  spec/support/system_test.rb
Labels: maintenance, needs review

#13649 Add unit test to ensure every permission has an english translation
  spec/permissions/translations_spec.rb
Labels: maintenance, needs review

#13656 Bump primer_view_components and octicons
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: maintenance

#13662 Enable "Nate Heckler" mode when using Factory Profiler tool 🔬
  spec/rails_helper.rb
Labels: maintenance, performance, needs review

#13670 Bump primer-view-components to 0.9.1
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: maintenance

#13679 [50020] Remove db string length constraint on news_journals.title
  db/migrate/20230911093530_remove_news_journals_title_length_constraint.rb
Labels: bugfix, ruby, needs review

#13681 documentation/fixes
  docs/development/concepts/translations/README.md
  docs/getting-started/boards-introduction/README.md
Labels: documentation

#13666 [49781] Allow trial creation in development mode
  config/constants/settings/definition.rb
  lib_static/open_project/configuration/helpers.rb
  spec/features/admin/enterprise/enterprise_trial_spec.rb
Labels: bugfix

#13682 fix(lookbook): remove closing collapsible-section wrapper tag
  lookbook/previews/collapsible_section_preview/default.html.erb
Labels: needs review

#13657 [#49923] Seed dev user with shared work packages
  app/seeders/development_data/projects_seeder.rb
  app/seeders/development_data/shared_work_packages_seeder.rb
  app/seeders/development_data/users_seeder.rb
  app/seeders/development_data_seeder.rb
  app/seeders/standard.yml
  spec/seeders/root_seeder_standard_edition_spec.rb
Labels: needs review

#13680 [#49948] PDF export does not contain custom fields and some core values
  app/models/exports/formatters/custom_field.rb
  app/models/work_package/pdf_export/work_package_detail.rb
  spec/models/work_packages/pdf_export/work_package_to_pdf_spec.rb
Labels: needs review

#13690 [#50076] Add `view_shared_work_packages` permission
  config/initializers/permissions.rb
  config/locales/en.yml
  db/migrate/20230912185647_add_view_shared_work_packages_permission.rb
Labels: needs review

#13714 Fix flaky Team Planner feature spec
  modules/bim/spec/features/bcf_view_management_spec.rb
  modules/calendar/spec/features/query_handling_spec.rb
  modules/team_planner/spec/features/query_handling_spec.rb
  spec/features/views/shared_examples.rb
Labels: maintenance, needs review

#13705 Feature/document development process
  docs/development/git-workflow/README.md
  docs/development/product-development-handbook/README.md
  docs/development/release-process/README.md
  docs/development/releases/README.md
Labels: needs review

#13706 Standardize resolution in Cuprite Browser
  spec/support/cuprite_setup.rb
Labels: maintenance, needs review

#13704 Add erb-lint with GitHub a11y linters
  .erb-lint.yml
  .erb-linters/erblint-github.rb
  Gemfile
  Gemfile.lock
Labels: needs review

#13733 allow adding plugins via Gemfile.{modules,plugins}
  docker/prod/Dockerfile
Labels: needs review

#13731 Direct download of file from OneDrive storage
  modules/storages/app/common/storages/peripherals/storage_interaction/one_drive.rb
  modules/storages/app/common/storages/peripherals/storage_interaction/one_drive/download_link_query.rb
  modules/storages/spec/common/storages/peripherals/registry_spec.rb
  modules/storages/spec/common/storages/peripherals/storage_interaction/nextcloud/download_link_query_spec.rb
  modules/storages/spec/common/storages/peripherals/storage_interaction/one_drive/download_link_query_spec.rb
Labels: feature, pullpreview

#13737 Renaming meetings to classic and dynamic
  modules/meeting/app/controllers/meetings_controller.rb
  modules/meeting/app/views/meetings/_form.html.erb
  modules/meeting/config/locales/en.yml
  modules/meeting/spec/features/structured_meetings/structured_meeting_crud_spec.rb
Labels: feature

#13747 Fix typos in Application architecture doc pages
  docs/development/application-architecture/README.md
  docs/development/concepts/application-architecture/README.md
  docs/development/data-flow/README.md
  docs/development/environments/README.md
Labels: documentation, needs review

#13746 Fix typos in running tests doc page
  docs/development/running-tests/README.md
Labels: documentation, needs review

#13703 Default to target=_top for all links rendered in CKEditor
  lib/open_project/text_formatting/filters/link_attribute_filter.rb
  modules/documents/spec/application_helper_spec.rb
  modules/documents/spec/lib/open_project/markdown_formatting_spec.rb
  modules/meeting/spec/lib/open_project/markdown_formatting_spec.rb
  spec/features/forums/attachment_upload_spec.rb
  spec/lib/open_project/text_formatting/markdown/in_tool_links_spec.rb
  spec/lib/open_project/text_formatting/markdown/lists_spec.rb
  spec/lib/open_project/text_formatting/markdown/mentions_spec.rb
  spec/lib/open_project/text_formatting/markdown/setting_variable_spec.rb
  spec/lib/open_project/text_formatting/markdown/user_provided_links_spec.rb
  spec/lib/open_project/text_formatting/markdown/work_package_buttons_macro_spec.rb
  spec/requests/api/v3/render_resource_spec.rb
Labels: bugfix, needs review

#13716 Rework docs for roles and permissions
  docs/system-admin-guide/users-permissions/roles-permissions/README.md
  docs/user-guide/activity/README.md
Labels: documentation

#13756 Fix incorrect execution order of `OpenProject::AccessControl` spec setup
  spec/lib/open_project/access_control_spec.rb
Labels: needs review, flaky-spec

#13764 Docker supervisord: Configure local postgresql if database_url is empty
  docker/prod/supervisord
Labels: docker, needs review

#13739 Create RSpec "service" spec generator
  docs/development/running-tests/README.md
  lib/generators/open_project/rspec/service/USAGE
  lib/generators/open_project/rspec/service/service_generator.rb
  lib/generators/open_project/rspec/service/templates/service_spec.rb.tt
Labels: maintenance, needs review

#13770 Do not set statement timeout if already set to 0
  .rubocop.yml
  lib_static/open_project/migration_statement_timeout/manager.rb
Labels: needs review

#13768 Create a StructuredMeeting seeder for the demo project
  app/seeders/demo_data/project_seeder.rb
  app/seeders/standard.yml
  modules/meeting/app/seeders/meetings/demo_data/meeting_agenda_items_seeder.rb
  modules/meeting/app/seeders/meetings/demo_data/meeting_seeder.rb
  modules/meeting/app/seeders/standard.yml
  modules/meeting/spec/seeders/demo_data/project_seeder_spec.rb
Labels: feature, needs review

#13771 [#50106] Add menu item for Permissions report
  app/controllers/roles_controller.rb
  config/initializers/menus.rb
  spec/features/menu_items/users_and_permissions_menu_item_spec.rb
Labels: pullpreview, needs review

#13776 Use meeting duration from seed data
  modules/meeting/app/seeders/meetings/demo_data/meeting_seeder.rb
  modules/meeting/spec/seeders/demo_data/project_seeder_spec.rb
  spec/seeders/root_seeder_standard_edition_spec.rb
Labels: needs review

#13780 Documentation/fixes
  docs/development/contribution-documentation/README.md
  docs/development/product-development-handbook/README.md
  docs/development/releases/README.md
  docs/development/running-tests/README.md
  docs/installation-and-operations/installation/docker/README.md
  docs/installation-and-operations/installation/univention/README.md
  docs/system-admin-guide/system-settings/project-system-settings/README.md
  docs/system-admin-guide/users-permissions/placeholder-users/README.md
  docs/system-admin-guide/users-permissions/roles-permissions/README.md
  docs/user-guide/members/README.md
Labels: documentation

#13782 Allow ANDI to run in development mode
  config/initializers/secure_headers.rb
Labels: Accessibility

#13777 Focus the CKEditor content when clicking "Add notes"
  frontend/src/stimulus/controllers/dynamic/meeting-agenda-item-form.controller.ts
Labels: bugfix

#13781 [#50106] Document both ways of getting to the Permissions report
  docs/system-admin-guide/users-permissions/roles-permissions/README.md
Labels: documentation

#13740 [#50108] Standardize labels for Global and Project roles in user tab
  app/views/individual_principals/_memberships.html.erb
  app/views/principals/_available_global_roles.html.erb
  config/locales/en.yml
Labels: bugfix

#13786 Fix broken documentation links
  CONTRIBUTING.md
  docs/api/apiv3/example/README.md
  docs/development/code-review-guidelines/README.md
  docs/development/concepts/inline-editing/README.md
  docs/development/concepts/queries/README.md
  docs/development/concepts/translations/README.md
  docs/development/running-tests/README.md
  docs/development/security/README.md
  docs/faq/README.md
  docs/installation-and-operations/installation/manual/README.md
  docs/system-admin-guide/authentication/oauth-applications/README.md
  docs/user-guide/team-planner/README.md
  docs/user-guide/time-and-costs/README.md
  docs/user-guide/time-and-costs/time-and-costs-faq/README.md
  frontend/README.md
  frontend/src/locales/README.md
Labels: documentation

#13789 Address font-size issue
  frontend/src/global_styles/openproject/_variable_defaults.scss
Labels: bugfix, styling, needs review

#13672 Add an extra test case for file_links_api_spec.rb
  modules/storages/spec/requests/api/v3/file_links/file_links_api_spec.rb
Labels: needs review

#13778 Allow downloading ICS file of meeting by extracting meeting_mailer
  .rubocop.yml
  Gemfile
  Gemfile.lock
  modules/meeting/app/components/meetings/header_component.rb
  modules/meeting/app/controllers/meetings_controller.rb
  modules/meeting/app/mailers/meeting_mailer.rb
  modules/meeting/app/services/meetings/ical_service.rb
  modules/meeting/config/locales/en.yml
  modules/meeting/config/routes.rb
  modules/meeting/lib/open_project/meeting/engine.rb
  modules/meeting/spec/controllers/meeting_contents_controller_spec.rb
  modules/meeting/spec/features/structured_meetings/structured_meeting_crud_spec.rb
  modules/meeting/spec/mailers/meeting_mailer_spec.rb
  modules/meeting/spec/services/meetings/ical_service_spec.rb
Labels: feature

#13811 Add test-prof sampling recipe
  spec/rails_helper.rb
Labels: maintenance

#13793 [#50106] Remove link to permissions report from underneath roles index table
  app/views/roles/index.html.erb
  docs/system-admin-guide/users-permissions/roles-permissions/README.md
Labels: bugfix, needs review

#13792 [#50108] Fix Global role column heading in user tab
  app/views/principals/_global_roles.html.erb
  config/locales/en.yml
Labels: bugfix
