Repository opf/openproject, pull requests merged in 2023-07, with the labels that each got.

#12856 [#48421] Dedicated logo for the pdf export of work plans
  app/controllers/custom_styles_controller.rb
  app/models/custom_style.rb
  app/models/work_package/pdf_export/page.rb
  app/views/custom_styles/show.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20230613155001_add_export_logo_to_custom_style.rb
  frontend/src/global_styles/content/_custom_logo.sass
  spec/controllers/custom_styles_controller_spec.rb
  spec/factories/custom_style_factory.rb
  spec/models/custom_style_spec.rb
  spec/support/custom_styles/export_logos/export_logo_image.png
Labels: pullpreview

#13011 Aded linked alphabet on top
  docs/glossary/README.md
Labels: documentation

#13013 docs(glossary): remove redundant divs (IDs are auto-generated)
  docs/glossary/README.md
Labels: documentation

#12883 [#48116] Baseline: Handle work package no longer visible
  frontend/src/app/core/schemas/schema-cache.service.ts
  frontend/src/app/features/calendar/te-calendar/te-calendar.component.ts
  frontend/src/app/features/hal/resources/work-package-resource.ts
  frontend/src/app/features/work-packages/components/wp-breadcrumb/wp-breadcrumb.component.ts
  frontend/src/app/features/work-packages/components/wp-breadcrumb/wp-breadcrumb.html
  frontend/src/app/features/work-packages/components/wp-fast-table/builders/cell-builder.ts
  frontend/src/app/features/work-packages/components/wp-fast-table/builders/modes/hierarchy/hierarchy-render-pass.ts
  frontend/src/app/features/work-packages/components/wp-fast-table/builders/modes/hierarchy/single-hierarchy-row-builder.ts
  frontend/src/app/shared/components/datepicker/services/date-modal-relations.service.ts
  spec/features/work_packages/table/baseline/baseline_invisible_project_spec.rb
Labels: needs review

#13019 [#48588] Glossary of OpenProjects Vocabulary
  docs/glossary/README.md
  docs/glossary/glossary-openproject-custom-field.png
  docs/glossary/glossary-openproject-gantt-chart.png
  docs/glossary/glossary-openproject-header.png
  docs/glossary/glossary-openproject-sys-admin-edit-workflow.png
  docs/glossary/glossary-openproject-wiki.png
  docs/glossary/glossary-openproject-work-package-table.png
  docs/glossary/glossary-openproject-work-package.png
Labels: documentation

#13012 [#48653] PDF Export: Add export time into footer
  app/models/work_package/pdf_export/page.rb
Labels: pullpreview

#13022 [40157] Entries in summary emails not clickable in Outlook (links not working)
  app/views/announcement_mailer/announce.html.erb
  app/views/mailer/_border_table.html.erb
  app/views/mailer/_notification_row.html.erb
  config/locales/en.yml
Labels: bugfix, needs review

#13029 Mark selected tab as aria-selected
  frontend/src/app/shared/components/tabs/scrollable-tabs/scrollable-tabs.component.html
  frontend/src/app/shared/components/tabs/scrollable-tabs/scrollable-tabs.component.ts
Labels: needs review

#13035 Update required browser versions
  app/helpers/browser_helper.rb
  docs/installation-and-operations/system-requirements/README.md
Labels: documentation, maintenance

#13039 [#48965] Missing StorageType leads to server error in storage creation form
  modules/storages/app/views/storages/admin/storages/_form.html.erb
Labels: bugfix

#13053 Glossary: Deleted image for Gantt Charts
  docs/glossary/README.md
  docs/glossary/glossary-openproject-gantt-chart.png
Labels: documentation

#13054 [44963] Add premium/enterprise feature icon also in the Project settings
  app/views/projects/settings/modules/_form.html.erb
  config/locales/en.yml
  frontend/src/global_styles/common/menu/menu.sass
  frontend/src/global_styles/content/_enterprise.sass
  lib/open_project/access_control.rb
  lib/redmine/menu_manager/menu_helper.rb
  modules/calendar/config/locales/en.yml
  modules/team_planner/config/locales/en.yml
  modules/team_planner/lib/open_project/team_planner/engine.rb
Labels: feature, needs review

#13055 fix(links): adjust anchor links
  docs/faq/README.md
  docs/glossary/README.md
  docs/user-guide/projects/projects-faq/README.md
Labels: documentation

#13061 Use new concurrency workflow config to ensure only one pullpreview run at a time
  .github/workflows/pullpreview.yml
Labels: pullpreview

#13008 CentOS / RHEL 9 and Debian 12 support
  .buildpacks
  .pkgr.yml
  docs/installation-and-operations/installation/packaged/README.md
  docs/installation-and-operations/system-requirements/README.md
  packaging/addons/openproject-edition/bin/preinstall
  packaging/addons/openproject/bin/postinstall
  packaging/addons/repositories/bin/postinstall
  packaging/addons/repositories/bin/preinstall
Labels: packager

#13077 Glossary updates
  docs/glossary/README.md
Labels: documentation

#13071 Fix/align headers on user activity page
  app/helpers/users_helper.rb
  app/models/user_preference.rb
  app/views/common/feed.atom.builder
  app/views/journals/index.atom.builder
  app/views/users/show.html.erb
  lib/api/v3/users/user_representer.rb
  spec/helpers/users_helper_spec.rb
Labels: pullpreview

#13038 [48725] Unable to edit CF as Value is required
  frontend/src/stimulus/controllers/dynamic/admin/custom-fields.controller.ts
  spec/features/admin/custom_fields/user_custom_field_spec.rb
Labels: bugfix, pullpreview, needs review

#13096 Implementation/48573 implement a copy command
  modules/storages/app/common/storages/peripherals/storage_interaction/nextcloud/copy_template_folder_command.rb
  modules/storages/app/common/storages/peripherals/storage_interaction/nextcloud/create_folder_command.rb
  modules/storages/app/common/storages/peripherals/storage_interaction/nextcloud/util.rb
  modules/storages/app/common/storages/peripherals/storage_requests.rb
  modules/storages/spec/common/peripherals/copy_template_folder_command_spec.rb
Labels: feature

#13040 [#48862] Add PDF Export of work plans to our documentation
  docs/user-guide/work-packages/exporting/README.md
  docs/user-guide/work-packages/exporting/openproject_export_atom.png
  docs/user-guide/work-packages/exporting/openproject_export_csv.png
  docs/user-guide/work-packages/exporting/openproject_export_excel.png
  docs/user-guide/work-packages/exporting/openproject_export_wp.png
  docs/user-guide/work-packages/exporting/openproject_pdf_report.png
  docs/user-guide/work-packages/exporting/openproject_pdf_report_images.png
  docs/user-guide/work-packages/exporting/openproject_pdf_table_export.png
  docs/user-guide/work-packages/exporting/openproject_pdf_table_export_description.png
  docs/user-guide/work-packages/exporting/openproject_pdf_table_export_relations.png
  docs/user-guide/work-packages/exporting/openproject_wp_export_options.png
  docs/user-guide/work-packages/exporting/openproject_wp_report_total_sum.png
  docs/user-guide/work-packages/exporting/openproject_wp_table_total_sum.png
Labels: documentation

#13113 Include location in iCal meeting export
  modules/meeting/app/mailers/meeting_mailer.rb
  modules/meeting/spec/mailers/meeting_mailer_spec.rb
Labels: bugfix, needs review

#13062 [#48816] PDF Export: Indent third level in index
  app/models/work_package/pdf_export/schema.json
  app/models/work_package/pdf_export/standard.yml
  app/models/work_package/pdf_export/style.rb
  app/models/work_package/pdf_export/table_of_contents.rb
Labels: needs review

#13123 APIv3: Add info section on boolean filter values
  docs/api/apiv3/tags/filters.yml
Labels: documentation

#13089 Fix flaky `mobile_date_filter_spec` file
  spec/features/work_packages/table/queries/mobile_date_filter_spec.rb
  spec/support/shared/with_mobile_screen.rb
Labels: needs review

#13111 Make internal login route easier, allowing POST /login without session
  app/controllers/account_controller.rb
  spec/controllers/account_controller_spec.rb
Labels: bugfix, needs review

#13138 Prevent rendering of delete button on global calendars page
  modules/calendar/app/components/calendar/row_component.rb
  modules/calendar/spec/features/calendars_index_spec.rb
  modules/calendar/spec/support/pages/calendar.rb
Labels: needs review

#12801 [46837] Preview of linked WP is cut off in split view when close to the edge
  frontend/src/app/core/setup/globals/global-listeners/preview-trigger.service.ts
  frontend/src/app/shared/components/modals/preview-modal/wp-preview-modal/wp-preview.modal.ts
Labels: needs review

#13127 Allow saving CKEditor with ctrl+enter or cmd+enter
  frontend/src/app/shared/components/dynamic-forms/components/dynamic-inputs/formattable-textarea-input/components/formattable-control/formattable-control.component.html
  frontend/src/app/shared/components/editor/components/ckeditor-augmented-textarea/ckeditor-augmented-textarea.html
  frontend/src/app/shared/components/editor/components/ckeditor/ckeditor.types.ts
  frontend/src/app/shared/components/editor/components/ckeditor/op-ckeditor.component.ts
  frontend/src/app/shared/components/fields/edit/field-types/formattable-edit-field/formattable-edit-field.component.html
  spec/features/work_packages/details/markdown/description_editor_spec.rb
  spec/support/edit_fields/text_editor_field.rb
Labels: pullpreview

#13110 [#48647] PDF Export: Manage long query titles in footer
  app/models/work_package/pdf_export/common.rb
  app/models/work_package/pdf_export/page.rb
  app/models/work_package/pdf_export/style.rb
  app/models/work_package/pdf_export/work_package_to_pdf.rb
Labels: needs review

#13083 [#48966] refactored help text api models
  .redocly.lint-ignore.yaml
  docs/api/apiv3/components/schemas/help_text_collection_model.yml
  docs/api/apiv3/components/schemas/help_text_model.yml
  docs/api/apiv3/components/schemas/help_texts_model.yml
  docs/api/apiv3/openapi-spec.yml
  docs/api/apiv3/paths/help_text.yml
  docs/api/apiv3/paths/help_texts.yml
Labels: documentation, needs review

#12756 [57911] Implement show changes legend - remove margin-bottom for wp toolbar title
  frontend/src/global_styles/layout/_toolbar.sass
  frontend/src/global_styles/layout/_toolbar_mobile.sass
Labels: needs review

#13025 [47145] Selected date (number) not visible when matches with Today
  frontend/src/global_styles/content/_datepicker.sass
Labels: needs review

#13095 [46827] Custom project attribute triggers error when selected during project creation
  frontend/src/app/core/current-user/current-user.service.ts
  spec/features/projects/projects_custom_fields_spec.rb
Labels: bugfix, needs review

#13081 fix: align attribute groups across the application
  app/components/attribute_groups/attribute_group_component.html.erb
  app/components/attribute_groups/attribute_key_value_component.html.erb
  app/views/admin/info.html.erb
  app/views/oauth/applications/show.html.erb
  app/views/users/change_status_info.html.erb
  frontend/src/app/features/work-packages/components/wp-form-group/wp-attribute-group.component.sass
  frontend/src/app/features/work-packages/components/wp-form-group/wp-attribute-group.component.ts
  frontend/src/global_styles/content/_attributes_group.sass
  frontend/src/global_styles/content/_attributes_key_value.sass
  modules/budgets/app/views/budgets/show.html.erb
  modules/ldap_groups/app/views/ldap_groups/synchronized_filters/show.html.erb
  modules/ldap_groups/app/views/ldap_groups/synchronized_groups/show.html.erb
  modules/two_factor_authentication/app/views/two_factor_authentication/settings.html.erb
  modules/two_factor_authentication/app/views/two_factor_authentication/two_factor_devices/totp/_form.html.erb
  modules/two_factor_authentication/app/views/users/_two_factor_authentication_admin.html.erb
  modules/webhooks/app/views/webhooks/outgoing/admin/show.html.erb
  spec/components/attribute_groups/attribute_key_value_component_spec.rb
Labels: needs review

#13057 [48328] My Page: My spent time shows incorrect non-working days
  frontend/src/app/features/calendar/op-calendar.service.ts
  frontend/src/app/features/calendar/te-calendar/te-calendar.component.ts
  frontend/src/app/features/calendar/te-calendar/te-calendar.template.html
  modules/my_page/spec/features/my/time_entries_current_user_spec.rb
Labels: needs review

#13150 [#49143] Reorder items in the top menu in tandem with the global sidebar
  config/initializers/menus.rb
  modules/boards/lib/open_project/boards/engine.rb
  modules/meeting/lib/open_project/meeting/engine.rb
  modules/team_planner/lib/open_project/team_planner/engine.rb
  spec/features/menu_items/top_menu_item_spec.rb
  spec/lib/redmine/menu_manager_spec.rb
Labels: needs review

#13152 (fix): Keep project filters section hidden when using predefined filters from sidebar
  app/helpers/projects_helper.rb
  app/views/projects/filters/_form.html.erb
  app/views/projects/index.html.erb
  spec/features/projects/projects_index_spec.rb
  spec/support/pages/projects/index.rb
Labels: needs review

#13159 [#35804] CFs marked as searchable are so globally and even if they aren't filters
  app/models/queries/work_packages/filter/search_filter.rb
  spec/features/search/search_spec.rb
Labels: needs review

#13164 Replace baseline icons
  frontend/src/app/features/work-packages/components/wp-baseline/baseline-legends/baseline-legends.component.html
  frontend/src/app/features/work-packages/components/wp-baseline/baseline-legends/baseline-legends.component.sass
  frontend/src/app/features/work-packages/components/wp-card-view/wp-single-card/wp-single-card.component.html
  frontend/src/app/features/work-packages/components/wp-fast-table/builders/baseline/baseline-column-builder.ts
  frontend/src/app/spot/icon-font/icons/arrow-in.svg
  frontend/src/app/spot/icon-font/icons/arrow-out.svg
  frontend/src/app/spot/icon-font/icons/baseline.svg
  frontend/src/app/spot/icon-font/icons/delta-triangle.svg
  frontend/src/app/spot/icon-font/src/arrow-in.svg
  frontend/src/app/spot/icon-font/src/arrow-out.svg
  frontend/src/app/spot/icon-font/src/baseline.svg
  frontend/src/app/spot/icon-font/src/delta-triangle.svg
  frontend/src/app/spot/styles/sass/common/icon.sass
  frontend/src/assets/fonts/openproject_icon/openproject-icon-font.svg
  frontend/src/assets/fonts/openproject_icon/openproject-icon-font.ttf
  frontend/src/assets/fonts/openproject_icon/openproject-icon-font.woff
  frontend/src/assets/fonts/openproject_icon/openproject-icon-font.woff2
  frontend/src/assets/fonts/openproject_spot_icon/openproject-spot-icon-font.svg
  frontend/src/assets/fonts/openproject_spot_icon/openproject-spot-icon-font.ttf
  frontend/src/assets/fonts/openproject_spot_icon/openproject-spot-icon-font.woff
  frontend/src/assets/fonts/openproject_spot_icon/openproject-spot-icon-font.woff2
  frontend/src/global_styles/fonts/_openproject_icon_definitions.sass
  frontend/src/global_styles/fonts/_openproject_icon_font.lsg
  frontend/src/global_styles/layout/work_packages/_table_baseline.sass
Labels: feature

#13163 Replace stub_env with with_env
  modules/bim/spec/seeders/root_seeder_bim_edition_spec.rb
  spec/constants/settings/definition_spec.rb
  spec/helpers/frontend_asset_helper_spec.rb
  spec/lib/open_project/feature_decisions_spec.rb
  spec/requests/api/v3/configuration_resource_spec.rb
  spec/seeders/root_seeder_standard_edition_spec.rb
  spec/support/root_seeder_test_helpers.rb
Labels: maintenance, needs review

#13174 Remove fixed height of table modal configuration
  frontend/src/global_styles/content/work_packages/_table_configuration_modal.sass
Labels: bugfix

#13175 Disable future dates in baseline datepickers
  frontend/src/app/features/work-packages/components/wp-baseline/baseline/baseline.component.html
  frontend/src/app/features/work-packages/components/wp-baseline/baseline/baseline.component.ts
  frontend/src/app/shared/components/datepicker/sheet/date-picker-sheet.component.ts
Labels: bugfix

#13177 Detect baseline changes from null to something
  frontend/src/app/features/work-packages/routing/wp-view-base/view-services/wp-view-baseline.service.ts
  spec/features/work_packages/table/baseline/baseline_rendering_spec.rb
Labels: bugfix

#13156 Fix WikiPage#destroy when destroying child, then parent
  app/models/wiki_page.rb
Labels: bugfix

#13179 Use saas-compatible check for the enterprise icons
  app/views/projects/settings/modules/_form.html.erb
Labels: bugfix

#13176 Fix quoting first message with stimulus
  app/views/messages/show.html.erb
  spec/features/forums/message_spec.rb
Labels: bugfix

#13178 Correctly map milestone date in comparison with timestamps
  frontend/src/app/features/work-packages/components/wp-fast-table/builders/cell-builder.ts
  spec/features/work_packages/table/baseline/baseline_rendering_spec.rb
  spec/support/components/work_packages/baseline.rb
Labels: bugfix

#13191 PDF Export: generated documentation for pdf styling yaml
  Gemfile
  Gemfile.lock
  app/models/work_package/pdf_export/schema.json
  app/models/work_package/pdf_export/standard.yml
  app/models/work_package/pdf_export/style.rb
  docs/system-admin-guide/design/pdf-export-styles/README.md
  script/pdf_export/generate_styles_doc
  script/pdf_export/validate_styles
Labels: needs review

#13195 Stabilise sidemenu loading
  frontend/src/app/shared/components/op-view-select/op-view-select.component.ts
  frontend/src/app/shared/components/op-view-select/op-view-select.template.html
Labels: bugfix

#13165 [#48546] Add Submenus for Meetings
  frontend/src/app/shared/components/sidemenu/sidemenu.component.sass
  frontend/src/app/shared/components/sidemenu/sidemenu.component.ts
  frontend/src/global_styles/content/_sidebar.sass
  frontend/src/stimulus/controllers/dynamic/menus/expandable-sidemenu.controller.ts
  modules/meeting/app/components/meetings/table_component.rb
  modules/meeting/app/controllers/meetings_controller.rb
  modules/meeting/app/helpers/meetings_helper.rb
  modules/meeting/app/views/meetings/_menu_query_select.html.erb
  modules/meeting/config/locales/en.yml
  modules/meeting/lib/open_project/meeting/engine.rb
  modules/meeting/spec/factories/meeting_participant_factory.rb
  modules/meeting/spec/features/meetings_copy_spec.rb
  modules/meeting/spec/features/meetings_global_menu_item_spec.rb
  modules/meeting/spec/features/meetings_index_spec.rb
  modules/meeting/spec/support/pages/meetings/index.rb
  spec/lib/redmine/menu_manager_spec.rb
Labels: needs review

#13205 Fix double render and missing translation on `types_controller#move`
  app/controllers/types_controller.rb
  config/locales/en.yml
  spec/controllers/types_controller_spec.rb
Labels: bugfix, needs review

#13189 Implementation/48587 copy project folder on project copy
  app/services/projects/copy_service.rb
  config/locales/en.yml
  modules/storages/app/common/storages/peripherals/storage_interaction/nextcloud/copy_template_folder_command.rb
  modules/storages/app/models/storages/project_storage.rb
  modules/storages/app/models/storages/storage_error.rb
  modules/storages/app/services/projects/copy/file_links_dependent_service.rb
  modules/storages/app/services/projects/copy/storage_project_folders_dependent_service.rb
  modules/storages/app/services/projects/copy/storages_dependent_service.rb
  modules/storages/app/services/storages/group_folder_properties_sync_service.rb
  modules/storages/spec/common/peripherals/copy_template_folder_command_spec.rb
Labels: feature

#13109 [48967] Extract create_user permission out of manage_user
  app/components/users/row_component.rb
  app/contracts/users/base_contract.rb
  app/contracts/users/create_contract.rb
  app/contracts/users/update_contract.rb
  app/controllers/members_controller.rb
  app/controllers/users_controller.rb
  app/helpers/users_helper.rb
  app/seeders/common.yml
  app/views/users/_toolbar.html.erb
  app/views/users/show.html.erb
  config/initializers/menus.rb
  config/initializers/permissions.rb
  config/locales/en.yml
  db/migrate/20230718084649_add_create_user_permission_to_roles.rb
  lib/api/v3/users/create_form_api.rb
  lib/api/v3/users/user_representer.rb
  lib/api/v3/users/users_api.rb
  spec/contracts/users/shared_contract_examples.rb
  spec/features/members/invitation_spec.rb
  spec/features/users/create_spec.rb
  spec/features/users/edit_users_spec.rb
  spec/features/users/invitation_spec.rb
  spec/features/users/invite_user_modal/custom_fields_spec.rb
  spec/features/users/invite_user_modal/invite_user_modal_spec.rb
  spec/lib/api/v3/capabilities/capability_sql_representer_rendering_spec.rb
  spec/models/capabilities/scopes/default_spec.rb
  spec/models/permitted_params_spec.rb
  spec/requests/api/v3/capability_resource_spec.rb
  spec/requests/api/v3/placeholder_users/delete_resource_spec.rb
  spec/requests/api/v3/user/create_form_resource_spec.rb
  spec/requests/api/v3/user/create_user_resource_spec.rb
Labels: needs review

#13112 Docs for 13.0: Added details on delay/lag and renamed operators
  docs/user-guide/work-packages/set-change-dates/README.md
  docs/user-guide/work-packages/work-package-relations-hierarchies/README.md
  docs/user-guide/work-packages/work-package-table-configuration/README.md
Labels: documentation

#12852 Allow azure providers to use a configured tenant and graph API
  Gemfile.lock
  Gemfile.modules
  docs/system-admin-guide/authentication/openid-providers/README.md
  frontend/src/stimulus/controllers/dynamic/admin/openid-connect-providers.controller.ts
  modules/openid_connect/app/controllers/openid_connect/providers_controller.rb
  modules/openid_connect/app/models/openid_connect/provider.rb
  modules/openid_connect/app/views/openid_connect/providers/_azure_form.html.erb
  modules/openid_connect/app/views/openid_connect/providers/_form.html.erb
  modules/openid_connect/app/views/openid_connect/providers/new.html.erb
  modules/openid_connect/config/locales/en.yml
Labels: bugfix, needs review

#13227 Fix Sidebar not vertically scrolling on Work Packages index pages
  frontend/src/global_styles/content/_sidebar.sass
Labels: bugfix, needs review

#13219 Glossary-update (docs)
  docs/glossary/README.md
Labels: documentation

#13237 Fix(WebMock): Allow `openproject-ci-public-logs.s3.eu-west-1.amazonaws.com` CI s3 bucket host
  spec/support/webmock.rb
Labels: needs review

#13249 fix(docs): adjust broken links
  docs/api/apiv3/tags/work_packages.yml
  docs/faq/README.md
  docs/installation-and-operations/operation/upgrading/README.md
  docs/user-guide/work-packages/exporting/README.md
Labels: documentation

#13220 [#49289] Fix CSS selectors for sidebar items in Notification Center
  frontend/src/global_styles/content/_index.sass
  frontend/src/global_styles/content/_sidebar.sass
  frontend/src/global_styles/content/_sidemenu.sass
  frontend/src/global_styles/layout/_main_menu.sass
  modules/meeting/app/views/meetings/_menu_query_select.html.erb
Labels: bugfix

#13162 Also allow saving with CTRL/CMD+enter on rails forms
  docs/user-guide/wysiwyg/README.md
  frontend/src/app/shared/components/editor/components/ckeditor-augmented-textarea/ckeditor-augmented-textarea.component.ts
  frontend/src/app/shared/components/editor/components/ckeditor-augmented-textarea/ckeditor-augmented-textarea.html
  lib/open_project/text_formatting/formats/markdown/helper.rb
  modules/meeting/spec/features/meetings_show_spec.rb
  spec/support/pages/admin/system_settings/general.rb
Labels: feature, pullpreview

#12490 Removing references to Enterprise for multi-select custom fields
  docs/system-admin-guide/custom-fields/README.md
  lib/open_project/static/links.rb
Labels: documentation

#13168 Bump i18n-js to v4
  .gitignore
  Gemfile
  Gemfile.lock
  config/environments/development.rb
  config/i18n-js.yml
  config/i18n.yml
  config/initializers/i18n-js.rb
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/core/i18n/i18n.service.ts
  frontend/src/app/core/setup/init-locale.ts
  frontend/src/app/core/setup/init-vendors.ts
  frontend/src/app/features/calendar/te-calendar/te-calendar.component.ts
  frontend/src/app/features/hal/services/hal-resource-notification.service.ts
  frontend/src/app/shared/components/attachments/attachment-list/attachment-list-item.component.ts
  frontend/src/app/shared/components/grids/widgets/time-entries/current-user/time-entries-current-user.component.ts
  frontend/src/app/shared/components/grids/widgets/time-entries/list/time-entries-list.component.ts
  frontend/src/typings/shims.d.ts
  frontend/src/vendor/i18n.js
  frontend/tsconfig.base.json
  lib/tasks/assets.rake
  modules/dashboards/spec/features/time_entries_spec.rb
  modules/my_page/spec/features/my/time_entries_current_user_spec.rb
Labels: maintenance

#12823 Implementation/45980 improve performance of baseline filtering
  app/models/journable/historic_active_record_relation.rb
  app/models/journable/timestamps.rb
  app/models/journable/with_historic_attributes.rb
  app/models/journable/with_historic_attributes/loader.rb
  app/models/journal/timestamps.rb
  app/models/query/results.rb
  app/services/add_work_package_note_service.rb
  app/services/journals/create_service.rb
  config/application.rb
  db/migrate/20230608151123_add_validity_period_to_journals.rb
  lib/api/v3/activities/activities_by_work_package_api.rb
  modules/backlogs/spec/models/burndown_spec.rb
  modules/bim/spec/bcf/bcf_xml/issue_writer_spec.rb
  modules/documents/app/models/document.rb
  modules/storages/spec/services/storages/file_links/create_service_spec.rb
  modules/storages/spec/services/storages/file_links/delete_service_spec.rb
  spec/controllers/activities_controller_spec.rb
  spec/factories/journal_factory.rb
  spec/factories/work_package_factory.rb
  spec/features/work_packages/edit_work_package_spec.rb
  spec/features/work_packages/tabs/activity_notifications_spec.rb
  spec/features/work_packages/tabs/activity_revisions_spec.rb
  spec/features/work_packages/tabs/activity_tab_spec.rb
  spec/lib/api/v3/work_packages/work_package_collection_representer_spec.rb
  spec/lib/api/v3/work_packages/work_package_representer_spec.rb
  spec/lib/journal_formatter/diff_spec.rb
  spec/models/journable/historic_active_record_relation_spec.rb
  spec/models/journable/timestamps_spec.rb
  spec/models/journable/with_historic_attributes_spec.rb
  spec/models/query/results_filter_on_historic_data_spec.rb
  spec/models/work_package/work_package_acts_as_journalized_spec.rb
  spec/requests/api/v3/work_packages/index_resource_spec.rb
  spec/requests/api/v3/work_packages/show_resource_spec.rb
  spec/support/components/work_packages/activities.rb
  spec/support/queries/shared_get_individual_query_examples.rb
Labels: pullpreview

#13198 Baseline: user guide docs for 13.0
  docs/user-guide/README.md
  docs/user-guide/work-packages/baseline-comparison/13-0_Baseline_activeFilters.png
  docs/user-guide/work-packages/baseline-comparison/13-0_Baseline_dateRange.png
  docs/user-guide/work-packages/baseline-comparison/13-0_Baseline_dropmodal.png
  docs/user-guide/work-packages/baseline-comparison/13-0_Baseline_legend.png
  docs/user-guide/work-packages/baseline-comparison/13-0_Baseline_maintainedChanges.png
  docs/user-guide/work-packages/baseline-comparison/13-0_Baseline_noLongerMeets.png
  docs/user-guide/work-packages/baseline-comparison/13-0_Baseline_nowMeets.png
  docs/user-guide/work-packages/baseline-comparison/13-0_Baseline_oldNewValues.png
  docs/user-guide/work-packages/baseline-comparison/13-0_Baseline_overview.png
  docs/user-guide/work-packages/baseline-comparison/13-0_Baseline_specificDate.png
  docs/user-guide/work-packages/baseline-comparison/13-0_Baseline_table.png
  docs/user-guide/work-packages/baseline-comparison/13_0_Baseline_unsupportedColumn.png
  docs/user-guide/work-packages/baseline-comparison/README.md
Labels: documentation

#13253 fix(docs): adjust broken links
  docs/user-guide/README.md
Labels: documentation

#13251 Change design of loading indicator
  frontend/src/app/core/loading-indicator/loading-indicator.service.ts
  frontend/src/app/shared/components/toaster/toast.component.html
  frontend/src/global_styles/content/_loading_indicator.lsg
  frontend/src/global_styles/content/_loading_indicator.sass
  modules/boards/spec/features/support/board_page.rb
  spec/support/onboarding_helper.rb
  spec/support/shared/loading_indicator_saveguard.rb
Labels: feature

#13236 [#49285] Fix flaky specs `modules/storages/spec/features/{manage_project_storage_spec.rb,create_file_links_spec.rb}`
  modules/storages/spec/features/create_file_links_spec.rb
  modules/storages/spec/features/manage_project_storage_spec.rb
Labels: needs review

#13256 Fix missing 18n export
  bin/setup_dev
  docker/dev/backend/scripts/setup
  docker/dev/backend/scripts/setup-tests
  docs/development/concepts/translations/README.md
  frontend/package-lock.json
Labels: needs review

#13258 Fix ./modules/storages/spec/features/manage_project_storage_spec.rb
  modules/storages/spec/features/manage_project_storage_spec.rb
Labels: needs review

#13252 improve documentation on journals create service
  app/services/journals/create_service.rb
Labels: needs review

#13267 Add breadcrumb toolbar to the show page and render in Admin Layout when possible
  app/controllers/users_controller.rb
  app/views/users/show.html.erb
Labels: needs review

#13266 alter calendar admin menu title
  app/controllers/admin/settings/icalendar_settings_controller.rb
  app/views/admin/settings/icalendar_settings/show.html.erb
  config/initializers/menus.rb
  config/locales/en.yml
  modules/calendar/spec/features/calendar_sharing_spec.rb
Labels: needs review

#12948 Added support for multi-value Version custom fields
  app/models/custom_field.rb
  frontend/src/app/shared/components/fields/display/display-field.initializer.ts
  frontend/src/app/shared/components/fields/display/display-field.service.ts
  frontend/src/app/shared/components/fields/edit/edit-field.initializer.ts
  frontend/src/stimulus/controllers/dynamic/admin/custom-fields.controller.ts
  lib/open_project/journal_formatter/custom_field.rb
  spec/features/activities/project_attributes_activity_spec.rb
  spec/features/custom_fields/multi_version_custom_field_spec.rb
Labels: feature

#13265 Update NEW FEATURES teaser on application start page
  config/locales/js-en.yml
  frontend/src/app/features/homescreen/blocks/new-features.component.ts
  frontend/src/assets/images/12_5_features.svg
  frontend/src/assets/images/13_0_features.svg
Labels: feature

#13270 [33375] Save newly created meeting via cmd+Enter
  frontend/src/app/shared/components/attachments/attachments.component.ts
  frontend/src/app/shared/components/editor/components/ckeditor-augmented-textarea/ckeditor-augmented-textarea.component.ts
  frontend/src/global_styles/content/_forms.lsg
  modules/meeting/spec/features/meetings_new_spec.rb
Labels: bugfix

#13277 Ensure `folderModeValue` is updated to the selected radio button
  frontend/src/stimulus/controllers/dynamic/project-storage-form.controller.ts
Labels: bugfix

#13268 Documentation update on admin settings
  docs/api/apiv3/openapi-spec.yml
  docs/faq/README.md
  docs/getting-started/my-account/README.md
  docs/getting-started/work-packages-introduction/README.md
  docs/release-notes/12-3-0/README.md
  docs/system-admin-guide/README.md
  docs/system-admin-guide/api-and-webhooks/README.md
  docs/system-admin-guide/api-and-webhooks/admin-api.png
  docs/system-admin-guide/api-and-webhooks/create-button-new-webhook.png
  docs/system-admin-guide/api-and-webhooks/incoming-vs-outgoing-webhooks.png
  docs/system-admin-guide/api-and-webhooks/steps-to-create-a-webhook.png
  docs/system-admin-guide/authentication/oauth-applications/README.md
  docs/system-admin-guide/calendars-and-dates/README.md
  docs/system-admin-guide/calendars-and-dates/add-non-working-day-link.png
  docs/system-admin-guide/calendars-and-dates/add-working-day-modal.png
  docs/system-admin-guide/calendars-and-dates/admin-working-days.png
  docs/system-admin-guide/calendars-and-dates/apply-changes-button.png
  docs/system-admin-guide/calendars-and-dates/calendar-subscriptions.png
  docs/system-admin-guide/calendars-and-dates/date-format.png
  docs/system-admin-guide/emails-and-notifications/README.md
  docs/system-admin-guide/emails-and-notifications/admin-email-aggregation.png
  docs/system-admin-guide/emails-and-notifications/admin-email-notifications-header-footer.png
  docs/system-admin-guide/emails-and-notifications/admin-email-notifications.png
  docs/system-admin-guide/emails-and-notifications/admin-incoming-emails.png
  docs/system-admin-guide/incoming-and-outgoing/README.md
  docs/system-admin-guide/incoming-and-outgoing/image-20211129133408193.png
  docs/system-admin-guide/incoming-and-outgoing/image-20211129135301400.png
  docs/system-admin-guide/incoming-and-outgoing/image-20211129135851860.png
  docs/system-admin-guide/incoming-and-outgoing/image-20211129140341687.png
  docs/system-admin-guide/incoming-and-outgoing/webhooks/README.md
  docs/system-admin-guide/initial-setup/README.md
  docs/system-admin-guide/openproject_system_administration_start_page.png
  docs/system-admin-guide/system-settings/README.md
  docs/system-admin-guide/system-settings/api-settings/README.md
  docs/system-admin-guide/system-settings/display-settings/README.md
  docs/system-admin-guide/system-settings/display-settings/image-20211209163420270.png
  docs/system-admin-guide/system-settings/image-20220125122744695.png
  docs/system-admin-guide/system-settings/languages/README.md
  docs/system-admin-guide/system-settings/languages/image-20211209162728606.png
  docs/system-admin-guide/system-settings/languages/openproject-system-languages.png
  docs/system-admin-guide/system-settings/system-settings.png
  docs/system-admin-guide/users-permissions/settings/Openproject_system_guide_user_settings.png
  docs/system-admin-guide/users-permissions/settings/README.md
  docs/system-admin-guide/users-permissions/settings/openproject_system_guide_user_display_format.png
  docs/system-admin-guide/working-days/README.md
  docs/system-admin-guide/working-days/add-non-working-day-link.png
  docs/system-admin-guide/working-days/add-working-day-modal.png
  docs/system-admin-guide/working-days/admin-working-days.png
  docs/system-admin-guide/working-days/apply-changes-button.png
  docs/user-guide/team-planner/README.md
  docs/user-guide/work-packages/set-change-dates/README.md
Labels: documentation

#13193 [49245] Changed dates are misaligned with the other dates
  frontend/src/global_styles/content/_datepicker.sass
  frontend/src/global_styles/content/_forms.sass
  frontend/src/global_styles/content/_table.sass
  frontend/src/global_styles/content/work_packages/inplace_editing/_display_fields.sass
  frontend/src/global_styles/layout/work_packages/_table_baseline.sass
  frontend/src/global_styles/openproject/_forms.sass
  frontend/src/global_styles/openproject/_homescreen.sass
  frontend/src/global_styles/openproject/_variables.sass
  frontend/src/styles.scss
Labels: bugfix

#13238 [#49081] PDF-Export: Add tests for pdf content
  Gemfile
  Gemfile.lock
  spec/models/work_packages/pdf_export/work_package_list_to_pdf_spec.rb
  spec/models/work_packages/pdf_export/work_package_to_pdf_spec.rb
  spec/support/work_packages/pdf_export.rb
Labels: needs review

#13298 Glossary update / Documentation
  docs/glossary/README.md
Labels: documentation

#13284 [#48623] Missing spacing between fields on project information form
  frontend/src/app/shared/components/forms/form.sass
Labels: bugfix

#13302 Include Budget in Checksum for WorkPackage to invalidate cache
  lib/api/v3/work_packages/eager_loading/checksum.rb
  spec/lib/api/v3/work_packages/eager_loading/cache_checksum_integration_spec.rb
Labels: bugfix, needs review

#13308 [#49410] Ensure Baseline functionality is reset when switching to a Builtin View
  frontend/src/app/features/work-packages/components/wp-baseline/baseline/baseline.component.ts
  spec/features/work_packages/table/baseline/baseline_rendering_spec.rb
Labels: needs review

#13309 [#49319] Correct Baseline legend phrasing for changes between dates
  config/locales/js-en.yml
  frontend/src/app/features/work-packages/components/wp-baseline/baseline-legends/baseline-legends.component.ts
  spec/features/work_packages/table/baseline/baseline_query_spec.rb
Labels: bugfix, needs review
