Repository opf/openproject, pull requests merged in 2023-02, with the labels that each got.

#12005 Timecamp integration
  docs/user-guide/time-and-costs/time-tracking/timecamp-integration/README.md
  docs/user-guide/time-and-costs/time-tracking/timecamp-integration/Start-time-in-OP.png
  docs/user-guide/time-and-costs/time-tracking/timecamp-integration/Time-appears-in-TC.png
  docs/user-guide/time-and-costs/time-tracking/timecamp-integration/TimeCamp_Chrome_plugin.png
  docs/user-guide/time-and-costs/time-tracking/timecamp-integration/add_extension.png
  docs/user-guide/time-and-costs/time-tracking/timecamp-integration/create-project-in-TimeCamp.png
  docs/user-guide/time-and-costs/time-tracking/timecamp-integration/create-task-in-TimeCamp.png
  docs/user-guide/time-and-costs/time-tracking/timecamp-integration/download-timecamp-extension.png
  docs/user-guide/time-and-costs/time-tracking/timecamp-integration/pin-to-browser-full.png
  docs/user-guide/time-and-costs/time-tracking/timecamp-integration/pin_to_browser.png
  docs/user-guide/time-and-costs/time-tracking/timecamp-integration/project-with-2-tasks-in-timecamp.png
  docs/user-guide/time-and-costs/time-tracking/timecamp-integration/project-with-2-tasks.png
  docs/user-guide/time-and-costs/time-tracking/timecamp-integration/select-a-task-2.png
  docs/user-guide/time-and-costs/time-tracking/timecamp-integration/select-a-task.png
  docs/user-guide/time-and-costs/time-tracking/timecamp-integration/stop-time-in-OP.png
  docs/user-guide/time-and-costs/time-tracking/timecamp-integration/work-package-start-timer.png
Labels: pullpreview

#12004 [#45954] Extend OpenAPI spec for storage files endpoint
  docs/api/apiv3/components/schemas/file_collection_model.yml
  docs/api/apiv3/components/schemas/storage_file_location_model.yml
  docs/api/apiv3/components/schemas/storage_file_model.yml
  docs/api/apiv3/components/schemas/storage_files_model.yml
  docs/api/apiv3/openapi-spec.yml
  docs/api/apiv3/paths/storage_files.yml
Labels: feature

#11628 [#45956] New tooltip proposal
  frontend/src/app/shared/components/header-project-select/insert-in-list.ts
  frontend/src/app/shared/components/project-include/calculate-positions.ts
  frontend/src/app/shared/components/project-include/insert-in-list.ts
  frontend/src/app/shared/components/project-include/list/project-include-list.component.html
  frontend/src/app/shared/components/project-include/list/project-include-list.component.ts
  frontend/src/app/shared/components/project-include/project-include.component.sass
  frontend/src/app/shared/components/project-include/project-include.component.ts
  frontend/src/app/shared/components/searchable-project-list/project-data.ts
  frontend/src/app/shared/components/storages/file-link-list-item/file-link-list-item.html
  frontend/src/app/shared/components/storages/storage-file-list-item/storage-file-list-item.html
  frontend/src/app/spot/components/tooltip/tooltip.component.ts
  frontend/src/app/spot/styles/sass/components/tooltip.sass
Labels: pullpreview

#12020 Update system guide users and permissions groups
  docs/system-admin-guide/users-permissions/avatars/README.md
  docs/system-admin-guide/users-permissions/avatars/image-20200211142213576.png
  docs/system-admin-guide/users-permissions/avatars/system-guide-avatar.png
  docs/system-admin-guide/users-permissions/groups/README.md
  docs/system-admin-guide/users-permissions/groups/Sys-admin-edit-groups.png
  docs/system-admin-guide/users-permissions/groups/create-new-group.png
  docs/system-admin-guide/users-permissions/groups/image-20200115164118182.png
  docs/system-admin-guide/users-permissions/groups/image-20200211142053557.png
  docs/system-admin-guide/users-permissions/groups/no-groups-yet.png
  docs/system-admin-guide/users-permissions/groups/system-guide-edit-groups.png
  docs/system-admin-guide/users-permissions/placeholder-users/README.md
  docs/system-admin-guide/users-permissions/placeholder-users/image-20210305170745049.png
  docs/system-admin-guide/users-permissions/placeholder-users/image-20210305171118210.png
  docs/system-admin-guide/users-permissions/placeholder-users/openproject-system-guide-ph-user-change-button.png
  docs/system-admin-guide/users-permissions/placeholder-users/openproject-system-guide-ph-user-new-project.png
  docs/system-admin-guide/users-permissions/placeholder-users/system-guide-ph-user-edit-project-role.png
  docs/system-admin-guide/users-permissions/roles-permissions/README.md
  docs/system-admin-guide/users-permissions/roles-permissions/Sys-admin-edit-roles.png
  docs/system-admin-guide/users-permissions/roles-permissions/system-guide-edit-role1.png
  docs/system-admin-guide/users-permissions/roles-permissions/system-guide-new-role.png
  docs/system-admin-guide/users-permissions/roles-permissions/system-guide-roles.png
  docs/system-admin-guide/users-permissions/roles-permissions/work-package-tracking-for-role-8145761.png
  docs/system-admin-guide/users-permissions/users-permissions-faq/README.md
Labels: documentation

#11996 [#43693] add file link list component to new work package form
  frontend/src/app/core/path-helper/path-helper.service.ts
  frontend/src/app/core/state/storages/storages.service.ts
  frontend/src/app/features/work-packages/components/wp-single-view/wp-single-view.component.ts
  frontend/src/app/features/work-packages/components/wp-single-view/wp-single-view.html
  frontend/src/app/features/work-packages/routing/wp-view-base/work-package-single-view.base.ts
  frontend/src/app/shared/components/fields/changeset/resource-changeset.ts
  frontend/src/app/shared/components/storages/storage/storage.component.ts
  frontend/src/global_styles/content/work_packages/tabs/_tab_content.sass
  frontend/src/global_styles/layout/work_packages/_details_view.sass
  spec/features/types/form_configuration_spec.rb
  spec/features/work_packages/tabs/files_tab_spec.rb
Labels: feature

#12030 Feature/43904 user guide add a link for ressource management in time and cost tracking
  docs/faq/README.md
  docs/user-guide/time-and-costs/README.md
Labels: documentation, needs review

#11718 [45001] Create a new component to show the list of non-working days of a year
  app/controllers/admin/settings/working_days_settings_controller.rb
  app/helpers/confirmation_dialog_helper.rb
  app/services/settings/working_days_update_service.rb
  app/views/admin/settings/working_days_settings/show.html.erb
  config/locales/en.yml
  config/locales/js-en.yml
  frontend/.eslintrc.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/core/setup/global-dynamic-components.const.ts
  frontend/src/app/shared/components/datepicker/single-date-picker/single-date-picker.component.html
  frontend/src/app/shared/components/datepicker/single-date-picker/single-date-picker.component.ts
  frontend/src/app/shared/components/modals/confirm-dialog/confirm-dialog.modal.html
  frontend/src/app/shared/components/modals/confirm-dialog/confirm-dialog.modal.sass
  frontend/src/app/shared/components/modals/confirm-dialog/confirm-dialog.modal.ts
  frontend/src/app/shared/components/op-non-working-days-list/op-non-working-days-list.component.html
  frontend/src/app/shared/components/op-non-working-days-list/op-non-working-days-list.component.sass
  frontend/src/app/shared/components/op-non-working-days-list/op-non-working-days-list.component.ts
  frontend/src/app/shared/shared.module.ts
  frontend/src/app/spot/components/text-field/text-field.component.html
  frontend/src/app/spot/components/text-field/text-field.component.ts
  package.json
  spec/controllers/admin/settings/working_days_settings_controller_spec.rb
  spec/features/admin/working_days_spec.rb
  spec/services/settings/working_days_update_service_spec.rb
Labels: feature, pullpreview

#12084 [45794] Incorrect width of the "Add" buttons in the sidebar (Calendar, Boards)
  frontend/src/app/features/boards/boards-sidebar/boards-menu.component.html
  frontend/src/app/features/calendar/sidemenu/calendar-sidemenu.component.html
Labels: bugfix

#12065 Update labels for project activity filters
  app/views/activities/index.html.erb
  config/locales/en.yml
  modules/budgets/config/locales/en.yml
  modules/documents/config/locales/en.yml
  modules/meeting/config/locales/en.yml
  spec/features/activities/activity_page_navigation_spec.rb
  spec/features/activities/disabled_activity_spec.rb
  spec/features/activities/wiki_activity_spec.rb
Labels: pullpreview

#12099 clear file mount column on custom style image deletion
  app/models/custom_style.rb
  spec/models/custom_style_spec.rb
Labels: bugfix, needs review

#12061 [#36129] Changing position in backlog creates activity of custom fiel…
  app/services/journals/create_service.rb
  modules/backlogs/spec/models/task_spec.rb
Labels: bugfix

#12118 Docs additions support
  docs/development/security/README.md
  docs/enterprise-guide/enterprise-cloud-guide/support/README.md
Labels: documentation

#12129 [46305] Wrong text references in the non working days admin page
  config/locales/en.yml
  config/locales/js-en.yml
Labels: bugfix

#12153 [#46311] Typo in tooltip
  modules/storages/config/locales/js-en.yml
Labels: bugfix

#12155 [46149] Notification authors overlap next line
  frontend/src/app/features/in-app-notifications/entry/actors-line/in-app-notification-actors-line.component.html
  frontend/src/app/features/in-app-notifications/entry/actors-line/in-app-notification-actors-line.component.sass
Labels: bugfix

#12172 [42287] Current rate of cost type increased by a factor of 10 when saving cost type with German language settings
  modules/costs/app/views/cost_types/_rate.html.erb
Labels: bugfix

#12110 [44907] Impossible to delete the Estimated time entry
  frontend/src/app/shared/components/fields/edit/field-types/hours-duration-edit-field.component.ts
Labels: bugfix

#12175 Make created at filter available for all users
  app/models/queries/projects/filters/created_at_filter.rb
  spec/models/queries/projects/filters/created_at_filter_spec.rb
Labels: bugfix

#12178 [46454] Date picker (work package) - anomalies on hover when there's only a start date
  frontend/src/global_styles/content/_datepicker.sass
Labels: bugfix

#12167 Allow state to be redirected to in notifications center
  app/controllers/angular_controller.rb
  spec/features/notifications/notification_center/notification_center_spec.rb
Labels: bugfix

#12176 Keep minimumDate for scheduling when reinitializing datepicker
  frontend/src/app/shared/components/datepicker/helpers/date-modal.helpers.ts
  frontend/src/app/shared/components/datepicker/wp-multi-date-form/wp-multi-date-form.component.ts
  spec/features/work_packages/datepicker/datepicker_follows_relation_spec.rb
Labels: bugfix
