Repository opf/openproject, pull requests merged in 2024-02, with the labels that each got.

#14686 Hide milestone gantt query if no milestones exist in project
  modules/gantt/app/controllers/gantt/menus_controller.rb
  modules/gantt/app/services/gantt/default_query_generator_service.rb
Labels: feature, needs review

#14680 [52252] Exclude derived_remaining_time from work package form
  app/models/type/attributes.rb
  spec/features/work_packages/share/access_spec.rb
Labels: needs review

#14691 [52129] Remove feature flag for Gantt module
  app/models/queries/views/filters/type_filter.rb
  app/services/queries/update_service.rb
  config/initializers/menus.rb
  frontend/src/app/features/work-packages/components/wp-buttons/wp-view-toggle-button/work-package-view-toggle-button.component.ts
  frontend/src/app/features/work-packages/components/wp-list/wp-query-view.service.ts
  frontend/src/app/features/work-packages/components/wp-table/configuration-modal/wp-table-configuration.modal.ts
  frontend/src/app/features/work-packages/components/wp-table/configuration-modal/wp-table-configuration.service.ts
  frontend/src/app/features/work-packages/components/wp-table/external-configuration/restricted-wp-table-configuration.service.ts
  frontend/src/app/features/work-packages/openproject-work-packages.module.ts
  frontend/src/app/features/work-packages/routing/wp-view-page/wp-view-page.component.ts
  frontend/src/app/shared/components/op-view-select/op-static-queries.service.ts
  modules/bim/spec/seeders/root_seeder_bim_edition_spec.rb
  modules/boards/spec/features/onboarding/boards_onboarding_tour_spec.rb
  modules/gantt/lib/open_project/gantt/engine.rb
  modules/gantt/spec/features/timeline/timeline_dates_spec.rb
  modules/gantt/spec/features/timeline/timeline_hierarchy_spec.rb
  modules/gantt/spec/features/timeline/timeline_labels_spec.rb
  modules/gantt/spec/features/timeline/timeline_navigation_spec.rb
  modules/team_planner/spec/features/onboarding/team_planner_onboarding_tour_spec.rb
  spec/features/onboarding/onboarding_tour_spec.rb
  spec/features/work_packages/sorting/manual_sorting_spec.rb
  spec/features/work_packages/table/context_menu/context_menu_spec.rb
  spec/models/queries/views/filters/type_filter_spec.rb
  spec/requests/api/v3/queries/query_resource_spec.rb
  spec/requests/api/v3/queries/update_query_spec.rb
  spec/seeders/root_seeder_standard_edition_spec.rb
  spec/services/queries/update_service_spec.rb
Labels: feature, needs review

#14693 [51246] Add the gantt module to all newly created projects
  config/constants/settings/definition.rb
  db/migrate/20240201115019_add_gantt_module_to_default_modules.rb
Labels: feature, needs review

#14695 Disable the option to turn off the Gantt chart in the Gantt module
  frontend/src/app/features/work-packages/components/wp-table/configuration-modal/tabs/timelines-tab.component.html
  frontend/src/app/features/work-packages/components/wp-table/configuration-modal/tabs/timelines-tab.component.ts
Labels: bugfix, needs review

#14699 Use translation key instead of fixed string
  modules/gantt/app/services/gantt/default_query_generator_service.rb
Labels: bugfix, needs review

#14704 Add FAQ on time and costs
  docs/user-guide/time-and-costs/time-and-costs-faq/README.md
Labels: documentation

#14712 [51619] Meetings: Title of linked work packages are truncated too early
  modules/meeting/app/components/meeting_agenda_items/item_component/show_component.sass
Labels: bugfix

#14716 [52012] Remove colour in share modal is not correct
  app/components/work_packages/share/share_row_component.html.erb
Labels: bugfix

#14690 [51354] Adapt onboardoing tour to new Gantt module
  app/views/onboarding/_configuration_modal.html.erb
  config/locales/js-en.yml
  frontend/src/app/core/setup/globals/onboarding/helpers.ts
  frontend/src/app/core/setup/globals/onboarding/onboarding_tour.ts
  frontend/src/app/core/setup/globals/onboarding/onboarding_tour_trigger.ts
  frontend/src/app/core/setup/globals/onboarding/tours/boards_tour.ts
  frontend/src/app/core/setup/globals/onboarding/tours/gantt_tour.ts
  frontend/src/app/core/setup/globals/onboarding/tours/team_planners_tour.ts
  frontend/src/app/core/setup/globals/onboarding/tours/work_package_tour.ts
  frontend/src/app/features/boards/board/board-list/board-list.component.html
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.html
  frontend/src/app/features/work-packages/components/wp-card-view/wp-single-card/wp-single-card.component.html
  lib/redmine/menu_manager/menu_helper.rb
  modules/boards/spec/features/onboarding/boards_onboarding_tour_spec.rb
  modules/team_planner/spec/features/onboarding/team_planner_onboarding_tour_spec.rb
  spec/features/onboarding/onboarding_tour_spec.rb
  spec/lib/redmine/menu_manager/menu_helper_spec.rb
  spec/support/onboarding_helper.rb
Labels: feature, needs review

#14677 Mark development environment
  app/assets/images/development/apple-touch-icon-120x120.png
  app/assets/images/development/favicon.ico
  app/views/common/_favicons.html.erb
  app/views/layouts/base.html.erb
  app/views/layouts/only_logo.html.erb
  config/constants/settings/definition.rb
  docs/development/README.md
  frontend/src/global_styles/common/header/app-header.sass
  lib/open_project/custom_styles/design.rb
  spec/views/layouts/base.html.erb_spec.rb
Labels: needs review

#14726 Housekeeping: amend user invitation case for members controller
  spec/controllers/members_controller_spec.rb
Labels: maintenance, needs review

#14069 Update users using their LDAP attributes when logging in
  app/controllers/account_controller.rb
  app/controllers/concerns/auth_source_sso.rb
  app/models/ldap_auth_source.rb
  app/services/ldap/base_service.rb
  app/services/ldap/import_users_from_filter_service.rb
  app/services/ldap/post_login_sync_service.rb
  app/services/users/login_service.rb
  config/locales/en.yml
  modules/ldap_groups/app/services/ldap_groups/synchronize_groups_service.rb
  modules/ldap_groups/lib/tasks/ldap_groups.rake
  spec/controllers/account_controller_spec.rb
  spec/controllers/concerns/auth_source_sso_spec.rb
  spec/features/auth/auth_source_sso_logout_spec.rb
  spec/models/ldap_auth_source_spec.rb
  spec/requests/auth/auth_source_sso_spec.rb
  spec/services/ldap/post_login_sync_service_spec.rb
  spec/support/shared/with_test_ldap.rb
Labels: feature

#14718 [#52119] Make renamed progress attributes searchable with old names
  config/locales/js-en.yml
  frontend/src/app/features/work-packages/components/filters/query-filters/query-filters.component.html
  frontend/src/app/features/work-packages/components/filters/query-filters/query-filters.component.ts
  frontend/src/app/shared/components/autocompleter/draggable-autocomplete/draggable-autocomplete.component.html
  frontend/src/app/shared/components/autocompleter/draggable-autocomplete/draggable-autocomplete.component.ts
  frontend/src/app/shared/components/work-packages/alternative-search.service.ts
  spec/features/a11y/work_packages/alternative_name_autcompleting_spec.rb
  spec/support/components/work_packages/columns.rb
  spec/support/components/work_packages/filters.rb
Labels: feature, needs review

#14673 [50866] Old story points seem to be saved but not shown in GUI (after deactivation and reactivation of the Story type in Backlogs) and it's impossible to enter the old value again
  lib/api/v3/work_packages/schema/work_package_schema_representer.rb
Labels: needs review

#14655 [#49396] Nudge admin to go through OAuth flow
  app/controllers/oauth_clients_controller.rb
  app/helpers/flash_messages_helper.rb
  app/services/oauth_clients/connection_manager.rb
  frontend/src/stimulus/controllers/dynamic/storages/oauth-access-grant-nudge-modal.controller.ts
  modules/storages/app/components/storages/admin/oauth_access_grant_nudge_modal_component.html.erb
  modules/storages/app/components/storages/admin/oauth_access_grant_nudge_modal_component.rb
  modules/storages/app/components/storages/open_project_storage_modal_component/body.html.erb
  modules/storages/app/components/storages/open_project_storage_modal_component/body.rb
  modules/storages/app/controllers/storages/admin/project_storages_controller.rb
  modules/storages/config/locales/en.yml
  modules/storages/config/routes.rb
  modules/storages/lib/open_project/storages/engine.rb
  modules/storages/spec/components/storages/admin/oauth_access_grant_nudge_modal_component_spec.rb
  modules/storages/spec/features/storages/project_settings/oauth_access_grant_spec.rb
  spec/services/oauth_clients/connection_manager_spec.rb
Labels: feature, needs review

#14732 Show error if gantt module enabled as default without work packages
  app/controllers/admin/settings/projects_settings_controller.rb
  config/locales/en.yml
Labels: bugfix, needs review

#14736 [52149] Clean menu structure on project lists page (change order of entries, use correct icons)
  app/components/projects/index_page_header_component.html.erb
  app/components/projects/index_page_header_component.rb
  config/locales/en.yml
Labels: needs review

#14734 Revert to display: flex, but fix outer container
  frontend/src/app/shared/components/fields/display/field-types/multiple-user-display-field.module.ts
  frontend/src/global_styles/content/_principal-list.sass
Labels: bugfix, styling

#14725 Get rid of type enums
  db/migrate/20240206085104_remove_enums.rb
  modules/storages/app/models/storages/project_storage.rb
  modules/storages/app/models/storages/storage.rb
  modules/storages/spec/models/storages/last_project_folder_spec.rb
  modules/storages/spec/models/storages/project_storage_spec.rb
Labels: needs review

#14745 Remove public permission adding when checking in Role
  app/models/role.rb
  spec/models/users/allowed_to_spec.rb
Labels: needs review

#14747 Bug/52676 Do not render oauth access grant modal when the project storage no longer exists
  app/controllers/oauth_clients_controller.rb
  modules/storages/app/components/storages/admin/oauth_access_grant_nudge_modal_component.rb
  modules/storages/spec/components/storages/admin/oauth_access_grant_nudge_modal_component_spec.rb
Labels: bugfix

#14740 Add draft for release notes 13.3.0
  docs/release-notes/13-3-0/README.md
  docs/release-notes/13-3-0/openproject-13-3-sharepoint-onedrive-automatically-managed-project-folders-highlighted.png
  docs/release-notes/13-3-0/openproject-filter-project-lists.png
  docs/release-notes/13-3-0/openproject-user-guide-select-gantt-charts-global.png
Labels: documentation

#14758 update release teaser for 13.3
  config/locales/js-en.yml
  frontend/src/app/features/homescreen/blocks/new-features.component.ts
  frontend/src/assets/images/13_2_features.svg
  frontend/src/assets/images/13_3_features.svg
Labels: needs review

#14674 Unset moment.js locale in timezone service
  frontend/src/app/core/datetime/timezone.service.ts
  frontend/src/app/core/setup/init-locale.ts
  frontend/src/app/core/setup/init-vendors.ts
  spec/features/work_packages/datepicker/datepicker_logic_spec.rb
  spec/support/edit_fields/date_edit_field.rb
Labels: needs review

#14767 [52754] Search result list is too long
  frontend/src/app/core/global_search/input/global-search-input.component.html
Labels: bugfix

#14762 [#52551] 13.3 Documentation: Update SharePoint/OneDrive documentation…
  docs/system-admin-guide/integrations/one-drive/README.md
  docs/system-admin-guide/integrations/one-drive/openproject_system_guide_new_onedrive_storage_details_new.png
  docs/user-guide/file-management/README.md
  docs/user-guide/file-management/file-management-faq/README.md
  docs/user-guide/file-management/one-drive-integration/README.md
  docs/user-guide/projects/project-settings/file-storages/README.md
  docs/user-guide/projects/project-settings/file-storages/onedrive-storage-add-folders-new.png
Labels: documentation

#14760 [#52552] 13.3 Documentation: Improved calculations and updates for pr…
  docs/user-guide/time-and-costs/progress-tracking/README.md
  docs/user-guide/time-and-costs/progress-tracking/progress-tracking-bulk-editing.png
  docs/user-guide/time-and-costs/progress-tracking/progress-tracking-hierarchy-progress.png
  docs/user-guide/time-and-costs/progress-tracking/progress-tracking-two-progress-values.png
  docs/user-guide/time-and-costs/progress-tracking/progress-tracking-wp-field-50perc.png
  docs/user-guide/time-and-costs/progress-tracking/progress-tracking-wp-field-editor.png
  docs/user-guide/time-and-costs/progress-tracking/progress-tracking-wp-field.png
Labels: documentation

#14765 Prevent error toasts from showing when HTTP status is 0
  frontend/src/app/shared/components/copy-to-clipboard/copy-to-clipboard.service.ts
  frontend/src/app/shared/components/toaster/toast.service.ts
Labels: bugfix, needs review

#14755 [32764] Gantt chart fixes
  config/locales/en.yml
  modules/gantt/app/controllers/gantt/menus_controller.rb
  modules/gantt/app/services/gantt/default_query_generator_service.rb
  modules/gantt/config/locales/en.yml
  modules/gantt/spec/features/menu/global_gantt_menu_spec.rb
Labels: bugfix, needs review

#14780 Documentation link checker
  .github/workflows/docs.yaml
  script/docs/check_links
Labels: documentation

#14790 Progress reporting docs update
  docs/user-guide/time-and-costs/progress-tracking/README.md
Labels: documentation

#14683 Update Primer to version 0.22.2
  Gemfile
  Gemfile.lock
  app/views/augmented/_autocomplete_select_decoration.html.erb
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/shared/components/autocompleter/autocomplete-select-decoration/autocomplete-select-decoration.component.ts
  frontend/src/app/shared/components/autocompleter/op-autocompleter/op-autocompleter.component.ts
  frontend/src/stimulus/controllers/dynamic/storages/oauth-access-grant-nudge-modal.controller.ts
  frontend/src/stimulus/controllers/dynamic/storages/open-project-storage-modal.controller.ts
  lib/primer/open_project/forms/autocompleter.html.erb
  modules/meeting/app/components/work_package_meetings_tab/add_work_package_to_meeting_form_component.html.erb
  modules/meeting/app/forms/meeting_agenda_item/meeting_form.rb
Labels: maintenance, needs review

#14804 Changing Project lists documentation
  docs/faq/README.md
  docs/getting-started/projects/README.md
  docs/getting-started/projects/view_all_projects.png
  docs/system-admin-guide/custom-fields/custom-fields-projects/README.md
  docs/system-admin-guide/system-settings/project-system-settings/README.md
  docs/user-guide/calendar/calendar-faq/README.md
  docs/user-guide/gantt-chart/README.md
  docs/user-guide/home/README.md
  docs/user-guide/home/global-modules/README.md
  docs/user-guide/projects/README.md
  docs/user-guide/projects/project-lists/Filter-projects-list.png
  docs/user-guide/projects/project-lists/Name-private-projects-filter.png
  docs/user-guide/projects/project-lists/Project-list-button.png
  docs/user-guide/projects/project-lists/README.md
  docs/user-guide/projects/project-lists/activity-global-menu.png
  docs/user-guide/projects/project-lists/actvity-global-filter.png
  docs/user-guide/projects/project-lists/arrow-project-description.png
  docs/user-guide/projects/project-lists/configure-project-list.png
  docs/user-guide/projects/project-lists/display-all-workpackages.png
  docs/user-guide/projects/project-lists/export-project-list-formats.png
  docs/user-guide/projects/project-lists/export-projects.png
  docs/user-guide/projects/project-lists/navigation-bar-modules-3923134.png
  docs/user-guide/projects/project-lists/navigation-bar-modules.png
  docs/user-guide/projects/project-lists/new-subproject-project-list.png
  docs/user-guide/projects/project-lists/overall-activity-button-3922893.png
  docs/user-guide/projects/project-lists/overall-activity-link.png
  docs/user-guide/projects/project-lists/overall-activity-meeting-filter.png
  docs/user-guide/projects/project-lists/private-project-filter-delete.png
  docs/user-guide/projects/project-lists/private-project-filter-saved.png
  docs/user-guide/projects/project-lists/project-overarching-report.gif
  docs/user-guide/projects/project-lists/projects-list.png
  docs/user-guide/projects/project-lists/projects-lists-default-filters.png
  docs/user-guide/projects/project-lists/save-button-filtered-view.png
  docs/user-guide/projects/project-lists/view_all_projects_options.png
  docs/user-guide/projects/project-settings/project-information/README.md
  docs/user-guide/projects/project-status/README.md
  docs/user-guide/projects/projects-faq/README.md
  docs/user-guide/projects/projects-lists/Projects-list-button.png
  docs/user-guide/search/README.md
  docs/user-guide/work-packages/work-package-table-configuration/README.md
  docs/user-guide/work-packages/work-packages-faq/README.md
Labels: documentation

#14795 Update Glossary
  docs/glossary/README.md
Labels: documentation

#14805 [52758] Queries are not highlighted in the menu
  frontend/src/app/features/boards/boards-sidebar/boards-menu.component.ts
  frontend/src/app/shared/components/op-view-select/op-static-queries.service.ts
  frontend/src/app/shared/components/op-view-select/op-view-select.component.ts
Labels: bugfix

#14810 [52834] sharing roles can be selected for groups: trigger an error
  app/models/role.rb
Labels: bugfix

#14808 [52765] When multi select user custom fields are truncated, the associated tooltip contains incorrect data
  frontend/src/app/shared/components/fields/display/display-field-renderer.ts
Labels: bugfix

#14788 Fix seeding on BIM edition
  app/seeders/demo_data/global_query_seeder.rb
  app/seeders/development_data/shared_work_packages_seeder.rb
  app/seeders/source/seed_data.rb
  app/seeders/standard.yml
  modules/bim/app/seeders/bim.yml
  modules/bim/spec/seeders/root_seeder_bim_edition_spec.rb
  spec/seeders/source/seed_data_spec.rb
Labels: bugfix, needs review

#14813 [52826] Onboarding tour displays permission error
  app/services/projects/archive_service.rb
  app/services/projects/concerns/update_demo_data.rb
  app/services/projects/delete_service.rb
  app/services/projects/unarchive_service.rb
  app/services/projects/update_service.rb
  spec/features/onboarding/onboarding_tour_spec.rb
  spec/services/projects/archive_service_spec.rb
  spec/services/projects/delete_service_spec.rb
  spec/services/projects/unarchive_service_spec.rb
  spec/services/projects/update_service_integration_spec.rb
Labels: bugfix

#14817 Bump lookbook version and fix broken previews
  Gemfile
  Gemfile.lock
  lib/open_project/patches/lookbook_tree_node_inflector.rb
  lookbook/docs/patterns/modals.md.erb
  lookbook/previews/open_project/common/submenu_component_preview.rb
Labels: maintenance

#14779 [#52287] Consent always shown in Browser language despite user's language being set differently
  app/controllers/application_controller.rb
  app/controllers/concerns/accounts/authentication_stages.rb
  app/controllers/concerns/accounts/user_consent.rb
  app/helpers/user_consent_helper.rb
  app/models/user.rb
  app/services/set_localization_service.rb
  app/views/account/_register.html.erb
  app/views/account/_user_consent_check.html.erb
  app/views/account/consent.html.erb
  spec/controllers/members_controller_spec.rb
  spec/features/auth/consent_auth_stage_spec.rb
  spec/support/authentication_helpers.rb
  spec/views/account/register.html.erb_spec.rb
Labels: needs review

#14806 [52671] Collapse the sidebar earlier
  app/views/layouts/base.html.erb
  frontend/src/app/core/browser/device.service.ts
  frontend/src/app/core/main-menu/main-menu-toggle.component.ts
  frontend/src/app/core/main-menu/main-menu-toggle.service.ts
  frontend/src/global_styles/layout/_main_menu_mobile.sass
Labels: bugfix

#14832 chore(docs): fix link
  docs/glossary/README.md
Labels: documentation

#14833 chore(docs): fix link to moved cloud hosting content
  docs/development/concepts/infrastructure/README.md
  docs/faq/README.md
  docs/getting-started/openproject-introduction/README.md
  docs/installation-and-operations/README.md
  docs/installation-and-operations/installation-faq/README.md
  docs/release-notes/7/7-0-0/README.md
  docs/release-notes/7/7-1-0/README.md
  docs/release-notes/7/7-4-0/README.md
  docs/release-notes/8/8-1-0/README.md
  docs/release-notes/8/8-2-0/README.md
  docs/system-admin-guide/custom-fields/custom-fields-projects/README.md
  docs/system-admin-guide/manage-work-packages/custom-actions/README.md
  docs/system-admin-guide/manage-work-packages/work-package-types/README.md
  docs/system-admin-guide/users-permissions/placeholder-users/README.md
  docs/user-guide/work-packages/work-package-relations-hierarchies/README.md
Labels: documentation

#14835 fix(docs): apply filename conventions, remove unused images
  docs/user-guide/meetings/classic-meetings/1567430908286.png
  docs/user-guide/meetings/classic-meetings/1567598397931.png
  docs/user-guide/meetings/classic-meetings/1567598762132.png
  docs/user-guide/meetings/classic-meetings/1567599156831.png
  docs/user-guide/meetings/classic-meetings/README.md
  docs/user-guide/meetings/classic-meetings/download-a-meeting.png
  docs/user-guide/meetings/classic-meetings/image-20210429105532164.png
  docs/user-guide/meetings/classic-meetings/image-20210429111019470.png
  docs/user-guide/meetings/classic-meetings/send-email-to-participants.png
Labels: documentation

#14834 Add attendees to ICS file in meetings
  modules/meeting/app/services/meetings/ical_service.rb
  modules/meeting/spec/services/meetings/ical_service_spec.rb
Labels: feature

#14840 Run `rubocop -a` on all files
  Gemfile
  app/components/admin/quarantined_attachments/row_component.rb
  app/components/members/row_component.rb
  app/components/projects/projects_filters_component.rb
  app/controllers/admin/settings/projects_settings_controller.rb
  app/controllers/admin/settings/virus_scanning_settings_controller.rb
  app/models/user.rb
  app/services/projects/update_service.rb
  config/constants/settings/definition.rb
  config/routes.rb
  db/migrate/20240131130134_fix_inherited_group_memberships.rb
  lib/api/helpers/attachment_renderer.rb
  lib/api/v3/work_packages/schema/work_package_schema_representer.rb
  modules/bim/db/migrate/20211011204301_add_column_conversion_status_to_ifc_model.rb
  modules/bim/spec/features/display_representations/switch_display_representations_spec.rb
  modules/boards/spec/features/support/board_page.rb
  modules/gantt/app/controllers/gantt/menus_controller.rb
  modules/gantt/app/services/gantt/default_query_generator_service.rb
  modules/ldap_groups/lib/tasks/ldap_groups.rake
  spec/features/admin/attachments/quarantined_attachments_spec.rb
  spec/features/custom_fields/multi_user_custom_field_spec.rb
  spec/features/projects/modules_spec.rb
  spec/features/projects/projects_index_spec.rb
  spec/features/work_packages/display_representations/switch_display_representations_on_mobile_spec.rb
  spec/features/work_packages/edit_on_change_work_package_status_permission_spec.rb
  spec/features/work_packages/share/share_spec.rb
  spec/features/work_packages/sorting/manual_sorting_spec.rb
  spec/requests/admin/attachments/quarantined_attachments_spec.rb
  spec/requests/admin/attachments/virus_scanning_settings_spec.rb
  spec/requests/oauth_clients/ensure_connection_flow_spec.rb
  spec/services/work_packages/create_service_integration_spec.rb
  spec/support/pages/members.rb
Labels: maintenance

#14856 [52920] Wrapping of URLs in lists in dynamic meetings
  frontend/src/global_styles/content/user-content/_list.sass
Labels: bugfix, DO NOT MERGE, needs review

#14859 [52519] Dynamics meetings: improve readability of agenda items (quote vs. normal text)
  modules/meeting/app/components/meeting_agenda_items/item_component/show_component.html.erb
Labels: bugfix, DO NOT MERGE

#14867 Use separate high contrast logo
  app/models/user_preference.rb
  app/views/custom_styles/_inline_css_logo.erb
  lib/redmine/menu_manager/top_menu_helper.rb
Labels: bugfix, styling

#14870 [#53040] fixed UI texts in storage view
  modules/storages/app/components/storages/admin/oauth_application_info_component.html.erb
  modules/storages/app/components/storages/admin/oauth_client_info_component.rb
  modules/storages/config/locales/en.yml
  modules/storages/spec/components/storages/admin/oauth_client_info_component_spec.rb
Labels: pullpreview

#14861 Copy meeting agenda items
  modules/meeting/app/controllers/meetings_controller.rb
  modules/meeting/app/models/meeting_agenda_item.rb
  modules/meeting/app/models/structured_meeting.rb
  modules/meeting/app/views/meetings/_form.html.erb
  modules/meeting/app/views/meetings/new.html.erb
  modules/meeting/config/locales/en.yml
  modules/meeting/spec/features/meetings_copy_spec.rb
  modules/meeting/spec/features/structured_meetings/structured_meeting_crud_spec.rb
  modules/meeting/spec/requests/meetings_spec.rb
Labels: feature

#14860 When copying, update links to images in wiki pages and work packages
  app/services/copy/concerns/copy_attachments.rb
  app/services/wiki_pages/copy_service.rb
  app/services/work_packages/copy_service.rb
  spec/services/wiki_pages/copy_service_integration_spec.rb
  spec/services/work_packages/copy_service_integration_spec.rb
Labels: bugfix

#14792 [Op#52605]: Add Loading state to Project Storage OAuth Grant Access nudge modal
  frontend/src/stimulus/controllers/dynamic/storages/oauth-access-grant-nudge-modal.controller.ts
  lookbook/previews/storages/admin/oauth_access_grant_nudge_modal_component_preview.rb
  lookbook/previews/storages/admin/oauth_access_grant_nudge_modal_component_preview/default.html.erb
  modules/storages/app/components/storages/admin/oauth_access_grant_nudge_modal_component.html.erb
  modules/storages/app/components/storages/admin/oauth_access_grant_nudge_modal_component.rb
  modules/storages/app/components/storages/open_project_storage_modal_component/body.html.erb
  modules/storages/app/components/storages/open_project_storage_modal_component/body.rb
  modules/storages/app/controllers/storages/admin/project_storages_controller.rb
  modules/storages/config/locales/en.yml
  modules/storages/spec/components/storages/admin/oauth_access_grant_nudge_modal_component_spec.rb
  modules/storages/spec/features/storages/project_settings/oauth_access_grant_spec.rb
  modules/storages/spec/requests/storages/project_settings/oauth_access_grant_flow_spec.rb
Labels: feature, needs review

#14888 feat(docs): move fair-language from website repo into docs
  docs/development/translate-openproject/fair-language/README.md
Labels: documentation

#14838 [52127] project list truncate long text fields and disable expand action
  app/components/_index.sass
  app/components/open_project/common/attribute_component.html.erb
  app/components/open_project/common/attribute_component.rb
  app/components/open_project/common/attribute_component.sass
  app/components/projects/row_component.html.erb
  app/components/projects/row_component.rb
  app/components/projects/table_component.html.erb
  app/components/projects/table_component.rb
  app/views/projects/index.html.erb
  config/locales/en.yml
  config/locales/js-en.yml
  frontend/src/global_styles/content/_projects_list.sass
  frontend/src/stimulus/controllers/dynamic/attribute.controller.ts
  frontend/src/stimulus/controllers/dynamic/project.controller.ts
  lookbook/previews/open_project/common/attribute_component_preview.rb
  spec/features/projects/projects_index_spec.rb
Labels: pullpreview
