Repository opf/openproject, pull requests merged in 2024-09, with the labels that each got.

#16537 Expands logging to CopyFileLinksService
  modules/storages/app/common/storages/peripherals/storage_interaction/nextcloud/files_info_query.rb
  modules/storages/app/common/storages/peripherals/storage_interaction/one_drive/files_info_query.rb
  modules/storages/app/services/storages/file_links/copy_file_links_service.rb
  modules/storages/spec/services/storages/file_links/copy_file_links_service_spec.rb
Labels: needs review

#16577 Documentation/fixes
  docs/api/apiv3/example/README.md
  docs/getting-started/my-account/openproject_my_account_page_new.png
  docs/system-admin-guide/files/external-file-storages/health-status/openproject_file_storages_health_message_nextcloud.png
  docs/system-admin-guide/information/Sys-admin-information.png
  docs/system-admin-guide/information/image-20200124104411677.png
  docs/system-admin-guide/information/image-20200124104803476.png
  docs/system-admin-guide/manage-work-packages/work-package-workflows/Sys-admin-copy-workflow.png
  docs/system-admin-guide/manage-work-packages/work-package-workflows/Sys-admin-workflow-summary.png
  docs/system-admin-guide/users-permissions/placeholder-users/system-guide-ph-user-edit-project-role.png
  docs/user-guide/agile-boards/this-is-a-kanban-board.png
  docs/user-guide/home/openproject_user_guide_home_page.png
  docs/user-guide/projects/project-lists/public-project-lists.png
  docs/user-guide/work-packages/edit-work-package/edit-work-package-1566546727784.png
Labels: documentation

#16583 Fix some test flakiness
  spec/migrations/rename_visible_to_admin_only_in_custom_fields_spec.rb
Labels: flaky-spec

#16557 Show progressBar instead of intermediate loading dialog
  frontend/.eslintrc.js
  frontend/src/app/shared/components/datepicker/modal-single-date-picker/modal-single-date-picker.component.ts
  frontend/src/stimulus/controllers/async-dialog.controller.ts
  frontend/src/turbo/helpers.ts
  frontend/src/typings/shims.d.ts
  lookbook/docs/patterns/05-dialogs.md.erb
  spec/support/components/datepicker/datepicker_modal.rb
Labels: maintenance, needs review

#16574 Navigate with query parameters kept in split view
  app/components/work_packages/details/tab_component.html.erb
  app/controllers/notifications_controller.rb
  app/helpers/url_helper.rb
  spec/features/notifications/navigation_spec.rb
Labels: bugfix, needs review

#16578 Provide better error when no projects are visible
  app/controllers/activities_controller.rb
  spec/controllers/activities_controller_spec.rb
Labels: bugfix

#16575 Bug/34971 Fix query_id is missing for export CSV/PDF lead manual sorting lost.
  app/components/work_packages/exports/modal_dialog_component.rb
  frontend/src/app/features/work-packages/components/wp-query/url-params-helper.ts
  frontend/src/app/shared/components/op-context-menu/handlers/op-settings-dropdown-menu.directive.ts
Labels: bugfix, contribution, needs review

#16573 [57527] Switching between work packages in the notification center resets the split screen width
  frontend/src/app/shared/components/resizer/resizer/wp-resizer.component.ts
Labels: bugfix, styling

#16598 Bump primer to 0.43.1
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: maintenance

#16582 [57003] OpenProject Dark Mode: selection colour of table rows
  frontend/src/app/features/in-app-notifications/entry/in-app-notification-entry.component.sass
  frontend/src/global_styles/content/_tables.sass
  frontend/src/global_styles/layout/work_packages/_table.sass
  frontend/src/global_styles/layout/work_packages/_table_embedded.sass
Labels: bugfix, needs review

#16579 [57395] Color gradient gone in gantt charts for work packages with only start or due date
  frontend/src/app/features/work-packages/components/wp-table/timeline/cells/timeline-cell-renderer.ts
Labels: bugfix, styling

#16593 Bug/57612 work package report export fails if work package has unavailable attachments
  app/models/work_package/pdf_export/markdown.rb
  spec/models/work_packages/pdf_export/work_package_to_pdf_spec.rb
Labels: bugfix, needs review

#16597 [57620] New mobile split screen scrolls horizontally
  app/components/work_packages/split_view_component.sass
  frontend/src/global_styles/layout/_base_mobile.sass
Labels: bugfix, styling

#16602 [#57591] 14.5 Documentation: Administration for workflows: Uncheck bo…
  docs/system-admin-guide/manage-work-packages/work-package-workflows/README.md
  docs/system-admin-guide/manage-work-packages/work-package-workflows/System-admin-guide-work-package-workflows.png
Labels: documentation

#16594 Bug/57345 icons and spacing wrong on work package configuration view
  frontend/src/app/features/work-packages/components/wp-table/configuration-modal/tabs/display-settings-tab.component.html
  frontend/src/app/shared/components/icon/icon.module.ts
  frontend/src/global_styles/content/work_packages/_table_configuration_modal.sass
Labels: bugfix

#16603 [51545] Add to meeting button is chopped of in the work package meetings tab
  modules/meeting/app/components/work_package_meetings_tab/heading_component.html.erb
Labels: bugfix, styling

#16590 Add spacing between title and icons for auth providers
  app/views/account/_auth_providers.html.erb
  app/views/account/_register.html.erb
Labels: bugfix

#16604 [#57608] Removal dialog shows storage type instead of storage name
  modules/storages/app/components/storages/project_storages/destroy_confirmation_dialog_component.rb
  modules/storages/config/locales/en.yml
  modules/storages/spec/components/storages/project_storages/destroy_confirmation_dialog_component_spec.rb
  modules/storages/spec/features/storages/admin/project_storages_spec.rb
Labels: bugfix, needs review

#16586 Bug/57599 Clicking on project list links does not render full project detail unless refreshed
  app/components/projects/row_component.rb
  app/components/settings/project_custom_fields/project_custom_field_mapping/table_component.html.erb
  modules/storages/app/components/storages/project_storages/projects/table_component.html.erb
  spec/components/projects/row_component_spec.rb
Labels: bugfix

#16606 [#57611] Deletion success banner is blue instead of green
  modules/storages/app/controllers/storages/admin/storages/project_storages_controller.rb
Labels: bugfix, needs review

#16591 Rework the Nextcloud AMPF Sync test suite
  modules/storages/app/common/storages/peripherals/storage_parent_folder_extractor.rb
  modules/storages/app/services/storages/nextcloud_managed_folder_sync_service.rb
  modules/storages/app/workers/storages/automatically_managed_storage_sync_job.rb
  modules/storages/lib/open_project/storages/engine.rb
  modules/storages/spec/services/storages/nextcloud_group_folder_properties_sync_service_spec.rb
  modules/storages/spec/services/storages/nextcloud_managed_folder_sync_service_spec.rb
  modules/storages/spec/workers/storages/automatically_managed_storage_sync_job_spec.rb
Labels: maintenance

#16610 RakeJob: Load the rake task if it wasn't found
  app/workers/rake_job.rb
Labels: bugfix, operations

#16622 Fix flaky move_work_package_spec.rb spec
  spec/features/work_packages/bulk/move_work_package_spec.rb
Labels: flaky-spec

#16623 [57646] Action menu item list is misaligned in 2FA page
  modules/two_factor_authentication/app/views/two_factor_authentication/my/two_factor_devices/index.html.erb
Labels: bugfix, needs review

#16621 Fix: Work packages export modal & CSV-Export: description column optional
  app/components/work_packages/exports/csv/export_settings_component.html.erb
  app/components/work_packages/exports/xls/export_settings_component.html.erb
  app/models/work_package/exports/csv.rb
  spec/features/work_packages/export_spec.rb
  spec/models/work_package/exporter/csv_integration_spec.rb
Labels: bugfix

#16607 Bump gems
  Gemfile
  Gemfile.lock
Labels: maintenance, dependencies

#16619 [#57536] Remove menu entry in Administration submenu
  app/helpers/settings_helper.rb
Labels: feature, needs review

#16624 Fix: Stop Job Status Modal navigating back after redirect clicked
  frontend/src/stimulus/controllers/dynamic/job-status-polling.controller.ts
  modules/job_status/app/components/job_status/dialog/body_component.html.erb
  modules/job_status/spec/features/job_status_spec.rb
Labels: bugfix

#16584 [57414] Non-working days are not correctly highlighted in the Gantt chart
  frontend/src/global_styles/content/work_packages/timelines/_grid.sass
Labels: bugfix, styling, needs review

#16608 [57346][57610] Scrolling issues with UnderlineNav in the new split screen
  app/components/work_packages/details/tab_component.html.erb
  app/components/work_packages/details/tab_component.sass
  config/locales/en.yml
  frontend/src/global_styles/primer/_overrides.sass
  frontend/src/stimulus/controllers/dynamic/work-packages/details/tabs.controller.ts
Labels: bugfix, pullpreview

#16629 fix github rate limit issue in deploy targets feature
  modules/github_integration/app/workers/cron/check_deploy_status_job.rb
  modules/github_integration/spec/workers/cron/check_deploy_status_job_spec.rb
Labels: bugfix

#16630 Ignore FileLink renames when rendering activities
  lib/open_project/journal_formatter/file_link.rb
  spec/lib/journal_formatter/file_link_spec.rb
Labels: needs review

#16636 [#57590] 14.5 Documentation: Store revisions of WYSIWYG content in lo…
  docs/user-guide/wiki/create-edit-wiki/1568198706474.png
  docs/user-guide/wiki/create-edit-wiki/1568209633619.png
  docs/user-guide/wiki/create-edit-wiki/1568209656591.png
  docs/user-guide/wiki/create-edit-wiki/1568210445539.png
  docs/user-guide/wiki/create-edit-wiki/README.md
  docs/user-guide/wiki/create-edit-wiki/create-wiki-1568199670933.png
  docs/user-guide/wiki/create-edit-wiki/edit-wiki-page.png
  docs/user-guide/wiki/create-edit-wiki/openproject_user_guide_create_wiki_page_button.png
  docs/user-guide/wiki/create-edit-wiki/openproject_user_guide_create_wiki_page_form.png
  docs/user-guide/wiki/create-edit-wiki/openproject_user_guide_edit_wiki_page_button.png
  docs/user-guide/wiki/create-edit-wiki/openproject_user_guide_watch_wiki_page_button.png
  docs/user-guide/wiki/create-edit-wiki/openproject_user_guide_wiki_autosave_icon.png
  docs/user-guide/wiki/create-edit-wiki/openproject_user_guide_wiki_child_page_example.png
  docs/user-guide/wiki/create-edit-wiki/openproject_user_guide_wiki_noparent_page_example.png
  docs/user-guide/wiki/create-edit-wiki/watch-wiki.png
  docs/user-guide/wiki/openproject_user_guide_wiki.png
  docs/user-guide/wiki/openproject_user_guide_wiki_emoji.png
  docs/user-guide/work-packages/edit-work-package/README.md
  docs/user-guide/work-packages/edit-work-package/edit-work-package.png
  docs/user-guide/work-packages/edit-work-package/openproject_user_guide_wp_autosave_icon.png
Labels: documentation

#16601 [#56636] 14.5 Documentation: Meetings module changes https://communi…
  docs/user-guide/meetings/dynamic-meetings/README.md
  docs/user-guide/meetings/dynamic-meetings/openproject_userguide_create_new_meeting.png
Labels: documentation

#16641 Fix error pages being styled incorrectly
  app/views/layouts/only_logo.html.erb
  config/application.rb
Labels: bugfix

#16625 Update macOS dev docs
  docs/development/development-environment/macos/README.md
Labels: documentation

#16646 [57644] Column ordering broken on project list
  app/components/projects/configure_view_modal_component.html.erb
  app/components/projects/configure_view_modal_component.rb
Labels: bugfix, needs review

#16648 [57686] Notification center split screen: tab nav is hidden behind the top banner
  app/components/work_packages/split_view_component.sass
  frontend/src/app/features/work-packages/components/wp-details/wp-details-toolbar.html
  frontend/src/global_styles/layout/_toolbar_mobile.sass
  frontend/src/global_styles/openproject/_mixins.sass
Labels: bugfix, styling, pullpreview, needs review

#16650 Fix date picker being blank and jumpy when appearing
  frontend/src/app/shared/components/datepicker/modal-single-date-picker/modal-single-date-picker.component.ts
  frontend/src/app/spot/components/drop-modal/drop-modal-portal.component.ts
  frontend/src/app/spot/components/drop-modal/drop-modal.component.ts
  modules/team_planner/spec/features/query_handling_spec.rb
  spec/features/admin/working_days_spec.rb
  spec/features/views/shared_examples.rb
  spec/support/components/datepicker/datepicker_modal.rb
  spec/support/toasts/expectations.rb
Labels: needs review, flaky-spec

#16647 [57683] Clicking a notification email should open the activity view of the work package
  app/mailers/sharing_mailer.rb
  app/views/mailer/_notification_row.html.erb
  app/views/work_package_mailer/mentioned.html.erb
Labels: bugfix, needs review

#16626 [#57592] 14.5 Documentation: Rename actions in work package dropdown …
  docs/user-guide/file-management/nextcloud-integration/README.md
  docs/user-guide/work-packages/README.md
  docs/user-guide/work-packages/copy-move-delete/openproject_user_guide_copy_move_delete_detailed_view.png
  docs/user-guide/work-packages/copy-move-delete/openproject_user_guide_copy_move_delete_threedotsmenu.png
  docs/user-guide/work-packages/copy-move-delete/openproject_user_guide_copy_move_delete_wptableview.png
  docs/user-guide/work-packages/duplicate-move-delete/README.md
  docs/user-guide/work-packages/duplicate-move-delete/change-project-of-work-package.png
  docs/user-guide/work-packages/duplicate-move-delete/openproject_user_guide_copy_move_delete_detailed_view.png
  docs/user-guide/work-packages/duplicate-move-delete/openproject_user_guide_copy_move_delete_threedotsmenu.png
  docs/user-guide/work-packages/duplicate-move-delete/openproject_user_guide_copy_move_delete_warning_message_missing_wp_type.png
  docs/user-guide/work-packages/duplicate-move-delete/openproject_user_guide_copy_move_delete_wptableview.png
  docs/user-guide/work-packages/work-packages-faq/README.md
Labels: documentation

#16600 Some doc updates
  docs/installation-and-operations/installation/packaged/README.md
  docs/installation-and-operations/operation/upgrading/README.md
  docs/system-admin-guide/authentication/openid-providers/07-client-secret.png
  docs/system-admin-guide/authentication/openid-providers/08-add-secret.png
  docs/system-admin-guide/authentication/openid-providers/README.md
Labels: documentation, needs review

#16414 Render split screen using no-layout turbo-frame
  app/components/work_packages/details/tab_component.html.erb
  app/components/work_packages/split_view_component.html.erb
  app/controllers/concerns/work_packages/with_split_view.rb
  app/controllers/notifications_controller.rb
  app/helpers/work_packages/split_view_helper.rb
  app/views/layouts/base.html.erb
  app/views/work_packages/split_view.html.erb
  config/routes.rb
  frontend/src/app/features/in-app-notifications/center/state/ian-center.service.ts
  frontend/src/turbo/setup.ts
  frontend/src/turbo/turbo-navigation-patch.ts
  lookbook/previews/open_project/work_packages/split_view_component_preview.rb
  spec/components/work_packages/split_view_component_spec.rb
  spec/features/notifications/notification_center/split_screen_spec.rb
Labels: bugfix, needs review

#16554 Add release notes draft for 14.5
  docs/release-notes/14-5-0/README.md
  docs/release-notes/14-5-0/openproject-14-5-export-work-packages-modal.png
  docs/release-notes/14-5-0/openproject-14-5-multiple-projects-to-storage.png
  docs/release-notes/14-5-0/openproject-14-5-recaptcha-turnstile.png
  docs/release-notes/14-5-0/openproject-14-5-wysiwyg-editor.png
Labels: documentation

#16656 [#57594] 14.5 Documentation: Update PageHeaders & SubHeaders in the M…
  docs/enterprise-guide/enterprise-cloud-guide/gdpr-compliance/README.md
  docs/faq/README.md
  docs/getting-started/my-account/README.md
  docs/getting-started/sign-in-registration/README.md
  docs/glossary/README.md
  docs/release-notes/12/12-0-0/README.md
  docs/release-notes/12/12-4-0/README.md
  docs/release-notes/13-1-0/README.md
  docs/release-notes/14-4-0/README.md
  docs/system-admin-guide/authentication/two-factor-authentication/README.md
  docs/system-admin-guide/emails-and-notifications/README.md
  docs/system-admin-guide/integrations/gitlab-integration/README.md
  docs/system-admin-guide/system-settings/languages/README.md
  docs/system-admin-guide/users-permissions/users/README.md
  docs/user-guide/calendar/README.md
  docs/user-guide/forums/README.md
  docs/user-guide/home/README.md
  docs/user-guide/my-account/README.md
  docs/user-guide/my-account/openproject_my_account_2fa_overview.png
  docs/user-guide/my-account/openproject_my_account_access_tokens_api.png
  docs/user-guide/my-account/openproject_my_account_access_tokens_calendar_invalid.png
  docs/user-guide/my-account/openproject_my_account_access_tokens_calendar_list.png
  docs/user-guide/my-account/openproject_my_account_access_tokens_delete_calendar.png
  docs/user-guide/my-account/openproject_my_account_access_tokens_oauth.png
  docs/user-guide/my-account/openproject_my_account_access_tokens_rss.png
  docs/user-guide/my-account/openproject_my_account_authentication_options.png
  docs/user-guide/my-account/openproject_my_account_authenticator_app.png
  docs/user-guide/my-account/openproject_my_account_authenticator_webauth.png
  docs/user-guide/my-account/openproject_my_account_avatar.png
  docs/user-guide/my-account/openproject_my_account_change_password.png
  docs/user-guide/my-account/openproject_my_account_dark_mode.png
  docs/user-guide/my-account/openproject_my_account_delete_account.png
  docs/user-guide/my-account/openproject_my_account_email_reminders.png
  docs/user-guide/my-account/openproject_my_account_high_contrast_mode.png
  docs/user-guide/my-account/openproject_my_account_notifications.png
  docs/user-guide/my-account/openproject_my_account_page_settings.png
  docs/user-guide/my-account/openproject_my_account_profile.png
  docs/user-guide/my-account/openproject_my_account_sessions_management.png
  docs/user-guide/my-account/openproject_my_account_two_factor_authentication.png
  docs/user-guide/my-account/openproject_my_account_two_factor_authentication_mobile.png
  docs/user-guide/my-account/openproject_open_my_account_page.png
  docs/user-guide/notifications/README.md
  docs/user-guide/notifications/notification-settings/README.md
  docs/user-guide/work-packages/edit-work-package/README.md
  docs/user-guide/work-packages/work-packages-faq/README.md
  lookbook/docs/patterns/15-colors.md.erb
Labels: documentation

#16658 [#57587] 14.5 Documentation: Notifications center changes https://co…
  docs/user-guide/notifications/README.md
  docs/user-guide/notifications/openproject-notification-center-inbox.png
  docs/user-guide/notifications/openproject_user_guide_notification_activity_tab.png
  docs/user-guide/notifications/openproject_user_guide_notification_center_mark_read_envelope.png
  docs/user-guide/notifications/openproject_user_guide_notification_center_mark_read_envelope_splitscreen_mode.png
  docs/user-guide/notifications/openproject_user_guide_notification_center_split_screen.png
Labels: documentation

#16653 [#55234] Fix text filter width on project list
  app/components/projects/index_sub_header_component.html.erb
  frontend/src/global_styles/primer/_overrides.sass
Labels: needs review

#16657 [#57588] 14.5 Documentation: Work packages export modal with settings…
  docs/user-guide/gantt-chart/README.md
  docs/user-guide/gantt-chart/openproject-user-guide-export-gantt-chart.png
  docs/user-guide/gantt-chart/openproject-user-guide-gantt-charts-export.png
  docs/user-guide/work-packages/exporting/README.md
  docs/user-guide/work-packages/exporting/openproject-pdf-export-work-plans.png
  docs/user-guide/work-packages/exporting/openproject_export_csv.png
  docs/user-guide/work-packages/exporting/openproject_export_csv_with_descriptions.png
  docs/user-guide/work-packages/exporting/openproject_export_excel.png
  docs/user-guide/work-packages/exporting/openproject_export_excel_with_descriptions.png
  docs/user-guide/work-packages/exporting/openproject_export_excel_with_relations.png
  docs/user-guide/work-packages/exporting/openproject_export_wp.png
  docs/user-guide/work-packages/exporting/openproject_pdf_export_report_excel_options.png
  docs/user-guide/work-packages/exporting/openproject_pdf_export_report_gantt_chart_options.png
  docs/user-guide/work-packages/exporting/openproject_pdf_export_report_options.png
  docs/user-guide/work-packages/exporting/openproject_pdf_report_csv_options.png
  docs/user-guide/work-packages/exporting/openproject_pdf_table_export.png
  docs/user-guide/work-packages/exporting/openproject_wp_export_options.png
  docs/user-guide/work-packages/exporting/openproject_wp_report_include_images_checked.png
  docs/user-guide/work-packages/exporting/openproject_wp_report_total_sum.png
  docs/user-guide/work-packages/exporting/openproject_wp_table_total_sum.png
Labels: documentation

#16609 [#56638] 14.5 Documentation: Enable a storage for multiple projects a…
  docs/system-admin-guide/files/external-file-storages/README.md
  docs/system-admin-guide/integrations/nextcloud/3_2_01-NC_Step_1.png
  docs/system-admin-guide/integrations/nextcloud/3_2_03-NC_Step_2.png
  docs/system-admin-guide/integrations/nextcloud/3_2_04-NC_Step_3.png
  docs/system-admin-guide/integrations/nextcloud/3_2_06-NC_OP_OAuth_Replace.png
  docs/system-admin-guide/integrations/nextcloud/3_4_03-OP_Replace_Alert.png
  docs/system-admin-guide/integrations/nextcloud/Nextcloud_OpenProject_integration_app.png
  docs/system-admin-guide/integrations/nextcloud/OP-OAuth-values.png
  docs/system-admin-guide/integrations/nextcloud/README.md
  docs/system-admin-guide/integrations/nextcloud/apps-in-top-right-menu.png
  docs/system-admin-guide/integrations/nextcloud/file-storage-list-admin.png
  docs/system-admin-guide/integrations/nextcloud/file-storage-list-project.png
  docs/system-admin-guide/integrations/nextcloud/nc-complete_setup.png
  docs/system-admin-guide/integrations/nextcloud/nc-project_folders-active_default.png
  docs/system-admin-guide/integrations/nextcloud/nc-project_folders-application_password.png
  docs/system-admin-guide/integrations/nextcloud/new-storage-admin.png
  docs/system-admin-guide/integrations/nextcloud/openproject-complete_setup.png
  docs/system-admin-guide/integrations/nextcloud/openproject-oauth.png
  docs/system-admin-guide/integrations/nextcloud/openproject-project_folders-default.png
  docs/system-admin-guide/integrations/nextcloud/openproject-system_guide_admin-defaults-user-options.png
  docs/system-admin-guide/integrations/nextcloud/openproject_system_guide_admin-file-storages.png
  docs/system-admin-guide/integrations/nextcloud/openproject_system_guide_file_storages_add_projects_button.png
  docs/system-admin-guide/integrations/nextcloud/openproject_system_guide_nextcloud_edit_remove_in_projects.png
  docs/system-admin-guide/integrations/nextcloud/openproject_system_guide_nextcloud_integration_setup_incomplete_message.png
  docs/system-admin-guide/integrations/nextcloud/openproject_system_guide_nextcloud_integration_setup_openproject_integration_app.png
  docs/system-admin-guide/integrations/nextcloud/openproject_system_guide_nextcloud_integration_setup_step_1.png
  docs/system-admin-guide/integrations/nextcloud/openproject_system_guide_nextcloud_integration_setup_step_10.png
  docs/system-admin-guide/integrations/nextcloud/openproject_system_guide_nextcloud_integration_setup_step_11.png
  docs/system-admin-guide/integrations/nextcloud/openproject_system_guide_nextcloud_integration_setup_step_2.png
  docs/system-admin-guide/integrations/nextcloud/openproject_system_guide_nextcloud_integration_setup_step_3.png
  docs/system-admin-guide/integrations/nextcloud/openproject_system_guide_nextcloud_integration_setup_step_4.png
  docs/system-admin-guide/integrations/nextcloud/openproject_system_guide_nextcloud_integration_setup_step_5.png
  docs/system-admin-guide/integrations/nextcloud/openproject_system_guide_nextcloud_integration_setup_step_6.png
  docs/system-admin-guide/integrations/nextcloud/openproject_system_guide_nextcloud_integration_setup_step_7.png
  docs/system-admin-guide/integrations/nextcloud/openproject_system_guide_nextcloud_integration_setup_step_8.png
  docs/system-admin-guide/integrations/nextcloud/openproject_system_guide_nextcloud_integration_setup_step_9.png
  docs/system-admin-guide/integrations/nextcloud/openproject_system_guide_nextcloud_reset.png
  docs/system-admin-guide/integrations/nextcloud/openproject_system_guide_nextcloud_setup_activate_in_projects.png
  docs/system-admin-guide/integrations/nextcloud/openproject_system_guide_nextcloud_setup_delete_storage_button.png
  docs/system-admin-guide/integrations/nextcloud/openproject_system_guide_nextcloud_setup_delete_storage_icon.png
  docs/system-admin-guide/integrations/nextcloud/openproject_system_guide_nextcloud_setup_oaut_replace_alert.png
  docs/system-admin-guide/integrations/nextcloud/openproject_system_guide_nextcloud_setup_select_apps.png
  docs/system-admin-guide/integrations/one-drive/README.md
  docs/system-admin-guide/integrations/one-drive/openproject_system_guide_delete_icon_onedrive_storage.png
  docs/system-admin-guide/integrations/one-drive/openproject_system_guide_delete_onedrive_storage_in_a_project.png
  docs/system-admin-guide/integrations/one-drive/openproject_system_guide_edit_icon_onedrive_storage.png
  docs/system-admin-guide/integrations/one-drive/openproject_system_guide_file_storages_add_projects_button_onedrive.png
  docs/system-admin-guide/integrations/one-drive/openproject_system_guide_onedrive_storage_add_multiple_projects.png
  docs/system-admin-guide/integrations/one-drive/openproject_system_guide_onedrive_storage_remove_projects.png
  docs/system-admin-guide/integrations/one-drive/openproject_system_guide_select_onedrive_storage.png
  docs/user-guide/file-management/README.md
  docs/user-guide/file-management/file-management-faq/README.md
Labels: documentation

#16665 remove unused images
  docs/getting-started/my-account/openproject_my_account_2fa_overview.png
  docs/getting-started/my-account/openproject_my_account_access_tokens.png
  docs/getting-started/my-account/openproject_my_account_access_tokens_calendar_invalid.png
  docs/getting-started/my-account/openproject_my_account_access_tokens_calendar_list.png
  docs/getting-started/my-account/openproject_my_account_access_tokens_delete_calendar.png
  docs/getting-started/my-account/openproject_my_account_access_tokens_oauth.png
  docs/getting-started/my-account/openproject_my_account_access_tokens_rss.png
  docs/getting-started/my-account/openproject_my_account_authentication_options.png
  docs/getting-started/my-account/openproject_my_account_authenticator_app.png
  docs/getting-started/my-account/openproject_my_account_authenticator_webauth.png
  docs/getting-started/my-account/openproject_my_account_avatar.png
  docs/getting-started/my-account/openproject_my_account_change_password.png
  docs/getting-started/my-account/openproject_my_account_dark_mode.png
  docs/getting-started/my-account/openproject_my_account_delete_account.png
  docs/getting-started/my-account/openproject_my_account_email_reminders.png
  docs/getting-started/my-account/openproject_my_account_high_contrast_mode.png
  docs/getting-started/my-account/openproject_my_account_notifications.png
  docs/getting-started/my-account/openproject_my_account_page_settings.png
  docs/getting-started/my-account/openproject_my_account_profile.png
  docs/getting-started/my-account/openproject_my_account_sessions_management.png
  docs/getting-started/my-account/openproject_my_account_two_factor_authentication.png
  docs/getting-started/my-account/openproject_my_account_two_factor_authentication_mobile.png
  docs/system-admin-guide/authentication/ldap-connections/Sys-admin_ldap-authentication.png
  docs/system-admin-guide/authentication/ldap-connections/ldap-attribute-mapping.png
  docs/system-admin-guide/authentication/ldap-connections/ldap-details.png
  docs/system-admin-guide/authentication/ldap-connections/ldap-group-synchronization/ldap-group-form.png
  docs/system-admin-guide/authentication/ldap-connections/ldap-group-synchronization/ldap-groups-filter.png
  docs/system-admin-guide/authentication/ldap-connections/ldap-host-and-security.png
  docs/system-admin-guide/authentication/ldap-connections/ldap-index-page.png
  docs/system-admin-guide/authentication/ldap-connections/ldap-system-user.png
  docs/system-admin-guide/authentication/recaptcha/Sys-admin-authentication-recaptcha.png
  docs/user-guide/gantt-chart/openproject-user-guide-gantt-pdf-gantt-icon.png
  docs/user-guide/gantt-chart/openproject-user-guide-gantt-pdf-gantt-options.png
  docs/user-guide/notifications/NotificationCenter-12.4-splitScreenView-structure.png
  docs/user-guide/notifications/mark-as-read.png
  docs/user-guide/notifications/notification-full-screen-view-work-package.png
  docs/user-guide/notifications/notifications-activity-tab.png
  docs/user-guide/notifications/notifications-bottom-bar-4292960.png
  docs/user-guide/work-packages/exporting/openproject_export_atom.png
  docs/user-guide/work-packages/exporting/openproject_pdf_table_export_description.png
  docs/user-guide/work-packages/exporting/openproject_pdf_table_export_relations.png
  docs/user-guide/work-packages/exporting/openproject_wp_export_options.png
Labels: documentation

#16618 [57632] Use FeedbackDialog component in core
  Gemfile
  Gemfile.lock
  app/components/my/access_token/access_token_created_dialog_component.html.erb
  app/components/shares/project_queries/upsale_component.html.erb
  app/components/shares/work_packages/modal_upsale_component.html.erb
  app/views/admin/settings/project_custom_fields/project_mappings.html.erb
  config/initializers/assets.rb
  frontend/package-lock.json
  frontend/package.json
  modules/job_status/app/components/job_status/dialog/body_component.html.erb
  modules/job_status/app/components/job_status/dialog/body_component.rb
  modules/job_status/app/components/job_status/dialog/dialog_component.html.erb
  modules/storages/app/components/storages/admin/storages/oauth_access_grant_nudge_modal_component.html.erb
  modules/storages/app/components/storages/open_project_storage_modal_component/body.html.erb
  modules/storages/app/components/storages/project_storages/destroy_confirmation_dialog_component.html.erb
  modules/storages/app/views/storages/admin/storages/project_storages/index.html.erb
  modules/storages/spec/requests/project_storages_open_spec.rb
Labels: maintenance

#16663 [57687] Mobile: Underline Nav readjusts horizontal scroll unnecessarily even when tab is visible
  frontend/src/global_styles/primer/_overrides.sass
Labels: bugfix, styling

#16669 Update the notification using the selected event ID
  frontend/src/app/features/in-app-notifications/center/state/ian-center.service.ts
Labels: bugfix, needs review

#16677 Bump gems
  Gemfile
  Gemfile.lock
Labels: dependencies

#16678 Use bold, default scheme for links in border boxes
  app/components/settings/project_custom_field_sections/custom_field_row_component.html.erb
  modules/storages/app/components/storages/admin/storage_row_component.html.erb
Labels: feature

#16670 update release notes 14.5
  docs/release-notes/14-5-0/README.md
  docs/release-notes/14-5-0/openproject-14-5-notification-center.png
  docs/release-notes/14-5-0/openproject_user_guide_copy_move_delete_detailed_view-570939f2.png
Labels: documentation

#16671 Bump primer to 0.45.0
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
  modules/storages/spec/features/hide_attachments_spec.rb
Labels: maintenance

#16684 docs update 14.5
  docs/user-guide/work-packages/edit-work-package/README.md
  docs/user-guide/work-packages/edit-work-package/openproject_user_guide_wp_quick_context_menu.png
Labels: documentation

#16664 [#57704] Resolve pending spec in `direct_ifc_upload_spec.rb`
  modules/bim/spec/features/ifc_models/direct_ifc_upload_spec.rb
Labels: maintenance

#16686 Fall back empty versions to "not set"
  .github/workflows/version-check.yml
  script/ci/version_check.sh
Labels: needs review

#16689 update glossary for 14.5
  docs/glossary/README.md
Labels: documentation

#16676 [#57037] Migrate UserPreference settings with the "default" theme to "light"
  db/migrate/20240909151818_migrate_legacy_default_theme_to_light_theme.rb
  spec/migrations/migrate_legacy_default_theme_to_light_theme_spec.rb
Labels: bugfix, needs review

#16706 Debug turbo events in development
  frontend/src/turbo/constants.ts
  frontend/src/turbo/setup.ts
Labels: maintenance, needs review

#16705 [#55021] Free choice of columns in exports
  app/components/projects/row_component.rb
  app/models/projects/exports/query_exporter.rb
  app/models/queries/projects/orders/default_order.rb
  app/models/queries/projects/selects/default.rb
  modules/xls_export/spec/models/xls_export/project/exporter/xls_integration_spec.rb
  spec/models/projects/exporter/csv_integration_spec.rb
  spec/models/queries/projects/project_query_spec.rb
Labels: feature

#16716 Docs: fix broken docker links
  docs/installation-and-operations/installation/kubernetes/README.md
  docs/installation-and-operations/installation/synology/README.md
  docs/installation-and-operations/misc/migration-to-postgresql13/README.md
  docs/installation-and-operations/operation/restoring/README.md
  docs/installation-and-operations/operation/upgrading/README.md
  script/docs/check_links
Labels: documentation

#16714 Fix remain hard code color in Invite user dialog.
  frontend/src/app/shared/components/option-list/option-list.sass
Labels: bugfix, styling

#16566 Added documentation concerning forms
  lookbook/docs/patterns/02-forms.md.erb
  lookbook/docs/patterns/16-settings-pages.md.erb
  lookbook/previews/patterns/forms_preview.rb
  lookbook/previews/patterns/forms_preview/default.html.erb
Labels: documentation

#16722 Fix/57906/disable permission check boxes
  frontend/src/stimulus/controllers/dynamic/admin/roles.controller.ts
  spec/features/global_roles/global_role_crud_spec.rb
Labels: bugfix, needs review

#16704 Try another hack to reposition CKEditor toolbar
  frontend/src/turbo/dialog-stream-action.ts
Labels: needs review

#16720 Use default formatting of text in agenda items
  modules/meeting/app/components/meeting_agenda_items/item_component/show_component.html.erb
Labels: bugfix, needs review

#16651 Lookbook: Docs for Feedback Dialog/Message
  lookbook/docs/patterns/13-feedback-dialog-and-feedback-message.md.erb
  lookbook/previews/patterns/feedback_dialog_preview.rb
  lookbook/previews/patterns/feedback_dialog_preview/custom_icon.html.erb
  lookbook/previews/patterns/feedback_dialog_preview/default.html.erb
  lookbook/previews/patterns/feedback_dialog_preview/loading.html.erb
Labels: documentation, maintenance

#16727 Bump primer to 0.47.0
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: maintenance

#16728 Add technical notes to lookbook forms page
  lookbook/docs/patterns/02-forms.md.erb
  lookbook/docs/patterns/14-forms.md.erb
  lookbook/previews/patterns/forms_preview.rb
  lookbook/previews/patterns/forms_preview/custom_width_fields_form.html.erb
Labels: needs review

#16713 [#57856] Export modal should not show a scrollbar for default settings
  app/components/_index.sass
  app/components/open_project/common/divider_component.rb
  app/components/work_packages/exports/modal_dialog_component.sass
  app/components/work_packages/exports/pdf/report/export_settings_component.html.erb
  app/components/work_packages/exports/xls/export_settings_component.html.erb
Labels: bugfix

#16719 Make expandable list button text more specific
  app/components/op_primer/expandable_list_component.html.erb
  config/locales/en.yml
  frontend/src/stimulus/controllers/dynamic/expandable-list.controller.ts
  modules/meeting/app/components/meetings/side_panel/participants_component.html.erb
Labels: pullpreview

#16740 [57614] Meetings: The add button should have a trailing icon to indicate that it's a drop-down
  modules/meeting/app/components/meeting_agenda_items/new_button_component.html.erb
Labels: bugfix, needs review

#16731 [57143] Primer: Action menu is sometimes incorrectly positioned on mobile
  frontend/src/app/core/setup/globals/global-listeners/top-menu-scroll.ts
  frontend/src/global_styles/layout/_base_mobile.sass
  frontend/src/global_styles/layout/_main_menu_mobile.sass
Labels: bugfix, styling, pullpreview, needs review

#16743 chore(deps): bump md-to-pdf to v0.1.2
  Gemfile
  Gemfile.lock
Labels: dependencies

#16542 [#57024] Relative value macros for work package descriptions
  docs/user-guide/wysiwyg/README.md
  lib/open_project/text_formatting/matchers/attribute_macros.rb
  spec/features/wysiwyg/macros/attribute_macros_spec.rb
  spec/lib/open_project/text_formatting/markdown/attribute_macros_spec.rb
Labels: pullpreview

#16742 [57927] Primerise the Notification badge in the top header
  frontend/src/app/features/in-app-notifications/bell/in-app-notification-bell.component.sass
  frontend/src/global_styles/openproject/_mixins.sass
Labels: bugfix, needs review

#16737 [57092] Right side of the instance upper banner looks misaligned
  frontend/src/app/features/in-app-notifications/bell/in-app-notification-bell.component.html
  frontend/src/app/shared/components/icon/icon.module.ts
  frontend/src/global_styles/common/header/app-menu.sass
  frontend/src/global_styles/primer/_overrides.sass
Labels: bugfix, needs review

#16735 [57423] Progress modal should always prevent save when there are invalid values
  app/components/work_packages/progress/status_based/modal_body_component.html.erb
  app/components/work_packages/progress/work_based/modal_body_component.html.erb
  app/controllers/work_packages/progress_controller.rb
  app/forms/work_packages/pre_14_4_progress_form.rb
  app/forms/work_packages/progress_form.rb
  app/forms/work_packages/progress_form/initial_values_form.rb
  app/services/work_packages/set_attributes_service/derive_progress_values_status_based.rb
  app/views/work_packages/progress/update.turbo_stream.erb
  frontend/src/app/shared/components/fields/edit/field-types/progress-popover-edit-field.component.ts
  frontend/src/stimulus/controllers/dynamic/work-packages/progress/preview-progress.controller.ts
  frontend/src/stimulus/controllers/dynamic/work-packages/progress/preview.controller.ts
  spec/features/work_packages/progress_modal_spec.rb
  spec/services/work_packages/set_attributes_service/derive_progress_values_status_based_spec.rb
  spec/support/components/work_packages/progress_popover.rb
  spec/support/edit_fields/progress_edit_field.rb
Labels: bugfix, needs review

#16750 Restore ldap-only warning for mail
  app/views/my/account.html.erb
Labels: bugfix, needs review

#16746 Include past meetings in count
  modules/meeting/app/controllers/work_package_meetings_tab_controller.rb
  modules/meeting/lib/open_project/meeting/engine.rb
  modules/meeting/spec/features/structured_meetings/work_package_meetings_tab_spec.rb
Labels: feature

#16757 fix[Op#57516]: Reset column info and primary key after migration for fresh state
  spec/migrations/add_primary_key_to_custom_fields_projects_spec.rb
Labels: flaky-spec

#16741 [#55392] page number should reset when changing the sort order via the configure view modal
  app/components/projects/configure_view_modal_component.html.erb
  app/controllers/projects_controller.rb
  app/helpers/pagination_helper.rb
  frontend/src/stimulus/controllers/dynamic/sort-by-config.controller.ts
  spec/features/projects/projects_index_spec.rb
  spec/support/pages/projects/index.rb
Labels: bugfix

#16691 [57153] Reduce amount of design variables needed for the sidebar
  app/views/custom_styles/_inline_css.erb
  frontend/src/global_styles/openproject/_variable_defaults.scss
  lib/open_project/custom_styles/design.rb
Labels: feature

#16764 [57911] Use simpler 'Show more' label for expandable list
  app/components/op_primer/expandable_list_component.html.erb
  config/locales/en.yml
Labels: feature, needs review

#16758 Change meeting flash banner width to 80%
  app/views/layouts/base.html.erb
  frontend/src/global_styles/primer/_banners.sass
  frontend/src/global_styles/primer/_index.sass
  frontend/src/turbo/flash-stream-action.ts
  modules/meeting/app/components/meetings/update_flash_component.html.erb
  modules/meeting/spec/features/structured_meetings/structured_meeting_update_flash_spec.rb
  modules/meeting/spec/support/pages/structured_meeting/show.rb
Labels: feature

#16766 Do not keep settings radio button state when navigating
  app/forms/settings_form_decorator.rb
  spec/features/admin/progress_tracking_spec.rb
Labels: bugfix, needs review

#15972 Use jemalloc to prevent memory bloating
  app/controllers/admin_controller.rb
  config/locales/en.yml
  docker/prod/Dockerfile
  docker/prod/entrypoint-slim.sh
  docker/prod/entrypoint.sh
  docker/prod/setup/preinstall-common.sh
Labels: contribution, needs review, docker

#16770 [#57648] Replace "Add assignee" button in Team Planner with + icon
  docs/user-guide/team-planner/README.md
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.html
  modules/team_planner/config/locales/js-en.yml
Labels: feature, needs review

#16779 i18n for `responsible` reason in notification center
  config/locales/js-en.yml
Labels: needs review

#16788 [57993] Browser tab is missing breadcrumb
  app/components/admin/design_header_component.html.erb
Labels: bugfix

#16790 [#57985] Meeting details concurrent error message is unclear and badly positioned
  config/locales/en.yml
  modules/meeting/app/components/meetings/side_panel/details_form_component.html.erb
Labels: bugfix, needs review

#16775 Feature/57990 preserve percent complete over remaining work when migrating
  app/workers/work_packages/progress/apply_statuses_change_job.rb
  app/workers/work_packages/progress/migrate_values_job.rb
  app/workers/work_packages/progress/sql_commands.rb
  config/locales/en.yml
  spec/lib/journal_formatter/cause_spec.rb
  spec/migrations/update_progress_calculation_spec.rb
Labels: feature

#16802 [57994] Display mode drop down from Design page doesn't change to correct display mode
  lib/open_project/custom_styles/color_themes.rb
  spec/features/custom_styles/tabs_navigation_spec.rb
Labels: bugfix

#16804 Add comma to authenticate header
  lib_static/open_project/authentication.rb
  spec/requests/api/v3/authentication_spec.rb
Labels: bugfix

#16808 Remove :percent_complete_edition feature flag
  app/components/work_packages/progress/status_based/modal_body_component.html.erb
  app/components/work_packages/progress/work_based/modal_body_component.html.erb
  app/components/work_packages/progress/work_based/modal_body_component.rb
  app/contracts/work_packages/base_contract.rb
  app/controllers/work_packages/progress_controller.rb
  app/forms/work_packages/pre_14_4_progress_form.rb
  app/forms/work_packages/progress_form/initial_values_form.rb
  app/services/work_packages/set_attributes_service.rb
  app/services/work_packages/set_attributes_service/pre_14_4_derive_progress_values.rb
  app/views/admin/settings/progress_tracking/show.html.erb
  app/workers/work_packages/progress/apply_statuses_change_job.rb
  config/initializers/feature_decisions.rb
  config/locales/en.yml
  config/locales/js-en.yml
  frontend/src/stimulus/controllers/dynamic/admin/progress-tracking.controller.ts
  spec/components/work_packages/progress/work_based/modal_body_component_pre_14_4_without_percent_complete_edition_spec.rb
  spec/contracts/work_packages/base_contract_pre_14_4_without_percent_complete_edition_spec.rb
  spec/contracts/work_packages/base_contract_spec.rb
  spec/controllers/work_packages/progress_controller_pre_14_4_without_percent_complete_edition_spec.rb
  spec/controllers/work_packages/progress_controller_spec.rb
  spec/features/admin/progress_tracking_spec.rb
  spec/features/work_packages/progress_modal_pre_14_4_without_percent_complete_edition_spec.rb
  spec/features/work_packages/progress_modal_spec.rb
  spec/lib/api/v3/work_packages/schema/specific_work_package_schema_pre_14_4_without_percent_complete_edition_spec.rb
  spec/lib/api/v3/work_packages/schema/specific_work_package_schema_spec.rb
  spec/lib/api/v3/work_packages/schema/typed_work_package_schema_pre_14_4_without_percent_complete_edition_spec.rb
  spec/lib/api/v3/work_packages/schema/typed_work_package_schema_spec.rb
  spec/lib/api/v3/work_packages/schema/work_package_schema_representer_pre_14_4_without_percent_complete_edition_spec.rb
  spec/lib/api/v3/work_packages/schema/work_package_schema_representer_spec.rb
  spec/services/work_packages/set_attributes_service_pre_14_4_without_percent_complete_edition_spec.rb
  spec/services/work_packages/set_attributes_service_spec.rb
  spec/support/edit_fields/progress_edit_field.rb
  spec/workers/work_packages/progress/apply_statuses_change_job_pre_14_4_without_percent_complete_edition_spec.rb
  spec/workers/work_packages/progress/apply_statuses_change_job_spec.rb
Labels: needs review

#16811 [#57505] Turn project list into favorite without reloading the page
  app/components/projects/row_component.rb
Labels: needs review

#16649 [#57529] Add options for sum totals calculation mode in hierarchies
  app/models/journal.rb
  app/models/journal/caused_by_total_percent_complete_mode_changed_to_simple_average.rb
  app/models/journal/caused_by_total_percent_complete_mode_changed_to_work_weighted_average.rb
  app/models/work_package.rb
  app/services/settings/update_service.rb
  app/services/work_packages/update_ancestors/loader.rb
  app/services/work_packages/update_ancestors_service.rb
  app/views/admin/settings/progress_tracking/show.html.erb
  app/workers/work_packages/progress/apply_total_percent_complete_mode_change_job.rb
  app/workers/work_packages/progress/sql_commands.rb
  config/constants/settings/definition.rb
  config/locales/en.yml
  lib/open_project/journal_formatter/cause.rb
  spec/controllers/admin/settings/progress_tracking_controller_spec.rb
  spec/features/admin/progress_tracking_spec.rb
  spec/lib/journal_formatter/cause_spec.rb
  spec/services/work_packages/update_ancestors_service_spec.rb
  spec/workers/work_packages/progress/apply_statuses_change_job_spec.rb
  spec/workers/work_packages/progress/apply_total_percent_complete_mode_change_job_spec.rb
Labels: feature, pullpreview

#16820 [57990] Make migration work with database from before 14.0 version
  app/workers/work_packages/progress/sql_commands_for_migration.rb
  lib/open_project/static/links.rb
Labels: bugfix

#16769 [53809] Update PageHeaders & SubHeaders in the (rails) global index pages
  app/components/add_button_component.html.erb
  app/components/add_button_component.rb
  app/controllers/homescreen_controller.rb
  app/views/activities/index.html.erb
  app/views/homescreen/index.html.erb
  app/views/news/index.html.erb
  modules/boards/app/controllers/boards/boards_controller.rb
  modules/boards/app/views/boards/boards/index.html.erb
  modules/boards/spec/features/board_enterprise_spec.rb
  modules/boards/spec/features/support/board_index_page.rb
  modules/boards/spec/features/support/board_list_page.rb
  modules/boards/spec/features/support/board_new_page.rb
  modules/calendar/app/components/calendar/add_button_component.html.erb
  modules/calendar/app/views/calendar/calendars/index.html.erb
  modules/calendar/spec/features/calendars_spec.rb
  modules/calendar/spec/support/pages/calendar.rb
  modules/reporting/app/views/cost_reports/index.html.erb
  modules/reporting/spec/features/me_value_spec.rb
  modules/team_planner/app/views/team_planner/team_planner/index.html.erb
  modules/team_planner/app/views/team_planner/team_planner/overview.html.erb
  modules/team_planner/spec/support/pages/team_planner.rb
  spec/features/news/creation_and_commenting_spec.rb
Labels: feature

#16821 Fix script injection vulnerability in version-check workflow
  .github/workflows/version-check.yml
Labels: needs review

#16822 Remove typo from the notifications page.
  app/views/notifications/index.html.erb
Labels: needs review

#16823 [#34316] fix incomprehensible statement in user settings
  app/views/users/_consent.html.erb
  config/locales/en.yml
Labels: bugfix, needs review

#16831 [58127] Subtitle in activity page is centerlized
  app/views/activities/index.html.erb
Labels: bugfix

#16838 Move the reference value back to the header
  frontend/src/stimulus/controllers/poll-for-changes.controller.ts
  modules/meeting/app/components/meetings/header_component.html.erb
Labels: bugfix

#16843 [#58142] Update banners to render overlayed flash with rounded borders
  app/controllers/admin/custom_fields/custom_field_projects_controller.rb
  app/controllers/admin/settings/project_custom_fields_controller.rb
  modules/storages/app/controllers/storages/admin/storages/project_storages_controller.rb
Labels: bugfix, needs review

#16832 [57992] Banners have display issues in dark mode
  frontend/src/global_styles/primer/_flash.sass
Labels: bugfix, needs review

#16830 Release Notes 14.6
  docs/release-notes/14-6-0/README.md
  docs/release-notes/14-6-0/open-project-14-6-custom-fields-new-highlighted.png
  docs/release-notes/14-6-0/openproject-14-6-macros.png
  docs/release-notes/14-6-0/openproject-14-6-meetings-reload.png
  docs/release-notes/14-6-0/progress-tracking-admin-options.png
Labels: documentation

#16854 Bump primer to 0.47.1
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: bugfix, maintenance

#16857 [56769] Migrate queries with timeline to Gantt module
  db/migrate/20240930122522_change_view_of_queries_with_timeline_to_gantt_again.rb
Labels: bugfix, needs review
