Repository opf/openproject, pull requests merged in 2024-12, with the labels that each got.

#17309 [59795] Missing space between project selector and "include sub-projects"-checkbox
  app/components/admin/custom_fields/custom_field_projects/new_custom_field_projects_form_modal_component.html.erb
  app/forms/projects/custom_fields/custom_field_mapping_form.rb
Labels: bugfix, needs review

#17321 fix typo in contributions guide
  docs/contributions-guide/give-back-to-community/README.md
Labels: documentation

#17320 [59828] Work package create button doesn't work on mWeb
  frontend/src/app/features/work-packages/routing/split-view-routes.template.ts
Labels: bugfix, needs review

#17324 update contributions guide
  docs/contributions-guide/README.md
  docs/contributions-guide/contribution-documentation/README.md
  docs/contributions-guide/give-back-to-community/README.md
Labels: documentation

#17319 Exclude non project members from user filter
  modules/reporting/app/models/cost_query/filter/user_id.rb
Labels: needs review

#17299 [22360] Edit lag to follow-precedes-relations
  app/components/work_package_relations_tab/relation_component.html.erb
  app/components/work_package_relations_tab/relation_component.rb
  app/components/work_package_relations_tab/work_package_relation_form_component.html.erb
  app/components/work_package_relations_tab/work_package_relation_form_component.rb
  app/controllers/work_package_relations_controller.rb
  config/locales/en.yml
  spec/features/work_packages/details/relations/primerized_relations_spec.rb
  spec/support/components/work_packages/relations.rb
Labels: feature

#17332 Do not reload the relations tab after a hierarchy change.
  frontend/src/app/features/work-packages/components/wp-relations/wp-relations.component.ts
Labels: bugfix, maintenance, needs review

#17318 [59810] Parent WP and existing children can be selected as a child
  app/components/work_package_relations_tab/add_work_package_child_form_component.html.erb
  spec/features/work_packages/details/relations/primerized_relations_spec.rb
  spec/support/components/work_packages/relations.rb
Labels: bugfix, needs review

#17336 [#59800] 15.1 Documentation: Zen mode for project lists page https:/…
  docs/user-guide/projects/project-lists/README.md
  docs/user-guide/projects/project-lists/openproject_project_list_select_zen_mode.png
Labels: documentation

#17339 Remove inappropriate status tripping up turbo
  app/controllers/types_controller.rb
  spec/controllers/types_controller_spec.rb
Labels: needs review

#17356 update release image for 15.1
  frontend/src/assets/images/15_1_features.svg
Labels: needs review

#17347 Improve robustness of activity back url
  app/helpers/journals_helper.rb
  spec/helpers/journals_helper_spec.rb
Labels: needs review

#17371 [#59781] Export of an unsaved query not working properly
  frontend/src/stimulus/controllers/dynamic/work-packages/export/form.controller.ts
  spec/features/work_packages/export_spec.rb
Labels: bugfix

#17337 [59772] Buttons not visible on iOS in edit relations modal
  app/components/work_package_relations_tab/add_work_package_child_dialog_component.html.erb
  app/components/work_package_relations_tab/add_work_package_child_dialog_component.rb
  app/components/work_package_relations_tab/work_package_relation_dialog_component.html.erb
  app/components/work_package_relations_tab/work_package_relation_dialog_component.rb
Labels: bugfix, needs review

#17373 Attempt to stabilize the `primerized_relations_spec`
  spec/features/work_packages/details/relations/primerized_relations_spec.rb
  spec/support/components/work_packages/relations.rb
Labels: maintenance, needs review

#17367 release notes 15.1
  docs/release-notes/15-0-0/README.md
  docs/release-notes/15-1-0/README.md
  docs/release-notes/15-1-0/openproject-15-1-custom-field-hierarchy.jpg
  docs/release-notes/15-1-0/openproject-15-1-meetings.png
  docs/release-notes/15-1-0/openproject-15-1-page-break-contract-highlighted.png
  docs/release-notes/15-1-0/openproject-15-1-relations.png
  docs/release-notes/15-1-0/openproject-15-1-zen-mode-highlighted.png
Labels: documentation

#17391 Update spec to always use future time
  modules/meeting/spec/requests/recurring_meetings/recurring_meetings_template_completed_spec.rb
Labels: needs review

#17348 [#59799] 15.1 Documentation: Primerised Meeting index pages https://…
  docs/user-guide/meetings/classic-meetings/README.md
  docs/user-guide/meetings/classic-meetings/openproject_user_guide_create_classic_meeting_button.png
  docs/user-guide/meetings/classic-meetings/openproject_user_guide_create_classic_meeting_copy_form.png
  docs/user-guide/meetings/classic-meetings/openproject_user_guide_create_classic_meeting_edit_participants.png
  docs/user-guide/meetings/classic-meetings/openproject_user_guide_create_classic_meeting_form.png
  docs/user-guide/meetings/dynamic-meetings/README.md
  docs/user-guide/meetings/dynamic-meetings/openproject_dynamic_meetings_copy_modal.png
  docs/user-guide/meetings/dynamic-meetings/openproject_dynamic_meetings_create_button.png
  docs/user-guide/meetings/dynamic-meetings/openproject_dynamic_meetings_filters.png
  docs/user-guide/meetings/dynamic-meetings/openproject_dynamic_meetings_new_dynamic_meeting_form.png
  docs/user-guide/meetings/dynamic-meetings/openproject_userguide_dynamic_meetings_overview.png
  docs/user-guide/meetings/dynamic-meetings/openproject_userguide_edit_dynamic_meeting_icon.png
  docs/user-guide/meetings/dynamic-meetings/openproject_userguide_meetings_module_select.png
Labels: documentation

#17404 docs: unify/fix spelling
  docs/release-notes/15-0-2/README.md
  docs/release-notes/15-1-0/README.md
  docs/use-cases/safe-framework/README.md
Labels: documentation

#17377 ICS download option for recurring meeting
  modules/meeting/app/components/recurring_meetings/show_page_header_component.html.erb
  modules/meeting/app/controllers/recurring_meetings_controller.rb
  modules/meeting/app/models/recurring_meeting.rb
  modules/meeting/app/models/scheduled_meeting.rb
  modules/meeting/app/services/meetings/ical_helpers.rb
  modules/meeting/app/services/meetings/ical_service.rb
  modules/meeting/app/services/recurring_meetings/ical_service.rb
  modules/meeting/config/routes.rb
  modules/meeting/lib/open_project/meeting/engine.rb
  modules/meeting/spec/factories/recurring_meeting_factory.rb
  modules/meeting/spec/factories/scheduled_meeting_factory.rb
  modules/meeting/spec/models/recurring_meeting_spec.rb
  modules/meeting/spec/services/recurring_meetings/ical_service_spec.rb
Labels: feature

#17385 [#59907] fix: User hovercard behind Meeting participants overlay
  app/components/users/hover_card_component.sass
  modules/meeting/app/components/meetings/side_panel/participants_dialog.html.erb
Labels: bugfix

#17379 [#59798] 15.1 Documentation: Multi-level selection fields to support …
  docs/system-admin-guide/custom-fields/README.md
  docs/system-admin-guide/custom-fields/openproject_system_guide_custom_field_new_hierarchy_subitems.png
  docs/system-admin-guide/custom-fields/openproject_system_guide_custom_fields_list.png
  docs/system-admin-guide/custom-fields/openproject_system_guide_hierarchy_field_add_further_levels.png
  docs/system-admin-guide/custom-fields/openproject_system_guide_hierarchy_field_add_item_button.png
  docs/system-admin-guide/custom-fields/openproject_system_guide_hierarchy_field_add_item_form.png
  docs/system-admin-guide/custom-fields/openproject_system_guide_hierarchy_field_edit_items.png
  docs/system-admin-guide/custom-fields/openproject_system_guide_new_custom_field_formats.png
  docs/system-admin-guide/custom-fields/openproject_system_guide_new_custom_field_new_hierarchy.png
  docs/system-admin-guide/custom-fields/openproject_system_guide_new_custom_field_path.png
  docs/system-admin-guide/custom-fields/openproject_system_guide_new_custom_hierarchy_details_tab.png
  docs/system-admin-guide/custom-fields/system-admin-allow-multi-select.png
Labels: documentation

#17419 Fix parsing of claims through ENVs
  modules/openid_connect/app/services/openid_connect/configuration_mapper.rb
  modules/openid_connect/spec/services/openid_connect/configuration_mapper_spec.rb
Labels: bugfix, needs review

#17381 Remove default sort order messing up apply_sort
  modules/meeting/app/models/queries/meetings/meeting_query.rb
Labels: bugfix

#17399 [#59802] 15.1 Documentation: Re-design Relations tab according to Fig…
  docs/system-admin-guide/integrations/README.md
  docs/user-guide/work-packages/work-package-relations-hierarchies/README.md
  docs/user-guide/work-packages/work-package-relations-hierarchies/Relations_column.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/User-guide-display-hierarchy.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/User-guide-hierarchies.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/autocompletion.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/change-parent-work-package.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/image-20200129144540902.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/image-20200129145033802.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/openproject_user_guide_relations_change_parent.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/openproject_user_guide_relations_tab.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/openproject_user_guide_wp_add_child.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/openproject_user_guide_wp_add_child_select.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/openproject_user_guide_wp_add_relations_button.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/openproject_user_guide_wp_add_relations_form.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/openproject_user_guide_wp_hierarchy_icon.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/openproject_user_guide_wp_table_configuration.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/openproject_user_guide_wp_table_configuration_filtered.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/openproject_user_guide_wp_table_show_parent.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/select-parent-as-column.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/work-package-add-relation-as-column.png
Labels: documentation

#17374 Bug/59458 activity tab does not scroll to the bottom or correct comment on mobile
  frontend/src/stimulus/controllers/dynamic/work-packages/activities-tab/index.controller.ts
Labels: pullpreview

#17410 Change glossary for 15.1
  docs/glossary/README.md
Labels: documentation

#17408 Update Release Notes 15.1
  docs/release-notes/15-1-0/README.md
Labels: documentation

#17384 [59933] Primer view components version bump to 0.50.1
  Gemfile
  Gemfile.lock
  app/components/shares/project_queries/upsale_component.html.erb
  app/components/shares/work_packages/modal_upsale_component.html.erb
  frontend/package-lock.json
  frontend/package.json
  modules/storages/app/components/storages/admin/general_info_component.html.erb
Labels: maintenance, needs review

#17423 [#59944] Editing the date of an upcoming recurring meeting to a past date doesn't move it to the 'Past' tab
  modules/meeting/app/contracts/meetings/update_contract.rb
  modules/meeting/spec/services/meetings/update_service_integration_spec.rb
Labels: bugfix

#17003 [58454] Sidebar menu should be hidden when page width is reduced
  frontend/src/app/core/main-menu/main-menu-toggle.service.ts
Labels: bugfix

#17432 Recurring meetings: Improve form, update interval/frequency text based on user input
  frontend/src/stimulus/controllers/dynamic/recurring-meetings/form.controller.ts
  frontend/src/stimulus/controllers/op-application.controller.ts
  modules/meeting/app/components/meetings/index/form_component.html.erb
  modules/meeting/app/components/meetings/side_panel/details_form_component.html.erb
  modules/meeting/app/components/recurring_meetings/footer_component.rb
  modules/meeting/app/components/recurring_meetings/show_page_header_component.rb
  modules/meeting/app/controllers/recurring_meetings/schedule_controller.rb
  modules/meeting/app/forms/meeting/duration.rb
  modules/meeting/app/forms/meeting/location.rb
  modules/meeting/app/forms/meeting/time_group.rb
  modules/meeting/app/forms/recurring_meeting/frequency.rb
  modules/meeting/app/forms/recurring_meeting/interval.rb
  modules/meeting/app/forms/recurring_meeting/iterations.rb
  modules/meeting/app/forms/recurring_meeting/specific_date.rb
  modules/meeting/app/models/recurring_meeting.rb
  modules/meeting/config/locales/en.yml
  modules/meeting/config/routes.rb
  modules/meeting/lib/open_project/meeting/engine.rb
  modules/meeting/spec/features/recurring_meetings/recurring_meeting_create_spec.rb
  modules/meeting/spec/features/recurring_meetings/recurring_meeting_crud_spec.rb
  modules/meeting/spec/models/recurring_meeting_spec.rb
  modules/meeting/spec/requests/recurring_meetings/recurring_meetings_schedule_spec.rb
  modules/meeting/spec/support/pages/meetings/index.rb
Labels: feature, needs review

#17441 Improve documenation on wp relations
  docs/user-guide/work-packages/work-package-relations-hierarchies/README.md
Labels: documentation

#17424 Implementation/59970 introduce enterprise banner viewcomponent
  app/components/_index.sass
  app/components/enterprise_edition/banner_component.html.erb
  app/components/enterprise_edition/banner_component.rb
  app/components/enterprise_edition/banner_component.sass
  app/components/shares/project_queries/upsale_component.html.erb
  app/components/shares/work_packages/modal_upsale_component.html.erb
  app/helpers/custom_fields_helper.rb
  config/locales/en.yml
  frontend/src/global_styles/content/_enterprise.sass
  lookbook/previews/open_project/enterprise_edition/banner_component_preview.rb
  spec/components/enterprise_edition/banner_component_spec.rb
  spec/support/components/sharing/share_modal.rb
Labels: needs review

#17443 Allow duration to be input with chronic duration
  app/services/duration_converter.rb
  frontend/src/stimulus/controllers/dynamic/chronic-duration.controller.ts
  modules/meeting/app/forms/meeting/time_group.rb
  modules/meeting/app/models/meeting.rb
  modules/meeting/app/models/meeting/chronic_duration.rb
  modules/meeting/spec/models/meeting_spec.rb
Labels: feature, needs review

#17446 Remove recurring meeting feature flag
  config/initializers/feature_decisions.rb
  modules/meeting/app/components/meetings/index_sub_header_component.html.erb
  modules/meeting/app/menus/meetings/menu.rb
  modules/meeting/app/models/queries/meetings/filters/recurring_filter.rb
  modules/meeting/spec/features/recurring_meetings/recurring_meeting_create_spec.rb
  modules/meeting/spec/features/recurring_meetings/recurring_meeting_crud_spec.rb
Labels: maintenance, needs review

#17451 attempt to stabilize flickering relations spec
  spec/features/work_packages/details/relations/primerized_relations_spec.rb
Labels: needs review

#17447 Rename dynamic meetings to One-time
  modules/meeting/app/components/meetings/index_sub_header_component.html.erb
  modules/meeting/config/locales/en.yml
  modules/meeting/spec/features/recurring_meetings/recurring_meeting_create_spec.rb
  modules/meeting/spec/features/structured_meetings/structured_meeting_crud_spec.rb
  modules/meeting/spec/support/pages/meetings/index.rb
Labels: feature, needs review

#17400 [#58160] project stage columns on project list
  .gitignore
  app/components/projects/row_component.rb
  app/components/projects/table_component.html.erb
  app/components/projects/table_component.rb
  app/helpers/projects_helper.rb
  app/helpers/sort_helper.rb
  app/models/project/life_cycle_step.rb
  app/models/project/life_cycle_step_definition.rb
  app/models/queries/projects.rb
  app/models/queries/projects/selects/life_cycle_step.rb
  frontend/src/global_styles/content/_projects_list.sass
  frontend/src/global_styles/content/_table.sass
  spec/features/projects/projects_index_spec.rb
  spec/helpers/sort_helper_spec.rb
  spec/support/pages/projects/index.rb
Labels: feature

#17471 Split up huge project index spec into separate files
  spec/features/projects/lists/columns_spec.rb
  spec/features/projects/lists/filters_spec.rb
  spec/features/projects/lists/gantt_spec.rb
  spec/features/projects/lists/order_spec.rb
  spec/features/projects/lists/table_spec.rb
  spec/features/projects/projects_index_spec.rb
Labels: needs review

#17437 [#55024] Remove bugfix that is not required anymore
  frontend/src/app/core/routing/openproject.routes.ts
  frontend/src/stimulus/controllers/dynamic/overview-header.controller.ts
  modules/overviews/app/views/overviews/overviews/show.html.erb
Labels: maintenance

#17476 Allow deletion of users that favored projects
  app/workers/principals/delete_job.rb
  spec/workers/principals/delete_job_integration_spec.rb
Labels: bugfix, needs review

#17457 Implementation/59987 add setedit reminder buttondialog to workpackage split view in notification center
  frontend/src/app/features/work-packages/components/wp-buttons/wp-reminder-button/wp-reminder-button.html
  frontend/src/app/features/work-packages/components/wp-details/wp-details-toolbar.component.ts
  frontend/src/app/features/work-packages/components/wp-details/wp-details-toolbar.html
Labels: pullpreview

#17458 bug/59458-activity-tab-does-not-scroll-to-the-bottom-or-correct-comment-on-mobile-fixed
  frontend/src/stimulus/controllers/dynamic/work-packages/activities-tab/index.controller.ts
Labels: pullpreview

#17355 [59769] When adding new relations, auto-scroll to show the newly added relation
  app/components/work_package_relations_tab/index_component.rb
  app/controllers/work_package_children_controller.rb
  app/controllers/work_package_relations_controller.rb
  frontend/src/stimulus/controllers/dynamic/work-packages/relations-tab/scroll.controller.ts
  spec/controllers/work_package_relations_controller_spec.rb
Labels: feature, needs review

#17477 Replace references for AuthProvider
  app/services/principals/replace_references_service.rb
  modules/auth_saml/spec/services/principals/replace_references_service_call_integration_spec.rb
  modules/storages/lib/open_project/storages/patches/replace_references_service_patch.rb
Labels: bugfix, needs review

#17490 Disable browser`s autocompleter on date picker fields
  frontend/src/app/shared/components/datepicker/basic-range-date-picker/basic-range-date-picker.component.html
  frontend/src/app/shared/components/datepicker/basic-single-date-picker/basic-single-date-picker.component.html
Labels: needs review

#17493 Fix invited user in meetings
  modules/meeting/app/controllers/meetings_controller.rb
  modules/meeting/app/services/meetings/set_attributes_service.rb
  modules/meeting/spec/features/meetings_index_spec.rb
  modules/meeting/spec/requests/meetings_spec.rb
  modules/meeting/spec/services/meetings/create_service_integration_spec.rb
Labels: bugfix, needs review

#17497 Feature/59793 Add new icons for setting reminders `op-alarm` & `op-alarm-set`
  Gemfile
  Gemfile.lock
  app/menus/notifications/menu.rb
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/features/work-packages/components/wp-buttons/wp-reminder-button/wp-reminder-button.component.ts
  frontend/src/app/features/work-packages/components/wp-buttons/wp-reminder-button/wp-reminder-button.html
  frontend/src/app/shared/components/icon/icon.module.ts
  spec/features/work_packages/reminders_spec.rb
  spec/support/pages/work_packages/full_work_package.rb
Labels: feature, needs review

#17461 implementation/59815 Add email setting to send an email reminder immediately
  app/mailers/reminders/notification_mailer.rb
  app/models/user_preference.rb
  app/views/reminders/notification_mailer/reminder_notification.html.erb
  app/views/reminders/notification_mailer/reminder_notification.text.erb
  app/workers/mails/reminders/notification_delivery_job.rb
  app/workers/reminders/schedule_reminder_job.rb
  config/locales/en.yml
  config/locales/js-en.yml
  config/schemas/user_preferences.schema.json
  frontend/src/app/features/user-preferences/reminder-settings/immediate-reminders/immediate-reminder-settings.component.html
  frontend/src/app/features/user-preferences/reminder-settings/immediate-reminders/immediate-reminder-settings.component.ts
  frontend/src/app/features/user-preferences/reminder-settings/page/reminder-settings-page.component.ts
  frontend/src/app/features/user-preferences/state/user-preferences.model.ts
  frontend/src/app/features/user-preferences/state/user-preferences.store.ts
  lib/api/v3/user_preferences/user_preference_representer.rb
  spec/features/notifications/settings/immediate_reminder_spec.rb
  spec/lib/api/v3/user_preferences/user_preference_representer_parsing_spec.rb
  spec/mailers/previews/reminders/notification_mailer_preview.rb
  spec/mailers/reminders/notification_mailer_spec.rb
  spec/workers/mails/reminders/notification_delivery_job_spec.rb
  spec/workers/reminders/schedule_reminder_job_spec.rb
Labels: needs review

#17503 Allow authorization before_action using given permission
  app/controllers/concerns/accounts/authorization.rb
  modules/meeting/app/controllers/recurring_meetings/schedule_controller.rb
  spec/controllers/concerns/authorization_spec.rb
Labels: maintenance

#17496 [#60291] Apply view permissions on the Project List page
  app/components/projects/row_component.rb
  app/components/projects/table_component.rb
  app/models/project.rb
  app/models/project/life_cycle_step.rb
  app/models/queries/projects/selects/life_cycle_step.rb
  spec/features/projects/lists/columns_spec.rb
  spec/models/project/life_cycle_step_spec.rb
  spec/models/project_spec.rb
Labels: needs review

#17512 Bump primer to 0.51.0
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: maintenance

#17510 [#60294] Allow Gate to be overlapping a Stage
  app/contracts/project_life_cycle_steps/base_contract.rb
  spec/contracts/project_life_cycle_steps/base_contract_spec.rb
Labels: needs review

#17491 [59920] Fixed group_by for single and multiselct hierarchy custom field
  app/models/custom_field/order_statements.rb
  app/models/query/results/group_by.rb
  lib/api/decorators/aggregation_group.rb
  lib/api/v3/utilities/endpoints/index.rb
  spec/models/custom_field/order_statements_spec.rb
Labels: needs review
