Repository opf/openproject, pull requests merged in 2024-10, with the labels that each got.

#16862 [#56917] Increase contrast of skip button in onboarding tour
  frontend/src/app/core/setup/globals/onboarding/tours/homescreen_tour.ts
  frontend/src/global_styles/vendor/_enjoyhint.sass
Labels: bugfix, needs review

#16867 Update release teaser to version 14.6.0
  config/locales/js-en.yml
  frontend/src/app/features/homescreen/blocks/new-features.component.ts
  frontend/src/assets/images/14_5_features.png
  frontend/src/assets/images/14_6_features.svg
Labels: maintenance

#16791 [#57671] Improve display of work package and agenda titles in meetings
  modules/meeting/app/components/meeting_agenda_items/item_component/show_component.html.erb
  modules/meeting/app/components/meeting_agenda_items/item_component/show_component.sass
  modules/meeting/app/components/meeting_sections/header_component.html.erb
Labels: feature

#16880 [57978] Mobile: Scrolling quickly to the top or bottom will not show top or bottom on the first try
  frontend/src/global_styles/layout/_base.sass
Labels: bugfix, styling

#16871 [57932] Make `Mails::MailerJob` retry failed emails
  app/workers/application_job.rb
  app/workers/mails/mailer_job.rb
  app/workers/shared_job_setup.rb
  spec/workers/mails/mailer_job_spec.rb
Labels: bugfix, needs review

#16873 [#57685] Rename "My account" to "Account settings"
  config/locales/en.yml
Labels: feature, pullpreview, needs review

#16899 [57634] Theming for font color is broken in sub-project
  frontend/src/global_styles/layout/_main_menu.sass
Labels: bugfix, styling, needs review

#16902 update release notes 14.6
  docs/release-notes/14-6-0/README.md
Labels: documentation

#16872 Remove deprecated toast methods
  modules/backlogs/spec/features/resolved_status_spec.rb
  modules/backlogs/spec/support/pages/backlogs.rb
  modules/budgets/spec/support/pages/budget_form.rb
  modules/meeting/spec/features/meetings_participants_spec.rb
  modules/meeting/spec/features/structured_meetings/structured_meeting_crud_spec.rb
  modules/meeting/spec/support/pages/meetings/base.rb
  spec/features/forums/message_spec.rb
  spec/features/projects/modules_spec.rb
  spec/support/pages/admin/system_settings/page.rb
  spec/support/pages/messages/base.rb
  spec/support/pages/my/password_page.rb
  spec/support/pages/projects/settings.rb
  spec/support/pages/projects/show.rb
  spec/support/pages/types/index.rb
  spec/support/toasts/expectations.rb
Labels: needs review

#16900 [58261] Version info shows html tag
  app/helpers/application_helper.rb
  app/views/versions/show.html.erb
  frontend/src/global_styles/content/_tables.sass
Labels: bugfix

#16904 [58237] Unnecessary space to the right on certain view width
  frontend/src/global_styles/layout/_base_mobile.sass
Labels: bugfix, styling, needs review

#16912 Fix showing custom fields in a project webhook
  modules/webhooks/app/workers/attachment_webhook_job.rb
  modules/webhooks/app/workers/project_webhook_job.rb
  modules/webhooks/app/workers/represented_webhook_job.rb
  modules/webhooks/app/workers/time_entry_webhook_job.rb
  modules/webhooks/app/workers/work_package_webhook_job.rb
  modules/webhooks/spec/workers/project_webhook_job_spec.rb
Labels: bugfix

#16833 [#58114] 14.6 Documentation: Replace "Add assignee" button in Team Pl…
  docs/user-guide/team-planner/README.md
  docs/user-guide/team-planner/openproject_user_guide_teamplanner_add_assignee.png
  docs/user-guide/team-planner/openproject_user_guide_teamplanner_add_existing_task.png
  docs/user-guide/team-planner/openproject_user_guide_teamplanner_add_task.png
  docs/user-guide/team-planner/openproject_user_guide_teamplanner_add_task_select_row.png
  docs/user-guide/team-planner/openproject_user_guide_teamplanner_delete_task.png
  docs/user-guide/team-planner/openproject_user_guide_teamplanner_detailed_view_explained.png
  docs/user-guide/team-planner/openproject_user_guide_teamplanner_new_unnamed_empty.png
  docs/user-guide/team-planner/openproject_user_guide_teamplanner_overview.png
  docs/user-guide/team-planner/openproject_user_guide_teamplanner_overview_explained.png
  docs/user-guide/team-planner/openproject_user_guide_teamplanner_task_drag_handles.png
  docs/user-guide/team-planner/openproject_user_guide_teamplanner_task_info_icon.png
  docs/user-guide/team-planner/openproject_user_guide_teamplanner_task_splitscreen.png
Labels: documentation

#16840 [#58111] 14.6 Documentation: Add to connection validation that manage…
  docs/system-admin-guide/files/external-file-storages/health-status/README.md
Labels: documentation

#16851 [#58115] 14.6 Documentation: Split content of Admin/Design page into …
  docs/release-notes/14-0-0/README.md
  docs/system-admin-guide/design/README.md
  docs/system-admin-guide/design/Sys-admin-design-favicon.png
  docs/system-admin-guide/design/Sys-admin-design-upload-logo.png
  docs/system-admin-guide/design/System-admin-guide_color-theme.png
  docs/system-admin-guide/design/openproject_system_guide_design.png
  docs/system-admin-guide/design/openproject_system_guide_design_branding.png
  docs/system-admin-guide/design/openproject_system_guide_design_color_theme_navy_blue.png
  docs/system-admin-guide/design/openproject_system_guide_design_color_theme_pick.png
  docs/system-admin-guide/design/openproject_system_guide_design_custom_favicon.png
  docs/system-admin-guide/design/openproject_system_guide_design_custom_logo_uploaded.png
  docs/system-admin-guide/design/openproject_system_guide_design_interface.png
  docs/system-admin-guide/design/openproject_system_guide_design_interface_colors.png
  docs/system-admin-guide/design/openproject_system_guide_design_pdf_export_styles.png
  docs/system-admin-guide/design/openproject_system_guide_design_upload_custom_logo.png
  docs/system-admin-guide/design/system_admin_logo_updated.png
Labels: documentation

#16911 Fix incorrect capitalization on storages
  modules/storages/app/models/storages/storage.rb
  modules/storages/config/locales/en.yml
Labels: bugfix

#16839 [#57626] 14.6 Documentation: Meeting module changes https://communit…
  docs/user-guide/meetings/dynamic-meetings/README.md
  docs/user-guide/meetings/dynamic-meetings/openproject_dynamic_meetings_page_update_reload_button.png
  docs/user-guide/meetings/dynamic-meetings/openproject_dynamic_meetings_wp_agenda.png
  docs/user-guide/work-packages/add-work-packages-to-meetings/openproject_user_guide_add_wp_to_meeting.png
  docs/user-guide/work-packages/add-work-packages-to-meetings/openproject_user_guide_meeting_dialogue.png
Labels: documentation

#16855 [#58110] 14.6 Documentation: Enable a custom field for multiple proje…
  docs/system-admin-guide/custom-fields/README.md
  docs/system-admin-guide/custom-fields/custom-fields-faq/README.md
  docs/system-admin-guide/custom-fields/openproject_system_guide_new_custom_field_add_to_projects.png
  docs/system-admin-guide/custom-fields/openproject_system_guide_new_custom_field_add_to_projects_search.png
  docs/user-guide/projects/project-settings/custom-fields/README.md
  docs/user-guide/projects/project-settings/custom-fields/openproject_user_guide_projects_project_settings_custom_fields.png
Labels: documentation

#16869 [#58113] 14.6 Documentation: Progress reporting changes https://comm…
  docs/system-admin-guide/manage-work-packages/README.md
  docs/system-admin-guide/manage-work-packages/work-package-progress-tracking/README.md
  docs/system-admin-guide/manage-work-packages/work-package-progress-tracking/openproject_system_guide_progress_tracking_settings.png
  docs/system-admin-guide/manage-work-packages/work-package-progress-tracking/openproject_system_guide_progress_tracking_settings_warning_message.png
  docs/system-admin-guide/manage-work-packages/work-package-settings/README.md
  docs/system-admin-guide/manage-work-packages/work-package-settings/openproject_system_guide_work_package_settings.png
  docs/user-guide/time-and-costs/progress-tracking/README.md
  docs/user-guide/time-and-costs/progress-tracking/openproject_user_guide_percentage_complete_calculation_hint.png
  docs/user-guide/time-and-costs/progress-tracking/openproject_user_guide_percentage_complete_manual.png
Labels: documentation

#16901 [#58150] Update the post storage creation message: admins don't need to activate individual modules per project anymore
  modules/storages/app/controllers/storages/admin/automatically_managed_project_folders_controller.rb
  modules/storages/app/controllers/storages/admin/oauth_clients_controller.rb
  modules/storages/config/locales/en.yml
  modules/storages/spec/features/storages/admin/create_storage_spec.rb
Labels: bugfix, needs review

#16905 Update Glossary for 14.6
  docs/glossary/README.md
Labels: documentation

#16917 Bump primer to 0.48.0
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: maintenance

#16884 Implementation/58105 item persistence service
  app/contracts/custom_fields/hierarchy/generate_root_contract.rb
  app/contracts/custom_fields/hierarchy/insert_item_contract.rb
  app/contracts/custom_fields/hierarchy/service_initialization_contract.rb
  app/services/custom_fields/hierarchy/hierarchical_item_service.rb
  spec/contracts/custom_fields/hierarchy/generate_root_contract_spec.rb
  spec/contracts/custom_fields/hierarchy/insert_item_contract_spec.rb
  spec/contracts/custom_fields/hierarchy/service_initialization_contract_spec.rb
  spec/factories/hierarchy_item_factory.rb
  spec/services/custom_fields/hierarchy/hierarchical_item_service_spec.rb
Labels: needs review

#16920 [58267] Document hover card pattern
  app/assets/images/lookbook/hover_card.png
  lookbook/docs/patterns/25-hover-cards.md.erb
Labels: maintenance

#16924 handle missing referer
  app/menus/work_packages/menu.rb
Labels: bugfix, needs review

#16925 Render work packages menu without using request.referer
  app/controllers/work_packages/menus_controller.rb
  app/menus/work_packages/menu.rb
  app/views/work_packages/menus/_menu.html.erb
Labels: bugfix

#16908 Use the static query strategy for the implicitly created widgets
  modules/my_page/lib/my_page/grid_registration.rb
  modules/my_page/spec/factories/grid_factory.rb
  modules/my_page/spec/features/my/custom_text_spec.rb
  modules/my_page/spec/features/my/documents_spec.rb
  modules/my_page/spec/features/my/my_spent_time_widget_with_a_negative_time_zone_spec.rb
  modules/my_page/spec/features/my/news_spec.rb
  modules/my_page/spec/features/my/time_entries_current_user_spec.rb
  modules/my_page/spec/features/my/work_package_table_spec.rb
  modules/my_page/spec/features/my/work_package_watcher_widget_spec.rb
  modules/my_page/spec/requests/api/v3/grids/grids_create_form_resource_spec.rb
  spec/features/projects/favorite_spec.rb
Labels: bugfix, needs review

#16923 Add helm release trigger workflow when a docker release is done
  .github/workflows/docker.yml
Labels: operations, needs review

#16928 adding internal links to blog articles into docs
  docs/system-admin-guide/manage-work-packages/custom-actions/README.md
  docs/system-admin-guide/manage-work-packages/work-package-workflows/README.md
  docs/user-guide/meetings/dynamic-meetings/README.md
  docs/user-guide/wiki/README.md
  docs/user-guide/work-packages/baseline-comparison/README.md
  docs/user-guide/wysiwyg/README.md
Labels: documentation

#16937 [#57673] Highlight box of Storage permissions includes non relevant p…
  docs/system-admin-guide/users-permissions/roles-permissions/openproject_user_guide_file_storages_permissions.png
Labels: documentation

#16946 [55870] The Assignee drop down list in the work packages list can't show long name perfectly
  frontend/src/app/shared/components/autocompleter/user-autocompleter/user-autocompleter-template.component.html
  frontend/src/app/shared/components/autocompleter/user-autocompleter/user-autocompleter.component.sass
  frontend/src/app/shared/components/autocompleter/user-autocompleter/user-autocompleter.component.ts
Labels: bugfix, styling, needs review

#16934 [53809] Fix issues in PageHeaders & SubHeaders in the (rails) global index pages
  app/components/add_button_component.html.erb
  app/components/add_button_component.rb
  app/components/notifications/index_page_header_component.rb
  app/components/projects/index_page_header_component.rb
  app/views/activities/index.html.erb
  app/views/homescreen/index.html.erb
  app/views/news/index.html.erb
  modules/boards/app/components/boards/add_button_component.rb
  modules/boards/app/views/boards/boards/index.html.erb
  modules/boards/spec/features/support/board_index_page.rb
  modules/boards/spec/features/support/board_list_page.rb
  modules/boards/spec/features/support/board_new_page.rb
  modules/calendar/app/components/calendar/add_button_component.html.erb
  modules/calendar/app/components/calendar/add_button_component.rb
  modules/calendar/app/views/calendar/calendars/index.html.erb
  modules/calendar/spec/features/calendar_sharing_spec.rb
  modules/calendar/spec/support/pages/calendar.rb
  modules/meeting/app/components/meetings/header_component.rb
  modules/meeting/app/components/meetings/index_page_header_component.rb
  modules/meeting/app/views/meetings/new.html.erb
  modules/reporting/app/views/cost_reports/index.html.erb
  modules/team_planner/app/components/team_planner/add_button_component.rb
  modules/team_planner/app/views/team_planner/team_planner/index.html.erb
  modules/team_planner/app/views/team_planner/team_planner/overview.html.erb
  modules/team_planner/spec/features/team_planner_spec.rb
  modules/team_planner/spec/support/pages/team_planner.rb
Labels: bugfix, needs review

#16948 Remove left/right and full view on mobile notifications
  app/components/work_packages/details/tab_component.html.erb
  frontend/src/global_styles/layout/_base_mobile.sass
Labels: bugfix, needs review

#16955 [58359] Update-Warning is not readable in dark mode
  frontend/src/global_styles/layout/_warning_bar.sass
Labels: bugfix, styling, needs review

#16953 [58358] Time&Costs module does not show submenu headers in the breadcrumb
  modules/reporting/app/components/cost_reports/index_page_header_component.html.erb
  modules/reporting/app/components/cost_reports/index_page_header_component.rb
  modules/reporting/app/views/cost_reports/index.html.erb
Labels: bugfix, needs review

#16956 [58393] Meetings modules is not showing the sidebar selection in the PageHeader
  app/menus/submenu.rb
  modules/meeting/app/components/meetings/index_page_header_component.html.erb
  modules/meeting/app/components/meetings/index_page_header_component.rb
Labels: bugfix

#16952 [58280] Improve sidebar item alignment
  app/components/open_project/common/submenu_component.html.erb
  app/components/open_project/common/submenu_component.sass
  frontend/src/app/shared/components/header-project-select/header-project-select.component.sass
  frontend/src/global_styles/common/header/app-menu.sass
  frontend/src/global_styles/layout/_main_menu.sass
  frontend/src/global_styles/openproject/_variable_defaults.scss
Labels: bugfix, styling, needs review

#16950 Fix copying a version column board
  app/services/grids/copy/widgets_dependent_service.rb
  app/services/queries/copy/filters_mapper.rb
  app/services/queries/copy_service.rb
  modules/boards/app/services/boards/copy_service.rb
  modules/boards/spec/factories/board_factory.rb
  modules/boards/spec/services/copy_service_integration_spec.rb
  spec/services/queries/filters_mapper_spec.rb
Labels: bugfix

#16960 [57983] Create a migration to remove the custom design color variables that we removed from the list
  config/locales/en.yml
  db/migrate/20241015081341_remove_obsolete_design_variables.rb
  lib/open_project/custom_styles/color_themes.rb
Labels: maintenance, needs review

#16949 Add cause message for closing duplicate
  app/models/journal.rb
  app/models/journal/caused_by_duplicate_work_package_close.rb
  app/models/work_package.rb
  config/locales/en.yml
  spec/models/work_packages/work_package_duplicates_spec.rb
Labels: bugfix

#16947 Disable sorting on custom actions table
  app/components/custom_actions/table_component.rb
Labels: bugfix

#16957 [58360] Disable "is read-only" checkbox in admin statuses when "is default" is checked
  app/forms/statuses/form.rb
  app/views/statuses/edit.html.erb
  app/views/statuses/new.html.erb
  config/locales/en.yml
  frontend/src/global_styles/content/_forms.sass
  frontend/src/stimulus/controllers/dynamic/admin/statuses.controller.ts
  modules/boards/app/views/boards/boards/_form.html.erb
  modules/boards/spec/features/board_enterprise_spec.rb
  modules/boards/spec/features/boards_global_create_spec.rb
  spec/features/admin/statuses_spec.rb
  spec/support/matchers/has_enterprise_banner.rb
Labels: bugfix

#16971 Fix typos in version tags
  docs/installation-and-operations/installation/docker/README.md
Labels: needs review

#16961 Restore the form that was removed in 14.4
  app/controllers/admin/settings_controller.rb
  app/views/admin/settings/show_plugin.html.erb
  config/routes.rb
  modules/avatars/app/views/settings/_openproject_avatars.html.erb
  modules/avatars/lib/open_project/avatars/engine.rb
  modules/costs/app/views/settings/_costs.html.erb
  modules/costs/lib/costs/engine.rb
Labels: needs review

#16973 [58431] Restore images in all-in-one docker container
  .github/workflows/docker.yml
Labels: bugfix, needs review

#16987 Bug/57526 migration 20230608151123 add validity period to journals is very slow
  db/migrate/20230608151123_add_validity_period_to_journals.rb
  spec/migrations/add_validity_period_to_journals_spec.rb
Labels: needs review

#16944 [#52147] quick action table headers
  app/components/admin/custom_fields/custom_field_projects/table_component.rb
  app/components/projects/table_component.html.erb
  app/components/projects/table_component.rb
  app/helpers/projects_helper.rb
  app/helpers/sort_helper.rb
  config/locales/en.yml
  frontend/src/global_styles/content/_table.sass
  frontend/src/global_styles/primer/_overrides.sass
  frontend/src/stimulus/controllers/dynamic/filter/filters-form.controller.ts
  frontend/src/stimulus/controllers/dynamic/table-action-menu.controller.ts
  modules/storages/app/components/storages/project_storages/projects/table_component.rb
  spec/features/projects/persisted_lists_spec.rb
  spec/features/projects/projects_index_spec.rb
  spec/helpers/sort_helper_spec.rb
  spec/support/pages/projects/index.rb
Labels: feature, pullpreview

#17002 [58429] Invite user modal doesn't work on Project overview page
  frontend/src/app/features/invite-user-modal/principal/principal.component.ts
  spec/features/users/invite_user_modal/invite_user_modal_spec.rb
Labels: bugfix, needs review

#17004 [58420] Notification screen does not show submenu headers in the breadcrumb
  app/components/notifications/index_page_header_component.html.erb
  app/components/notifications/index_page_header_component.rb
  app/menus/notifications/menu.rb
Labels: bugfix

#16999 [#53767] fix: focus input field after selecting a filter
  app/views/filters/_autocomplete.html.erb
  app/views/filters/_boolean.html.erb
  app/views/filters/date/_days.html.erb
  app/views/filters/list/_select.html.erb
  frontend/src/stimulus/controllers/dynamic/filter/filters-form.controller.ts
  spec/features/projects/projects_index_spec.rb
Labels: bugfix, needs review

#17006 Sent notifications to users mentioning themselves again
  app/services/notifications/create_from_model_service.rb
  spec/services/notifications/create_from_model_service_work_package_spec.rb
Labels: needs review

#17000 [#58479] bug: adjust label "Enabled in projects" to "Projects"
  config/locales/en.yml
  docs/system-admin-guide/projects/project-attributes/README.md
  modules/storages/spec/features/storages/admin/project_storages_spec.rb
  spec/features/admin/project_custom_fields/edit_spec.rb
  spec/features/admin/project_custom_fields/project_mappings_spec.rb
Labels: bugfix

#17010 Fix capitalization on storage errors status
  modules/storages/app/components/storages/admin/side_panel/health_status_component.html.erb
  modules/storages/app/components/storages/admin/side_panel/health_status_component.rb
  modules/storages/app/components/storages/admin/side_panel_component.html.erb
  modules/storages/spec/components/storages/admin/side_panel/health_status_component_spec.rb
Labels: bugfix

#17020 [58508]Remove "Beta" label from Dark mode selection
  config/locales/en.yml
Labels: feature, needs review

#17021 Bug/58555 reminder mail not sent in case more than 15 notifications are to be reported about
  app/views/digest_mailer/work_packages.html.erb
  app/workers/mails/reminder_job.rb
  spec/mailers/digest_mailer_spec.rb
Labels: needs review

#17019 [58512] Primerised version of the basic work package hovercard
  app/components/work_packages/highlighted_date_component.html.erb
  app/components/work_packages/highlighted_date_component.rb
  app/components/work_packages/hover_card_component.html.erb
  app/components/work_packages/hover_card_component.rb
  app/components/work_packages/hover_card_component.sass
  app/components/work_packages/status_badge_component.html.erb
  app/components/work_packages/status_badge_component.rb
  frontend/src/app/shared/components/modals/preview-modal/hover-card-modal/hover-card.modal.sass
  lookbook/previews/open_project/work_packages/status_badge_component_preview.rb
Labels: feature

#17033 fix removing consecutive custom field filters in baseline
  app/models/journable/historic_active_record_relation.rb
  spec/models/journable/historic_active_record_relation_spec.rb
Labels: needs review

#17034 Memoize cfs activated in project to avoid n+1
  app/models/type/attributes.rb
Labels: needs review

#17008 [58108] Dark mode: "Custom text" widget - table cell editing UI has wrong colors
  app/views/custom_styles/_primer_color_mapping.erb
Labels: bugfix, needs review

#17039 [58414] When you click on the "To the Notification Center" button, an outline appears (update core)
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: bugfix, maintenance

#17007 [58404] Enterprise banners have excessive top-margin
  app/views/admin/settings/work_packages_general/_enterprise_feature_hint.html.erb
  app/views/types/form/_form_configuration.html.erb
  frontend/src/app/shared/components/enterprise-banner/enterprise-banner.component.html
  frontend/src/app/shared/components/enterprise-banner/enterprise-banner.component.ts
  frontend/src/global_styles/content/_toast.sass
Labels: bugfix

#17054 [58419] Time & Costs Delete button is green
  modules/reporting/lib/widget/controls/delete.rb
Labels: bugfix, styling, needs review

#17056 [58527] Calendar shortcut link broken
  frontend/src/app/core/path-helper/path-helper.service.ts
Labels: bugfix

#17044 Feature/46309 Custom field no longer added to all projects when added to a type
  app/controllers/types_controller.rb
  app/services/base_type_service.rb
  config/locales/en.yml
  spec/features/types/form_configuration_spec.rb
  spec/services/shared_type_service.rb
Labels: needs review

#17048 Remove unused sys actions
  app/controllers/sys_controller.rb
  app/views/admin/settings/repositories_settings/show.html.erb
  config/constants/settings/definition.rb
  config/locales/en.yml
  config/routes.rb
  docs/installation-and-operations/configuration/repositories/README.md
  extra/svn/reposman.rb
  modules/backlogs/app/controllers/rb_application_controller.rb
  spec/controllers/sys_controller_spec.rb
Labels: maintenance

#16982 docs/user-guide/time-and-costs/progress-tracking/README.md: fix % Com…
  docs/user-guide/time-and-costs/progress-tracking/README.md
Labels: documentation, contribution

#17064 set correct color for normal and expanded states in global search box
  frontend/src/app/core/global_search/input/global-search-input.component.sass
Labels: bugfix, needs review

#17065 [#58675] Bump gems
  Gemfile
  Gemfile.lock
  spec/requests/api/v3/authentication_spec.rb
  spec/services/api/v3/parse_query_params_service_spec.rb
Labels: maintenance, dependencies

#17059 [47777] Work package date picker: wrong spacing
  frontend/src/app/shared/components/datepicker/styles/datepicker.modal.sass
Labels: bugfix, styling

#17055 [Op#40437]: wait for activity tab comments to load
  app/components/work_packages/activities_tab/journals/index_component.html.erb
  spec/features/activities/work_package/activities_spec.rb
  spec/support/components/work_packages/activities.rb
  spec/support/components/work_packages/emoji_reactions.rb
Labels: flaky-spec

#17068 shrink an re-expand editor with content on blur/on focus as requested
  app/components/work_packages/activities_tab/journals/new_component.sass
  frontend/src/app/shared/components/editor/components/ckeditor-augmented-textarea/ckeditor-augmented-textarea.component.ts
  frontend/src/app/shared/components/editor/components/ckeditor-augmented-textarea/ckeditor-augmented-textarea.html
  frontend/src/app/shared/components/editor/components/ckeditor/op-ckeditor.component.ts
  frontend/src/stimulus/controllers/dynamic/work-packages/activities-tab/index.controller.ts
Labels: pullpreview

#17078 chore[Op#40437]: delay 0.5 in between journal polling update
  spec/features/activities/work_package/activities_spec.rb
Labels: flaky-spec

#17081 Include specs for hierarchy/items_controller
  spec/controllers/admin/custom_fields/hierarchy/items_controller_spec.rb
Labels: needs review

#17080 [#58651] Add reactions button should not be hidden when user has exhausted all reactions
  app/components/work_packages/activities_tab/journals/item_component/add_reactions.html.erb
  app/components/work_packages/activities_tab/journals/item_component/add_reactions.rb
  app/components/work_packages/activities_tab/journals/item_component/show.html.erb
  app/models/concerns/reactable.rb
  app/models/emoji_reaction.rb
  spec/features/activities/work_package/emoji_reactions_spec.rb
  spec/models/emoji_reaction_spec.rb
  spec/support/components/work_packages/emoji_reactions.rb
Labels: bugfix, needs review

#17098 Add `CAPYBARA_PUMA_THREADS` to control puma threads count
  spec/support/capybara.rb
Labels: needs review
