Repository opf/openproject, pull requests merged in 2024-08, with the labels that each got.

#16298 Remove required clause on Projects::CustomFields
  app/models/projects/custom_fields.rb
Labels: needs review

#16258 [#56633] 14.4 Documentation: Allow users to freely input % complete v…
  docs/system-admin-guide/manage-work-packages/work-package-status/README.md
  docs/system-admin-guide/manage-work-packages/work-package-status/openproject_system_guide_create_new_wp_status.png
  docs/system-admin-guide/manage-work-packages/work-package-status/openproject_system_guide_create_wp_status_overview.png
  docs/system-admin-guide/manage-work-packages/work-package-status/openproject_system_guide_edit_new_wp_status.png
Labels: documentation

#16313 Change 2fa administration page title to match with the sidebar
  modules/two_factor_authentication/app/views/two_factor_authentication/settings.html.erb
Labels: bugfix, needs review

#16312 [56655] Close button of onboarding tour is hard to see with a bright primary color
  frontend/src/global_styles/vendor/_enjoyhint.sass
Labels: bugfix, styling

#16283 [56761] Dark mode is not applied to drop downs in cost reports
  frontend/src/global_styles/content/_autocomplete.sass
  frontend/src/global_styles/content/_forms.sass
  frontend/src/global_styles/openproject/_forms.sass
Labels: bugfix, styling, tinyfix

#16320 [56920] Backlogs and GitHub have unnecessarily nested menu nodes
  config/initializers/menus.rb
  modules/backlogs/app/controllers/backlogs_settings_controller.rb
  modules/backlogs/app/views/backlogs_settings/show.html.erb
  modules/github_integration/app/controllers/deploy_targets_controller.rb
  modules/github_integration/app/views/deploy_targets/index.html.erb
  modules/github_integration/app/views/deploy_targets/new.html.erb
  modules/github_integration/lib/open_project/github_integration/engine.rb
Labels: bugfix

#16319 Fix wiki pages being cut off with new content layout
  frontend/src/global_styles/layout/_print.sass
Labels: bugfix, needs review

#16321 [#56634] 14.4 Documentation: OpenProject Dark Mode https://community…
  docs/getting-started/my-account/README.md
  docs/getting-started/my-account/openproject_my_account_dark_mode.png
  docs/getting-started/my-account/openproject_my_account_high_contrast_mode.png
  docs/getting-started/my-account/openproject_my_account_page_settings.png
  docs/getting-started/my-account/openproject_my_account_profile.png
  docs/getting-started/my-account/openproject_open_my_account_page.png
Labels: documentation

#16252 [#56253] Correct missing filter value in notification translation string
  config/locales/js-en.yml
Labels: bugfix

#16301 Update docs with project attributes permissions description
  docs/user-guide/project-overview/README.md
  docs/user-guide/projects/project-settings/project-attributes/README.md
Labels: documentation, needs review

#16328 [54450] Sort order of wiki pages in main menu wrong
  lib/redmine/menu_manager/wiki_menu_helper.rb
  spec/requests/wiki/menu_items_order_spec.rb
Labels: bugfix, needs review

#16326 Allow lookup of already removed journal class
  db/migrate/20220818074159_fix_deleted_data_journals.rb
Labels: bugfix, needs review

#16339 [#56986] Member user role's seed data is incorrect
  modules/boards/app/seeders/common.yml
Labels: needs review

#16325 Rewrite migration using plain SQL
  db/migrate/20211117195121_remove_destroyed_help_texts.rb
Labels: bugfix, needs review

#16177 [#56235] Send invitation button broken when user tries to reinvite themselves
  app/views/users/_toolbar.html.erb
Labels: bugfix, contribution

#16336 [52890] Truncaded custom fields in work package table (Browser: Edge)
  frontend/src/global_styles/content/work_packages/_table_content.sass
Labels: bugfix

#16331 Set verify_partial_doubles=true
  .rubocop.yml
  modules/auth_plugins/spec/requests/auth_plugins_spec.rb
  modules/auth_plugins/spec/views/base.html.erb_spec.rb
  modules/backlogs/spec/controllers/backlogs_settings_controller_spec.rb
  modules/bim/spec/views/bim/ifc_models/ifc_models/index.html.erb_spec.rb
  modules/costs/spec/lib/api/v3/costs_api_user_permission_check_spec.rb
  modules/costs/spec/models/queries/time_entries/filters/activity_filter_spec.rb
  modules/two_factor_authentication/spec/controllers/two_factor_authentication/authentication_controller_spec.rb
  spec/components/members/delete_member_dialog_component_spec.rb
  spec/components/members/delete_work_package_shares_dialog_component_spec.rb
  spec/controllers/account_controller_spec.rb
  spec/controllers/concerns/omniauth_login_spec.rb
  spec/controllers/custom_styles_controller_spec.rb
  spec/helpers/settings_helper_spec.rb
  spec/lib/acts_as_list/acts_as_list_patch_spec.rb
  spec/lib/api/decorators/link_object_spec.rb
  spec/lib/api/v3/groups/group_collection_representer_spec.rb
  spec/lib/api/v3/memberships/membership_collection_representer_spec.rb
  spec/lib/api/v3/notifications/notification_collection_representer_spec.rb
  spec/lib/api/v3/placeholder_users/placeholder_user_collection_representer_spec.rb
  spec/lib/api/v3/relations/relation_paginated_collection_representer_spec.rb
  spec/lib/api/v3/shares/share_collection_representer_spec.rb
  spec/lib/api/v3/users/user_collection_representer_spec.rb
  spec/lib/api/v3/work_packages/work_package_at_timestamp_representer_rendering_spec.rb
  spec/lib/api/v3/work_packages/work_package_collection_representer_spec.rb
  spec/lib/api/v3/work_packages/work_package_representer_spec.rb
  spec/lib/custom_field_form_builder_spec.rb
  spec/lib/open_project/text_formatting/markdown/child_pages_macro_spec.rb
  spec/mailers/digest_mailer_spec.rb
  spec/migrations/fix_untranslated_work_package_roles_spec.rb
  spec/models/custom_actions/actions/custom_field_spec.rb
  spec/models/queries/work_packages/filter/principal_loader_spec.rb
  spec/models/queries/work_packages/filter/project_filter_spec.rb
  spec/rspec_helper.rb
  spec/services/oauth_clients/connection_manager_spec.rb
  spec/services/projects/delete_service_spec.rb
  spec/services/projects/set_attributes_service_spec.rb
  spec/services/users/login_service_spec.rb
  spec/services/work_packages/set_attributes_service_spec.rb
  spec/support/api/v3/work_packages/work_package_representer_eager_loading.rb
  spec/support/shared/with_direct_uploads.rb
  spec/support_spec/mocked_permission_helper_spec.rb
  spec/views/layouts/admin.html.erb_spec.rb
  spec/views/layouts/base.html.erb_spec.rb
  spec/views/users/edit.html.erb_spec.rb
  spec/views/users/index.html.erb_spec.rb
  spec/views/wiki/new.html.erb_spec.rb
  spec/workers/mails/shared/member_job.rb
  spec/workers/mails/shared/watcher_job.rb
  spec/workers/mails/work_package_shared_job_spec.rb
Labels: maintenance, needs review

#16332 [#56641] 14.4 Documentation: Meetings module changes https://communi…
  docs/user-guide/meetings/dynamic-meetings/README.md
  docs/user-guide/meetings/dynamic-meetings/openproject_dynamic_meetings_wp_agenda.png
  docs/user-guide/work-packages/add-work-packages-to-meetings/README.md
  docs/user-guide/work-packages/add-work-packages-to-meetings/openproject_user_guide_add_wp_to_meeting.png
Labels: documentation

#16329 Scroll to active project list item when changing facet
  frontend/src/app/shared/components/header-project-select/header-project-select.component.html
  frontend/src/app/shared/components/header-project-select/header-project-select.component.ts
Labels: bugfix, needs review

#16311 [56866] Change the styling of the split screen layout in the notification center
  app/components/work_packages/details/tab_component.html.erb
  app/components/work_packages/details/tab_component.sass
  app/components/work_packages/split_view_component.sass
  frontend/src/app/features/in-app-notifications/center/in-app-notification-center.component.sass
  frontend/src/app/features/in-app-notifications/entry/in-app-notification-entry.component.sass
  frontend/src/global_styles/layout/_base.sass
  frontend/src/global_styles/layout/work_packages/_details_view.sass
  frontend/src/global_styles/openproject/_mixins.sass
  frontend/src/global_styles/openproject/_notifications.sass
  frontend/src/global_styles/primer/_overrides.sass
Labels: feature, pullpreview, needs review

#16337 [#56158] 14.4 Documentation: Require explicit type selection on proje…
  docs/user-guide/work-packages/copy-move-delete/README.md
  docs/user-guide/work-packages/copy-move-delete/openproject_user_guide_copy_move_delete_warning_message_missing_wp_type.png
Labels: documentation

#16338 [#56995] 14.4 Documentation: Color of text and icons of primary butto…
  docs/system-admin-guide/design/README.md
Labels: documentation

#16352 Refactor: move allow to before block
  spec/controllers/concerns/omniauth_login_spec.rb
Labels: maintenance, ruby, needs review

#16324 Allow webauthn_challenge to be called
  modules/two_factor_authentication/app/controllers/two_factor_authentication/forced_registration/two_factor_devices_controller.rb
Labels: bugfix, needs review

#16341 MIME prefix constraint removed
  modules/bim/app/services/bim/bcf/viewpoints/set_attributes_service.rb
Labels: contribution

#16348 Bump primer to 0.41.0 and octicons to 19.18.0
  Gemfile
  Gemfile.lock
  app/components/projects/index_page_header_component.html.erb
  app/components/projects/index_page_header_component.rb
  app/forms/queries/projects/form.rb
  frontend/package-lock.json
  frontend/package.json
  modules/meeting/app/components/meetings/header_component.html.erb
  modules/meeting/app/components/meetings/header_component.rb
  modules/meeting/app/forms/meeting/title.rb
Labels: maintenance, needs review

#16362 [#40942] documented API behaviour for relation creation
  docs/api/apiv3/components/examples/relation_collection_response.yml
  docs/api/apiv3/components/examples/relation_create_request.yml
  docs/api/apiv3/components/examples/relation_response.yml
  docs/api/apiv3/components/examples/relation_update_request.yml
  docs/api/apiv3/components/schemas/relation_collection_model.yml
  docs/api/apiv3/components/schemas/relation_read_model.yml
  docs/api/apiv3/components/schemas/relation_write_model.yml
  docs/api/apiv3/openapi-spec.yml
  docs/api/apiv3/paths/relation.yml
  docs/api/apiv3/paths/work_package_relations.yml
  lib/api/v3/work_packages/work_package_relations_api.rb
  spec/requests/api/v3/relations_resource_spec.rb
Labels: documentation

#16359 [22517] PDF export of meeting agenda and meeting
  frontend/src/app/shared/components/attachments/attachment-list/attachment-list-item.component.html
  frontend/src/app/shared/components/attachments/attachments.component.html
  frontend/src/global_styles/layout/_print.sass
  modules/meeting/app/components/_index.sass
  modules/meeting/app/components/meeting_agenda_items/item_component/show_component.html.erb
  modules/meeting/app/components/meeting_agenda_items/new_button_component.html.erb
  modules/meeting/app/components/meeting_sections/header_component.html.erb
  modules/meeting/app/components/meeting_sections/show_component.html.erb
  modules/meeting/app/components/meetings/header_component.html.erb
  modules/meeting/app/components/meetings/side_panel/attachments_component.html.erb
  modules/meeting/app/components/meetings/side_panel/details_component.html.erb
  modules/meeting/app/components/meetings/side_panel/participants_component.html.erb
  modules/meeting/app/components/meetings/side_panel/participants_component.sass
  modules/meeting/app/components/meetings/side_panel/state_component.html.erb
  modules/meeting/app/components/meetings/side_panel_component.html.erb
Labels: feature

#16299 Add draft for 14.4 release notes
  docs/release-notes/14-4-0/Custom_field__long_text__changed.png
  docs/release-notes/14-4-0/README.md
  docs/release-notes/14-4-0/openproject-14-4-copy-link.png
  docs/release-notes/14-4-0/openproject-14-4-dark-mode.png
  docs/release-notes/14-4-0/openproject-14-4-project-attributes-permissions-highlighted.png
  docs/release-notes/14-4-0/openproject-14-4-project-lists-filter.png
  docs/release-notes/14-4-0/openproject-14-4-status-percentage-complete.png
Labels: documentation

#16365 [#56284] Implement "Edit project folder" button in context menu
  modules/storages/app/components/storages/admin/storages/projects_storage_form_modal_component.html.erb
  modules/storages/app/components/storages/admin/storages/projects_storage_form_modal_component.rb
  modules/storages/app/components/storages/admin/storages/projects_storage_modal_component.html.erb
  modules/storages/app/components/storages/admin/storages/projects_storage_modal_component.rb
  modules/storages/app/components/storages/project_storages/projects/row_component.rb
  modules/storages/app/controllers/storages/admin/storages/project_storages_controller.rb
  modules/storages/app/forms/storages/admin/project_storages/project_folder_mode_form.rb
  modules/storages/config/locales/en.yml
  modules/storages/config/routes.rb
  modules/storages/spec/features/storages/admin/project_storages_spec.rb
Labels: needs review

#16373 [56157] Loading gif in notification center and some images have white background in dark mode
  app/assets/images/installation_alerts.svg
  app/assets/images/professional_support.svg
  app/assets/images/security_alerts.jpg
  app/assets/images/security_alerts.svg
  app/assets/images/system_maintenance.jpg
  app/views/enterprises/_info.html.erb
  frontend/src/app/features/in-app-notifications/center/in-app-notification-center.component.ts
  frontend/src/app/shared/components/colors/colors.service.ts
  frontend/src/assets/images/notification-center/notification_loading_dark.gif
  frontend/src/assets/images/notification-center/notification_loading_light.gif
  frontend/src/global_styles/content/_info_boxes.sass
Labels: bugfix, styling

#16360 [56921] Description text shown above the editor toolbar
  frontend/src/global_styles/content/work_packages/new/_overridden_description_wiki.sass
Labels: bugfix, needs review

#16375 Remove EmptyStateComponent for notification center
  frontend/src/app/features/in-app-notifications/center/empty-state/empty-state.component.html
  frontend/src/app/features/in-app-notifications/center/empty-state/empty-state.component.sass
  frontend/src/app/features/in-app-notifications/center/empty-state/empty-state.component.ts
  frontend/src/app/features/in-app-notifications/in-app-notifications.module.ts
Labels: maintenance

#16380 [57008] Open Project Darkmode: pressing buttons / flash colour gets too bright
  app/views/custom_styles/_primer_color_mapping.erb
  frontend/src/global_styles/content/_editable_toolbar.sass
  frontend/src/global_styles/layout/_toolbar.sass
  frontend/src/global_styles/openproject/_variable_defaults.scss
Labels: bugfix, needs review

#16382 [57095] Remaining bugs in dark mode
  app/views/custom_styles/_primer_color_mapping.erb
  frontend/src/global_styles/content/_forms.sass
  frontend/src/global_styles/content/_types_form_configuration.sass
  frontend/src/global_styles/content/modules/_2fa.sass
  frontend/src/global_styles/content/work_packages/inplace_editing/_display_fields.sass
  frontend/src/global_styles/content/work_packages/inplace_editing/_textareas.sass
  frontend/src/global_styles/content/work_packages/single_view/_work_package_comment.sass
  frontend/src/global_styles/openproject/_variable_defaults.scss
Labels: bugfix, needs review

#16393 [57027] Avoid empty first page when printing in Firefox
  frontend/src/global_styles/layout/_print.sass
Labels: bugfix, needs review

#16395 Update migration to use raw SQL rather than AR models
  db/migrate/20240808125617_populate_remote_identities.rb
Labels: needs review

#16396 [57097] Notification center split screen is wider than it previously was
  app/components/work_packages/split_view_component.sass
Labels: bugfix, styling, needs review

#16399 [57031] Some status indicators are missing a border
  app/helpers/colors_helper.rb
Labels: bugfix, styling

#16400 Fix 2FA download link
  frontend/src/app/core/setup/globals/global-listeners/link-hijacking.ts
Labels: bugfix, needs review

#16402 Fix merge conflict
  app/services/remote_identities/create_service.rb
  spec/services/oauth_clients/connection_manager_spec.rb
Labels: needs review

#16398 [57003] OpenProject Dark Mode: selection colour of table rows
  frontend/src/global_styles/layout/work_packages/_table.sass
Labels: bugfix, needs review

#16407 [57154] Project filter in notification center is not correctly highlighted
  app/menus/notifications/menu.rb
Labels: bugfix

#16403 [57015] Unable to mark all project specific notifications as read
  app/controllers/notifications_controller.rb
  spec/features/notifications/notification_center/notification_center_spec.rb
Labels: bugfix, needs review

#16374 update release notes
  docs/release-notes/14-4-0/README.md
  docs/release-notes/14-4-0/openproject_file_storages_recheck_connection_nextcloud.png
Labels: documentation

#16409 [#57059] Confusing UX when cancelling editing Nextcloud OAuth settings
  modules/storages/app/components/storages/admin/oauth_client_info_component.rb
  modules/storages/spec/components/storages/admin/oauth_client_info_component_spec.rb
Labels: bugfix, needs review

#16418 update glossary
  docs/glossary/README.md
Labels: documentation

#16384 Fix preview of SplitViewComponent
  app/components/work_packages/details/tab_component.html.erb
  app/components/work_packages/split_view_component.html.erb
  config/routes.rb
  frontend/src/global_styles/layout/_viewcomponent_previews.sass
  lookbook/previews/open_project/work_packages/split_view_component_preview.rb
  spec/components/previews/work_packages/split_view_component_preview.rb
  spec/components/work_packages/split_view_component_spec.rb
Labels: maintenance, needs review

#16413 [#55088] Gantt PDF export shows superfluous hyphen (-) when dates are missing
  app/models/work_package/pdf_export/gantt/gantt_builder.rb
  config/locales/en.yml
  spec/models/work_packages/pdf_export/work_package_list_to_pdf_gantt_spec.rb
Labels: needs review

#16426 Fix failing test missing the remote_identity data
  modules/storages/spec/features/storages/admin/project_storages_spec.rb
Labels: needs review

#16389 [#57038] Trigger all necessary hooks when a project is removed from a storage
  modules/storages/app/controllers/storages/admin/storages/project_storages_controller.rb
  modules/storages/config/locales/en.yml
  modules/storages/spec/features/storages/admin/project_storages_spec.rb
  spec/support/retryable.rb
Labels: needs review

#16427 Cleanup after Remote Identity introduction
  db/migrate/20240813131647_drop_origin_user_id_from_oauth_client_tokens.rb
  modules/storages/app/services/storages/nextcloud_group_folder_properties_sync_service.rb
  modules/storages/app/services/storages/one_drive_managed_folder_sync_service.rb
  modules/storages/spec/factories/storage_factory.rb
  modules/storages/spec/lib/api/v3/storages/storages_representer_parsing_spec.rb
Labels: maintenance

#16441 Filter the project storage members to show only users
  modules/storages/app/controllers/storages/project_settings/project_storage_members_controller.rb
  modules/storages/app/views/storages/project_settings/project_storage_members/index.html.erb
  modules/storages/spec/features/view_project_storage_members_spec.rb
Labels: bugfix, needs review

#16444 New PR templates that differentiate between bug and feature
  .github/PULL_REQUEST_TEMPLATE/bug_pull_request_template.md
  .github/PULL_REQUEST_TEMPLATE/feature_pull_request_template.md
Labels: maintenance

#16438 change the filtering on the visible time entries to be done in the join
  app/models/work_packages/scopes/include_spent_time.rb
Labels: needs review

#16430 [#57030] Fix storage delete button in "Enabled in projects" tab
  modules/storages/app/components/storages/admin/edit_form_header_component.html.erb
  modules/storages/app/views/storages/admin/storages/edit.html.erb
  modules/storages/spec/features/storages/admin/project_storages_spec.rb
Labels: needs review

#16422 Warn if trying to migrate WikiContent broken journals
  db/migrate/20220818074159_fix_deleted_data_journals.rb
Labels: bugfix, needs review

#16437 [56919] Make notification center split screen resizable
  app/components/work_packages/split_view_component.html.erb
  frontend/src/app/features/work-packages/routing/wp-split-view/wp-split-view-entry.component.ts
  frontend/src/app/features/work-packages/routing/wp-split-view/wp-split-view.component.ts
  frontend/src/app/features/work-packages/routing/wp-split-view/wp-split-view.html
  frontend/src/app/shared/components/resizer/resizer/wp-resizer.component.ts
Labels: needs review

#16446 [57103] OpenProject Dark Mode: CKEditor using too light colours e.g. for pressed buttons
  app/views/custom_styles/_primer_color_mapping.erb
Labels: bugfix, needs review

#16454 Rename work package actions
  config/locales/js-en.yml
  frontend/src/app/shared/components/op-context-menu/wp-context-menu/wp-static-context-menu-actions.ts
  spec/features/work_packages/bulk/copy_work_package_spec.rb
  spec/features/work_packages/bulk/move_work_package_spec.rb
  spec/features/work_packages/copy_spec.rb
  spec/features/work_packages/details/context_menu_spec.rb
  spec/features/work_packages/table/context_menu/context_menu_shared_examples.rb
Labels: feature

#16447 Don't access #project on widget migration
  modules/overviews/db/migrate/20190826083604_my_project_page_to_grid.rb
Labels: bugfix

#16449 [#56440] Add 🔍 to projects autocompleter
  app/components/_index.sass
  app/components/settings/project_custom_fields/project_custom_field_mapping/new_project_mapping_component.sass
  app/forms/projects/custom_fields/custom_field_mapping_form.rb
  frontend/src/global_styles/content/_index.sass
  frontend/src/global_styles/content/_projects_autocomplete_with_search_icon.sass
  lib/primer/open_project/forms/autocompleter.html.erb
  lookbook/docs/patterns/03-autocompleters.md.erb
  lookbook/previews/open_project/common/autocomplete_preview.rb
  lookbook/previews/open_project/common/autocomplete_preview/project_with_search_icon.html.erb
  modules/storages/app/forms/storages/admin/storages/add_projects_autocompleter_form.rb
Labels: needs review

#16350 2FA: Disable writing of ENV enforced settings
  modules/two_factor_authentication/app/controllers/two_factor_authentication/two_factor_settings_controller.rb
  modules/two_factor_authentication/app/views/two_factor_authentication/settings.html.erb
  modules/two_factor_authentication/config/locales/en.yml
Labels: bugfix

#16465 Show meetings in user's correct timezone
  frontend/src/app/features/calendar/wp-calendar/wp-calendar.component.ts
  modules/calendar/spec/features/calendar_widget_spec.rb
  spec/support/browsers/chrome.rb
Labels: bugfix

#16421 Sort meetings by start_time ASC in work package tab
  .rubocop.yml
  modules/meeting/app/forms/meeting_agenda_item/meeting_form.rb
Labels: bugfix, needs review

#16463 [57198] Time and cost report : text of unit cost activity is displayed with html tag <i>
  modules/reporting/app/helpers/reporting_helper.rb
Labels: bugfix, needs review

#16466 [57033] New status field rendering not vertically aligned correctly in notification center
  frontend/src/app/features/in-app-notifications/entry/in-app-notification-entry.component.sass
  frontend/src/app/features/in-app-notifications/entry/status/in-app-notification-status.component.sass
Labels: bugfix, styling

#16471 [57151] OpenProject Dark Mode: diff view for description (and large text fields) not matching
  frontend/src/global_styles/content/_diff.sass
Labels: bugfix, styling

#16473 [57093] Default user avatar is too big for work package table rendering (Safari)
  frontend/src/global_styles/content/_avatar.sass
Labels: bugfix, styling, needs review

#16472 Show only updated time, not actor if first notification is date alert
  config/locales/js-en.yml
  frontend/src/app/features/in-app-notifications/entry/actors-line/in-app-notification-actors-line.component.ts
  spec/features/notifications/notification_center/notification_center_date_alert_mention_spec.rb
Labels: bugfix, needs review

#16474 [57208] Missing space between avatar and name on Project settings file page
  app/components/admin/attachments_settings_header_component.html.erb
  modules/storages/app/components/storages/project_storages/members/row_component.rb
  modules/storages/app/components/storages/project_storages/row_component.rb
  modules/storages/spec/features/view_project_storage_members_spec.rb
Labels: bugfix, needs review

#15398 feat: Add support for Cloudflare Turnstile
  docs/system-admin-guide/authentication/recaptcha/README.md
  modules/recaptcha/app/controllers/recaptcha/request_controller.rb
  modules/recaptcha/app/helpers/recaptcha_helper.rb
  modules/recaptcha/app/views/recaptcha/admin/show.html.erb
  modules/recaptcha/app/views/recaptcha/request/perform.html.erb
  modules/recaptcha/config/locales/en.yml
  modules/recaptcha/lib/open_project/recaptcha.rb
  modules/recaptcha/lib/open_project/recaptcha/configuration.rb
  modules/recaptcha/lib/open_project/recaptcha/engine.rb
Labels: contribution

#16464 [57209] Attachment headlines are semi-transparent and overlapped by content
  frontend/src/global_styles/content/work_packages/tabs/_tab_content.sass
Labels: bugfix, styling, needs review

#16478 Replace inconsistent i18n-tasks spec with workflow
  .github/workflows/i18n-tasks.yml
  spec/i18n_spec.rb
Labels: maintenance, needs review

#16470 Bug/57316 robots follow action links unnecessarily
  app/components/projects/configure_view_modal_component.rb
  app/components/projects/delete_list_modal_component.rb
  app/components/projects/export_list_modal_component.rb
  app/components/projects/index_page_header_component.html.erb
  app/controllers/projects/queries_controller.rb
  app/controllers/projects_controller.rb
  app/models/project.rb
  config/routes.rb
  lookbook/docs/patterns/05-dialogs.md.erb
  spec/routing/project_queries_routing_spec.rb
  spec/routing/project_routing_spec.rb
Labels: needs review

#16494 [#57361] 14.4.0 release notes repeat itself
  docs/getting-started/my-account/README.md
  docs/release-notes/14-4-0/README.md
  docs/system-admin-guide/system-settings/README.md
Labels: documentation

#16493 [#57028] Fix Removal of a project leaves some js components unusable
  modules/storages/app/components/storages/project_storages/destroy_confirmation_dialog_component.html.erb
Labels: needs review

#16483 [57341] Full height split screen
  app/components/work_packages/details/tab_component.sass
  app/components/work_packages/split_view_component.sass
  frontend/src/global_styles/common/header/app-header.sass
  frontend/src/global_styles/layout/_base.sass
  frontend/src/global_styles/layout/_base_mobile.sass
  frontend/src/global_styles/layout/work_packages/_details_view.sass
  frontend/src/global_styles/openproject/_mixins.sass
  frontend/src/global_styles/openproject/_notifications.sass
  frontend/src/global_styles/primer/_overrides.sass
Labels: feature, pullpreview

#16485 [#57298] Custom field filter in project list causes internal server error
  app/models/queries/filters/shared/custom_fields/base.rb
  app/models/queries/projects/filters/custom_field_context.rb
  app/models/queries/work_packages/filter/custom_field_context.rb
  spec/features/projects/persisted_lists_spec.rb
  spec/models/queries/projects/filters/custom_field_filter_spec.rb
Labels: needs review

#16492 remove explicit project column from notifications
  app/contracts/notifications/create_contract.rb
  app/mailers/digest_mailer.rb
  app/models/notification.rb
  app/models/queries/notifications/filters/project_filter.rb
  app/models/queries/notifications/group_bys/group_by_project.rb
  app/models/queries/notifications/orders/project_order.rb
  app/services/notifications/create_from_model_service.rb
  app/services/notifications/set_attributes_service.rb
  app/workers/notifications/create_date_alerts_notifications_job/service.rb
  db/migrate/20240820123011_remove_project_from_notification.rb
  lib/api/v3/notifications/notification_eager_loading_wrapper.rb
  lib/api/v3/notifications/notification_representer.rb
  spec/contracts/notifications/create_contract_spec.rb
  spec/factories/notification_factory.rb
  spec/features/notifications/navigation_spec.rb
  spec/features/notifications/notification_center/notification_center_date_alert_mention_spec.rb
  spec/features/notifications/notification_center/notification_center_date_alerts_spec.rb
  spec/features/notifications/notification_center/notification_center_sidemenu_spec.rb
  spec/features/notifications/notification_center/notification_center_spec.rb
  spec/features/notifications/notification_center/split_screen_spec.rb
  spec/features/work_packages/tabs/activity_notifications_spec.rb
  spec/lib/api/v3/notifications/notification_representer_rendering_spec.rb
  spec/mailers/digest_mailer_spec.rb
  spec/models/journal_spec.rb
  spec/models/notifications/scopes/visible_spec.rb
  spec/models/queries/notifications/notification_query_spec.rb
  spec/requests/api/v3/notifications/bulk_read_ian_resource_spec.rb
  spec/requests/api/v3/notifications/bulk_unread_ian_resource_spec.rb
  spec/requests/api/v3/notifications/details_resource_spec.rb
  spec/requests/api/v3/notifications/index_resource_spec.rb
  spec/requests/api/v3/notifications/read_ian_resource_spec.rb
  spec/requests/api/v3/notifications/show_resource_spec.rb
  spec/services/notifications/create_from_journal_job_shared.rb
  spec/services/notifications/create_service_intergration_spec.rb
  spec/services/notifications/set_attributes_service_spec.rb
  spec/services/work_packages/delete_service_integration_spec.rb
Labels: needs review

#16506 Update system admin guie
  docs/system-admin-guide/backup/README.md
  docs/system-admin-guide/backup/administration-backup-2034314.png
  docs/system-admin-guide/backup/backup-code.png
  docs/system-admin-guide/backup/create-backup-token.png
  docs/system-admin-guide/backup/openproject_system_guide_backup_tocken.png
  docs/system-admin-guide/backup/openproject_system_guide_backup_token_confirm.png
  docs/system-admin-guide/backup/openproject_system_guide_backup_token_success.png
  docs/system-admin-guide/design/README.md
Labels: documentation

#16502 Use #subclasses instead of constantize for enumeration_class
  app/controllers/enumerations_controller.rb
  app/models/concerns/subclass_registry.rb
  app/models/enumeration.rb
  config/initializers/sti_eager_load.rb
  modules/costs/lib/costs/engine.rb
  modules/documents/lib/open_project/documents/engine.rb
Labels: maintenance, needs review

#16508 Fix meeting participant counter
  modules/meeting/app/components/meetings/side_panel/attachments_component.html.erb
  modules/meeting/app/components/meetings/side_panel/participants_component.html.erb
  modules/meeting/spec/features/structured_meetings/structured_meeting_participant_spec.rb
Labels: bugfix

#16507 Bump primer to 0.43.0
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: maintenance

#16504 [56918] Counter in files tab of new split screen is not updated correctly
  frontend/src/app/shared/components/attachments/attachment-list/attachment-list.component.ts
Labels: bugfix, needs review

#16246 Project index turbofy
  app/components/filter/filter_button_component.html.erb
  app/components/filter/filter_button_component.rb
  app/components/projects/configure_view_modal_component.html.erb
  app/components/projects/index_page_header_component.html.erb
  app/components/projects/index_page_header_component.rb
  app/components/projects/index_sub_header_component.html.erb
  app/components/projects/index_sub_header_component.rb
  app/components/projects/projects_filters_component.html.erb
  app/components/projects/projects_filters_component.rb
  app/components/projects/table_component.html.erb
  app/components/projects/table_component.rb
  app/controllers/projects/queries_controller.rb
  app/controllers/projects_controller.rb
  app/helpers/pagination_helper.rb
  app/helpers/sort_helper.rb
  app/views/filters/_autocomplete.html.erb
  app/views/layouts/base.html.erb
  frontend/src/app/shared/components/autocompleter/draggable-autocomplete/draggable-autocomplete.component.ts
  frontend/src/stimulus/controllers/dynamic/filter/filters-form.controller.ts
  spec/features/projects/export_spec.rb
  spec/features/projects/persisted_lists_sharing_spec.rb
  spec/features/projects/persisted_lists_spec.rb
  spec/features/projects/projects_index_spec.rb
  spec/helpers/sort_helper_spec.rb
  spec/support/pages/projects/index.rb
Labels: feature

#16517 Merge release/14.4 into dev
  config/locales/crowdin/js-ro.yml
  config/locales/crowdin/ro.yml
  modules/reporting/config/locales/crowdin/ro.yml
  modules/two_factor_authentication/config/locales/crowdin/ro.yml
Labels: create-merge-release-into-dev-pr

#16520 [57399] Label name is showing when meeting has no participants
  app/components/op_primer/expandable_list_component.html.erb
Labels: bugfix, needs review

#16522 Documentation/update ruby version docs
  docs/development/development-environment-osx/README.md
  docs/development/development-environment-ubuntu/README.md
  docs/installation-and-operations/installation/manual/README.md
Labels: documentation

#16525 [#57400] Delete wiki-Macro "include a wiki page in antother wiki" men…
  docs/user-guide/wiki/wiki-faq/README.md
Labels: documentation

#16523 [57096] Add hover effect for read notifications
  frontend/src/app/features/in-app-notifications/entry/in-app-notification-entry.component.sass
Labels: bugfix, styling, needs review

#16526 [57282] OpenProject Dark Mode: reiterate hover/active button colour
  frontend/src/global_styles/content/_buttons.sass
Labels: bugfix, styling, needs review

#16499 Fix copy project background color in dark mode
  frontend/src/app/shared/components/forms/highlighted-input.sass
  frontend/src/app/shared/components/option-list/option-list.sass
Labels: contribution

#16539 [57258] Indicate which fields are automatically derived and why in progress pop over
  app/components/work_packages/progress/work_based/modal_body_component.html.erb
  app/contracts/work_packages/base_contract.rb
  app/forms/work_packages/progress_form.rb
  app/models/work_package.rb
  app/services/duration_converter.rb
  app/services/work_packages/set_attributes_service/derive_progress_values_base.rb
  app/services/work_packages/set_attributes_service/derive_progress_values_status_based.rb
  app/services/work_packages/set_attributes_service/derive_progress_values_work_based.rb
  config/locales/en.yml
  spec/components/work_packages/progress/work_based/modal_body_component_spec.rb
  spec/contracts/work_packages/base_contract_spec.rb
  spec/services/duration_converter_spec.rb
  spec/services/work_packages/set_attributes_service/derive_progress_values_status_based_spec.rb
  spec/services/work_packages/set_attributes_service/derive_progress_values_work_based_spec.rb
  spec/services/work_packages/set_attributes_service/shared_examples.rb
Labels: feature, pullpreview

#16521 [57391] New split screen: fixed width breaks layout when resizing the screen
  app/components/work_packages/split_view_component.html.erb
  app/components/work_packages/split_view_component.sass
  frontend/src/app/features/work-packages/components/wp-table/wp-table.component.html
  frontend/src/app/features/work-packages/routing/wp-full-view/wp-full-view.html
  frontend/src/app/features/work-packages/routing/wp-split-view/wp-split-view-entry.component.ts
  frontend/src/app/features/work-packages/routing/wp-split-view/wp-split-view.component.ts
  frontend/src/app/features/work-packages/routing/wp-split-view/wp-split-view.html
  frontend/src/app/shared/components/resizer/resizer.component.ts
  frontend/src/app/shared/components/resizer/resizer/wp-resizer.component.ts
  frontend/src/global_styles/layout/_base.sass
  frontend/src/global_styles/layout/work_packages/_details_view.sass
  frontend/src/global_styles/layout/work_packages/_full_view.sass
  frontend/src/global_styles/layout/work_packages/_table.sass
  frontend/src/global_styles/openproject/_variable_defaults.scss
  modules/gantt/spec/features/timeline/timeline_dates_spec.rb
Labels: bugfix, styling

#16544 Remove duplicate instructions if ldap and identity provider
  app/views/my/account.html.erb
Labels: bugfix

#16547 Merge release/14.4 into dev
  docs/development/design-system/README.md
  docs/release-notes/14-4-1/README.md
  docs/release-notes/README.md
Labels: create-merge-release-into-dev-pr

#16551 Documentation: cleanup dev sections
  docs/README.md
  docs/development/README.md
  docs/development/concepts/README.md
  docs/development/concepts/application-architecture/README.md
  docs/development/create-openproject-plugin/README.md
  docs/development/development-environment/README.md
  docs/development/development-environment/docker-macos/README.md
  docs/development/development-environment/docker/README.md
  docs/development/development-environment/linux/README.md
  docs/development/development-environment/macos/README.md
  docs/development/environments/README.md
  docs/development/localhost-ssl/README.md
  docs/development/product-development-handbook/README.md
  docs/development/releases/README.md
  docs/development/running-tests/README.md
  docs/installation-and-operations/installation/manual/README.md
Labels: documentation

#16564 Docker builds: Only merge the digests from matrix.target
  .github/workflows/docker.yml
Labels: operations, docker

#16553 [#56605] Project attributes: Rename "Deactivate in project" to "Remove from project"
  app/components/settings/project_custom_fields/project_custom_field_mapping/row_component.rb
  config/locales/en.yml
  spec/features/admin/project_custom_fields/project_mappings_spec.rb
Labels: bugfix, needs review
