Repository opf/openproject, pull requests merged in 2024-11, with the labels that each got.

#17099 Implements the ability to add items above or below another
  app/components/admin/custom_fields/hierarchy/item_component.html.erb
  app/components/admin/custom_fields/hierarchy/item_component.rb
  app/components/admin/custom_fields/hierarchy/item_form_component.html.erb
  app/components/admin/custom_fields/hierarchy/item_form_component.rb
  app/components/admin/custom_fields/hierarchy/items_component.html.erb
  app/components/admin/custom_fields/hierarchy/items_component.rb
  app/controllers/admin/custom_fields/hierarchy/items_controller.rb
  app/forms/custom_fields/hierarchy/item_form.rb
  app/models/custom_field/hierarchy/item.rb
  app/services/custom_fields/hierarchy/hierarchical_item_service.rb
  config/locales/en.yml
  spec/features/custom_fields/hierarchy_custom_field_spec.rb
  spec/services/custom_fields/hierarchy/hierarchical_item_service_spec.rb
Labels: needs review

#17101 [Op#58763] Double label on "add reactions" button hover
  app/components/work_packages/activities_tab/journals/item_component/add_reactions.html.erb
Labels: bugfix

#17105 docs/fix typos
  docs/release-notes/14-5-0/README.md
  docs/system-admin-guide/authentication/openid-providers/README.md
  docs/system-admin-guide/integrations/nextcloud/README.md
  docs/user-guide/notifications/README.md
Labels: documentation

#17106 [47777] Work package date picker: wrong spacing
  frontend/src/app/shared/components/datepicker/styles/datepicker.modal.sass
  frontend/src/app/shared/components/modal/modal-banner/modal-banner.component.sass
  frontend/src/app/spot/styles/sass/components/action-bar.sass
Labels: bugfix, needs review

#17102 [52150] Zen mode for project lists page
  app/components/projects/index_page_header_component.html.erb
  frontend/src/stimulus/controllers/dynamic/projects/zen-mode.controller.ts
  frontend/src/stimulus/setup.ts
Labels: feature

#17114 Bug/58787 notification banner is showing up on all pages
  frontend/src/app/features/in-app-notifications/bell/in-app-notification-bell.component.ts
  frontend/src/app/features/plugins/plugin-context.ts
  frontend/src/stimulus/controllers/dynamic/work-packages/activities-tab/index.controller.ts
Labels: bugfix, pullpreview, needs review

#17077 Bug/58685 doubled scrollbar on mobile
  app/components/work_packages/activities_tab/index_component.html.erb
  app/components/work_packages/activities_tab/index_component.sass
  frontend/src/stimulus/controllers/dynamic/work-packages/activities-tab/index.controller.ts
Labels: pullpreview

#17126 [#58844] 15.0 Documentation: Reduce amount of design variables needed…
  docs/system-admin-guide/design/README.md
  docs/system-admin-guide/design/openproject_system_guide_design_interface.png
Labels: documentation

#17066 [#58007] Notification on a mention added to an edited comment is not triggered
  app/services/journals/update_service.rb
  config/initializers/subscribe_listeners.rb
  lib/open_project/events.rb
Labels: bugfix

#17128 Updates for the release notes 15.0
  docs/release-notes/15-0-0/README.md
  docs/release-notes/15-0-0/openproject-15-0-hovercard.png
Labels: documentation

#17136 Render errors for the `short` field of Hierarchy Items
  app/components/admin/custom_fields/hierarchy/item_form_component.rb
  app/controllers/admin/custom_fields/hierarchy/items_controller.rb
  app/forms/custom_fields/hierarchy/item_form.rb
Labels: bugfix

#17135 [#58889] Line height in activity less then e.g. in description
  app/components/work_packages/activities_tab/journals/item_component/show.html.erb
Labels: bugfix, styling, needs review

#17132 [#58773] Activity tab emoji line overflow behaviour can introduce horizontal scroll
  app/components/work_packages/activities_tab/journals/item_component/reactions.html.erb
  app/components/work_packages/activities_tab/journals/item_component/reactions.sass
Labels: bugfix, styling, needs review

#17140 Bug/58890 new comment on wp requires page reload to appear
  app/components/work_packages/activities_tab/index_component.rb
  app/controllers/work_packages/activities_tab_controller.rb
  frontend/src/app/core/turbo/turbo-requests.service.ts
  frontend/src/stimulus/controllers/dynamic/work-packages/activities-tab/index.controller.ts
Labels: pullpreview

#17131 Add documentation for OIDC
  docs/development/development-environment/docker/README.md
  docs/installation-and-operations/misc/custom-openid-connect-providers/README.md
  docs/system-admin-guide/authentication/authentication-faq/README.md
  docs/system-admin-guide/authentication/openid-providers/README.md
  docs/system-admin-guide/authentication/openid-providers/azure-display-name-tenant.png
  docs/system-admin-guide/authentication/openid-providers/azure-provider-index.png
  docs/system-admin-guide/authentication/openid-providers/custom-provider-advanced-config.png
  docs/system-admin-guide/authentication/openid-providers/custom-provider-claims.png
  docs/system-admin-guide/authentication/openid-providers/custom-provider-metadata-discovery.png
  docs/system-admin-guide/authentication/openid-providers/openproject_system-admin-guide_authentication_openid_provider_empty.png
  docs/system-admin-guide/authentication/openid-providers/openproject_system-admin-guide_authentication_openid_provider_new_google.png
  docs/system-admin-guide/authentication/openid-providers/openproject_system-admin-guide_authentication_openid_provider_new_google_successful_message.png
  docs/system-admin-guide/authentication/openid-providers/openproject_system-admin-guide_authentication_openid_provider_saved_google.png
  modules/openid_connect/app/components/openid_connect/providers/row_component.rb
Labels: documentation

#17155 [#58846] 15.0 Documentation: Update PageHeaders & SubHeaders in the (…
  docs/user-guide/home/global-modules/openproject_global_modules_activity.png
  docs/user-guide/home/global-modules/openproject_global_modules_boards.png
  docs/user-guide/home/global-modules/openproject_global_modules_meetings.png
  docs/user-guide/home/global-modules/openproject_global_modules_news.png
  docs/user-guide/home/global-modules/openproject_global_modules_team_planner.png
  docs/user-guide/home/global-modules/openproject_global_modules_time_costs.png
Labels: documentation

#17157 [#58837] 15.0 Documentation: Move "Powered by CKEditor" position to t…
  docs/user-guide/wiki/create-edit-wiki/openproject_user_guide_wiki_autosave_icon.png
  docs/user-guide/work-packages/edit-work-package/openproject_user_guide_wp_autosave_icon.png
Labels: documentation

#17153 [#58845] 15.0 Documentation: Add separate permission to show email ad…
  docs/system-admin-guide/users-permissions/roles-permissions/README.md
Labels: documentation

#17129 [#58847] 15.0 Documentation: Custom field no longer added to all proj…
  docs/system-admin-guide/custom-fields/README.md
  docs/system-admin-guide/manage-work-packages/work-package-types/README.md
Labels: documentation

#17127 [#58839] 15.0 Documentation: Add a caption to clarify what the % Comp…
  docs/system-admin-guide/manage-work-packages/work-package-status/openproject_system_guide_create_new_wp_status.png
Labels: documentation

#17159 [#58824] Emoji reactions overlap on mWeb
  app/components/_index.sass
  app/components/work_packages/activities_tab/journals/item_component/add_reactions.html.erb
  app/components/work_packages/activities_tab/journals/item_component/add_reactions.sass
Labels: bugfix, styling, needs review

#17165 Documentation: ensure well formed markdown alerts
  docs/getting-started/account-settings/README.md
  docs/system-admin-guide/authentication/saml/README.md
  docs/system-admin-guide/custom-fields/README.md
  docs/system-admin-guide/custom-fields/custom-fields-projects/README.md
  docs/system-admin-guide/projects/project-attributes/README.md
  docs/system-admin-guide/users-permissions/roles-permissions/README.md
  docs/user-guide/forums/README.md
  docs/user-guide/meetings/dynamic-meetings/README.md
  docs/user-guide/notifications/README.md
  docs/user-guide/project-overview/README.md
  docs/user-guide/projects/project-settings/custom-fields/README.md
  docs/user-guide/projects/project-settings/project-attributes/README.md
  docs/user-guide/time-and-costs/progress-tracking/README.md
  docs/user-guide/wiki/README.md
  docs/user-guide/wiki/create-edit-wiki/README.md
  docs/user-guide/work-packages/baseline-comparison/README.md
  docs/user-guide/work-packages/duplicate-move-delete/README.md
  docs/user-guide/work-packages/edit-work-package/README.md
  docs/user-guide/work-packages/exporting/README.md
  docs/user-guide/work-packages/work-packages-faq/README.md
  docs/user-guide/wysiwyg/README.md
Labels: documentation

#17170 Documentation: Fixes
  docs/system-admin-guide/authentication/openid-providers/azure-provider-index.png
  docs/system-admin-guide/authentication/openid-providers/openproject_system-admin-guide_authentication_openid_provider.png
  docs/system-admin-guide/authentication/openid-providers/openproject_system-admin-guide_authentication_openid_provider_new.png
  docs/system-admin-guide/design/openproject_system_guide_design_advanced_settings_primer.png
  docs/system-admin-guide/design/openproject_system_guide_design_color_theme_pick.png
  docs/system-admin-guide/integrations/nextcloud/README.md
  docs/system-admin-guide/manage-work-packages/work-package-settings/openproject_system_guide_work_package_settings_warning.png
  docs/system-admin-guide/manage-work-packages/work-package-status/README.md
  docs/system-admin-guide/projects/project-attributes/README.md
  docs/user-guide/backlogs-scrum/taskboard/User-guide-task-color.png
  docs/user-guide/forums/Forum-message-reply.png
  docs/user-guide/forums/Forum-unwatch.png
  docs/user-guide/forums/Forum-watcher.png
  docs/user-guide/forums/Forum_add-message.png
  docs/user-guide/forums/Forum_delete-message.png
  docs/user-guide/forums/Forum_edit-message.png
  docs/user-guide/forums/Forum_watch-message.png
  docs/user-guide/forums/User-guide-create-new-forum.png
  docs/user-guide/forums/User-guide-manage-forums.png
  docs/user-guide/forums/image-20191119100717879.png
  docs/user-guide/forums/image-20191119102209845.png
  docs/user-guide/forums/image-20191119103331490.png
  docs/user-guide/forums/image-20191119105329892.png
  docs/user-guide/forums/image-20191119105630149.png
  docs/user-guide/forums/image-20191119113940355.png
  docs/user-guide/forums/image-20200213093639380.png
  docs/user-guide/projects/project-lists/openproject-work-package-pdf-export1.png
  docs/user-guide/projects/project-lists/projects-list.png
  docs/user-guide/projects/project-settings/custom-fields/User-guide_project-settings-custom-fields.png
  docs/user-guide/team-planner/TeamPlanner-12.4-addAssignee.png
  docs/user-guide/team-planner/TeamPlanner-12.4-addExisting.png
  docs/user-guide/team-planner/TeamPlanner-12.4-emptyNew.png
  docs/user-guide/team-planner/TeamPlanner-12.4-hoverWorkPackageCard-dragHandles.png
  docs/user-guide/team-planner/TeamPlanner-12.4-hoverWorkPackageCard.png
  docs/user-guide/team-planner/TeamPlanner-12.4-listAllAvailable.png
  docs/user-guide/team-planner/TeamPlanner-12.4-newTask-drag.png
  docs/user-guide/team-planner/TeamPlanner-12.4-newTask-splitScreen.png
  docs/user-guide/team-planner/TeamPlanner-12.4-oneWeek.png
  docs/user-guide/team-planner/TeamPlanner-12.4-removeAssigneeDates.png
  docs/user-guide/team-planner/TeamPlanner-12.4-splitScreen.png
  docs/user-guide/team-planner/TeamPlanner-12.4-twoWeeks.png
  docs/user-guide/time-and-costs/progress-tracking/README.md
  docs/user-guide/time-and-costs/progress-tracking/progress-popover-percentage-complete-only.png
Labels: documentation

#17171 [#59176] Activity tab: Too much spacing between comment and Emoji line
  app/components/work_packages/activities_tab/journals/item_component/show.html.erb
Labels: bugfix, styling

#17172 Chore: do not run non-related Github actions on doc changes
  .github/workflows/codeql-scan-core.yml
  .github/workflows/rubocop-core.yml
Labels: github_actions

#17168 Bug/59165 when user has newest on top sort order latest comment still shows up at the bottom
  app/components/work_packages/activities_tab/index_component.rb
  app/components/work_packages/activities_tab/journals/filter_and_sorting_component.rb
  app/components/work_packages/activities_tab/journals/index_component.rb
  app/components/work_packages/activities_tab/journals/item_component/details.rb
  app/components/work_packages/activities_tab/shared_helpers.rb
  app/controllers/work_packages/activities_tab_controller.rb
  spec/features/activities/work_package/activities_spec.rb
  spec/support/components/work_packages/activities.rb
Labels: pullpreview

#17166 [58728] Loading animation is too big in HoverCard
  frontend/src/app/shared/components/modals/preview-modal/hover-card-modal/hover-card.modal.html
Labels: bugfix, needs review

#17096 Bump tag references from 14 to 15
  docs/development/packaging/README.md
  docs/installation-and-operations/configuration/README.md
  docs/installation-and-operations/configuration/database/README.md
  docs/installation-and-operations/configuration/server/docker-compose.yml
  docs/installation-and-operations/installation/docker/README.md
  docs/installation-and-operations/installation/packaged/README.md
  docs/installation-and-operations/installation/synology/README.md
  docs/installation-and-operations/misc/migration-to-postgresql13/README.md
  docs/installation-and-operations/operation/backing-up/README.md
  docs/installation-and-operations/operation/restoring/README.md
  docs/installation-and-operations/operation/upgrading/README.md
  docs/installation-and-operations/system-requirements/README.md
  modules/gitlab_integration/README.md
Labels: operations, needs review

#17163 release-notes-final-updates-15-0
  docs/release-notes/15-0-0/README.md
Labels: documentation

#17182 small docs changes
  docs/getting-started/account-settings/README.md
  docs/system-admin-guide/users-permissions/roles-permissions/README.md
  docs/user-guide/account-settings/README.md
Labels: documentation

#17118 Documentation: New activity panel, emoji reactions and auto polling
  docs/user-guide/activity/Activity-addEmoji.png
  docs/user-guide/activity/Activity-changeset.png
  docs/user-guide/activity/Activity-comment.png
  docs/user-guide/activity/Activity-commentBox.png
  docs/user-guide/activity/Activity-filter.png
  docs/user-guide/activity/Activity-mention.png
  docs/user-guide/activity/Activity-more.png
  docs/user-guide/activity/Activity-sortOrder.png
  docs/user-guide/activity/Activity-tab.png
  docs/user-guide/activity/README.md
Labels: documentation

#17187 Bug/59239 notification bubbles and mark as read buttons not responding correctly to changes
  app/controllers/work_packages/activities_tab_controller.rb
  frontend/src/app/features/work-packages/components/wp-buttons/wp-mark-notification-button/work-package-mark-notification-button.component.ts
  frontend/src/app/features/work-packages/routing/wp-full-view/wp-full-view.component.ts
  frontend/src/app/features/work-packages/routing/wp-split-view/wp-split-view.component.ts
  frontend/src/app/features/work-packages/routing/wp-view-base/state/wp-single-view.service.ts
  frontend/src/stimulus/controllers/dynamic/work-packages/activities-tab/index.controller.ts
Labels: pullpreview

#17198 documentation: fix typos and unify spelling
  docs/release-notes/14-5-0/README.md
  docs/release-notes/14-6-0/README.md
  docs/release-notes/15-0-0/README.md
  docs/system-admin-guide/authentication/openid-providers/README.md
  docs/system-admin-guide/design/README.md
  docs/system-admin-guide/integrations/nextcloud/README.md
  docs/user-guide/activity/README.md
  docs/user-guide/notifications/README.md
Labels: documentation

#17215 Merge release/15.0 into dev
  config/locales/crowdin/js-ro.yml
  config/locales/crowdin/pt-BR.seeders.yml
  config/locales/crowdin/ro.yml
  config/locales/crowdin/sv.yml
  modules/calendar/config/locales/crowdin/js-ro.yml
  modules/calendar/config/locales/crowdin/ro.yml
  modules/meeting/config/locales/crowdin/ro.yml
  modules/team_planner/config/locales/crowdin/js-ro.yml
  modules/team_planner/config/locales/crowdin/ro.yml
  modules/two_factor_authentication/config/locales/crowdin/ro.yml
Labels: create-merge-release-into-dev-pr

#17217 [59159] Removed watchexec-cli from Dockerfile for development
  docker/dev/backend/Dockerfile
Labels: bugfix, needs review

#17219 [#59408] Signing in after two factor methods have been deleted lead to a 500 error
  modules/two_factor_authentication/app/controllers/two_factor_authentication/authentication_controller.rb
  modules/two_factor_authentication/spec/features/account_activation_spec.rb
  modules/two_factor_authentication/spec/features/backup_codes/generate_backup_codes_spec.rb
  modules/two_factor_authentication/spec/features/backup_codes/login_with_backup_code_spec.rb
  modules/two_factor_authentication/spec/features/login/login_enforced_2fa_spec.rb
  modules/two_factor_authentication/spec/features/login/login_with_2fa_spec.rb
  modules/two_factor_authentication/spec/features/login/login_with_deleted_2fa_spec.rb
  modules/two_factor_authentication/spec/features/login/login_without_2fa_spec.rb
  modules/two_factor_authentication/spec/features/login/switch_available_devices_spec.rb
  modules/two_factor_authentication/spec/features/remember_cookie/login_with_remember_cookie_spec.rb
  modules/two_factor_authentication/spec/features/shared_two_factor_examples.rb
Labels: tinyfix

#17221 Respect self-registration in saml
  modules/auth_saml/app/components/saml/providers/sections/show_component.html.erb
  modules/auth_saml/app/controllers/saml/providers_controller.rb
  modules/auth_saml/app/services/saml/configuration_mapper.rb
  modules/auth_saml/spec/features/administration/saml_crud_spec.rb
  modules/auth_saml/spec/services/saml/configuration_mapper_spec.rb
Labels: bugfix, needs review

#17220 Bump primer to 0.49.1
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
  frontend/src/global_styles/primer/_overrides.sass
Labels: maintenance, needs review

#17216 Start implementing mobile behavior for border-box table
  app/components/op_primer/border_box_row_component.html.erb
  app/components/op_primer/border_box_row_component.rb
  app/components/op_primer/border_box_table_component.html.erb
  app/components/op_primer/border_box_table_component.rb
  app/components/op_primer/border_box_table_component.sass
  lookbook/docs/patterns/12-tables.md.erb
  lookbook/previews/op_primer/border_box_table_component_preview/custom_column_widths.html.erb
  lookbook/previews/op_primer/border_box_table_component_preview/default.html.erb
  lookbook/previews/op_primer/border_box_table_component_preview/with_action_menu.html.erb
  modules/auth_saml/app/components/saml/providers/row_component.rb
  modules/auth_saml/app/components/saml/providers/table_component.rb
  modules/meeting/app/components/meetings/row_component.rb
  modules/meeting/app/components/meetings/table_component.rb
  modules/openid_connect/app/components/openid_connect/providers/row_component.rb
  modules/openid_connect/app/components/openid_connect/providers/table_component.rb
Labels: feature, styling, needs review

#17227 Add custom scopes to OpenID Connect
  modules/openid_connect/app/components/openid_connect/providers/client_details_form.rb
  modules/openid_connect/app/models/openid_connect/provider.rb
  modules/openid_connect/app/models/openid_connect/provider/hash_builder.rb
  modules/openid_connect/app/services/openid_connect/configuration_mapper.rb
  modules/openid_connect/config/locales/en.yml
  modules/openid_connect/spec/features/administration/oidc_custom_crud_spec.rb
  modules/openid_connect/spec/migration/migrate_oidc_settings_to_providers_spec.rb
  modules/openid_connect/spec/services/openid_connect/configuration_mapper_spec.rb
Labels: bugfix, needs review

#17233 #59353] Missing * next to Project selector to indicate that field is mandatory
  modules/meeting/app/forms/meeting/project_autocompleter.rb
Labels: bugfix

#17245 Do not treat HTML as inlinable
  app/models/attachment.rb
  spec/models/attachment_spec.rb
Labels: bugfix, needs review

#17224 Code maintenance/59280 ensure that the new activity tab renders quickly also for work packages with over 100 comments
  app/components/work_packages/activities_tab/index_component.html.erb
  app/components/work_packages/activities_tab/index_component.rb
  app/components/work_packages/activities_tab/journals/index_component.html.erb
  app/components/work_packages/activities_tab/journals/index_component.rb
  app/components/work_packages/activities_tab/journals/item_component.rb
  app/components/work_packages/activities_tab/journals/item_component/details.html.erb
  app/components/work_packages/activities_tab/journals/item_component/details.rb
  app/controllers/work_packages/activities_tab_controller.rb
  app/models/journal.rb
  frontend/src/stimulus/controllers/dynamic/work-packages/activities-tab/index.controller.ts
  lib/api/v3/activities/activity_eager_loading_wrapper.rb
  spec/lib/api/v3/activities/activity_eager_loading_wrapper_spec.rb
Labels: pullpreview

#17234 [58734] Extract work package info line into a Primer component and document it
  app/components/work_package_relations_tab/relation_component.html.erb
  app/components/work_packages/hover_card_component.html.erb
  app/components/work_packages/hover_card_component.sass
  app/components/work_packages/info_line_component.html.erb
  app/components/work_packages/info_line_component.rb
  lookbook/docs/patterns/26-work-package-info-line.md.erb
  lookbook/previews/open_project/work_packages/info_line_component_preview.rb
  modules/meeting/app/components/meeting_agenda_items/item_component/show_component.html.erb
Labels: needs review

#17256 Documentation/55879 Add documentation about OPENPROJECT_SMTP__TIMEOUT, fix OPENPROJECT_SMTP__USER__NAME
  docs/installation-and-operations/configuration/outbound-emails/README.md
Labels: documentation, contribution

#17181 Bump IfcConvert version
  docker/dev/backend/scripts/setup-bim
  docker/prod/setup/preinstall-common.sh
  modules/bim/bin/setup_dev.sh
  packaging/addons/openproject-edition/bin/preinstall
Labels: contribution, needs review

#16989 [#58345] Primerize Relations tab
  app/components/_index.sass
  app/components/work_package_relations_tab/add_work_package_child_dialog_component.html.erb
  app/components/work_package_relations_tab/add_work_package_child_dialog_component.rb
  app/components/work_package_relations_tab/add_work_package_child_form_component.html.erb
  app/components/work_package_relations_tab/add_work_package_child_form_component.rb
  app/components/work_package_relations_tab/index_component.html.erb
  app/components/work_package_relations_tab/index_component.rb
  app/components/work_package_relations_tab/index_component.sass
  app/components/work_package_relations_tab/relation_component.html.erb
  app/components/work_package_relations_tab/relation_component.rb
  app/components/work_package_relations_tab/work_package_relation_dialog_component.html.erb
  app/components/work_package_relations_tab/work_package_relation_dialog_component.rb
  app/components/work_package_relations_tab/work_package_relation_form_component.html.erb
  app/components/work_package_relations_tab/work_package_relation_form_component.rb
  app/components/work_packages/hover_card_component.html.erb
  app/components/work_packages/hover_card_component.sass
  app/components/work_packages/info_line_component.html.erb
  app/components/work_packages/info_line_component.rb
  app/controllers/work_package_children_controller.rb
  app/controllers/work_package_relations_controller.rb
  app/controllers/work_package_relations_tab_controller.rb
  app/models/relation.rb
  app/views/work_package_relations_tab/_index.html.erb
  config/initializers/permissions.rb
  config/locales/en.yml
  config/routes.rb
  frontend/src/app/features/work-packages/components/wp-fast-table/handlers/row/wp-state-links-handler.ts
  frontend/src/app/features/work-packages/components/wp-relations/embedded/relations/wp-relation-inline-create.service.ts
  frontend/src/app/features/work-packages/components/wp-relations/wp-relations.component.ts
  frontend/src/app/features/work-packages/components/wp-relations/wp-relations.template.html
  frontend/src/app/shared/components/autocompleter/op-autocompleter/op-autocompleter.component.ts
  frontend/src/global_styles/content/work_packages/single_view/_single_view.sass
  lookbook/docs/patterns/26-work-package-info-line.md.erb
  lookbook/previews/open_project/work_packages/info_line_component_preview.rb
  modules/boards/spec/features/board_navigation_spec.rb
  modules/gantt/spec/features/timeline/timeline_navigation_spec.rb
  modules/meeting/app/components/meeting_agenda_items/item_component/show_component.html.erb
  spec/controllers/work_package_children_controller_spec.rb
  spec/controllers/work_package_relations_controller_spec.rb
  spec/controllers/work_package_relations_tab_controller_spec.rb
  spec/features/work_packages/copy_spec.rb
  spec/features/work_packages/details/query_groups/relation_query_group_spec.rb
  spec/features/work_packages/details/relations/hierarchy_custom_fields_spec.rb
  spec/features/work_packages/details/relations/hierarchy_spec.rb
  spec/features/work_packages/details/relations/primerized_relations_spec.rb
  spec/features/work_packages/details/relations/relations_spec.rb
  spec/features/work_packages/new/new_work_package_spec.rb
  spec/support/components/work_packages/relations.rb
Labels: feature, pullpreview

#17278 Bump primer to 0.49.2
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: maintenance

#17273 Allow locking of the seeded admin user
  app/seeders/root_seeder.rb
  config/constants/settings/definition.rb
  docs/installation-and-operations/configuration/README.md
  modules/bim/spec/seeders/root_seeder_bim_edition_spec.rb
  spec/seeders/admin_user_seeder_spec.rb
  spec/seeders/root_seeder_standard_edition_spec.rb
Labels: feature, needs review

#17281 [59556] Filter out root item of hierarchy filter
  frontend/src/app/features/work-packages/components/filters/filter-searchable-multiselect-value/filter-searchable-multiselect-value.component.ts
  frontend/src/app/shared/components/autocompleter/op-autocompleter/op-autocompleter.component.html
Labels: needs review

#17279 [#59343] Spacing between table columns is off if name is long
  app/components/op_primer/border_box_row_component.rb
  app/components/op_primer/border_box_table_component.html.erb
  app/components/op_primer/border_box_table_component.rb
  app/components/op_primer/border_box_table_component.sass
  lookbook/docs/patterns/12-tables.md.erb
  lookbook/previews/op_primer/border_box_table_component_preview/custom_column_widths.html.erb
  modules/auth_saml/app/components/saml/providers/table_component.rb
  modules/meeting/app/components/meetings/table_component.rb
  modules/openid_connect/app/components/openid_connect/providers/table_component.rb
Labels: bugfix

#17298 [59163] Auto focus label field of new hierarchy item
  app/forms/custom_fields/hierarchy/item_form.rb
Labels: needs review

#17300 [59770] When opening relations modal, focus is not on text field
  app/components/work_package_relations_tab/add_work_package_child_form_component.html.erb
  app/components/work_package_relations_tab/work_package_relation_form_component.html.erb
Labels: bugfix, needs review

#17286 Increase spacing between create button and explanation text
  app/components/work_package_relations_tab/index_component.html.erb
Labels: bugfix, styling

#17294 [58345] Move the "More" menu to the same row as the WorkPackageInfoLine
  app/components/work_package_relations_tab/index_component.rb
  app/components/work_package_relations_tab/index_component.sass
  app/components/work_package_relations_tab/relation_component.html.erb
Labels: bugfix, styling

#17301 Remove unused code
  modules/bim/app/controllers/bim/bcf/issues_controller.rb
  modules/bim/app/views/bim/bcf/issues/index.html.erb
  modules/bim/config/routes.rb
  modules/bim/lib/open_project/bim/engine.rb
  modules/boards/app/views/boards/boards/overview.html.erb
Labels: maintenance

#17297 [59771] Some relations type do not pre-populate the right WP when relation is edited
  app/components/work_package_relations_tab/work_package_relation_form_component.rb
  spec/features/work_packages/details/relations/primerized_relations_spec.rb
  spec/support/components/work_packages/relations.rb
Labels: bugfix, needs review
