Repository opf/openproject, pull requests merged in 2024-04, with the labels that each got.

#15128 Remove the definition for LDAP tls options
  app/models/setting.rb
  config/configuration.yml.example
  config/constants/settings/definition.rb
  db/migrate/20221115082403_add_ldap_tls_options.rb
  db/migrate/20240402065214_remove_ldap_tls_setting.rb
  spec/migrations/restore_defaults_on_empty_settings_spec.rb
Labels: maintenance

#14950 [53316] Change row break in email notifications
  app/views/mailer/_notification_row.html.erb
Labels: feature, needs review

#15130 Apply text attribute component to overview page - using text expander
  app/components/open_project/common/attribute_component.html.erb
  app/components/open_project/common/attribute_component.rb
  app/components/open_project/common/attribute_component.sass
  app/components/projects/row_component.rb
  app/components/projects/settings/project_custom_field_sections/custom_field_row_component.html.erb
  app/components/projects/settings/project_custom_field_sections/show_component.html.erb
  app/components/settings/project_custom_field_sections/custom_field_row_component.html.erb
  app/components/settings/project_custom_field_sections/custom_field_row_component.rb
  app/components/settings/project_custom_field_sections/show_component.html.erb
  app/components/settings/project_custom_field_sections/show_component.rb
  app/components/settings/project_custom_fields/header_component.html.erb
  config/locales/en.yml
  frontend/src/stimulus/controllers/dynamic/attribute.controller.ts
  modules/overviews/app/components/project_custom_fields/sections/edit_dialog_component.html.erb
  modules/overviews/app/components/project_custom_fields/sections/project_custom_fields/show_component.html.erb
  modules/overviews/app/components/project_custom_fields/sections/project_custom_fields/show_component.rb
  modules/overviews/app/components/project_custom_fields/sections/show_component.html.erb
  modules/overviews/app/components/project_custom_fields/sidebar_component.html.erb
  spec/features/admin/project_custom_fields/list_spec.rb
  spec/features/projects/project_custom_fields/overview_page/dialog/permission_spec.rb
  spec/features/projects/project_custom_fields/overview_page/dialog/update_spec.rb
  spec/features/projects/project_custom_fields/overview_page/sidebar_spec.rb
  spec/features/projects/project_custom_fields/settings/mapping_spec.rb
  spec/features/projects/projects_index_spec.rb
  spec/support/components/projects/project_custom_fields/edit_dialog.rb
  spec/support/pages/projects/show.rb
Labels: pullpreview

#15120 Bug/52798 add meaningful flash error message when user cancels oauth flow on onedrivesharepoint
  config/locales/en.yml
Labels: pullpreview

#15161 Show lock actions of user with an icon on mobile
  app/helpers/users_helper.rb
  app/views/users/_toolbar.html.erb
  spec/helpers/users_helper_spec.rb
Labels: feature, needs review

#15134 [#53577] Use sidebar_enabled method on the overview page instead of project meta tags
  app/views/layouts/_common_head.html.erb
  frontend/src/app/core/current-project/current-project.service.ts
  frontend/src/app/features/overview/overview.component.ts
  modules/overviews/app/controllers/overviews/overviews_controller.rb
  modules/overviews/app/views/overviews/overviews/show.html.erb
  modules/overviews/spec/features/managing_overview_page_spec.rb
  spec/support/components/grids/grid_area.rb
Labels: needs review

#15165 Fix selector to target_top links
  lib/open_project/text_formatting/filters/link_attribute_filter.rb
  spec/lib/open_project/text_formatting/markdown/lists_spec.rb
  spec/lib/open_project/text_formatting/markdown/mentions_spec.rb
  spec/lib/open_project/text_formatting/markdown/setting_variable_spec.rb
  spec/lib/open_project/text_formatting/markdown/user_provided_links_spec.rb
  spec/requests/api/v3/render_resource_spec.rb
Labels: bugfix, needs review

#15167 Bump gems
  Gemfile.lock
Labels: maintenance, ruby

#15172 Bug fixes for new color mapping
  app/views/custom_styles/_primer_color_mapping.erb
  frontend/src/app/spot/styles/sass/components/switch.sass
  frontend/src/global_styles/content/_datepicker.sass
  frontend/src/global_styles/openproject/_variable_defaults.scss
Labels: bugfix, styling, needs review

#15177 [53948] New GitLab integration tab content is displayed in front of all popups
  modules/gitlab_integration/frontend/module/gitlab-tab/gitlab-tab.component.sass
Labels: bugfix, styling, needs review

#15180 Introduce helper for border box that sets the correct position class
  app/components/op_primer/component_helpers.rb
  app/components/projects/settings/project_custom_field_sections/show_component.html.erb
  app/components/settings/project_custom_field_sections/show_component.html.erb
  app/components/work_packages/share/modal_body_component.html.erb
  modules/meeting/app/components/meeting_agenda_items/list_component.html.erb
  modules/meeting/app/components/work_package_meetings_tab/meeting_component.html.erb
  modules/storages/app/components/storages/admin/storage_list_component.html.erb
  modules/storages/app/components/storages/admin/storage_view_component.html.erb
Labels: bugfix, needs review

#15181 Fix displaying of dates in macros
  frontend/src/app/shared/components/fields/display/display-field.component.ts
  frontend/src/app/shared/components/fields/macros/attribute-value-macro.component.ts
  spec/features/wysiwyg/macros/attribute_macros_spec.rb
Labels: bugfix, needs review

#15179 Add diff for agenda item notes
  app/controllers/journals_controller.rb
  app/models/journal.rb
  lib/open_project/journal_formatter/diff.rb
  modules/meeting/app/models/activities/meeting_event_mapper.rb
  modules/meeting/app/models/meeting/journalized.rb
  modules/meeting/lib/open_project/journal_formatter/agenda_item_diff.rb
  modules/meeting/lib/open_project/journal_formatter/agenda_item_title.rb
  modules/meeting/spec/features/structured_meetings/history_spec.rb
  modules/meeting/spec/support/pages/structured_meeting/show.rb
  spec/lib/journal_formatter/diff_spec.rb
  spec/lib/journal_formatter/wiki_diff_spec.rb
Labels: feature

#15185 Hide storage link if user has no ':read_files' permission
  frontend/src/app/core/state/project-storages/project-storage.model.ts
  frontend/src/app/features/work-packages/components/wp-single-view-tabs/files-tab/op-files-tab.component.ts
  frontend/src/app/shared/components/storages/storage/storage.component.html
  frontend/src/app/shared/components/storages/storage/storage.component.ts
  modules/storages/lib/api/v3/project_storages/project_storage_representer.rb
  modules/storages/spec/lib/api/v3/project_storages/project_storage_representer_spec.rb
Labels: bugfix, needs review

#15193 Sort assignee resources in team planner by title
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.ts
Labels: needs review

#15192 [#51794] Bump version number in Project details widget.
  frontend/src/app/shared/components/grids/widgets/project-details/project-details.component.html
  modules/dashboards/spec/features/project_details_spec.rb
Labels: needs review

#15190 [#53660] Show meeting state in meeting history
  app/models/journal.rb
  modules/meeting/app/models/meeting/journalized.rb
  modules/meeting/config/locales/en.yml
  modules/meeting/db/migrate/20240408161233_add_state_to_meeting_journal.rb
  modules/meeting/lib/open_project/journal_formatter/meeting_state.rb
  modules/meeting/spec/features/structured_meetings/history_spec.rb
Labels: feature, needs review

#15178 [53504] Wrong colors for accent color and primary button
  app/views/custom_styles/_primer_color_mapping.erb
  db/migrate/20240408093541_change_default_accent_and_bim_primary_color.rb
  frontend/src/global_styles/openproject/_variable_defaults.scss
  lib/open_project/custom_styles/color_themes.rb
Labels: bugfix, needs review

#15195 Add copy to clipboard action for agenda menu
  frontend/src/app/core/setup/globals/global-listeners.ts
  modules/meeting/app/components/meeting_agenda_items/item_component/show_component.html.erb
  modules/meeting/app/components/meeting_agenda_items/item_component/show_component.rb
  modules/meeting/spec/features/structured_meetings/history_spec.rb
Labels: feature

#15196 [#54015] Update agenda item work package history subtitles
  app/components/activities/item_component.html.erb
  app/components/activities/item_component.rb
  app/components/activities/item_subtitle_component.rb
  config/locales/en.yml
  modules/meeting/app/models/activities/meeting_event_mapper.rb
  modules/meeting/spec/features/structured_meetings/history_spec.rb
  spec/components/activities/item_subtitle_component_spec.rb
Labels: feature, needs review

#15184 [53812] Meeting agenda item overflow with long work package subject
  modules/meeting/app/components/_index.sass
  modules/meeting/app/components/meeting_agenda_items/form_component.sass
  modules/meeting/app/components/meeting_agenda_items/item_component/show_component.sass
  modules/meeting/app/components/meetings/show_component.html.erb
  modules/meeting/app/components/meetings/sidebar/attachments_component.html.erb
  modules/meeting/app/components/meetings/sidebar/details_component.html.erb
  modules/meeting/app/components/meetings/sidebar/details_component.sass
  modules/meeting/app/components/meetings/sidebar/participants_component.sass
  modules/meeting/app/components/meetings/sidebar/state_component.html.erb
  modules/meeting/app/components/meetings/sidebar/state_component.sass
  modules/meeting/app/components/meetings/sidebar_component.html.erb
  modules/meeting/config/locales/en.yml
  modules/meeting/spec/features/structured_meetings/history_spec.rb
  modules/meeting/spec/features/structured_meetings/structured_meeting_crud_spec.rb
Labels: bugfix, styling, needs review

#15175 [Op#52449] Upgrade the storage health status component to use an extensible sidebar component
  modules/meeting/app/components/meetings/sidebar_component.html.erb
  modules/storages/app/components/storages/admin/health_status_component.html.erb
  modules/storages/app/components/storages/admin/sidebar/health_status_component.html.erb
  modules/storages/app/components/storages/admin/sidebar/health_status_component.rb
  modules/storages/app/components/storages/admin/sidebar_component.html.erb
  modules/storages/app/components/storages/admin/sidebar_component.rb
  modules/storages/app/views/storages/admin/storages/edit.html.erb
  modules/storages/config/locales/en.yml
  modules/storages/spec/components/storages/admin/sidebar/health_status_component_spec.rb
  modules/storages/spec/features/storages/admin/edit_storage_spec.rb
Labels: feature

#15198 Remove old `allowed_to?` methods
  app/models/users/permission_checks.rb
  app/services/authorization/user_allowed_service.rb
  lib/api/v3/work_packages/available_projects_on_create_api.rb
  lib/api/v3/work_packages/available_projects_on_edit_api.rb
  spec/models/users/allowed_to_spec.rb
  spec/services/authorization/user_allowed_service_spec.rb
  spec/support/mocked_permission_helper.rb
  spec/support_spec/mocked_permission_helper_spec.rb
Labels: maintenance, needs review

#15209 [54029] Search preview is rendered behind the search field for Work Package meeting agenda items
  modules/meeting/app/components/meeting_agenda_items/form_component.sass
Labels: bugfix, styling, needs review

#15160 [53811] Documentation of PageHeader
  lookbook/docs/patterns/10-page-headers.md.erb
  lookbook/previews/open_project/common/page_header_preview.rb
Labels: documentation

#15210 Release notes section for changes in design variables
  docs/release-notes/14-0-0/README.md
Labels: documentation, needs review

#15219 [54108] Share modal layout is broken
  frontend/src/global_styles/openproject.sass
Labels: bugfix, styling, needs review

#15232 bug/storage-health-status-mails-are-send-for-every-failed-request
  modules/storages/app/workers/storages/health_status_mailer_job.rb
Labels: bugfix

#15234 [#54140] Add email settings button in storages mailer
  modules/storages/app/views/storages/storages_mailer/notify_healthy.html.erb
  modules/storages/app/views/storages/storages_mailer/notify_healthy.text.erb
  modules/storages/app/views/storages/storages_mailer/notify_unhealthy.html.erb
  modules/storages/app/views/storages/storages_mailer/notify_unhealthy.text.erb
  modules/storages/spec/mailers/storages/storages_mailer_spec.rb
  spec/mailers/previews/storages/storages_mailer_preview.rb
Labels: bugfix

#15235 Require rubocop-rspec_rails to fix rubocop warning.
  .rubocop.yml
Labels: dependencies, needs review

#15236 Fix/transaction for update progress job
  app/services/journals/create_service.rb
  app/workers/work_packages/apply_statuses_p_complete_job.rb
  app/workers/work_packages/update_progress_job.rb
  db/migrate/20240402072213_update_progress_calculation.rb
  spec/migrations/update_progress_calculation_spec.rb
  spec/workers/work_packages/apply_statuses_p_complete_job_spec.rb
Labels: needs review

#15225 Documentation gitlab add local network settings
  docs/system-admin-guide/attachments/virus-scanning/README.md
  docs/system-admin-guide/integrations/gitlab-integration/README.md
Labels: documentation, needs review

#15226 [#53799] Overview page crashes if there have been project custom fiel…
  db/migrate/20231123111357_create_custom_field_sections.rb
  spec/migrations/create_custom_field_sections_spec.rb
Labels: needs review

#15250 [#53802] Deletion dialog does not provide enough context
  app/components/settings/project_custom_field_sections/custom_field_row_component.rb
  config/locales/en.yml
Labels: needs review

#15249 Allow shared users to be set as accountable/responsible as well
  docs/api/apiv3/components/schemas/available_responsibles_model.yml
  docs/api/apiv3/openapi-spec.yml
  docs/api/apiv3/paths/project_available_responsibles.yml
  docs/release-notes/14-0-0/README.md
  lib/api/v3/projects/available_responsibles_api.rb
  lib/api/v3/projects/projects_api.rb
  lib/api/v3/utilities/path_helper.rb
  lib/api/v3/work_packages/schema/work_package_schema_representer.rb
  spec/lib/api/v3/utilities/path_helper_spec.rb
  spec/lib/api/v3/work_packages/schema/work_package_schema_representer_spec.rb
  spec/requests/api/v3/projects/available_responsibles_api_spec.rb
Labels: bugfix

#15247 Update teaser block text for 14.0
  config/locales/js-en.yml
  frontend/src/app/features/homescreen/blocks/new-features.component.ts
Labels: needs review

#15251 Fix hidden display of participants dialog
  modules/meeting/app/components/_index.sass
  modules/meeting/app/components/meetings/sidebar/details_component.html.erb
  modules/meeting/app/components/meetings/sidebar/details_component.sass
  modules/meeting/app/components/meetings/sidebar/participants_component.html.erb
  modules/meeting/spec/features/structured_meetings/structured_meeting_participant_spec.rb
  modules/meeting/spec/support/pages/structured_meeting/show.rb
Labels: bugfix

#15243 Set target=_top for all links, also external
  lib/open_project/text_formatting/filters/link_attribute_filter.rb
  modules/meeting/spec/features/structured_meetings/turbo_links_spec.rb
  spec/lib/open_project/text_formatting/markdown/lists_spec.rb
  spec/lib/open_project/text_formatting/markdown/mentions_spec.rb
  spec/lib/open_project/text_formatting/markdown/setting_variable_spec.rb
  spec/lib/open_project/text_formatting/markdown/user_provided_links_spec.rb
  spec/requests/api/v3/render_resource_spec.rb
Labels: bugfix, needs review

#15244 Unset old total p complete values in journals
  app/workers/work_packages/update_progress_job.rb
  spec/migrations/update_progress_calculation_spec.rb
Labels: needs review

#15248 [#54061] Rails.application.routes don't respects OPENPROJECT_RAILS__RELATIVE__URL__ROOT
  config/application.rb
Labels: needs review

#15265 Bump angular to 17
  frontend/angular.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/core/forms/forms.service.ts
  frontend/src/app/core/global_search/input/global-search-input-mobile.component.sass
  frontend/src/app/core/global_search/input/global-search.component.sass
  frontend/src/app/features/bim/ifc_models/bcf/list/bcf-list.component.sass
  frontend/src/app/features/bim/ifc_models/ifc-viewer/ifc-viewer.component.sass
  frontend/src/app/features/bim/ifc_models/pages/viewer/styles/generic.sass
  frontend/src/app/features/boards/board/board-actions/assignee/assignee-board-header.sass
  frontend/src/app/features/boards/board/board-actions/status/status-board-header.sass
  frontend/src/app/features/boards/board/board-actions/subproject/subproject-board-header.sass
  frontend/src/app/features/boards/board/board-actions/subtasks/subtasks-board-header.sass
  frontend/src/app/features/boards/board/board-actions/version/version-board-header.sass
  frontend/src/app/features/boards/board/board-list/board-list.component.sass
  frontend/src/app/features/boards/board/board-partitioned-page/board-list-container.component.sass
  frontend/src/app/features/in-app-notifications/bell/in-app-notification-bell.component.sass
  frontend/src/app/features/in-app-notifications/entry/actors-line/in-app-notification-actors-line.component.sass
  frontend/src/app/features/in-app-notifications/entry/in-app-notification-entry.component.sass
  frontend/src/app/features/team-planner/team-planner/add-work-packages/add-existing-pane.component.sass
  frontend/src/app/features/work-packages/components/wp-activity/user/user-activity.component.sass
  frontend/src/app/features/work-packages/components/wp-baseline/baseline/baseline.component.sass
  frontend/src/app/features/work-packages/components/wp-breadcrumb/wp-breadcrumb.sass
  frontend/src/app/features/work-packages/components/wp-form-group/wp-attribute-group.component.sass
  frontend/src/app/features/work-packages/routing/partitioned-query-space-page/partitioned-query-space-page.component.sass
  frontend/src/app/features/work-packages/routing/wp-list-view/wp-list-view.component.sass
  frontend/src/app/shared/components/fields/macros/attribute-macro.sass
  frontend/src/app/shared/components/fields/macros/work-package-quickinfo-macro.sass
  frontend/src/app/shared/components/principal/principal.component.sass
  frontend/src/app/shared/components/tabs/tab-badges/tab-count.component.sass
  frontend/src/app/shared/components/time_entries/timer/timer-account-menu.component.sass
  frontend/src/global_styles/content/work_packages/single_view/_single_view.sass
  frontend/src/spot.scss
Labels: maintenance

#15279 Applied retry_on for ManageNextcloudIntegrationJob
  modules/storages/app/common/storages/errors.rb
  modules/storages/app/workers/storages/manage_nextcloud_integration_job.rb
  modules/storages/spec/workers/storages/manage_nextcloud_integration_job_spec.rb
Labels: bugfix, needs review

#15309 Fix meeting being an attachable resource
  frontend/src/app/features/calendar/wp-calendar/wp-calendar.component.ts
  frontend/src/app/features/hal/resources/meeting-resource.ts
Labels: bugfix

#15310 [54184] Progress popover: header font size too big, excessive margins
  app/components/work_packages/progress/status_based/modal_body_component.html.erb
  app/components/work_packages/progress/work_based/modal_body_component.html.erb
  frontend/src/app/shared/components/fields/edit/field-types/progress-popover-edit-field.component.html
  frontend/src/app/shared/components/fields/edit/field-types/progress-popover-edit-field.component.sass
  frontend/src/app/spot/styles/sass/components/drop-modal.sass
Labels: bugfix, styling, needs review

#14907 [#53069] bump xeokit bim viewer version to 2.5.1-beta-18
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/features/bim/bcf/api/bcf-api.model.ts
  frontend/src/app/features/bim/bcf/helper/viewpoints.service.ts
  frontend/src/app/features/bim/ifc_models/ifc-viewer/ifc-viewer.component.ts
  frontend/src/app/features/bim/ifc_models/ifc-viewer/ifc-viewer.service.ts
  frontend/src/app/features/bim/ifc_models/pages/viewer/ifc-models-data.service.ts
  frontend/src/app/features/bim/ifc_models/pages/viewer/styles/tabs.sass
  frontend/src/app/features/bim/ifc_models/pages/viewer/styles/toolbar.sass
  frontend/src/app/features/bim/ifc_models/xeokit/xeokit-server.ts
  modules/bim/app/contracts/bim/bcf/viewpoints/create_contract.rb
  modules/bim/spec/support/pages/ifc_models/show_default.rb
Labels: bugfix, maintenance, pullpreview

#15280 Bug/52098 misleading error message when ifc upload file size exceeds `Setting.attachment_max_size`
  modules/bim/app/services/bim/ifc_models/set_attributes_service.rb
  modules/bim/spec/services/ifc_models/set_attributes_service_spec.rb
Labels: bugfix, needs review

#15301 [fix] replace xeokit toolbar icons with octicons
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/features/bim/ifc_models/ifc-viewer/ifc-viewer.component.html
  frontend/src/app/features/bim/ifc_models/ifc-viewer/ifc-viewer.component.ts
  frontend/src/app/features/bim/ifc_models/openproject-ifc-models.module.ts
  frontend/src/app/features/bim/ifc_models/pages/viewer/ifc-viewer-page.component.ts
  frontend/src/app/features/bim/ifc_models/pages/viewer/styles/toolbar.sass
  frontend/src/app/shared/components/icon/icon.module.ts
Labels: maintenance

#15315 Backfill presenter from author
  modules/meeting/db/migrate/20240313102951_add_presenter_to_meeting.rb
  modules/meeting/db/migrate/20240418110249_set_author_as_presenter.rb
Labels: bugfix, needs review

#15312 [54306] Excessive field length for work/remaining work
  frontend/src/global_styles/content/work_packages/inplace_editing/_display_fields.sass
Labels: bugfix, styling, needs review

#15024 Use capability to identify whether work package create button is available
  frontend/src/app/features/work-packages/components/wp-buttons/wp-create-button/wp-create-button.component.ts
Labels: bugfix

#15320 [53724] ckEditor paragraph toolbar item is cut off in the project custom field dialog
  frontend/src/global_styles/content/editor/_ckeditor.sass
Labels: bugfix, styling, needs review

#15258 Bug/53344 cannot modify a query that was created by a deleted user
  frontend/src/app/features/hal/resources/query-resource.ts
  frontend/src/app/features/work-packages/components/wp-list/wp-list.service.ts
  spec/features/work_packages/table/queries/query_menu_refresh_spec.rb
Labels: needs review

#15319 [54306] Left align the progress modal to the field
  frontend/src/app/shared/components/fields/edit/field-types/progress-popover-edit-field.component.html
  frontend/src/app/spot/components/drop-modal/drop-modal.component.ts
  frontend/src/app/spot/styles/sass/components/drop-modal.sass
Labels: bugfix, styling, needs review

#15298 Documentation 14.0: adding files storages permissions explanation
  docs/system-admin-guide/users-permissions/roles-permissions/README.md
  docs/system-admin-guide/users-permissions/roles-permissions/openproject_user_guide_file_storages_permissions.png
Labels: documentation

#15295 Adding documentation on file storages troubleshooting
  docs/system-admin-guide/file-storages/README.md
  docs/system-admin-guide/file-storages/file-storage-troubleshooting/README.md
  docs/system-admin-guide/file-storages/file-storage-troubleshooting/openproject_file_storages_health_message.png
Labels: documentation

#15296 [#53704] Visible=false project attribute values are deleted when a non-admins edit the attributes
  app/models/projects/acts_as_customizable_patches.rb
  spec/features/projects/project_custom_fields/overview_page/dialog/update_spec.rb
  spec/features/projects/project_custom_fields/overview_page/shared_context.rb
  spec/models/projects/customizable_spec.rb
Labels: bugfix

#15246 [#53788] .ics calendar object does not account for daylight savings time loads incorrectly in MS Outlook
  modules/meeting/app/services/meetings/ical_service.rb
  modules/meeting/spec/services/meetings/ical_service_spec.rb
Labels: bugfix

#15330 Adding 14.0 docs on dynamic meetings
  docs/user-guide/meetings/dynamic-meetings/README.md
  docs/user-guide/meetings/dynamic-meetings/agenda_drag_handle.png
  docs/user-guide/meetings/dynamic-meetings/openproject_dynamic_meetings_add_agenda_item.png
  docs/user-guide/meetings/dynamic-meetings/openproject_dynamic_meetings_attachments.png
  docs/user-guide/meetings/dynamic-meetings/openproject_dynamic_meetings_copy_meeting.png
  docs/user-guide/meetings/dynamic-meetings/openproject_dynamic_meetings_copy_meeting_details.png
  docs/user-guide/meetings/dynamic-meetings/openproject_dynamic_meetings_delete_meeting.png
  docs/user-guide/meetings/dynamic-meetings/openproject_dynamic_meetings_edit_agenda.png
  docs/user-guide/meetings/dynamic-meetings/openproject_dynamic_meetings_meeting_history.png
  docs/user-guide/meetings/dynamic-meetings/openproject_dynamic_meetings_select_meeting_history.png
  docs/user-guide/meetings/dynamic-meetings/openproject_dynamic_meetings_wp_agenda.png
  docs/user-guide/meetings/dynamic-meetings/openproject_userguid_dynamic_meeting_edit_title.png
  docs/user-guide/meetings/dynamic-meetings/openproject_userguide_add_agenda_item.png
  docs/user-guide/meetings/dynamic-meetings/openproject_userguide_add_work_package.png
  docs/user-guide/meetings/dynamic-meetings/openproject_userguide_create_new_meeting.png
  docs/user-guide/meetings/dynamic-meetings/openproject_userguide_dynamic_meetings_overview.png
  docs/user-guide/meetings/dynamic-meetings/openproject_userguide_edit_screen.png
  docs/user-guide/meetings/dynamic-meetings/openproject_userguide_meetings_module_select.png
Labels: documentation

#15338 [#54349] Dragging agenda items to the top not possible on long agendas
  frontend/src/stimulus/controllers/dynamic/meeting-agenda-item-drag-and-drop.controller.ts
Labels: bugfix

#15349 Merge release/14.0 into dev
  app/controllers/work_packages/progress_controller.rb
  config/locales/crowdin/pl.yml
  spec/features/work_packages/progress_modal_spec.rb
  spec/support/edit_fields/progress_edit_field.rb
Labels: create-merge-release-into-dev-pr

#15335 Release Notes 14.0
  docs/release-notes/14-0-0/14-0-project-attributes-administration.png
  docs/release-notes/14-0-0/14-0-project-attributes-sections-highlighted.png
  docs/release-notes/14-0-0/README.md
  docs/release-notes/14-0-0/progress-work-estimates-excludedFromParent.jpg
  docs/release-notes/14-0-0/progress-work-estimates-statusMode.jpg
  docs/release-notes/14-0-0/progress-work-estimates-workMode.jpg
Labels: documentation

#15339 [#53112] 14.0 Documentation: Remove member and revoke shared work pac…
  docs/user-guide/members/README.md
  docs/user-guide/members/confirm-user-deletion.png
  docs/user-guide/members/delete-project-member.png
  docs/user-guide/members/edit-project-member.png
  docs/user-guide/members/filter-project-members.png
  docs/user-guide/members/members-overview-group.png
  docs/user-guide/members/members-overview.png
  docs/user-guide/members/openproject_user_guide_confirm_user_removal_with_shares.png
  docs/user-guide/members/openproject_user_guide_members_remove_work_package_shares.png
  docs/user-guide/work-packages/share-work-packages/README.md
Labels: documentation

#15355 docs update wording
  docs/user-guide/meetings/dynamic-meetings/README.md
Labels: documentation

#15356 Documentation/fixes
  docs/installation-and-operations/configuration/README.md
  docs/release-notes/13-3-0/README.md
  docs/release-notes/13-4-0/README.md
  docs/release-notes/14-0-0/README.md
  docs/release-notes/README.md
  docs/security-and-privacy/processing-of-personal-data/README.md
  docs/system-admin-guide/file-storages/file-storage-troubleshooting/README.md
Labels: documentation

#15357 Last updates to release notes
  docs/release-notes/14-0-0/README.md
Labels: documentation

#15213 [#54275] Live update the work package progress modal with morphing on turbo frame re-rendering.
  app/components/work_packages/progress/base_modal_component.rb
  app/components/work_packages/progress/status_based/modal_body_component.html.erb
  app/components/work_packages/progress/status_based/modal_body_component.rb
  app/components/work_packages/progress/work_based/modal_body_component.html.erb
  app/components/work_packages/progress/work_based/modal_body_component.rb
  app/components/work_packages/share/permission_button_component.rb
  app/controllers/work_packages/progress_controller.rb
  app/forms/work_packages/progress_form.rb
  app/services/work_packages/set_attributes_service.rb
  config/routes.rb
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/core/path-helper/path-helper.service.ts
  frontend/src/app/shared/components/fields/edit/field-types/progress-popover-edit-field.component.ts
  frontend/src/stimulus/controllers/dynamic/work-packages/progress/preview-progress.controller.ts
  frontend/src/stimulus/controllers/dynamic/work-packages/progress/touched-field-marker.controller.ts
  frontend/src/turbo/setup.ts
  lib/api/v3/work_packages/work_package_representer.rb
  spec/features/work_packages/progress_modal_spec.rb
  spec/lib/api/v3/work_packages/work_package_payload_representer_spec.rb
  spec/services/work_packages/set_attributes_service_spec.rb
  spec/support/edit_fields/progress_edit_field.rb
  spec/support/toasts/expectations.rb
  spec/workers/copy_project_job_spec.rb
Labels: feature, pullpreview

#15201 Updated docs for changes to progress calculation (% complete)
  docs/system-admin-guide/manage-work-packages/work-package-settings/README.md
  docs/system-admin-guide/manage-work-packages/work-package-status/README.md
  docs/system-admin-guide/manage-work-packages/work-package-status/Sys-admin-edit-work-package-status.png
  docs/system-admin-guide/manage-work-packages/work-package-status/Sys-admin-work-package-new-status.png
  docs/system-admin-guide/manage-work-packages/work-package-status/Sys-admin-work-package-status.png
  docs/system-admin-guide/manage-work-packages/work-package-status/image-20200211142716298.png
  docs/system-admin-guide/manage-work-packages/work-package-status/openproject_system_guide_create_new_wp_status.png
  docs/system-admin-guide/manage-work-packages/work-package-status/openproject_system_guide_create_wp_stati_dropdown.png
  docs/system-admin-guide/manage-work-packages/work-package-status/openproject_system_guide_edit_new_wp_status.png
  docs/user-guide/time-and-costs/README.md
  docs/user-guide/time-and-costs/progress-tracking/README.md
  docs/user-guide/time-and-costs/progress-tracking/hierarchy-totals.png
  docs/user-guide/time-and-costs/progress-tracking/progress-popover-percentage-complete-only.png
  docs/user-guide/time-and-costs/progress-tracking/progress-popover-status-based.png
  docs/user-guide/time-and-costs/progress-tracking/progress-popover-work-based.png
  docs/user-guide/time-and-costs/progress-tracking/progress-work-estimates-excludedFromParent.png
Labels: documentation

#15361 final 14.0 docs changes
  docs/system-admin-guide/projects/README.md
Labels: documentation

#15374 Update ESLint to a compatible version with current TypeScript
  frontend/package-lock.json
  frontend/package.json
Labels: javascript

#15371 [#54453] Attribute help texts are missing for the Overview sidebar
  frontend/src/app/app.module.ts
  modules/overviews/app/components/project_custom_fields/sections/project_custom_fields/show_component.html.erb
  spec/features/projects/project_custom_fields/overview_page/sidebar_spec.rb
  spec/features/support/components/attribute_help_text_modal.rb
Labels: bugfix

#15384 Fix lookup when assets proxied and manifest present
  app/helpers/frontend_asset_helper.rb
Labels: bugfix

#15383 Feature/54464 snappier progress popover
  app/forms/work_packages/progress_form.rb
  frontend/package-lock.json
  frontend/package.json
  frontend/src/stimulus/controllers/dynamic/work-packages/progress/preview-progress.controller.ts
  frontend/src/turbo/setup.ts
  frontend/src/typings/idiomorph.d.ts
Labels: needs review

#15395 Bump to Primer/ViewComponents 0.29.1
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
  modules/storages/spec/features/storages/admin/create_storage_spec.rb
Labels: maintenance, needs review

#15385 Glossary update for 14.0
  docs/glossary/README.md
Labels: documentation

#15346 [#54347] Open notes for new agenda items
  frontend/src/stimulus/controllers/dynamic/meeting-agenda-item-form.controller.ts
  modules/meeting/app/components/meeting_agenda_items/form_component.html.erb
  modules/meeting/spec/features/structured_meetings/attachment_upload_spec.rb
  modules/meeting/spec/features/structured_meetings/history_spec.rb
Labels: feature, needs review

#15409 [#54380] Set presenter when adding to meeting from work package tab
  modules/meeting/app/controllers/work_package_meetings_tab_controller.rb
  modules/meeting/spec/features/structured_meetings/work_package_meetings_tab_spec.rb
Labels: bugfix, needs review

#15413 Enable YJIT in docker images
  config/initializers/01_enable_yjit.rb
  docs/installation-and-operations/configuration/environment/README.md
Labels: needs review

#15426 update docs
  docs/user-guide/time-and-costs/time-and-costs-faq/README.md
Labels: documentation

#15423 Show icon to add/remove project favorite on index
  app/components/_index.sass
  app/components/projects/row_component.rb
  app/components/projects/row_component.sass
  app/components/projects/table_component.html.erb
  frontend/src/global_styles/primer/_icons.sass
  spec/features/projects/projects_index_spec.rb
  spec/support/pages/projects/index.rb
Labels: feature, needs review

#15418 Blankslate for favorite project header list
  config/locales/js-en.yml
  frontend/src/app/shared/components/header-project-select/header-project-select.component.html
  frontend/src/app/shared/components/header-project-select/header-project-select.component.sass
  frontend/src/app/shared/components/header-project-select/header-project-select.component.ts
Labels: feature, needs review

#15427 Renamed disk usage component
  app/components/projects/disk_usage_information_component.html.erb
  app/components/projects/disk_usage_information_component.rb
  app/components/projects/storage_information_component.html.erb
  app/views/projects/index.html.erb
  config/locales/en.yml
Labels: maintenance

#15381 Add "no permission" message to file links using OneDrive/SharePoint
  modules/storages/app/common/storages/peripherals/storage_interaction/one_drive/file_info_query.rb
  modules/storages/app/common/storages/peripherals/storage_interaction/one_drive/files_info_query.rb
  modules/storages/app/common/storages/peripherals/storage_parent_folder_extractor.rb
  modules/storages/app/models/storages/storage_error_data.rb
  modules/storages/app/models/storages/storage_file_info.rb
  modules/storages/spec/common/storages/peripherals/storage_interaction/one_drive/file_info_query_spec.rb
  modules/storages/spec/common/storages/peripherals/storage_interaction/one_drive/files_info_query_spec.rb
  modules/storages/spec/support/fixtures/vcr_cassettes/one_drive/file_info_query_forbidden.yml
  modules/storages/spec/support/fixtures/vcr_cassettes/one_drive/file_info_query_not_found.yml
  modules/storages/spec/support/fixtures/vcr_cassettes/one_drive/file_info_query_one_not_found.yml
  modules/storages/spec/support/fixtures/vcr_cassettes/one_drive/file_info_query_success_file.yml
  modules/storages/spec/support/fixtures/vcr_cassettes/one_drive/file_info_query_success_folder.yml
  modules/storages/spec/support/fixtures/vcr_cassettes/one_drive/files_info_query_one_not_found.yml
Labels: feature, needs review

#15399 Clean up application loading paths
  modules/reporting/lib/open_project/reporting/engine.rb
Labels: maintenance

#15430 Show no results message in project header if no favored is found
  frontend/src/app/shared/components/header-project-select/header-project-select.component.html
  frontend/src/app/shared/components/header-project-select/header-project-select.component.ts
Labels: bugfix

#15432 fix header levels
  docs/development/concepts/application-architecture/README.md
  docs/development/environments/README.md
  docs/release-notes/10/10-5-0/README.md
  docs/release-notes/4/4-0-3/README.md
  docs/release-notes/9/9-0-1/README.md
Labels: documentation
