Repository opf/openproject, pull requests merged in 2024-06, with the labels that each got.

#15721 [55231] User icon appearing on the share work packages modal in the empty state
  app/components/work_packages/share/share_counter_component.html.erb
Labels: bugfix

#15723 Fix typo in migration
  db/migrate/20230731153909_add_file_link_journals_to_existing_containers.rb
Labels: needs review

#15688 Removes the link around the table text
  modules/storages/app/views/storages/storages_mailer/_health_status_notification.html.erb
  modules/storages/app/workers/storages/health_status_mailer_job.rb
Labels: needs review

#15726 Add DATO-IT integration to docs
  docs/system-admin-guide/integrations/README.md
Labels: documentation

#15728 [55300] Selected item in the side menu is not highlighted in high contrast mode
  app/views/custom_styles/_primer_color_mapping.erb
  frontend/src/global_styles/layout/_main_menu.sass
Labels: bugfix, needs review

#15727 [50724] Show notifications button correctly on mobile
  frontend/src/global_styles/content/_forms_mobile.sass
Labels: bugfix, needs review

#15730 [55169] Meetings participants toggle has the wrong color
  app/views/custom_styles/_primer_color_mapping.erb
Labels: bugfix, needs review

#15724 [55344] Fix close button label of drop-modal
  config/locales/js-en.yml
Labels: needs review

#15729 Update Ruby to 3.3.2
  .github/workflows/danger.yml
  .ruby-version
  Gemfile.lock
  docker/ci/Dockerfile
  docker/dev/backend/Dockerfile
  docker/prod/Dockerfile
  docs/development/development-environment-osx/README.md
  docs/development/development-environment-ubuntu/README.md
  docs/installation-and-operations/installation/manual/README.md
  script/github_pr_errors
Labels: needs review

#15743 Sync `package-lock.json` with `package.json`
  frontend/package-lock.json
Labels: needs review

#15752 Bump octicons to 19.14.0 and view_components to 0.33.1
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: maintenance

#15700 Implementation/54749 create add project modal
  app/components/_index.sass
  app/components/settings/project_custom_fields/project_custom_field_mapping/new_project_mapping_component.html.erb
  app/components/settings/project_custom_fields/project_custom_field_mapping/new_project_mapping_component.rb
  app/components/settings/project_custom_fields/project_custom_field_mapping/new_project_mapping_component.sass
  app/components/settings/project_custom_fields/project_custom_field_mapping/row_component.html.erb
  app/controllers/admin/settings/project_custom_fields_controller.rb
  app/forms/projects/custom_fields/custom_field_mapping_form.rb
  app/models/permitted_params.rb
  app/services/project_custom_field_project_mappings/bulk_create_service.rb
  app/views/admin/settings/project_custom_fields/project_mappings.html.erb
  config/initializers/primer_forms.rb
  config/locales/en.yml
  config/routes.rb
  frontend/src/stimulus/controllers/dynamic/projects/settings/available-project-mappings-filter.controller.ts
  spec/features/admin/project_custom_fields/project_mappings_spec.rb
  spec/services/project_custom_field_project_mappings/bulk_create_service_spec.rb
Labels: feature, needs review

#15760 [55467] Warn about potential data loss when changing progress modes
  app/views/admin/settings/work_packages_settings/show.html.erb
  app/views/admin/settings/working_days_and_hours_settings/show.html.erb
  config/locales/js-en.yml
  frontend/src/stimulus/controllers/dynamic/admin/work-packages-settings.controller.ts
  frontend/src/stimulus/controllers/op-application.controller.ts
Labels: ruby, needs review

#15761 [#55429] Only display "working/non-working days changed warning" when they actually change
  frontend/src/app/shared/components/op-non-working-days-list/op-non-working-days-list.component.ts
  spec/features/admin/working_days_spec.rb
Labels: bugfix

#15768 [#53987] 🇺🇦 Use different Ukraine supporting logos.
  app/assets/images/logo-black-bg-ua.png
  app/assets/images/logo-white-bg-ua.png
Labels: pullpreview

#15771 Do not trigger development seeders if installation is obviously old
  app/seeders/development_data/projects_seeder.rb
Labels: needs review

#15767 [#55495] 14.2 Documentation: Allow renaming persisted project lists …
  docs/system-admin-guide/integrations/excel-synchronization/README.md
  docs/system-admin-guide/integrations/excel-synchronization/image-20211014153150017.png
  docs/user-guide/projects/project-lists/README.md
  docs/user-guide/projects/project-lists/private-project-filter-rename-delete.png
Labels: documentation

#15769 [#55493] 14.2 Documentation: Transform remove action from share modals…
  docs/user-guide/work-packages/share-work-packages/openproject_user_guide_share_button_wp.png
  docs/user-guide/work-packages/share-work-packages/openproject_user_guide_share_button_wp_numbers.png
  docs/user-guide/work-packages/share-work-packages/openproject_user_guide_shared_search.png
  docs/user-guide/work-packages/share-work-packages/openproject_user_guide_shared_with_list.png
  docs/user-guide/work-packages/share-work-packages/openproject_user_guide_shared_with_list_change_role.png
  docs/user-guide/work-packages/share-work-packages/openproject_user_guide_shared_with_users_filter_new.png
Labels: documentation

#15781 [Bug] Autocompleter height does not grow with the items
  frontend/src/global_styles/content/_autocomplete_primerized.sass
Labels: bugfix, needs review

#15778 Lookbook documentation for SubHeader component
  lookbook/docs/patterns/10-page-header.md.erb
  lookbook/docs/patterns/11-sub-header.md.erb
  lookbook/previews/open_project/common/page_header_preview.rb
  lookbook/previews/open_project/common/sub_header_preview.rb
Labels: documentation

#15792 [#55489] 14.2 Documentation: Embedded work package attributes in PDF …
  docs/user-guide/work-packages/exporting/README.md
Labels: documentation

#15780 Task/55517 remove filter from `14.2` pending a more complete solution
  app/components/settings/project_custom_fields/project_custom_field_mapping/row_component.html.erb
  app/views/admin/settings/project_custom_fields/project_mappings.html.erb
  config/locales/en.yml
  frontend/src/stimulus/controllers/dynamic/projects/settings/available-project-mappings-filter.controller.ts
Labels: needs review

#15777 Remove icon generator script for deprecated icon font
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/spot/icon-font/README.md
  frontend/src/app/spot/icon-font/generate.js
  nix/shell.nix
Labels: maintenance, needs review

#15803 [#55254] Switch to show favorite projects is shown for anonymous user
  frontend/src/app/shared/components/header-project-select/header-project-select.component.html
  spec/features/projects/favorite_spec.rb
Labels: needs review

#15797 Fix send_notifications being ignored when copying meetings
  modules/meeting/app/controllers/meetings_controller.rb
  modules/meeting/spec/requests/meetings_spec.rb
Labels: bugfix

#15804 Allow user groups to be visible on profile page so that project admins can identify them
  app/controllers/users_controller.rb
  app/views/users/show.html.erb
  spec/features/users/show_spec.rb
  spec/views/users/show.html.erb_spec.rb
Labels: bugfix, needs review

#15812 [#55268] PDF report: multi column table with pictures not included
  Gemfile
  Gemfile.lock
Labels: bugfix, pullpreview, needs review

#15756 [55482] Replace old icons with Octicons in the main menu
  app/views/admin/index.html.erb
  config/initializers/menus.rb
  frontend/src/global_styles/common/header/app-help.sass
  frontend/src/global_styles/common/header/index.sass
  frontend/src/global_styles/common/menu/menu.sass
  frontend/src/global_styles/content/menus/_menu_blocks.sass
  lib/redmine/menu_manager/menu_helper.rb
  lib/redmine/menu_manager/top_menu/help_menu.rb
  lib/redmine/menu_manager/wiki_menu_helper.rb
  modules/avatars/lib/open_project/avatars/engine.rb
  modules/backlogs/lib/open_project/backlogs/engine.rb
  modules/bim/lib/open_project/bim/engine.rb
  modules/boards/lib/open_project/boards/engine.rb
  modules/budgets/lib/budgets/engine.rb
  modules/dashboards/lib/dashboards/engine.rb
  modules/documents/lib/open_project/documents/engine.rb
  modules/gantt/lib/open_project/gantt/engine.rb
  modules/github_integration/lib/open_project/github_integration/engine.rb
  modules/meeting/lib/open_project/meeting/engine.rb
  modules/overviews/lib/overviews/engine.rb
  modules/reporting/lib/open_project/reporting/engine.rb
  modules/storages/lib/open_project/storages/engine.rb
  modules/team_planner/lib/open_project/team_planner/engine.rb
  modules/two_factor_authentication/lib/open_project/two_factor_authentication/engine.rb
  spec/controllers/admin_controller_spec.rb
Labels: maintenance

#15819 Remove ui-router from projects
  app/views/projects/copy.html.erb
  app/views/projects/new.html.erb
  app/views/projects/settings/general/show.html.erb
  frontend/src/app/app.module.ts
  frontend/src/app/core/routing/openproject.routes.ts
  frontend/src/app/features/projects/components/copy-project/copy-project.component.ts
  frontend/src/app/features/projects/components/new-project/new-project.component.ts
  frontend/src/app/features/projects/components/projects/projects.component.ts
  frontend/src/app/features/projects/openproject-projects.module.ts
  frontend/src/app/features/projects/projects-routes.ts
  spec/features/menu_items/menu_permissions_spec.rb
Labels: maintenance, needs review

#15833 Update Rubocop gems and properly load them
  .rubocop.yml
  Gemfile
  Gemfile.lock
Labels: dependencies, ruby, needs review

#15832 update migration script, specifically fix the OP7 step
  script/migration/migrate-from-pre-8.sh
Labels: needs review

#15831 disable direct login provider if value is empty
  app/helpers/omniauth_helper.rb
  spec/controllers/account_controller_spec.rb
Labels: bugfix, needs review

#15820 [#55523] make add projects dialog mobile friendly
  app/components/settings/project_custom_fields/project_custom_field_mapping/new_project_mapping_component.html.erb
  app/forms/projects/custom_fields/custom_field_mapping_form.rb
  frontend/src/global_styles/primer/_overrides.sass
Labels: needs review

#15782 [#55507] Make it possible to activate custom fields on multiple projects at the same time
  app/controllers/admin/settings/project_custom_fields_controller.rb
  app/forms/projects/custom_fields/custom_field_mapping_form.rb
  app/services/project_custom_field_project_mappings/bulk_create_service.rb
  spec/services/project_custom_field_project_mappings/bulk_create_service_spec.rb
Labels: bugfix

#15823 Remove ui-router from backlogs
  app/helpers/frontend_asset_helper.rb
  frontend/angular.json
  frontend/src/app/core/routing/openproject.routes.ts
  frontend/src/app/core/setup/global-dynamic-components.const.ts
  frontend/src/app/features/backlogs/backlogs-page/backlogs-page.component.ts
  frontend/src/app/features/backlogs/openproject-backlogs.module.ts
  frontend/src/app/features/backlogs/openproject-backlogs.routes.ts
  frontend/src/assets/sass/backlogs/_dialogues.sass
  frontend/src/assets/sass/backlogs/_global.css
  frontend/src/assets/sass/backlogs/_global_print.css
  frontend/src/assets/sass/backlogs/_index.sass
  frontend/src/assets/sass/backlogs/_jqplot.css
  frontend/src/assets/sass/backlogs/_master_backlog.sass
  frontend/src/assets/sass/backlogs/_statistics.css
  frontend/src/assets/sass/backlogs/_taskboard.sass
  frontend/src/backlogs.scss
  frontend/src/global_styles/openproject/_index.sass
  modules/backlogs/app/views/layouts/backlogs.html.erb
Labels: maintenance, needs review

#15824 Replace ui-router in My account
  app/controllers/my_controller.rb
  app/views/layouts/angular/angular.html.erb
  app/views/users/_notifications.html.erb
  app/views/users/_reminders.html.erb
  frontend/src/app/app.module.ts
  frontend/src/app/core/routing/openproject.routes.ts
  frontend/src/app/features/user-preferences/notifications-settings/overdue-reminder-available-times.ts
  frontend/src/app/features/user-preferences/notifications-settings/page/notifications-settings-page.component.ts
  frontend/src/app/features/user-preferences/notifications-settings/table/notification-settings-table.component.ts
  frontend/src/app/features/user-preferences/reminder-settings/page/reminder-settings-page.component.ts
  frontend/src/app/features/user-preferences/user-preferences.lazy-routes.ts
  frontend/src/app/features/user-preferences/user-preferences.module.ts
  frontend/src/app/features/user-preferences/user-preferences.routes.ts
Labels: maintenance, needs review

#15846 [#55678] Rename "Projects" tab to "Enabled in projects"
  app/components/settings/project_custom_fields/edit_form_header_component.html.erb
  config/locales/en.yml
  spec/features/admin/project_custom_fields/edit_spec.rb
  spec/features/admin/project_custom_fields/project_mappings_spec.rb
Labels: bugfix, needs review

#15765 Add week support of Gantt PDF export.
  app/models/work_package/pdf_export/gantt.rb
  app/models/work_package/pdf_export/gantt/gantt_builder.rb
  app/models/work_package/pdf_export/gantt/gantt_builder_weeks.rb
  frontend/src/app/shared/components/modals/export-modal/wp-table-export.modal.ts
Labels: contribution

#15842 [#55502] Sorting suggested to be possible when it isn't
  app/components/projects/table_component.rb
  app/components/settings/project_custom_fields/project_custom_field_mapping/table_component.rb
Labels: needs review

#15862 Bug/55505 Reinstate listing archived projects in project attributes "enabled in projects" page, just disable the "Deactivate in project" option
  app/components/settings/project_custom_fields/project_custom_field_mapping/row_component.rb
  app/controllers/admin/settings/project_custom_fields_controller.rb
  spec/features/admin/project_custom_fields/project_mappings_spec.rb
Labels: bugfix, needs review

#15868 Merge release/14.2 into dev
  app/components/settings/project_custom_fields/project_custom_field_mapping/row_component.rb
  app/controllers/admin/settings/project_custom_fields_controller.rb
  config/initializers/appsignal.rb
  frontend/src/app/shared/components/storages/functions/storages.functions.ts
  modules/storages/app/common/storages/peripherals/storage_interaction/nextcloud/file_info_query.rb
  modules/storages/app/common/storages/peripherals/storage_interaction/one_drive/file_info_query.rb
  modules/storages/app/common/storages/peripherals/storage_interaction/one_drive/util.rb
  modules/storages/spec/common/storages/peripherals/storage_interaction/one_drive/file_info_query_spec.rb
  modules/storages/spec/common/storages/peripherals/storage_interaction/one_drive/files_info_query_spec.rb
  spec/features/admin/project_custom_fields/project_mappings_spec.rb
Labels: create-merge-release-into-dev-pr

#15632 Get rid of manual html_safe calls in reporting
  modules/reporting/app/helpers/reporting_helper.rb
  modules/reporting/app/views/cost_reports/index.html.erb
  modules/reporting/lib/report/result.rb
  modules/reporting/lib/widget/base.rb
  modules/reporting/lib/widget/controls/save_as.rb
  modules/reporting/lib/widget/cost_types.rb
  modules/reporting/lib/widget/filters.rb
  modules/reporting/lib/widget/filters/heavy.rb
  modules/reporting/lib/widget/filters/multi_choice.rb
  modules/reporting/lib/widget/filters/operators.rb
  modules/reporting/lib/widget/filters/option.rb
  modules/reporting/lib/widget/group_bys.rb
  modules/reporting/lib/widget/reporting_widget.rb
  modules/reporting/lib/widget/table.rb
  modules/reporting/lib/widget/table/entry_table.rb
  modules/reporting/lib/widget/table/report_table.rb
Labels: maintenance, needs review

#15869 Archvied projects are no longer visible for non-admins
  spec/features/projects/persisted_lists_spec.rb
Labels: needs review

#15851 [#55523] Add Dialog not mobile friendly: don't center align on mobile
  frontend/src/global_styles/primer/_overrides.sass
Labels: needs review

#15860 Bug/55504 changing page sizepage after removing a project from an project attribute leads to page not found
  app/components/projects/table_component.html.erb
  app/components/projects/table_component.rb
  app/components/settings/project_custom_fields/project_custom_field_mapping/table_component.rb
  app/controllers/admin/settings/project_custom_fields_controller.rb
  spec/features/admin/project_custom_fields/project_mappings_spec.rb
Labels: bugfix, needs review

#15835 [#55487] 14.2 Documentation: Progress reporting changes https://comm…
  docs/release-notes/12/12-3-0/README.md
  docs/system-admin-guide/calendars-and-dates/README.md
  docs/system-admin-guide/calendars-and-dates/add-non-working-day-link.png
  docs/system-admin-guide/calendars-and-dates/add-working-day-modal.png
  docs/system-admin-guide/calendars-and-dates/admin-working-days-hours.png
  docs/system-admin-guide/calendars-and-dates/admin-working-days.png
  docs/system-admin-guide/calendars-and-dates/apply-changes-button.png
  docs/system-admin-guide/calendars-and-dates/calendar-subscriptions.png
  docs/system-admin-guide/calendars-and-dates/date-format.png
  docs/system-admin-guide/manage-work-packages/work-package-settings/README.md
  docs/system-admin-guide/manage-work-packages/work-package-settings/openproject_system_guide_work_package_settings_warning.png
  docs/system-admin-guide/manage-work-packages/work-package-status/README.md
  docs/system-admin-guide/manage-work-packages/work-package-status/openproject_system_guide_create_new_wp_status.png
  docs/user-guide/calendar/README.md
  docs/user-guide/calendar/calendar-faq/README.md
  docs/user-guide/team-planner/README.md
  docs/user-guide/time-and-costs/progress-tracking/README.md
  docs/user-guide/time-and-costs/progress-tracking/hierarchy-totals-days.png
  docs/user-guide/time-and-costs/progress-tracking/hierarchy-totals.png
  docs/user-guide/time-and-costs/progress-tracking/progress-popover-percentage-complete-only.png
  docs/user-guide/time-and-costs/progress-tracking/progress-popover-status-based-days.png
  docs/user-guide/time-and-costs/progress-tracking/progress-popover-status-based.png
  docs/user-guide/time-and-costs/progress-tracking/progress-popover-work-based-days.png
  docs/user-guide/time-and-costs/progress-tracking/progress-popover-work-based.png
  docs/user-guide/time-and-costs/progress-tracking/progress-work-estimates-excludedFromParent-days.png
  docs/user-guide/work-packages/set-change-dates/README.md
Labels: documentation

#15805 [#55483] Project custom field of type link not listed in project settings
  frontend/src/app/core/forms/typings.d.ts
  frontend/src/app/shared/components/dynamic-forms/services/dynamic-fields/dynamic-fields.service.ts
  spec/features/projects/project_custom_fields/settings/mapping_spec.rb
Labels: needs review

#15870 Glossary update for 14.2
  docs/glossary/README.md
Labels: documentation

#15817 Update Release Notes 14.2.md
  docs/release-notes/14-2-0/README.md
  docs/release-notes/14-2-0/openproject-14-2-changing-work-based-status-based-progress-reporting.png
  docs/release-notes/14-2-0/openproject-14-2-pdf-export-attributes.png
  docs/release-notes/14-2-0/openproject-14-2-progress-reporting-work-package-table-highlighted.png
  docs/release-notes/14-2-0/openproject-14-2-project-attributes-settings-highlighted.png
  docs/release-notes/14-2-0/openproject-14-2-rename-persisted-lists.png
  docs/release-notes/14-2-0/openproject-14-2-working-days-and-hours.png
  docs/release-notes/14-2-0/openproject-14-2meeting-invitation-mail-highlighted.png
Labels: documentation

#15872 [53989] Use Octicons inside the GitLab plugin
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/shared/components/icon/icon.module.ts
  modules/gitlab_integration/frontend/module/gitlab-tab/gitlab-tab.template.html
  modules/gitlab_integration/frontend/module/icons/gitlab-icons.svg
  modules/gitlab_integration/frontend/module/issue/issue.component.html
  modules/gitlab_integration/frontend/module/issue/issue.component.sass
  modules/gitlab_integration/frontend/module/merge-request/merge-request.component.html
  modules/gitlab_integration/frontend/module/merge-request/merge-request.component.sass
  modules/gitlab_integration/frontend/module/merge-request/merge-request.component.ts
  modules/gitlab_integration/frontend/module/tab-header-issue/tab-header-issue.template.html
  modules/gitlab_integration/frontend/module/tab-header-mr/tab-header-mr.template.html
Labels: maintenance

#15821 [#55621] Presenter field on agenda item becomes tiny if the current presenter is removed and a new one is searched for
  modules/meeting/app/components/meeting_agenda_items/form_component.sass
Labels: bugfix, needs review

#15866 [#55488] 14.2 Documentation: Configure which projects are activated f…
  docs/system-admin-guide/projects/project-attributes/README.md
  docs/system-admin-guide/projects/project-attributes/open_project_system_admin_guide_project_attributes_add.png
  docs/system-admin-guide/projects/project-attributes/open_project_system_admin_guide_project_attributes_deactivate_for_project.png
  docs/system-admin-guide/projects/project-attributes/open_project_system_admin_guide_project_attributes_details.png
  docs/system-admin-guide/projects/project-attributes/open_project_system_admin_guide_project_attributes_enabled_in_projects.png
Labels: documentation

#15884 update sponsors
  docs/release-notes/14-2-0/README.md
Labels: documentation

#15871 Makes sure Commands/Queries handle 403 responses
  modules/storages/app/common/storages/peripherals/storage_interaction/one_drive/auth_check_query.rb
  modules/storages/app/common/storages/peripherals/storage_interaction/one_drive/create_folder_command.rb
  modules/storages/app/common/storages/peripherals/storage_interaction/one_drive/download_link_query.rb
  modules/storages/app/common/storages/peripherals/storage_interaction/one_drive/files_query.rb
  modules/storages/app/common/storages/peripherals/storage_interaction/one_drive/open_file_link_query.rb
  modules/storages/app/common/storages/peripherals/storage_interaction/one_drive/open_storage_query.rb
  modules/storages/app/common/storages/peripherals/storage_interaction/one_drive/rename_file_command.rb
  modules/storages/app/common/storages/peripherals/storage_interaction/one_drive/set_permissions_command.rb
  modules/storages/app/common/storages/peripherals/storage_interaction/one_drive/upload_link_query.rb
  modules/storages/app/common/storages/peripherals/storage_interaction/one_drive/util.rb
  modules/storages/app/services/storages/one_drive_managed_folder_sync_service.rb
  modules/storages/spec/common/storages/peripherals/storage_interaction/one_drive/files_query_spec.rb
  modules/storages/spec/common/storages/peripherals/storage_interaction/one_drive/open_file_link_query_spec.rb
  modules/storages/spec/services/storages/one_drive_managed_folder_sync_service_spec.rb
Labels: needs review

#15883 Add correct join for sorting by latest project activity
  app/models/projects/storage.rb
  app/models/queries/projects/orders/latest_activity_at_order.rb
  app/models/queries/projects/orders/required_disk_space_order.rb
  spec/features/projects/projects_index_spec.rb
  spec/models/queries/projects/orders/latest_activity_at_order_spec.rb
  spec/models/queries/projects/orders/required_disk_space_order_spec.rb
Labels: bugfix, needs review

#15849 [55640] Provide rails-based 100% layout with optional split view
  app/components/projects/table_component.rb
  app/views/layouts/base.html.erb
  app/views/members/index.html.erb
  frontend/src/app/features/bim/ifc_models/pages/viewer/styles/generic.sass
  frontend/src/app/features/work-packages/components/wp-breadcrumb/wp-breadcrumb.sass
  frontend/src/assets/sass/backlogs/_master_backlog.sass
  frontend/src/assets/sass/backlogs/_taskboard.sass
  frontend/src/global_styles/content/_grid.sass
  frontend/src/global_styles/content/_journal.sass
  frontend/src/global_styles/content/_table.sass
  frontend/src/global_styles/content/modules/_boards.sass
  frontend/src/global_styles/content/modules/_calendar.sass
  frontend/src/global_styles/content/modules/_index.sass
  frontend/src/global_styles/content/modules/_team_planner.sass
  frontend/src/global_styles/layout/_base.sass
  frontend/src/global_styles/layout/_base_mobile.sass
  frontend/src/global_styles/layout/_breadcrumb.sass
  frontend/src/global_styles/layout/_main_menu.sass
  frontend/src/global_styles/layout/_print.sass
  frontend/src/global_styles/layout/_toolbar_mobile.sass
  frontend/src/global_styles/layout/_zen_mode.sass
  frontend/src/global_styles/layout/work_packages/_mobile.sass
  frontend/src/global_styles/layout/work_packages/_table.sass
  frontend/src/global_styles/openproject/_generic.sass
  frontend/src/global_styles/openproject/_homescreen.sass
  frontend/src/global_styles/openproject/_mixins.sass
  modules/storages/app/views/storages/admin/storages/index.html.erb
Labels: feature

#15896 Split up API requests for relations in gantt chart
  frontend/src/app/core/apiv3/endpoints/relations/apiv3-relations-paths.ts
Labels: bugfix

#15900 Fix meeting sortBy type
  modules/meeting/app/components/meetings/table_component.rb
  modules/meeting/spec/requests/meetings_spec.rb
Labels: bugfix, needs review

#15901 Merge release/14.2 into dev
  docs/release-notes/14-2-0/README.md
  docs/release-notes/README.md
  frontend/src/app/core/apiv3/endpoints/relations/apiv3-relations-paths.ts
Labels: create-merge-release-into-dev-pr

#15897 Update Ruby to 3.3.3
  .github/workflows/danger.yml
  .ruby-version
  Gemfile.lock
  docker/ci/Dockerfile
  docker/dev/backend/Dockerfile
  docker/prod/Dockerfile
  docs/development/development-environment-osx/README.md
  docs/development/development-environment-ubuntu/README.md
  docs/installation-and-operations/installation/manual/README.md
  script/github_pr_errors
Labels: needs review

#15911 Allow smtp_timeout to be set to anything != 5 seconds
  app/models/setting/mail_settings.rb
  config/constants/settings/definition.rb
  spec/models/setting_spec.rb
Labels: feature

#15893 Handle errors when Copying Project Folders when the Storage is broken
  modules/storages/app/common/storages/peripherals/storage_interaction/nextcloud/copy_template_folder_command.rb
  modules/storages/app/common/storages/peripherals/storage_interaction/nextcloud/util.rb
  modules/storages/app/common/storages/peripherals/storage_interaction/one_drive/copy_template_folder_command.rb
  modules/storages/app/services/storages/project_storages/copy_project_folders_service.rb
  modules/storages/app/workers/storages/copy_project_folders_job.rb
  modules/storages/spec/common/storages/peripherals/storage_interaction/nextcloud/copy_template_folder_command_spec.rb
  modules/storages/spec/common/storages/peripherals/storage_interaction/one_drive/copy_template_folder_command_spec.rb
  modules/storages/spec/services/storages/project_storages/copy_project_folders_service_spec.rb
  modules/storages/spec/workers/storages/copy_project_folders_job_spec.rb
Labels: bugfix, needs review

#15910 [55874][55812] Page width is too large if the content is wide
  frontend/src/global_styles/layout/_base.sass
Labels: bugfix, styling, needs review

#15907 Allow static widgets to be available to non-members
  config/initializers/permissions.rb
  frontend/src/app/features/boards/board/board-list/board-list-menu.component.html
  frontend/src/app/shared/components/grids/widgets/menu/widget-abstract-menu.component.ts
  frontend/src/app/shared/components/grids/widgets/menu/widget-menu.component.html
  frontend/src/app/shared/components/grids/widgets/menu/wp-set-menu.component.ts
  frontend/src/app/shared/components/grids/widgets/project-details/project-details-menu.component.ts
  frontend/src/app/shared/components/grids/widgets/time-entries/current-user/time-entries-current-user-menu.component.ts
  frontend/src/app/shared/components/grids/widgets/wp-table/wp-table-menu.component.ts
  frontend/src/app/shared/components/op-context-menu/icon-triggered-context-menu/icon-triggered-context-menu.component.ts
  modules/my_page/lib/my_page/grid_registration.rb
  modules/my_page/spec/features/my/work_package_watcher_widget_spec.rb
Labels: bugfix

#15919 [Bug #55901] 403 when entering the overview page of a project in which a work package is shared with the current user
  modules/overviews/lib/overviews/engine.rb
  spec/features/work_packages/share/access_spec.rb
Labels: needs review

#15916 Stop interrupting the sync process on error.
  modules/storages/app/common/storages/errors.rb
  modules/storages/app/workers/storages/manage_storage_integrations_job.rb
  modules/storages/spec/workers/storages/manage_storage_integrations_job_spec.rb
Labels: bugfix, needs review

#15935 [55657] Page title is wrong on project attributes settings page
  app/views/admin/settings/new_project_settings/show.html.erb
  app/views/admin/settings/project_custom_fields/edit.html.erb
  app/views/admin/settings/project_custom_fields/new.html.erb
  app/views/admin/settings/projects_settings/show.html.erb
Labels: bugfix, needs review

#15933 [55447] Individual work packages in ID filter cannot be removed
  frontend/src/app/shared/components/autocompleter/op-autocompleter/op-autocompleter.component.html
  frontend/src/app/shared/components/autocompleter/project-autocompleter/project-autocompleter-template.component.html
Labels: bugfix, needs review

#15939 [55914] Star for favourite projects is black
  frontend/src/app/features/work-packages/components/wp-card-view/wp-single-card/wp-single-card.component.sass
  frontend/src/app/shared/components/op-content-loader/op-content-loader.component.html
  frontend/src/assets/sass/backlogs/_taskboard.sass
  frontend/src/global_styles/content/_datepicker.sass
  frontend/src/global_styles/content/_progress_bar.sass
  frontend/src/global_styles/content/modules/_costs.sass
  frontend/src/global_styles/primer/_icons.sass
Labels: bugfix, styling

#15928 Use custom element for op-attachments
  app/helpers/attachments_helper.rb
  frontend/src/app/app.module.ts
  frontend/src/app/core/setup/global-dynamic-components.const.ts
  frontend/src/app/shared/components/attachments/attachments.component.ts
Labels: bugfix, needs review

#15936 Prevent recursive attribute macros
  config/locales/js-en.yml
  frontend/src/app/shared/components/fields/macros/attribute-value-macro.component.ts
  spec/features/wysiwyg/macros/attribute_macros_spec.rb
Labels: bugfix, needs review

#15887 [#55771] Warn user that the type is not available when moving a work package
  app/controllers/work_packages/moves_controller.rb
  app/views/work_packages/moves/new.html.erb
  config/locales/en.yml
Labels: bugfix

#15945 Always go to global boards in top_menu
  modules/boards/lib/open_project/boards/engine.rb
Labels: bugfix

#15941 [55919] Gantt elements overlap the header
  frontend/src/global_styles/content/work_packages/timelines/_timelines_header.sass
Labels: bugfix, styling

#15944 [55922] Projects list drop down cut off in memberships page
  app/views/groups/_memberships.html.erb
  app/views/groups/_users.html.erb
  app/views/individual_principals/_memberships.html.erb
  frontend/src/global_styles/layout/_grid.sass
Labels: bugfix, styling

#15940 [55775] Fix some issues in dark mode
  app/views/custom_styles/_primer_color_mapping.erb
  frontend/src/app/features/team-planner/team-planner/add-work-packages/add-existing-pane.component.sass
  frontend/src/app/features/team-planner/team-planner/planner/team-planner.component.sass
  frontend/src/app/spot/styles/sass/components/form-field.sass
  frontend/src/global_styles/content/_activity_list.sass
  frontend/src/global_styles/content/_autocomplete.sass
  frontend/src/global_styles/content/_grid.sass
  frontend/src/global_styles/content/_hide_section.sass
  frontend/src/global_styles/openproject/_forms.sass
  frontend/src/global_styles/openproject/_variable_defaults.scss
Labels: bugfix, styling, needs review

#15801 Bug/53772 the label for spent time is still visible after deactiving the module time and costs active modules
  app/controllers/groups_controller.rb
  app/models/project.rb
  app/models/users/permission_checks.rb
  app/services/authorization/user_permissible_service.rb
  lib/open_project/access_control/permission.rb
  modules/boards/spec/features/menu_items/global_menu_item_spec.rb
  modules/boards/spec/features/menu_items/top_menu_item_spec.rb
  modules/meeting/spec/controllers/meetings_controller_spec.rb
  modules/meeting/spec/features/meetings_global_menu_item_spec.rb
  modules/reporting/spec/features/top_menu_item_spec.rb
  modules/reporting/spec/workers/cost_query/export_job_spec.rb
  spec/controllers/activities_controller_spec.rb
  spec/controllers/news_controller_spec.rb
  spec/features/custom_fields/create_long_text_spec.rb
  spec/features/news/global_menu_item_spec.rb
  spec/features/projects/global_menu_item_spec.rb
  spec/features/types/form_configuration_spec.rb
  spec/features/work_packages/work_package_index_spec.rb
  spec/lib/open_project/access_control/permission_spec.rb
  spec/models/users/permission_checks_spec.rb
  spec/models/work_packages/scopes/allowed_to_spec.rb
  spec/requests/rate_limiting/api_v3_rate_limiting_spec.rb
  spec/services/authorization/user_permissible_service_spec.rb
Labels: needs review

#15952 Fix type-reassignment warning message being shown in cases where it shouldn't
  app/controllers/work_packages/moves_controller.rb
Labels: bugfix

#15956 Merge release/14.2 into dev
  app/views/custom_styles/_inline_css_logo.erb
  docs/user-guide/file-management/nextcloud-integration/README.md
Labels: create-merge-release-into-dev-pr

#15946 [55786] Main menu resizer handle icon change on hover not working for Safari
  frontend/src/global_styles/layout/_main_menu.sass
Labels: bugfix, styling, needs review

#15966 minor doc update
  docs/user-guide/projects/project-lists/README.md
Labels: documentation

#15967 feat(docs): document support for github markdown alerts
  docs/development/contribution-documentation/documentation-style-guide/README.md
Labels: documentation

#15984 chore: bump md-to-pdf to v0.1.1
  Gemfile
  Gemfile.lock
  app/models/work_package/pdf_export/markdown.rb
  app/models/work_package/pdf_export/schema.json
  app/models/work_package/pdf_export/standard.yml
  docs/system-admin-guide/design/pdf-export-styles/README.md
Labels: needs review

#15983 Move ProjectQuery model to the main namespace
  app/components/projects/delete_list_modal_component.html.erb
  app/components/projects/index_page_header_component.html.erb
  app/contracts/queries/projects/project_queries/base_contract.rb
  app/controllers/admin/settings/project_custom_fields_controller.rb
  app/controllers/projects/queries_controller.rb
  app/forms/queries/projects/form.rb
  app/helpers/menus/projects.rb
  app/helpers/projects_helper.rb
  app/models/member.rb
  app/models/project_queries/scopes/allowed_to.rb
  app/models/project_query.rb
  app/models/queries/projects/factory.rb
  app/models/user.rb
  app/services/params_to_query_service.rb
  app/services/queries/projects/project_queries/create_service.rb
  app/views/projects/index.html.erb
  app/workers/projects/export_job.rb
  config/constants/settings/definition.rb
  config/routes.rb
  lib/open_project/access_control/permission.rb
  lookbook/previews/open_project/filter/filter_button_component_preview.rb
  lookbook/previews/open_project/filter/filters_component_preview.rb
  lookbook/previews/open_project/queries/sort_by_component_preview.rb
  modules/storages/lib/open_project/storages/engine.rb
  spec/contracts/queries/projects/project_queries/create_contract_spec.rb
  spec/contracts/queries/projects/project_queries/loading_contract_spec.rb
  spec/contracts/queries/projects/project_queries/update_contract_spec.rb
  spec/controllers/projects/queries_controller_spec.rb
  spec/factories/principal_factory.rb
  spec/factories/queries/project_query_factory.rb
  spec/helpers/menus/projects_spec.rb
  spec/helpers/projects_helper_spec.rb
  spec/lib/open_project/access_control/permission_spec.rb
  spec/models/project_queries/scopes/allowed_to_spec.rb
  spec/models/queries/projects/factory_spec.rb
  spec/models/queries/projects/filters/custom_field_filter_spec.rb
  spec/models/queries/projects/project_query_results_spec.rb
  spec/models/queries/projects/project_query_spec.rb
  spec/routing/project_queries_routing_spec.rb
  spec/services/params_to_query_service_project_query_spec.rb
  spec/services/queries/projects/project_queries/create_service_spec.rb
  spec/services/queries/projects/project_queries/set_attributes_service_spec.rb
  spec/workers/principals/delete_job_integration_spec.rb
Labels: needs review
