Repository opf/openproject, pull requests merged in 2024-07, with the labels that each got.

#15962 Set hosts config when present in config
  config/constants/settings/definition.rb
  config/environments/production.rb
  lib/tasks/packager.rake
Labels: DO NOT MERGE

#15948 Document how to render validation errors inside a dialog with a form
  lookbook/docs/patterns/05-dialogs.md.erb
Labels: needs review

#15991 LDAP group sync: Prevent creating empty keys in the user_data hash
  modules/ldap_groups/app/services/ldap_groups/synchronize_groups_service.rb
Labels: bugfix

#15964 [#55898] Add uniqueness index to project_custom_field_project_mappings
  app/services/project_custom_field_project_mappings/bulk_create_service.rb
  app/services/project_custom_field_project_mappings/bulk_update_service.rb
  db/migrate/20240625075139_add_uniqueness_index_to_project_custom_field_project_mappings.rb
  spec/services/project_custom_field_project_mappings/bulk_create_service_spec.rb
Labels: needs review

#16014 Debian 10 is EOL, remove packaging support
  .pkgr.yml
  docs/installation-and-operations/installation/packaged/README.md
  docs/installation-and-operations/operation/upgrading/README.md
  docs/installation-and-operations/system-requirements/README.md
Labels: operations, needs review

#16006 Allow values of a dynamic setting hash to be interpreted as strings
  config/constants/settings/definition.rb
  docs/installation-and-operations/configuration/environment/README.md
  spec/seeders/env_data/ldap_seeder_spec.rb
Labels: bugfix

#16016 Remove Debian 10 from preinstall script
  packaging/addons/openproject-edition/bin/preinstall
Labels: operations, needs review

#16013 Add an option to unselect projects via the global project selector
  app/controllers/homescreen_controller.rb
  frontend/src/app/shared/components/header-project-select/header-project-select.component.html
  frontend/src/app/shared/components/header-project-select/list/header-project-select-list.component.html
  frontend/src/app/shared/components/header-project-select/list/header-project-select-list.component.ts
  frontend/src/app/shared/components/icon/icon.module.ts
  lib/redmine/menu_manager/menu_controller.rb
  spec/features/projects/navigation_spec.rb
Labels: feature

#16027 Exclude the check for 4096 bytes
  frontend/src/app/shared/components/attachments/attachments.component.ts
Labels: bugfix, needs review

#16026 Remember back_url/origin as RelayState in saml
  app/controllers/concerns/accounts/omniauth_login.rb
  modules/auth_saml/lib/open_project/auth_saml/engine.rb
  modules/auth_saml/spec/requests/saml_provider_callback_spec.rb
Labels: bugfix, needs review

#16031 fix(Admin Menu Item): Use absolute path to mitigate routing exception red herring
  modules/webhooks/lib/open_project/webhooks/engine.rb
Labels: bugfix, needs review

#16030 [#55903] Add hint about case sensitivity to GitLab docs https://comm…
  docs/system-admin-guide/integrations/gitlab-integration/README.md
Labels: documentation

#16035 Bump primer_view_components to 0.36.0 and octicons to 19.15.0
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: maintenance

#15922 [Op#54117] Refactor storage view components to use the more declaritive `OpTurbo::{ComponentStream,Streamable}` helpers
  modules/storages/app/components/storages/admin/access_management_component.html.erb
  modules/storages/app/components/storages/admin/access_management_component.rb
  modules/storages/app/components/storages/admin/automatically_managed_project_folders_info_component.html.erb
  modules/storages/app/components/storages/admin/automatically_managed_project_folders_info_component.rb
  modules/storages/app/components/storages/admin/forms/access_management_form_component.html.erb
  modules/storages/app/components/storages/admin/forms/access_management_form_component.rb
  modules/storages/app/components/storages/admin/forms/automatically_managed_project_folders_form_component.html.erb
  modules/storages/app/components/storages/admin/forms/automatically_managed_project_folders_form_component.rb
  modules/storages/app/components/storages/admin/forms/general_info_form_component.html.erb
  modules/storages/app/components/storages/admin/forms/general_info_form_component.rb
  modules/storages/app/components/storages/admin/forms/oauth_client_form_component.html.erb
  modules/storages/app/components/storages/admin/forms/oauth_client_form_component.rb
  modules/storages/app/components/storages/admin/forms/redirect_uri_form_component.html.erb
  modules/storages/app/components/storages/admin/forms/redirect_uri_form_component.rb
  modules/storages/app/components/storages/admin/general_info_component.html.erb
  modules/storages/app/components/storages/admin/general_info_component.rb
  modules/storages/app/components/storages/admin/oauth_application_info_component.html.erb
  modules/storages/app/components/storages/admin/oauth_application_info_component.rb
  modules/storages/app/components/storages/admin/oauth_application_info_copy_component.html.erb
  modules/storages/app/components/storages/admin/oauth_application_info_copy_component.rb
  modules/storages/app/components/storages/admin/oauth_client_info_component.html.erb
  modules/storages/app/components/storages/admin/oauth_client_info_component.rb
  modules/storages/app/components/storages/admin/redirect_uri_component.html.erb
  modules/storages/app/components/storages/admin/redirect_uri_component.rb
  modules/storages/app/components/storages/admin/storage_view_component.html.erb
  modules/storages/app/controllers/storages/admin/access_management_controller.rb
  modules/storages/app/controllers/storages/admin/automatically_managed_project_folders_controller.rb
  modules/storages/app/controllers/storages/admin/oauth_clients_controller.rb
  modules/storages/app/controllers/storages/admin/storages_controller.rb
  modules/storages/app/views/storages/admin/access_management/create.turbo_stream.erb
  modules/storages/app/views/storages/admin/access_management/edit.turbo_stream.erb
  modules/storages/app/views/storages/admin/access_management/update.turbo_stream.erb
  modules/storages/app/views/storages/admin/automatically_managed_project_folders/create.turbo_stream.erb
  modules/storages/app/views/storages/admin/automatically_managed_project_folders/edit.html.erb
  modules/storages/app/views/storages/admin/automatically_managed_project_folders/edit.turbo_stream.erb
  modules/storages/app/views/storages/admin/oauth_clients/create.turbo_stream.erb
  modules/storages/app/views/storages/admin/oauth_clients/new.turbo_stream.erb
  modules/storages/app/views/storages/admin/oauth_clients/show_redirect_uri.html.erb
  modules/storages/app/views/storages/admin/oauth_clients/update.turbo_stream.erb
  modules/storages/app/views/storages/admin/storages/create.turbo_stream.erb
  modules/storages/app/views/storages/admin/storages/edit_host.turbo_stream.erb
  modules/storages/app/views/storages/admin/storages/new.turbo_stream.erb
  modules/storages/app/views/storages/admin/storages/replace_oauth_application.turbo_stream.erb
  modules/storages/app/views/storages/admin/storages/show_oauth_application.turbo_stream.erb
  modules/storages/app/views/storages/admin/storages/update.turbo_stream.erb
Labels: maintenance, pullpreview

#16034 Stabilize test
  spec/support/form_fields/primerized/autocomplete_field.rb
Labels: maintenance

#16012 [55774] Preselected colors for Status and Type are hard to see in dark mode
  app/helpers/colors_helper.rb
  app/helpers/highlighting_helper.rb
  app/models/colors/hex_color.rb
  db/migrate/20240703131639_add_timestamps_to_user_preferences.rb
  frontend/src/app/features/work-packages/components/wp-buttons/wp-status-button/wp-status-button.component.sass
  frontend/src/app/features/work-packages/components/wp-fast-table/builders/highlighting/highlighting.functions.ts
  frontend/src/global_styles/content/work_packages/timelines/elements/_bar.sass
  spec/models/user_preference_spec.rb
Labels: bugfix, styling, needs review

#16042 [#56141] 14.3 Documentation: Replace old icons with Octicons in the m…
  docs/system-admin-guide/openproject_system_administration_start_page.png
  docs/user-guide/home/README.md
  docs/user-guide/home/global-modules/README.md
  docs/user-guide/home/global-modules/open_project_user_guide_global_modules_menu.png
  docs/user-guide/home/global-modules/open_project_user_guide_global_modules_menu_grid_icon.png
  docs/user-guide/home/global-modules/openproject_global_modules_activity.png
  docs/user-guide/home/global-modules/openproject_global_modules_add_board.png
  docs/user-guide/home/global-modules/openproject_global_modules_add_calendar.png
  docs/user-guide/home/global-modules/openproject_global_modules_add_team_planner.png
  docs/user-guide/home/global-modules/openproject_global_modules_boards.png
  docs/user-guide/home/global-modules/openproject_global_modules_calendars.png
  docs/user-guide/home/global-modules/openproject_global_modules_gantt_charts.png
  docs/user-guide/home/global-modules/openproject_global_modules_meetings.png
  docs/user-guide/home/global-modules/openproject_global_modules_new_meeting.png
  docs/user-guide/home/global-modules/openproject_global_modules_news.png
  docs/user-guide/home/global-modules/openproject_global_modules_projects.png
  docs/user-guide/home/global-modules/openproject_global_modules_team_planner.png
  docs/user-guide/home/global-modules/openproject_global_modules_time_costs.png
  docs/user-guide/home/global-modules/openproject_global_modules_work_packages.png
  docs/user-guide/home/global-modules/openproject_global_modules_work_packages_full_view.png
  docs/user-guide/home/openproject_user_guide_home_page.png
  docs/user-guide/home/openproject_user_guide_home_page1.png
Labels: documentation

#16056 [56186] Fixed translation text
  config/locales/en.yml
Labels: needs review

#16055 [53587] 'Mark all as read' clears already read notifications
  frontend/src/app/features/in-app-notifications/center/state/ian-center.service.ts
Labels: bugfix, needs review

#16059 Allow users with edit permission to save the query
  app/contracts/queries/projects/project_queries/base_contract.rb
  spec/contracts/queries/projects/project_queries/shared_contract_examples.rb
Labels: bugfix, needs review

#16077 Fix flickering cleanup_inherited_roles_service_integration_spec test
  spec/services/groups/cleanup_inherited_roles_service_integration_spec.rb
Labels: flaky-spec

#16064 [55656] Remove derivedRemainingTime from form payload
  lib/api/utilities/payload_representer.rb
  lib/api/v3/work_packages/work_package_representer.rb
  spec/lib/api/v3/work_packages/work_package_payload_representer_spec.rb
Labels: bugfix, ruby, needs review

#15876 [#55423] Meeting: Saving an new agenda item does not automatically add another empty one
  modules/meeting/app/controllers/concerns/meetings/agenda_component_streams.rb
  modules/meeting/spec/features/structured_meetings/history_spec.rb
  modules/meeting/spec/features/structured_meetings/structured_meeting_crud_spec.rb
  modules/meeting/spec/support/pages/structured_meeting/show.rb
Labels: feature

#16082 deps[Op#51376]: Bump `opf/primer_view_components` to v0.36.2
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
  modules/storages/app/components/storages/admin/forms/redirect_uri_form_component.html.erb
Labels: dependencies

#16080 Fix flaky feature tests involving timeline
  spec/support/pages/work_packages/work_packages_timeline.rb
  spec/support/shared/cuprite_helpers.rb
Labels: needs review, flaky-spec

#16036 Switch empty state when public flag is toggled
  app/components/shares/modal_body_component.rb
  app/components/shares/modal_upsale_component.rb
  app/components/shares/project_queries/empty_state_component.rb
  app/controllers/projects/queries_controller.rb
  app/controllers/shares_controller.rb
  app/models/sharing_strategies/base_strategy.rb
  frontend/src/app/features/work-packages/components/wp-share-modal/wp-share.modal.html
  spec/controllers/projects/queries_controller_spec.rb
Labels: needs review

#16045 [#56012] all Viepoints are saved to the last BCF
  docker/dev/backend/Dockerfile
  docker/dev/backend/scripts/setup-bim
  frontend/src/app/features/bim/bcf/bcf-wp-attribute-group/bcf-new-wp-attribute-group.component.ts
  frontend/src/app/features/bim/bcf/helper/viewpoints.service.ts
Labels: bugfix, pullpreview

#16061 [#56012] all Viepoints are saved to the last BCF
  docker/dev/backend/Dockerfile
  docker/dev/backend/scripts/setup-bim
  frontend/src/app/features/bim/bcf/bcf-wp-attribute-group/bcf-new-wp-attribute-group.component.ts
  frontend/src/app/features/bim/bcf/helper/viewpoints.service.ts
  modules/bim/app/services/bim/ifc_models/update_service.rb
Labels: pullpreview

#16091 [55075] Update homescreen teaser block of versionn 14.3
  config/locales/js-en.yml
  frontend/src/app/features/homescreen/blocks/new-features.component.ts
  frontend/src/assets/images/14_2_features.png
  frontend/src/assets/images/14_3_features.png
Labels: feature, needs review

#16043 [#56164] 14.3 Documentation: Allow admins to choose between display i…
  docs/system-admin-guide/calendars-and-dates/README.md
  docs/system-admin-guide/calendars-and-dates/admin-working-days-hours.png
  docs/user-guide/time-and-costs/progress-tracking/README.md
Labels: documentation

#16062 Set raise_on_open_redirects = true
  app/controllers/concerns/auth_source_sso.rb
  app/controllers/help_controller.rb
  app/controllers/oauth_clients_controller.rb
  config/initializers/health_checks.rb
  config/initializers/new_framework_defaults_7_0.rb
  lib_static/plugins/verification/init.rb
  modules/storages/app/controllers/storages/admin/project_storages_controller.rb
  spec/fixtures/ee_tokens/v2_1_user_localhost_3000.token
  spec/fixtures/ee_tokens/v2_1_user_test_host.token
  spec/requests/admin/token_domain_spec.rb
Labels: security

#16098 Move user profile page to SidePanel component
  Gemfile
  Gemfile.lock
  app/components/users/profile/attributes_component.html.erb
  app/components/users/profile/groups_component.html.erb
  app/components/users/profile/projects_component.html.erb
  app/components/users/profile/side_panel_component.html.erb
  app/components/users/profile/side_panel_component.rb
  app/components/users/profile_component.html.erb
  frontend/package-lock.json
  frontend/package.json
Labels: needs review

#16102 Basic documentation on Layout + SidePanel
  lookbook/docs/patterns/01-layout.md.erb
  lookbook/previews/patterns/layout_preview.rb
  lookbook/previews/patterns/layout_preview/default.html.erb
Labels: documentation

#15981 [#55950] updated documentation for storage health checks
  docs/system-admin-guide/files/external-file-storages/README.md
  docs/system-admin-guide/files/external-file-storages/file-storage-troubleshooting/openproject_file_storages_health_message.png
  docs/system-admin-guide/files/external-file-storages/health-status/README.md
  docs/system-admin-guide/files/external-file-storages/health-status/openproject_file_storages_health_message.png
  docs/system-admin-guide/files/external-file-storages/health-status/openproject_file_storages_recheck_connection.png
  docs/system-admin-guide/integrations/one-drive/README.md
  docs/system-admin-guide/users-permissions/roles-permissions/README.md
  docs/system-admin-guide/users-permissions/roles-permissions/openproject_user_guide_file_storages_permissions.png
  docs/user-guide/projects/project-settings/files/README.md
Labels: documentation

#16111 Bump primer view components to 0.37.1
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: maintenance

#16065 [#56251] Fix share modal mobile styling and layouting bugs
  app/components/shares/project_queries/public_flag_component.html.erb
  app/components/shares/project_queries/public_flag_component.rb
  frontend/src/global_styles/content/_autocomplete.sass
Labels: bugfix

#16097 [#56165] 14.3 Documentation: Unselect projects from the project selector and searchbar in context menu
  docs/getting-started/projects/README.md
  docs/getting-started/projects/create-a-new-project-landing-page.png
  docs/getting-started/projects/create-project-header.png
  docs/getting-started/projects/filter_project_header_menu.png
  docs/getting-started/projects/name-your-project.png
  docs/getting-started/projects/openproject-landing-page.png
  docs/getting-started/projects/project_hierarchy-8178054.png
  docs/getting-started/projects/view_all_projects.png
  docs/user-guide/agile-boards/README.md
  docs/user-guide/agile-boards/choose-board-type.png
  docs/user-guide/agile-boards/create-a-new-board-in-the-boards-module.png
  docs/user-guide/agile-boards/openproject_userguide_boards_overview.png
  docs/user-guide/gantt-chart/README.md
  docs/user-guide/gantt-chart/openproject-user-guide-gantt-charts-export.png
  docs/user-guide/gantt-chart/openproject-user-guide-gantt-charts-views.png
  docs/user-guide/gantt-chart/openproject-user-guide-select-gantt-charts-global.png
  docs/user-guide/gantt-chart/openproject-user-guide-select-gantt-charts.png
  docs/user-guide/home/global-modules/README.md
  docs/user-guide/home/global-modules/openproject_global_modules_unselect_project.png
Labels: documentation

#16054 [56059] Can't change default work package lists columns
  app/helpers/work_packages_helper.rb
Labels: bugfix

#16123 Show attribute help text for date correctly
  frontend/src/app/features/work-packages/components/wp-form-group/wp-attribute-group.component.ts
  frontend/src/app/features/work-packages/components/wp-form-group/wp-attribute-group.template.html
  frontend/src/app/features/work-packages/components/wp-single-view/wp-single-view.component.ts
Labels: bugfix, needs review

#16131 [56436] Static queries are not highlighted in side menu
  app/menus/submenu.rb
Labels: bugfix, needs review

#16124 Also check for existence of a filter with status_id
  frontend/src/app/features/boards/board/board-partitioned-page/board-list-container.component.ts
Labels: bugfix, needs review

#16140 Merge release/14.3 into dev
  app/menus/projects/menu.rb
  config/locales/en.yml
  spec/menus/projects/menu_spec.rb
Labels: create-merge-release-into-dev-pr

#16129 Allow placeholder users in assignee or group filter
  app/models/queries/work_packages/filter/assignee_or_group_filter.rb
  spec/models/queries/work_packages/filter/assignee_or_group_filter_spec.rb
Labels: bugfix

#16137 Upgrade ruby to 3.3.4
  .github/workflows/danger.yml
  .ruby-version
  Gemfile.lock
  docker/dev/backend/Dockerfile
  docker/prod/Dockerfile
  docs/development/development-environment-osx/README.md
  docs/development/development-environment-ubuntu/README.md
  docs/installation-and-operations/installation/manual/README.md
Labels: needs review

#16136 Allow specifiying a name for date picker names
  lib/tabular_form_builder.rb
  spec/lib/custom_field_form_builder_spec.rb
  spec/lib/tabular_form_builder_spec.rb
Labels: bugfix

#16058 [50109] Breadcrumb and menu structure is inconsistent for user administration
  app/controllers/admin/settings/users_settings_controller.rb
  app/controllers/admin/settings_controller.rb
  app/controllers/groups_controller.rb
  app/controllers/placeholder_users_controller.rb
  app/controllers/roles_controller.rb
  app/controllers/users_controller.rb
  app/helpers/tabs_helper.rb
  app/helpers/users_helper.rb
  app/views/admin/settings/show_plugin.html.erb
  app/views/admin/settings/users_settings/show.html.erb
  app/views/common/_tabs.html.erb
  app/views/groups/edit.html.erb
  app/views/groups/index.html.erb
  app/views/groups/new.html.erb
  app/views/groups/show.html.erb
  app/views/placeholder_users/_toolbar.html.erb
  app/views/placeholder_users/edit.html.erb
  app/views/placeholder_users/index.html.erb
  app/views/placeholder_users/new.html.erb
  app/views/placeholder_users/show.html.erb
  app/views/roles/edit.html.erb
  app/views/roles/index.html.erb
  app/views/roles/new.html.erb
  app/views/roles/report.html.erb
  app/views/users/_notifications.html.erb
  app/views/users/_reminders.html.erb
  app/views/users/_toolbar.html.erb
  app/views/users/edit.html.erb
  app/views/users/index.html.erb
  app/views/users/new.html.erb
  app/views/users/show.html.erb
  frontend/src/app/features/user-preferences/notifications-settings/page/notifications-settings-page.component.html
  frontend/src/app/features/user-preferences/notifications-settings/page/notifications-settings-page.component.ts
  frontend/src/app/features/user-preferences/reminder-settings/page/reminder-settings-page.component.html
  frontend/src/app/features/user-preferences/reminder-settings/page/reminder-settings-page.component.ts
  modules/avatars/app/controllers/avatars/avatar_controller.rb
  modules/avatars/app/views/avatars/users/_avatar_tab.html.erb
  modules/avatars/app/views/settings/_openproject_avatars.html.erb
  modules/costs/app/controllers/cost_types_controller.rb
  modules/costs/app/views/cost_types/edit.html.erb
  modules/costs/app/views/cost_types/index.html.erb
  modules/costs/app/views/settings/_costs.html.erb
  modules/costs/app/views/users/_rates.html.erb
  spec/features/groups/group_show_spec.rb
  spec/features/placeholder_users/delete_spec.rb
  spec/features/roles/create_spec.rb
  spec/features/users/edit_users_spec.rb
  spec/helpers/tabs_helper_spec.rb
  spec/support/pages/admin/individual_principals/edit.rb
  spec/support/pages/admin/users/edit.rb
  spec/support/pages/groups.rb
Labels: bugfix, maintenance, pullpreview

#16150 Rename `my private lists` -> `my lists`
  app/menus/projects/menu.rb
  config/locales/en.yml
Labels: needs review

#16053 Release Notes 14.3
  docs/release-notes/14-3-0/README.md
  docs/release-notes/14-3-0/openproject-14-3-favorite-project-lists-highlighted.png
  docs/release-notes/14-3-0/openproject-14-3-gantt-chart-pdf-export.png
  docs/release-notes/14-3-0/openproject-14-3-profile-page-primer-highlighted.png
  docs/release-notes/14-3-0/openproject-14-3-progress-reporting-hours-only.png
  docs/release-notes/14-3-0/openproject-14-3-share-project-list-highlighted.png
  docs/release-notes/14-3-0/openproject-14-3-storages-connection-validation-highlighted.png
  docs/release-notes/14-3-0/openproject-14-3-submenu-search-bar.png
  docs/release-notes/14-3-0/openproject-14-3-unselect-projects-highlighted.png
Labels: documentation

#16135 Update Authentication FAQs documentation
  docs/system-admin-guide/authentication/authentication-faq/README.md
Labels: documentation

#16157 fix docs typos
  docs/user-guide/agile-boards/README.md
Labels: documentation

#16158 Do not perform select validation when changing name
  app/contracts/queries/projects/project_queries/base_contract.rb
Labels: bugfix, needs review

#16156 updated link
  docs/release-notes/14-3-0/README.md
Labels: documentation

#16160 Documentation/fixes
  docs/development/development-environment-docker/README.md
  docs/release-notes/14-1-0/README.md
  docs/release-notes/14-2-0/README.md
  docs/release-notes/14-3-0/README.md
  docs/user-guide/gantt-chart/README.md
  script/docs/check_links
Labels: documentation

#16166 Documentation: fixes release notes
  docs/release-notes/14-3-0/README.md
Labels: documentation

#16169 documenation: spell check fixes
  docs/release-notes/14-3-0/README.md
  docs/user-guide/projects/project-lists/README.md
Labels: documentation

#16172 change links to relative links
  docs/release-notes/14-3-0/README.md
Labels: documentation

#16171 [56507] Transform modules menu in top menu into a Primer menu
  frontend/src/global_styles/common/header/app-menu.sass
  frontend/src/global_styles/primer/_overrides.sass
  lib/redmine/menu_manager/top_menu_helper.rb
  modules/boards/spec/features/menu_items/top_menu_item_spec.rb
  modules/calendar/spec/features/calendars_index_spec.rb
  modules/reporting/spec/features/top_menu_item_spec.rb
  spec/features/menu_items/top_menu_item_spec.rb
  spec/support/pages/page.rb
Labels: feature

#16122 Document submenu pattern in the lookbook
  lookbook/docs/patterns/07-menu-and-navigation.md.erb
  lookbook/previews/open_project/common/submenu_component_preview.rb
  lookbook/previews/open_project/common/submenu_preview/default.html.erb
  lookbook/previews/open_project/common/submenu_preview/playground.html.erb
Labels: documentation

#16168 [56463] Colour of text and icons of primary buttons shall adapt when colour is light
  app/models/colors/hex_color.rb
  app/views/custom_styles/_inline_css.erb
Labels: feature, styling, needs review

#16174 [#38951] List companies / contact persons for custom development on w…
  docs/faq/README.md
Labels: documentation

#16182 [56463] Apply calcualted font color of primary buttons also on the primer buttons
  app/views/custom_styles/_primer_color_mapping.erb
  frontend/src/global_styles/content/_types_form_configuration.sass
  frontend/src/global_styles/openproject/_variable_defaults.scss
Labels: bugfix, styling, needs review

#16183 [56337] Small Octicon changes required
  Gemfile
  Gemfile.lock
  config/initializers/menus.rb
  frontend/package-lock.json
  frontend/package.json
Labels: bugfix, maintenance

#16185 Await an idle network when possible while applying filters
  spec/support/pages/projects/index.rb
Labels: flaky-spec

#16151 Extract PageHeader code into separate components
  app/components/groups/edit_page_header_component.html.erb
  app/components/groups/edit_page_header_component.rb
  app/components/groups/show_page_header_component.html.erb
  app/components/groups/show_page_header_component.rb
  app/components/placeholder_users/edit_page_header_component.html.erb
  app/components/placeholder_users/edit_page_header_component.rb
  app/components/placeholder_users/show_page_header_component.html.erb
  app/components/placeholder_users/show_page_header_component.rb
  app/components/users/edit_page_header_component.html.erb
  app/components/users/edit_page_header_component.rb
  app/components/users/index_page_header_component.html.erb
  app/components/users/index_page_header_component.rb
  app/components/users/index_sub_header_component.html.erb
  app/components/users/index_sub_header_component.rb
  app/components/users/show_page_header_component.html.erb
  app/components/users/show_page_header_component.rb
  app/helpers/users_helper.rb
  app/views/groups/edit.html.erb
  app/views/groups/show.html.erb
  app/views/placeholder_users/_toolbar_delete.html.erb
  app/views/placeholder_users/edit.html.erb
  app/views/placeholder_users/new.html.erb
  app/views/placeholder_users/show.html.erb
  app/views/users/edit.html.erb
  app/views/users/index.html.erb
  app/views/users/show.html.erb
  lookbook/docs/patterns/10-page-header.md.erb
Labels: maintenance

#16191 [56590] Colors of types in WP create button are gone
  app/helpers/colors_helper.rb
Labels: bugfix, styling

#16186 Merge release/14.3 into dev
  app/menus/submenu.rb
  docs/faq/README.md
  modules/boards/app/menus/boards/menu.rb
  modules/reporting/app/menus/cost_reports/menu.rb
Labels: create-merge-release-into-dev-pr

#16126 Hide archived subprojects in filter
  app/models/queries/work_packages/filter/subproject_filter.rb
  frontend/src/app/features/work-packages/components/filters/filter-project/filter-project.component.ts
  lib/api/v3/queries/schemas/subproject_filter_dependency_representer.rb
  spec/features/work_packages/table/subproject_filters_spec.rb
  spec/lib/api/v3/queries/schemas/subproject_filter_dependency_representer_spec.rb
  spec/models/queries/work_packages/filter/subproject_filter_spec.rb
Labels: bugfix, needs review

#16208 [56602] Community edition demo videos do not render
  config/initializers/secure_headers.rb
Labels: bugfix, needs review

#16206 [56461] Meeting date picker calendar displays double arrow
  frontend/src/global_styles/content/_datepicker.sass
Labels: bugfix, styling

#16207 Avoid StateService.go on every type switch
  frontend/src/app/shared/components/fields/edit/field-types/select-edit-field/select-edit-field.component.ts
Labels: bugfix, needs review

#16213 [56398] Searching for text in work packages is not intuitive
  app/components/open_project/common/submenu_component.html.erb
  config/locales/en.yml
Labels: bugfix

#16210 [50607] "Time 1" label in Email reminders truncated when language=FR
  frontend/src/app/features/user-preferences/reminder-settings/reminder-time/reminder-settings-daily-time.component.sass
Labels: bugfix, styling

#16215 [56445] Buttons in Attribute help text modal are too close
  frontend/src/app/spot/styles/sass/components/action-bar.sass
Labels: bugfix, styling, needs review

#16217 Fix splitting of name when not providing space
  app/seeders/admin_user_seeder.rb
  spec/seeders/admin_user_seeder_spec.rb
Labels: bugfix

#16223 [#56292] Fix share drop down being cut off on small modal heights
  frontend/src/app/features/work-packages/components/wp-share-modal/wp-share.modal.sass
Labels: bugfix, needs review

#16228 Bump Ociticons to 19.17.0
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: bugfix, maintenance

#16143 [#34363] Project custom field set to searchable is not searchable
  db/migrate/20240715183144_add_indexes_to_custom_options.rb
  lib_static/plugins/acts_as_searchable/lib/acts_as_searchable.rb
  spec/features/search/search_spec.rb
  spec/models/work_packages/search_spec.rb
Labels: needs review

#16229 update dynamic meetings docs
  docs/user-guide/meetings/dynamic-meetings/README.md
  docs/user-guide/meetings/dynamic-meetings/openproject_dynamic_meetings_untitled_section.png
Labels: documentation

#16233 Commit synced Gemfile.lock
  Gemfile.lock
Labels: dependencies

#16237 Bump primer to 0.39.0
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: maintenance

#16234 [#56331] Require explicit type selection on project change
  app/services/work_packages/set_attributes_service.rb
  config/locales/en.yml
  spec/features/work_packages/bulk/move_work_package_spec.rb
  spec/services/work_packages/set_attributes_service_spec.rb
  spec/services/work_packages/update_service_integration_spec.rb
Labels: feature

#16256 Bump primer to 0.39.1
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
  lookbook/docs/patterns/10-page-header.md.erb
Labels: maintenance

#16260 [#56651] Display related meetings chronologically
  modules/meeting/app/controllers/work_package_meetings_tab_controller.rb
  modules/meeting/spec/features/structured_meetings/work_package_meetings_tab_spec.rb
Labels: feature

#16238 [#55969] redirect to the edit storage page after creating a storage
  modules/storages/app/controllers/storages/admin/automatically_managed_project_folders_controller.rb
  modules/storages/app/controllers/storages/admin/oauth_clients_controller.rb
  modules/storages/spec/features/storages/admin/create_storage_spec.rb
Labels: needs review

#16247 [#56639] 14.4 Documentation: Transform modules menu in top menu into …
  docs/user-guide/home/global-modules/open_project_user_guide_global_modules_menu.png
  docs/user-guide/home/global-modules/open_project_user_guide_global_modules_menu_grid_icon.png
  docs/user-guide/home/global-modules/openproject_global_modules_activity.png
  docs/user-guide/home/global-modules/openproject_global_modules_add_board.png
  docs/user-guide/home/global-modules/openproject_global_modules_add_calendar.png
  docs/user-guide/home/global-modules/openproject_global_modules_add_team_planner.png
  docs/user-guide/home/global-modules/openproject_global_modules_boards.png
  docs/user-guide/home/global-modules/openproject_global_modules_calendars.png
  docs/user-guide/home/global-modules/openproject_global_modules_gantt_charts.png
  docs/user-guide/home/global-modules/openproject_global_modules_meetings.png
  docs/user-guide/home/global-modules/openproject_global_modules_new_meeting.png
  docs/user-guide/home/global-modules/openproject_global_modules_news.png
  docs/user-guide/home/global-modules/openproject_global_modules_projects.png
  docs/user-guide/home/global-modules/openproject_global_modules_team_planner.png
  docs/user-guide/home/global-modules/openproject_global_modules_time_costs.png
  docs/user-guide/home/global-modules/openproject_global_modules_work_packages.png
  docs/user-guide/home/global-modules/openproject_global_modules_work_packages_full_view.png
Labels: documentation

#16265 When participants are empty, fall back to copy author
  modules/meeting/app/services/meetings/copy_service.rb
  modules/meeting/spec/services/meetings/copy_service_integration_spec.rb
Labels: bugfix

#16264 [56786] Empty white space below meeting agenda item
  modules/meeting/app/components/meeting_agenda_items/form_component.sass
Labels: bugfix, styling, needs review

#16272 Bump primer view_components to 0.40.0
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: maintenance

#16227 Toggle public changes empty state
  app/components/shares/project_queries/public_flag_component.html.erb
Labels: needs review

#16267 Fix generic drag & drop controller
  frontend/src/app/features/admin/types/type-form-configuration.component.ts
  frontend/src/app/shared/components/autocompleter/draggable-autocomplete/draggable-autocomplete.component.ts
  frontend/src/stimulus/controllers/dynamic/admin/custom-fields.controller.ts
  frontend/src/stimulus/controllers/dynamic/generic-drag-and-drop.controller.ts
  frontend/src/stimulus/controllers/dynamic/meeting-agenda-item-drag-and-drop.controller.ts
Labels: bugfix, needs review

#16273 [56461] Datepicker dialog arrow has wrong color
  frontend/src/global_styles/content/_datepicker.sass
Labels: bugfix, styling, needs review

#16266 Fix position by using border box with position:relative
  modules/meeting/app/components/meeting_sections/show_component.html.erb
Labels: bugfix, needs review

#16268 [56655] Onboarding tour buttons are hard to see with a bright primary color
  app/views/custom_styles/_inline_css.erb
  frontend/src/global_styles/content/_buttons.sass
  frontend/src/global_styles/openproject/_variable_defaults.scss
  frontend/src/global_styles/vendor/_enjoyhint.sass
Labels: bugfix, styling, needs review

#16250 [#56640] 14.4 Documentation: Move "Copy link to clipboard" https://c…
  docs/user-guide/gantt-chart/README.md
  docs/user-guide/gantt-chart/gantt-context-menu.png
  docs/user-guide/work-packages/copy-move-delete/README.md
  docs/user-guide/work-packages/copy-move-delete/change-project-of-work-package.png
  docs/user-guide/work-packages/copy-move-delete/openproject_user_guide_copy_move_delete_detailed_view.png
  docs/user-guide/work-packages/copy-move-delete/openproject_user_guide_copy_move_delete_threedotsmenu.png
  docs/user-guide/work-packages/copy-move-delete/openproject_user_guide_copy_move_delete_wptableview.png
  docs/user-guide/work-packages/edit-work-package/1566375642243.png
  docs/user-guide/work-packages/edit-work-package/1566546959027.png
  docs/user-guide/work-packages/edit-work-package/Assignee_accountable-3987223.png
  docs/user-guide/work-packages/edit-work-package/README.md
  docs/user-guide/work-packages/edit-work-package/comment-work-packages.png
  docs/user-guide/work-packages/edit-work-package/comment-work-packages1.png
  docs/user-guide/work-packages/edit-work-package/edit-work-package.png
  docs/user-guide/work-packages/edit-work-package/image-20200331133245192.png
  docs/user-guide/work-packages/edit-work-package/image-20201119163714831.png
  docs/user-guide/work-packages/edit-work-package/openproject_user_guide_wp_activity_tab_comment.png
  docs/user-guide/work-packages/edit-work-package/openproject_user_guide_wp_activity_tab_comment_update.png
  docs/user-guide/work-packages/edit-work-package/openproject_user_guide_wp_assignee_responsible.png
  docs/user-guide/work-packages/edit-work-package/openproject_user_guide_wp_bulk_edit.png
  docs/user-guide/work-packages/edit-work-package/openproject_user_guide_wp_bulk_edit_notification.png
  docs/user-guide/work-packages/edit-work-package/openproject_user_guide_wp_change_status.png
  docs/user-guide/work-packages/edit-work-package/openproject_user_guide_wp_comment_emojis.png
  docs/user-guide/work-packages/edit-work-package/openproject_user_guide_wp_file_delete.png
  docs/user-guide/work-packages/edit-work-package/openproject_user_guide_wp_file_upload.png
  docs/user-guide/work-packages/edit-work-package/openproject_user_guide_wp_quick_context_menu.png
  docs/user-guide/work-packages/edit-work-package/openproject_user_guide_wp_update_message.png
  docs/user-guide/work-packages/edit-work-package/openproject_user_guide_wp_watchers_remove.png
  docs/user-guide/work-packages/edit-work-package/openproject_user_guide_wp_watchers_tab.png
  docs/user-guide/work-packages/edit-work-package/quick-context-menu.png
  docs/user-guide/work-packages/edit-work-package/remove-watchers.png
  docs/user-guide/work-packages/edit-work-package/watchers.png
Labels: documentation

#16276 Use UpdateService to make use of send_notifcations
  modules/meeting/app/controllers/meetings_controller.rb
  modules/meeting/app/models/meeting.rb
  modules/meeting/app/services/meetings/set_attributes_service.rb
  modules/meeting/app/views/meetings/_form.html.erb
  modules/meeting/config/locales/en.yml
  modules/meeting/spec/requests/meetings_spec.rb
Labels: bugfix

#16248 Add very basic BorderBoxTable and Row components
  app/components/_index.sass
  app/components/op_primer/border_box_row_component.html.erb
  app/components/op_primer/border_box_row_component.rb
  app/components/op_primer/border_box_table_component.html.erb
  app/components/op_primer/border_box_table_component.rb
  app/components/op_primer/border_box_table_component.sass
  app/components/table_component.rb
  lookbook/docs/patterns/12-tables.md.erb
  lookbook/previews/op_primer/border_box_table_component_preview.rb
  lookbook/previews/op_primer/border_box_table_component_preview/custom_column_widths.html.erb
  lookbook/previews/op_primer/border_box_table_component_preview/default.html.erb
  lookbook/previews/op_primer/border_box_table_component_preview/with_action_menu.html.erb
Labels: needs review

#16279 [56704]Search bar stays open when redirecting to search results page
  frontend/src/app/core/global_search/input/global-search-input.component.ts
Labels: bugfix
