Repository opf/openproject, pull requests merged in 2024-05, with the labels that each got.

#15444 fix incorrect bracketing
  docs/user-guide/time-and-costs/time-and-costs-faq/README.md
Labels: documentation

#15446 Update git lab integration documentation
  docs/system-admin-guide/integrations/gitlab-integration/README.md
Labels: documentation

#15448 Set state = open when copying meetings
  modules/meeting/app/services/meetings/copy_service.rb
  modules/meeting/spec/services/meetings/copy_service_integration_spec.rb
Labels: feature

#15472 Merge release/14.0 into dev
  docs/user-guide/time-and-costs/progress-tracking/README.md
Labels: create-merge-release-into-dev-pr

#15483 [#46116] Pages have unnecessary "..." collapsing between 1st and 2nd page
  frontend/src/app/shared/components/table-pagination/table-pagination.component.ts
Labels: needs review

#15494 Bundler 2.5.9 -> 2.5.10
  Gemfile.lock
  docker/ci/Dockerfile
  docker/dev/backend/Dockerfile
  docker/prod/Dockerfile
  docs/development/development-environment-osx/README.md
  docs/development/development-environment-ubuntu/README.md
  script/github_pr_errors
Labels: needs review

#15327 [#53704] BUG Visible=false project attribute values are deleted when a non-admin user edits the attributes (2/2)
  app/models/projects/acts_as_customizable_patches.rb
  spec/models/projects/customizable_spec.rb
Labels: needs review

#15511 remove obsolete migration which breaks updating to 14.0
  db/migrate/20211105142202_queue_notification_update_mail.rb
Labels: needs review

#15431 [#53474] Having custom columns on Sharepoint blocks the copying of dr…
  docs/system-admin-guide/integrations/one-drive/README.md
  docs/user-guide/file-management/file-management-faq/README.md
Labels: documentation

#15530 [51447] Use same headings for permissions report and role forms
  app/helpers/roles_helper.rb
  app/views/roles/_permissions.html.erb
  app/views/roles/report.html.erb
  modules/storages/spec/features/storages_module_spec.rb
Labels: bugfix, ruby, needs review

#15529 [54128] Text editor is partially out of view on mobile
  frontend/src/app/spot/styles/sass/components/form-field.sass
Labels: bugfix, styling

#15425 Update Nextcloud docs screenshots after NC 2.6.2 release
  docs/system-admin-guide/integrations/nextcloud/NC_admin-defaults-user-options.png
  docs/user-guide/file-management/nextcloud-integration/NC_0_01-FileRelationSearch_new.png
  docs/user-guide/file-management/nextcloud-integration/NC_1_00-FileWPRelation.png
  docs/user-guide/file-management/nextcloud-integration/NC_1_00-FileWPRelation_new.png
  docs/user-guide/file-management/nextcloud-integration/NC_1_01-FileWPActions.png
  docs/user-guide/file-management/nextcloud-integration/README.md
Labels: documentation

#15543 Fix `bin/setup_dev` script
  frontend/package-lock.json
Labels: bugfix, maintenance, needs review

#15551 [54128] Hide overflowing textareas but not select fields
  frontend/src/app/shared/components/dynamic-forms/components/dynamic-inputs/formattable-textarea-input/formattable-textarea-input.component.scss
  frontend/src/app/spot/styles/sass/components/form-field.sass
Labels: bugfix, needs review

#15555 Lookbook is missing Primer styles
  app/views/layouts/component_preview.html.erb
Labels: maintenance, needs review

#15531 [54746] Typeahead options overlying typed in field in column selection
  app/components/projects/configure_view_modal_component.html.erb
Labels: bugfix

#15553 Bump to primer_view_components 0.30.1 and octicons 19.12.0
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: maintenance

#15560 Fix eslint complaint about 'eqeqeq' rule
  frontend/src/app/features/boards/board/add-list-modal/add-list-modal.html
  frontend/src/app/features/work-packages/components/filters/query-filter/query-filter.component.html
  frontend/src/app/features/work-packages/components/filters/query-filters/query-filters.component.html
  frontend/src/app/shared/components/table-pagination/table-pagination.component.html
Labels: maintenance, needs review

#15400 [#54459] Add `AvailableProjectAttributesFilter` to project queries to display the mapped projects list in projects attribute settings view
  app/models/project.rb
  app/models/projects/scopes/available_custom_fields.rb
  app/models/queries/projects.rb
  app/models/queries/projects/filters/available_project_attributes_filter.rb
  config/locales/en.yml
  docs/api/apiv3/paths/projects.yml
  spec/models/projects/scopes/available_custom_fields_spec.rb
  spec/models/queries/projects/filters/available_project_attributes_filter_spec.rb
  spec/requests/api/v3/projects/index_resource_spec.rb
Labels: needs review

#15588 [#51745] Remove unused translation string
  config/locales/en.yml
Labels: needs review

#15587 Remove agenda items when deleting section
  modules/meeting/app/components/meeting_sections/header_component.html.erb
  modules/meeting/app/components/meeting_sections/header_component.rb
  modules/meeting/app/contracts/meeting_sections/delete_contract.rb
  modules/meeting/config/locales/en.yml
  modules/meeting/spec/contracts/meeting_sections/delete_contract_spec.rb
  modules/meeting/spec/features/structured_meetings/structured_meeting_crud_spec.rb
Labels: bugfix, needs review

#15569 [#55010] 14.1 Documentation: Add "Manage project attributes" button t…
  docs/user-guide/project-overview/README.md
  docs/user-guide/project-overview/configure-view-widgets.png
  docs/user-guide/project-overview/openproject_user_guide_project_overview.png
  docs/user-guide/project-overview/openproject_user_guide_project_overview_add_widget_icon.png
  docs/user-guide/project-overview/openproject_user_guide_project_overview_archive_project.png
  docs/user-guide/project-overview/openproject_user_guide_project_overview_axis_criteria_widget.png
  docs/user-guide/project-overview/openproject_user_guide_project_overview_filter_criteria_widget.png
  docs/user-guide/project-overview/openproject_user_guide_project_overview_mark_favorite.png
  docs/user-guide/project-overview/openproject_user_guide_project_overview_project_attributes_section.png
  docs/user-guide/project-overview/openproject_user_guide_project_overview_project_attributes_section_edit_new.png
  docs/user-guide/project-overview/openproject_user_guide_project_overview_project_attributes_section_new.png
  docs/user-guide/project-overview/openproject_user_guide_project_overview_project_attributes_settings.png
  docs/user-guide/project-overview/openproject_user_guide_project_overview_project_members_widget.png
  docs/user-guide/project-overview/remove-widget.png
  docs/user-guide/projects/README.md
  docs/user-guide/projects/delete-a-project.png
  docs/user-guide/projects/image-20220728200830893.png
  docs/user-guide/projects/project-information-description-status.png
  docs/user-guide/projects/project-list-filter.png
  docs/user-guide/projects/project-settings-archive-project.png
  docs/user-guide/projects/project-settings-subproject.png
Labels: documentation

#15585 Tests for sorting config dialog
  app/components/queries/sort_by_field_component.html.erb
  spec/features/projects/persisted_lists_spec.rb
  spec/features/projects/projects_index_spec.rb
  spec/support/pages/projects/index.rb
Labels: needs review

#15591 [54354] Update seed data
  app/seeders/standard.yml
  modules/meeting/app/seeders/meetings/demo_data/meeting_agenda_items_seeder.rb
  modules/meeting/app/seeders/standard.yml
  modules/meeting/spec/seeders/demo_data/meeting_agenda_items_seeder_spec.rb
  modules/meeting/spec/seeders/demo_data/project_seeder_spec.rb
  spec/seeders/root_seeder_standard_edition_spec.rb
Labels: needs review

#14946 [53466] Check for inconsistent interpolations in all i18n files
  config/i18n-tasks-all-files.yml
  spec/i18n_spec.rb
Labels: needs review

#15589 [#55005] 14.1 Documentation: Advanced meetings features https://comm…
  docs/user-guide/meetings/dynamic-meetings/README.md
  docs/user-guide/meetings/dynamic-meetings/openproject_dynamic_meetings_add_agenda_item.png
  docs/user-guide/meetings/dynamic-meetings/openproject_dynamic_meetings_add_item_to_section.png
  docs/user-guide/meetings/dynamic-meetings/openproject_dynamic_meetings_add_section.png
  docs/user-guide/meetings/dynamic-meetings/openproject_dynamic_meetings_edit_item_in_section.png
  docs/user-guide/meetings/dynamic-meetings/openproject_dynamic_meetings_edit_section_options.png
  docs/user-guide/meetings/dynamic-meetings/openproject_dynamic_meetings_section_duration.png
  docs/user-guide/meetings/dynamic-meetings/openproject_dynamic_meetings_untitled section.png
  docs/user-guide/meetings/dynamic-meetings/openproject_userguide_add_agenda_item.png
  docs/user-guide/meetings/meetings-faq/README.md
Labels: documentation

#15575 [#55008] 14.1 Documentation: Add links to custom fields type text ht…
  docs/system-admin-guide/custom-fields/README.md
  docs/system-admin-guide/custom-fields/administration-custom-fields.png
  docs/system-admin-guide/custom-fields/image-20200122112806127.png
  docs/system-admin-guide/custom-fields/openproject_system_guide_new_custom_field_new.png
  docs/system-admin-guide/custom-fields/system-admin-add-field-to-wp-type.png
  docs/system-admin-guide/custom-fields/system-admin-allow-multi-select.png
  docs/system-admin-guide/custom-fields/system-admin-edit-delete-custom-field.png
Labels: documentation

#15601 [55132] Disabled Primer button styles not displayed correctly
  app/views/custom_styles/_inline_css.erb
  app/views/custom_styles/_primer_color_mapping.erb
  frontend/src/global_styles/openproject/_variable_defaults.scss
Labels: bugfix, styling, needs review

#15572 [#55011] 14.1 Documentation: PDF export of Gantt view (print Gantt ch…
  docs/user-guide/gantt-chart/README.md
  docs/user-guide/gantt-chart/openproject-user-guide-gantt-charts-export.png
  docs/user-guide/gantt-chart/openproject-user-guide-gantt-pdf-gantt-icon.png
  docs/user-guide/gantt-chart/openproject-user-guide-gantt-pdf-gantt-options.png
  docs/user-guide/work-packages/exporting/README.md
Labels: documentation

#15623 [#55007] 14.1 Documentation: OneDrive/SharePoint changes https://com…
  docs/user-guide/file-management/one-drive-integration/README.md
  docs/user-guide/file-management/one-drive-integration/openproject_onedrive_no_permission_to_view.png
Labels: documentation

#15624 [#55009] 14.1 Documentation: Update permissions https://community.op…
  docs/system-admin-guide/users-permissions/roles-permissions/README.md
  docs/system-admin-guide/users-permissions/roles-permissions/openproject_user_guide_file_storages_permissions.png
Labels: documentation

#15625 Fix meeting type label selection on the new meeting form.
  modules/meeting/app/views/meetings/_form.html.erb
  modules/meeting/spec/features/meetings_new_spec.rb
Labels: needs review

#15636 Documentation/fixes
  docs/release-notes/14-1-0/README.md
  docs/release-notes/README.md
  docs/system-admin-guide/files/README.md
  docs/user-guide/meetings/dynamic-meetings/README.md
Labels: documentation

#15626 chore[Op#55123]: remove redundant query build
  app/controllers/admin/settings/project_custom_fields_controller.rb
Labels: tinyfix

#15618 [#55112] Rename Storages::ManageNextcloudIntegrationJob
  lib/tasks/cron.rake
  modules/storages/app/workers/storages/manage_storage_integrations_job.rb
  modules/storages/lib/open_project/storages/engine.rb
  modules/storages/spec/workers/storages/manage_storage_integrations_job_spec.rb
  spec/controllers/roles_controller_spec.rb
  spec/lib/open_project/events_spec.rb
Labels: needs review

#15640 Make delete_permission required in the DeleteService
  app/contracts/delete_contract.rb
  app/contracts/project_custom_field_project_mappings/delete_contract.rb
Labels: maintenance

#15500 [#54469] Allow sending notifications for invited users
  modules/meeting/app/controllers/meetings_controller.rb
  modules/meeting/app/services/meetings/create_service.rb
  modules/meeting/app/views/meetings/_form.html.erb
  modules/meeting/config/locales/en.yml
  modules/meeting/spec/features/structured_meetings/structured_meeting_crud_spec.rb
Labels: feature

#15652 Bump primer_view_components to 0.31.0
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: maintenance, needs review

#15674 Use shared_let and explicitly set user for `public_query`
  spec/models/queries/projects/project_query_spec.rb
Labels: needs review

#15495 [#53669] Change default view for meetings module to upcoming invitations
  modules/meeting/app/controllers/meetings_controller.rb
  modules/meeting/app/helpers/meetings_helper.rb
  modules/meeting/spec/controllers/meetings_controller_spec.rb
  modules/meeting/spec/features/meetings_delete_spec.rb
  modules/meeting/spec/features/meetings_global_menu_item_spec.rb
  modules/meeting/spec/features/meetings_index_spec.rb
  modules/meeting/spec/features/meetings_show_spec.rb
Labels: feature, needs review

#15679 Reserve project queries identifier
  app/models/project.rb
  spec/models/project_spec.rb
Labels: needs review

#15697 Bump octicons to 19.13.0
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: maintenance

#15698 My page docs update
  docs/getting-started/my-page/Move-widget.png
  docs/getting-started/my-page/My-page-default-view.png
  docs/getting-started/my-page/README.md
  docs/getting-started/my-page/image-20200211154602328.png
  docs/getting-started/my-page/my-page-add-widget.png
  docs/getting-started/my-page/my-page-size-handle.png
  docs/getting-started/my-page/my-page-widget-list.png
  docs/getting-started/my-page/openproject-mypage-widgets.gif
  docs/user-guide/project-overview/README.md
Labels: documentation

#15696 [55230] Transform remove action from share modals to an IconButton
  app/components/work_packages/share/modal_body_component.html.erb
  app/components/work_packages/share/share_row_component.html.erb
  spec/support/components/work_packages/share_modal.rb
Labels: needs review

#15653 Implementation/55133 handle edge case if unlink fails render a primer error banner
  app/contracts/project_custom_field_project_mappings/base_contract.rb
  app/controllers/admin/settings/project_custom_fields_controller.rb
  app/helpers/flash_messages_helper.rb
  app/helpers/flash_messages_output_safety_helper.rb
  app/services/project_custom_field_project_mappings/delete_service.rb
  app/views/layouts/base.html.erb
  config/locales/en.yml
  modules/storages/app/controllers/storages/admin/storages_controller.rb
  spec/contracts/project_custom_field_project_mappings/base_contract_spec.rb
  spec/services/project_custom_field_project_mappings/delete_service_spec.rb
Labels: needs review

#15676 [#55196] Wrong menu entry when deactivating a project attribute (not "Delete")
  app/components/projects/row_component.rb
  app/components/settings/project_custom_fields/project_custom_field_mapping/row_component.rb
  app/views/admin/settings/project_custom_fields/project_mappings.html.erb
  config/locales/en.yml
  spec/features/admin/project_custom_fields/project_mappings_spec.rb
Labels: bugfix

#15701 Fix the pr errors script, show the in progress run even if there is a successful previous run
  script/github_pr_errors
Labels: needs review

#15699 Implementation/55124 retain project list hierarchy in the project attributes tab detail page
  app/components/settings/project_custom_fields/project_custom_field_mapping/table_component.rb
  app/controllers/admin/settings/project_custom_fields_controller.rb
  app/views/admin/settings/project_custom_fields/project_mappings.html.erb
Labels: needs review

#15709 Bump primer_view_components to 0.32.0
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: maintenance

#15710 [#55381] The available_projects api endpoint displays custom fields incorrectly
  lib/api/v3/projects/project_eager_loading_wrapper.rb
  spec/lib/api/v3/projects/project_eager_loading_wrapper_spec.rb
  spec/requests/api/v3/versions/available_projects_resource_spec.rb
Labels: needs review
