Repository opf/openproject, pull requests merged in 2025-07, with the labels that each got.

#19335 [65091] Change default color of sidebar in light mode
  app/components/open_project/common/main_menu_toggle_component.sass
  app/components/open_project/common/submenu_component.sass
  app/views/custom_styles/_inline_css.erb
  app/views/layouts/base.html.erb
  db/migrate/20250627121119_change_default_main_menu_color.rb
  frontend/src/app/shared/components/header-project-select/header-project-select.component.sass
  frontend/src/global_styles/common/header/app-header.sass
  frontend/src/global_styles/layout/_main_menu.sass
  frontend/src/global_styles/layout/_tree_menu.sass
  frontend/src/global_styles/openproject/_variable_defaults.scss
  lib/open_project/custom_styles/color_themes.rb
  spec/migrations/change_default_main_menu_color_spec.rb
Labels: feature

#19356 [65254] Project attributes modal has no divider
  modules/overviews/app/components/overviews/project_custom_fields/edit_dialog_component.html.erb
Labels: bugfix, styling

#19369 [65279] Menu toggler overlaps back button and breadcrumb in WP full view
  app/components/open_project/common/main_menu_toggle_component.sass
  frontend/src/app/features/work-packages/routing/wp-full-view/wp-full-view.html
  frontend/src/global_styles/layout/work_packages/_mobile.sass
  frontend/src/global_styles/openproject/_mixins.sass
Labels: bugfix, styling

#19352 Bug/65074 create a new custom field link on empty index page does not allow creating one
  app/components/settings/project_custom_field_sections/show_component.html.erb
  app/components/settings/project_custom_field_sections/show_component.rb
  app/views/custom_fields/_tab.html.erb
  spec/features/admin/custom_fields/projects/index_spec.rb
Labels: bugfix

#19354 [65071] Disabled invisible button has a background color
  frontend/package-lock.json
  frontend/package.json
Labels: bugfix, styling, needs review

#19384 [#65281] Update Gantt FAQ https://community.openproject.org/work_pac…
  docs/user-guide/gantt-chart/gantt-chart-faq/README.md
Labels: documentation

#19368 [64294] Focus is not on back arrow when navigating through main menu
  frontend/src/stimulus/controllers/dynamic/menus/main.controller.ts
  lib/redmine/menu_manager/menu_helper.rb
  spec/lib/redmine/menu_manager/menu_helper_spec.rb
Labels: bugfix, needs review

#19389 [65340] Some instances are missing a color for the sidebar border
  app/models/colors/hex_color.rb
  app/views/custom_styles/_inline_css.erb
  frontend/src/global_styles/openproject/_variable_defaults.scss
Labels: bugfix, needs review

#18152 [#62523] Work package datepicker incorrectly renders turbo frame response
  app/components/work_packages/date_picker/date_form_component.rb
  app/components/work_packages/date_picker/dialog_content_component.html.erb
  app/components/work_packages/date_picker/dialog_content_component.rb
  app/components/work_packages/date_picker/form_component.html.erb
  app/components/work_packages/date_picker/form_component.rb
  app/controllers/work_packages/date_picker_controller.rb
  app/controllers/work_packages/progress_controller.rb
  app/views/work_packages/date_picker/show.html.erb
  config/routes.rb
  frontend/src/stimulus/controllers/dynamic/work-packages/date-picker/preview.controller.ts
  frontend/src/stimulus/controllers/dynamic/work-packages/dialog/preview.controller.ts
  spec/controllers/work_packages/date_picker_controller_spec.rb
  spec/features/a11y/work_packages/datepicker_spec.rb
  spec/features/work_packages/table/scheduling/manual_scheduling_spec.rb
  spec/support/components/datepicker/work_package_datepicker.rb
Labels: needs review

#19396 [65348] Breadcrumb can overlap title
  frontend/src/app/shared/components/breadcrumbs/op-breadcrumbs.component.sass
Labels: bugfix

#19423 docs: fixed typo in project overview section
  docs/user-guide/project-overview/README.md
Labels: documentation

#19417 [65524] PageHeader has the wrong background on project overview
  frontend/src/global_styles/content/_grid.sass
Labels: bugfix, needs review

#19422 [65078] On mobile web, text blocks in widgets on the home page can be too narrow when there's an image
  frontend/src/app/features/homescreen/blocks/new-features.component.sass
Labels: bugfix

#19427 [#65394] Time tracking changes https://community.openproject.org/wor…
  docs/getting-started/my-page/README.md
  docs/release-notes/16-0-0/README.md
  docs/user-guide/README.md
  docs/user-guide/my-time-tracking/openproject-my-time-tracking-page1.gif
  docs/user-guide/my-time-tracking/openproject_user_guide_my_time_tracking_module_calendar_tab_total_sums.png
  docs/user-guide/my-time-tracking/openproject_user_guide_my_time_tracking_module_filters_explained.png
  docs/user-guide/my-time-tracking/openproject_user_guide_my_time_tracking_module_list_view_edit_icon.png
  docs/user-guide/my-time-tracking/openproject_user_guide_my_time_tracking_module_list_view_overview.png
  docs/user-guide/my-time-tracking/openproject_user_guide_my_time_tracking_module_logging_modal.png
  docs/user-guide/my-time-tracking/openproject_user_guide_my_time_tracking_module_overview.png
  docs/user-guide/time-and-costs/README.md
  docs/user-guide/time-and-costs/my-time-tracking/README.md
  docs/user-guide/time-and-costs/my-time-tracking/openproject-my-time-tracking-page.gif
  docs/user-guide/time-and-costs/my-time-tracking/openproject_user_guide_my_time_tracking_module_calendar_tab_total_sums.png
  docs/user-guide/time-and-costs/my-time-tracking/openproject_user_guide_my_time_tracking_module_filters_explained.png
  docs/user-guide/time-and-costs/my-time-tracking/openproject_user_guide_my_time_tracking_module_list_view_edit_icon.png
  docs/user-guide/time-and-costs/my-time-tracking/openproject_user_guide_my_time_tracking_module_list_view_overview.png
  docs/user-guide/time-and-costs/my-time-tracking/openproject_user_guide_my_time_tracking_module_logging_modal.png
  docs/user-guide/time-and-costs/my-time-tracking/openproject_user_guide_my_time_tracking_module_overview.png
Labels: documentation

#19436 [#65388] PDF Export https://community.openproject.org/work_packages/…
  docs/user-guide/work-packages/exporting/README.md
  docs/user-guide/work-packages/exporting/openproject-user-guide-wp-export-multilingual-symbols-example.png
Labels: documentation

#19438 [65260] 'Auto hide success message' menu item is missing caption
  app/forms/my/alerts_form.rb
  config/locales/en.yml
Labels: bugfix, needs review

#19420 Release Notes 16.2
  docs/release-notes/16-2-0/README.md
  docs/release-notes/16-2-0/openproject-16-2-create-project.png
  docs/release-notes/16-2-0/openproject-16-2-design-updates.png
  docs/release-notes/16-2-0/openproject-16-2-pdf-export.png
  docs/release-notes/16-2-0/openproject-16-2-reminder.png
  docs/release-notes/16-2-0/openproject-user-guide-account-settings-interface.png
  docs/release-notes/16-2-0/openproject-user-guide-relations-second-level-navigation.png
  docs/release-notes/16-2-0/user-guide-my-time-tracking-module-list-view.png
Labels: documentation

#19415 [65498] Mobile: double header when opening a WP from a notification
  app/components/open_project/common/main_menu_toggle_component.sass
  frontend/src/global_styles/layout/_base_mobile.sass
Labels: bugfix, needs review

#19418 [#65416] Show custom field format on #new
  app/components/settings/project_custom_fields/new_form_header_component.html.erb
  app/components/settings/project_custom_fields/new_form_header_component.rb
  app/views/admin/settings/project_custom_fields/new.html.erb
  app/views/custom_fields/new.html.erb
  spec/features/admin/custom_fields/projects/create_in_section_spec.rb
Labels: bugfix, needs review

#19432 Fix incorrectly applied Angular class decorators
  frontend/src/app/core/global_search/global-search-work-packages.component.ts
  frontend/src/app/core/global_search/tabs/global-search-tabs.component.ts
  frontend/src/app/features/bim/ifc_models/toolbar/import-export-bcf/refresh-button.component.ts
  frontend/src/app/features/boards/board/inline-add/board-inline-add-autocompleter.component.ts
  frontend/src/app/features/work-packages/components/filters/quick-filter-by-text-input/quick-filter-by-text-input.component.ts
  frontend/src/app/shared/components/copy-to-clipboard/copy-to-clipboard.service.ts
  frontend/src/app/shared/components/fields/display/field-types/excluded-icon-helper.service.ts
  frontend/src/app/shared/components/fields/display/field-types/hierarchy-query-link-helper.service.ts
  frontend/src/app/shared/components/modals/get-ical-url-modal/query-get-ical-url.modal.ts
  frontend/src/app/shared/components/no-results/no-results.component.ts
  frontend/src/app/shared/components/resizer/resizer/main-menu-resizer.component.ts
  frontend/src/app/shared/components/resizer/resizer/wp-resizer.component.ts
  frontend/src/app/shared/components/tabs/scrollable-tabs/scrollable-tabs.component.ts
  frontend/src/app/shared/components/work-package-graphs/overview/wp-overview-graph.component.ts
  frontend/src/app/shared/components/work-packages/alternative-search.service.ts
Labels: hotfix, javascript

#18882 Fix meeting time zone handling
  frontend/src/stimulus/controllers/dynamic/meetings/form.controller.ts
  frontend/src/stimulus/controllers/dynamic/recurring-meetings/form.controller.ts
  frontend/tsconfig.base.json
  modules/meeting/app/components/meetings/index/form_component.html.erb
  modules/meeting/app/controllers/recurring_meetings/schedule_controller.rb
  modules/meeting/app/forms/meeting/time_group.rb
  modules/meeting/app/models/meeting.rb
  modules/meeting/app/models/meeting/virtual_start_time.rb
  modules/meeting/app/models/recurring_meeting.rb
  modules/meeting/app/services/recurring_meetings/update_service.rb
  modules/meeting/app/workers/recurring_meetings/init_next_occurrence_job.rb
  modules/meeting/config/locales/en.yml
  modules/meeting/spec/models/meeting_spec.rb
Labels: bugfix

#19470 [65614] WP details diffs are not in colours anymore
  frontend/src/global_styles/content/_diff.sass
Labels: bugfix, needs review

#19262 Task/61285 remove event type filter compatibility alias
  app/models/activities/fetcher.rb
  spec/models/activities/fetcher_integration_spec.rb
Labels: maintenance, needs review

#19430 Use `querySelector` if we only need first `Element`
  frontend/src/app/core/current-user/current-user.module.ts
  frontend/src/app/features/work-packages/openproject-work-packages.module.ts
  frontend/src/app/shared/components/resizer/resizer/wp-resizer.component.ts
  frontend/src/app/spot/components/drop-modal/drop-modal.component.ts
Labels: maintenance, javascript, tinyfix

#19405 [65336] Missing breadcrumb in remaining pages
  app/controllers/search_controller.rb
  app/views/work_packages/bulk/edit.html.erb
  app/views/work_packages/moves/new.html.erb
  frontend/src/app/core/global_search/title/global-search-title.component.html
  frontend/src/app/core/global_search/title/global-search-title.component.ts
  frontend/src/app/features/work-packages/components/wp-copy/wp-copy-full-view.component.ts
  frontend/src/app/features/work-packages/components/wp-new/wp-create.component.ts
  frontend/src/app/features/work-packages/components/wp-new/wp-new-full-view.component.ts
  frontend/src/app/features/work-packages/components/wp-new/wp-new-full-view.html
  frontend/src/app/shared/components/breadcrumbs/op-breadcrumbs.component.ts
  modules/meeting/spec/features/meetings_search_spec.rb
  modules/team_planner/spec/support/pages/team_planner.rb
  spec/support/components/autocompleter/ng_select_autocomplete_helpers.rb
Labels: bugfix

#19488 [#65679] Work package comments fire a webhook https://community.open…
  docs/system-admin-guide/api-and-webhooks/README.md
  docs/system-admin-guide/api-and-webhooks/openproject_system_admin_guide_api.png
  docs/system-admin-guide/api-and-webhooks/openproject_system_admin_guide_api_new_webhook.png
  docs/system-admin-guide/api-and-webhooks/openproject_system_admin_guide_webhooks.png
Labels: documentation

#19411 [65414] Sidebar is too small when being re-opened
  frontend/src/app/core/main-menu/main-menu-toggle.service.ts
Labels: bugfix

#19500 [65360] Disabled project selector on project copy form is missing styling
  frontend/src/global_styles/content/_autocomplete.sass
Labels: bugfix, styling, needs review

#19483 [65313] Wrong menu item is highlighted when copying a project
  app/controllers/projects_controller.rb
Labels: bugfix

#19508 Update release notes 16.2
  docs/release-notes/16-2-0/README.md
  docs/release-notes/16-2-0/openproject-16-2-custom-field-type.png
  docs/release-notes/16-2-0/openproject-16-2-design-updates.png
  docs/release-notes/16-2-0/openproject-16-2-scim-api.png
Labels: documentation

#19464 robustness on calling account/consent outside of login process
  app/controllers/concerns/accounts/user_consent.rb
  spec/features/auth/consent_auth_stage_spec.rb
Labels: needs review

#19491 [65612] Adjust spacings in sidebar
  app/components/enterprise_edition/trial_teaser_component.rb
  app/components/open_project/common/submenu_component.sass
  frontend/src/global_styles/layout/_main_menu.sass
Labels: bugfix, styling

#19447 [65252] Links in descriptive text not distinguishable enough
  Gemfile
  Gemfile.lock
  app/components/work_packages/activities_tab/journals/revision_component.html.erb
  app/components/work_packages/date_picker/banner_component.rb
  app/components/work_packages/progress/status_based/modal_body_component.html.erb
  app/forms/projects/settings/work_packages/activities/form.rb
  app/forms/work_package_types/subject_configuration_form.rb
  config/locales/en.yml
  frontend/package-lock.json
  frontend/package.json
  lib/open_project/patches/primer_page_header_breadcrumb.rb
  lookbook/previews/op_primer/border_box_table_component_preview/default.html.erb
  lookbook/previews/op_primer/border_box_table_component_preview/with_action_menu.html.erb
  lookbook/previews/op_primer/border_box_table_component_preview/with_footer.html.erb
  modules/costs/app/components/my/time_tracking/time_entry_row.rb
  modules/job_status/app/components/job_status/dialog/body_component.html.erb
  modules/meeting/app/components/meetings/row_component.rb
  modules/storages/app/components/storages/admin/forms/general_info_form_component.rb
  modules/storages/app/components/storages/admin/forms/oauth_client_form_component.rb
  modules/storages/app/components/storages/admin/general_info_component.html.erb
  modules/storages/app/components/storages/admin/health/check_result_component.html.erb
  modules/storages/app/components/storages/open_project_storage_modal_component.rb
  modules/storages/app/forms/storages/admin/managed_project_folders/application_password_input.rb
  modules/storages/app/forms/storages/admin/provider_drive_id_input_form.rb
  modules/storages/app/forms/storages/admin/provider_tenant_id_input_form.rb
  spec/features/admin/scim_clients/create_spec.rb
  spec/features/admin/scim_clients/update_spec.rb
Labels: bugfix, Accessibility

#19424 [#65395] Work package relations menu changes https://community.openp…
  docs/user-guide/work-packages/work-package-relations-hierarchies/README.md
  docs/user-guide/work-packages/work-package-relations-hierarchies/openproject_user_guide_wp_add_child.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/openproject_user_guide_wp_add_relations_button.png
Labels: documentation

#19468 [#64235] Provide A11y labels for pagination links
  app/components/projects/table_component.html.erb
  app/helpers/application_helper.rb
  app/helpers/pagination_helper.rb
  config/locales/en.yml
  config/locales/js-en.yml
  frontend/src/app/shared/components/table-pagination/table-pagination.component.html
  frontend/src/app/shared/components/table-pagination/table-pagination.component.ts
  frontend/src/global_styles/content/_pagination.sass
  lib/open_project/link_renderer.rb
  spec/helpers/application_helper_spec.rb
  spec/helpers/pagination_helper_spec.rb
Labels: bugfix, styling, javascript, needs review, Accessibility

#19512 [65772] Empty "Other relations" entry when missing permissions
  app/components/work_package_relations_tab/index_component.html.erb
  spec/features/work_packages/details/relations/primerized_relations_spec.rb
  spec/features/work_packages/tabs/relations_children_spec.rb
  spec/support/components/work_packages/relations.rb
Labels: bugfix, needs review

#19526 [65785] Redundant scrollbar in wp side menu
  frontend/src/global_styles/layout/_main_menu.sass
Labels: bugfix, styling

#19496 [64229] Search is missing a screen reader label
  frontend/src/app/core/global_search/input/global-search-input.component.html
  frontend/src/app/core/global_search/input/global-search-input.component.sass
Labels: bugfix

#19530 [#65770] Document how to configure SCIM clients
  app/forms/scim_clients/form.rb
  app/views/admin/scim_clients/edit.html.erb
  app/views/admin/scim_clients/new.html.erb
  config/locales/en.yml
  config/static_links.yml
  docs/system-admin-guide/authentication/README.md
  docs/system-admin-guide/authentication/ldap-connections/README.md
  docs/system-admin-guide/authentication/oauth-applications/README.md
  docs/system-admin-guide/authentication/recaptcha/README.md
  docs/system-admin-guide/authentication/saml/README.md
  docs/system-admin-guide/authentication/scim/README.md
  docs/system-admin-guide/authentication/scim/add_scim_1.png
  docs/system-admin-guide/authentication/scim/add_scim_10.png
  docs/system-admin-guide/authentication/scim/add_scim_2.png
  docs/system-admin-guide/authentication/scim/add_scim_3.png
  docs/system-admin-guide/authentication/scim/add_scim_4.png
  docs/system-admin-guide/authentication/scim/add_scim_5.png
  docs/system-admin-guide/authentication/scim/add_scim_6.png
  docs/system-admin-guide/authentication/scim/add_scim_7.png
  docs/system-admin-guide/authentication/scim/add_scim_8.png
  docs/system-admin-guide/authentication/scim/add_scim_9.png
  docs/system-admin-guide/authentication/scim/openproject_system_administration_authetication_scim_index_page.png
  docs/system-admin-guide/authentication/two-factor-authentication/README.md
Labels: documentation

#19528 Update Release Notes 16.2
  docs/release-notes/16-1-0/README.md
  docs/release-notes/16-2-0/README.md
Labels: documentation

#19586 fixed typo in postgresql17 guide
  docs/installation-and-operations/misc/migration-to-postgresql17/README.md
Labels: documentation

#19629 Fix typos in docs.md
  docs/user-guide/home/global-modules/README.md
Labels: documentation

#19620 Freeze string literals in app/policies
  app/policies/base_policy.rb
  app/policies/query_policy.rb
  app/policies/redirect_policy.rb
  app/policies/scm/authorization_policy.rb
  app/policies/scm/git_authorization_policy.rb
  app/policies/scm/subversion_authorization_policy.rb
Labels: maintenance, ruby

#19623 Freeze string literals in app/uploaders
  app/uploaders/direct_fog_uploader.rb
  app/uploaders/file_uploader.rb
  app/uploaders/fog_file_uploader.rb
  app/uploaders/local_file_uploader.rb
Labels: maintenance, ruby

#19624 Freeze string literals in app/validators
  app/validators/json_validator.rb
  app/validators/not_nil_validator.rb
  app/validators/secure_context_uri_validator.rb
  app/validators/url_validator.rb
Labels: maintenance, ruby

#19625 Freeze string literals in app/views
  app/views/common/feed.atom.builder
  app/views/journals/index.atom.builder
Labels: maintenance, ruby

#19618 Freeze string literals in app/menus
  app/menus/members/menu.rb
  app/menus/notifications/menu.rb
  app/menus/projects/menu.rb
  app/menus/submenu.rb
  app/menus/work_packages/menu.rb
Labels: maintenance, ruby

#18908 fix restore command for restoring assets for docker
  docs/installation-and-operations/operation/restoring/README.md
Labels: documentation, needs review

#19638 Fix building `config/frontend_assets.manifest.json`
  frontend/angular.json
  frontend/esbuild/plugins.ts
  lib/open_project/assets.rb
Labels: bugfix, javascript

#19621 Freeze string literals in app/seeders
  app/seeders/admin_user_seeder.rb
  app/seeders/basic_data/base_role_seeder.rb
  app/seeders/basic_data/color_scheme_seeder.rb
  app/seeders/basic_data/global_role_seeder.rb
  app/seeders/basic_data/priority_seeder.rb
  app/seeders/basic_data/project_custom_field_section_seeder.rb
  app/seeders/basic_data/project_phase_color_seeder.rb
  app/seeders/basic_data/project_phase_definition_seeder.rb
  app/seeders/basic_data/project_query_role_seeder.rb
  app/seeders/basic_data/project_role_seeder.rb
  app/seeders/basic_data/setting_seeder.rb
  app/seeders/basic_data/status_seeder.rb
  app/seeders/basic_data/time_entry_activity_seeder.rb
  app/seeders/basic_data/type_seeder.rb
  app/seeders/basic_data/work_package_role_seeder.rb
  app/seeders/basic_data/workflow_seeder.rb
  app/seeders/basic_data_seeder.rb
  app/seeders/composite_seeder.rb
  app/seeders/demo_data/global_query_seeder.rb
  app/seeders/demo_data/group_seeder.rb
  app/seeders/demo_data/overview_seeder.rb
  app/seeders/demo_data/project_seeder.rb
  app/seeders/demo_data/projects_seeder.rb
  app/seeders/demo_data/query_builder.rb
  app/seeders/demo_data/references.rb
  app/seeders/demo_data/version_builder.rb
  app/seeders/demo_data/wiki_seeder.rb
  app/seeders/demo_data/work_package_board_seeder.rb
  app/seeders/demo_data_seeder.rb
  app/seeders/development_data/custom_fields_seeder.rb
  app/seeders/env_data/ldap_seeder.rb
  app/seeders/env_data_seeder.rb
  app/seeders/root_seeder.rb
  app/seeders/seeder.rb
  app/seeders/standard/basic_data_seeder.rb
Labels: maintenance, ruby

#19665 Refactoring: PDF export rename parameter
  app/components/work_packages/exports/generate/modal_dialog_component.html.erb
  app/components/work_packages/exports/generate/modal_dialog_component.rb
  app/models/work_package/pdf_export/work_package_to_pdf.rb
  modules/meeting/app/components/meetings/exports/modal_dialog_component.html.erb
  modules/meeting/app/components/meetings/exports/modal_dialog_component.rb
  modules/meeting/app/workers/meetings/pdf/exporter.rb
  modules/meeting/config/locales/en.yml
  modules/meeting/spec/features/structured_meetings/structured_meeting_export_spec.rb
  modules/meeting/spec/workers/meetings/pdf/exporter_spec.rb
  spec/features/work_packages/generate_pdf_spec.rb
  spec/models/work_packages/pdf_export/work_package_to_pdf_spec.rb
Labels: maintenance

#19658 [#65998] Upgrade Angular to v20
  .github/workflows/docker.yml
  .github/workflows/eslint-core.yml
  .github/workflows/test-frontend-unit.yml
  frontend/angular.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/core/active-window/active-window.service.ts
  frontend/src/app/core/apiv3/api-v3.service.ts
  frontend/src/app/core/apiv3/paths/apiv3-resource.ts
  frontend/src/app/core/apiv3/paths/path-resources.ts
  frontend/src/app/core/browser/browser-detector.service.ts
  frontend/src/app/core/enterprise/banners.service.ts
  frontend/src/app/core/top-menu/top-menu.service.ts
  frontend/src/app/core/util-types.ts
  frontend/src/app/features/admin/types/type-banner.service.ts
  frontend/src/app/features/bim/bcf/api/bcf-api-request.service.ts
  frontend/src/app/features/bim/bcf/api/bcf-path-resources.ts
  frontend/src/app/features/bim/bcf/helper/bcf-detector.service.ts
  frontend/src/app/features/invite-user-modal/invite-user-modal-augment.service.ts
  frontend/src/app/features/work-packages/components/wp-table/external-configuration/external-query-configuration.service.ts
  frontend/src/app/shared/components/fields/display/display-field.component.ts
  frontend/src/app/shared/components/fields/edit/editing-portal/edit-form-portal.injector.ts
  frontend/src/app/shared/components/fields/edit/editing-portal/editing-portal-service.ts
  frontend/src/app/shared/components/fields/edit/field-types/select-edit-field/select-edit-field.component.ts
  frontend/src/app/shared/components/modal/modal-wrapper-augment.service.ts
  frontend/src/app/shared/components/modal/modal.service.ts
  frontend/src/app/shared/components/op-context-menu/op-context-menu.service.ts
  frontend/src/app/shared/helpers/angular/inject-field.decorator.ts
  frontend/src/app/shared/helpers/drag-and-drop/drag-and-drop.service.ts
Labels: maintenance, javascript

#19647 [65926] Impossible to change the left-side menu colour
  app/views/custom_styles/_interface.html.erb
Labels: bugfix, needs review

#19666 Fix Stimulus UsersController missing target error
  frontend/src/stimulus/controllers/dynamic/admin/users.controller.ts
Labels: javascript, tinyfix

#19688 Bump primer octicons to 19.26.0
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: maintenance

#19503 [65615] Document Link design guidelines
  lookbook/docs/patterns/04-links.md.erb
  lookbook/previews/open_project/common/link_preview.rb
  lookbook/previews/open_project/common/link_preview/inline.html.erb
Labels: documentation, maintenance

#19694 Bump octicons to 19.26.2
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: maintenance

#19668 Do not defer jQuery loading, remove `turbo:load` hacks
  app/helpers/frontend_asset_helper.rb
  app/views/wiki/edit_parent_page.html.erb
  frontend/angular.json
  modules/backlogs/app/views/rb_burndown_charts/_burndown.html.erb
  modules/bim/app/views/bim/ifc_models/ifc_models/_form.html.erb
  modules/documents/app/views/documents/index.html.erb
Labels: bugfix, javascript, needs review

#19633 Code maintenance/65033 Decompose WorkPackagesActivitiesTabIndex Stimulus JS Controller
  app/components/concerns/work_packages/activities_tab/stimulus_controllers.rb
  app/components/work_packages/activities_tab/index_component.rb
  app/components/work_packages/activities_tab/journals/item_component.rb
  app/components/work_packages/activities_tab/journals/item_component/add_reactions.html.erb
  app/components/work_packages/activities_tab/journals/item_component/add_reactions.rb
  app/components/work_packages/activities_tab/journals/item_component/edit.html.erb
  app/components/work_packages/activities_tab/journals/item_component/reactions.html.erb
  app/components/work_packages/activities_tab/journals/item_component/reactions.rb
  app/components/work_packages/activities_tab/journals/new_component.html.erb
  app/components/work_packages/activities_tab/shared_helpers.rb
  frontend/src/stimulus/controllers/dynamic/work-packages/activities-tab/auto-scrolling.controller.ts
  frontend/src/stimulus/controllers/dynamic/work-packages/activities-tab/base.controller.ts
  frontend/src/stimulus/controllers/dynamic/work-packages/activities-tab/editor.controller.ts
  frontend/src/stimulus/controllers/dynamic/work-packages/activities-tab/index.controller.ts
  frontend/src/stimulus/controllers/dynamic/work-packages/activities-tab/internal-comment.controller.ts
  frontend/src/stimulus/controllers/dynamic/work-packages/activities-tab/polling.controller.ts
  frontend/src/stimulus/controllers/dynamic/work-packages/activities-tab/quote-comment.controller.ts
  frontend/src/stimulus/controllers/dynamic/work-packages/activities-tab/services/view-port-service.ts
  frontend/src/stimulus/controllers/dynamic/work-packages/activities-tab/stems.controller.ts
  frontend/src/stimulus/setup.ts
  spec/features/activities/work_package/activities_spec.rb
  spec/support/components/work_packages/activities.rb
Labels: maintenance, javascript, needs review

#19709 Chore: bump md-to-pdf to v0.2.5
  Gemfile
  Gemfile.lock
  app/models/exports/pdf/components/page.rb
  app/models/exports/pdf/components/wp_table.rb
  app/models/work_package/pdf_export/common/markdown_field.rb
  app/models/work_package/pdf_export/report/detail.rb
  app/models/work_package/pdf_export/report/sums_table.rb
  app/models/work_package/pdf_export/report/table_of_contents.rb
  app/models/work_package/pdf_export/work_package_to_pdf.rb
  app/models/work_package/pdf_export/wp/attributes.rb
  spec/models/work_packages/pdf_export/work_package_to_pdf_spec.rb
Labels: maintenance

#19641 [#65866] NoMethodError in GET::API::V3::Queries::QueriesAPI#/queries/id
  app/models/journal/timestamps.rb
  spec/models/journal/timestamps_spec.rb
Labels: needs review

#19702 Fix permission on delete meeting series button
  modules/meeting/app/components/recurring_meetings/show_page_header_component.html.erb
Labels: bugfix, needs review

#19653 Gon begone!
  Gemfile
  Gemfile.lock
  app/views/layouts/_common_head.html.erb
  frontend/src/app/core/gon/gon.service.ts
  frontend/src/app/features/bim/ifc_models/ifc-viewer/ifc-viewer.service.ts
  frontend/src/app/features/bim/ifc_models/pages/viewer/ifc-models-data.service.ts
  frontend/src/app/features/bim/ifc_models/xeokit/xeokit-server.ts
  modules/bim/app/helpers/ifc_models_helper.rb
  modules/bim/app/views/bim/ifc_models/ifc_viewer/show.html.erb
  spec/views/users/edit.html.erb_spec.rb
Labels: maintenance

#19735 Extract polling and editor stimulus values from the index controller
  app/components/work_packages/activities_tab/index_component.rb
  frontend/src/stimulus/controllers/dynamic/work-packages/activities-tab/base.controller.ts
  frontend/src/stimulus/controllers/dynamic/work-packages/activities-tab/editor.controller.ts
  frontend/src/stimulus/controllers/dynamic/work-packages/activities-tab/index.controller.ts
  frontend/src/stimulus/controllers/dynamic/work-packages/activities-tab/polling.controller.ts
Labels: maintenance, needs review

#19717 [66128] 'Invite user' menu is missing an icon
  lib/redmine/menu_manager/top_menu/quick_add_menu.rb
Labels: bugfix

#19744 Make docker dev env `README.md` a bit more foolproof
  docs/development/development-environment/docker/README.md
Labels: documentation, tinyfix, docker

#19758 Remove `turbo:load` hacks from `base.html.erb`
  app/views/layouts/base.html.erb
Labels: bugfix, javascript, needs review
