Repository opf/openproject, pull requests merged in 2025-02, with the labels that each got.

#17791 bug/60976 Setting the user display format without lastname breaks user custom fields with Group values
  app/models/custom_field.rb
  spec/models/custom_field_spec.rb
Labels: bugfix, needs review

#17793 Do not allow time tracking for users that are not visible to you
  app/models/principal.rb
  modules/costs/app/contracts/time_entries/base_contract.rb
  modules/costs/spec/contracts/time_entries/create_contract_spec.rb
  modules/costs/spec/contracts/time_entries/shared_contract_examples.rb
  modules/costs/spec/contracts/time_entries/update_contract_spec.rb
  modules/costs/spec/controllers/time_entries_controller_spec.rb
  modules/costs/spec/factories/time_entry_factory.rb
  modules/costs/spec/models/time_entry_spec.rb
  modules/costs/spec/requests/api/time_entries/update_form_resource_spec.rb
  modules/costs/spec/requests/api/time_entry_resource_spec.rb
  modules/dashboards/spec/features/time_entries_spec.rb
Labels: bugfix

#17798 Include ongoing in upcoming scope of schedule meeting
  modules/meeting/app/controllers/recurring_meetings_controller.rb
  modules/meeting/app/helpers/recurring_meetings_helper.rb
  modules/meeting/app/models/recurring_meeting.rb
  modules/meeting/spec/models/recurring_meeting_spec.rb
Labels: bugfix

#17803 Use relative path instead of url for activities refresh
  app/components/work_packages/activities_tab/index_component.rb
  frontend/src/stimulus/controllers/dynamic/work-packages/activities-tab/index.controller.ts
Labels: needs review

#17815 Fix condition for checking if draft
  .github/workflows/version-check.yml
Labels: needs review

#17813 Merge release/15.2 into dev
  app/models/custom_field.rb
  config/locales/crowdin/nl.yml
  spec/models/custom_field_spec.rb
Labels: create-merge-release-into-dev-pr

#17817 [#60762] Changing the start date of a recurring meeting to a past date loses occurrences
  modules/meeting/app/contracts/recurring_meetings/update_contract.rb
Labels: bugfix

#17692 Feature/59925 show user popover on the name
  app/components/users/row_component.rb
  app/components/work_packages/activities_tab/journals/item_component.html.erb
  app/components/work_packages/activities_tab/journals/item_component/details.rb
  app/components/work_packages/activities_tab/shared_helpers.rb
  app/components/work_packages/hover_card_component.html.erb
  app/helpers/application_helper.rb
  app/views/homescreen/blocks/_users.html.erb
  config/locales/en.yml
  frontend/src/app/core/setup/globals/global-listeners/hover-card-trigger.service.ts
  frontend/src/app/shared/components/autocompleter/user-autocompleter/user-autocompleter-template.component.html
  frontend/src/app/shared/components/autocompleter/user-autocompleter/user-autocompleter-template.component.ts
  frontend/src/app/shared/components/principal/principal-renderer.service.ts
  frontend/src/app/shared/components/user-link/user-link.component.ts
  lib/open_project/object_linking.rb
  modules/meeting/app/components/meetings/header_infoline_component.html.erb
  modules/my_page/spec/features/my/work_package_table_spec.rb
  spec/features/users/index_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/lib/open_project/text_formatting/markdown/mentions_spec.rb
Labels: feature

#17825 [#59966] Main recurring meeting index doesn't show updated empty state
  modules/meeting/app/components/meetings/table_component.rb
  modules/meeting/app/views/meetings/_grouped_meetings.html.erb
  modules/meeting/app/views/meetings/index.html.erb
  modules/meeting/config/locales/en.yml
  modules/meeting/spec/features/meetings_delete_spec.rb
  modules/meeting/spec/features/meetings_index_spec.rb
  modules/meeting/spec/support/pages/meetings/index.rb
Labels: bugfix, needs review

#17827 Implement ending behavor for meetings
  modules/meeting/app/components/recurring_meetings/show_page_header_component.html.erb
  modules/meeting/app/controllers/recurring_meetings_controller.rb
  modules/meeting/app/models/recurring_meeting.rb
  modules/meeting/app/services/recurring_meetings/update_service.rb
  modules/meeting/app/views/recurring_meetings/_show_upcoming.html.erb
  modules/meeting/app/views/recurring_meetings/show.html.erb
  modules/meeting/config/locales/en.yml
  modules/meeting/spec/models/recurring_meeting_spec.rb
  modules/meeting/spec/requests/recurring_meetings/recurring_meetings_show_spec.rb
  modules/meeting/spec/services/recurring_meetings/update_service_integration_spec.rb
Labels: feature

#17829 Merge release/15.2 into dev
  app/components/work_packages/activities_tab/journals/new_component.sass
  docs/enterprise-guide/enterprise-cloud-guide/enterprise-cloud-faq/README.md
  frontend/src/turbo/helpers.ts
  frontend/src/turbo/turbo-event-listeners.ts
  frontend/src/typings/shims.d.ts
Labels: create-merge-release-into-dev-pr

#17831 Add jira migration tool info to the documentation
  docs/system-admin-guide/integrations/README.md
Labels: documentation

#17833 Updated docu link to PDF export styling yml
  docs/system-admin-guide/design/pdf-export-styles/README.md
Labels: documentation

#17839 Fix flaky spec
  modules/meeting/spec/features/recurring_meetings/recurring_meeting_end_series_spec.rb
Labels: flaky-spec

#17835 Fix js error when time entry has no activity
  frontend/src/app/features/calendar/te-calendar/te-calendar.component.ts
  frontend/src/app/features/hal/resources/time-entry-resource.ts
Labels: needs review

#17836 [61185] Replace storage deletion dialog with new DangerDialog
  modules/storages/app/components/storages/project_storages/destroy_confirmation_dialog_component.html.erb
  modules/storages/spec/features/storages/admin/project_storages_spec.rb
Labels: maintenance, needs review

#17843 Fix event listener binding
  frontend/src/app/features/work-packages/components/wp-reminder-modal/wp-reminder.modal.ts
  frontend/src/app/shared/components/fields/edit/field-types/progress-popover-edit-field.component.ts
  frontend/src/stimulus/controllers/disable-when-checked.controller.ts
  frontend/src/stimulus/controllers/dynamic/filter/filters-form.controller.ts
  frontend/src/stimulus/controllers/dynamic/projects/zen-mode.controller.ts
  frontend/src/stimulus/controllers/dynamic/shares/user-selected.controller.ts
  frontend/src/stimulus/controllers/show-when-checked.controller.ts
  frontend/src/stimulus/controllers/show-when-value-selected.controller.ts
Labels: bugfix, maintenance, needs review

#17850 Remove with_show_button of dialog rendered with turbo
  modules/meeting/app/components/meetings/side_panel/details_dialog_component.html.erb
Labels: bugfix, needs review

#17849 Fix setting direction for past meetings count
  modules/meeting/app/controllers/recurring_meetings_controller.rb
  modules/meeting/spec/requests/recurring_meetings/recurring_meetings_show_spec.rb
Labels: bugfix

#17851 Merge release/15.2 into dev
  docs/release-notes/15-2-1/README.md
  docs/release-notes/README.md
  docs/system-admin-guide/design/pdf-export-styles/README.md
  docs/system-admin-guide/integrations/README.md
  publiccode.yml
  script/docs/check_links
Labels: create-merge-release-into-dev-pr

#17856 [60705] Regression: If WP title is long without spaces, it overflows outside of the split screen
  app/components/_index.sass
  app/components/work_package_relations_tab/relation_component.html.erb
  app/components/work_package_relations_tab/relation_component.sass
Labels: bugfix

#17859 do not show the user input when logging from the my page
  frontend/src/app/features/calendar/te-calendar/te-calendar.component.ts
  modules/costs/app/controllers/time_entries_controller.rb
Labels: bugfix, needs review

#17844 Deal with anonymous user in meeting menu
  modules/meeting/app/menus/meetings/menu.rb
  modules/meeting/spec/requests/meetings_menu_spec.rb
Labels: bugfix

#17857 Bug/61307 log time modal allows to remove the user
  modules/costs/app/components/time_entries/user_form.rb
Labels: bugfix, needs review

#17868 [#61336] Role permissions concerning comments are named "Notes" and a…
  docs/system-admin-guide/users-permissions/roles-permissions/openproject_user_guide_file_storages_permissions.png
Labels: documentation

#17867 update teaser for 15.3
  config/locales/js-en.yml
  frontend/src/app/features/homescreen/blocks/new-features.component.ts
  frontend/src/assets/images/15_2_features.svg
  frontend/src/assets/images/15_3_features.svg
Labels: needs review

#17848 Ensure project stays selected on error in global meeting form
  frontend/src/app/shared/components/autocompleter/project-autocompleter/project-autocompleter.component.ts
  modules/meeting/app/controllers/meetings_controller.rb
  modules/meeting/app/controllers/recurring_meetings_controller.rb
  modules/meeting/app/forms/meeting/project_autocompleter.rb
  modules/meeting/spec/features/recurring_meetings/recurring_meeting_global_create_spec.rb
  modules/meeting/spec/features/structured_meetings/structured_meeting_global_crud_spec.rb
Labels: bugfix

#17845 [#61194] Last planned meeting is not showing when current meeting is in both 'Upcoming' and 'Past' tab
  modules/meeting/app/controllers/recurring_meetings_controller.rb
  modules/meeting/app/models/recurring_meeting.rb
  modules/meeting/spec/features/meetings_index_spec.rb
  modules/meeting/spec/requests/recurring_meetings/recurring_meetings_show_spec.rb
  modules/meeting/spec/support/pages/recurring_meeting/show.rb
Labels: bugfix, needs review

#17875 update bundler in docker build to fix issue with uninstalled gems
  docker/ci/Dockerfile
  docker/dev/backend/Dockerfile
  docker/prod/Dockerfile
  docs/development/development-environment/linux/README.md
  docs/development/development-environment/macos/README.md
Labels: needs review

#17871 [#61301] User gets a 500 if they edit a meeting series and lower the count of total occurrences to less than the count of currently open occurrences
  modules/meeting/app/controllers/recurring_meetings_controller.rb
  modules/meeting/spec/requests/recurring_meetings/recurring_meetings_show_spec.rb
Labels: bugfix

#17883 [#61364] Saving changes to the meetings series details saves the template even though template is not yet saved
  modules/meeting/app/components/meeting_agenda_items/list_component.html.erb
  modules/meeting/config/locales/en.yml
  modules/meeting/spec/features/recurring_meetings/recurring_meeting_create_spec.rb
Labels: bugfix

#17805 Add some docs for keycloak dev setup
  docker/dev/keycloak/README.md
Labels: documentation

#17789 [60358] Document the two variants of the DangerDialog
  lookbook/docs/patterns/14-danger-dialog.md.erb
Labels: documentation, maintenance

#17891 [61293] Sub-headlines are larger than the actual PageHeader on meetings index page
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
  modules/meeting/app/components/recurring_meetings/table_header_component.html.erb
  modules/meeting/app/views/meetings/_grouped_meetings.html.erb
Labels: bugfix, styling, needs review

#17892 [61395] Spacing issues in log time dialog
  modules/costs/app/components/time_entries/entry_dialog_component.html.erb
  modules/costs/app/components/time_entries/time_entry_form_component.html.erb
Labels: bugfix, styling, needs review

#17898 [#61335] Cost reports should include work package children https://c…
  docs/user-guide/time-and-costs/progress-tracking/README.md
  docs/user-guide/time-and-costs/reporting/README.md
  docs/user-guide/time-and-costs/reporting/openproject_userguide_timeandcosts_module_filter.png
Labels: documentation

#17899 [60746] Missing breadcrumb in Times & Cost Administration
  modules/costs/app/views/cost_types/edit.html.erb
  modules/costs/app/views/cost_types/index.html.erb
  modules/costs/app/views/costs_settings/show.html.erb
Labels: bugfix, needs review

#17915 [#61329] Display sums in Timesheet PDF https://community.openproject…
  docs/user-guide/time-and-costs/reporting/README.md
  docs/user-guide/time-and-costs/reporting/openproject_userguide_timesheet_pdf_export_multiple_users.png
Labels: documentation

#17927 [#61326] Show user popover on the name, not only avatar https://comm…
  docs/system-admin-guide/users-permissions/users/README.md
Labels: documentation

#17906 Remove jQuery from globals
  frontend/src/app/core/setup/globals/global-helpers.ts
  frontend/src/app/core/setup/globals/openproject.ts
  frontend/src/main.ts
Labels: maintenance, javascript, tinyfix

#17755 improve performance of relations visible scope
  app/components/work_package_relations_tab/relations_mediator.rb
  app/models/relations/scopes/visible.rb
  app/models/work_package.rb
  app/models/work_packages/relations.rb
  lib/api/v3/work_packages/work_package_representer.rb
  spec/lib/api/v3/work_packages/work_package_representer_spec.rb
  spec/models/work_package/work_package_relations_spec.rb
Labels: needs review

#17930 Avoid rescue by checking for the table`s existence
  config/initializers/retry_failed_jobs_with_name_error.rb
Labels: needs review

#17917 Allow moving meeting occurrence earlier
  modules/meeting/app/contracts/meetings/update_contract.rb
  modules/meeting/app/controllers/recurring_meetings_controller.rb
  modules/meeting/app/mailers/meeting_series_mailer.rb
  modules/meeting/app/models/recurring_meeting.rb
  modules/meeting/app/models/scheduled_meeting.rb
  modules/meeting/spec/services/meetings/update_service_integration_spec.rb
Labels: bugfix

#17919 [#61306] Dialog text should use "Cancel occurrence"
  modules/meeting/app/components/meetings/delete_dialog_component.html.erb
  modules/meeting/app/components/meetings/delete_dialog_component.rb
  modules/meeting/config/locales/en.yml
  modules/meeting/spec/components/meetings/delete_dialog_component_spec.rb
  modules/meeting/spec/components/recurring_meetings/delete_scheduled_dialog_component_spec.rb
  modules/meeting/spec/features/recurring_meetings/recurring_meeting_crud_spec.rb
  modules/meeting/spec/features/recurring_meetings/recurring_meeting_global_crud_spec.rb
  modules/meeting/spec/support/pages/recurring_meeting/show.rb
Labels: bugfix

#17904 Fix Nextcloud capitalization in I18n strings, docs
  modules/storages/spec/common/storages/peripherals/storage_interaction/nextcloud/create_folder_command_spec.rb
Labels: bugfix, maintenance, needs review, tinyfix

#17934 [43665] Missing space for no-results box on mobile
  frontend/src/app/features/work-packages/routing/wp-list-view/wp-list-view.component.sass
Labels: bugfix, needs review

#17935 Ensure meeting series are created in the future
  modules/meeting/app/contracts/recurring_meetings/create_contract.rb
  modules/meeting/config/locales/en.yml
  modules/meeting/spec/services/recurring_meetings/create_service_integration_spec.rb
Labels: bugfix

#17936 Code maintenance/61471 Migration Utils Permission adder crashes when supplied with a permission that no longer exists
  db/migrate/migration_utils/permission_adder.rb
  spec/migrations/permission_adder_spec.rb
Labels: needs review

#17916 [#61330] Remove ability to set default time tracking activity https:…
  docs/system-admin-guide/enumerations/README.md
  docs/system-admin-guide/enumerations/openproject_system_admin_guide_enumerations.png
Labels: documentation

#17946 Compare with beginning_of_day for meeting index groups
  modules/meeting/app/controllers/meetings_controller.rb
  modules/meeting/spec/requests/meetings_index_spec.rb
Labels: bugfix

#17776 [60869] No error message shows on Relations modal if no WP is selected
  app/components/work_package_relations_tab/add_work_package_child_form_component.html.erb
  app/components/work_package_relations_tab/add_work_package_child_form_component.rb
  app/components/work_package_relations_tab/work_package_relation_form_component.html.erb
  app/components/work_package_relations_tab/work_package_relation_form_component.rb
  app/contracts/relations/base_contract.rb
  app/contracts/relations/update_contract.rb
  app/controllers/work_package_children_relations_controller.rb
  app/controllers/work_package_relations_controller.rb
  app/models/relation.rb
  config/locales/en.yml
  spec/contracts/relations/shared_contract_examples.rb
  spec/contracts/relations/update_contract_spec.rb
  spec/features/work_packages/details/relations/primerized_relations_spec.rb
  spec/models/queries/relations/filters/from_filter_spec.rb
  spec/models/relation_spec.rb
  spec/requests/api/v3/relations/relations_api_spec.rb
  spec/support/components/work_packages/relations.rb
Labels: bugfix, needs review

#17911 Bug/58260 disable hover card on mobile
  frontend/src/stimulus/controllers/hover-card-trigger.controller.ts
  spec/features/members/membership_spec.rb
  spec/support/pages/members.rb
Labels: bugfix, needs review

#17932 [#61328] 15.3 Relations tab changes https://community.openproject.or…
  docs/user-guide/work-packages/work-package-relations-hierarchies/README.md
  docs/user-guide/work-packages/work-package-relations-hierarchies/openproject_user_guide_ghost_relations.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/openproject_user_guide_relations_tab_edit_lag.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/openproject_user_guide_wp_add_child.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/openproject_user_guide_wp_add_child_new.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/openproject_user_guide_wp_add_relations_button.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/openproject_user_guide_wp_relations_child_button.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/openproject_user_guide_wp_relations_tab_overview.png
Labels: documentation

#17944 Ensure human_attribute_name is present on ServiceResult
  app/services/service_result.rb
  spec/services/service_result_spec.rb
Labels: bugfix, needs review

#17910 Update serving open project via local network to external devices documentation
  docs/development/running-tests/README.md
  frontend/package.json
Labels: needs review

#17950 [60629] Display messed up after creating child from relations tab in split view
  frontend/src/app/core/routing/openproject.routes.ts
  spec/features/work_packages/tabs/relations_children_spec.rb
Labels: bugfix, needs review

#17963 Move meetings after boards
  Gemfile.modules
  modules/meeting/lib/open_project/meeting/engine.rb
Labels: feature

#17939 [60638] Opening a work package (full view) on mobile auto-scrolls to the tab row when not desired
  frontend/src/app/features/work-packages/components/wp-single-view-tabs/activity-panel/activity-tab.component.ts
  frontend/src/app/features/work-packages/components/wp-single-view-tabs/activity-panel/activity-tab.html
  frontend/src/app/features/work-packages/routing/wp-full-view/wp-full-view.html
  frontend/src/app/features/work-packages/routing/wp-split-view/wp-split-view.component.ts
  frontend/src/app/features/work-packages/routing/wp-split-view/wp-split-view.html
Labels: bugfix, needs review, Accessibility

#17926 Final changes release notes 15.3
  docs/release-notes/15-3-0/README.md
Labels: documentation

#17967 Reword meeting labels
  modules/meeting/app/forms/recurring_meeting/frequency.rb
  modules/meeting/app/models/recurring_meeting.rb
  modules/meeting/config/locales/en.yml
  modules/meeting/spec/features/recurring_meetings/recurring_meeting_crud_spec.rb
  modules/meeting/spec/requests/recurring_meetings/recurring_meetings_schedule_spec.rb
Labels: feature

#17978 Bump bundler
  Gemfile.lock
Labels: dependencies, ruby, needs review

#17984 15.3-docs-improvements
  docs/user-guide/meetings/README.md
  docs/user-guide/meetings/one-time-meetings/README.md
  docs/user-guide/meetings/recurring-meetings/README.md
Labels: documentation

#17987 [#61461] Harmonize capitalization of tab names https://community.ope…
  docs/getting-started/work-packages-introduction/README.md
  docs/user-guide/activity/README.md
  docs/user-guide/forums/README.md
  docs/user-guide/work-packages/edit-work-package/README.md
  docs/user-guide/work-packages/work-package-relations-hierarchies/README.md
  docs/user-guide/work-packages/work-packages-faq/README.md
Labels: documentation

#17846 Feature/60521 autocompleters for filter values on the project list
  app/components/filter/filter_component.rb
  app/views/filters/_autocomplete.html.erb
  frontend/src/app/shared/components/autocompleter/op-autocompleter/op-autocompleter.component.ts
  spec/features/projects/lists/filters_spec.rb
  spec/support/components/autocompleter/ng_select_autocomplete_helpers.rb
  spec/support/pages/projects/index.rb
Labels: needs review

#17993 Do not display time entry comment unsanitized in My Spent Time widget
  frontend/src/app/features/calendar/te-calendar/te-calendar.component.ts
Labels: bugfix, security

#17990 less dependent specs on project list filters
  spec/features/projects/lists/filters_spec.rb
Labels: needs review

#17994 limit time entry comment to the current database value with a rails validation
  modules/costs/app/components/time_entries/comments_form.rb
  modules/costs/app/models/time_entry.rb
  modules/costs/spec/models/time_entry_spec.rb
Labels: bugfix, needs review

#17997 Add release video to 15.3 release notes
  docs/release-notes/15-3-0/README.md
Labels: documentation

#17971 [61543] Big space below the comment box on mobile
  app/components/work_packages/activities_tab/index_component.html.erb
  app/components/work_packages/activities_tab/index_component.sass
Labels: bugfix, needs review

#17996 Merge release/15.3 into dev
  docs/glossary/README.md
  docs/release-notes/15-1-1/README.md
  docs/release-notes/15-3-0/README.md
  docs/release-notes/README.md
  docs/user-guide/meetings/README.md
  docs/user-guide/meetings/recurring-meetings/README.md
  docs/user-guide/work-packages/edit-work-package/README.md
  frontend/src/app/features/calendar/te-calendar/te-calendar.component.ts
  modules/costs/app/components/time_entries/comments_form.rb
  modules/costs/app/models/time_entry.rb
  modules/costs/spec/models/time_entry_spec.rb
  publiccode.yml
Labels: create-merge-release-into-dev-pr

#17948 [61448] Replace "last" by "closest" in the "no predecessors" placeholder in date picker
  config/locales/en.yml
Labels: bugfix, needs review

#18001 Fix openapi: time entry comments are plain strings
  docs/api/apiv3/components/schemas/time_entry_model.yml
Labels: documentation

#17973 60858 in add relation dialog selecting a wp that user doesnt have permission to edit raises an error
  app/contracts/work_packages/update_contract.rb
  app/controllers/work_package_children_relations_controller.rb
  config/locales/en.yml
Labels: bugfix, needs review

#18002 Bump rubocop_performance
  .rubocop.yml
  Gemfile.lock
Labels: needs review

#17962 Wait for cost entry to update after save before test assertion
  modules/costs/spec/features/cost_entries/add_cost_entry_spec.rb
Labels: needs review, flaky-spec

#18009 Group AWS gems into one dependabot PR
  .github/dependabot.yml
Labels: needs review

#18011 Delete recurring_meetings together with project
  app/models/project.rb
  modules/meeting/spec/services/projects/delete_service_spec.rb
Labels: bugfix

#18021 Bump primer to 0.54.1
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: maintenance

#17980 Never assign builtin users as meeting participants
  modules/meeting/app/controllers/meetings_controller.rb
  modules/meeting/app/models/meeting.rb
  modules/meeting/app/services/meetings/copy_service.rb
  modules/meeting/app/services/meetings/set_attributes_service.rb
  modules/meeting/spec/factories/meeting_factory.rb
  modules/meeting/spec/factories/recurring_meeting_factory.rb
  modules/meeting/spec/features/meetings_close_spec.rb
  modules/meeting/spec/features/meetings_copy_spec.rb
  modules/meeting/spec/features/meetings_index_spec.rb
  modules/meeting/spec/features/structured_meetings/mobile_structure_meeting_spec.rb
  modules/meeting/spec/features/structured_meetings/structured_meeting_delete_spec.rb
  modules/meeting/spec/features/structured_meetings/structured_meeting_participant_spec.rb
  modules/meeting/spec/models/meeting_spec.rb
  modules/meeting/spec/requests/meetings_delete_spec.rb
  modules/meeting/spec/requests/meetings_index_spec.rb
  modules/meeting/spec/services/meetings/copy_service_integration_spec.rb
  modules/meeting/spec/services/meetings/create_service_spec.rb
Labels: bugfix

#18024 Change the time entries work package as intended instead of creating a new one
  modules/costs/app/components/time_entries/time_entry_form_component.rb
  modules/costs/app/controllers/time_entries_controller.rb
  modules/costs/config/routes.rb
  modules/costs/spec/features/time_entry_dialog_spec.rb
  modules/my_page/spec/features/my/time_entries_current_user_spec.rb
Labels: bugfix

#18026 Update README.md
  docs/faq/README.md
Labels: documentation

#18015 Show an error when logging time on a work package you did not have permission to log for
  modules/costs/app/components/time_entries/work_package_form.rb
  modules/costs/app/contracts/time_entries/create_contract.rb
  modules/costs/config/locales/en.yml
  modules/costs/spec/contracts/time_entries/create_contract_spec.rb
  modules/costs/spec/requests/api/time_entry_resource_spec.rb
Labels: bugfix

#18027 Merge release/15.3 into dev
  modules/costs/app/components/time_entries/time_entry_form_component.rb
  modules/costs/app/controllers/time_entries_controller.rb
  modules/costs/config/routes.rb
  modules/costs/spec/features/time_entry_dialog_spec.rb
  modules/meeting/app/controllers/meetings_controller.rb
  modules/meeting/app/models/meeting.rb
  modules/meeting/app/services/meetings/copy_service.rb
  modules/meeting/app/services/meetings/set_attributes_service.rb
  modules/meeting/spec/factories/meeting_factory.rb
  modules/meeting/spec/factories/recurring_meeting_factory.rb
  modules/meeting/spec/features/meetings_close_spec.rb
  modules/meeting/spec/features/meetings_copy_spec.rb
  modules/meeting/spec/features/meetings_index_spec.rb
  modules/meeting/spec/features/structured_meetings/mobile_structure_meeting_spec.rb
  modules/meeting/spec/features/structured_meetings/structured_meeting_delete_spec.rb
  modules/meeting/spec/features/structured_meetings/structured_meeting_participant_spec.rb
  modules/meeting/spec/models/meeting_spec.rb
  modules/meeting/spec/requests/meetings_delete_spec.rb
  modules/meeting/spec/requests/meetings_index_spec.rb
  modules/meeting/spec/services/meetings/copy_service_integration_spec.rb
  modules/meeting/spec/services/meetings/create_service_spec.rb
  modules/my_page/spec/features/my/time_entries_current_user_spec.rb
Labels: create-merge-release-into-dev-pr

#18022 Bump primer to 0.55.0
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: maintenance, dependencies

#18035 allow custom url + custom function for loading work packages in autocompleter
  frontend/src/app/shared/components/autocompleter/op-autocompleter/op-autocompleter.component.ts
  frontend/src/app/shared/components/autocompleter/op-autocompleter/services/op-autocompleter.service.ts
  frontend/src/app/shared/components/autocompleter/time-entries-work-package-autocompleter/time-entries-work-package-autocompleter.component.ts
  modules/costs/app/components/time_entries/work_package_form.rb
Labels: DO NOT MERGE

#18038 Fix incorrect erb todo and disable comment indentation erb rule
  .erb_lint.yml
  app/views/work_packages/bulk/edit.html.erb
Labels: needs review

#18020 Fix cost log edit form field updater
  frontend/src/app/shared/components/remote-field-updater/remote-field-updater.component.ts
  modules/costs/app/views/admin/cost_types/edit.html.erb
  modules/costs/app/views/costlog/edit.html.erb
  modules/costs/spec/features/cost_entries/add_cost_entry_spec.rb
Labels: needs review

#18044 flaky test - wait for network requests to complete on wp update in activities spec
  spec/features/activities/work_package/activities_spec.rb
Labels: flaky-spec

#18053 bug/61708 Cannot delete users who used emoji reactions
  app/models/user.rb
  spec/models/user_spec.rb
Labels: bugfix, needs review

#18041 Make some files ready for frozen string literals
  app/helpers/application_helper.rb
  app/services/notifications/create_from_model_service.rb
  lib/custom_field_form_builder.rb
  lib/open_project/form_tag_helper.rb
  spec/contracts/shared/model_contract_shared_context.rb
Labels: needs review

#18046 Use default loadFromUrl option in autocompleter, not relation mode
  app/components/work_package_relations_tab/add_work_package_child_form_component.html.erb
  app/components/work_package_relations_tab/work_package_relation_form_component.html.erb
  frontend/src/app/shared/components/autocompleter/op-autocompleter/op-autocompleter.component.ts
  frontend/src/app/shared/components/autocompleter/op-autocompleter/services/op-autocompleter.service.ts
  lib/api/v3/work_packages/available_relation_candidates_api.rb
Labels: maintenance

#18055 [60618] Updated heading for project list deletion dialog
  app/components/projects/delete_list_modal_component.html.erb
  config/locales/en.yml
Labels: bugfix, needs review

#18067 bug/61756 Cannot delete users who have work package reminders
  app/models/reminder_notification.rb
  app/models/user.rb
  app/workers/principals/delete_job.rb
  spec/models/reminder_notification_spec.rb
  spec/models/user_spec.rb
Labels: bugfix

#18073 [#61775] Improve FAQs https://community.openproject.org/work_package…
  docs/faq/README.md
Labels: documentation

#18018 Allow admins to choose not exchanging for specific SSO token
  frontend/src/stimulus/controllers/dynamic/storages/storage-audience.controller.ts
  modules/storages/app/common/storages/peripherals/nextcloud_registry.rb
  modules/storages/app/common/storages/peripherals/nextcloud_storage_wizard.rb
  modules/storages/app/components/storages/admin/forms/nextcloud_audience_form_component.html.erb
  modules/storages/app/components/storages/admin/forms/nextcloud_audience_form_component.rb
  modules/storages/app/components/storages/admin/nextcloud_audience_info_component.erb
  modules/storages/app/components/storages/admin/nextcloud_audience_info_component.rb
  modules/storages/app/contracts/storages/storages/nextcloud_audience_contract.rb
  modules/storages/app/controllers/storages/admin/storages_controller.rb
  modules/storages/app/forms/storages/admin/nextcloud_audience_input_form.rb
  modules/storages/app/models/storages/nextcloud_storage.rb
  modules/storages/app/services/storages/storages/set_attributes_service.rb
  modules/storages/config/locales/en.yml
  modules/storages/config/routes.rb
  modules/storages/spec/common/storages/peripherals/nextcloud_connection_validator_spec.rb
  modules/storages/spec/common/storages/peripherals/nextcloud_storage_wizard_spec.rb
  modules/storages/spec/contracts/storages/storages/nextcloud_contract_spec.rb
  modules/storages/spec/factories/storage_factory.rb
  modules/storages/spec/features/storages/admin/create_storage_spec.rb
  modules/storages/spec/features/storages/admin/edit_storage_spec.rb
  modules/storages/spec/models/storages/nextcloud_storage_spec.rb
Labels: needs review

#18072 chore: bump md_to_pdf to 0.2.0
  Gemfile
  Gemfile.lock
  app/models/work_package/pdf_export/export/schema.json
Labels: needs review

#18074 Merge release/15.3 into dev
  Gemfile
  Gemfile.lock
  app/models/reminder_notification.rb
  app/models/user.rb
  app/models/work_package/pdf_export/export/schema.json
  app/workers/principals/delete_job.rb
  docs/faq/README.md
  docs/release-notes/15-3-1/README.md
  docs/release-notes/README.md
  publiccode.yml
  spec/models/reminder_notification_spec.rb
  spec/models/user_spec.rb
Labels: create-merge-release-into-dev-pr

#18078 use costs instead of cost
  modules/costs/app/views/admin/costs_settings/show.html.erb
Labels: needs review

#18098 add missing space to README
  README.md
Labels: documentation, maintenance

#18100 Update pimer to version 0.56.0
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: maintenance

#18102 Update installation docs
  docs/installation-and-operations/installation/README.md
Labels: documentation

#18096 Update the version we use for our own omniauth-fork
  Gemfile
  Gemfile.lock
Labels: needs review

#18068 Make sure redirect URI does not show as completed prematurely
  modules/storages/app/components/storages/admin/redirect_uri_component.html.erb
  modules/storages/app/models/storages/one_drive_storage.rb
  modules/storages/spec/models/storages/one_drive_storage_spec.rb
Labels: needs review

#18105 Remove author check from meeting notifications
  modules/meeting/app/services/meeting_notification_service.rb
Labels: bugfix

#18086 Use opf/ferrum fork
  Gemfile
  Gemfile.lock
Labels: maintenance

#18103 [61860] Separate component definition from patterns in the lookbook
  lookbook/docs/components/danger-dialog.md.erb
  lookbook/docs/components/feedback-dialog-and-feedback-message.md.erb
  lookbook/docs/components/hover-cards.md.erb
  lookbook/docs/components/page-header.md.erb
  lookbook/docs/components/page-heading.md.erb
  lookbook/docs/components/sub-header.md.erb
  lookbook/docs/components/tables.md.erb
  lookbook/docs/components/work-package-info-line.md.erb
  lookbook/previews/op_primer/border_box_table_component_preview.rb
  lookbook/previews/op_primer/status_button_component_preview.rb
  lookbook/previews/open_project/deprecated/danger_zone_preview/default.html.erb
  lookbook/previews/open_project/deprecated/widget_component_preview/default.html.erb
  lookbook/previews/open_project/work_packages/info_line_component_preview.rb
Labels: maintenance, needs review
