Repository opf/openproject, pull requests merged in 2025-05, with the labels that each got.

#18796 run IfcConvert in working dir to ensure it is writable
  modules/bim/app/services/bim/ifc_models/view_converter_service.rb
Labels: bugfix, needs review

#18813 Docs/fixes
  docs/glossary/README.md
Labels: documentation

#18808 [63444] Sort projects in Favorite Projects widget on My page alphabetically
  frontend/src/app/shared/components/grids/widgets/project-favorites/widget-project-favorites.component.ts
Labels: bugfix, needs review

#18771 More time tracking calendar layout fixes
  frontend/src/stimulus/controllers/dynamic/my/time-tracking.controller.ts
  modules/costs/app/components/my/time_tracking/calendar_component.sass
  modules/costs/app/components/my/time_tracking/list_component.rb
  modules/costs/app/components/my/time_tracking/sub_header_component.html.erb
  modules/costs/config/locales/en.yml
  modules/costs/lib/full_calendar/time_entry_event.rb
Labels: needs review

#18815 update teaser text for 16.0
  config/locales/js-en.yml
  frontend/src/app/features/homescreen/blocks/new-features.component.ts
Labels: pullpreview, needs review

#18785 Implement homescreen banner
  app/assets/images/enterprise/homescreen.png
  app/views/homescreen/blocks/_upsell.html.erb
  config/locales/en.yml
  config/locales/js-en.yml
  frontend/src/global_styles/content/_enterprise.sass
  frontend/src/global_styles/openproject/_homescreen.sass
Labels: feature, needs review

#18823 Fix behavior of wrong entries in edit modal when switching timezones
  modules/costs/app/components/time_entries/days_and_hours_form.rb
  modules/costs/app/components/time_entries/user_form.rb
  modules/costs/app/controllers/time_entries_controller.rb
Labels: bugfix

#18830 Do not allow to enable enforcement of exact times when it is not enabled
  modules/costs/app/controllers/admin/costs_settings_controller.rb
  modules/costs/config/locales/en.yml
Labels: bugfix, needs review

#18831 Do not assign time zone, when there is no user
  modules/costs/app/services/time_entries/set_attributes_service.rb
  modules/costs/spec/services/time_entries/set_attributes_service_spec.rb
Labels: bugfix

#18809 Release Notes 16.0
  docs/release-notes/16-0-0/README.md
  docs/release-notes/16-0-0/openproject-16-0-internal-comment.png
  docs/release-notes/16-0-0/openproject-16-0-meeting-backlogs-one-time-highlighted.png
  docs/release-notes/16-0-0/openproject-16-0-meeting-backlogs-recurring-options.png
  docs/release-notes/16-0-0/openproject-16-0-my-time-tracking-calendar-view.png
  docs/release-notes/16-0-0/openproject-16-0-my-time-tracking-list-view.png
  docs/release-notes/16-0-0/openproject-16-0-parent-relation.png
  docs/release-notes/16-0-0/openproject-16-0-save-export-settings-highlighted.png
  docs/release-notes/16-0-0/openproject-16-0-timesheet-hours-user-day.png
  docs/release-notes/16-0-0/openproject-project-reports.png
Labels: documentation

#18827 [#63611] remove feature flag for generated subjects
  app/helpers/types_helper.rb
  config/initializers/feature_decisions.rb
Labels: pullpreview

#18841 do not use output in highlight CSS as it already concat'ed to the output buffer
  app/views/highlighting/styles.css.erb
Labels: bugfix, needs review

#18838 Merge release/16.0 into dev
  app/contracts/types/base_contract.rb
  app/helpers/types_helper.rb
  app/models/types/pattern_resolver.rb
  app/models/types/patterns/attribute_token.rb
  app/models/types/patterns/token_property_mapper.rb
  config/initializers/feature_decisions.rb
  config/initializers/homescreen.rb
  docs/release-notes/16-0-0/README.md
  docs/release-notes/16-0-0/openproject-16-0-internal-comment.png
  docs/release-notes/16-0-0/openproject-16-0-meeting-backlogs-one-time-highlighted.png
  docs/release-notes/16-0-0/openproject-16-0-meeting-backlogs-recurring-options.png
  docs/release-notes/16-0-0/openproject-16-0-my-time-tracking-calendar-view.png
  docs/release-notes/16-0-0/openproject-16-0-my-time-tracking-list-view.png
  docs/release-notes/16-0-0/openproject-16-0-parent-relation.png
  docs/release-notes/16-0-0/openproject-16-0-save-export-settings-highlighted.png
  docs/release-notes/16-0-0/openproject-16-0-timesheet-hours-user-day.png
  docs/release-notes/16-0-0/openproject-project-reports.png
  modules/costs/app/controllers/admin/costs_settings_controller.rb
  modules/costs/app/services/time_entries/set_attributes_service.rb
  modules/costs/spec/services/time_entries/set_attributes_service_spec.rb
  spec/contracts/types/base_contract_spec.rb
Labels: create-merge-release-into-dev-pr

#18843 Merge release/16.0 into dev
  Gemfile
  Gemfile.lock
  app/models/types/patterns/token_property_mapper.rb
  app/views/highlighting/styles.css.erb
  config/locales/js-en.yml
  modules/auth_saml/app/models/saml/provider/hash_builder.rb
  modules/meeting/app/controllers/concerns/meetings/agenda_component_streams.rb
  modules/meeting/app/controllers/meeting_agenda_items_controller.rb
  modules/meeting/app/models/meeting.rb
  modules/meeting/spec/features/structured_meetings/structured_meeting_update_flash_spec.rb
  modules/meeting/spec/features/structured_meetings/update_flash_shared_examples.rb
  modules/meeting/spec/support/pages/meetings/show.rb
Labels: create-merge-release-into-dev-pr

#18753 [59918] Broken pages in lookbook
  lookbook/previews/open_project/deprecated/scrollable_tabs_preview.rb
  lookbook/previews/open_project/filter/filters_component_preview.rb
Labels: bugfix

#18834 Use selected date for the "+ Log Time" button
  modules/costs/app/components/my/time_tracking/sub_header_component.html.erb
Labels: bugfix, needs review

#18833 Fix input group selection
  app/forms/settings/form_decorator.rb
  spec/features/admin/settings/authentication_settings_spec.rb
Labels: bugfix

#18835 Allow forcing a feature flag to be active
  config/constants/settings/definition.rb
  lib_static/open_project/feature_decisions.rb
  spec/constants/settings/definition_spec.rb
  spec/lib/open_project/feature_decisions_spec.rb
Labels: pullpreview

#18846 Document breaking api changes
  docs/api/apiv3/openapi-spec.yml
  docs/release-notes/16-0-0/README.md
Labels: documentation

#18858 Add missing notification center loading Gif for light High Contrast mode
  app/controllers/notifications_controller.rb
  config/locales/en.yml
  frontend/src/assets/images/notification-center/notification_loading_lightHighContrast.gif
  spec/features/notifications/notification_center/notification_center_spec.rb
Labels: bugfix

#18874 [63913] Work package subject can overflow on list view
  app/components/op_primer/border_box_table_component.sass
Labels: bugfix, styling, needs review

#18779 bug/61544 Activity Tab renders the same turbo frame multiple times inside of itself
  app/components/concerns/work_packages/activities_tab/stimulus_controllers.rb
  app/components/work_packages/activities_tab/index_component.html.erb
  app/components/work_packages/activities_tab/index_component.rb
  app/components/work_packages/activities_tab/journals/item_component.rb
  spec/support/components/work_packages/activities.rb
Labels: bugfix

#18791 `ServiceResult` minor code improvements and documentation
  app/services/service_result.rb
  lib/open_project/patches/active_record_i18n.rb
Labels: maintenance, styling, ruby, needs review, tinyfix

#18881 Allow updating meeting status with edit_meeting permission
  modules/meeting/lib/open_project/meeting/engine.rb
  modules/meeting/spec/requests/meetings_status_spec.rb
Labels: bugfix, needs review

#18800 [58704] Quick wins for top bar search
  frontend/src/app/core/global_search/input/global-search-input-mobile.component.sass
  frontend/src/app/core/global_search/input/global-search-input.component.html
  frontend/src/app/core/global_search/input/global-search-input.component.sass
  frontend/src/app/core/global_search/input/global-search-input.component.ts
  frontend/src/app/core/global_search/input/global-search.component.sass
  spec/features/search/search_spec.rb
Labels: bugfix

#18892 Fix log time caption
  modules/costs/app/components/my/time_tracking/time_entries_list_component.rb
Labels: bugfix, needs review

#18859 limit Projects tab to work packages and project custom fields
  app/components/admin/custom_fields/edit_form_header_component.rb
Labels: pullpreview

#18863 [#63796] Authentication settings administration changes https://comm…
  docs/installation-and-operations/configuration/README.md
  docs/system-admin-guide/authentication/README.md
  docs/system-admin-guide/authentication/authentication-faq/README.md
  docs/system-admin-guide/authentication/authentication-settings/README.md
  docs/system-admin-guide/authentication/authentication-settings/openproject_system_admin_guide_authentication_settings.png
  docs/system-admin-guide/authentication/authentication-settings/openproject_system_admin_guide_authentication_settings_other.png
  docs/system-admin-guide/authentication/authentication-settings/openproject_system_admin_guide_authentication_settings_passwords.png
  docs/system-admin-guide/authentication/authentication-settings/openproject_system_admin_guide_authentication_settings_registration_footer.png
  docs/system-admin-guide/authentication/login-registration-settings/README.md
  docs/system-admin-guide/authentication/login-registration-settings/openproject_system_admin_guide_authentication_settings_login_and_registration.png
  docs/system-admin-guide/authentication/login-registration-settings/openproject_system_admin_guide_authentication_settings_login_sso_tab.png
  docs/system-admin-guide/authentication/login-registration-settings/openproject_system_admin_guide_authentication_settings_password_tab.png
  docs/system-admin-guide/authentication/login-registration-settings/openproject_system_admin_guide_authentication_settings_registration_tab.png
  docs/system-admin-guide/authentication/openproject_system_guide_authentication_settings.png
  docs/system-admin-guide/authentication/saml/README.md
  docs/system-admin-guide/users-permissions/users/README.md
  docs/user-guide/projects/README.md
Labels: documentation

#18886 [#63571] Work package meetings tab has discrepency when work packages are added to a template
  modules/meeting/app/controllers/work_package_meetings_tab_controller.rb
Labels: bugfix

#18888 [63831] Fix error 500 when bulk deleting related work packages
  app/services/work_packages/delete_service.rb
  spec/controllers/work_packages/bulk_controller_spec.rb
  spec/services/work_packages/delete_service_spec.rb
Labels: bugfix, pullpreview

#18894 [64006] Rename `admin_settings_primer_form_with` to `settings_primer_form_with`
  app/components/custom_fields/details_component.html.erb
  app/components/op_primer/form_helpers.rb
  app/components/projects/life_cycle_step_definitions/form_component.html.erb
  app/components/projects/settings/general/show_component.html.erb
  app/components/work_packages/types/settings_component.html.erb
  app/components/work_packages/types/subject_configuration_component.html.erb
  app/views/admin/settings/authentication_settings/_login.html.erb
  app/views/admin/settings/authentication_settings/_passwords.html.erb
  app/views/admin/settings/authentication_settings/_registration.html.erb
  app/views/admin/settings/progress_tracking/show.html.erb
  app/views/admin/settings/work_package_priorities/edit.html.erb
  app/views/admin/settings/work_package_priorities/new.html.erb
  app/views/statuses/edit.html.erb
  lookbook/docs/patterns/17-settings-pages.md.erb
  modules/costs/app/views/admin/costs_settings/show.html.erb
  modules/costs/app/views/admin/settings/time_entry_activities/edit.html.erb
  modules/documents/app/views/admin/settings/document_categories/edit.html.erb
Labels: maintenance

#18876 [#63799] 16.0 PDF export changes https://community.openproject.org/w…
  docs/user-guide/time-and-costs/reporting/README.md
  docs/user-guide/time-and-costs/reporting/openproject_userguide_timesheet_pdf_export.png
  docs/user-guide/time-and-costs/reporting/openproject_userguide_timesheet_pdf_export_multiple_users.png
  docs/user-guide/work-packages/exporting/README.md
  docs/user-guide/work-packages/exporting/openproject-user-guide-wp-export-settings-save-checkbox.png
Labels: documentation

#18901 fix upsell page
  app/controllers/custom_styles_controller.rb
  modules/storages/app/controllers/storages/admin/storages_controller.rb
  modules/storages/spec/controllers/storages/admin/storages_controller_spec.rb
  modules/team_planner/app/controllers/team_planner/team_planner_controller.rb
  modules/team_planner/spec/controllers/team_planner/team_planner_controller_spec.rb
  spec/controllers/custom_styles_controller_spec.rb
  spec/controllers/shared_upsell_examples.rb
Labels: bugfix, needs review

#18885 [60580] Fix error 500 when bulk editing work packages
  frontend/src/app/shared/components/editor/components/ckeditor-augmented-textarea/ckeditor-augmented-textarea.component.ts
Labels: bugfix, needs review

#18852 have project phase changes show up on wp activity
  app/models/journal.rb
  app/models/work_package/journalized.rb
  config/locales/en.yml
  lib/open_project/journal_formatter/project_phase_definition.rb
  lib_static/plugins/acts_as_journalized/lib/journal_formatter/named_association.rb
  spec/features/work_packages/project_phases/linking_spec.rb
  spec/lib/open_project/journal_formatter/project_phase_definition_spec.rb
Labels: needs review

#18915 [64021] Medium Enterprise Banners look weird in Dark mode
  app/components/enterprise_edition/banner_component.html.erb
  app/components/enterprise_edition/banner_component.rb
  app/components/enterprise_edition/banner_component.sass
  app/views/homescreen/blocks/_upsell.html.erb
  frontend/src/global_styles/content/_enterprise.sass
  frontend/src/global_styles/openproject/_mixins.sass
Labels: bugfix, needs review

#18914 Allow hiding of antivirus settings
  app/components/admin/attachments_settings_header_component.html.erb
  app/controllers/admin/attachments/quarantined_attachments_controller.rb
  app/controllers/admin/settings/virus_scanning_settings_controller.rb
  app/models/setting/virus_scanning.rb
  config/constants/settings/definition.rb
Labels: bugfix, needs review

#18893 [63659] Share work package and share project list upsell banners do not display the correct pricing level
  app/components/shares/project_queries/upsell_component.html.erb
  app/components/shares/work_packages/modal_upsell_component.html.erb
  config/locales/en.yml
  spec/support/components/sharing/share_modal.rb
Labels: bugfix, needs review

#18924 Move success translation to separate key
  .github/workflows/crowdin.yml
  modules/storages/app/common/storages/peripherals/connection_validators/validation_group_result.rb
  modules/storages/app/common/storages/peripherals/connection_validators/validator_result.rb
  modules/storages/app/components/storages/admin/side_panel/validation_result_component.rb
  modules/storages/config/locales/en.yml
  script/i18n/fix_crowdin_storages_health_checks_failures_zero_key
Labels: needs review

#18925 [63729] Medium Enterprise Banner text can overflow into invisibility
  app/assets/images/enterprise/nextcloud-sso-authentication.png
  modules/storages/app/components/storages/admin/forms/general_info_form_component.html.erb
Labels: bugfix, needs review

#18864 [#63793] Automatically generated work package subjects https://commu…
  config/static_links.yml
  docs/system-admin-guide/manage-work-packages/README.md
  docs/system-admin-guide/manage-work-packages/work-package-types/README.md
  docs/system-admin-guide/manage-work-packages/work-package-types/automatic-subjects/README.md
  docs/system-admin-guide/manage-work-packages/work-package-types/automatic-subjects/openproject-automatic-subjects.gif
  docs/system-admin-guide/manage-work-packages/work-package-types/automatic-subjects/openproject_system_guide_work_package_automatic_subject_configuration_settings.png
  docs/system-admin-guide/manage-work-packages/work-package-types/openproject_system_guide_work_package_types_pdf_tab.png
Labels: documentation

#18905 [#63794] Time tracking module https://community.openproject.org/work…
  docs/system-admin-guide/time-and-costs/README.md
  docs/system-admin-guide/time-and-costs/openproject_system_admin_guide_time_time_defaults.png
  docs/user-guide/README.md
  docs/user-guide/my-time-tracking/README.md
  docs/user-guide/my-time-tracking/openproject-my-time-tracking-page1.gif
  docs/user-guide/my-time-tracking/openproject_user_guide_my_time_tracking_module_calendar_tab_total_sums.png
  docs/user-guide/my-time-tracking/openproject_user_guide_my_time_tracking_module_filters_explained.png
  docs/user-guide/my-time-tracking/openproject_user_guide_my_time_tracking_module_list_view_edit_icon.png
  docs/user-guide/my-time-tracking/openproject_user_guide_my_time_tracking_module_list_view_overview.png
  docs/user-guide/my-time-tracking/openproject_user_guide_my_time_tracking_module_logging_modal.png
  docs/user-guide/my-time-tracking/openproject_user_guide_my_time_tracking_module_overview.png
Labels: documentation

#18820 [63739] do not format work and remaining work for xls and csv exports
  app/models/work_package/exports/additional_columns.rb
  app/models/work_package/exports/csv.rb
  app/models/work_package/exports/formatters/compound_done_ratio.rb
  app/models/work_package/exports/formatters/compound_hours.rb
  app/models/work_package/exports/formatters/done_ratio.rb
  config/initializers/export_formats.rb
  modules/xls_export/app/models/xls_export/work_package/exporter/xls.rb
  modules/xls_export/spec/models/xls_export/work_package/exporter/xls_integration_spec.rb
  spec/models/work_package/exporter/csv_integration_spec.rb
  spec/models/work_package/exports/formatters/compound_done_ratio_spec.rb
Labels: pullpreview

#18927 [64068] Tooltip in Enterprise banners is floating out of box
  frontend/src/app/features/enterprise/free-trial-button/free-trial-button.component.html
Labels: bugfix, needs review

#18928 [63379] Show self-registration warning on click
  app/views/admin/settings/authentication_settings/_registration.html.erb
  frontend/src/stimulus/controllers/dynamic/admin/registration.controller.ts
  spec/features/admin/settings/authentication_settings_spec.rb
  spec/support/pages/admin/authentication/registration.rb
Labels: needs review

#18828 [#62295] Update Internal comments "Learn more" link to point to correct documentation
  app/components/work_packages/activities_tab/journals/new_component.rb
  app/forms/projects/settings/work_packages/activities/form.rb
  config/static_links.yml
  docs/system-admin-guide/users-permissions/roles-permissions/openproject_user_guide_file_storages_permissions.png
  docs/user-guide/activity/README.md
  docs/user-guide/activity/openproject_user_guide_internal_comment_checkbox.png
  docs/user-guide/activity/openproject_user_guide_internal_comment_edit_quote_copy.png
  docs/user-guide/activity/openproject_user_guide_internal_comment_example.png
  docs/user-guide/projects/project-settings/work-packages/README.md
  docs/user-guide/projects/project-settings/work-packages/openproject_user_guide_project_settings_work_packages_categories.png
  docs/user-guide/projects/project-settings/work-packages/openproject_user_guide_project_settings_work_packages_categories_edit_delete.png
  docs/user-guide/projects/project-settings/work-packages/openproject_user_guide_project_settings_work_packages_custom_fields.png
  docs/user-guide/projects/project-settings/work-packages/openproject_user_guide_project_settings_work_packages_internal_comments.png
  docs/user-guide/projects/project-settings/work-packages/openproject_user_guide_project_settings_work_packages_types.png
  docs/user-guide/work-packages/edit-work-package/README.md
Labels: documentation

#18889 [#63767] 16.0 Meetings changes https://community.openproject.org/wor…
  docs/user-guide/meetings/README.md
  docs/user-guide/meetings/classic-meetings/README.md
  docs/user-guide/meetings/classic-meetings/copy-meeting.png
  docs/user-guide/meetings/classic-meetings/delete-meeting.png
  docs/user-guide/meetings/classic-meetings/download-a-meeting.png
  docs/user-guide/meetings/classic-meetings/edit-meeting-agenda.png
  docs/user-guide/meetings/classic-meetings/edit-meeting.png
  docs/user-guide/meetings/classic-meetings/edit-minutes.png
  docs/user-guide/meetings/classic-meetings/meetings.png
  docs/user-guide/meetings/classic-meetings/openproject_user_guide_create_classic_meeting_button.png
  docs/user-guide/meetings/classic-meetings/openproject_user_guide_create_classic_meeting_copy_form.png
  docs/user-guide/meetings/classic-meetings/openproject_user_guide_create_classic_meeting_edit_participants.png
  docs/user-guide/meetings/classic-meetings/openproject_user_guide_create_classic_meeting_form.png
  docs/user-guide/meetings/classic-meetings/send-email-to-participants.png
  docs/user-guide/meetings/meetings-faq/README.md
  docs/user-guide/meetings/one-time-meetings/README.md
  docs/user-guide/meetings/one-time-meetings/openproject_userguide_meetings_agenda_backlog.png
  docs/user-guide/meetings/one-time-meetings/openproject_userguide_meetings_agenda_backlog_title.png
  docs/user-guide/meetings/one-time-meetings/openproject_userguide_meetings_clear_agenda_backlog.png
  docs/user-guide/meetings/one-time-meetings/openproject_userguide_meetings_create_meeting_button.png
  docs/user-guide/meetings/one-time-meetings/openproject_userguide_meetings_move_agenda_backlog_items.png
  docs/user-guide/meetings/recurring-meetings/README.md
  docs/user-guide/meetings/recurring-meetings/openproject_userguide_meetings_clear_series_backlog.png
  docs/user-guide/meetings/recurring-meetings/openproject_userguide_meetings_move_series_backlog_items.png
  docs/user-guide/meetings/recurring-meetings/openproject_userguide_meetings_series_backlog.png
  docs/user-guide/meetings/recurring-meetings/openproject_userguide_meetings_series_backlog_title.png
Labels: documentation

#18860 [#63800] Project settings UI changes https://community.openproject.o…
  docs/user-guide/projects/README.md
  docs/user-guide/projects/openproject_user_guide_projects_project_settings_info.png
  docs/user-guide/projects/openproject_user_guide_projects_subproject_button.png
  docs/user-guide/projects/openproject_user_guide_projects_subproject_of.png
  docs/user-guide/projects/project-information-description-status.png
  docs/user-guide/projects/project-settings-subproject.png
  docs/user-guide/projects/project-settings/project-information/README.md
  docs/user-guide/projects/project-settings/project-information/openproject_user_guide_project_settings_information.png
  docs/user-guide/projects/project-settings/project-information/openproject_user_guide_project_settings_information_more_icon_menu.png
  docs/user-guide/projects/project-settings/project-information/openproject_user_guide_project_settings_information_subproject_and_identifier.png
Labels: documentation

#18861 [#63795] Add parent item to relations https://community.openproject.…
  docs/user-guide/work-packages/work-package-relations-hierarchies/README.md
  docs/user-guide/work-packages/work-package-relations-hierarchies/openproject_user_guide_relations_change_parent.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/openproject_user_guide_wp_add_relations_button.png
Labels: documentation

#18934 [63475] Preserve unset dates when moving work packages in calendar
  frontend/src/app/features/calendar/op-work-packages-calendar.service.ts
  modules/calendar/spec/features/calendar_user_interaction_spec.rb
  modules/calendar/spec/support/pages/calendar.rb
  modules/team_planner/spec/features/team_planner_add_existing_work_packages_spec.rb
Labels: bugfix, pullpreview, needs review

#18941 Parameterize `attachments_storage_path` based on `TEST_ENV_NUMBER`
  spec/rails_helper.rb
Labels: needs review

#18945 update 16.0 release notes
  docs/release-notes/16-0-0/README.md
  docs/release-notes/16-0-0/openproject-16-0-automatic-subjects-settings.png
  docs/release-notes/16-0-0/openproject-16-0-my-time-tracking-calendar-view.png
Labels: documentation

#18907 [#63686] update health status report documentation
  docs/release-notes/14/14-4-0/README.md
  docs/system-admin-guide/files/external-file-storages/health-status/README.md
  docs/system-admin-guide/files/external-file-storages/health-status/openproject_file_storages_nextcloud_open_full_health_report_button.png
  docs/system-admin-guide/files/external-file-storages/health-status/openproject_file_storages_nextcloud_open_full_health_report_download_button.png
  docs/system-admin-guide/files/external-file-storages/health-status/openproject_file_storages_nextcloud_run_checks_link.png
  docs/system-admin-guide/files/external-file-storages/health-status/openproject_file_storages_recheck_connection.png
  docs/system-admin-guide/files/external-file-storages/health-status/openproject_file_storages_recheck_connection_nextcloud.png
  modules/storages/app/common/storages/peripherals/connection_validators/nextcloud/authentication_validator.rb
  modules/storages/app/common/storages/peripherals/connection_validators/one_drive/ampf_configuration_validator.rb
  modules/storages/config/locales/en.yml
  modules/storages/spec/common/storages/peripherals/connection_validators/nextcloud/authentication_validator_spec.rb
  modules/storages/spec/common/storages/peripherals/connection_validators/one_drive/ampf_configuration_validator_spec.rb
Labels: documentation

#18949 update time tracking docs
  docs/getting-started/my-page/README.md
Labels: documentation

#18948 16.0 docs changes
  docs/system-admin-guide/integrations/nextcloud/README.md
  docs/system-admin-guide/integrations/nextcloud/oidc-sso/README.md
  docs/system-admin-guide/manage-work-packages/work-package-types/automatic-subjects/README.md
Labels: documentation

#18865 [#63810] 16.0 changes for Enterprise guide https://community.openpro…
  docs/enterprise-guide/README.md
Labels: documentation

#18959 Documentation fixes
  docs/enterprise-guide/enterprise-cloud-guide/sign-in/README.md
  docs/getting-started/README.md
  docs/getting-started/boards-introduction/README.md
  docs/getting-started/gantt-chart-introduction/README.md
  docs/getting-started/invite-members/README.md
  docs/getting-started/my-page/README.md
  docs/getting-started/projects/README.md
  docs/getting-started/sign-in-registration/README.md
  docs/getting-started/work-packages-introduction/README.md
  docs/installation-and-operations/installation/packaged/README.md
  docs/installation-and-operations/misc/migration-to-postgresql17/README.md
  docs/release-notes/16-0-0/README.md
  docs/system-admin-guide/custom-fields/README.md
  docs/system-admin-guide/integrations/excel-synchronization/README.md
  docs/system-admin-guide/integrations/nextcloud/README.md
  docs/system-admin-guide/integrations/nextcloud/oidc-sso/README.md
  docs/system-admin-guide/manage-work-packages/work-package-types/README.md
  docs/user-guide/agile-boards/README.md
  docs/user-guide/backlogs-scrum/README.md
  docs/user-guide/gantt-chart/README.md
  docs/user-guide/gantt-chart/scheduling/README.md
  docs/user-guide/meetings/one-time-meetings/README.md
  docs/user-guide/meetings/recurring-meetings/README.md
  docs/user-guide/notifications/README.md
  docs/user-guide/projects/project-templates/README.md
  docs/user-guide/time-and-costs/README.md
  docs/user-guide/work-packages/README.md
Labels: documentation

#18873 Update Release Notes + Glossary 16.0
  docs/glossary/README.md
  docs/release-notes/16-0-0/README.md
  docs/release-notes/16-0-0/openproject-16-0-automatically-generated-work-package-subjects-candidate-interview-explained.png
  docs/release-notes/16-0-0/openproject-16-0-my-time-tracking-work-week-final.png
Labels: documentation, needs review

#18962 remove a redundant screenshot
  docs/release-notes/16-0-0/README.md
Labels: documentation

#18956 Document minimum required keycloak version
  docs/installation-and-operations/system-requirements/README.md
  docs/system-admin-guide/integrations/nextcloud/README.md
Labels: documentation

#18965 Bump primer to 0.66.2
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: maintenance

#18974 fixing docs typos
  docs/user-guide/meetings/one-time-meetings/README.md
Labels: documentation

#18976 [64134] ActionView::Template::Error (NoMethodError) in DocumentsController#index
  modules/documents/app/views/documents/index.html.erb
  modules/documents/spec/features/document_categories_spec.rb
Labels: bugfix, needs review

#18980 [#64144] Watcher email notification can expose an internal comment if…
  app/helpers/work_packages_helper.rb
  spec/helpers/work_packages_helper_spec.rb
Labels: bugfix

#17920 [62708] Implementing ARIA live regions to communicate contextual changes
  app/components/concerns/op_turbo/streamable.rb
  app/components/work_packages/date_picker/date_form_component.rb
  app/components/work_packages/date_picker/dialog_content_component.html.erb
  app/components/work_packages/date_picker/dialog_content_component.rb
  app/controllers/concerns/op_turbo/component_stream.rb
  app/controllers/work_packages/date_picker_controller.rb
  app/views/layouts/base.html.erb
  config/locales/en.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/stimulus/controllers/dynamic/work-packages/date-picker/preview.controller.ts
  frontend/src/turbo/live-region-stream-action.ts
  frontend/src/turbo/setup.ts
  lookbook/docs/patterns/accessibility/18-aria-live.md.erb
  spec/components/work_packages/date_picker/dialog_content_component_spec.rb
  spec/controllers/work_packages/date_picker_controller_spec.rb
Labels: feature

#18982 [#64153] Journals index atom export can expose internal comments
  app/models/query.rb
  spec/models/query_spec.rb
Labels: bugfix

#18958 [64019] 'Make project public' modal has to be scrolled to be read in full
  app/components/projects/settings/toggle_public_dialog_component.html.erb
Labels: bugfix, needs review

#18984 [64123] Project attribute page shows the same button twice on mobile
  app/components/settings/project_custom_fields/header_component.html.erb
  spec/features/admin/project_custom_fields/list_spec.rb
Labels: bugfix, needs review

#18996 exclude ongoing timers from my time tracking page
  modules/costs/app/controllers/my/time_tracking_controller.rb
  modules/costs/spec/controllers/my/time_tracking_controller_spec.rb
Labels: bugfix, needs review

#18995 [#62130] Add internal:boolean property to activity comments (read) API
  docs/api/apiv3/components/examples/activity_response.yml
  docs/api/apiv3/components/schemas/activity_model.yml
  lib/api/v3/activities/activity_representer.rb
  spec/lib/api/v3/activities/activity_representer_rendering_spec.rb
Labels: feature

#18988 code maintenance/64103 Structure emoji reactions query methods with internal comments scope
  app/components/work_packages/activities_tab/journals/index_component.rb
  app/controllers/work_packages/activities_tab_controller.rb
  app/models/concerns/reactable.rb
  lib/api/v3/emoji_reactions/emoji_reactions_by_work_package_comments_api.rb
  spec/models/concerns/reactable_spec.rb
Labels: maintenance

#19002 Bump primer to 0.67.0
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: maintenance

#18940 Update Ruby to version 3.4.4 and Bundler to 2.6.9
  .ruby-version
  Gemfile.lock
  docker/dev/backend/Dockerfile
  docker/prod/Dockerfile
  docs/development/development-environment/linux/README.md
  docs/development/development-environment/macos/README.md
  docs/installation-and-operations/installation/manual/README.md
Labels: needs review

#19003 [#64219] Update package installation docs to no longer indicate it as…
  docs/installation-and-operations/installation/packaged/README.md
Labels: documentation

#19005 expand faqs about Nextcloud
  docs/system-admin-guide/integrations/nextcloud/README.md
  docs/user-guide/file-management/file-management-faq/README.md
Labels: documentation

#19030 Merge release/16.0 into dev
  app/contracts/work_packages/base_contract.rb
  config/locales/crowdin/ja.yml
  config/locales/crowdin/js-ja.yml
  docs/installation-and-operations/misc/migration-to-postgresql17/README.md
  docs/release-notes/16-0-0/README.md
  docs/system-admin-guide/integrations/nextcloud/README.md
  docs/user-guide/file-management/file-management-faq/README.md
  spec/contracts/work_packages/base_contract_spec.rb
Labels: create-merge-release-into-dev-pr

#18998 feature/64166 Add work package internal comments (write) API
  docs/api/apiv3/components/schemas/activity_comment_write_model.yml
  docs/api/apiv3/paths/work_package_activities.yml
  lib/api/v3/activities/activities_by_work_package_api.rb
  spec/requests/api/v3/activities_by_work_package_resource_spec.rb
Labels: feature

#19035 improve meetings documentation
  docs/user-guide/meetings/one-time-meetings/README.md
Labels: documentation

#19008 implementation/64104 Extend API V3 to cover Emoji reactions on work package comments (toggle) and extend documentation
  app/controllers/work_packages/activities_tab_controller.rb
  app/services/emoji_reactions/toggle_emoji_reaction_service.rb
  docs/api/apiv3/paths/activity_emoji_reactions.yml
  lib/api/v3/emoji_reactions/emoji_reactions_by_activity_comment_api.rb
  spec/requests/api/v3/emoji_reactions/emoji_reactions_by_activity_comment_api_spec.rb
  spec/services/emoji_reactions/toggle_emoji_reaction_service_spec.rb
Labels: feature, needs review

#19020 code maintenance/64167 Restructure emoji reactions queries to be independent of the Reactable assoc mixin
  app/components/work_packages/activities_tab/journals/index_component.rb
  app/controllers/work_packages/activities_tab_controller.rb
  app/models/concerns/emoji_reactions/grouped_queries.rb
  app/models/concerns/reactable.rb
  lib/api/v3/activities/activity_representer.rb
  lib/api/v3/emoji_reactions/emoji_reactions_by_activity_comment_api.rb
  lib/api/v3/emoji_reactions/emoji_reactions_by_work_package_comments_api.rb
  spec/models/concerns/emoji_reactions/grouped_queries_spec.rb
  spec/models/concerns/reactable_spec.rb
  spec/requests/api/v3/emoji_reactions/emoji_reaction_representer_spec.rb
Labels: maintenance

#19026 Bump op-primer-view-component to 0.68.0
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
  modules/auth_saml/spec/features/administration/saml_crud_spec.rb
  modules/meeting/spec/features/recurring_meetings/recurring_meeting_global_create_spec.rb
  modules/meeting/spec/features/structured_meetings/structured_meeting_global_crud_spec.rb
  modules/my_page/spec/features/my/my_page_navigation_spec.rb
  modules/storages/spec/features/delete_project_storage_and_file_links_spec.rb
  modules/storages/spec/features/manage_project_storage_spec.rb
  modules/storages/spec/features/storages/project_settings/oauth_access_grant_spec.rb
  spec/controllers/news_controller_spec.rb
Labels: maintenance

#19019 [63921] Wrong tab header is selected within a hierachy CF item
  app/helpers/tabs_helper.rb
  spec/features/custom_fields/hierarchy_custom_field_spec.rb
  spec/support/pages/custom_fields/hierarchy_page.rb
Labels: bugfix, needs review

#19046 docs: use relative links to docs
  docs/README.md
  docs/contributions-guide/contribution-documentation/README.md
  docs/contributions-guide/contribution-documentation/documentation-style-guide/README.md
  docs/installation-and-operations/misc/migration-to-postgresql17/README.md
  docs/release-notes/10/10-3-0/README.md
  docs/release-notes/11/11-3-0/README.md
  docs/system-admin-guide/integrations/nextcloud/README.md
  docs/system-admin-guide/integrations/nextcloud/oidc-sso/README.md
  docs/system-admin-guide/time-and-costs/README.md
  docs/user-guide/file-management/file-management-faq/README.md
  docs/user-guide/work-packages/work-package-table-configuration/README.md
Labels: documentation

#19049 adjust alert boxes: crowding does not support alert boxes in lists
  docs/system-admin-guide/authentication/login-registration-settings/README.md
  docs/system-admin-guide/custom-fields/README.md
  docs/system-admin-guide/integrations/nextcloud/README.md
  docs/system-admin-guide/manage-work-packages/work-package-progress-tracking/README.md
  docs/system-admin-guide/manage-work-packages/work-package-status/README.md
  docs/system-admin-guide/manage-work-packages/work-package-types/automatic-subjects/README.md
  docs/system-admin-guide/system-settings/general-settings/README.md
  docs/user-guide/my-time-tracking/README.md
  docs/user-guide/projects/project-settings/versions/README.md
Labels: documentation

#18672 Feature/61610 date picker to edit phases and phase gates of a project lifecycle (2/2)
  app/components/_index.sass
  app/contracts/project_life_cycle_steps/update_contract.rb
  app/forms/_index.sass
  app/forms/projects/life_cycles/form.rb
  app/forms/projects/life_cycles/form.sass
  app/models/day.rb
  app/models/permitted_params.rb
  app/models/project/phase.rb
  app/services/base_services/set_attributes.rb
  app/services/project_life_cycle_steps/activation_service.rb
  app/services/project_life_cycle_steps/set_attributes_service.rb
  app/services/project_life_cycle_steps/update_service.rb
  config/locales/en.yml
  frontend/src/app/shared/components/datepicker/datepicker.ts
  frontend/src/app/shared/components/datepicker/wp-date-picker-modal/wp-date-picker-instance.component.ts
  frontend/src/global_styles/openproject.sass
  frontend/src/global_styles/primer/_overrides.sass
  frontend/src/stimulus/controllers/dynamic/overview/project-life-cycles-form.controller.ts
  frontend/src/stimulus/controllers/form-preview.controller.ts
  lookbook/previews/open_project/projects/phase_component_preview.rb
  modules/overviews/app/components/_index.sass
  modules/overviews/app/components/overviews/project_phases/edit_component.html.erb
  modules/overviews/app/components/overviews/project_phases/edit_dialog_component.html.erb
  modules/overviews/app/components/overviews/project_phases/edit_dialog_component.rb
  modules/overviews/app/components/overviews/project_phases/item_component.html.erb
  modules/overviews/app/components/overviews/project_phases/item_component.rb
  modules/overviews/app/components/overviews/project_phases/item_component.sass
  spec/contracts/project_life_cycle_steps/update_contract_spec.rb
  spec/factories/project_phase_factory.rb
  spec/factories/work_package_factory.rb
  spec/features/projects/life_cycle/overview_page/dialog/update_spec.rb
  spec/features/projects/life_cycle/overview_page/shared_context.rb
  spec/models/day_spec.rb
  spec/models/project/phase_spec.rb
  spec/services/project_life_cycle_steps/activation_service_spec.rb
  spec/services/project_life_cycle_steps/set_attributes_service_spec.rb
  spec/services/project_life_cycle_steps/update_service_spec.rb
  spec/support/components/projects/project_life_cycles/edit_dialog.rb
Labels: pullpreview

#19057 bug/64324 Enhance internal comments feature plan access
  app/components/work_packages/activities_tab/journals/new_component.rb
  app/contracts/work_packages/create_note_contract.rb
  spec/contracts/work_packages/create_note_contract_spec.rb
  spec/features/activities/work_package/internal_comments_spec.rb
Labels: bugfix
