Repository opf/openproject, pull requests merged in 2025-04, with the labels that each got.

#18425 [60667] Automatic scheduling mode: make it possible to enter Finish date by direct input or by clicking on the mini calendar
  app/components/work_packages/date_picker/date_form_component.rb
  app/components/work_packages/date_picker/dialog_content_component.html.erb
  app/components/work_packages/date_picker/form_component.html.erb
  app/components/work_packages/date_picker/form_component.rb
  app/controllers/work_packages/date_picker_controller.rb
  app/views/work_packages/date_picker/show.html.erb
  frontend/src/app/shared/components/datepicker/wp-date-picker-modal/wp-date-picker-instance.component.ts
  frontend/src/stimulus/controllers/dynamic/work-packages/date-picker/preview.controller.ts
  spec/components/work_packages/date_picker/dialog_content_component_spec.rb
  spec/features/work_packages/datepicker/datepicker_editable_finish_date_logic_spec.rb
  spec/features/work_packages/datepicker/datepicker_follows_relation_spec.rb
  spec/features/work_packages/datepicker/datepicker_logic_spec.rb
  spec/features/work_packages/scheduling/automatic_scheduling_logic_spec.rb
  spec/support/components/datepicker/datepicker.rb
Labels: feature, pullpreview, needs review

#18499 [61051] Remove close button on mobile for datepicker dialog
  frontend/src/app/shared/components/datepicker/wp-date-picker-modal/wp-date-picker.modal.ts
Labels: styling

#18489 [#49288] Harmonize writing of "My page" vs "My Page" vs "MyPage" http…
  docs/api/apiv3/tags/grids.yml
  docs/development/concepts/inline-editing/README.md
  docs/getting-started/README.md
  docs/getting-started/my-activity/README.md
  docs/getting-started/my-page/README.md
  docs/glossary/README.md
  docs/release-notes/10/10-0-0/README.md
  docs/release-notes/10/10-5-0/README.md
  docs/release-notes/11/11-2-0/README.md
  docs/release-notes/11/11-2-1/README.md
  docs/release-notes/11/11-4-1/README.md
  docs/release-notes/12/12-0-3/README.md
  docs/release-notes/12/12-1-0/README.md
  docs/release-notes/12/12-5-5/README.md
  docs/release-notes/13/13-0-0/README.md
  docs/release-notes/14/14-1-0/README.md
  docs/release-notes/14/14-5-0/README.md
  docs/release-notes/5/5-0-17/README.md
  docs/release-notes/6/6-1-4/README.md
  docs/release-notes/9/9-0-0/README.md
  docs/release-notes/9/9-0-1/README.md
  docs/user-guide/keyboard-shortcuts-access-keys/README.md
  docs/user-guide/meetings/meetings-faq/README.md
  docs/user-guide/time-and-costs/time-and-costs-faq/README.md
  docs/user-guide/time-and-costs/time-tracking/README.md
Labels: documentation

#18507 [62554] Children number icon and children label are not the right colour in dark mode
  frontend/src/app/features/work-packages/components/wp-buttons/wp-filter-button/wp-filter-button.html
  frontend/src/app/features/work-packages/components/wp-buttons/wp-share-button/wp-share-button.html
  frontend/src/app/features/work-packages/components/wp-fast-table/builders/relation-cell-builder.ts
  frontend/src/app/shared/components/fields/display/field-types/resources-display-field.module.ts
  frontend/src/app/shared/components/principal/principal-renderer.service.ts
  frontend/src/app/shared/components/project-include/project-include.component.html
  frontend/src/global_styles/content/_badges.sass
  frontend/src/global_styles/content/work_packages/_table_relations.sass
  frontend/src/global_styles/layout/_toolbar.sass
  lookbook/previews/open_project/deprecated/badges_preview/border_only.html.erb
  lookbook/previews/open_project/deprecated/badges_preview/secondary.html.erb
  modules/webhooks/app/components/webhooks/outgoing/webhooks/row_component.rb
Labels: bugfix, styling

#18504 [62581] Excess padding in the Activity tab comment box
  app/components/work_packages/activities_tab/index_component.html.erb
  app/components/work_packages/activities_tab/index_component.sass
  app/components/work_packages/activities_tab/journals/new_component.html.erb
Labels: bugfix, styling, pullpreview, needs review

#18506 [62596] User can't delete a date with mobile date picker
  app/components/work_packages/date_picker/date_form_component.rb
  frontend/src/stimulus/controllers/dynamic/work-packages/date-picker/preview.controller.ts
Labels: bugfix, needs review

#18514 Remove some deprecated lookbook previews
  lookbook/docs/patterns/deprecated/modals.md.erb
  lookbook/previews/open_project/deprecated/contextual_info_text_preview.rb
  lookbook/previews/open_project/deprecated/contextual_info_text_preview/default.html.erb
  lookbook/previews/open_project/deprecated/links_preview.rb
  lookbook/previews/open_project/deprecated/links_preview/default.html.erb
  lookbook/previews/open_project/deprecated/news_preview.rb
  lookbook/previews/open_project/deprecated/news_preview/default.html.erb
  lookbook/previews/open_project/deprecated/news_preview/detailed_view.html.erb
  lookbook/previews/open_project/deprecated/progress_bar_preview.rb
  lookbook/previews/open_project/deprecated/progress_bar_preview/default.html.erb
  lookbook/previews/open_project/deprecated/toolbar_component_preview.rb
  lookbook/previews/open_project/deprecated/toolbar_component_preview/default.html.erb
  lookbook/previews/open_project/deprecated/toolbar_component_preview/with_form_elements.html.erb
  lookbook/previews/open_project/deprecated/toolbar_component_preview/with_labelled_form_elements.html.erb
  lookbook/previews/open_project/deprecated/widget_component_preview.rb
  lookbook/previews/open_project/deprecated/widget_component_preview/default.html.erb
Labels: maintenance

#18513 Update remote identity indices
  db/migrate/20250402083709_change_remote_identities_foreign_key_indices.rb
Labels: needs review

#18519 Fixes for Custom Actions administration
  app/models/custom_actions/actions/assigned_to.rb
  app/models/custom_actions/actions/project.rb
  app/models/custom_actions/actions/responsible.rb
  app/models/custom_actions/actions/strategies/me_associated.rb
  app/models/custom_actions/actions/strategies/user_custom_field.rb
  app/views/custom_actions/_form.html.erb
  app/views/custom_actions/edit.html.erb
  app/views/custom_actions/new.html.erb
  frontend/src/app/app.module.ts
  frontend/src/app/shared/components/autocompleter/user-autocompleter/user-autocompleter.component.ts
  frontend/src/app/shared/components/hide-section/add-section-dropdown/add-section-dropdown.component.html
  frontend/src/app/shared/components/hide-section/add-section-dropdown/add-section-dropdown.component.ts
  frontend/src/app/shared/components/hide-section/hide-section-link/hide-section-link.component.html
  frontend/src/app/shared/components/hide-section/hide-section-link/hide-section-link.component.ts
  frontend/src/app/shared/components/hide-section/hide-section.service.ts
  frontend/src/app/shared/shared.module.ts
  frontend/src/stimulus/controllers/dynamic/hide-sections.controller.ts
  spec/features/work_packages/custom_actions/custom_actions_spec.rb
  spec/models/custom_actions/actions/assigned_to_spec.rb
  spec/models/custom_actions/actions/custom_field_spec.rb
  spec/models/custom_actions/actions/project_spec.rb
  spec/models/custom_actions/actions/responsible_spec.rb
  spec/support/pages/admin/custom_actions/form.rb
Labels: bugfix

#18533 Bump primer 0.59.1
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: bugfix, needs review

#18526 Remove bulk show actions
  frontend/src/app/shared/components/op-context-menu/wp-context-menu/wp-view-context-menu.directive.ts
  modules/bim/spec/features/card_view/bulk_actions_spec.rb
  spec/features/work_packages/bulk/copy_work_package_spec.rb
  spec/features/work_packages/bulk/update_work_package_spec.rb
  spec/features/work_packages/table/context_menu/context_menu_spec.rb
  spec/support/components/work_packages/context_menu.rb
Labels: bugfix, needs review

#18529 [61790] Not enough spacing on Files Categories page (and other pages)
  frontend/src/app/core/routing/openproject.routes.ts
  spec/features/work_packages/navigation_spec.rb
Labels: bugfix, needs review

#18532 [62743] The add relations drop down list doesn't indicate that there are other options hidden behind a scroll
  app/components/work_package_relations_tab/index_component.sass
Labels: bugfix, needs review

#18542 Replace deprecated Primer::ButtonComponent with Primer::Beta::Button
  app/components/add_button_component.html.erb
  app/components/admin/custom_fields/custom_field_projects/new_custom_field_projects_form_modal_component.html.erb
  app/components/my/access_token/new_access_token_form_component.html.erb
  app/components/projects/configure_view_modal_component.html.erb
  app/components/settings/project_custom_field_sections/dialog_body_form_component.html.erb
  app/components/work_package_relations_tab/add_work_package_child_dialog_component.html.erb
  app/components/work_package_relations_tab/work_package_relation_dialog_component.html.erb
  app/components/work_packages/date_picker/date_form_component.html.erb
  app/components/work_packages/date_picker/dialog_content_component.html.erb
  app/components/work_packages/dialogs/create_dialog_component.html.erb
  app/components/work_packages/exports/generate/modal_dialog_component.html.erb
  app/components/work_packages/exports/modal_dialog_component.html.erb
  modules/costs/app/components/time_entries/entry_dialog_component.html.erb
  modules/meeting/app/components/meetings/index/dialog_component.html.erb
  modules/meeting/app/components/meetings/side_panel/details_form_component.html.erb
  modules/meeting/app/components/meetings/side_panel/participants_dialog.html.erb
  modules/meeting/app/components/work_package_meetings_tab/add_work_package_to_meeting_dialog_component.html.erb
  modules/overviews/app/components/project_custom_fields/sections/edit_dialog_component.html.erb
  modules/overviews/app/components/project_life_cycles/sections/edit_dialog_component.html.erb
  modules/storages/app/components/storages/admin/storages/projects_storage_form_modal_component.html.erb
  modules/storages/app/components/storages/open_project_storage_modal_component.html.erb
Labels: maintenance

#18544 Bump primer 0.59.2
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: bugfix, maintenance

#18565 Bump vite to 5.4.17
  frontend/package-lock.json
Labels: dependencies, javascript, needs review

#18548 [62641] toggling non working days keeps dates and updates duration
  app/services/work_packages/set_attributes_service.rb
  spec/features/work_packages/datepicker/datepicker_editable_finish_date_logic_spec.rb
  spec/features/work_packages/datepicker/datepicker_logic_spec.rb
  spec/services/work_packages/set_attributes_service_spec.rb
Labels: bugfix, needs review

#18558 Release Notes 15.5
  docs/release-notes/15-5-0/README.md
  docs/release-notes/15-5-0/openproject-15-5-children-work-package-table-highlighted.png
  docs/release-notes/15-5-0/openproject-15-5-children-work-package-table-unfolded.png
  docs/release-notes/15-5-0/openproject-15-5-classic-meetings-highlighted.png
  docs/release-notes/15-5-0/openproject-15-5-descendants-filter-highlighted.png
  docs/release-notes/15-5-0/openproject-15-5-percentage-complete-sum-highlighted.png
Labels: documentation

#18570 Merge release/15.5 into dev
  app/controllers/workflows_controller.rb
  docs/user-guide/work-packages/exporting/README.md
  docs/user-guide/work-packages/exporting/openproject-user-guide-single-pdf-export.png
  docs/user-guide/work-packages/exporting/openproject_user_guide_work_package_export_pdf_modal.png
  frontend/src/app/features/work-packages/components/wp-fast-table/builders/relations/relation-row-builder.ts
  frontend/src/global_styles/content/work_packages/_table_relations.sass
  spec/controllers/workflows_controller_spec.rb
  spec/features/workflows/edit_spec.rb
Labels: create-merge-release-into-dev-pr

#18527 [62650] The duration field is not visible on focus in mobile screens
  frontend/src/app/shared/components/modal/modal.component.ts
  frontend/src/app/spot/styles/sass/components/modal-overlay.sass
  frontend/src/stimulus/controllers/dynamic/work-packages/date-picker/preview.controller.ts
Labels: bugfix, needs review

#18578 [62848] Don't use native date fields for mobile safari
  app/components/work_packages/date_picker/date_form_component.rb
  frontend/src/stimulus/controllers/dynamic/work-packages/date-picker/preview.controller.ts
Labels: bugfix, pullpreview

#18590 [#62444] Webhook embedded resource custom fields are null
  modules/webhooks/app/workers/represented_webhook_job.rb
  modules/webhooks/spec/workers/work_package_webhook_job_spec.rb
Labels: needs review

#18598 [63014] The "Create meeting" drop down in the Meetings subheader doesn't not properly right-align with the button
  modules/meeting/app/components/meetings/index_sub_header_component.html.erb
Labels: bugfix

#18588 Fix footer for past recurring meetings
  modules/meeting/app/components/recurring_meetings/footer_component.rb
  modules/meeting/app/components/recurring_meetings/table_component.rb
  modules/meeting/app/controllers/recurring_meetings_controller.rb
  modules/meeting/app/views/recurring_meetings/_show_upcoming.html.erb
  modules/meeting/app/views/recurring_meetings/show.html.erb
  modules/meeting/config/locales/en.yml
Labels: bugfix, needs review

#18530 [#62386] Project attribute list entries not displayed when applied as filter in project list
  app/components/filter/filter_component.rb
  app/views/filters/_autocomplete.html.erb
  frontend/src/app/shared/components/autocompleter/op-autocompleter/op-autocompleter.component.ts
  frontend/src/app/shared/components/autocompleter/op-autocompleter/op-autocompleter.spec.ts
  modules/boards/spec/features/support/board_page.rb
  spec/features/projects/persisted_lists_spec.rb
  spec/features/types/form_configuration_query_spec.rb
  spec/features/work_packages/custom_actions/custom_actions_spec.rb
  spec/features/work_packages/details/milestones_spec.rb
  spec/support/components/admin/type_configuration_form.rb
  spec/support/components/common/filters.rb
  spec/support/components/work_packages/relations.rb
  spec/support/pages/projects/index.rb
Labels: needs review

#18593 [#62768] Automatic scheduling mode: make it possible to enter Finish …
  docs/user-guide/work-packages/set-change-dates/README.md
  docs/user-guide/work-packages/set-change-dates/openproject_user_guide_date_picker_banner_automatic_mode.png
  docs/user-guide/work-packages/set-change-dates/openproject_user_guide_date_picker_banner_automatic_mode_relations_banner.png
Labels: documentation

#18604 [#62761] 15.5 relations changes https://community.openproject.org/wo…
  docs/user-guide/work-packages/work-package-relations-hierarchies/README.md
  docs/user-guide/work-packages/work-package-relations-hierarchies/openproject_user_guide_wp_add_child.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/openproject_user_guide_wp_add_relations_button.png
  docs/user-guide/work-packages/work-package-relations-hierarchies/openproject_user_guide_wp_relations_tab_overview.png
Labels: documentation

#18560 [#62771] Classic meetings sunsetting https://community.openproject.o…
  docs/user-guide/meetings/README.md
  docs/user-guide/meetings/classic-meetings/README.md
  docs/user-guide/meetings/meetings-faq/README.md
  docs/user-guide/meetings/one-time-meetings/README.md
  docs/user-guide/meetings/one-time-meetings/openproject_userguide_meetings_add_agenda_item_button.png
  docs/user-guide/meetings/one-time-meetings/openproject_userguide_meetings_add_section.png
  docs/user-guide/meetings/one-time-meetings/openproject_userguide_meetings_add_section_items.png
  docs/user-guide/meetings/one-time-meetings/openproject_userguide_meetings_add_section_items_form.png
  docs/user-guide/meetings/one-time-meetings/openproject_userguide_meetings_agenda_item_more_menu.png
  docs/user-guide/meetings/one-time-meetings/openproject_userguide_meetings_agenda_outcome_button.png
  docs/user-guide/meetings/one-time-meetings/openproject_userguide_meetings_agenda_outcome_form.png
  docs/user-guide/meetings/one-time-meetings/openproject_userguide_meetings_agenda_outcome_more_menu.png
  docs/user-guide/meetings/one-time-meetings/openproject_userguide_meetings_agenda_too_long.png
  docs/user-guide/meetings/one-time-meetings/openproject_userguide_meetings_close_meeting.png
  docs/user-guide/meetings/one-time-meetings/openproject_userguide_meetings_cogwheel_icon.png
  docs/user-guide/meetings/one-time-meetings/openproject_userguide_meetings_copy_meeting.png
  docs/user-guide/meetings/one-time-meetings/openproject_userguide_meetings_create_meeting_button.png
  docs/user-guide/meetings/one-time-meetings/openproject_userguide_meetings_delete_meeting.png
  docs/user-guide/meetings/one-time-meetings/openproject_userguide_meetings_edit_meeting_form.png
  docs/user-guide/meetings/one-time-meetings/openproject_userguide_meetings_edit_meeting_title.png
  docs/user-guide/meetings/one-time-meetings/openproject_userguide_meetings_meeting_mark_in_progress.png
  docs/user-guide/meetings/one-time-meetings/openproject_userguide_meetings_meeting_status.png
  docs/user-guide/meetings/one-time-meetings/openproject_userguide_meetings_new_onetime_meeting_form.png
  docs/user-guide/meetings/one-time-meetings/openproject_userguide_meetings_reopen_meeting.png
  docs/user-guide/meetings/one-time-meetings/openproject_userguide_meetings_section_duration_sum.png
  docs/user-guide/meetings/one-time-meetings/openproject_userguide_meetings_section_more_menu.png
  docs/user-guide/meetings/one-time-meetings/openproject_userguide_meetings_select_meeting_history.png
  docs/user-guide/meetings/one-time-meetings/openproject_userguide_meetings_untitled_section.png
  docs/user-guide/meetings/recurring-meetings/README.md
  docs/user-guide/meetings/recurring-meetings/openproject_userguide_meetings_copy_recurring_meeting_as_onetime.png
  docs/user-guide/meetings/recurring-meetings/openproject_userguide_meetings_edit_meeting_occurence_link.png
  docs/user-guide/meetings/recurring-meetings/openproject_userguide_meetings_recurring_meeting_button.png
  docs/user-guide/meetings/recurring-meetings/openproject_userguide_meetings_recurring_meeting_edit_template_button.png
  docs/user-guide/meetings/recurring-meetings/openproject_userguide_meetings_recurring_meeting_move_agenda_item_to_next_meeting.png
Labels: documentation

#18623 Bump primerViewComponents to 0.61.0 and octicons to 19.24.2
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: maintenance

#18550 [#62772] Project settings: Harmonise "enabled in project" for Types a…
  docs/getting-started/work-packages-introduction/README.md
  docs/glossary/README.md
  docs/release-notes/14/14-4-0/README.md
  docs/release-notes/14/14-6-0/README.md
  docs/system-admin-guide/custom-fields/README.md
  docs/system-admin-guide/manage-work-packages/work-package-types/README.md
  docs/user-guide/projects/project-settings/README.md
  docs/user-guide/projects/project-settings/User-guide-open-project-settings.png
  docs/user-guide/projects/project-settings/activities-time-tracking/README.md
  docs/user-guide/projects/project-settings/activities-time-tracking/image-20200211134150920.png
  docs/user-guide/projects/project-settings/activities-time-tracking/openproject_user_guide_project_settings_time_tracking_activities.png
  docs/user-guide/projects/project-settings/backlogs-settings/README.md
  docs/user-guide/projects/project-settings/backlogs-settings/image-20200211134305495.png
  docs/user-guide/projects/project-settings/backlogs-settings/openproject_user_guide_project_settings_backlogs.png
  docs/user-guide/projects/project-settings/custom-fields/README.md
  docs/user-guide/projects/project-settings/custom-fields/openproject_user_guide_projects_project_settings_custom_fields.png
  docs/user-guide/projects/project-settings/files/README.md
  docs/user-guide/projects/project-settings/modules/Modules-overview.png
  docs/user-guide/projects/project-settings/modules/README.md
  docs/user-guide/projects/project-settings/modules/openproject_user_guide_project_settings_modules.png
  docs/user-guide/projects/project-settings/openproject_user_guide_project_settings_module.png
  docs/user-guide/projects/project-settings/project-attributes/README.md
  docs/user-guide/projects/project-settings/project-attributes/open_project_user_guide_project_settings_project_attributes_list.png
  docs/user-guide/projects/project-settings/project-information/README.md
  docs/user-guide/projects/project-settings/project-information/image-20201010152113743.png
  docs/user-guide/projects/project-settings/project-information/openproject_user_guide_project_settings_information.png
  docs/user-guide/projects/project-settings/project-information/openproject_user_guide_project_settings_information_more_icon_menu.png
  docs/user-guide/projects/project-settings/project-information/openproject_user_guide_project_settings_information_subproject_and_identifier.png
  docs/user-guide/projects/project-settings/repository/README.md
  docs/user-guide/projects/project-settings/repository/openproject_user_guide_project_settings_repository.png
  docs/user-guide/projects/project-settings/required-disk-storage/README.md
  docs/user-guide/projects/project-settings/required-disk-storage/openproject-user-guide-project-settings-required-disk-storage.png
  docs/user-guide/projects/project-settings/versions/README.md
  docs/user-guide/projects/project-settings/versions/User-guide-project-settings-versions.png
  docs/user-guide/projects/project-settings/versions/openproject_user_guide_project_settings_work_packages_versions.png
  docs/user-guide/projects/project-settings/versions/openproject_user_guide_project_settings_work_packages_versions_closed.png
  docs/user-guide/projects/project-settings/versions/openproject_user_guide_project_settings_work_packages_versions_edit_close_delete.png
  docs/user-guide/projects/project-settings/versions/openproject_user_guide_project_settings_work_packages_versions_new.png
  docs/user-guide/projects/project-settings/work-package-categories/README.md
  docs/user-guide/projects/project-settings/work-package-categories/User-guide-project-settings-create-category.png
  docs/user-guide/projects/project-settings/work-package-categories/User-guide-project-settings-edit-category.png
  docs/user-guide/projects/project-settings/work-package-categories/User-guide-project-settings-work-package-categories-1581425056359.png
  docs/user-guide/projects/project-settings/work-package-types/README.md
  docs/user-guide/projects/project-settings/work-package-types/image-20200211133405469.png
  docs/user-guide/projects/project-settings/work-packages/README.md
  docs/user-guide/projects/project-settings/work-packages/openproject_user_guide_project_settings_work_packages.png
  docs/user-guide/projects/project-settings/work-packages/openproject_user_guide_project_settings_work_packages_categories.png
  docs/user-guide/projects/project-settings/work-packages/openproject_user_guide_project_settings_work_packages_categories_edit_delete.png
  docs/user-guide/projects/project-settings/work-packages/openproject_user_guide_project_settings_work_packages_categories_new.png
  docs/user-guide/projects/project-settings/work-packages/openproject_user_guide_project_settings_work_packages_custom_fields.png
  docs/user-guide/projects/project-settings/work-packages/openproject_user_guide_project_settings_work_packages_types.png
  docs/user-guide/work-packages/duplicate-move-delete/README.md
  docs/user-guide/work-packages/work-packages-faq/README.md
Labels: documentation

#18599 [61807] Gantt chart and relations tab are not synchronized
  frontend/src/app/features/work-packages/components/wp-relations/wp-relations.component.ts
  frontend/src/app/features/work-packages/components/wp-table/timeline/cells/wp-timeline-cell-mouse-handler.ts
  spec/features/work_packages/details/relations/primerized_relations_syncing_spec.rb
Labels: bugfix

#18627 fix docs typo
  docs/user-guide/projects/project-settings/work-packages/README.md
  docs/user-guide/work-packages/work-package-relations-hierarchies/README.md
Labels: documentation

#18631 [62823] NoMethodError in WorkPackages::DatePickerController#show
  app/controllers/work_packages/date_picker_controller.rb
Labels: bugfix, needs review

#18594 [62891][63152] Recalculate start date correctly when toggling "Working days only"
  app/components/work_package_relations_tab/closest_relation.rb
  app/components/work_packages/date_picker/form_component.html.erb
  app/components/work_packages/date_picker/form_component.rb
  app/models/relation.rb
  app/models/work_package/scheduling_rules.rb
  app/services/work_packages/schedule_dependency/dependency.rb
  app/services/work_packages/set_attributes_service.rb
  app/services/work_packages/shared/all_days.rb
  app/services/work_packages/shared/working_days.rb
  frontend/src/app/core/datetime/timezone.service.ts
  frontend/src/app/shared/components/datepicker/wp-date-picker-modal/wp-date-picker-instance.component.ts
  frontend/src/stimulus/controllers/dynamic/work-packages/date-picker/preview.controller.ts
  spec/components/work_package_relations_tab/closest_relation_spec.rb
  spec/features/work_packages/datepicker/datepicker_follows_relation_spec.rb
  spec/features/work_packages/datepicker/datepicker_logic_spec.rb
  spec/models/relation_spec.rb
  spec/models/work_package/work_package_relations_spec.rb
  spec/services/work_packages/set_attributes_service_spec.rb
  spec/services/work_packages/shared/all_days_spec.rb
  spec/services/work_packages/shared/shared_examples_days.rb
  spec/services/work_packages/shared/working_days_spec.rb
  spec/services/work_packages/update_service_integration_spec.rb
  spec/support/table_helpers/table.rb
  spec/support/time_helpers.rb
Labels: bugfix

#18612 [63296] Fix date error when creating parent-child relationship
  app/models/work_package/scheduling_rules.rb
  app/services/work_packages/set_attributes_service.rb
  spec/features/work_packages/table/scheduling/manual_scheduling_spec.rb
  spec/services/work_packages/update_service_integration_spec.rb
  spec/support/components/datepicker/datepicker.rb
  spec/support/components/datepicker/work_package_datepicker.rb
Labels: bugfix

#18613 [62992] Show single date work packages in the calendar
  frontend/src/app/features/calendar/wp-calendar/wp-calendar.component.ts
  modules/calendar/spec/features/calendars_spec.rb
  spec/support/components/work_packages/relations.rb
Labels: bugfix, needs review

#18634 [62754] Document CollapsibleSection
  lookbook/docs/components/collapsible-section.md.erb
  lookbook/previews/patterns/collapsible_section_preview.rb
  lookbook/previews/patterns/collapsible_section_preview/default.html.erb
  lookbook/previews/patterns/collapsible_section_preview/full_example.html.erb
Labels: maintenance

#18641 [63270] Fix example for collapsible Header
  lookbook/previews/op_primer/border_box_component_preview/collapsible.html.erb
Labels: bugfix

#18628 [63014] The "Create meeting" drop down in the Meetings subheader is too wide
  modules/meeting/app/components/meetings/index_sub_header_component.html.erb
Labels: bugfix, needs review

#18597 Update release notes 15.5
  docs/release-notes/15-5-0/README.md
Labels: documentation

#18630 [#62293] PDF export does not export all embedded screenshots
  app/models/work_package/pdf_export/common/attachments.rb
  spec/models/work_packages/pdf_export/work_package_to_pdf_spec.rb
Labels: bugfix

#18643 Increase wait time for custom action title assertion
  spec/features/work_packages/custom_actions/custom_actions_spec.rb
Labels: needs review, flaky-spec

#18644 Bump primer 0.61.1
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: bugfix

#18646 Fix custom action title flaky spec by fetching titles on initialization.
  frontend/src/app/features/work-packages/components/wp-custom-actions/wp-custom-actions/wp-custom-action.component.ts
Labels: needs review

#18632 Ensure we don't try to reschedule meetings that ended up on the same day due to TZ shifts
  modules/meeting/app/services/recurring_meetings/update_service.rb
  modules/meeting/config/locales/en.yml
  modules/meeting/lib/open_project/journal_formatter/meeting_state.rb
Labels: bugfix, needs review

#18660 include video in release notes 15.5
  docs/release-notes/15-5-0/README.md
Labels: documentation

#18659 [63848] Harmonize three dots menus
  app/components/projects/index_page_header_component.html.erb
  app/components/projects/settings/index_page_header_component.html.erb
  frontend/src/app/features/work-packages/components/wp-details/wp-details-toolbar.html
  frontend/src/app/shared/components/icon/icon.module.ts
  lookbook/previews/open_project/common/page_header_preview.rb
  modules/meeting/app/components/recurring_meetings/show_page_header_component.html.erb
  modules/overviews/app/views/overviews/overviews/show.html.erb
Labels: maintenance

#18645 update-open-code-screenshots
  publiccode.yml
  screenshots/opencode_openproject_1_homepage.png
  screenshots/opencode_openproject_2_gantt_chart.png
  screenshots/opencode_openproject_3_work_package_detailed_view.png
  screenshots/opencode_openproject_4_notifications_wp_reminder.png
  screenshots/opencode_openproject_5_meetings.png
  screenshots/opencode_openproject_6_teamplanner.png
  screenshots/opencode_openproject_7_gitlab-integration.png
  screenshots/opencode_openproject_8_sharepoint_integration_details.png
  screenshots/opencode_openproject_9_overview_of_file_storages.png
  screenshots/opencode_openproject_file_storages.png
  screenshots/opencode_openproject_gantt_chart.png
  screenshots/opencode_openproject_gitlab-integration.png
  screenshots/opencode_openproject_homepage.png
  screenshots/opencode_openproject_meetings.png
  screenshots/opencode_openproject_notifications_wp_reminder.png
  screenshots/opencode_openproject_sharepoint_integration_details.png
  screenshots/opencode_openproject_teamplanner.png
  screenshots/opencode_openproject_work_package_detailed_view.png
Labels: documentation

#18547 Fix remaining unit test failures due to frozen string literals
  app/controllers/application_controller.rb
  app/helpers/repositories_helper.rb
  app/models/work_package/journalized.rb
  lib/open_project/scm/adapters/checkout_instructions.rb
  lib/redmine/helpers/diff.rb
  lib/redmine/menu_manager/menu_helper.rb
  modules/reporting/app/controllers/cost_reports_controller.rb
  modules/reporting/lib/widget/base.rb
  modules/reporting/lib/widget/filters/heavy.rb
  spec/lib/api/v3/repositories/revision_representer_spec.rb
  spec/lib/open_project/scm/adapters/git_adapter_spec.rb
  spec/models/mail_handler_spec.rb
  spec/models/repository/git_spec.rb
  spec/models/repository/subversion_spec.rb
Labels: needs review

#18642 [63466] Replace opce-collapsible-section-augment with Primer::CollapsibleSection
  app/views/augmented/_collapsible_section.html.erb
  app/views/enterprises/_form.html.erb
  frontend/src/app/app.module.ts
  frontend/src/app/shared/components/collapsible-section/collapsible-section.component.ts
  frontend/src/app/shared/components/collapsible-section/collapsible-section.html
  frontend/src/app/shared/shared.module.ts
  frontend/src/global_styles/content/_collapsible_section.sass
  frontend/src/global_styles/content/_index.sass
  frontend/src/global_styles/content/modules/_documents.sass
  lookbook/previews/open_project/deprecated/collapsible_section_preview/default.html.erb
  modules/documents/app/views/documents/index.html.erb
  spec/features/admin/enterprise/enterprise_spec.rb
  spec/features/workflows/edit_spec.rb
Labels: maintenance, needs review

#18655 Update structured_warnings gem
  Gemfile
  Gemfile.lock
Labels: needs review

#18680 [62525] Non-working days can be choosen via date field (2)
  frontend/src/stimulus/controllers/dynamic/work-packages/date-picker/preview.controller.ts
  frontend/src/stimulus/controllers/dynamic/work-packages/dialog/preview.controller.ts
  frontend/src/stimulus/controllers/dynamic/work-packages/progress/preview.controller.ts
  spec/features/activities/work_package/activities_spec.rb
  spec/features/work_packages/datepicker/datepicker_non_working_day_spec.rb
  spec/support/components/datepicker/datepicker.rb
  spec/support/components/datepicker/work_package_datepicker.rb
Labels: bugfix, needs review

#18690 Fix calendar styling in dark mode
  modules/costs/app/components/my/time_tracking/calendar_component.sass
Labels: bugfix

#18393 Validate scopes of JWTs
  lib_static/open_project/authentication/strategies/warden/jwt_oidc.rb
  spec/requests/api/v3/authentication_spec.rb
Labels: needs review

#18658 [63434] Fix user with a particular set of permissions seeing errors when updating work packages dates
  app/components/work_packages/date_picker/date_form_component.rb
  app/components/work_packages/date_picker/form_component.rb
  app/controllers/work_packages/date_picker_controller.rb
  config/routes.rb
  frontend/src/app/core/path-helper/path-helper.service.ts
  frontend/src/stimulus/controllers/dynamic/work-packages/date-picker/preview.controller.ts
  frontend/src/stimulus/controllers/dynamic/work-packages/dialog/preview.controller.ts
  frontend/src/stimulus/controllers/dynamic/work-packages/progress/preview.controller.ts
  spec/components/work_packages/date_picker/dialog_content_component_spec.rb
  spec/controllers/work_packages/date_picker_controller_spec.rb
  spec/controllers/work_packages/progress_controller_spec.rb
Labels: bugfix

#18676 [63521] Do nothing if relation to delete does not exist anymore
  app/controllers/work_package_relations_controller.rb
  spec/controllers/work_package_relations_controller_spec.rb
  spec/features/types/form_configuration_query_spec.rb
  spec/support/components/admin/type_configuration_form.rb
Labels: bugfix

#18697 Update Enterprise docs
  docs/enterprise-guide/README.md
Labels: documentation

#18678 Use upsale banner for internal comments
  app/views/projects/settings/work_packages/activities/show.html.erb
  spec/features/projects/settings/work_packages_settings_spec.rb
Labels: pullpreview

#18691 Add medium variant of enterprise banner
  app/assets/images/enterprise/internal-comments.png
  app/components/enterprise_edition/banner_component.html.erb
  app/components/enterprise_edition/banner_component.rb
  app/components/enterprise_edition/banner_component.sass
  app/components/enterprise_edition/upsale_buttons_component.rb
  lookbook/docs/components/enterprise.md.erb
  lookbook/previews/open_project/enterprise_edition/banner_component_preview.rb
Labels: needs review

#18696 minor doc improvements and link fixes
  CHANGELOG.md
  CONTRIBUTING.md
  docs/development/development-environment/README.md
Labels: documentation, contribution

#18679 Bump primer to 0.63.0
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: maintenance

#18707 [#63566] Order of users is not alphabetical in the details tables of PDF time sheet
  modules/reporting/app/workers/cost_query/pdf/timesheet_generator.rb
Labels: tinyfix

#18709 disable autocomplete in time entry form
  modules/costs/app/components/time_entries/time_entry_form_component.rb
Labels: bugfix

#18702 Documentation/63501 add information about the new enterprise plans and how to try them in our enterprise guide
  docs/enterprise-guide/README.md
  docs/enterprise-guide/enterprise-cloud-guide/enterprise-cloud-faq/README.md
  docs/enterprise-guide/enterprise-on-premises-guide/enterprise-on-premises-faq/README.md
  docs/enterprise-guide/enterprise-on-premises-guide/enterprise-on-premises-trial/README.md
Labels: documentation

#18713 Add index for user_id on the sessions table
  db/migrate/20250423123519_add_index_to_sessions.rb
Labels: needs review

#18708 Reload the correct table when adding a new time entry from the list view
  app/controllers/concerns/op_turbo/component_stream.rb
  frontend/src/stimulus/controllers/dynamic/my/time-tracking.controller.ts
  frontend/src/turbo/dialog-stream-action.ts
  frontend/src/turbo/turbo-event-listeners.ts
  lookbook/docs/patterns/05-dialogs.md.erb
  modules/costs/app/components/time_entries/entry_dialog_component.html.erb
  modules/costs/app/controllers/time_entries_controller.rb
Labels: bugfix, needs review

#18719 [#63600] PDF timesheet: Error for TimeEntry with hours set to nil
  modules/reporting/app/workers/cost_query/pdf/timesheet_generator.rb
Labels: bugfix

#18731 Do not try to set invalid duration for deriving due date
  app/contracts/work_packages/base_contract.rb
  app/services/work_packages/set_attributes_service.rb
  spec/services/work_packages/set_attributes_service_spec.rb
  spec/services/work_packages/update_service_integration_spec.rb
Labels: bugfix, needs review

#18737 bug/63637 After clicking on "Make public" once, subsequent "cancel" actions do not retain the "Internal comment" checked state
  frontend/src/stimulus/controllers/dynamic/work-packages/activities-tab/internal-comment.controller.ts
  spec/features/activities/work_package/internal_comments_spec.rb
Labels: bugfix

#18736 Touch up `InternalCommentMentionsSanitizer`
  app/controllers/work_packages/activities_tab_controller.rb
  app/services/work_packages/activities_tab/internal_comment_mentions_sanitizer.rb
  spec/features/activities/work_package/internal_comments_spec.rb
  spec/services/work_packages/activities_tab/internal_comment_mentions_sanitizer_spec.rb
Labels: maintenance

#18723 Use localize together with %A to get localized weekday names
  modules/costs/app/components/my/time_tracking/list_component.rb
Labels: bugfix, needs review

#18747 Bump octicons to 19.25.0
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: maintenance

#18749 Updated MS Project mention in integrations section
  docs/system-admin-guide/integrations/README.md
Labels: documentation

#18730 upgraded misc installation docs for postgres17
  docs/installation-and-operations/misc/migration-to-postgresql17/README.md
Labels: documentation

#18738 adjust width wp select autocomplete on baord view
  frontend/src/app/features/boards/board/inline-add/board-inline-add-autocompleter.sass
  frontend/src/app/shared/components/autocompleter/op-autocompleter/op-autocompleter.component.html
Labels: bugfix

#18763 update system guide (create new work package status page)
  docs/system-admin-guide/manage-work-packages/work-package-status/README.md
Labels: documentation

#18760 Merge release/15.5 into dev
  app/contracts/work_packages/base_contract.rb
  app/models/work_packages/relations.rb
  app/services/work_packages/set_attributes_service.rb
  config/locales/crowdin/af.yml
  config/locales/crowdin/ar.yml
  config/locales/crowdin/az.yml
  config/locales/crowdin/be.yml
  config/locales/crowdin/bg.yml
  docs/system-admin-guide/integrations/README.md
  docs/user-guide/work-packages/work-package-table-configuration/README.md
  modules/meeting/app/menus/meetings/menu.rb
  modules/meeting/config/locales/crowdin/et.yml
  modules/team_planner/config/locales/crowdin/da.yml
  spec/models/relations/scopes/visible_spec.rb
  spec/services/work_packages/set_attributes_service_spec.rb
  spec/services/work_packages/update_service_integration_spec.rb
Labels: create-merge-release-into-dev-pr

#18732 Soft-deprecate postgres < 16
  app/views/admin/info.html.erb
  config/static_links.yml
  lib_static/open_project/database.rb
Labels: maintenance, needs review

#18757 fix sql alias when ordering&sorting by same table
  app/models/custom_field/order_statements.rb
  spec/models/query/results_sort_and_group_integration_spec.rb
Labels: needs review

#18766 [#63676] Use a boolean instead of CSS classes to check state for the collapsible header in meetings stimulus controllers
  frontend/src/stimulus/helpers/collapsible-helper.ts
  modules/meeting/spec/support/pages/meetings/show.rb
Labels: maintenance, needs review

#18768 [62604] Marking a notification as read automatically selects the first notification
  frontend/src/app/features/in-app-notifications/center/state/ian-center.service.ts
Labels: bugfix, needs review

#18198 Prepare nextcloud storage docs for new authentication method
  docs/system-admin-guide/integrations/nextcloud/README.md
  docs/system-admin-guide/integrations/nextcloud/oidc-sso/README.md
  docs/system-admin-guide/integrations/nextcloud/oidc-sso/keycloak_audience_mapper.png
  docs/system-admin-guide/integrations/nextcloud/oidc-sso/keycloak_client_with_scope.png
  docs/system-admin-guide/integrations/nextcloud/oidc-sso/keycloak_empty_policies.png
  docs/system-admin-guide/integrations/nextcloud/oidc-sso/keycloak_exchange_permission.png
  docs/system-admin-guide/integrations/nextcloud/oidc-sso/keycloak_exchange_policy.png
  docs/system-admin-guide/integrations/nextcloud/oidc-sso/keycloak_features.png
  docs/system-admin-guide/integrations/nextcloud/oidc-sso/keycloak_new_client_scope.png
  docs/system-admin-guide/integrations/nextcloud/oidc-sso/nextcloud_hub_configuration.png
  docs/system-admin-guide/integrations/nextcloud/oidc-sso/nextcloud_manual_storage_audience.png
  docs/system-admin-guide/integrations/nextcloud/oidc-sso/nextcloud_using_login_token.png
  docs/system-admin-guide/integrations/nextcloud/oidc-sso/openproject_idp_storage_audience.png
  docs/system-admin-guide/integrations/nextcloud/oidc-sso/openproject_manual_storage_audience.png
  docs/system-admin-guide/integrations/nextcloud/two-way-oauth2/README.md
  docs/system-admin-guide/integrations/nextcloud/two-way-oauth2/two_way_oauth2_setup_step_1.png
  docs/system-admin-guide/integrations/nextcloud/two-way-oauth2/two_way_oauth2_setup_step_2.png
  docs/system-admin-guide/integrations/nextcloud/two-way-oauth2/two_way_oauth2_setup_step_3.png
  docs/system-admin-guide/integrations/nextcloud/two-way-oauth2/two_way_oauth2_setup_step_4.png
Labels: documentation

#18764 Fix wrong calculation for time entries without start&end times
  frontend/src/stimulus/controllers/dynamic/my/time-tracking.controller.ts
  modules/costs/app/controllers/time_entries_controller.rb
Labels: bugfix, needs review

#18734 Primerize authentication settings page
  app/components/types/edit_page_header_component.html.erb
  app/forms/application_form.rb
  app/forms/settings/form_decorator.rb
  app/forms/settings/form_helper.rb
  app/forms/settings/multi_lang_form.rb
  app/forms/settings_form_decorator.rb
  app/helpers/tabs_helper.rb
  app/models/setting/self_registration.rb
  app/views/admin/settings/authentication_settings/_login.html.erb
  app/views/admin/settings/authentication_settings/_passwords.html.erb
  app/views/admin/settings/authentication_settings/_registration.html.erb
  app/views/admin/settings/authentication_settings/show.html.erb
  app/views/common/_tabs.html.erb
  config/constants/settings/definition.rb
  config/initializers/menus.rb
  config/locales/en.yml
  config/static_links.yml
  frontend/src/app/core/setup/globals/global-listeners/settings.ts
  frontend/src/app/shared/components/editor/components/ckeditor-augmented-textarea/ckeditor-augmented-textarea.component.ts
  lib/open_project/passwords.rb
  lib/open_project/text_formatting/formats/markdown/helper.rb
  lib/primer/open_project/forms/rich_text_area.html.erb
  lib/primer/open_project/forms/rich_text_area.rb
  lookbook/docs/patterns/02-forms.md.erb
  spec/components/projects/settings/general/show_component_spec.rb
  spec/features/users/password_change_spec.rb
  spec/forms/projects/settings/description_form_spec.rb
  spec/forms/projects/settings/status_form_spec.rb
  spec/requests/admin/settings/authentication_settings_spec.rb
  spec/support/form_fields/primerized/editor_form_field.rb
  spec/support/pages/admin/system_settings/general.rb
Labels: feature

#18777 add IMAP_NO_PERMISSION_CHECK variable to inbound mail docs
  docs/installation-and-operations/configuration/incoming-emails/README.md
Labels: documentation, needs review

#18784 Fixes for my time tracking calendar regarding to timezones
  frontend/package-lock.json
  frontend/package.json
  frontend/src/stimulus/controllers/dynamic/my/time-tracking.controller.ts
  modules/costs/app/components/my/time_tracking/calendar_component.rb
Labels: bugfix
